gText_ApprenticeChallenge0::
	.string "{JPN}あの… わたし {STR_VAR_1}の {STR_VAR_2}ばんめの でしです。\nぐすん… きんちょうして きました…$"

gText_ApprenticeChallenge1::
	.string "{JPN}わたしは {STR_VAR_1}の {STR_VAR_2}ばんめの でし!\nいきますよ!$"

gText_ApprenticeChallenge2::
	.string "{JPN}おれは {STR_VAR_1}の {STR_VAR_2}ばんめの でしだ!\nしょうぶを うけて もらうぜ!$"

gText_ApprenticeChallenge3::
	.string "{JPN}あの… {STR_VAR_1}の {STR_VAR_2}ばんめの でしです…\nわたしでも かてると おもいますか?$"

gText_ApprenticeChallenge4::
	.string "{JPN}ぼくは {STR_VAR_1}の {STR_VAR_2}ばんめの でし!\nしょうぶ させて あげるよ!$"

gText_ApprenticeChallenge5::
	.string "{JPN}いそがしいんだけど おれは\n{STR_VAR_1}の {STR_VAR_2}ばんめの でしなんだ。$"

gText_ApprenticeChallenge6::
	.string "{JPN}わたしは {STR_VAR_1}の {STR_VAR_2}ばんめの でし。\nよろしく おねがいします!$"

gText_ApprenticeChallenge7::
	.string "{JPN}わたくしは {STR_VAR_1}の {STR_VAR_2}ばんめの でし。\nはじめても よろしいですか?$"

gText_ApprenticeChallenge8::
	.string "{JPN}ひえっ! わたし {STR_VAR_1}の {STR_VAR_2}ばんめの でし!\nがんばります!$"

gText_ApprenticeChallenge9::
	.string "{JPN}いよっ! おれは {STR_VAR_1}の {STR_VAR_2}ばんめの でし!\nかかって きな!$"

gText_ApprenticeChallenge10::
	.string "{JPN}おれは {STR_VAR_1}の 1000ばんめの でし!\nうそ ほんとは {STR_VAR_2}ばんめ! いくぜ!$"

gText_ApprenticeChallenge11::
	.string "{JPN}そうさ おれは {STR_VAR_1}の {STR_VAR_2}ばんめの でし!\nノリノリで いこうぜ!$"

gText_ApprenticeChallenge12::
	.string "{JPN}イエーイ! おれさまこそ\n{STR_VAR_1}の {STR_VAR_2}ばんめの でしよ!$"

gText_ApprenticeChallenge13::
	.string "{JPN}ゴホッ! おれは {STR_VAR_1}の {STR_VAR_2}ばんめの でし。\nよろしくな! ゴホッ!$"

gText_ApprenticeChallenge14::
	.string "{JPN}きんちょう しますね…\nわたしは {STR_VAR_1}の {STR_VAR_2}ばんめの でし。$"

gText_ApprenticeChallenge15::
	.string "{JPN}わたしは {STR_VAR_1}の {STR_VAR_2}ばんめの でし。\nうそでは ありません。$"

gText_ApprenticePleaseTeach0::
	.string "{JPN}あなたが… {PLAYER}さん?\nあっ ぐすっ… えぐっ…\pご ごめんなさい…\nきんちょうして なみだが とまらなくて…\pわたし {STR_VAR_1}です。\n{PLAYER}さんに ずっと あこがれて いました。\pいつか あなたに あって ポケモンの ことを\nおしえて もらうのが ゆめ だったんです。\pおねがいします {PLAYER}さん!\nポケモンの ことを おしえて ください!$"

gText_ApprenticeRejectTeaching0::
	.string "{JPN}そんな… で でも…\nぐすっ… うわあああん!\pおねがい!\nおねがいします どうか!$"

gText_ApprenticeWhichLevelMode0::
	.string "{JPN}ほんとうですか? いいんですか?\nすごい! やった! わあい!\pあっ ごめんなさい…\nうれしくて ないちゃった…\pあの… では おしえて ください!\nバトルタワーの ことです。\pわたしには レベル50と オープンレベル\nどちらが いいでしょうか?$"

gText_ApprenticeLevelModeThanks0::
	.string "{JPN}{STR_VAR_1}?\nうわああん!\pあっ ごめんなさい!\nレベルを きめて もらえたのが\lうれしくて ないちゃったんです…\pぐすっ…\nほんとうに ありがとう ございます!\lまた おはなし させて ください!$"

gText_ApprenticePleaseTeach1::
	.string "{JPN}わあ! {PLAYER}さん ですよね?\nすっごく つよいんですよね?\pぼく {STR_VAR_1}!\nトレーナーに なったばかりなんだ!\pおねがい {PLAYER}さん!\nぼくの せんせいに なって トレーナーの\lことを たくさん おしえて くれない?$"

gText_ApprenticeRejectTeaching1::
	.string "{JPN}ええー どうして?\nねえ おねがい おねがいだよ?\lせんせいに なって おねがい!$"

gText_ApprenticeWhichLevelMode1::
	.string "{JPN}やった! うれしい!\pさいしょに ききたいのは\nバトルタワーの ことなんだ!\pレベル50と オープンレベル…\nぼくには どっちが ぴったりかな?$"

gText_ApprenticeLevelModeThanks1::
	.string "{JPN}{STR_VAR_1}か! たしかに!\nそこで がんばって みるよ!\pまた ここで あったら べつの ことも\nおしえて ね せんせい!$"

gText_ApprenticePleaseTeach2::
	.string "{JPN}あの… {PLAYER}さん ですか?\nわたしは {STR_VAR_1}と いいます。\pポケモントレーナーに なりたいのですが\nどうすれば いいのか わからなくて…\pゆうめいな あなたなら アドバイスを\nいただけるかと おもいまして。\p{PLAYER}さん おしえて いただけませんか?$"

gText_ApprenticeRejectTeaching2::
	.string "{JPN}そんな…\pわたしは ほんきで ポケモントレーナーに\nなりたいのです!\pおねがいです しつもんに こたえて ください!$"

gText_ApprenticeWhichLevelMode2::
	.string "{JPN}ありがとう ございます!\nさっそく さいしょの しつもんです!\pバトルタワーには レベル50と\nオープンレベルが ありますよね?\pわたしには どちらが むいて いると\nおもいますか?$"

gText_ApprenticeLevelModeThanks2::
	.string "{JPN}{STR_VAR_1}ですね?\nわかりました!\pまた しつもんが できたら ここへ\nアドバイスを もらいに きます!$"

gText_ApprenticePleaseTeach3::
	.string "{JPN}えっ? あっ あなたは…\nいえ そんな はずは…\pぼくなんかが {PLAYER}さんに\nあえる わけが ないんです。\p…ほんとうに {PLAYER}さん?\nおはなし できるなんて しんじられない!\pこんな いい ことが あったら\nこのあと きっと ひどい ことが\lおきるに きまって いるんです…\p…すみません…\nぼくは… {STR_VAR_1}と いいます…\pじまんできる ところなんて\nなにも ない ぼくですが…\pどうせ わすれられるので じぶんの ことは\nはなさない ほうが いいですね…\pもし {PLAYER}さんに あえたら トレーナーとして\nアドバイスを もらえないかと\lゆめに みて いたんです。\pでも そんな こと ひきうけては\nくれませんよね。\p…それとも アドバイスを\nいただけるのでしょうか?$"

gText_ApprenticeRejectTeaching3::
	.string "{JPN}やっぱり…\pぼくなんて つまらない にんげんだから\nとうぜんですよね…\pでも もしかしたらと おもって…\nかんがえなおしては くれませんよね?\pでも まだ あきらめられません。\nうんが ある うちに おねがいします!\pどうか アドバイスを\nいただけないでしょうか?$"

gText_ApprenticeWhichLevelMode3::
	.string "{JPN}ほんとうですか? しんじられない!\nアドバイスを もらえるなんて!\lぼく… とても うれしいです…\pききたいのは ほんとうに ささいな ことで\nでも きめられなくて…\pバトルタワーでは レベル50か\nオープンレベルを えらべますよね。\pぼくでも チャンスが ありそうなのは\nどちらだと おもいますか?$"

gText_ApprenticeLevelModeThanks3::
	.string "{JPN}{STR_VAR_1}ですね わかりました!\nでも ぼくなんかに ほんとうに\lチャンスが あるでしょうか?\pうまく いくとは おもえませんが\nがんばって みます。\pぼくなんかに じかんを つかって\nくださって ありがとう ございました。$"

gText_ApprenticePleaseTeach4::
	.string "{JPN}あら! {PLAYER}{KUN}でしょ?\pポケモンが つよいって\nきいて いるわよ!\pわたしは {STR_VAR_1}!\nともだちに なって あげる!\pしって いる?\pトレーナーズスクールで ならう ことだけじゃ\nバトルフロンティアでは\lかてないのよ。\pアドバイスを きいて あげても いいわ。\nもちろん いいわよね?$"

gText_ApprenticeRejectTeaching4::
	.string "{JPN}えっ どうして ことわるの?\nこっちが たのんで あげてるのよ!\lかんがえなおしなさい!$"

gText_ApprenticeWhichLevelMode4::
	.string "{JPN}きめて ほしい ことが あるの。\nかわりに きめて ちょうだい。\pバトルタワーには レベル50と\nオープンレベルが あるでしょ?\p{PLAYER}{KUN} わたしには\nどっちが いいと おもう?$"

gText_ApprenticeLevelModeThanks4::
	.string "{JPN}{STR_VAR_1}が わたしに むいて いるのね?\nありがとう!\p{PLAYER}{KUN}が きめて くれたのなら\nまけても そんなに くやしく\lないと おもうわ。\pじゃあ また アドバイスを もらいに くるわ。\nまたね!$"

gText_ApprenticePleaseTeach5::
	.string "{JPN}やあ! {PLAYER}{KUN}!\nゆうめいだから しって いるよ!\lおれは {STR_VAR_1} よろしくな!\pトライアスリートだから ポケモンを そだてながら\nからだも きたえて いるんだ。\pしごとに ひるねに しゃこうダンス\nほかにも いろいろ やって いてね…\pこんなに いそがしいと まともな トレーナーに\nなるのは かんたんじゃ ないんだ。\pそこで ていあんが ある!\pであったのも なにかの えんだ。\n{PLAYER}{KUN} ときどき その ちえを\lおれに わけて くれないか?$"

gText_ApprenticeRejectTeaching5::
	.string "{JPN}そこを なんとか たのむよ!\nおれみたいな やつには {PLAYER}{KUN}みたいな\lひとが ひつようなんだ!\pほんとうに アドバイスが ほしいんだ!$"

gText_ApprenticeWhichLevelMode5::
	.string "{JPN}ありがとう! そうこなくちゃ!\nじゃあ かんたんな ことから!\pバトルタワーには ふたつの コースが\nあるのは しって いるよな?\lレベル50と オープンレベルだ。\pいそがしい おれは どっちに\nそなえれば いいと おもう?$"

gText_ApprenticeLevelModeThanks5::
	.string "{JPN}{STR_VAR_1}か わかった。\nなんとか じかんを つくって いって みるよ!\p…おっと しごとに いかなきゃ!\nありがとう! またな!$"

gText_ApprenticePleaseTeach6::
	.string "{JPN}うそ! まさか!\nほんものの {PLAYER}さん?\pわあ すごい! わたし {STR_VAR_1}!\nおあいできて うれしい!\p{PLAYER}さんって とっても\nつよいんですよね?\pみんなが うわさして いますよ!\pあっ いい ことを おもいついた!\n{PLAYER}さんに アドバイスを もらうの!\lきっと つよく なれる はずだわ!\pすてきな かんがえでしょ?\nおねがい アドバイスが ほしいの!$"

gText_ApprenticeRejectTeaching6::
	.string "{JPN}アハハ いじわるな ふりを しても\nわたしには わかるんだから!\lほんとうは いいよって いうんでしょ?$"

gText_ApprenticeWhichLevelMode6::
	.string "{JPN}やった! {PLAYER}さんは こころが\nひろいと おもって いたの!\pまず なにを きこうかな?\n…あっ おもいついた!\pドラムロール おねがい!\nわたしの しつもんは…\pバトルタワーに ちょうせん するなら\nどっちに いけば いいのかしら?\pレベル50と オープンレベル\nわたしには どっちが むいて いる?$"

gText_ApprenticeLevelModeThanks6::
	.string "{JPN}おおお!\n{STR_VAR_1}って いうのね!\lすっごく クールな こたえ ありがとう!\pきょう ききたかったのは\nそれくらいかな。\pまた ここで あいましょうね?\nありがとう!$"

gText_ApprenticePleaseTeach7::
	.string "{JPN}しつれいですが…\n{PLAYER}さん ですか?\pわたくしは {STR_VAR_1}と もうします。\nおめに かかれて こうえいです。\pずっと あなたを おしたい\nもうして おりました…\p… … … … … …\pあの… ごめいわくで なければ\nおねがいが あるのですが…\pわたくしを おでしに して\nいただけませんか {PLAYER}さん?$"

gText_ApprenticeRejectTeaching7::
	.string "{JPN}ああっ…!\p… … … … … …\n… … … … … …\p…おどろきの あまり きを うしなって いました。\nききまちがえたようで もうしわけ ありません。\pどうか! どうか おでしにすると\nおっしゃって ください!$"

gText_ApprenticeWhichLevelMode7::
	.string "{JPN}ああ うれしゅう ございます!\pおじかんを むだに したく ないので\nさっそく おしえて ください。\pちかいうちに バトルタワーに\nちょうせん する つもりです。\pですが レベルが ふたつ あって…\pわたくしには どちらが よいでしょう?\nレベル50と オープンレベル。$"

gText_ApprenticeLevelModeThanks7::
	.string "{JPN}{STR_VAR_1}ですね!\nわかりました がんばります!\pありがとう ございます {PLAYER}さん。\nまた たよらせて いただきます。\lどうぞ おげんきで!$"

gText_ApprenticePleaseTeach8::
	.string "{JPN}ひゃっ ひゃっ {PLAYER}さん!\nはなしかけて くれた!\lわ… わたし かんげきです!\pわたし! なまえは {STR_VAR_1}!\nトレーナーに なったばかりです!\pポケモンかいの ゆうめいじん {PLAYER}さんに\nあえるなんて うれしいです!\pああ そうだ!\nおおきな おねがいが あるんです {PLAYER}さん!\pわたしを おでしに して ください!\nあなたから まなびたいんです!$"

gText_ApprenticeRejectTeaching8::
	.string "{JPN}うわああん!\n{PLAYER}さんに ことわられた…\lこ これも きちょうな けいけん!\p{PLAYER}さん おねがい! こんどこそ\nはいと いって ほしいんです!\pどうか ごしどうを おねがいします!$"

gText_ApprenticeWhichLevelMode8::
	.string "{JPN}ひえええ! {PLAYER}さんが はいって!\n{PLAYER}さんが いって くれた!\pこんや ねむれそうに ありません…\nほんとうに ありがとう ございます!\pでは しつもんです!\pバトルタワーでは レベル50と\nオープンレベル どちらが いいですか?$"

gText_ApprenticeLevelModeThanks8::
	.string "{JPN}{STR_VAR_1}! かんぺきに わかりました!\nかんぜんに りかいしました!\lうれしくて どうにか なりそうです!\pまた こんど べつの ことも\nおしえて いただけると うれしいです。$"

gText_ApprenticePleaseTeach9::
	.string "{JPN}おっと もしかして…\nあなた… {PLAYER}{KUN}?!\lつよくて ゆうめいな トレーナーの?\lいやあ おれって ついてるなあ!\pどうも おれは {STR_VAR_1}!\pポケモンの ししょうを\nさがして いたんだ。\pそこへ ちょうど いい タイミングで\n{PLAYER}{KUN}が あらわれた!\pという わけだ {PLAYER}{KUN}!\nおれを でしに して くれ!$"

gText_ApprenticeRejectTeaching9::
	.string "{JPN}ぐわあああ!\nつれないし つよいし…\pそう いわずに たのむよ。\nおねがいだ!$"

gText_ApprenticeWhichLevelMode9::
	.string "{JPN}よっしゃ! いい へんじだ!\nさいこうだね!\pじゃあ さっそく バトルタワーの\nアドバイスを もらえるかな?\pいくなら どっちが いいと おもう?\nレベル50か オープンレベルか。$"

gText_ApprenticeLevelModeThanks9::
	.string "{JPN}なるほど {STR_VAR_1}だな!\nオーケー オーケー!\lどんと ちからを みせて くるぜ!\pよし あんたを ししょうと あおぐぜ!\nアディオス!$"

gText_ApprenticePleaseTeach10::
	.string "{JPN}おや {PLAYER}{KUN}だろ?\nけいさつが さがして いたぞ!\p… … …\nもちろん うそだけどな!\pおれは {STR_VAR_1}。こう みえて\nポケモンリーグ チャンピオンさ!\l…これも うそだけどな!\pでも これは うそじゃ ない。\nおれは バトルが とくいじゃ ないんだ。\pそこで ポケモンの ことを おしえる\nししょうに なって くれないか?$"

gText_ApprenticeRejectTeaching10::
	.string "{JPN}そんな つめたい たいどを とるなら\nこっちにも かんがえが あるぞ!\pうわーん! うわーん! うわーん!\nヒック!\pハハハ いまのは いたみわけ… なんてな!\pたのむよ ポケモンの ししょうに\nなって くれないか?$"

gText_ApprenticeWhichLevelMode10::
	.string "{JPN}やったー!\nおれいに ふねを かって やる!\pもちろん また うそだけどな!\nでも… ありがとう ししょう!\pバトルタワーには レベル50と\nオープンレベルが あるだろ?\pどっちに ちょうせん するか\nなやんで いるんだ…\pししょう かわりに きめて くれよ?$"

gText_ApprenticeLevelModeThanks10::
	.string "{JPN}なるほど {STR_VAR_1}が いいのか!\nじゃあ もう ひとつの ほうに いくぜ!\pなんてな!\nししょうの おしえに したがうよ!\pありがとう ししょう!\nこれからも おしえて くれよな!$"

gText_ApprenticePleaseTeach11::
	.string "{JPN}ア ホ ー イ!\nつづりは あほい いみは やあ だぜ!\pおれは {STR_VAR_1} ラップする\nフネのりさ!\pつぎは そっちの ばん じぶんの ことを\nちょっと きかせて みな!\pふむふむ なるほど!\n{PLAYER}{KUN}って なまえで\lポケモンが とくいと きた!\pせかいが ぜんぶ ぶたいに みえる\nびみょうな おとしごろって わけだ!\pところで ひとこと いいたい ことが ある。\nきょう はなした トレーナーの なかで\lあんたが 10にんめなのさ。\pこれは おいわい ものだぜ!\nきねんに おれの ししょうに なって くれ!$"

gText_ApprenticeRejectTeaching11::
	.string "{JPN}だがな!\nつきあって もらうぜ!\pじらさないで くれよ!\nししょうに なって おくれよ!$"

gText_ApprenticeWhichLevelMode11::
	.string "{JPN}そう こなくちゃ!\n{PLAYER} こんじょうが あるねえ!\pじゃあ さっそく さいしょの しつもん\nこたえを きかせて ちょうだい!\pバトルタワーの ことなんだが\nおれの ちからに かかわる はなしさ!\pレベル50と オープンレベル\nおれに あうのは どっちだい?$"

gText_ApprenticeLevelModeThanks11::
	.string "{JPN}なるほど {STR_VAR_1}だってな!\nさっそく いって みるとしよう!\pアドバイスが ほしい ときは\n{PLAYER}の ことばに したがうぜ!$"

gText_ApprenticePleaseTeach12::
	.string "{JPN}やあ あんた {PLAYER}だろ?\nどうしよう はなしかけようか?\lなんてな もう はなしかけて るぜ!\p{PLAYER} おどろいて いるかい?\nおれが だれか おしえて やろう!\p{STR_VAR_1}と よんで くれ。\nギターかいで いちばん かがやく ほし\lそれが おれさ!\pきこえて いるかい?\nきこえて いるよな!\pきょうは ついてるぜ\nひとつ おねがいが あるんだ!\p{PLAYER} おれを こぶんに して くれ!\nぜんぶ おしえて ほしいんだ!$"

gText_ApprenticeRejectTeaching12::
	.string "{JPN}ことわるって いうのかい?\nなら もういちど たのむしか ないな!\p{PLAYER} こぶんに して くれよ!\nぜんぶ おしえて ほしいんだ!$"

gText_ApprenticeWhichLevelMode12::
	.string "{JPN}ラッキー イエー フー!\nひとつ しつもん しても いいかい?\pバトルタワーの ちかくだしな\nタワーの ことを きいても いいかな?\pならんで いる えらびかたの なかで\nおれに あうのは どれだい?$"

gText_ApprenticeLevelModeThanks12::
	.string "{JPN}{STR_VAR_1}が いいって いうのなら\nそれが いちばんに ちがいない!\pじゃあ {PLAYER} おれは たびを つづける\nでも おれの ことを わすれないでくれ。\pまた あおうぜ かしこい ともだち!$"

gText_ApprenticePleaseTeach13::
	.string "{JPN}おっ そこの きみ!\nかたを もんで くれないか?\p…そう そこだ! そこ!\nいたた! おお きくぞ!\pおれの なまえは {STR_VAR_1}。\nからてを やって いるが からだが\lもたなくてな…\pポケモンで バトルして からだを\nきたえなおす ことに したんだ。\pきみ {PLAYER}{KUN}だろ?\nポケモンリーグの チャンピオンの?\pなあ おれに アドバイスを\nくれないか?$"

gText_ApprenticeRejectTeaching13::
	.string "{JPN}なぜ だめなんだ?\pめいわくは かけないと やくそくする!\nたのむよ?$"

gText_ApprenticeWhichLevelMode13::
	.string "{JPN}ありがとう ありがたいぜ!\n…ゴホッ! ゴホッ!\pうう はやく からだを きたえないと…\pさっそく バトルタワーへ いくが おれには\nどっちが いいと おもう?\lレベル50か オープンレベルか。$"

gText_ApprenticeLevelModeThanks13::
	.string "{JPN}ふむ わかった {STR_VAR_1}だな。\nさっそく いって みるよ。\pこれからも たよらせて くれよな。\nなにしろ きみは おれの ししょうだ!$"

gText_ApprenticePleaseTeach14::
	.string "{JPN}あの… その…\n{PLAYER}{KUN}…?\pおねがい そんなに みないで。\nはずかしく なって しまいます。\pわ わたしは {STR_VAR_1}です。\pはずかしい はなしですが\nこだいの いせきなどを しらべて います。\pもっと はずかしい ことに\nバトルフロンティアにも きょうみが あって。\p{PLAYER}{KUN}は つよい トレーナーだと\nひょうばんですよね…\pいいにくいのですが\nおねがいが あるんです。\pわたしの せんせいに なって\nアドバイスを いただけませんか?$"

gText_ApprenticeRejectTeaching14::
	.string "{JPN}そんなに つれなく しないで ください!\nはずかしくて いきて いけません。\pどうか せんせいに なって!\nアドバイスが ひつようなんです!$"

gText_ApprenticeWhichLevelMode14::
	.string "{JPN}あ ありがとう ございます…\pでも そんなに みつめないで ください。\nどぎまぎ して しまいます。\pどうか めを みないで\nこたえて ください。\pバトルタワーでは…\nどちらの レベルに いどむべきでしょう?$"

gText_ApprenticeLevelModeThanks14::
	.string "{JPN}あ… はい!\nそれに ちょうせん して みます。\pどぎまぎ しないで りっぱに\nたたかえると いいのですが…\pありがとう ございます {PLAYER}{KUN}。\nまた あえたら そのときも\lたよりに させて ください。$"

gText_ApprenticePleaseTeach15::
	.string "{JPN}ふむ? {PLAYER}{KUN}の ようですが…\nほんとうに ほんものですか?\pわたしは {STR_VAR_1}と および ください。\pつよい トレーナーの もとで でしいり しようかと\nかんがえて いた ところでして。\pいや あなたが きて くれて ついて います!\n…ほんとうに {PLAYER}{KUN} ですよね?\pいや ほんものなら それで けっこう。\nわたしを でしとして みとめて\lいただきたいだけですから。$"

gText_ApprenticeRejectTeaching15::
	.string "{JPN}おや?\nなぜ おことわりに なるのです?\pほんものか うたがった ことは\nおわび いたします。\pどうか おゆるし いただき\nでしとして みとめて ください。$"

gText_ApprenticeWhichLevelMode15::
	.string "{JPN}ほんとうに みとめて くださるので?\nぬか よろこびは したく ないのですが。\pほんとうなら しつれい しました。\nでは さっそく アドバイスを。\pバトルタワーに はいるなら\nわたしに ふさわしいのは どちらでしょう?\lレベル50か オープンレベルか。$"

gText_ApprenticeLevelModeThanks15::
	.string "{JPN}{STR_VAR_1}?\nまちがい ありませんか?\pなるほど そう いう ことでしたら けっこう。\nおじかんを いただき ありがとう ございます。\pわたしは めんどうな おとこですが\nみとめて いただけて うれしいのです。\pまた おあい しましょう!$"

gText_ApprenticeWhatHeldItem0::
	.string "{JPN}ぐすっ… えぐっ…\nああ {PLAYER}さん!\pどうしても きめられなくて\nなやんで いるんです。\pわたしの {STR_VAR_1}に なにを\nもたせれば いいのか きめられなくて。\pおしえて ください {PLAYER}さん。\nどの どうぐを もたせれば いいですか?$"

gText_ApprenticeHoldNothing0::
	.string "{JPN}えっ ほんとうですか? {STR_VAR_1}には\nなにも もたせなくて いいんですか?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "{JPN}わかりました! きまって うれしい!\nすごい! やった! わあい!\pほんとうに ありがとう ございます!$"

gText_ApprenticeThanksHeldItem0::
	.string "{JPN}ああ よかった…\n{STR_VAR_1}なら わたしも もって います。\pきまって うれしい!\nすごい! やった! わあい!\pほんとうに ありがとう ございます!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "{JPN}うわああん! いじわる しないで!\p{STR_VAR_1}は まえにも\nおすすめされました ぐすっ…\pそれとも {STR_VAR_2}には なにも\nもたせるなと いう ことですか?$"

gText_ApprenticeWhatHeldItem1::
	.string "{JPN}やった! {PLAYER}さんだ!\nよかった ききたい ことが あったんだ!\pポケモンに どうぐを もたせて いる?\nぼくも もたせたいんだけど…\p{STR_VAR_1}には どんな どうぐが\nいいと おもう?\pどう おもう?$"

gText_ApprenticeHoldNothing1::
	.string "{JPN}えっ? ぼくの {STR_VAR_1}には\nなにも もたせなくて いいの?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "{JPN}わかった! そうするよ!\nおしえて くれて ありがとう!$"

gText_ApprenticeThanksHeldItem1::
	.string "{JPN}わあ {STR_VAR_1}だね?\nうん そうするよ!\pおしえて くれて ありがとう!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "{JPN}ううん そういう ことじゃ なくて。\nもう しって いる どうぐとは べつの\lものを ききたいんだ。\pそれとも こんかいは なにも\nもたせなくて いいって こと?$"

gText_ApprenticeWhatHeldItem2::
	.string "{JPN}{PLAYER}さん こんにちは!\nわたしの {STR_VAR_1}の ことですが…\pいい どうぐを もたせたいんです。\nなにが いいと おもいますか?$"

gText_ApprenticeHoldNothing2::
	.string "{JPN}では {STR_VAR_1}には なにも\nもたせなくて いいのですね?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "{JPN}わかりました!\nまた あいましょう!$"

gText_ApprenticeThanksHeldItem2::
	.string "{JPN}{STR_VAR_1}ですね?\nわかりました!\pがんばって さがして みます!\nまた あいましょう!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "{JPN}{STR_VAR_1}なら もう\nおしえて もらいました。\pべつの しゅるいの どうぐを\nもたせたいのです。\pそれとも {STR_VAR_2}には なにも\nもたせなくて いいと おもいますか?$"

gText_ApprenticeWhatHeldItem3::
	.string "{JPN}こんにちは {PLAYER}さん…\nおじゃまして すみませんが もうひとつ\lききたい ことが あるんです。\pじぶんの ちからだけでは かてそうに ないので\n{STR_VAR_1}に どうぐを もたせようかと\lおもって いるんです。\pでも なにが いいのか わからなくて。\p{PLAYER}さん おねがいします\nきめて いただけませんか?$"

gText_ApprenticeHoldNothing3::
	.string "{JPN}ぼくみたいな ものの ポケモンは\nなにも もたない ほうが いいのですか?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "{JPN}わかりました…\nどうぐに たよるなと いう ことですね。\lたよらない ように がんばります!\pほんとうに ありがとう ございました!$"

gText_ApprenticeThanksHeldItem3::
	.string "{JPN}{STR_VAR_1}ですね。\nてに はいるか わかりませんが…\lいえ! がんばって さがします。\pほんとうに ありがとう ございました!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "{JPN}でも…\nそれは まえにも きいた ような…\pわたしが {STR_VAR_1}を うまく\nつかえて いないからでしょうか?\pそれとも {STR_VAR_2}には なにも\nもたせるなと いう ことですか?$"

gText_ApprenticeWhatHeldItem4::
	.string "{JPN}ねえ {PLAYER}{KUN}。\nききたい ことが あるの。\pわたしが どの ポケモンを つかうか\nきめて くれたでしょ?\pでも どうぐの ことは\nきいて いなかったわ。\pアドバイスを くれたんだから\nさいごまで つきあって くれる?\pなにが いいかしら? {STR_VAR_1}に\nなにか もたせたいの。$"

gText_ApprenticeHoldNothing4::
	.string "{JPN}あら! {STR_VAR_1}は てぶらで\nがんばれって こと?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "{JPN}それが いちばんなら そうするわ。\p{PLAYER}{KUN}が きめて くれたのなら\nまけても そんなに くやしく\lないと おもうわ。\pじゃあ また アドバイスを もらいに くるわ。\nまたね!$"

gText_ApprenticeThanksHeldItem4::
	.string "{JPN}{STR_VAR_1}ね?\nわるく ないわ つかって みる!\p{PLAYER}{KUN}が きめて くれたのなら\nまけても そんなに くやしく\lないと おもうわ。\pじゃあ また アドバイスを もらいに くるわ。\nまたね!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "{JPN}えっ なにを いって いるの?\n{STR_VAR_1}は まえにも\lおしえて くれたでしょ。\pそれとも {STR_VAR_2}は てぶらで\nがんばれって こと?$"

gText_ApprenticeWhatHeldItem5::
	.string "{JPN}よう {PLAYER}{KUN}!\pおたがい いそがしいのに よく\nかおを あわせるもんだな!\pきょうは あるいて そうじして\nブラッシングも しなきゃ ならん。\pだいじな {STR_VAR_1}に なにか\nかって やる ひまも なくてね。\pじかんが ないんだ {STR_VAR_1}に\nなにを もたせれば いいか\lアドバイスを くれないか?$"

gText_ApprenticeHoldNothing5::
	.string "{JPN}いそがしい おれの {STR_VAR_1}には\nなにも いらないって ことか?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "{JPN}よし わかった。\nそれなら じかんも いらないな。\pきょうは ありがとう!\nまたな!$"

gText_ApprenticeThanksHeldItem5::
	.string "{JPN}よし わかった。\nなんとか じかんを つくって\lおすすめの {STR_VAR_1}を さがすよ。\pいい ししょうに であえて よかった。\nありがとう! またな!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "{JPN}ん? {STR_VAR_1}なら\nもう しって いるぞ。\pああ そうか わかった。\nいそがしい おれの {STR_VAR_2}には\lなにも いらないって ことだな?$"

gText_ApprenticeWhatHeldItem6::
	.string "{JPN}やあ {PLAYER}さん! わたしよ!\nきょうも ちえを かりたいの。\lおねがい アドバイスを ちょうだい!\pドラムロール おねがい!\nわたしの しつもんは…\p{STR_VAR_1}に どうぐを もたせるなら\nなにが いいかしら?$"

gText_ApprenticeHoldNothing6::
	.string "{JPN}そうなの? {STR_VAR_1}には\nどうぐは いらないって いうのね。$"

gText_ApprenticeThanksNoHeldItem6::
	.string "{JPN}わかった そうする!\pきょう ききたかったのは\nそれくらいかな。\pまた ここで あいましょうね?\nありがとう!$"

gText_ApprenticeThanksHeldItem6::
	.string "{JPN}なるほど {STR_VAR_1}ね。\nすてきな えらびかた!\lかならず ためして みるわ!\pきょう ききたかったのは\nそれくらいかな。\pまた ここで あいましょうね?\nありがとう!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "{JPN}アハハ! おかしいわ!\n{STR_VAR_1}なら まえに\lおしえて くれたじゃ ない!\pぐあいでも わるいの {PLAYER}さん?\pあっ そうか! {STR_VAR_2}には\nどうぐは いらないって いうのね。$"

gText_ApprenticeWhatHeldItem7::
	.string "{JPN}こんにちは {PLAYER}さん。\nおかわり ありませんか?\pまた アドバイスを おねがいできますか?\pさきの たたかいで あいては ポケモンに\nどうぐを もたせて いたように\lおもわれます。\pそのけっか わたくしは やぶれました…\pおくれを とりたく ありません。\nわたくしの {STR_VAR_1}にも\lどうぐを もたせたいのです。\pどれが ふさわしいか きめて\nいただけると うれしいのですが…$"

gText_ApprenticeHoldNothing7::
	.string "{JPN}つまり… わたくしの ポケモンには\nどうぐは いらないと?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "{JPN}よく わかりました!\nこの ままで がんばりつづけます。\pありがとう ございます {PLAYER}さん。\nまた たよらせて いただきます。\lどうぞ おげんきで!$"

gText_ApprenticeThanksHeldItem7::
	.string "{JPN}{STR_VAR_1}ですね!\nさっそく とりよせます。\pありがとう ございます {PLAYER}さん。\nまた たよらせて いただきます。\lどうぞ おげんきで!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "{JPN}それは もう おしえて いただき\nわたくしも もって おります。\pそれとも… わたくしの ポケモンには\nどうぐは いらないと?$"

gText_ApprenticeWhatHeldItem8::
	.string "{JPN}ひゃっ {PLAYER}さん!\nま また あえて かんげきです {PLAYER}さん!\pああ そうだ! どうしても\nききたい ことが あったんです!\pわたしの {STR_VAR_1}に なにを\nもたせれば いいか きめて ください!$"

gText_ApprenticeHoldNothing8::
	.string "{JPN}わあ そんな こたえだとは!\nもちものは いらないんですね?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "{JPN}かんぺきに わかりました!\nなにも もたせずに がんばります!\pまた こんど べつの ことも\nおしえて いただけると うれしいです。$"

gText_ApprenticeThanksHeldItem8::
	.string "{JPN}{STR_VAR_1}! それを つかいます!\pあの… もしかして {PLAYER}さんも\nその どうぐを もたせて いますか?\pかならず てに いれます!\nまた こんど べつの ことも\lおしえて いただけると うれしいです。$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "{JPN}あれ? {STR_VAR_1}は\nまえにも おすすめ されました。\pそれほど いい ものなのですか?\nそれとも {STR_VAR_2}には\lなにも いらないと いう ことですか?$"

gText_ApprenticeWhatHeldItem9::
	.string "{JPN}オラ!\nししょう {PLAYER}{KUN}!\pポケモンの どうぐの ことで\nアドバイスが ほしいんだ。\pおれの {STR_VAR_1}には なにを\nもたせるのが いいと おもう?\pえんりょは いらないぜ。\nズバッと いって くれ!$"

gText_ApprenticeHoldNothing9::
	.string "{JPN}ほう? おれの {STR_VAR_1}は\nなにも もたずに かてると?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "{JPN}シ ブエノ!\nぜんりょくで やって みるぜ バシッと!\pよし いつも ありがとうな!\nアディオス!$"

gText_ApprenticeThanksHeldItem9::
	.string "{JPN}なるほど {STR_VAR_1}か?\nシ ブエノ!\lさっそく さがしに いくぜ バシッと!\pよし いつも ありがとうな!\nアディオス!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "{JPN}ちがう ちがう! {STR_VAR_1}なら\nまえにも おしえて くれたぜ。\pおっと ちょっと まてよ…\nつまり おれの {STR_VAR_2}は\lなにも もたずに かてると?$"

gText_ApprenticeWhatHeldItem10::
	.string "{JPN}{PLAYER}{KUN} しんじられない ことが\nおきたんだ!\pけさ おきたら おれの ポケモンが\nきんのたまを 10こ もって いた!\pもちろん うそだけどな!\nワハハハ!\pでも これは うそじゃ ない。\nポケモンに なにを もたせるか\lかんがえるのが にがてなんだ。\pだから ししょう {STR_VAR_1}に なにを\nもたせるか きめて くれないか?$"

gText_ApprenticeHoldNothing10::
	.string "{JPN}どういう いみだ?\nなにも もたせるなって ことか?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "{JPN}よし なにも もたせないんだな。\nじゃあ なにか かって こよう!\pなんてな!\nししょうの おしえに したがうよ!\pありがとう ししょう!\nこれからも おしえて くれよな!$"

gText_ApprenticeThanksHeldItem10::
	.string "{JPN}なるほど {STR_VAR_1}か!\nじゃあ それいがいを もたせるぜ!\pなんてな!\nししょうの おしえに したがうよ!\pありがとう ししょう!\nこれからも おしえて くれよな!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "{JPN}それ まえにも おしえて くれた\nよな?\pほかには ないのかい?\pそれとも {STR_VAR_2}には なにも\nもたせるなって ことかい?$"

gText_ApprenticeWhatHeldItem11::
	.string "{JPN}ア ホ ー イ!\nつづりは あほい だぜ!\pラップする フネのり おれさま!\nとびきり イカした しつもんを\lもって きたぜ!\pどうぐの しつもん\nこたえを たのむぜ!\p{STR_VAR_1}に なにか もたせたい\nいったい なにが いいと おもう?$"

gText_ApprenticeHoldNothing11::
	.string "{JPN}そうなのかい?\nおれの {STR_VAR_1}は なにも\lもたなくて いいってのかい?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "{JPN}わかった しかと きいたぜ!\nおれの ポケモンも てぶらで いくぜ!\pアドバイスが ほしい ときは\n{PLAYER}の ことばに したがうぜ!$"

gText_ApprenticeThanksHeldItem11::
	.string "{JPN}よし {STR_VAR_1}を\nつかう ことに するぜ。\lあんたに きいて せいかいだった!\pアドバイスが ほしい ときは\n{PLAYER}の ことばに したがうぜ!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "{JPN}{STR_VAR_1}って いうのかい?\nそりゃ このまえ きいたぜ。\lあたらしい ネタが ほしいんだ。\pそれとも そういう ことかい?\nおれの ポケモンは なにも\lもたなくて いいってのかい?$"

gText_ApprenticeWhatHeldItem12::
	.string "{JPN}やあ {PLAYER}!\nきょうも みつけたぜ!\pどうしよう アドバイスを もらおうか?\nなんてな もう はなしかけて るぜ!\p{PLAYER} おれに あきて きたかい?\nいやいや そんな はずは ないよな。\pきいて くれるかい?\nアドバイスを さがして いるんだ\lそれが いいたい ことなのさ。\p{STR_VAR_1}に もたせる どうぐの はなし\nなにが いいのか きめられなくて\lあたまを かかえて いるんだ。$"

gText_ApprenticeHoldNothing12::
	.string "{JPN}{STR_VAR_1}には なにも いらない?\nなにも もたせなくて いいのかい?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "{JPN}なにも もたせないのが いちばんなら\nいわれた とおりに するぜ!\pじゃあ {PLAYER} おれは たびを つづける\nでも おれの ことを わすれないでくれ。\pまた あおうぜ かしこい ともだち!$"

gText_ApprenticeThanksHeldItem12::
	.string "{JPN}{STR_VAR_1}を もたせるのが いちばんなら\nいわれた とおりに するぜ!\pじゃあ {PLAYER} おれは たびを つづける\nでも おれの ことを わすれないでくれ。\pまた あおうぜ かしこい ともだち!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "{JPN}{STR_VAR_1}なら まえにも\nきいた きが するぜ?\lいや たしかに きいたぜ!\pあたらしい ものが ほしいんだ!\nそれとも {STR_VAR_2}には なにも\lもたせなくて いいのかい?$"

gText_ApprenticeWhatHeldItem13::
	.string "{JPN}ぐわっ! いたた! {PLAYER}{KUN} うでが おれた!\nさわらないで くれよ!\pポケモンたちに いろんな どうぐを\nもたせて ためして いたら\lやって しまったらしい。\pそんな わけで\nかわりに きめて ほしいんだ。\p{PLAYER}{KUN} おれの {STR_VAR_1}には\nなにを もたせるのが いいと おもう?$"

gText_ApprenticeHoldNothing13::
	.string "{JPN}いてて…\pつまり {STR_VAR_1}には なにも\nもたせなくて いいって ことか?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "{JPN}ふむ わかった。いまの じょうたいなら\nその ほうが らくで いいな。\pこれからも こうやって\nたよらせて くれよな。$"

gText_ApprenticeThanksHeldItem13::
	.string "{JPN}ふむ わかった {STR_VAR_1}だな。\nポケモンの うでは ぶじだから\lさっそく もたせて みるよ。\pこれからも こうやって\nたよらせて くれよな。$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "{JPN}ちがう ちがう {STR_VAR_1}なら\nまえに おしえて くれただろ?\pもっと いい ものを\nおしえて くれないか?\pおっと ちょっと まてよ。\nつまり {STR_VAR_2}には なにも\lもたせなくて いいって ことか?$"

gText_ApprenticeWhatHeldItem14::
	.string "{JPN}あの… その…\n{PLAYER}{KUN}…\pおねがい そんなに みないで。\nわたしの ポケモンは なにも もって いなくて。\pほんとうに はずかしいのですが\nアドバイスが ほしいんです。\p{STR_VAR_1}を つよく する どうぐが\nきめられなくて…\p{PLAYER}{KUN}は なにが いいと\nおもいますか?$"

gText_ApprenticeHoldNothing14::
	.string "{JPN}あの… では {STR_VAR_1}には\nどうぐが ない ほうが いいのですね?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "{JPN}あ… はい!\nなにも もたせずに いきます。\pきんちょう しますね。\nかっこよすぎるでしょうか?\pありがとう ございます {PLAYER}{KUN}。\nまた あえたら そのときも\lたよりに させて ください。$"

gText_ApprenticeThanksHeldItem14::
	.string "{JPN}あ… はい!\n{STR_VAR_1}で いきます。\pきんちょう しますね。\nかっこよすぎるでしょうか?\pありがとう ございます {PLAYER}{KUN}。\nまた あえたら そのときも\lたよりに させて ください。$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "{JPN}で でも それは もう ききました。\pそんなに つれなく しないで ください!\nはずかしくて いきて いけません。\pあっ… はやとちり でしょうか?\n{STR_VAR_2}には どうぐが ない ほうが\lいいと いう ことですか?$"

gText_ApprenticeWhatHeldItem15::
	.string "{JPN}ふむ? {PLAYER}{KUN}の ようですが…\nほんとうに そうですか?\lふたごの かたでは?\pいえ いえ ごしんぱいなく!\nほんものの {PLAYER}なら さきほどの\lしつれいは わすれて ください。\pわたしが ほしいのは\nさらなる りっぱな アドバイスです。\pこの {STR_VAR_1}に べんりな どうぐを\nもたせたいのですが。\pなにが ふさわしいでしょう?$"

gText_ApprenticeHoldNothing15::
	.string "{JPN}なにも もたせない ほうが よいと?\nまちがい ありませんか?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "{JPN}なるほど そう いう ことでしたら けっこう。\nおじかんを いただき ありがとう ございます。\pまた おあい しましょう!$"

gText_ApprenticeThanksHeldItem15::
	.string "{JPN}{STR_VAR_1}ですか?\nまちがい ありませんか?\pなるほど そう いう ことでしたら けっこう。\nおじかんを いただき ありがとう ございます。\pわたくしの ポケモンが うまく\nつかいこなせると よいのですが。\pまた おあい しましょう!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "{JPN}いえ いえ おまち ください。\nそれは まえに おそわった はずです。\pこんかいは べつの ものを\nおすすめ いただきたいのですが。\pそれとも {STR_VAR_2}には なにも\nもたせるなと おっしゃるのですか?\lまちがい ありませんか?$"

gText_ApprenticeWhichMonFirst0::
	.string "{JPN}うわーん {PLAYER}さん!\nなやんで いるんです ぐすっ…\pひとと たたかい はじめたいのですが\nどうすれば いいのか わからなくて。\pどんな ならびに すれば ポケモンたちが\nいちばん つよく なるのでしょう?\pおしえて ください {PLAYER}さん。\nあなたなら この なかの どの ポケモンを\lさいしょに だしますか?$"

gText_ApprenticeMonFirstThanks0::
	.string "{JPN}{STR_VAR_1}を さいしょに?\nうわああん!\pあっ ごめんなさい!\nさいしょの ポケモンを きめて もらえたのが\lうれしくて ないちゃったんです…\pほんとうに ありがとう ございます!$"

gText_ApprenticeWhichMonFirst1::
	.string "{JPN}やった! {PLAYER}さんだ!\nよかった ききたい ことが あったんだ!\pあのね ぼくの ポケモンの なかで\nどれを さいしょに だすべきかな?$"

gText_ApprenticeMonFirstThanks1::
	.string "{JPN}{STR_VAR_1}? たしかに そうだね。\nうん そうするよ!\pおしえて くれて ありがとう!$"

gText_ApprenticeWhichMonFirst2::
	.string "{JPN}{PLAYER}さん こんにちは!\pたたかいでは どの ポケモンを さいしょに\nだすかが とても だいじだと おもうんです。\pわたしの ポケモンの なかで\nどれを さきに だすと いいでしょう?$"

gText_ApprenticeMonFirstThanks2::
	.string "{JPN}{STR_VAR_1}を さいしょに?\nわかりました!\pまた あいましょう!$"

gText_ApprenticeWhichMonFirst3::
	.string "{JPN}こんにちは {PLAYER}さん…\nまた しつもんで おじゃまして\lもうしわけ ありません。\pじしんが なくて {PLAYER}さんが いないと\nどうして いいか わからないんです。\pぼくなんかが なやむのは じかんの\nむだかも しれませんが どうしても\lきめられなくて…\pたたかいで どの ポケモンを\nさいしょに だせば いいのでしょう?$"

gText_ApprenticeMonFirstThanks3::
	.string "{JPN}{STR_VAR_1}ですか?\nわかりました!\pこんなに なんども しつもんに\nこたえて いただけるなんて!\pぼくなんかと はなして くださって…\nありがとう ございます!$"

gText_ApprenticeWhichMonFirst4::
	.string "{JPN}あら {PLAYER}{KUN}! わたしよ!\nちょっと こまった ことが あって\lあえて うれしいわ。\pポケモンの ならびが きめられないの。\nかわりに きめて くれない?\pああ ぜんぶ きめなくても\nいいのよ。\pさいしょの ポケモンだけ\nきめて くれないかしら?$"

gText_ApprenticeMonFirstThanks4::
	.string "{JPN}{STR_VAR_1}ね? すてき!\p{PLAYER}{KUN}が きめて くれたのなら\nまけても そんなに くやしく\lないと おもうわ。\pじゃあ また アドバイスを もらいに くるわ。\nまたね!$"

gText_ApprenticeWhichMonFirst5::
	.string "{JPN}やあ ししょうの {PLAYER}{KUN}!\nきょうも いそがしくてね!\pサイクリングに かいものに\nはなうたも うたわなきゃ ならん。\pポケモンの ならびを きめる ひまも\nなかったんだ。\pそこで おれの てもちを みて くれ。\nどれを さいしょに だせば いい?$"

gText_ApprenticeMonFirstThanks5::
	.string "{JPN}よし わかった。\n{STR_VAR_1}を せんとうに おく くらいの\lじかんは あるからな!\pおっと かのじょが まって いる!\nありがとう! またな!$"

gText_ApprenticeWhichMonFirst6::
	.string "{JPN}ヤッホー! やあ {PLAYER}さん!\nいつも つよそうに あるいて いるわね!\pねえ また おねがいが あるの!\nいつもの あれよ!\pドラムロール おねがい!\nしつもんは てもちの ことなの。\pわたしの ポケモンの どれを\nさいしょに だせば いいかしら?$"

gText_ApprenticeMonFirstThanks6::
	.string "{JPN}ふむふむ!\n{STR_VAR_1}って いうのね!\lすっごく クールな こたえ ありがとう!\pきょう ききたかったのは\nそれくらいかな。\pまた ここで あいましょうね?\nありがとう!$"

gText_ApprenticeWhichMonFirst7::
	.string "{JPN}たちどまって おはなし くださって\nほんとうに ありがとう ございます {PLAYER}さん。\pおやさしさに あまえて しまいますが\nアドバイスを おねがいできますか?\pわたくしの ポケモンの ならびを\nきめて いただきたいのです。\pどの ポケモンを さいしょに するか\nきめて いただけると うれしいのですが。$"

gText_ApprenticeMonFirstThanks7::
	.string "{JPN}{STR_VAR_1}ですね!\nさっそく せんとうに おきます!\pありがとう ございます {PLAYER}さん。\nまた たよらせて いただきます。\lどうぞ おげんきで!$"

gText_ApprenticeWhichMonFirst8::
	.string "{JPN}ひゃっ {PLAYER}さん!\nま また あえて かんげきです!\pわたしの ポケモンたち ずいぶん\nつよく なったんです!\pでも いつも かてるわけでは なくて。\nどの ポケモンを さきに だすかで かわるみたい。\p{PLAYER}さん おねがいします!\pどの ポケモンを さいしょに だすか\nきめて ください!$"

gText_ApprenticeMonFirstThanks8::
	.string "{JPN}ああ… うれしくて どうにか なりそうです…\p{PLAYER}さんに きめて もらえるなんて\nゆめの ようです。\pでも かんぺきに わかりました!\n{STR_VAR_1}を さいしょに だします!\pまた こんど べつの ことも\nおしえて いただけると うれしいです。$"

gText_ApprenticeWhichMonFirst9::
	.string "{JPN}やあ やあ!\nししょうの {PLAYER}{KUN}!\lきょうも ちえを かして くれ!\pじつは ポケモンを 3びき そろえたんだ。\nそこまでは じゅんちょうさ。\pだが ならびが まだ\nきまって いないんだ。\pそこで {PLAYER}{KUN}の でばんだ!\nどれを せんとうに するか きめて くれ!\pえんりょは いらないぜ。\nズバッと いって くれ!$"

gText_ApprenticeMonFirstThanks9::
	.string "{JPN}なるほど {STR_VAR_1}が せんとうか!\nオーケー オーケー!\lならびを かえるぜ ズバッとな!\pよし いつも ありがとうな!\nアディオス!$"

gText_ApprenticeWhichMonFirst10::
	.string "{JPN}{PLAYER}{KUN} きいて くれ!\nおおごとだ!\pおれの ポケモン 3びき ぜんぶが\nいちどに たたかいに でるんだ!\pもちろん ありえない けどな!\nワハハハ!\pでも これは うそじゃ ない。\nポケモンの ならびを かんがえるのが\lにがてなんだ。\pだから ししょう どの ポケモンを\nさいしょに だすか きめて くれよ?$"

gText_ApprenticeMonFirstThanks10::
	.string "{JPN}なるほど {STR_VAR_1}を えらんだのか?\nじゃあ それいがいを さきに だすぜ!\pなんてな!\nししょうの おしえに したがうよ!\pありがとう ししょう!\nこれからも おしえて くれよな!$"

gText_ApprenticeWhichMonFirst11::
	.string "{JPN}ア ホ ー イ!\nつづりは あほい だぜ!\pラップする フネのり おれさま!\nとびきり イカした しつもんを\lもって きたぜ!\pならびの しつもん\nこたえを たのむぜ!\pこの なかの どれを さいしょに\nおくるのが いいと おもう?$"

gText_ApprenticeMonFirstThanks11::
	.string "{JPN}わかった しかと きいたぜ!\nさっそく ならべかえると するぜ!\pアドバイスが ほしい ときは\n{PLAYER}の ことばに したがうぜ!$"

gText_ApprenticeWhichMonFirst12::
	.string "{JPN}ヤッホー {PLAYER}!\nごきげん いかが?\pどうしよう きいて みようか?\nああ ききたい ことが あるんだ!\lきこえて いるかい?\lきこえて いるよな!\pきめて くれよ おれの ポケモンの\nどれが さいしょに のりだすか!\lたたかいの はなしだぜ。$"

gText_ApprenticeMonFirstThanks12::
	.string "{JPN}{STR_VAR_1}? そうかい!\nそれで きまりだ もんだい なしさ!\pじゃあ {PLAYER} おれは たびを つづける\nでも おれの ことを わすれないでくれ。\pまた あおうぜ かしこい ともだち!$"

gText_ApprenticeWhichMonFirst13::
	.string "{JPN}…うう いてて… {PLAYER}{KUN}…\nきゅうに はらが いたく なって きた…\p…すこし よく なって きたよ…\pポケモンの ならびを どうするか\nあたまを なやませすぎて\lはらまで いためたらしい。\pそんな わけで\nかわりに きめて ほしいんだ。\p{PLAYER}{KUN} どの ポケモンを さきに だせば\nかてると おもう?$"

gText_ApprenticeMonFirstThanks13::
	.string "{JPN}ふむ わかった。\n{STR_VAR_1}が せんとうだな。\pめしを くったら その ならびに\nなおして おくよ。\pこれからも こうやって\nたよらせて くれよな。$"

gText_ApprenticeWhichMonFirst14::
	.string "{JPN}あの… その…\n{PLAYER}{KUN}?\pおねがい そんなに みないで。\nどぎまぎ して しまいます。\pあの…\nアドバイスが ほしいんです。\pはずかしいのですが ポケモンを\n3びき えらんだんです。\lでも ならびが きめられなくて。\pせめて それらしく みえるように\nどれを さきに だせば いいでしょう?$"

gText_ApprenticeMonFirstThanks14::
	.string "{JPN}あ… はい!\n{STR_VAR_1}を せんとうに します。\pどぎまぎ しないで\nがんばれると いいのですが。\pありがとう ございます {PLAYER}{KUN}。\nまた あえたら そのときも\lたよりに させて ください。$"

gText_ApprenticeWhichMonFirst15::
	.string "{JPN}ふむ? {PLAYER}{KUN}の ようですが…\nほんとうに そうですか?\lよく にた にせものでは?\pいえ いえ ごしんぱいなく!\nほんものの {PLAYER}なら さきほどの\lしつれいは わすれて ください。\pわたしが ほしいのは りっぱな アドバイスです。\pここに わたくしの てもちが あります。\nたたかいで どれを さいしょに だすべきか\lおしえて いただきたいのです。$"

gText_ApprenticeMonFirstThanks15::
	.string "{JPN}{STR_VAR_1}ですか…\nからかって いませんか?\pなるほど そう いう ことでしたら けっこう。\nおじかんを いただき ありがとう ございます。\pこの とおりの わたくしですが\nぜんりょくで やって みます。\pまた おあい しましょう!$"

gText_ApprenticeWhichMon0::
	.string "{JPN}ぐすっ…\nああ {PLAYER}さん!\pちょうど よかった!\nどうしても きめられない ことが あって…\pどの ポケモンを つかえば いいのか\nきめられないんです。\p{STR_VAR_1}と {STR_VAR_2}の どちらに\nするか まよって いて…\p{PLAYER}さん わたしでも かてそうなのは\nどちらだと おもいますか?$"

gText_ApprenticeMonThanks0::
	.string "{JPN}ぐすっ… わ わかりました!\nあっ ごめんなさい!\lうれしすぎて ないちゃって…\p{STR_VAR_1}を つかまえられる ように\nがんばります!\pほんとうに ありがとう ございます!$"

gText_ApprenticeWhichMon1::
	.string "{JPN}やった! {PLAYER}さんだ!\nちょうど いい ときに きて くれた!\lまた アドバイスが ほしいんだ!\pあのね {STR_VAR_1}と {STR_VAR_2}の\nどっちを つかうか まよって いて…\p{PLAYER}さんなら どっちを\nそだてると おもう?$"

gText_ApprenticeMonThanks1::
	.string "{JPN}そうか {STR_VAR_1}の ほうが いいんだ!\nうん そうするよ!\pおしえて くれて ありがとう!$"

gText_ApprenticeWhichMon2::
	.string "{JPN}{PLAYER}さん こんにちは!\nききたい ことが あるんです。\p{STR_VAR_1}と {STR_VAR_2}の どちらを\nそだてるか まよって いて。\pどちらの ポケモンの ほうが\nつよく なると おもいますか?$"

gText_ApprenticeMonThanks2::
	.string "{JPN}{STR_VAR_1}ですね?\nわかりました!\pさっそく つよい {STR_VAR_1}を\nつかまえに いきます!\pまた あいましょう!$"

gText_ApprenticeWhichMon3::
	.string "{JPN}こんにちは {PLAYER}さん…\pあの ぼくのような ものの ことは\nもう わすれて いますよね…\p…でも アドバイスさえ いただければ\nそれで いいんです…\pそだてる ポケモンを ひとつに\nきめられなくて…\p{STR_VAR_1}と {STR_VAR_2}の ふたつまでは\nしぼれたのですが そこから さきに\lすすめなくて…\p{PLAYER}さん おてすうでしょうが\nきめて いただけませんか?$"

gText_ApprenticeMonThanks3::
	.string "{JPN}でも やせいの {STR_VAR_1}が ぼくなんかを\nあいてに して くれるでしょうか?\pやって みます!\pつかまえられるか わかりませんが…\nいえ! がんばります!\pありがとう ございました!$"

gText_ApprenticeWhichMon4::
	.string "{JPN}あら {PLAYER}{KUN}! あえて よかった!\nさがしに いく ところ だったのよ!\pわたしが つかう ポケモンを\nきめて くれない?\pたとえば…\n{STR_VAR_1}と {STR_VAR_2}だったら\lどうかしら?\pどっちの ほうが いいと\nおもう?$"

gText_ApprenticeMonThanks4::
	.string "{JPN}{STR_VAR_1}ね? すてき!\p{PLAYER}{KUN}が きめて くれたのなら\nまけても そんなに くやしく\lないと おもうわ。\pじゃあ また アドバイスを もらいに くるわ。\nまたね!$"

gText_ApprenticeWhichMon5::
	.string "{JPN}やあ {PLAYER}{KUN}! ちょうしは どうだい?\nおれは きょうも いそがしくてね!\pポケモンでも いい せんを いきたいんだが\nどの ポケモンを つかうか\lきめられなくてね。\p{STR_VAR_1}は つよそうだろ?\nでも {STR_VAR_2}も すてがたい。\p{PLAYER}{KUN} いい アドバイスを たのむ!\nおれには どっちが いいと おもう?$"

gText_ApprenticeMonThanks5::
	.string "{JPN}よし わかった。\nなんとか じかんを つくって\lおすすめの {STR_VAR_1}を つかまえるよ。\pいい ししょうに であえて よかった。\nありがとう! またな!$"

gText_ApprenticeWhichMon6::
	.string "{JPN}あっ!\nやった {PLAYER}さんだ!\pあなたに あった ことを さっそく\nともだちに じまん しちゃった!\pきょうも ちえを かりたいの。\nあなたには かんたんな ことよ!\pドラムロール おねがい!\nわたしの しつもんは…\pポケモンを そだてるなら\n{STR_VAR_1}と {STR_VAR_2}の\lどちらに するべきかしら?$"

gText_ApprenticeMonThanks6::
	.string "{JPN}ああ!\n{STR_VAR_1}って いうのね!\lすっごく クールな こたえ ありがとう!\pきょう ききたかったのは\nそれくらいかな。\pまた ここで あいましょうね?\nありがとう!$"

gText_ApprenticeWhichMon7::
	.string "{JPN}おや {PLAYER}さん ですか?\nまた おあいできて うれしいです!\pおでしに して いただいてから\nじしんが ついて きました。\pじぶんの ポケモンを そだてる じゅんびが\nできたと おもうのです!\p{PLAYER}さん どの ポケモンを そだてるか\nえらんで いただけませんか?\pえらぶのは {STR_VAR_1}か\n{STR_VAR_2}なのですが…\lどちらが わたくしに あうでしょう?$"

gText_ApprenticeMonThanks7::
	.string "{JPN}{STR_VAR_1}ですね!\nさっそく さがして きます!\pありがとう ございます {PLAYER}さん。\nまた たよらせて いただきます。\lどうぞ おげんきで!$"

gText_ApprenticeWhichMon8::
	.string "{JPN}ひゃっ {PLAYER}さん! また あえた!\nか かんげきです!\pああ そうだ!\nこの チャンスを のがしては だめです!\pおおきな おねがいが あります {PLAYER}さん!\nポケモンを えらんで ください!\p{STR_VAR_1}と {STR_VAR_2} どちらが\nいいか きめて ください!$"

gText_ApprenticeMonThanks8::
	.string "{JPN}わあ! きめて くれた!\n{STR_VAR_1}を ぜんりょくで\lそだてて みせます。\pまた こんど べつの ことも\nおしえて いただけると うれしいです。$"

gText_ApprenticeWhichMon9::
	.string "{JPN}やあ やあ!\nししょうの {PLAYER}{KUN}!\pまた りっぱな アドバイスが ほしくて\nさがして いたんだ!\pおれに あう ポケモンは どっちだと おもう?\n{STR_VAR_1}か {STR_VAR_2}か。\pえんりょは いらないぜ。\nズバッと いって くれ!$"

gText_ApprenticeMonThanks9::
	.string "{JPN}なるほど {STR_VAR_1}だな!\nオーケー オーケー!\lボールに いれて くるぜ バシッと!\pよし いつも ありがとうな!\nアディオス!$"

gText_ApprenticeWhichMon10::
	.string "{JPN}{PLAYER}{KUN} きいて くれ! ビッグニュースだ!\nまぼろしの ポケモンを つかまえた!\pもちろん うそだけどな!\nワハハハ!\pでも これは うそじゃ ない。\nおれは ポケモンを つかまえるのが\lにがてなんだ。\pだから ししょう どの しゅるいの\nポケモンを つかまえるか\lきめて くれないか?\pどっちが いいと おもう?\n{STR_VAR_1}か {STR_VAR_2}か?$"

gText_ApprenticeMonThanks10::
	.string "{JPN}なるほど {STR_VAR_1}を えらんだのか?\nじゃあ もう ひとつの ほうを つかまえるぜ!\pなんてな!\nししょうの おしえに したがうよ!\pありがとう ししょう!\nこれからも おしえて くれよな!$"

gText_ApprenticeWhichMon11::
	.string "{JPN}ア ホ ー イ!\nつづりは あほい だぜ!\pラップする フネのり おれさま!\nおれの ことは おぼえて いるよな?\pきょうは ポケモンの しつもん\nこたえを たのむぜ!\pえらべるのは この {STR_VAR_1}と\n{STR_VAR_2}なんだが\lつかまえるなら どっちだい?$"

gText_ApprenticeMonThanks11::
	.string "{JPN}{STR_VAR_1}って いうんだな!\nさっそく つかまえに いくとするぜ!\pアドバイスが ほしい ときは\n{PLAYER}の ことばに したがうぜ!$"

gText_ApprenticeWhichMon12::
	.string "{JPN}おおっ {PLAYER}じゃ ないか!\pどうしよう アドバイスを もらおうか?\nなんてな もう はなしかけて るぜ!\pひさしぶりだな まずは あいさつ がわりに。\nじつは アドバイスを さがして いるのさ!\lきこえて いるかい?\lきこえて いるよな!\pおれの ポケモン どっちを つかおう?\n{STR_VAR_1}か {STR_VAR_2}か。\lあんたなら どっちを えらぶ?$"

gText_ApprenticeMonThanks12::
	.string "{JPN}{STR_VAR_1}が いちばんなら\nいわれた とおりに するぜ!\pじゃあ {PLAYER} おれは たびを つづける\nでも おれの ことを わすれないでくれ。\pまた あおうぜ かしこい ともだち!$"

gText_ApprenticeWhichMon13::
	.string "{JPN}やあ {PLAYER}{KUN}…\nひどい ずつうで まいって いるんだ…\pどの ポケモンを そだてるか\nなやみすぎたのかも しれない。\pそんな わけで\nかわりに きめて ほしいんだ。\p{PLAYER}{KUN} {STR_VAR_1}と\n{STR_VAR_2}から えらぶなら\lどっちが いいと おもう?$"

gText_ApprenticeMonThanks13::
	.string "{JPN}ふむ {STR_VAR_1}だな わかった。\nよく なったら さがしに いくよ。\pこれからも こうやって\nたよらせて くれよな。$"

gText_ApprenticeWhichMon14::
	.string "{JPN}あの… その…\n{PLAYER}{KUN}…?\pおねがい そんなに みないで。\nどぎまぎ して しまいます…\lあ アドバイスが ほしいんです。\pは はずかしいのですが どの ポケモンを\nつかうか きめられなくて。\p{STR_VAR_1}と {STR_VAR_2}なら\nどちらが いいでしょうか?$"

gText_ApprenticeMonThanks14::
	.string "{JPN}あ… はい!\n{STR_VAR_1}で がんばって みます。\pどぎまぎ しないで\nがんばれると いいのですが。\pありがとう ございます {PLAYER}{KUN}。\nまた あえたら そのときも\lたよりに させて ください。$"

gText_ApprenticeWhichMon15::
	.string "{JPN}ふむ? {PLAYER}{KUN}の ようですが…\nほんとうに ほんものですか?\pいや ほんものなら それで けっこう。\nところで あなたの アドバイスを\lいただきたいのです。\pつかう ポケモンの ことなのですが。\pえらべるのが {STR_VAR_1}と\n{STR_VAR_2}なら どちらが\lわたくしに ふさわしいでしょう?$"

gText_ApprenticeMonThanks15::
	.string "{JPN}{STR_VAR_1}ですか?\nまちがい ありませんか?\pなるほど そう いう ことでしたら けっこう。\nおじかんを いただき ありがとう ございます。\pわたくしにも うまく あつかえる ものだと\nよいのですが。\pまた おあい しましょう!$"

gText_ApprenticeWhichMove0::
	.string "{JPN}うわーん! ああ {PLAYER}さん!\nぐすっ… ヒック…\pこまって いるんです!\n{STR_VAR_1}の わざが\lきめられなくて…\pおねがいします {PLAYER}さん。\nかわりに きめて くれませんか?\p{STR_VAR_1}には どちらの わざが\nいいでしょう {STR_VAR_2}と\l{STR_VAR_3}では?$"

gText_ApprenticeMoveThanks0::
	.string "{JPN}{STR_VAR_1}?\nうわああん!\pあっ ごめんなさい {PLAYER}さん!\nわざを きめて もらえたのが\lうれしくて ないちゃったんです…\pぐすっ…\nほんとうに ありがとう ございます!$"

gText_ApprenticeWhichMove1::
	.string "{JPN}やった! {PLAYER}さんだ!\nまた アドバイスが ほしいんだ!\p{STR_VAR_1}に かっこいい わざを\nおぼえさせたいんだ。\p{STR_VAR_2}も {STR_VAR_3}も\nどっちも いいと おもうんだけど\lどっちが おすすめ?$"

gText_ApprenticeMoveThanks1::
	.string "{JPN}{STR_VAR_1}の ほうが いいの? なるほど!\nうん そうするよ!\pまた ここで あったら べつの ことも\nおしえて ね せんせい!$"

gText_ApprenticeWhichMove2::
	.string "{JPN}{PLAYER}さん こんにちは!\nわたしの {STR_VAR_1}の ことですが\lわざで なやんで いて。\p{STR_VAR_2}と {STR_VAR_3}\nなんです。\p{STR_VAR_1}には どちらが つよくて\nいいと おもいますか?$"

gText_ApprenticeMoveThanks2::
	.string "{JPN}{STR_VAR_1}ですね?\nわかりました!\pさっそく {STR_VAR_1}を\nおぼえさせて きます!\pまた あいましょう!$"

gText_ApprenticeWhichMove3::
	.string "{JPN}ああ {PLAYER}さん…\nぼくは どうしようも ないですね…\pポケモンを そだてる ことには きめたのに\nこんどは どの わざを おぼえさせるかが\lきめられなくて…\p{PLAYER}さんには どうでも いい ことだと\nわかって います。\pでも ぼくには だいじな ことで…\pおねがいします {PLAYER}さん\n{STR_VAR_1}の わざを えらんで ください。\p{STR_VAR_2}と {STR_VAR_3}から\nえらんで いただけたら…$"

gText_ApprenticeMoveThanks3::
	.string "{JPN}わかりました!\pでも {STR_VAR_1}を おぼえて\nくれるでしょうか…\lいえ! がんばります!\pありがとう ございました!$"

gText_ApprenticeWhichMove4::
	.string "{JPN}あら {PLAYER}{KUN}!\nちょうど あいたいと おもって いたの!\p{STR_VAR_1}には どんな わざが\nあうのか かんがえて いたのよ。\pきめられないから かわりに\nきめて くれない?\pたとえば… {STR_VAR_2}と\n{STR_VAR_3}なら\lどっちが いいと おもう?$"

gText_ApprenticeMoveThanks4::
	.string "{JPN}{STR_VAR_1}ね? すてき!\p{PLAYER}{KUN}が きめて くれたのなら\nまけても そんなに くやしく\lないと おもうわ。\pじゃあ また アドバイスを もらいに くるわ。\nまたね!$"

gText_ApprenticeWhichMove5::
	.string "{JPN}なんで こんなに いそがしいんだ?\nやあ {PLAYER}{KUN}じゃ ないか!\lちょうしは どうだい?\pけさ おきてから ジョギングに すいえいに\nりょうりまで やったんだぜ!\pどれだけ いそがしいか わかるだろう!\p{STR_VAR_1}に おぼえさせる わざも\nきめられないんだ!\p{STR_VAR_2}も よさそうだよな?\nでも {STR_VAR_3}も わるく ない。\p{PLAYER}{KUN} いい アドバイスを たのむ!\nおれには どっちの わざが いいと おもう?$"

gText_ApprenticeMoveThanks5::
	.string "{JPN}よし わかった。\nなんとか じかんを つくって\lその わざを おぼえさせるよ。\pいい ししょうに であえて よかった。\nありがとう! またな!$"

gText_ApprenticeWhichMove6::
	.string "{JPN}あっ ラッキー!\nまた あえたわね {PLAYER}さん!\lきょうも ちえを かりたいの。\pドラムロール おねがい!\nわたしの しつもんは…\p{STR_VAR_1}に いちばん あう わざは\n{STR_VAR_2}と {STR_VAR_3}\lどっちかしら?$"

gText_ApprenticeMoveThanks6::
	.string "{JPN}ああ!\n{STR_VAR_1}って いうのね!\lすっごく クールな こたえ ありがとう!\pきょう ききたかったのは\nそれくらいかな。\pまた ここで あいましょうね?\nありがとう!$"

gText_ApprenticeWhichMove7::
	.string "{JPN}こんにちは {PLAYER}さん。\nおかわり ありませんか?\pまた アドバイスを おねがいします。\nかわいい {STR_VAR_1}の ことです。\pいとしい {STR_VAR_1}に ぴったりの\nわざは どちらでしょう?\l{STR_VAR_2}と {STR_VAR_3}。$"

gText_ApprenticeMoveThanks7::
	.string "{JPN}{STR_VAR_1}ですね!\nさっそく おぼえさせます!\pありがとう ございます {PLAYER}さん。\nまた たよらせて いただきます。\lどうぞ おげんきで!$"

gText_ApprenticeWhichMove8::
	.string "{JPN}ひゃっ {PLAYER}さん! また あえた!\nか かんげきです!\pこまった ときは いつも {PLAYER}さんが\nいて くれるんですね!\pきょうは わざを えらんで\nいただきたいんです!\pわたしの {STR_VAR_1}の わざを\nきめて ください!\p{STR_VAR_2}と {STR_VAR_3}\nどちらが いいでしょう?$"

gText_ApprenticeMoveThanks8::
	.string "{JPN}ああ ありがとう ございます!\n{STR_VAR_1}ですね!\lかんぺきに わかりました!\pまた こんど べつの ことも\nおしえて いただけると うれしいです。$"

gText_ApprenticeWhichMove9::
	.string "{JPN}オラ {PLAYER}{KUN} ブエノ!\nきょうも りっぱな アドバイスを\lもらいたいんだ!\pおれの {STR_VAR_1}に いちばん あう\nわざは なんだと おもう?\pズバッと かてる ような\nわざが いいんだ!\p{STR_VAR_2}か?\nそれとも {STR_VAR_3}か?$"

gText_ApprenticeMoveThanks9::
	.string "{JPN}なるほど {STR_VAR_1}だな!\nシ ブエノ!\lさっそく おぼえさせるぜ バシッと!\pよし いつも ありがとうな!\nアディオス!$"

gText_ApprenticeWhichMove10::
	.string "{JPN}{PLAYER}{KUN} とんでもない ことに なったぞ!\pおれの ポケモンが!\nわざを 6つも おぼえたんだ!\pもちろん うそだけどな!\nワハハハ!\pでも これは うそじゃ ない。\nポケモンの わざを えらぶのが\lにがてなんだ。\pだから どの わざを おぼえさせるか\nきめて くれないか?\p{STR_VAR_2}と {STR_VAR_3} どっちが\n{STR_VAR_1}に あうと おもう?$"

gText_ApprenticeMoveThanks10::
	.string "{JPN}なるほど {STR_VAR_1}を えらんだのか?\nじゃあ べつの わざに するぜ!\pなんてな!\nししょうの おしえに したがうよ!\pありがとう ししょう!\nこれからも おしえて くれよな!$"

gText_ApprenticeWhichMove11::
	.string "{JPN}ア ホ ー イ!\nつづりは あほい だぜ!\pラップする フネのり おれさま!\nいつだって ノリノリなのさ りゆうは きくな!\pきょうは わざの しつもん\nこたえを たのむぜ!\pわざは {STR_VAR_2}と {STR_VAR_3}。\n{STR_VAR_1}が のれるのは\lどっちだと おもう?$"

gText_ApprenticeMoveThanks11::
	.string "{JPN}{STR_VAR_1}って いうんだな!\nさっそく おぼえさせに いくとするぜ!\pアドバイスが ほしい ときは\n{PLAYER}の ことばに したがうぜ!$"

gText_ApprenticeWhichMove12::
	.string "{JPN}おおっ {PLAYER}じゃ ないか!\pどうしよう アドバイスを もらおうか?\nなんてな もう はなしかけて るぜ!\p{PLAYER} おどろいて いるかい?\nアドバイスが ほしいのさ わかるだろ?\pきこえて いるかい?\nきこえて いるよな!\pおれの {STR_VAR_1} なにを つかおう?\n{STR_VAR_2}か {STR_VAR_3}か\lあんたなら どっちを えらぶ?$"

gText_ApprenticeMoveThanks12::
	.string "{JPN}{STR_VAR_1}が いちばんなら\nいわれた とおりに するぜ!\pじゃあ {PLAYER} おれは たびを つづける\nでも おれの ことを わすれないでくれ。\pまた あおうぜ かしこい ともだち!$"

gText_ApprenticeWhichMove13::
	.string "{JPN}ゲホッ! ゴホッ! ああ {PLAYER}{KUN}…\nひどい かぜを ひいて しまってね…\pポケモンの わざを えらびたいんだが\nそんな げんきも なくて…\pそんな わけで\nかわりに きめて ほしいんだ。\p{PLAYER}{KUN} {STR_VAR_1}の わざを\n{STR_VAR_2}と {STR_VAR_3}から\lえらぶなら どっちに する?$"

gText_ApprenticeMoveThanks13::
	.string "{JPN}ふむ {STR_VAR_1}だな わかった。ゴホッ!\nよく なったら おぼえさせに いくよ。\pこれからも こうやって\nたよらせて くれよな。$"

gText_ApprenticeWhichMove14::
	.string "{JPN}あの… その…\n{PLAYER}{KUN}…?\pおねがい そんなに みないで。\nどぎまぎ して しまいます…\lあ アドバイスが ほしいんです。\pは はずかしいのですが ポケモンに\nおぼえさせる わざが\lきめられなくて。\pわたしの {STR_VAR_1}の ことです。\n{STR_VAR_2}と {STR_VAR_3}なら\lどちらが いいでしょうか?$"

gText_ApprenticeMoveThanks14::
	.string "{JPN}あ… はい!\n{STR_VAR_1}を ためして みます。\pちゃんと おぼえさせられるか…\nきんちょう しますね…\pありがとう ございます {PLAYER}{KUN}。\nまた あえたら そのときも\lたよりに させて ください。$"

gText_ApprenticeWhichMove15::
	.string "{JPN}ふむ? {PLAYER}{KUN}の ようですが…\nほんとうに ほんものですか?\pはやりの ものまねの かたでは\nありませんか?\pいえ ほんものなら けっこうです。\nおこらないで ください おねがいします!\pところで あなたの アドバイスを\nいただきたいのです。\pわたくしの {STR_VAR_1}の ことです。\pつかう わざは {STR_VAR_2}と\n{STR_VAR_3} どちらが よいでしょう?$"

gText_ApprenticeMoveThanks15::
	.string "{JPN}{STR_VAR_1}ですか?\nまちがい ありませんか?\pなるほど そう いう ことでしたら けっこう。\nおじかんを いただき ありがとう ございます。\pわたくしの ポケモンにも おぼえられる\nものだと よいのですが。\pまた おあい しましょう!$"

gText_ApprenticePickWinSpeech0::
	.string "{JPN}あっ… {PLAYER}さん?\n{PLAYER}さんだ!\lあっ ぐすっ… きいて ください!\pわたし たたかうと きんちょうして\nかっても ないて しまうんです…\pかった ときに かっこいい ことを\nいえたら いいのに…\pおねがいします {PLAYER}さん!\nかった ときに ないたり しないよう\lかっこいい ことばを おしえて ください!$"

gText_ApprenticeWinSpeechThanks0::
	.string "{JPN}{STR_VAR_1}\pすごい! やった! わあい!\nとっても かっこいい!\pあっ ごめんなさい…\nうれしくて ないちゃった…\pぐすっ… {PLAYER}さん!\nいままで ほんとうに ありがとう ございます!\p{PLAYER}さんの ために せいいっぱい\nたたかって みせます!\p{PLAYER}さん…\nこんどは… しょうぶ しましょう!$"

gText_ApprenticePickWinSpeech1::
	.string "{JPN}やった! {PLAYER}さんだ! こんにちは!\nききたい ことが あったんだ!\pしょうぶに かった ときに かっこいい\nことを いいたいんだ。\pなにか かっこいい ことばを\nおしえて くれない?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{JPN}{STR_VAR_1}\pわあ すっごく かっこいい!\nうん それを いうよ!\pいままで おしえて くれて ありがとう!\nこれから どこへ いっても\lせいいっぱい がんばるよ!\pこんど あう ときは\nしょうぶだよ!$"

gText_ApprenticePickWinSpeech2::
	.string "{JPN}{PLAYER}さん こんにちは!\pわたしと ポケモンは なんでも\nじゅんび できて います。でも ひとつだけ。\pかった ときに さけぶ ことばが\nあると いいと おもうんです。\pなにか いい ことばを\nかんがえて くれませんか?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{JPN}{STR_VAR_1}\p…かっこいい!\nそれを つかいます!\pこれから あちこちで\nたたかって きます。\pいつか {PLAYER}さんと たたかう ひも\nくるかも しれませんね。\pこんどは たたかいの ばで\nおあい しましょう!$"

gText_ApprenticePickWinSpeech3::
	.string "{JPN}こんにちは {PLAYER}さん…\nおじゃまして すみません ぼくは だめですね…\pかっても…\nかっても なにも いう ことが\lおもいつかなくて…\p{PLAYER}さんには どうでも いい ことだと\nわかって います。\pでも ぼくには だいじな ことで…\pおねがいします {PLAYER}さん\nかったら なんと いえば いいでしょう?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{JPN}{STR_VAR_1}\pすばらしい ことばです…\pあの… ぼくなんかが それを\nいっても いいのでしょうか?\pいえ! がんばります!\p{PLAYER}さん こんなに ながく\nつきあって くださって ありがとう ございます…\pこれからは せいいっぱい がんばります。\pぼくの ことは すぐに わすれるでしょうが\nどこかで また あえたら\lうれしいです!$"

gText_ApprenticePickWinSpeech4::
	.string "{JPN}ねえ {PLAYER}{KUN}。\nきいて ほしい ことが あるの。\pわたし いつも ことばづかいが\nやさしく ないでしょ…\pしょうぶに かった とき えらそうに\nきこえて いる きが するの。\pきらわれたく ないから まけた ひとに\nなにか やさしい ことを\lいいたいのよ。\pでも いい ことばが おもいつかない!\nかんがえて くれない?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{JPN}{STR_VAR_1}\pわるく ないわね!\nうん それで いくわ!\pおしえて もらった ことを あたまと\nこころに いれて わたしは たびに\lでる ことに するわ。\pわがままばかり いって\nごめんなさいね!\pこんどは しょうぶよ いい?\nまたね!$"

gText_ApprenticePickWinSpeech5::
	.string "{JPN}いやあ いそがしくて かなわない!\nおっと {PLAYER}{KUN} さがして いたんだ。\pあいかわらず げんきかい?\nおれの ほうは なにも かわらないよ。\pはしって たたかって ちずも かかなきゃ。\nなんで こんなに いそがしいんだ?\pでも いそがしいからって かった あと\nなにも いわずに せなかを むけるのは\lしつれいだろう?\pだから かっこよく きめて さる ための\nことばが ほしいんだ。{PLAYER}{KUN}\lたすけて くれ!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{JPN}{STR_VAR_1}\pよし わかった。\nそれを いう じかんくらいは あるさ!\pしょうじき きみのような いい ししょうに\nであえて よかったよ。\pなんとか じかんを つくって\nバトルに うちこむ ことに するよ。\pいままで ありがとう {PLAYER}{KUN}!\nいつか おれと しょうぶ しような!$"

gText_ApprenticePickWinSpeech6::
	.string "{JPN}きょうも ついてるわ!\n{PLAYER}さん あえて うれしい!\lいつもの ように アドバイスが ほしいの!\pドラムロール おねがい!\nさいごの しつもんは…\pしょうぶに かって かっこよく\nしめくくるなら なんと\lいえば いいかしら?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{JPN}{STR_VAR_1}\pそれ… すてきだわ!\nどうどうと して かっこいい! もらった!\p…ねえ わたしも すこしは\nさまに なって きたと おもわない?\pだから これからは ほかの トレーナーにも\nちょうせん しようと おもうの。\p{PLAYER}さんの アドバイスは ほんとうに たすかったわ。\pいつか わたしたちが たたかう ひも\nくるかも しれないわね!\pいままで ありがとう!$"

gText_ApprenticePickWinSpeech7::
	.string "{JPN}ああ {PLAYER}さん。\nおあいできて よかった!\pポケモンに ついては もう\nなやみは ありません。\pなやみは わたくし じしんです…\pトレーナーは しょうぶに かった とき\nひとこと いう ものでしょう?\pわたくしも ぜひ そうしたいの\nです!\pおねがいします かった ときに\nなんと いえば よいでしょう?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{JPN}{STR_VAR_1}\pああ! その ことば! こころが あらわれて\nうまれかわった ような きもちです!\pさっそく つかわせて いただきます!\pそして いまこそ おいとま いたします\n{PLAYER}さん…\pこれから おおぜいと たたかいますが\nおしえは けっして わすれません。\pいつの ひか また…\nさようなら!$"

gText_ApprenticePickWinSpeech8::
	.string "{JPN}ひゃっ {PLAYER}さんを みつけました!\nか かんげきです!\pああ そうだ! どうしても\nききたい ことが あったんです!\pすこしまえ しょうぶに かったんです。\nそこまでは うれしかったのですが!\pうれしすぎて むねが いっぱいに なって\nなにも いえなかったんです!\pだから {PLAYER}さん かった ときの\nきめゼリフを かんがえて ください!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{JPN}{STR_VAR_1}\pうわあああん!\nわたしが それを いうんですか?!\lう うれしくて どうにか なりそうです!\pあ ありがとう ございます!\nもう なにも おもいのこす ことは ありません!\pこれから たびに でて いろいろな ひとと\nたたかって きます。\pすべて {PLAYER}さんの おかげです。\nほんとうに ほんとうに ありがとう!\pもう いかなければ いつか たたかいの ばで\nおあい しましょう!$"

gText_ApprenticePickWinSpeech9::
	.string "{JPN}オラ ブエノ!\n{PLAYER}{KUN}!\pじつは あちこちを たびして\nたたかいたく なって きたんだ。\pその まえに もういちど\nアドバイスが ほしいんだ たのむ!\pしょうぶに かった とき まけた トレーナーに\nかっこよく いう ことばは\lなにが いいと おもう?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{JPN}{STR_VAR_1}\pおお それは しびれるぜ!\nシ ブエノ!\lさっそく いって みるぜ バシッと!\pそして いよいよ おわかれの じかんだ!\nいろいろ ありがとうな!\pいつか しょうぶ しような?\nアディオス!$"

gText_ApprenticePickWinSpeech10::
	.string "{JPN}{PLAYER}{KUN} たいへんだ!\pおれは しょうぶに かつと\n1じかんは じまんしつづけるんだ!\pもちろん うそだけどな!\nワハハハ!\pでも これは うそじゃ ない。\nおれは おしゃべりが にがてなんだ。\pだから ししょう かった あとに なんと\nいえば いいか きめて\lくれないか?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{JPN}{STR_VAR_1}\pそれを いえば いいんだな?\nじゃあ それは いわないで おくぜ!\pなんてな!\nししょうの おしえに したがうよ!\pいままで おしえて くれて ありがとう\nししょう!\pトレーナーって ものが やっと\nわかって きた きが するよ。\pこれから どんな トレーナーにも\nかって みせるぜ。\pいつか ししょうが あいてかもな!\pそれじゃあな!\nさらばだ ししょう!$"

gText_ApprenticePickWinSpeech11::
	.string "{JPN}ア ホ ー イ!\nつづりは あほい だぜ!\pラップする フネのり おれさま!\nこれが さいごの しつもんさ\lないたり するなよ!\pきめゼリフの しつもん\nこたえを たのむぜ!\pしょうぶに かったら どんな ふうに\nいえば かっこいいと おもう?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{JPN}{STR_VAR_1}\pかんぺきだ それを つかうぜ。\nあんたに きいて せいかいだった!\pそして そろそろ おれも\nすを とびだつ ときが きたようだ!\pおしえて くれて ありがとうな。\nこれから たたかいの たびに でるぜ!\pボ ン ボ ヤ ー ジ!\nつづりは ぼんぼやーじ\lあんたへの さいこうの はなむけさ!$"

gText_ApprenticePickWinSpeech12::
	.string "{JPN}やあ {PLAYER}!\nきょうも みつけたぜ!\pどうしよう また きいて みようか?\nなんてな もう きいて るぜ!\pところで {PLAYER}…\nきこえて いるかい?\lきこえて いるよな!\lもうすこし アドバイスが ほしいのさ!\pさけぶ ことばの はなしさ。\nたたかいが うまく おわった ときに\lいう かっこいい ことばだよ。\pさあ あんたの くちから ききたいぜ!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{JPN}{STR_VAR_1}\pいいね いいね!\nイカして るから それを つかうぜ!\pきく ことは もう なくなった。\nあとは てを ふって さよならだけさ。\pでも いつか どちらかが まける\nそんな ひが くるかもな。\pだが ほんとうに おわかれの ときだ。\pじゃあ {PLAYER} おれは たびを つづける\nでも おれの ことを わすれないでくれ!\pげんきでな {PLAYER}!\nあんたが すきだぜ!$"

gText_ApprenticePickWinSpeech13::
	.string "{JPN}{PLAYER}{KUN} おれは もう だめだ…\nはなみずが とまらないんだ…\pかった ときに いう かっこいい ことばを\nかんがえて いたんだが。\pかんげきしすぎて ないて しまって\nはなみずが とまらなく なったのさ…\pそんな わけで\nかわりに きめて くれ {PLAYER}{KUN}。\pしょうぶに かったら\nなんと いえば いいと おもう?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{JPN}{STR_VAR_1}\p… … …いいな。\nいや かんどうものだ!\lまた なみだが でて きたぞ!\pなみだと はなみずに まみれても\nその ことばを つかわせて もらうよ!\pきく ことは もう なくなった\n{PLAYER}{KUN}。\pこれからは ライバルだな!\nいままで ありがとう!$"

gText_ApprenticePickWinSpeech14::
	.string "{JPN}あの… その…\n{PLAYER}{KUN}…\pおねがい そんなに みないで。\nきんちょう して しまいます。\pま また アドバイスが ほしいんです。\nこれで さいごに しますから…\pはずかしいのですが しょうぶに かったら\nなんと いえば いいでしょう?\lおしえて ください。$"

gText_ApprenticeWinSpeechThanks14::
	.string "{JPN}{STR_VAR_1}\pあ… はい!\nいえるように して みます!\lきんちょうして いえないかも しれませんが…\pありがとう ございます {PLAYER}{KUN}。\nもう おわかれ ですね。\p{PLAYER}{KUN}に おしえて いただいた ことを\nまもって せいいっぱい がんばります。$"

gText_ApprenticePickWinSpeech15::
	.string "{JPN}ふむ? {PLAYER}{KUN}の ようですが…\nほんとうに そうですか?\lよく できた {PLAYER}にんぎょうでは?\pいえ いえ ごしんぱいなく!\nほんものなら さきほどの しつれいは\lわすれて ください。\pおこらないで ください。ほしいのは\nりっぱな アドバイスだけです。\pことばの ことなのですが。\pくわしく いえば しょうぶに かったら\nなんと いえば よいでしょう?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{JPN}{STR_VAR_1}\p… … … … … …\nしょうぶに かった ときに…\p{STR_VAR_1}\p…ほんきで おっしゃって いますか?\pなるほど ほんきなら けっこうです。\nおじかんを いただき ありがとう ございます。\pわたくしにも うまく つかえる ことばだと\nよいのですが。\pききたい ことも\nつきたようです。\pそろそろ おいとまして ひとりで\nあるきだす ときのようです。\pありがとう ございました ししょう!\nうたがった ことを おわび します!$"
