FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "{JPN}バトルテント シダケタウンかいじょうへ\nようこそ!\pいちげきトーナメントの ごあんない いたします!$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "{JPN}では いちげきトーナメントに\nちょうせん されますか?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "{JPN}また の ちょうせんを\nおまち して います!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "{JPN}シダケの バトルテントでは いちげき トーナメントを\nおこなって います。\pさんかは ポケモン 3びきの\nチームです。\p3びきは でる じゅんばんに ならべて\nください。\pしょうぶでは きめた じゅんばんに 1ぴきずつ でて\nいきます。\pいちど でた ポケモンは しょうぶが きまるまで\nひっこめられません。\p3ターンで きまらない ときは はんていに\nなります。\pとちゅうで やめる ときは かならず ゲームを\nほぞん して ください。\pほぞん しないと つづきから ちょうせん\nできません。\p3にんの トレーナーに つづけて\nかてば すてきな しょうひんを\lさしあげます。$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "{JPN}バトルテントへ ごあんない する まえに\nゲームを ほぞん します。 よろしいですか?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "{JPN}レベル50と オープンレベルの\n2しゅるいが あります。\lどちらに しますか?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "{JPN}では ポケモンを 3びき\nえらんで ください。$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "{JPN}ちょうせんしゃさま!\pさんかに ひつような ポケモン 3びきが\nそろって おりません。\pおなじ しゅるいの どうぐを もたせる ことも\nできません。\pタマゴ{STR_VAR_1} さんか できません。\pじゅんびが ととのいましたら\nまた おこし ください。$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "{JPN}ちょうせんしゃさま!\pさんかに ひつような ポケモン 3びきが\nそろって おりません。\pちがう しゅるいの ポケモンを 3びき\nつれて きて ください。\pおなじ しゅるいの どうぐを もたせる ことも\nできません。\pタマゴ{STR_VAR_1} さんか できません。\pじゅんびが ととのいましたら\nまた おこし ください。$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "{JPN}それでは バトルテントへ\nごあんない いたします。$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "{JPN}ちょうせんしゃさま!\pでんげんを きる まえに ゲームを ほぞん\nされませんでしたね?\pざんねんですが その ため\nちょうせんは むこうに\lなりました。\pもちろん あたらしく ちょうせんを はじめる ことは\nできます。$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "{JPN}みごとです! 3にんの トレーナーに\nつづけて かちました!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "{JPN}ゲームを ほぞん します。 すこし おまちください。$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "{JPN}3れんしょうの きねんに\nこちらの しょうひんを さしあげます。$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{JPN}{PLAYER}は しょうひんの\n{STR_VAR_1}を うけとった。$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "{JPN}おや?\nバッグが いっぱいのようですね。\pあきを つくってから しょうひんを\nうけとりに きて ください。$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "{JPN}ごさんか ありがとう ございました!\pゲームを ほぞん します。 すこし おまちください。$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "{JPN}また の ちょうせんを\nおまち して います!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "{JPN}おこしを おまち して\nおりました。\pバトルテントへ ごあんない する まえに ゲームを\nほぞん します。 おまちください。$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "{JPN}バトルテント シダケ… いえ\nハジツゲかいじょうへ ようこそ!\pここでは トレーナーの ポケモンへの\nしんらいが ためされます。$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "{JPN}ハジツゲの バトルテントに\nちょうせん しますか?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "{JPN}ハジツゲの バトルテントには かならず\nまもって いただく ルールが ひとつ\lあります。\pトレーナーが できるのは ポケモンを いれかえる\nことだけです。\pそれ いがいの しじは\nできません。\pポケモンは じぶんの せいかくに したがって\nじぶんで たたかいます。\pポケモンを しんじて みまもって あげて\nください。\p3にんの トレーナーに つづけて\nかてば しょうひんを\lさしあげます。\pとちゅうで やめる ときは かならず ゲームを\nほぞん して ください。\pほぞん せずに やめると ちょうせんは むこうに\nなります。$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "{JPN}こころと ポケモンの じゅんびが\nととのったら また おこし ください。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "{JPN}レベル50と オープンレベルの\n2しゅるいが あります。\lどちらに ちょうせん しますか?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "{JPN}はあ…\pちょうせんに ひつような ポケモン 3びきが\nそろって おりません。\pさんかには ちがう しゅるいの ポケモンが\n3びき ひつようです。\pおなじ しゅるいの どうぐを もたせる ことも\nできません。\pタマゴ{STR_VAR_1} さんか できません。\pじゅんびが ととのいましたら\nまた おこし ください。$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "{JPN}はあ…\pちょうせんに ひつような ポケモン 3びきが\nそろって おりません。\pさんかには ちがう しゅるいの ポケモンが\n3びき ひつようです。\pおなじ しゅるいの どうぐを もたせる ことも\nできません。\pタマゴ{STR_VAR_1} さんか できません。\pじゅんびが ととのいましたら\nまた おこし ください。$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "{JPN}けっこうです。 では ポケモンを\n3びき えらんで ください。$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "{JPN}バトルテントへ ごあんない する まえに\nほぞん します。 よろしいですか?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "{JPN}けっこうです。\nでは ついて きて ください。$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "{JPN}あなたの ポケモンの かつやくを\nみられて こうえいです。\pけっかを きろく します。\nすこし おまちください。$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "{JPN}3れんしょうを なしとげるとは…\pあなたと ポケモンの きずなは\nかたく たしかな もののようです。$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "{JPN}あなたの きろくを のこします。\nすこし おまちください。$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "{JPN}3れんしょうの きねんに\nこちらの しょうひんを さしあげます。$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "{JPN}バトルテント カイナかいじょうへ\nようこそ!\pバトルスワップの ごあんない\nいたします。$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "{JPN}バトルスワップに ちょうせん\nしますか?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "{JPN}カイナの バトルテントでは レンタルの\nポケモンを つかった バトルスワップを\lおこなって います。\pまず この たいかいよう ポケモンを 3びき おかし\nします。\pその レンタルポケモンで シングルバトルを\nおこないます。\pかつと レンタルポケモンを 1ぴき こうかん\nできます。\pこれを くりかえして 3れんしょう\nすると すてきな しょうひんが\lもらえます。\pとちゅうで やめる ときは かならず ゲームを\nほぞん して ください。\pほぞん せずに やめると ちょうせんは むこうに\nなります。$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "{JPN}また の おこしを おまち して います。$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "{JPN}どちらの レベルに ちょうせん しますか?\nレベル50 それとも レベル100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "{JPN}ちょうせんの まえに データを\nほぞん します。 よろしいですか?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "{JPN}では たいかいの あいだ あなたの\nポケモンを おあずかり します。$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "{JPN}どうぞ こちらへ。$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "{JPN}ごさんか ありがとう ございました!\pレンタルポケモンと ひきかえに\nあなたの ポケモンを おかえし します。\pけっかも ほぞん します。\nおまちください。$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "{JPN}レンタルポケモンと ひきかえに\nあなたの ポケモンを おかえし します。$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "{JPN}おめでとう ございます!\n3れんしょうです!\pレンタルポケモンと ひきかえに\nあなたの ポケモンを おかえし します。\pけっかも ほぞん します。\nおまちください。$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "{JPN}3れんしょうを たたえて\nこちらの しょうひんを さしあげます。$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "{JPN}おや?\nいれる ばしょが ないようですね。\pバッグに あきを つくって\nおしえて ください。$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "{JPN}おまち して おりました!\pちょうせんを さいかい する まえに\nゲームを ほぞん します。$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "{JPN}もうしわけ ありませんが まえに やめた とき\nほぞん されませんでした。\pその ため ちょうせんは\nむこうに なりました。$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "{JPN}あなたの ポケモンを おかえし します。$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{JPN}{PLAYER}は しょうひんの\n{STR_VAR_1}を うけとった。$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "{JPN}バトルスワップの ルールです。$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "{JPN}どの こうもくを よみますか?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "{JPN}バトルスワップでは ポケモンを 3びきしか\nつかえません。\pレンタルでも こうかんでも おなじ ポケモンを\n2ひき いじょう そろえる ことは\lできません。$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "{JPN}こうかん できるのは たったいま\nたおした トレーナーとだけです。\pこうかん できるのは たおした トレーナーが\nつかった ポケモンだけです。$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "{JPN}しょうぶに かつたびに たおした\nあいての ポケモンを 1ぴき こうかん\lできます。\p3にんめの トレーナーとは こうかん\nできません。$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "{JPN}こうかんの ときに きを つける ことが 2つ\nあります。\pまず こうかんの まえに うけとる\nポケモンの のうりょくを みる ことは\lできません。\pつぎに てもちの ポケモンは\nかりた じゅんばんに ならんで\lいます。\pこの じゅんばんは こうかん しても\nかわりません。$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "{JPN}カイナの バトルテントの ポケモンは\nすべて レンタルです。\pレンタルポケモンは すべて\nレベル30です。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "{JPN}ハジツゲの バトルテントの\nルールです。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "{JPN}どの こうもくを よみますか?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "{JPN}ハジツゲの バトルテントでは\nポケモンが じぶんで かんがえて\lたたかいます。\pやせいと ちがい ひとと くらす\nポケモンは せいかくに よって ふるまいが\lかわります。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "{JPN}せいかくに よっては なにが あっても こうげき\nしたがる ポケモンも います。\pぎゃくに みを まもろうと する ポケモンも\nいます。\pあいてを こまらせたり まどわせたりするのを このむ\nポケモンも います。\pせいかくに よって\nポケモンには とくいな わざが\lあります。\pぎゃくに つかいづらい にがてな わざも\nあるのです。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "{JPN}あいてに ちょくせつ ダメージを あたえる\nこうげきの わざが あります。\pあいての こうげきに そなえたり HPを\nかいふく したり する まもりの わざも\lあります。\pさらに どくや まひなどで\nあいてを よわらせる\lかわった わざも\lあります。\pポケモンは この 3つの なかから つかう わざを\nかんがえます。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "{JPN}トレーナーの しじが ないと\nポケモンは うまく つかえない わざも\lあります。\pにがてな わざは じょうずに\nつかえません。\pせいかくに あわない わざしか おぼえて\nいないと ちからを だしきれない ことが おおく\lなります。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "{JPN}せいかくに よっては ピンチに なると\nせいかくに あわない わざを つかいだす\lポケモンも います。\pピンチで ようすが おかしく なったら\nよく みて あげて ください。$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "{JPN}この バトルテントでは あいての レベルが\nあなたの ポケモンに あわせて\lちょうせい されます。\pただし レベル30より したの ポケモンは\nでて きません。$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "{JPN}ハジツゲの バトルテントの\nルールです。$"
