PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "{JPN}おとうさん: やあ {PLAYER}!\pとても めずらしい きのみを もらったんだ。\nおまえに あげよう。$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "{JPN}やわらかい つちに きのみが なって いたら\nじゆうに とって いいんだよ。\pでも おなじ ばしょに きのみを うえて おく。\nそれが れいぎと いう ものだ。\pほら これを わけて あげよう。$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "{JPN}その ようすだと\nトレーナーだね?\pトレーナーは よく ポケモンに きのみを もたせる\nものだ。\pそだてるか つかうかは きみの\nじゆうだよ。$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "{JPN}まいにち みずを やったの。\nたくさん はなが さいたわ。\pきのみも たくさん なったのよ。\pはい どうぞ!\nあげるわ!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "{JPN}いろいろな いろの きのみを つくれるように\nがんばるわ。\pあなたも がんばってね!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "{JPN}きょうは なにいろの きのみを\nさがそうかしら?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "{JPN}きのみクラッシャーが すきだから\nきのみを あつめて いるんだ。\pよければ 1つ わけて あげるよ。$"

Route114_Text_TryBerryCrushWithFriends:
	.string "{JPN}ともだちと きのみクラッシャーを\nためして みると いいよ。$"

Route114_Text_FunToThinkAboutBerries:
	.string "{JPN}どの きのみを うえようか。\nつかうか とっておくか。\pかんがえるのが たのしいのよ。$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "{JPN}きのみは ひざしを あびて そだつの。\pこまめに みずを やって\nそだてる。\pそれって あいじょうだと おもわない?$"

Route120_Text_YesYouUnderstand:
	.string "{JPN}そう そう。\nわかって くれるのね。\pこれを もって いって。$"

Route120_Text_MakeYourOwnImpressions:
	.string "{JPN}あら… でも じぶんの かんじかたが\nいちばん たいせつよね…\pこれを あげるわ。$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "{JPN}その きのみは めずらしいと おもうの。\nたいせつに そだててね。$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "{JPN}きのみは また きのみはかせから\nもらって くるわ。$"

LilycoveCity_Text_BerrySuitsYou:
	.string "{JPN}つまる ところ…\pスーツが わたしに にあうように\nすずしい かぜは うみに にあう。\pそして きみには きのみが にあう…\pなぜ だろうな?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "{JPN}つまる ところ…\pきみが トレーナーだからさ!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "{JPN}つまる ところ…\pおちついた そぼくさが わたしに にあうように\n{POKEBLOCK}は ポケモンに にあうのだ。$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "{JPN}わしを きのみはかせと よんで くれ。\pうつくしい はなで せかいを みたす。\nそれが ゆめでな きのみを そだてて\lみんなに くばって いるのじゃ。\pおまえさんにも 1つ やろう!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "{JPN}けちけち せずに\nもう 1つ もって いけ!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "{JPN}カナズミの ちかくの はなやにも\nぜひ よって いって おくれ。\pはなで せかいを みたすのじゃ!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "{JPN}きょうは ここまでじゃ。\nまた べつの ひに おいで。\pはなで せかいを みたすのじゃ!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "{JPN}うちの ひとの きのみの そだてかたは\nそりゃあ せかいいちでね。\pじまんの おっとですよ。\pところで おじょうちゃん さいきん\nいい ことばを きいたかい?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "{JPN}まあ! なんて すばらしい ことば!\nこころに ひびくねえ!\pこれを もって いって おくれ。$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "{JPN}おや! いい ことばだねえ。\nたいした ものだよ。\pこれを もって いって おくれ。$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "{JPN}4にんの まごには おっとより りっぱに\nなって ほしいねえ。\pよろこびの たえない まいにちだよ!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "{JPN}ああ…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "{JPN}いらっしゃい!\pここは はなやです。\nせかいじゅうに はなを ひろげるの!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{JPN}{PLAYER}{KUN} きのみに ついて\nしりたい?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "{JPN}おなまえは?\p{PLAYER}{KUN}。\nすてきな なまえね。\p{PLAYER}{KUN} きのみに ついて\nしりたい?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "{JPN}きのみは やわらかい つちでしか そだたない\nきに なるの。\pきのみを とったら また やわらかい つちに\n1つ うえて おいてね。\pうえた きのみは めを だし そだって\nうつくしい はなを さかせ また きのみを\lつけるのよ。\pせかいじゅうが うつくしい はなで\nみたされる ところを みたいの。\lそれが わたしの ゆめ。\p{PLAYER}{KUN} てつだってね。 きのみを うえて\nせかいに はなを ふやしましょう。$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "{JPN}はなは ひとを しあわせに\nするわよね?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "{JPN}いらっしゃい!\pはなは てを かけるほど うつくしく\nさくの。\pあなたも はなを そだてるのが すきに なるわ。\nきっとね。 これを あげる。$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "{JPN}きのみが そだつ あいだは ジョウロで\nみずを やってね。\pそれと もう ひとつ。\pしばらく とらないで いると きのみは\nじめんに おちて しまうの。\lでも また めを だすのよ。\pすごいでしょう?\nいきようと する ちからね。$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "{JPN}おねえちゃんたちの まねを して\nわたしも はなを そだてて いるの!\pはい どうぞ!\nあなたに あげる!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "{JPN}きのみは うえて そだてても いいし\nポケモンに もたせても いいの。\pでも いまは いろいろな きのみを まぜて\nポケモンの おかしを つくる きかいが\lあるんだって。\pわたしも おかしが ほしいな。$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "{JPN}こんにちは おなまえは?\p… … …  … … …  … … …\nそう すてきね!\pわたしは キリ。\pすこやかで やさしい こに そだつように\nパパと ママが つけて くれた\lなまえなの。\pこれを 1つ どうぞ。$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "{JPN}キリは これも あげちゃう!\nとっても きに いって いるのよ!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "{JPN}あなたの なまえには どんな ねがいが\nこめられて いるのかな。$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "{JPN}はる なつ あき ふゆ。\pはるに うまれたら はるが すきで\nなつに うまれたら なつが すきに\lなるのかな?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "{JPN}キリは あきに うまれたから\nあきが だいすき!\pあなたは どの きせつが すき?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "{JPN}そう…\nいいの…\pしりたい ことが たくさん あるの…$"
