gText_Birch_Welcome::
	.string "{JPN}やあ!\p$"

gText_Birch_Pokemon::
	.string "{JPN}ポケモン エメラルドローグへ ようこそ!\p$"

gText_Birch_MainSpeech::
	.string "{JPN}この ゲームでは ぼうけんに でる\nたびに…\pせかいも であう ポケモンも\nかわって いくんだ!\p$"

gText_Birch_AndYouAre::
	.string "{JPN}それでは…\nきみの ことを おしえて くれ$$"

gText_Birch_BoyOrGirl::
	.string "{JPN}すがたを えらんで ください$"

gText_Birch_AvatarStyle0::
	.string "{JPN}みための タイプを えらんで ください$"

gText_Birch_AvatarStyle1::
	.string "{JPN}ふくそうを えらんで ください$"

gText_Birch_WhatsYourName::
	.string "{JPN}きみの なまえは?$"

gText_Birch_HappyWithAvatar::
	.string "{JPN}この すがたで いいかな?\n「あとで かえられるよ」$"

gText_Birch_SoItsPlayer::
	.string "{JPN}きみは {PLAYER}{KUN}だね?$"

gText_Birch_YourePlayer::
	.string "{JPN}そうか わかった!\p{PLAYER}{KUN}!$"

gText_Birch_AreYouReady::
	.string "{JPN}けんきゅうじょで まって いるよ!\pついたら たずねて きて くれ。\p$"
