BerryBlender_Text_BlendWithTheBlendMaster:
	.string "{JPN}ブレンドマスター: いかにも!\nわたしこそ ブレンドマスター!\pわたしと ブレンドすれば その うでまえを\nめに する ことが できるぞ!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "{JPN}ブレンドマスター: ふむ! わたしの\nうでまえを みたいと いうのだな?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "{JPN}ふむ!\pいまは いそがしいと いうのだな!\pあんずるな!\nわたしは いちにちじゅう ここに おる!\lようが すんだら いそいで もどるが よい!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "{JPN}ふむ!\pきのみを ひとつも もって おらんな!\pわたしは いちにちじゅう ここに おる!\nきのみを もって いそいで もどるが よい!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "{JPN}むろん!\nむろんだ!\pところで…\nきのみから {POKEBLOCK}を つくる\lやりかたは しって おるか?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "{JPN}ふむ!\pなに かんたんな ことだ!\pブレンダーの はりが きみの しるしに\nきたら Aボタンを おすだけ。\pそれだけの ことよ。\pわたしが どれほど せいかくに\nAボタンを おすか みれば わかるだろう。$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "{JPN}よし!\pでは はじめると しよう!\pブレンドマスターと ともに\nきのみブレンダーだ!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "{JPN}ふむ!\p{POKEBLOCK}ケースを もって おらんな!\pわたしは いちにちじゅう ここに おる!\n{POKEBLOCK}ケースを てに いれて もどるが よい!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "{JPN}ふむ!\p{POKEBLOCK}ケースが いっぱいのようだ!\pわたしは いちにちじゅう ここに おる!\n{POKEBLOCK}を つかってから もどるが よい!$"

BerryBlender_Text_WhoaAwesome:
	.string "{JPN}うわあ!\nすごい!$"

BerryBlender_Text_WickedlyFast:
	.string "{JPN}とんでもない はやさだ!$"

BerryBlender_Text_WhatAnExpert:
	.string "{JPN}まさに たつじん!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "{JPN}マスターと ブレンドしたら\nすごい {POKEBLOCK}が できた!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "{JPN}きかいの ように はりを おいつづける め…\pとけいの ように せいかくに\nAボタンを たたく て…\pその ふたつを もつからこそ\nブレンドマスターは いだいなのだ。$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "{JPN}ブレンドマスターは やまおくで\nうでを みがいて いる はずなんだ。\pときどき ミナモに きては\nいちにちじゅう きのみを ブレンドして いる。$"
