CableClub_Text_WelcomeWhichCableClubService:
	.string "{JPN}ポケモンつうしんクラブへ\nようこそ。\pどの サービスを ごりように\nなりますか?$"

CableClub_Text_WhichService:
	.string "{JPN}どの サービスを ごりように\nなりますか?$"

CableClub_Text_TradeUsingLinkCable::
	.string "{JPN}つうしんケーブルで ほかの ひとと\nポケモンを こうかん します。$"

CableClub_Text_BattleUsingLinkCable::
	.string "{JPN}つうしんケーブルで ほかの トレーナーと\nしょうぶが できます。$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "{JPN}つうしんケーブルで ほかの ひとと\nきろくコーナーが つかえます。$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "{JPN}この メニューを とじます。$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "{JPN}ダブルバトルには ポケモンが\n2ひき いじょう ひつようです。$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "{JPN}こうかんには ポケモンが\n2ひき いじょう ひつようです。$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "{JPN}{STR_VAR_1}のみを もった ポケモンは\nこうかん できません。$"

gText_PleaseWaitForLink::
	.string "{JPN}おまちください。\n… … Bボタン やめる$"

gText_ConfirmLinkWhenPlayersReady::
	.string "{JPN}ぜんいんの じゅんびが できたら…\nAボタン けってい\lBボタン やめる$"

gText_ConfirmStartLinkWithXPlayers::
	.string "{JPN}{STR_VAR_1}にんで つうしんを はじめます。\nAボタン けってい\lBボタン やめる$"

gText_AwaitingLinkup::
	.string "{JPN}つうしんを まって います…\n… … Bボタン やめる$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "{JPN}つうしんの まえに ぼうけんを\nほぞん します。 よろしいですか?$"

CableClub_Text_PleaseEnter:
	.string "{JPN}おはいり ください。$"

CableClub_Text_DirectYouToYourRoom:
	.string "{JPN}おへやへ ごあんない いたします。$"

Text_SomeoneIsNotReadyToLink:
	.string "{JPN}じゅんびの できて いない かたが います。\pみなさまの したくが ととのってから\nまた おこし ください。$"

Text_LinkErrorPleaseReset:
	.string "{JPN}もうしわけ ありません つうしん エラーです…\nリセットして やりなおして ください。$"

Text_PlayersMadeDifferentSelections:
	.string "{JPN}あいての かたと えらんだ ものが\nちがうようです。$"

CableClub_Text_PleaseVisitAgain:
	.string "{JPN}また の おこしを おまち して います。$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "{JPN}さんかする にんずうが\nただしく ありません。$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "{JPN}シングルバトルは {STR_VAR_1}にんでは\nあそべません。$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "{JPN}ダブルバトルは {STR_VAR_1}にんでは\nあそべません。$"

CableClub_Text_NeedFourPlayers:
	.string "{JPN}この バトルモードは 4にん\nそろわないと あそべません。$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "{JPN}にんずうを たしかめて\nもういちど おねがい します。$"

Text_TerminateLinkConfirmation:
	.string "{JPN}へやを でると つうしんが おわります。\nよろしいですか?$"

Text_TerminateLinkPleaseWait:
	.string "{JPN}つうしんを おわります…\nおへやから ごあんない します。\lおまちください。$"

CableClub_Text_TooBusyToNotice:
	.string "{JPN}この トレーナーは いそがしくて\nきづかない ようです…$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "{JPN}やった! {STR_VAR_1}の トレーナーカードを\nみせて もらった!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "{JPN}やった! {STR_VAR_1}の トレーナーカードを\nみせて もらった!\p{STR_VAR_2}カードだ!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "{JPN}せきに ついて しょうぶを\nはじめて ください。$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "{JPN}せきに ついて こうかんを\nはじめて ください。$"

RecordCorner_Text_ThanksForComing:
	.string "{JPN}おこし いただき ありがとう ございます。$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "{JPN}トレーナーカードの データを\nかきかえます。$"

CableClub_Text_HopeToSeeYouAgain:
	.string "{JPN}また の おこしを おまち して います!$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "{JPN}もうしわけ ありません。\pとおくの ちほうの トレーナーとの\nこうかんには まだ たいおう して\lおりません…$"

CableClub_Text_OtherTrainerNotReady:
	.string "{JPN}あいての トレーナーの じゅんびが\nできて いません。$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "{JPN}こうかんに だせない ポケモンが\n1ぴき いじょう います。$"

RecordCorner_Text_TakeSeatAndWait:
	.string "{JPN}せきに ついて おまちください。$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{JPN}{STR_VAR_1}から {STR_VAR_2}が\nおくられて きた。$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "{JPN}もうしわけ ありません つうしん エラーです。\pにほんごばんの ルビー サファイアとは  \nきろくを まぜられません。\pまた にほんごばんの エメラルドと\nかいがいばんの ルビー サファイアを\lどうじに まぜる ことも できません。$"

CableClub_Text_AdapterNotConnected:
	.string "{JPN}ワイヤレスアダプタが\nただしく つながって いません。$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "{JPN}さんかの かたは うけつけカウンターへ\nおこし ください。$"

@ Unused
CableClub_Text_Hello:
	.string "{JPN}いらっしゃいませ!$"

@ Unused
CableClub_Text_PleaseWait:
	.string "{JPN}おまちください。$"

CableClub_Text_YouMayTradeHere::
	.string "{JPN}ここで ほかの トレーナーと ポケモンを\nこうかん できます。$"

CableClub_Text_YouMayBattleHere::
	.string "{JPN}ここで ともだちと しょうぶが\nできます。$"

CableClub_Text_CanMakeBerryPowder::
	.string "{JPN}2にんから 5にんで きのみパウダーを\nつくれます。$"

CableClub_Text_CanMixRecords::
	.string "{JPN}2にんから 4にんの きろくを\nまぜられます。$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "{JPN}ワイヤレスクラブの サービスの\nごあんない。$"

CableClub_Text_CancelSelectedItem::
	.string "{JPN}えらんだ メニューを とりけします。$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "{JPN}どの バトルモードに しますか?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "{JPN}ひとつ まえに もどります。$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "{JPN}きのみクラッシュを つかうには\nきのみが 1つ いじょう ひつようです。$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "{JPN}ユニオンルームに はいるには\nポケモンが 2ひき いじょう ひつようです。$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "{JPN}{STR_VAR_1}のみを もった ポケモンは\nユニオンルームに はいれません。$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "{JPN}ここは ポケモンワイヤレスクラブの\nユニオンルームです。\pもうしわけ ありませんが ワイヤレス\nアダプタが ただしく つながって いません。\pまた の おこしを おまち して います。$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "{JPN}あら…\nしつれい しました!$"

CableClub_Text_PlayerIsWaiting:
	.string "{JPN}いま {STR_VAR_1}が あそんで\nいるようです。\lがんばって!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "{JPN}あそびかたを せつめい\nしますよ。\pどの ゲームの せつめいを しましょう?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "{JPN}「ポケモンなわとび」\pAボタンで ポケモンに つるのムチの なわを\nとばせます。\p70センチくらいまでの ちいさな ポケモンだけ\nさんか できます。\pおよぐだけ もぐるだけ とぶだけの ポケモンは\nとぶのが にがてです。\pそのため さんか\nできません。\pみんなの タイミングが あうと いい ことが\nおきますよ。$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "{JPN}「ドードリオの きのみどり」\pドードリオの 3つの あたまを うごかして\nおちて くる きのみを うけとめます。\p{PLUS}ボタンの みぎ うえ ひだりで\nあたまを うごかします。\pこの ゲームには ドードリオが\nひつようです。$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "{JPN}ゲームで あそびたい ときは\nとなりの おじいさんに いって ください。$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "{JPN}やあ いらっしゃい!\nワイヤレスつうしんで ゲームを\lしに きたのかい?\pすこし まって くれるかね?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "{JPN}よし また おいで!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "{JPN}ワイヤレスアダプタが つながって おらん。\nつないでから また おいで!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "{JPN}よし どの ゲームで\nあそびたいのかね?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "{JPN}どの ポケモンを\nださるかね?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "{JPN}よし じゅんびは できたぞ。\nほかの ものに まけるでないぞ!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "{JPN}もう かえるのかね?\nまた おいで!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "{JPN}だせる ポケモンが\nおらんようじゃな…\pどんな ポケモンが だせるのか せつめい\nしようかね?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "{JPN}「ポケモンなわとび」は 70センチくらいまでの\nポケモンが さんか できる。\pだせないのは とべない\nポケモンじゃ。\pほれ およぐだけ もぐるだけ とぶだけの\nポケモンじゃな。\pそれだけ わかって おれば よい。$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "{JPN}ドードリオの きのみどりは ドードリオだけが\nさんか できる ゲームじゃ。$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "{JPN}もういちど はじめから やりなおして\nくれるかね?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "{JPN}ポケモンワイヤレスクラブの ダイレクトコーナーへ\nようこそ。\pここでは ともだちと ちょくせつ やりとり\nできます。\pどの へやに\nはいりますか?$"

CableClub_Text_TradePokemon:
	.string "{JPN}ポケモンを こうかん しますか?$"

CableClub_Text_PlayWhichBattleMode:
	.string "{JPN}どの バトルモードで\nあそびますか?$"

CableClub_Text_AccessRecordCorner:
	.string "{JPN}きろくコーナーを\nつかいますか?$"

CableClub_Text_UseBerryCrush:
	.string "{JPN}きのみクラッシュを\nつかいますか?$"

CableClub_Text_ExplainBattleModes:
	.string "{JPN}バトルモードは 3しゅるい あります。\pシングルバトルは ポケモンを 1ぴき いじょう\nもった 2にんで あそびます。\pそれぞれ 1ぴきずつ しょうぶに\nだします。\pダブルバトルは ポケモンを 2ひき いじょう もった\n2にんで あそびます。\pそれぞれ 2ひきずつ しょうぶに\nだします。\pマルチバトルは ポケモンを 1ぴき いじょう もった\n4にんで あそびます。\pそれぞれ 1ぴきずつ しょうぶに\nだします。$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "{JPN}ふたりの どちらが リーダーに なるか\nきめて ください。\pもう ひとりは「なかまに はいる」を\nえらんで ください。$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "{JPN}4にんの だれが リーダーに なるか\nきめて ください。\pほかの かたは「なかまに はいる」を\nえらんで ください。$"

CableClub_Text_ChooseGroupLeader:
	.string "{JPN}だれが リーダーに なるか\nきめて ください。\pほかの かたは「なかまに はいる」を\nえらんで ください。$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "{JPN}ポケモンワイヤレスクラブの\nユニオンルームへ ようこそ。\pここでは しらない かたも ふくめて\nほかの トレーナーと ちょくせつ\lやりとり できます。\pおへやに はいりますか?$"

CableClub_Text_UnionRoomInfo:
	.string "{JPN}ユニオンルームの トレーナーは\nおなじく はいって いる まわりの\lかたたちです。\pあいさつを かわしたり いろいろな\nことが できます。\pレベル30までの ポケモンを 2ひき だして\n1たい1の しょうぶが できます。\p2にんから 5にんで チャットも\nできます。\pこうかんに だす ポケモンを\nとうろく する ことも できます。\pおへやに はいりますか?$"

CableClub_Text_EnjoyUnionRoom:
	.string "{JPN}ユニオンルームを おたのしみ\nください。$"

CableClub_Text_FirstTimeRightThisWay:
	.string "{JPN}こんにちは! わたしは ティーラと\nもうします。\pこちらは\nはじめてですね。\pワイヤレスつうしんの しくみを ごあんない\nします。\pまずは この ポケモンセンターの フロアの\nごあんないから。\pこちらへ どうぞ。$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "{JPN}さいじょうかいには おへやが\n2つ あります。\pまず ひだりの おへや。\nユニオンルームです。\pおなじく ユニオンルームに はいって\nいる まわりの トレーナーと\lつながる ことが できます。\pチャットや しょうぶ こうかんなどが\nできます。\pつぎに みぎの おへやは\nダイレクトコーナーです。\pここでは ともだちと ポケモンの\nこうかんや しょうぶが できます。\pワイヤレスアダプタが なくても\nつうしんケーブルを つかえば\lつながる ことが できます。\pその ばあいは ダイレクトコーナーへ\nおこし ください。\pワイヤレスつうしんを\nおたのしみ ください。$"

CableClub_Text_AskAboutLinking:
	.string "{JPN}こんにちは {PLAYER}!\pポケモンセンター2かいの\nかかりの ティーラです。\pつうしんに ついて なにか\nおききに なりたい ことは?$"

CableClub_Text_ExplainWirelessClub:
	.string "{JPN}ポケモンワイヤレスクラブの\nしくみを ごせつめい します。\pこの さいじょうかいには おへやが\n2つ あります。\pまず ひだりの おへや。\nユニオンルームです。\pおなじく ユニオンルームに はいって\nいる まわりの トレーナーと\lつながる ことが できます。\pチャットや しょうぶ こうかんなどが\nできます。\pつぎに みぎの おへやは\nダイレクトコーナーです。\pここでは ともだちと ポケモンの\nこうかんや しょうぶが できます。\pユニオンルームや ダイレクトコーナーで\nともだちが みつからない ことも\lあります。\pその ときは ともだちの ちかくへ\nいどうして ください。\pワイヤレスアダプタが なくても\nつうしんケーブルを つかえば\lつながる ことが できます。\pその ばあいは ダイレクトコーナーへ\nおこし ください。\pワイヤレスつうしんを\nおたのしみ ください。$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "{JPN}ワイヤレスつうしんを\nおたのしみ ください。$"
