Text_PictureBookShelf:
	.string "{JPN}ポケモンの えほんが ならんで いる。$"

Text_BookShelf:
	.string "{JPN}いろいろな ほんで いっぱいだ。$"

Text_PokemonCenterBookShelf:
	.string "{JPN}ポケモンの ざっしだ!\nポケモンのともだち…\pポケモンずかんハンドブック…\nかわいい ポケモン…$"

Text_Vase:
	.string "{JPN}たかそうな つぼだ…\nなかを のぞいて みた…\pだが からっぽだった。$"

Text_EmptyTrashCan:
	.string "{JPN}からっぽだ。$"

Text_ShopShelf:
	.string "{JPN}たなには ポケモングッズが\nぎっしり ならんで いる。$"

Text_Blueprint:
	.string "{JPN}なにかの せっけいずだろうか?\nふくざつすぎて わからない!$"
