@ With the exception of Link standby, none of the below texts are used

gTest_MissedTurn::
	.string "{JPN}ばんを とばした$"

gText_LinkStandby4::
	.string "{JPN}つうしん たいき!$"

gText_WinnerIsPlayersMonCongrats::
	.string "{JPN}ゆうしょうは {STR_VAR_1}の {STR_VAR_2}!\nおめでとう ございます!$"

gText_WinnerIsPlayersMon::
	.string "{JPN}ゆうしょうは {STR_VAR_1}の {STR_VAR_2}!{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "{JPN}いちじ しんさ ナンバー {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "{JPN}にじ しんさ ナンバー {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "{JPN}セット イベント ナンバー {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "{JPN}いちばん つかわれた わざ\n{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "{JPN}もっとも みごとな ポケモン\n{STR_VAR_1}の {STR_VAR_2}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "{JPN}セット イベント ナンバー {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "{JPN}トレーナーが まけたので つうしんの\nテレビばんぐみは つくられません。{PAUSE_UNTIL_PRESS}$"
