gContestHallPaintingCaption::
	.string "{JPN}{STR_VAR_1}\n{STR_VAR_2}の {STR_VAR_3}$"

@ Unused
gContestPaintingContest::
	.string "{JPN}コンテスト$"

gContestRankNormal::
	.string "{JPN}ノーマルランク$"

gContestRankSuper::
	.string "{JPN}スーパーランク$"

gContestRankHyper::
	.string "{JPN}ハイパーランク$"

gContestRankMaster::
	.string "{JPN}マスターランク$"

gContestLink::
	.string "{JPN}つうしん$"

gContestCoolness::
	.string "{JPN}かっこよさ$"

gContestBeauty::
	.string "{JPN}うつくしさ$"

gContestCuteness::
	.string "{JPN}かわいさ$"

gContestSmartness::
	.string "{JPN}かしこさ$"

gContestToughness::
	.string "{JPN}たくましさ$"

gContestPaintingCool1::
	.string "{JPN}とまらない かっこよさ\nはかりしれない {STR_VAR_1}$"

gContestPaintingCool2::
	.string "{JPN}やあ どうも!\nみばえの いい ポケモン {STR_VAR_1}$"

gContestPaintingCool3::
	.string "{JPN}すばらしくて すてきで\nとても いだいな {STR_VAR_1}$"

gContestPaintingBeauty1::
	.string "{JPN}せいきさいごの ビーナス\nうつくしき {STR_VAR_1}$"

gContestPaintingBeauty2::
	.string "{JPN}{STR_VAR_1}の まばゆく\nきらめく えがお$"

gContestPaintingBeauty3::
	.string "{JPN}ポケモンセンターの スーパーアイドル\nくらぶ ものなき {STR_VAR_1}$"

gContestPaintingCute1::
	.string "{JPN}かわいくて あまい {STR_VAR_1}$"

gContestPaintingCute2::
	.string "{JPN}かわいい {STR_VAR_1}の\nゆうしょうの しょうぞうが$"

gContestPaintingCute3::
	.string "{JPN}ウインクを ひとつ!\nキュートな ポケモン {STR_VAR_1}$"

gContestPaintingSmart1::
	.string "{JPN}かしこさの きょしょう\nかしこき ポケモン {STR_VAR_1}$"

gContestPaintingSmart2::
	.string "{JPN}{STR_VAR_1} すべての ポケモンの\nなかから えらばれし もの$"

gContestPaintingSmart3::
	.string "{JPN}みごとな {STR_VAR_1}の\nゆうがな ひととき$"

gContestPaintingTough1::
	.string "{JPN}きんにく りゅうりゅう\nはやての {STR_VAR_1}$"

gContestPaintingTough2::
	.string "{JPN}つよく より つよく\nもっとも つよい {STR_VAR_1}$"

gContestPaintingTough3::
	.string "{JPN}たくましく はげしい\nハイパー ポケモン {STR_VAR_1}$"
