@ Contest move effect descriptions

gText_HighlyAppealingMove::
	.string "{JPN}とても めだつ わざ。$"

gText_UserMoreEasilyStartled::
	.string "{JPN}この わざの あと おどろき\nやすく なる。$"

gText_GreatAppealButNoMoreToEnd::
	.string "{JPN}おおいに めだつが\nそれいこう だせなく なる。$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "{JPN}つづけて つかっても\nしんさいんが あきない。$"

gText_AvoidStartledByOthersOnce::
	.string "{JPN}1かいだけ ほかの ポケモンに\nおどろかされなく なる。$"

gText_AvoidStartledByOthers::
	.string "{JPN}ほかの ポケモンに\nおどろかされなく なる。$"

gText_AvoidStartledByOthersLittle::
	.string "{JPN}ほかの ポケモンに\nすこし おどろかされにくく なる。$"

gText_UserLessLikelyStartled::
	.string "{JPN}この わざの あと\nおどろきにくく なる。$"

gText_SlightlyStartleFrontMon::
	.string "{JPN}まえの ポケモンを\nすこし おどろかせる。$"

gText_SlightlyStartleAppealed::
	.string "{JPN}アピール ずみの ポケモンを\nすこし おどろかせる。$"

gText_StartleAppealedBeforeUser::
	.string "{JPN}じぶんの まえに アピール した\nポケモンを おどろかせる。$"

gText_StartleAllAppealed::
	.string "{JPN}アピール ずみの ポケモン\nぜんいんを おどろかせる。$"

gText_BadlyStartleFrontMon::
	.string "{JPN}まえの ポケモンを\nひどく おどろかせる。$"

gText_BadlyStartleAppealed::
	.string "{JPN}アピール ずみの ポケモンを\nひどく おどろかせる。$"

gText_StartleAppealedBeforeUser2::
	.string "{JPN}じぶんの まえに アピール した\nポケモンを おどろかせる。$"

gText_StartleAllAppealed2::
	.string "{JPN}アピール ずみの ポケモン\nぜんいんを おどろかせる。$"

gText_ShiftJudgesAttentionFromOthers::
	.string "{JPN}しんさいんの ちゅうもくを\nほかから そらす。$"

gText_StartleMonHasJudgesAttention::
	.string "{JPN}しんさいんが ちゅうもく して\nいる ポケモンを おどろかせる。$"

gText_JamOthersMissesTurn::
	.string "{JPN}ほかを じゃま するが\n1かい アピール できなく なる。$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "{JPN}おなじ タイプの アピールを した\nポケモンを おどろかせる。$"

gText_BadlyStartleCoolAppeals::
	.string "{JPN}かっこよさの アピールを した\nポケモンを ひどく おどろかせる。$"

gText_BadlyStartleBeautyAppeals::
	.string "{JPN}うつくしさの アピールを した\nポケモンを ひどく おどろかせる。$"

gText_BadlyStartleCuteAppeals::
	.string "{JPN}かわいさの アピールを した\nポケモンを ひどく おどろかせる。$"

gText_BadlyStartleSmartAppeals::
	.string "{JPN}かしこさの アピールを した\nポケモンを ひどく おどろかせる。$"

gText_BadlyStartleToughAppeals::
	.string "{JPN}たくましさの アピールを した\nポケモンを ひどく おどろかせる。$"

gText_MakeMonAfterUserNervous::
	.string "{JPN}じぶんの つぎの ポケモンを\nきんちょう させる。$"

gText_MakeAllMonsAfterUserNervous::
	.string "{JPN}じぶんより あとの ポケモン\nぜんいんを きんちょう させる。$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "{JPN}アピール ずみの ポケモンの\nちょうしを わるく する。$"

gText_BadlyStartleMonsGoodCondition::
	.string "{JPN}ちょうしの よい ポケモンを\nひどく おどろかせる。$"

gText_AppealGreatIfPerformedFirst::
	.string "{JPN}さいしょに だすと\nよく めだつ。$"

gText_AppealGreatIfPerformedLast::
	.string "{JPN}さいごに だすと\nよく めだつ。$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "{JPN}まえの ポケモンたちと\nおなじだけ めだつ。$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "{JPN}すぐ まえの ポケモンと\nおなじだけ めだつ。$"

gText_AppealBetterLaterItsPerformed::
	.string "{JPN}あとに だすほど\nよく めだつ。$"

gText_AppealVariesDependingOnTiming::
	.string "{JPN}だす じゅんばんで\nめだちかたが かわる。$"

gText_WorksWellIfSameTypeAsBefore::
	.string "{JPN}まえと おなじ タイプなら\nよく めだつ。$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "{JPN}まえと ちがう タイプなら\nよく めだつ。$"

gText_AffectedByAppealInFront::
	.string "{JPN}まえの アピールの できに\nえいきょう される。$"

gText_UpsConditionHelpsPreventNervousness::
	.string "{JPN}ちょうしが あがる。\nきんちょうを ふせぎやすく なる。$"

gText_AppealWorksWellIfConditionGood::
	.string "{JPN}ちょうしが よいと\nよく めだつ。$"

gText_NextAppealMadeEarlier::
	.string "{JPN}つぎの ターン はやく\nアピール できる。$"

gText_NextAppealMadeLater::
	.string "{JPN}つぎの ターン おそく\nアピール する。$"

gText_TurnOrderMoreEasilyScrambled::
	.string "{JPN}つぎの ターンの じゅんばんが\nみだれやすく なる。$"

gText_ScrambleOrderOfNextAppeals::
	.string "{JPN}つぎの ターンの アピールの\nじゅんばんを みだす。$"

gText_AppealExcitesAudienceInAnyContest::
	.string "{JPN}どの コンテストでも\nかんきゃくが もりあがる アピール。$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "{JPN}よい アピールを した ポケモン\nぜんいんを ひどく おどろかせる。$"

gText_AppealBestMoreCrowdExcited::
	.string "{JPN}かんきゃくが もりあがって\nいるほど よく めだつ。$"

gText_TemporarilyStopCrowdExcited::
	.string "{JPN}しばらく かんきゃくが\nもりあがらなく なる。$"

@ Unused move names

gText_RainDance::
	.string "{JPN}あまごい$"

gText_Rage::
	.string "{JPN}いかり$"

gText_FocusEnergy::
	.string "{JPN}きあいだめ$"

gText_Hypnosis::
	.string "{JPN}さいみんじゅつ$"

gText_Softboiled::
	.string "{JPN}タマゴうみ$"

gText_HornAttack::
	.string "{JPN}つのでつく$"

gText_SwordsDance::
	.string "{JPN}つるぎのまい$"

gText_Conversion::
	.string "{JPN}テクスチャー$"

gText_SunnyDay::
	.string "{JPN}にほんばれ$"

gText_Rest2::
	.string "{JPN}ねむる$"

gText_Vicegrip::
	.string "{JPN}はさむ$"

gText_DefenseCurl::
	.string "{JPN}まるくなる$"

gText_LockOn::
	.string "{JPN}ロックオン$"

@ Contest type names

gContestMoveTypeCoolText::
	.string "{JPN}かっこよさ$"

gContestMoveTypeBeautyText::
	.string "{JPN}うつくしさ$"

gContestMoveTypeCuteText::
	.string "{JPN}かわいさ$"

gContestMoveTypeSmartText::
	.string "{JPN}かしこさ$"

gContestMoveTypeToughText::
	.string "{JPN}たくましさ$"

gText_AppealNumWhichMoveWillBePlayed::
	.string "{JPN}アピール {STR_VAR_1}かいめ!\nどの わざを つかう?$"

gText_AppealNumButItCantParticipate::
	.string "{JPN}アピール {STR_VAR_1}かいめ!\nでも さんか できない!$"

gText_MonAppealedWithMove::
	.string "{JPN}{STR_VAR_1}は {STR_VAR_2}で\nアピール した!$"

gText_MonWasWatchingOthers::
	.string "{JPN}{STR_VAR_1}は ほかの ようすを\nみて いた。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AllOutOfAppealTime::
	.string "{JPN}アピールタイムは\nこれで おしまい!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

@ Unused appeal result texts

gText_ButAppealWasJammed::
	.string "{JPN}しかし アピールは\nじゃま された。$"

gText_FollowedAnotherMonsLead::
	.string "{JPN}ほかの ポケモンに\nあわせた。$"

gText_ButItMessedUp::
	.string "{JPN}しかし しくじって しまった。$"

gText_WentBetterThanUsual::
	.string "{JPN}いつもより うまく\nいった。$"

gText_JudgeLookedAwayForSomeReason::
	.string "{JPN}しんさいんは なぜか\nよそを むいて いた。$"

gText_WorkedHardToBuildOnPastMistakes::
	.string "{JPN}しっぱいを とりかえそうと\nがんばった。$"

gText_CantMakeAnyMoreMoves::
	.string "{JPN}もう わざを\nだせない。$"

gText_WorkedFrighteninglyWell::
	.string "{JPN}おそろしいほど うまく\nいった。$"

gText_WorkedHardAsStandoutMon::
	.string "{JPN}めだって いる ポケモンに\nまけないくらい がんばった。$"

gText_JudgedLookedOnExpectantly::
	.string "{JPN}しんさいんは きたいを こめて\nみつめて いた。$"

gText_WorkedRatherWell::
	.string "{JPN}なかなか うまく いった。$"

gText_WorkedLittleBetterThanUsual::
	.string "{JPN}いつもより すこし\nうまく いった。$"

@ Round result texts

gText_MonFailedToStandOutAtAll::
	.string "{JPN}{STR_VAR_1}は まったく\nめだたなかった…{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch::
	.string "{JPN}{STR_VAR_1}は あまり\nめだたなかった…{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention::
	.string "{JPN}{STR_VAR_1}は すこし\nちゅうもくを あつめた。{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention::
	.string "{JPN}{STR_VAR_1}は おおいに\nちゅうもくを あつめた。{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention::
	.string "{JPN}{STR_VAR_1}は ちゅうもくを\nひとりじめ した。{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal::
	.string "{JPN}{STR_VAR_1}は まだ\nアピール して いない。{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2::
	.string "{JPN}つぎの {STR_VAR_1}の アピールに\nきたいが たかまった。$"

gText_EmptyContestString::
	.string "{JPN}$"

gText_JudgesViewsOnMonHeldFirm::
	.string "{JPN}{STR_VAR_1}への しんさいんの\nみかたは かわらなかった。$"

gText_MonsXChangedPerceptions::
	.string "{JPN}{STR_VAR_1}の {STR_VAR_3}が\nみかたを かえさせた。$"

gText_MonsAppealEffectWoreOff::
	.string "{JPN}{STR_VAR_1}の アピールの\nこうかが きれた。$"

gText_SpecialAppealsEffectWoreOff::
	.string "{JPN}とくべつな アピールの\nこうかが きれた。$"

gText_EveryonesAppealsMadeToLookSame::
	.string "{JPN}みんなの アピールが\nおなじように みえて しまった。$"

gText_CheapenedMonsAppeal::
	.string "{JPN}{STR_VAR_2}の アピールを\nかすませた。$"

gText_CheapenedAppealOfThoseAhead::
	.string "{JPN}まえの ポケモンたちの\nアピールを かすませた。$"

gText_StoleAttentionAwayFromMon::
	.string "{JPN}{STR_VAR_2}から ちゅうもくを\nうばいとった。$"

gText_CheapenedMonsAppeal2::
	.string "{JPN}{STR_VAR_2}の アピールを\nかすませた。$"

gText_SeverelyCheapenedOtherAppeals::
	.string "{JPN}ほかの アピールを\nおおいに かすませた。$"

gText_AnticipationSwelledForMonsAppealNext::
	.string "{JPN}つぎの {STR_VAR_1}の アピールに\nきたいが たかまった。$"

gText_CheapenedAppealOfThoseAhead2::
	.string "{JPN}まえの ポケモンたちの\nアピールを かすませた。$"

gText_CheapenedJudgesFavoriteAppeal::
	.string "{JPN}しんさいんの おきにいりの\nアピールを かすませた。$"

gText_AppealsOfOthersCheapenedByHalf::
	.string "{JPN}ほかの アピールを\nはんぶん かすませた。$"

gText_StoodOutToMakeUpForBeingJammed::
	.string "{JPN}じゃまされた ぶんを\nとりかえすように めだった。$"

gText_CantParticipateInAppealsAnyMore::
	.string "{JPN}もう アピールに\nさんか できない。$"

gText_TouchedJudgeForFantasticAppeal::
	.string "{JPN}しんさいんに ふれて\nすばらしい アピールに なった。$"

gText_AnticipationRoseForUpcomingAppeals::
	.string "{JPN}つぎの アピールへの きたいが\nたかまった。$"

gText_StoodOutAsMuchAsSpecialAppeals::
	.string "{JPN}とくべつな アピールと\nおなじくらい めだった。$"

gText_StoodOutAsMuchAsMon::
	.string "{JPN}{STR_VAR_1}と おなじくらい\nめだった。$"

gText_JammedAppealsMadeEvenLessNoticeable::
	.string "{JPN}じゃまされた アピールが\nさらに めだたなく なった。$"

gText_EveryonesAppealsMadeSame::
	.string "{JPN}みんなの アピールが\nおなじに なって しまった。$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.string "{JPN}ほかの ポケモンが\nきに なりだした。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{JPN}{STR_VAR_1}は これいじょう\nアピール できない。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "{JPN}すこしだけ\nおちついた。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "{JPN}ほかの ポケモンが\nきに ならなく なった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "{JPN}ほかの ポケモンが\nあまり きに ならなく なった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "{JPN}ほかの ポケモンを\nきに しなく なった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "{JPN}ほかの ポケモンを\nおどろかせようと した。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "{JPN}ほかの ポケモンの めを\nくらませようと した。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "{JPN}しんさいんは {STR_VAR_1}から\nめを そらした。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "{JPN}つぎの ポケモンを\nきんちょう させようと した。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{JPN}{STR_VAR_1}は\nきんちょう した。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "{JPN}まって いる ポケモンを\nきんちょう させようと した。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "{JPN}ちょうしの よい ポケモンを\nちょうはつ した。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{JPN}{STR_VAR_1}は ちょうしを\nとりもどした。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "{JPN}ちょうしの よい ポケモンを\nじゃま しようと した。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "{JPN}めだって いる {STR_VAR_1}は\nさらに はりきった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "{JPN}めだって いない {STR_VAR_1}は\nがんばった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "{JPN}まえの ポケモンたちと\nおなじだけ がんばった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "{JPN}{STR_VAR_1}の アピールは\nうまく いかなかった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "{JPN}すぐ まえの ポケモンと\nおなじだけ がんばった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "{JPN}{STR_VAR_1}の アピールは\nうまく いかなかった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "{JPN}{STR_VAR_1}の アピールは\nうまく いかなかった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "{JPN}{STR_VAR_1}の アピールは\nすこし うまく いった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "{JPN}{STR_VAR_1}の アピールは\nなかなか うまく いった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "{JPN}{STR_VAR_1}の アピールは\nみごとに きまった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "{JPN}{STR_VAR_1}の アピールは\nさっぱりだった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "{JPN}{STR_VAR_1}の アピールは\nあまり うまく いかなかった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "{JPN}{STR_VAR_1}の アピールは\nすこし うまく いった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "{JPN}{STR_VAR_1}の アピールは\nなかなか うまく いった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "{JPN}{STR_VAR_1}の アピールは\nとても うまく いった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "{JPN}{STR_VAR_1}の アピールは\nみごとに きまった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "{JPN}まえの ポケモンと おなじ タイプ。\nこれは いい!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "{JPN}まえの ポケモンと ちがう タイプ。\nこれは いい!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "{JPN}まえの ポケモンより\nずっと めだった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "{JPN}まえの ポケモンほど\nうまく いかなかった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "{JPN}{STR_VAR_1}の ちょうしが\nいつもより あがった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "{JPN}{STR_VAR_1}は ちょうしが よく\nすばらしい アピールに なった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "{JPN}つぎの アピールの じゅんばんが\nはやく なった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "{JPN}つぎの アピールの じゅんばんが\n1つ おそく なった。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "{JPN}つぎの ターンの じゅんばんを\nかきまわした。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "{JPN}しんさいんは きたいを こめて\n{STR_VAR_1}を みつめた。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverWell::
	.string "{JPN}アピールの つなぎが\nうまく いった。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverVeryWell::
	.string "{JPN}アピールの つなぎが\nとても うまく いった。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverExcellently::
	.string "{JPN}アピールの つなぎが\nみごとに きまった。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvertGaze::
	.string "{JPN}{STR_VAR_1}は なんとか\nめを そらせた。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{JPN}{STR_VAR_1}は なんとか\nみずに すんだ。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{JPN}{STR_VAR_1}は その くらいでは\nうろたえない。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameALittleDistracted::
	.string "{JPN}{STR_VAR_1}は すこし\nきを とられた。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherPokemon::
	.string "{JPN}ほかの ポケモンを\nおどろかせようと した。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonLookedDownOutOfDistraction::
	.string "{JPN}{STR_VAR_1}は きを とられて\nしたを むいた。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{JPN}{STR_VAR_1}は きを とられて\nうしろを むいた。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpUtteringCry::
	.string "{JPN}{STR_VAR_1}は おもわず\nなきごえを あげた。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpLeapingUp::
	.string "{JPN}{STR_VAR_1}は おもわず\nとびあがった。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTrippedOutOfDistraction::
	.string "{JPN}{STR_VAR_1}は きを とられて\nつまずいた。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasTooNervousToMove::
	.string "{JPN}{STR_VAR_1}は きんちょうして\nうごけなかった。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItMessedUp2::
	.string "{JPN}しかし しくじって しまった。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeTargetNervous::
	.string "{JPN}しかし あいてを きんちょう\nさせられなかった。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "{JPN}しかし だれも きんちょう\nさせられなかった。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItWasIgnored::
	.string "{JPN}しかし むし されて しまった…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CouldntImproveItsCondition::
	.string "{JPN}しかし ちょうしを\nあげられなかった…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BadConditionResultedInWeakAppeal::
	.string "{JPN}ちょうしが わるくて\nよわい アピールに なった。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasUnaffected::
	.string "{JPN}{STR_VAR_1}には\nきかなかった。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal::
	.string "{JPN}{STR_VAR_1}は おなじ アピールを\nくりかえして がっかりさせた。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXWentOverGreat::
	.string "{JPN}{STR_VAR_1}の {STR_VAR_3}は\nおおいに うけた。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell::
	.string "{JPN}{STR_VAR_1}の {STR_VAR_3}は\nここでは うけなかった…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXGotTheCrowdGoing::
	.string "{JPN}{STR_VAR_1}の {STR_VAR_3}で\nかんきゃくが もりあがった。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantAppealNextTurn::
	.string "{JPN}{STR_VAR_1}は つぎの ターン\nアピール できない…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AttractedCrowdsAttention::
	.string "{JPN}かんきゃくの ちゅうもくを\nあつめた。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CrowdContinuesToWatchMon::
	.string "{JPN}かんきゃくは {STR_VAR_3}を\nみつめつづけて いる。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsMoveIsIgnored::
	.string "{JPN}{STR_VAR_1}の\n{STR_VAR_2}は むし された。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness::
	.string "{JPN}はずかしがり$"

gText_Contest_Anxiety::
	.string "{JPN}ふあん$"

gText_Contest_Laziness::
	.string "{JPN}なまけ$"

gText_Contest_Hesitancy::
	.string "{JPN}ためらい$"

gText_Contest_Fear::
	.string "{JPN}おそれ$"

gText_Contest_Coolness::
	.string "{JPN}かっこよさ$"

gText_Contest_Beauty::
	.string "{JPN}うつくしさ$"

gText_Contest_Cuteness::
	.string "{JPN}かわいさ$"

gText_Contest_Smartness::
	.string "{JPN}かしこさ$"

gText_Contest_Toughness::
	.string "{JPN}たくましさ$"

@ Unused
gText_Tension::
	.string "{JPN}きんちょう$"

gText_CoolMove::
	.string "{JPN}かっこよさの わざ$"

gText_BeautyMove::
	.string "{JPN}うつくしさの わざ$"

gText_CuteMove::
	.string "{JPN}かわいさの わざ$"

gText_SmartMove::
	.string "{JPN}かしこさの わざ$"

gText_ToughMove::
	.string "{JPN}たくましさの わざ$"

gText_3QuestionMarks::
	.string "{JPN}???$"
