EventTicket_Text_OldSeaMapTooFar:
	.string "{JPN}どうした ぼうず?\pなに ぼろぼろの ふるい ちずを もって\nいるのは おまえさんかい?\pどれ みせて みろ。\n… … … … … …\pこりゃ だいぶ とおいな。\nわるいが ちからには なれん…$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "{JPN}オダマキ: ちょっと まった!\pわしが せわに なった ひとを\nおいかえすとは どういう つもりだ?$"

EventTicket_Text_BrineyLetsSail:
	.string "{JPN}{PLAYER}{KUN} ほんとうに すまなかった。\pたよって きて くれたのに\nおいかえす ところだった。\pさあ うめあわせを させて くれ。\pもちろん すぐに ふねを だすぞ!\pこの ふるいかいずの しまを\nさがしに いこう!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "{JPN}その みょうな チケットを もって きたのは\nおまえさんかい?\pいこうと して いるのは はるか とおくの\nしまだぞ。\pなにが まって いるかは だれも しらん…\pその かんがえだけで うみおとこの\nちが さわぐ わい!\pのりな ぼうず!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "{JPN}ミナモリ せんちょうは きまぐれで\nこまった ものだ…\pミナモに もどるかい?$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "{JPN}みょうな かたちの しまだな。\nミナモに もどるかい?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "{JPN}その みょうな チケットを もって きたのは\nおまえさんかい?\p… … …ふむ。\pこの チケットが あれば はるか とおくの\nしまへ いける。\pなにが まって いて なにが おきるかは\nだれにも わからん。\pその かんがえだけで うみおとこの\nちが さわぐ わい!\pのりな ぼうず!\nまずは どこへ むかう?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "{JPN}い いまの きこえたか?\nおくの ほうから ひくい うなりごえが。\pほんとうに だいじょうぶか?\nもどった ほうが いいんじゃ ないか?$"

FarawayIsland_Entrance_Text_Sign:
	.string "{JPN}ずいぶん むかしに かかれた ような\nうすれかけた もじだ…\p「…がつ 6にち\nもし にんげんが ここに あしを…\lふたたび…こころ やさしき ものであれ\l…そう ねがい われは たびだつ」$"

FarawayIsland_Interior_Text_Mew:
	.string "{JPN}みゅう…$"
