EventTicket_Text_ShowOldSeaMap:
	.string "{JPN}カイナへの れんらくせんは…\pえっ なんですって?\nこの ちずの ばしょへ ふねで?\pもっと くわしい ものを よびますので\nすこし おまち ください。$"

EventTicket_Text_ThatPass:
	.string "{JPN}カイナへの れんらくせんは…\pおや?\nその チケットは…$"

EventTicket_Text_ShowEonTicket:
	.string "{JPN}おい あんたが あの みょうな チケットを\nもって きた ひとかい?\pいうとくが あんたが いこうと して いるのは\nはるか みなみの ちっぽけな しまだぞ。\pついてみるまで なにが まって いるか\nだれにも わからん。\lぞくぞくするねえ!\pさあ のった のった!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "{JPN}おい こんな しまには みる ものも\nする ことも なにも ないぜ。\pミナモに もどるかい?$"

EventTicket_Text_SailHome:
	.string "{JPN}よし きまりだ!\nかえるとしよう!$"

EventTicket_Text_AsYouLike:
	.string "{JPN}そうかい すきに しな。$"

SouthernIsland_Interior_Text_Sign:
	.string "{JPN}「ゆめは すべて もうひとつの げんじつ。\nけっして わすれるな…」$"

SouthernIsland_Exterior_Text_Sign:
	.string "{JPN}「きおくの うすれゆく ものは\nそれを こころに きざもうと する…」$"
