@ Battle Tower
gText_AnabelWonSilver::
	.string "{JPN}とても ざんねんです…$"

gText_AnabelDefeatSilver::
	.string "{JPN}ええ わかりました…$"

gText_AnabelWonGold::
	.string "{JPN}ほんとうに もうしわけ ありません…$"

gText_AnabelDefeatGold::
	.string "{JPN}ありがとう ございます…$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "{JPN}アハハハ! はずかしく ないの?\nみんな みて いるよ!$"

gText_TuckerDefeatSilver::
	.string "{JPN}ぐぬぬ…\nなんだと…$"

gText_TuckerWonGold::
	.string "{JPN}ドームエースの なは かざりじゃ ない!$"

gText_TuckerDefeatGold::
	.string "{JPN}アハハハ!\nしびれるね!$"

@ Battle Factory
gText_NolandWonSilver::
	.string "{JPN}よく やった!\nいい べんきょうに なっただろう?$"

gText_NolandDefeatSilver::
	.string "{JPN}いいぞ!\nよく わかって いるね!$"

gText_NolandWonGold::
	.string "{JPN}おいおい おい!\nもう おわりかい?$"

gText_NolandDefeatGold::
	.string "{JPN}なにが あったんだ?$"

@ Battle Pike
gText_LucyWonSilver::
	.string "{JPN}ふん…$"

gText_LucyDefeatSilver::
	.string "{JPN}うっ…$"

gText_LucyWonGold::
	.string "{JPN}はっ!$"

gText_LucyDefeatGold::
	.string "{JPN}くそっ!$"

@ Battle Arena
gText_GretaWonSilver::
	.string "{JPN}おいおい!\nもっと がんばらないと だめだろう!$"

gText_GretaDefeatSilver::
	.string "{JPN}まさか!\nよく やった!$"

gText_GretaWonGold::
	.string "{JPN}ヘヘッ!\nなにを きたい して いたんだい?$"

gText_GretaDefeatGold::
	.string "{JPN}えっ?\nほんきで いって いるの?!$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "{JPN}トレーナーが よわいから\nポケモンも よわいのよ!$"

gText_SpenserDefeatSilver::
	.string "{JPN}ああ…\nこれは ただものでは ない…$"

gText_SpenserWonGold::
	.string "{JPN}グワハハハ!\nどうしたち おそれる ものは ない!$"

gText_SpenserDefeatGold::
	.string "{JPN}グワッ!\nハハハハ!$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "{JPN}こら どうした!\nこんじょうを みせろ! たちあがれ!$"

gText_BrandonDefeatSilver::
	.string "{JPN}それだ! よく やった!\nこの ために がんばって きたんだ!$"

gText_BrandonWonGold::
	.string "{JPN}こら あきらめるな!\nたちあがれ! じぶんを しんじろ!$"

gText_BrandonDefeatGold::
	.string "{JPN}それだ! やったな!\nこの ために がんばりつづけたんだ!$"
