LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "{JPN}ポケモンくじ コーナーです。\pデパートで おかいものを された かたは\nポケモンくじを ひけます。\pくじの ばんごうと おてもちの ポケモンの\nIDばんごうが あえば\lすてきな けいひんを さしあげます。\pポケモンくじを ひきますか?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "{JPN}また あした おこし ください。$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "{JPN}また の おこしを おまち して います。$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "{JPN}くじを ひいて ください。\n…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "{JPN}くじの ばんごうは {STR_VAR_1}です。\pおてもちの ポケモンの IDばんごうと\nくらべますので しばらく\lおまち ください。$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "{JPN}おめでとう ございます!\pてもちの {STR_VAR_1}の IDばんごうが\nくじの ばんごうと\lあって います!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "{JPN}おめでとう ございます!\pパソコンの {STR_VAR_1}の IDばんごうが\nくじの ばんごうと\lあって います!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "{JPN}ざんねんでした。\nどの ばんごうも あいません でした。$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "{JPN}2けた あったので 3とうしょうです!\l{STR_VAR_1}を さしあげます!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "{JPN}3けた あったので 2とうしょうです!\l{STR_VAR_1}を さしあげます!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "{JPN}4けた あったので 1とうしょうです!\l{STR_VAR_1}を さしあげます!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "{JPN}まあ たいへん 5けた ぜんぶ\nあいました!\pとくとうしょうです!\n{STR_VAR_1}を さしあげます!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "{JPN}おや?\nいれる ばしょが ないようですね。\pバッグに あきを つくって\nおしえて ください。$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{JPN}{PLAYER}さん ですね?\nおまちして おりました。\pおあずかり して いた けいひんです。$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "{JPN}また の おこしを おまち して います。$"
