MatchCall_WildBattleText1::
	.string "{JPN}やあ! {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}だよ。\pさっき {STR_VAR_2}を みかけたんだけど\nつかまえられなかったんだ。\pおしかったのになあ!\nじゃあ また ね!$"

MatchCall_WildBattleText2::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\pさっき いい {STR_VAR_2}を\nつかまえようと したの。\pでも にげられちゃって。\nがっかりしたわ!\pじゃあ またね!$"

MatchCall_WildBattleText3::
	.string "{JPN}よお {PLAYER}!\nおれだ {STR_VAR_1}だ。\pさっき {STR_VAR_2}を つかまえようと\nしたんだが にげられた。\pおしかったんだがなあ!\pきぶんが だいなしだよ…\nそれじゃ またな!$"

MatchCall_WildBattleText4::
	.string "{JPN}やあ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\p{STR_VAR_2}って ポケモンを しって るか?\nもう すこしで つかまえられたんだ。\pついさっきの ことさ。\nいけると おもったのに にげられた。\pこんど みかけたら かならず\nつかまえて みせるよ。\pそれじゃ またな。$"

MatchCall_WildBattleText5::
	.string "{JPN}やあ {PLAYER}{KUN}!\n{STR_VAR_1}よ。\lさいきん ポケモン つかまえて る?\pさっき もうすこしで つかまえられたのに\nにげられちゃったの。\pそれじゃ きを つけてね!$"

MatchCall_WildBattleText6::
	.string "{JPN}やあ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\lさいきん ポケモンは つかまえたか?\pこの あいだ もうすこしで\nつかまえられたのに にげられたよ。\pきを つけてな。$"

MatchCall_WildBattleText7::
	.string "{JPN}…あの {PLAYER}{KUN}?\nわたし {STR_VAR_1}です。\pあっ まって! まって!\nこの {STR_VAR_2}が つかまえられそう…\pああっ! にげられた!\nおしいなんて ものじゃ ないわ!$"

MatchCall_WildBattleText8::
	.string "{JPN}おや {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。\pさいきん ポケモンは うまく\nつかまえられて いますか?\pさきほど おしい ところまで\nいったのですが にげられました。\pもっと がんばらなければ!\nでは また!$"

MatchCall_WildBattleText9::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}よ!\pどう? ポケモンは あつまって\nる?\pわたしは さんざん! みんな\nにげられちゃうの!\pじゃあね!$"

MatchCall_WildBattleText10::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは…\n{STR_VAR_1}です。\pあのね もうすこしで {STR_VAR_2}を\nつかまえられそうだったの…\pでも にげられて しまって…\pもっと がんばらないと。\nそれじゃ また。$"

MatchCall_WildBattleText11::
	.string "{JPN}ああ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\lちょうしは どうかね?\pさっき やせいの {STR_VAR_2}を\nつかまえようと したが にげられた。\pなさけない ものだ…$"

MatchCall_WildBattleText12::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\lまだ ポケモンを つかまえて いますか?\pわたしも つかまえようと して いますが\nなかなか むずかしい ものですね。\pポケモンの みちは おくが ふかい!$"

MatchCall_WildBattleText13::
	.string "{JPN}ああ こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\lポケモンは つかまえて いますか?\pわたしも つかまえようと して いますが\nうまく いきません。\pポケモンの みちは おくが ふかい!$"

MatchCall_WildBattleText14::
	.string "{JPN}あら {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。\pいま かわいい {STR_VAR_2}を\nつかまえようと したの。\pでも にげられちゃった!\nがっかりしたわ!\pバイバイ!$"

MatchCall_WildBattleText15::
	.string "{JPN}よお {PLAYER}!\n{STR_VAR_1}だぜ!\pポケモンを つかまえて みようかと\nおもって いたんだ。\pだが みつからなくてな。\nさっぱり わからん!\pおてあげだよ!\nそれじゃ またな!$"

MatchCall_NegativeBattleText1::
	.string "{JPN}やあ! {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}だよ。\pほかの トレーナーと しょうぶ したけど\nまけちゃった。\pすごく くやしかったよ。\nじゃあ また ね!$"

MatchCall_NegativeBattleText2::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\pあなたと しょうぶした あと\nべつの ひとに いどんだの。\pおしかったけど まけちゃった。\nしかたないわね!$"

MatchCall_NegativeBattleText3::
	.string "{JPN}よお {PLAYER}!\nおれだ {STR_VAR_1}だ。\pしょうぶで こてんぱんに やられたよ。\pもっと てもちを きたえないと\nだめみたいだ!$"

MatchCall_NegativeBattleText4::
	.string "{JPN}よお {PLAYER}。\n{STR_VAR_1}だ。\pきのう また しょうぶ したんだが\nかちきれなかった。\pもっと きたえないとな。\nそれじゃ またな。$"

MatchCall_NegativeBattleText5::
	.string "{JPN}やあ {PLAYER}!\n{STR_VAR_1}よ。\pちょうしは どう?\pしょうぶは つづけて いるけど\nあまり かてて いないの。\pどうも ちょうしが でないわ。\nそれじゃ きを つけてね!$"

MatchCall_NegativeBattleText6::
	.string "{JPN}よお {PLAYER}。\n{STR_VAR_1}だ。\pちょうしは どうだ?\pさいきん しょうぶを つづけて いるが\nあまり かてて いない。\pどうも ノれないんだ。\nきを つけてな。$"

MatchCall_NegativeBattleText7::
	.string "{JPN}{STR_VAR_1}だ。\nさいきん どうだ?\pきのう しょうぶに まけて\nずっと その ことを かんがえて いる。\pさくせんを ねりなおさないと…\nそれじゃ。$"

MatchCall_NegativeBattleText8::
	.string "{JPN}あら {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。\pポケモンは げんきですか?\nわたしは このあいだ まけました。\pもっと がんばらないと!\nでは また!$"

MatchCall_NegativeBattleText9::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}よ!\pねえ ねえ\nきいて!\pさっき ポケモンの しょうぶを したけど さいごの\nさいごで まけちゃったの。\pああ くやしい!$"

MatchCall_NegativeBattleText10::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは…\n{STR_VAR_1}です。\pすこし まえに しょうぶを しました。\nまけて しまいましたけど。\pもっと ポケモンを そだてないと。\nそれじゃ また。$"

MatchCall_NegativeBattleText11::
	.string "{JPN}ああ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\lポケモンは げんきかね?\pまた しょうぶに まけて しまったよ。\pでは また!$"

MatchCall_NegativeBattleText12::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\lしょうぶは がんばって いますか?\pわたしは このあいだ まけたので\nてもちを きたえなおして います。\pまた あいましょう。$"

MatchCall_NegativeBattleText13::
	.string "{JPN}ああ こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\pげんきに して いますか。\pついさっき しょうぶを して\nきたところです。\p{PLAYER}{KUN}も わたしのように\nげんきに いきましょう。 では また!$"

MatchCall_NegativeBattleText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\pげんきに して る?\pたまには いえにも\nかえりなさいね。\pバイバイ!$"

MatchCall_PositiveBattleText1::
	.string "{JPN}やあ! {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}だよ!\pさっき トレーナーと しょうぶ して\nかったんだ! かったよ!\pうちの {STR_VAR_2}が すごく\nがんばって くれた。 さいこうだ!$"

MatchCall_PositiveBattleText2::
	.string "{JPN}こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\pきのう しょうぶを して\nかったの! すごいでしょう!$"

MatchCall_PositiveBattleText3::
	.string "{JPN}よお {PLAYER}!\nおれだ {STR_VAR_1}だ!\lしょうぶは どうだ?\pこの あいだ しょうぶ してな\nうちの {STR_VAR_2}が おおかつやくだ!\pつぎに {PLAYER}と やる ときは\nまける きは ないぞ!$"

MatchCall_PositiveBattleText4::
	.string "{JPN}よお {PLAYER}。\n{STR_VAR_1}だ。\pさっき しょうぶが あってな。\nきわどかったが かてたよ。\pうちの {STR_VAR_2}が\nみごとな はたらきを した。$"

MatchCall_PositiveBattleText5::
	.string "{JPN}やあ {PLAYER}{KUN}!\n{STR_VAR_1}よ。\pちょうしは どう? しょうぶ\nしてる?\pさっき かったところよ! うちの {STR_VAR_2}が\nみごとだったの!\pみてなさい つぎは あなたに かつわ! それじゃ\nきを つけてね!$"

MatchCall_PositiveBattleText6::
	.string "{JPN}よお {PLAYER}{KUN}。\n{STR_VAR_1}だ。\pちょうしは どうだ?\pおれは ちょうしが いいぞ。\nさっきも しょうぶに かった。\pこんど おまえと やる ときは\nぜったいに まけないからな!$"

MatchCall_PositiveBattleText7::
	.string "{JPN}{PLAYER}{KUN}?\n{STR_VAR_1}だ。\pうちの {STR_VAR_2}は たいした ものだ!\nさっきも しょうぶに かたせて くれた!\pまた きみと しょうぶ するのが\nたのしみだよ。$"

MatchCall_PositiveBattleText8::
	.string "{JPN}あら {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。\pおげんきで なによりです。\nさっき しょうぶに かちました。\pうちの {STR_VAR_2}が とくに\nがんばって くれたのです。\pでは また!$"

MatchCall_PositiveBattleText9::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}よ!\pポケモンは げんき?\nうちの こは しょうぶに かったの!\pうちの {STR_VAR_2}が それはもう\nみごとだったのよ!\pみせて あげたかったわ!\nそれじゃ また!$"

MatchCall_PositiveBattleText10::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは…\n{STR_VAR_1}です。\pさいきん いかがですか?\pうちの ポケモンは ちからが\nみなぎって いるようです。\pさっき しょうぶに かちました。\nそれじゃ また。$"

MatchCall_PositiveBattleText11::
	.string "{JPN}ああ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\pさいきん しょうぶは して いるか?\nわしは きょうも かったぞ!\pのって おるわ! がはははは!\nでは また!$"

MatchCall_PositiveBattleText12::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\pおげんきでしたか?\nわたしは まだまだ げんきですよ!\pついさっきも しょうぶに かちました。\nわかい ひとに ゆずる きは\lまだ ありません!$"

MatchCall_PositiveBattleText13::
	.string "{JPN}ああ こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\pおげんきで なによりです。\nわたしも まだまだ げんきです!\pついさっきも また しょうぶに かちました。\nわかい ひとには まだまだ\lまけませんよ!\pでは また!$"

MatchCall_PositiveBattleText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\pこの あいだ しょうぶを して\nうちの {STR_VAR_2}が みごとでした!\p{PLAYER}{KUN}にも みせたかったわ。\nバイバイ!$"

MatchCall_SameRouteBattleRequestText1::
	.string "{JPN}やあ! {PLAYER} こんにちは!\n{STR_VAR_1}だよ。\pえ? いま {STR_VAR_2}の\nちかくに いるの?\pそれなら しょうぶ しよう!\nまって るよ! それじゃ!$"

MatchCall_SameRouteBattleRequestText2::
	.string "{JPN}こんにちは {PLAYER}!\n{STR_VAR_1}です。\pあら? いま {STR_VAR_2}の\nあたりに いるの?\pいま しょうぶ しませんか?\nまって います! それじゃ!$"

MatchCall_SameRouteBattleRequestText3::
	.string "{JPN}よお {PLAYER}! おれだ\n{STR_VAR_1}だ。\pおい いま {STR_VAR_2}の ちかくに\nいるのか?\pいま おれと しょうぶ\nしないか?\pもう まけないぞ! まって るからな!\nまたな!$"

MatchCall_SameRouteBattleRequestText4::
	.string "{JPN}よお {PLAYER}{KUN}。\n{STR_VAR_1}だ。\pいま どこに いる?\nえ? {STR_VAR_2}?\pいま しょうぶ しないか?\nまって るぞ。 それじゃ!$"

MatchCall_SameRouteBattleRequestText5::
	.string "{JPN}やあ {PLAYER}{KUN}!\n{STR_VAR_1}よ。\lちょうしは どう?\pいま どこに いるの?\n{STR_VAR_2}?\pそれなら いますぐ もういちど\nしょうぶ しない?\pさがして るわね。\nまた すぐに!$"

MatchCall_SameRouteBattleRequestText6::
	.string "{JPN}よお {PLAYER}{KUN}。\n{STR_VAR_1}だ。\lポケモンは げんきか?\pほう そうなのか? {STR_VAR_2}の\nあたりに いるのか?\pそれなら もういちど\nしょうぶ しないとな。\pまって るぞ。\nそれじゃ!$"

MatchCall_SameRouteBattleRequestText7::
	.string "{JPN}…あの {PLAYER}{KUN}?\n{STR_VAR_1}です…\pあら {STR_VAR_2}の あたりに\nいるのですか?\pそれなら しょうぶ しましょう。\nいますぐ。\pわたしの ポケモンを みせて あげます。\nまって います。$"

MatchCall_SameRouteBattleRequestText8::
	.string "{JPN}あら {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。\pおげんきで なによりです。\nあら {STR_VAR_2}の ちかくですね。\pそれなら わたしと しょうぶを\nしませんか?\pまって います。\nでは また すぐに!$"

MatchCall_SameRouteBattleRequestText9::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}よ!\pがんばって る?\nあら {STR_VAR_2}の ちかく?\pそれなら しょうぶ するしか\nないと おもわない?\pあまり またせないでね!$"

MatchCall_SameRouteBattleRequestText10::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは…\n{STR_VAR_1}です。\pちょうしは いかがですか?\nあら {STR_VAR_2}の ちかくですね。\pそれなら いま しょうぶ しましょう。\pじゅんびして まって います。\nはやく きてね!$"

MatchCall_SameRouteBattleRequestText11::
	.string "{JPN}ああ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\pほう いま いる ところは\n{STR_VAR_2}か?\pそれなら しょうぶを するしか\nないと おもわないか?\pまって いるぞ!\nすぐに あおう!$"

MatchCall_SameRouteBattleRequestText12::
	.string "{JPN}こんにちは {PLAYER}{KUN}。 {STR_VAR_1}です。\nいま どこに\lいますか?\p{STR_VAR_2}? ずいぶん\nちかいですね!\pいま しょうぶを\nしませんか?\pまって いますよ。\nそれじゃ!$"

MatchCall_SameRouteBattleRequestText13::
	.string "{JPN}ああ こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\pおげんきで なによりです。\nあら {STR_VAR_2}の ちかくですか?\pそれほど とおくないので\nしょうぶに きて ください。\pまって います。\nでは また。$"

MatchCall_SameRouteBattleRequestText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\pいま どこ? …{STR_VAR_2}?\nとても ちかいわね。\pそれなら しょうぶ するべきだと\nおもわない?\pさがして るわね!\nバイバイ!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "{JPN}やあ! {PLAYER} こんにちは!\n{STR_VAR_1}だよ。\pぼくと しょうぶ しないかい?\p{STR_VAR_2}の あたりで\nまって るよ!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "{JPN}こんにちは {PLAYER}!\n{STR_VAR_1}です。\pまた わたしと しょうぶ\nしませんか?\p{STR_VAR_2}の あたりに います。\nまって いますね!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "{JPN}よお {PLAYER}!\nおれだ {STR_VAR_1}だ。\pまえより ポケモンが ずいぶん\nつよく なったんだ。\pどれくらい つよく なったか\n{PLAYER}の ポケモンで ためしたい。\pだから しょうぶ しよう!\p{STR_VAR_2}の あたりで\nまって るからな。$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "{JPN}よお {PLAYER}{KUN}。\n{STR_VAR_1}だ。\lちょうしは どうだ?\pさいきん ポケモンが かなり\nつよく なってな。\pなあ また おれと しょうぶ\nしないか?\p{STR_VAR_2}の あたりで\nあおうじゃないか。$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "{JPN}やあ {PLAYER}{KUN}!\n{STR_VAR_1}よ。\pうちの ポケモンは いい かんじに\nそだって いるの。\pぜひ また あなたと しょうぶ\nしたいわ。\p{STR_VAR_2}の あたりで\nさがして るわね。 また すぐに!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "{JPN}よお {PLAYER}{KUN}。\n{STR_VAR_1}だ。\lうまく やって いるか?\pまた きみと しょうぶ したいと\nおもって いたんだ。 どうだ?\pその きが あるなら\n{STR_VAR_2}に きて くれ。\pそれじゃ!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "{JPN}…あの {PLAYER}{KUN}?\n{STR_VAR_1}です…\lポケモンは そだって いますか?\pうちの こは つよく なりました。\nみせて あげたいです。\p{STR_VAR_2}の あたりに います。\nしょうぶに きて ください。\pそれじゃ また。$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "{JPN}あら {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。\pおげんきで なによりです。\nうちの ポケモンは げんきいっぱい。\pこの あたりに きたら ぜひ\nもういちど しょうぶを。\p{STR_VAR_2}の あたりに います。\nそれでは また!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}よ!\lポケモンは げんき?\pうちの ポケモンは どんどん よく\nなって いるの。 {PLAYER}{KUN}に みせたいわ。\pいまは {STR_VAR_2}の あたりに\nいるから ちかければ しょうぶ しましょう。\pまって るわね!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは…\n{STR_VAR_1}です。\lちょうしは いかがですか?\pうちの ポケモンは まえより\nずっと つよく なりました。\pぜひ また {PLAYER}{KUN}と\nしょうぶ したいです。\p{STR_VAR_2}の あたりに います。\nちかければ きて ください。$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "{JPN}ああ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\lいま どこに いる?\pうちの ポケモンは げんきいっぱいだ。\n{PLAYER}{KUN}の ポケモンに あうのを\lたのしみに して いるようだ。\pいまは {STR_VAR_2}の あたりに いる。\nさがしに きて くれると うれしい。$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\pうちの ポケモンは さいきん\nずいぶん たくましく なりました。\p{PLAYER}{KUN}との しょうぶで\nその すがたを みたいのです。\p{STR_VAR_2}の あたりに います。\nいつでも きて ください!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "{JPN}ああ こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\lポケモンは げんきですか?\pうちの ポケモンは とても げんきで\nまける きが しません!\pぜひ また しょうぶを\nして みたいのです。\p{STR_VAR_2}の ちかくなら\nきて ください。$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\lおげんきですか。\pそうそう! うちの ポケモンは\nまえより ずっと つよいのよ。\p{PLAYER}{KUN} しょうぶ するべきだと\nおもわない?\p{STR_VAR_2}の あたりで\nまって いるわ。\pいつでも きてね?$"

MatchCall_PersonalizedText1::
	.string "{JPN}やまずきの\n{STR_VAR_1}だ!\pあれから やまの よさが わかって\nきたかね?\pやまでは あまり きみを みかけないな…\pこんどは {STR_VAR_2}の あたりで\nあおうじゃないか。$"

MatchCall_PersonalizedText2::
	.string "{JPN}{STR_VAR_1}です。\nこんにちは。\pあたらしい トレーナーに\nあなたの ことを はなして いました。\pポケモンを たいせつに そだてる\nつよい トレーナーが いると。\pみんなに あこがれられる トレーナーに\nなって くださいね。\pまた あいましょう!$"

MatchCall_PersonalizedText3::
	.string "{JPN}こんにちは! {STR_VAR_1}です。\pいまいる ところが だいすきなの。\nあまい かおりで こころちよいわ!\pだれかが きのみを うえたようで\nいっせいに はなが さいたの。\pまた いつか!$"

MatchCall_PersonalizedText4::
	.string "{JPN}こんにちは! たんけん 30ねん\n{STR_VAR_1}だ!\pきみは あちこちを げんきに\nたびして いるようだな。\pあたらしい いせきは みつけたかね?\nみつけたら おしえて くれたまえ!\pでは しつれい するよ。\nいせきの たんけんが あるのでね。$"

MatchCall_PersonalizedText5::
	.string "{JPN}{STR_VAR_1}よ!\pきょう なにを して いると おもう?\nはまべで なみを ながめて いるの!\pはあ… なみが きらきらして るわ。\nうみは ここから みるのが いちばん きれい。\lおなかが すいたから バイバイ!$"

MatchCall_PersonalizedText6::
	.string "{JPN}もぐもぐ…\nあら {STR_VAR_1}よ。\lはまべで たべるのが すきなの。\pポケモンも わたしも げんきよ。\nエネルギー まんタン!\lおよいで くるわね バイバイ!$"

MatchCall_PersonalizedText7::
	.string "{JPN}こんにちは {STR_VAR_1}です…\pエリートトレーナーと いうのに すこし つかれて\nしまって…\pみんな わたしを かんぺきな トレーナーだと\nおもうから それに こたえようと\lしてしまうの。\pでも それが エリートトレーナーと いう\nものよね。\pはらを くくって… がまん するしか\nないわ。\pこんな はなしが できるのは\nあなただけよ。\pつぎに あう ときは\nわすれてね。$"

MatchCall_PersonalizedText8::
	.string "{JPN}ヤッホー {STR_VAR_1}よ!\nごきげん いかが?\pあなたを めざして ポケモンを\nそだてて いるの。\pつぎに しょうぶする ときは\nまける つもりは ないわ。\pトレーナーの ともだちって いいわね!\nまた あいましょう!$"

MatchCall_PersonalizedText9::
	.string "{JPN}{STR_VAR_1}です…\nいま あなたの うしろに…\lなにか いませんでしたか…?\pおくりびやまに ねむる ポケモンの\nちからが…\pあなたの ことを おしえて くれるの…\pはやく そこを はなれて\nいちども ふりかえらない ことね…\pうふふ…\nさようなら…$"

MatchCall_PersonalizedText10::
	.string "{JPN}{STR_VAR_1}です。\nごきげんよう。\pこうして はなれて いても はなせるのは\nべんりですわね?\pむかしは だれかと はなすのに\nパパに くるまを だして もらわないと\lいけませんでしたの…\pそろそろ しつれい しますわ。\nおはなし できて うれしかった。$"

MatchCall_PersonalizedText11::
	.string "{JPN}{STR_VAR_1}よ! きいて\nくれる?\pサファリゾーンが だいすきなんだけど いくと\nかならず まいごに なるの!\pくさむらだらけだし\nひろすぎるのよ!\pはなしたら\nすっきりしたわ!\pまた サファリゾーンに いってくるね!\nそれじゃ!$"

MatchCall_PersonalizedText12::
	.string "{JPN}こんにちは {STR_VAR_1}です。 ええ そうです わたしは\nかねもち。\pいって おきますが まえに あったときより\nざいさんが ふえましたのよ。\pさらに ポケモンも つよく\nなりました。\pこの よは わたしの ために あるような きが して\nなりません!\pああ なにも いわなくて けっこう! みんな しって\nいる ことですもの!\pでは しつれい しますわ。 しょくじかいが\nありますの。$"

MatchCall_PersonalizedText13::
	.string "{JPN}うふふふふ…\nわたしよ {STR_VAR_1}…\pいま なにを みて いると おもう?\n{STR_VAR_2}が 2ひきで しょうぶ してるの。\pかった ほうを つかまえようかしら…\nうふふふふ…\pわ わたし いま すこし いそがしいの。\nきらないと。$"

MatchCall_PersonalizedText14::
	.string "{JPN}おや {STR_VAR_1}だ!\pすてられぶねにも あきてきたなと おもって いた\nところさ。\pだが せっかく ここに いるんだし いちどは\nきみに かちたいから もうすこし いる ことに\lするよ。\pその きに なったら あいに きて\nくれないか?\pきょうこそ となりの おとこに\nしょうぶを いどんで みる\lつもりだ。\pそれじゃ また!$"

MatchCall_PersonalizedText15::
	.string "{JPN}おれは {STR_VAR_1}!\nうみの おとこだ!\pなにを おもうか わかるか?\pうみに でる トレーナーこそ\nいちばん てごわいのさ!\pきみも おれを みならって\nうみで きたえると いい…\pおっと おおなみが きた!\pれんしゅうには もってこいだ!\nわるいが きるぞ!$"

MatchCall_PersonalizedText16::
	.string "{JPN}{STR_VAR_1}だ! きいてくれ ポケモンに からてを おしえて\nいたんだ。\pだが いまでは おれより つよくてな!\nまけてばかりだ!\pポケモンには まけても\nほかの トレーナーには\lまけないぞ!\pまた しょうぶ しようじゃないか!\nうおおお!$"

MatchCall_PersonalizedText17::
	.string "{JPN}おれだ {STR_VAR_1}だ。\nたびの ちょうしは どうだい?\p…おっと そうなのか?\nずいぶん しげきてきだな!\pきみの できごとを きょくに\nできそうだよ。\p…おっ きた。\nあたまの なかで リフが なって いる。\pちゃんと かきとめないと いけない。\nいくぞ! またな!$"

MatchCall_PersonalizedText18::
	.string "{JPN}{STR_VAR_1}だ…\nあたらしい きょくを きいて くれ。\pラララ {STR_VAR_2} {STR_VAR_2}!\nなぜ きみは {STR_VAR_2}なんだ?\lなぜ おれは {STR_VAR_2}に なれない?\lララ {STR_VAR_2}と {STR_VAR_1}\l{STR_VAR_1}と {STR_VAR_2}…\pくりかえして フェードアウト…$"

MatchCall_PersonalizedText19::
	.string "{JPN}キャンプの めいじん\n{STR_VAR_1}だ!\pしょうぶの ときは きみに まける しか\nなかったな。\pなにしろ おれの とくいは\nキャンプだからな。\pだが かっても まけても キャンプでの しょうぶは\nたのしい。\pまた しょうぶ しような? それと キャンプにも\nいこう!$"

MatchCall_PersonalizedText20::
	.string "{JPN}おれ おれ {STR_VAR_1}だ!\pしょうじきに いうと ほかの やまにも\nのぼって みたいんだ。\pでも えんとつやまの ような\nおじょうさんが いるかは わからないな。\pほかに おじょうさんの いる やまを\nしって いたら おしえて くれ!\pえへへ またな!$"

MatchCall_PersonalizedText21::
	.string "{JPN}… … … … … …\n… … … … … …\l{STR_VAR_1}です…\p… … … … … …\n… … … … … …\lきょうは これだけ…$"

MatchCall_PersonalizedText22::
	.string "{JPN}{STR_VAR_1}だ。 きょうは きみと\nはなす きが したんだ。\pきみを たおしたいと いう おもいは\nひごとに つよく なる。\pきみにも そんな ライバルが いるだろう?\nそれが おれだと いいのだが…\pきいて くれて ありがとう。\nまたな!$"

MatchCall_PersonalizedText23::
	.string "{JPN}{STR_VAR_1}だ。\pちかくに つよい トレーナーが いると\nなんとなく かんじる ことが\lあるんだ。\p{PLAYER}{KUN} ちかくを とおったか? きみ だったのかも\nしれないな。\pきみが くるのを まって いる。\nそれじゃ!$"

MatchCall_PersonalizedText24::
	.string "{JPN}こんにちは {STR_VAR_1}です。\nおげんきそうですね {PLAYER}{KUN}。\pせかいじゅうを たびして きましたが\nこの ちほうが すっかり きに\lいって しまいました。\pしばらく ここに いる つもりです。\nまた あえますか?\pあなたの みごとな わざは\nわすれて いません。\pぜひ もういちど しょうぶを。$"

MatchCall_PersonalizedText25::
	.string "{JPN}ぐすん… {STR_VAR_1}です…\n…ぐすっ…\pきょう じゅぎょうで ツツジせんせいに\nしかられちゃった。\pでも きらいじゃ ないんだ。\pツツジせんせいは どこが だめだったか\nちゃんと おしえて くれるから。\pあしたも トレーナーズスクールに\nいくよ!\pそれじゃ また!$"

MatchCall_PersonalizedText26::
	.string "{JPN}{STR_VAR_1}だよ!\pきのう ツツジせんせいが しょうぶを して\nくれたんだ。\pけっかは… きくまでも なく\nさんざんだったよ。\pでも ツツジせんせいが しょうぶを うけて くれた\nことが うれしかった!\pますます\nあこがれちゃった!\pしっかり がんばるよ! それじゃ\nまた!$"

MatchCall_PersonalizedText27::
	.string "{JPN}アンナよ! きょうも こうはいの\nメグと いっしょ。\pメグと ポケモンの せわを するのが\nだいすきなの。 かわいいのよ!\pきょうだいの ように せわが\nできたら いいのに!\pあら メグ!\nパンは かって きた?\pえ? ちがう ちがう!\nこきつかって なんて いないわ!\pしょうぶに まけたんだから\nばつとして パンを かって くるのよ!\pこきつかって なんて いないでしょう\nメグ? あなたは たいせつな こうはいよ!\pそれじゃ また ね!$"

MatchCall_PersonalizedText28::
	.string "{JPN}ポケモンが だいすき!\nファンクラブの {STR_VAR_1}です!\pきいて ください!\nうちの かわいい ポケモンが…\pふふっ わははは!\nこれいじょうは いえません! ひみつです!\lかわいすぎて ことばに なりません!\pあら うちの {STR_VAR_2}が\n{POKEBLOCK}を ねだって います!\pかわいさの きわみです!\pすみませんが いまは はなせません!\nまた こんど!$"

MatchCall_PersonalizedText29::
	.string "{JPN}おほほ!\p{STR_VAR_1}です! かわいい ポケモンの\nはなしを させて ください!\pぜひ きいて ください。\nうちの {STR_VAR_2}の ことです。\pだれかが だきあげると まっすぐ\nわたしの うでに とんで くるの!\pああ… ああ… これほどの\nしあわせが あるかしら?\pもう てんごくの きぶんですわ!\pこの しあわせを すこし わけられて\nうれしかった ですわ。\pそれでは しつれい します。\nまた ね!$"

MatchCall_PersonalizedText30::
	.string "{JPN}わたしは… {STR_VAR_1}。\nひとは わたしを たつじんと よぶ。\pだが ひとつ わかって いる ことが ある。\nわたし ひとりの ちからでは\lたつじんには なれなかった。\pポケモンの たすけが あってこそ\nトレーナーは たつじんに なれるのだ。\pふむ! いま なかなか ふかい ことを\nいった きが するぞ!\pよい きぶんで しつれい しよう!$"

MatchCall_PersonalizedText31::
	.string "{JPN}{STR_VAR_1}じゃ。\nはなせて うれしいのう!\pおんせんに つかって からだが\nいきかえるようじゃ。\pあれから わかい トレーナーと\nしょうぶを して おるが きみが\lいまでも いちばん つよいのう。\pきみも としを とれば たつじんに\nなるじゃろう! ほっほっほ…$"

MatchCall_PersonalizedText32::
	.string "{JPN}やった! {STR_VAR_1}だよ!\nどうしてる?\pきの せいかも しれないけど しょうぶに\nかつと はんズボンの はきごこちが\lよく なる きが するんだ。\pどういう ことかって?\nうまく いえないんだけど…\lなんて いうかな…\lはんズボンが すべすべに なるんだ!\p{PLAYER}{KUN}と しょうぶ した ときは\nはんズボンが ざらざら して いたよ。\p… … … … … …\nいまのを ほんきに した?\lえへへ それだけ! またね!$"

MatchCall_PersonalizedText33::
	.string "{JPN}よお!\n{STR_VAR_1}だ!\pあいかわらず むちゅうで\nつりを して いるぜ!\pうみや かわ いがいにも\nつりが できる ところは あるのか?\pどこでも つりたく なる ときが\nあるんだよなあ!\pおっと しまった!\nいとが からまった!\pきるぞ!\nあたらしい つりばを さがして おいて くれ!$"

MatchCall_PersonalizedText34::
	.string "{JPN}やあ! {STR_VAR_1}だ。\nのんびり やって るかい?\pこどもの ころから おれは\nずっと のんびりやでね。\pあせったり いそいだり するのは\nどうも にがてだった。\pそれが どういう わけか\nいまでは トライアスリートさ。\pじんせいは どこへ ころがるか\nわからない ものだな。\pきみも いまは トレーナーだが\nさきの ことは わからないぞ?\pせんせいに なった じぶんを\nそうぞう して みるのも おもしろい。\pそれじゃ またな!$"

MatchCall_PersonalizedText35::
	.string "{JPN}{STR_VAR_1}だ!\nいま じてんしゃに のって いる。\pすいえいも ランニングも すきだが\nじてんしゃが いちばん すきなんだ!\pぜんしんが かぜと ひとつに\nなった ような きぶんに なる。\pそらを とんで いるみたいで\nたまらないんだ!\pよし きょうこそ じてんしゃロードの\nきろくを こうしんするぞ!\pきみも ちょうせん して みろよ!\nまたな!$"

MatchCall_PersonalizedText36::
	.string "{JPN}よお {STR_VAR_1}だ! いま トライアスロンの\nまっさいちゅうだ!\pだが おしゃべりの じかんは\nいつでも あるぜ!\pポケモンと からだを うごかすのは\nじつに きもちが いい!\pことばを かわさなくても こころが\nひとつに なった ように そろうんだ。\pしびれるぜ!\pはあ… はしりながら はなして いたら…\nばてて きたな…\lはあ… はあ…$"

MatchCall_PersonalizedText37::
	.string "{JPN}やあ {STR_VAR_1}だ。\nもちりょくを つけたいなら\lこうちで きたえるに かぎる!\pやまの うえで はしって みろ。\nすぐに いきが あがるぞ!\pおれも さんそが たりなく なって きた!\nまたな!$"

MatchCall_PersonalizedText38::
	.string "{JPN}おや {STR_VAR_1}だ こんにちは。\pずいぶん およいで いるのに\nサイユウシティに つかないんだ。\pぐるぐる まわって いるのかな。\pいや いや そんな はずは ない。\nわははは。\lきを つけてな!$"

MatchCall_PersonalizedText39::
	.string "{JPN}よお {STR_VAR_1}だ…\nおっと!\pばしゃっ!\pごぼごぼごぼ…\pざぶーん!\pふうふう! ふうふう!\pおっと わるい わるい! ひやけどめを ぬった\nばかりでな。\pポケナビが てから すべって みずに おちて\nしまったんだ!\pだが デボンの ポケナビは じょうぶだな。 みずに\nおちても へいきだ!\pそれじゃ ひなたぼっこの\nつづきだ!$"

MatchCall_PersonalizedText40::
	.string "{JPN}こんにちは {STR_VAR_1}です。\pトライアスロンの 3しゅもくの なかでは\nすいえいが いちばん すきなの。\pでも うみに ながく つかって いると\nてが しわしわに ならないかしら?\pああ トライアスロンは にんげんの\nがまんの げんかいへの ちょうせんね! それじゃ!$"

MatchCall_PersonalizedText41::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}だ。\pポケモンは げんきかね?\pうちの ドラゴンポケモンは\nちょうしが いいようだ。 それでは。$"

MatchCall_PersonalizedText42::
	.string "{JPN}{STR_VAR_1}だ。\pうちの {STR_VAR_2}は まえより\nずっと つよく なったぞ。\pこんどは まけない。\nつぎを たのしみに して いろ!\pそれじゃ またな!$"

MatchCall_PersonalizedText43::
	.string "{JPN}{STR_VAR_1}で ござる。\pかくれみの わざを みがきつづけて\nおり ました。\pだが うまく いきすぎて だれにも\nみつけて もらえませぬ。\lうまく いくほど さびしい ものよ…\pけむりの ごとく きえまする!\nさらば!$"

MatchCall_PersonalizedText44::
	.string "{JPN}{STR_VAR_1}だ。\nあれから きたえつづけて いる。\pうちの {STR_VAR_2}は かなり\nつよく なって きたぞ。\pはまべでの れんしゅうは やはり\nききめが あるな。 それじゃ!$"

MatchCall_PersonalizedText45::
	.string "{JPN}ごきげんよう。\n{STR_VAR_1}です。\pこの いやな かざんばいは\nいつまで ふるのかしら?\pつもりすぎると ひがさの もようが\nみえなく なって しまうわ…\pまた あう やくそくを しましょう!$"

MatchCall_PersonalizedText46::
	.string "{JPN}やあ {STR_VAR_1}だ。\pプールより うみの ほうが うかびやすいのを\nしって いたかい?\pじっと して いるだけで からだが\nかってに うくんだ。\pただし ながく うかんで いると\nとおくまで ながされるから\lきを つけるんだぞ。\p…ところで ここは どこだ?\nいかないと!$"

MatchCall_PersonalizedText47::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}です。\lいま やまの なかに います。\pでも じめんが でこぼこで\nテントが はれないの…\pあ! いい ことを おもいついた!\pポケモンに じめんを ふみかためて\nもらえば いいんだわ!\pためして みるわね!\nバイバイ!$"

MatchCall_PersonalizedText48::
	.string "{JPN}あ こんにちは {STR_VAR_1}です!\pリブと いっしょに ポケモンを\nそだてて いるの! がんばって るわ!\pもっと がんばれば 1ばんに\nなれるかしら? バイバイ!$"

MatchCall_PersonalizedText49::
	.string "{JPN}{STR_VAR_1}だ!\pふなのりだが いまは ふねに\nのって いない。\pりくに いる ふなのりは なんと\nよべば いいのかな?\pなみを ながめながら そんな ことを\nかんがえて いたんだ。\pそれじゃ また こんど!$"

MatchCall_PersonalizedText50::
	.string "{JPN}{STR_VAR_1}だ。\nどうだ ポケモンは ふえたか?\pあたらしい ポケモンを つかまえたら\nみせに きて くれよ。\pねだったり しないから ほんとうだ。\nまって るぞ。 それじゃ。$"

MatchCall_PersonalizedText51::
	.string "{JPN}{STR_VAR_1}です。\pポケモンを いちばん よい かたちで そだてて\nいますか?\pわたしの いる ところは くうきが\nきれい。 ポケモンを そだてるのに\lぴったりです。\pそだてる ことに うちこむなら\n{STR_VAR_2}に きて ください。 それでは\lまた。$"

MatchCall_PersonalizedText52::
	.string "{JPN}こんにちは {STR_VAR_1}です。\pうちの {STR_VAR_2}に {POKEBLOCK}を\nあげたら とても よろこびました。\pポケモンにも {POKEBLOCK}の すききらいが\nあるようですね。\pとても おもしろいと おもいます。\nそれでは また。$"

MatchCall_PersonalizedText53::
	.string "{JPN}{STR_VAR_1}だ。\pポケモンと ちからを あわせれば\nやせいでも こころよく くらせる。\pみんな それに きづいて もっと\nポケモンと ちからを あわせるべきだ。\pそれが りそうだと\nほんきで おもって いる。\pきみは いい みちを あるいて いるな!\nまたな!$"

MatchCall_PersonalizedText54::
	.string "{JPN}やあ {STR_VAR_1}だ。 いつでも じゅんびばんたんの\nトレーナーさ!\p{PLAYER}{KUN} どうぐは たりて いるか? ポケモンの ちょうしは\nいいか?\pみのまわりを いつも きちんと して\nおくのが たびを つづける\lひけつなんだ。\pおれも じゅんびを たしかめて くる! ゆだんは\nきんもつだぞ!$"

MatchCall_PersonalizedText55::
	.string "{JPN}{STR_VAR_1}よ!\n{STR_VAR_1}よ!\p{STR_VAR_2}は ひとどおりが おおいから\nまいにち いろんな トレーナーに\lしょうぶを いどまれるの。\pきょうは 5かい かって\n3かいしか まけなかったわ!\pあなたは どうだった?\nこんど おしえてね!$"

MatchCall_PersonalizedText56::
	.string "{JPN}おれだ {STR_VAR_1}だ。\pむしポケモンを たくさん もって いるから\nにんきものなんだ そうだろう?\pきょう おきにいりの むしを\nがっこうに もって いったんだ。\pすきな こが ないちゃった!\nわらいたければ わらって くれ。\pむしポケモンの みりょくを\nおしえないと いけないな。\pぐすん…\nそれじゃ!$"

MatchCall_PersonalizedText57::
	.string "{JPN}はあ! はあ! はあ! はあ!\pやあ! {STR_VAR_1}だ! はあ! はあ!\pのぼりながら…\nはなすのは…\lきつい うんどうだ… はあ! はあ!\pうっ ふう…\nきゅうに なって きた…\lはなしは… また こんど…\lはあ! はあ! はあ!$"

MatchCall_PersonalizedText58::
	.string "{JPN}やあ こんにちは!\pキリと いっしょに たからものを\nさがして いるんだ!\pここには なにも ないのかも\nしれないけどね…\pだいじなのは キリと いっしょに\nさがす ことなんだ。\pあっ キリ!\nな なんで おこって るんだ?\pむし して なんか いないよ!\nきみが いちばん たいせつさ!\p…{PLAYER} きるよ またね!$"

MatchCall_PersonalizedText59::
	.string "{JPN}{STR_VAR_1}だ!\pムロタウンの ジムに また\nきたえに いって きたよ。\pジムリーダーの トウキさんは\nまた つよく なった みたいだ。\pあらい なみに きたえられたとか\nなんとか いって いたな…\pだが あいかわらず かっこいい。\nおんなの ひとに もてるんだ!\lうらやましい かぎりだよ。\pなあ… トウキさんの ともだちの\nシバさんも おなじ かんじなのかな?\pあせくさかったり ひとを「おおなみ」と\nよんだり する かんじ なのかな?\lきに なるなあ。\pうーん わからないな。\pともかく また きたえに いくよ。\pそれじゃ また!$"

MatchCall_PersonalizedText60::
	.string "{JPN}きみのような わかい トレーナーと\nはなせるのは うれしい ものじゃ。\pいくつに なっても ポケモンを\nたのしむ ことは できるはずじゃ。\pわしらの ような つながりを\nもてたら すてきだと おもわんかね?\pもっとも {PLAYER}{KUN}は すでに\nポケモンと しんらいで むすばれて\lおるがのう。\pながく つづく きずなの めばえが\nもう そこに あるのじゃ。\pはっはっは!\nくじけては いかんぞ!$"

MatchCall_PersonalizedText61::
	.string "{JPN}やあ {STR_VAR_1}よ! いま しょうぶに\nかったの!\pめったに かてないのに あいては かっこいい\nスイマーの おにいさん。\pおねえちゃんは かんかん!\pよわい ふりを して\nみせたかったんだって!\pかっても まけても わたしを\nしかるのよ!\p{PLAYER}{KUN} こんど なにか いって\nあげて!\pそれじゃ また!$"

MatchCall_PersonalizedText62::
	.string "{JPN}{STR_VAR_1}です はい。 きのう うみへ\nでました。\pあたらしい いせきを みつけたいと\nおもったのです。\pですが しおに ながされて もとの ばしょに\nもどって しまい ました。\pしょうぶも まだ よわいまま… わらって\nくださって けっこう… でも\lあきらめません。\pいつか あたらしい いせきを みつけて\nみせます!\pおはなしは\nこれだけです。$"

MatchCall_PersonalizedText63::
	.string "{JPN}おーい!\nおれだ {STR_VAR_1}だ!\lいま 108ばんすいどうに いる!\lつまり いつもの ばしょだ!\pきょう きれいな スイマーの\nおねえさんが およいで きた!\pだから おおごえで おどろかせた!\pそうしたら すごい めで にらまれた!\p108ばんすいどうから\n{STR_VAR_1}が おとどけ しました!$"

MatchCall_PersonalizedText64::
	.string "{JPN}{STR_VAR_1}だ!\pすこし いそがしいんだが きょうも\nトレーナーを 5にん たおしたと\lつたえて おきたくてな。\pこの ちょうしなら つぎは\nきみにも かてそうだ。\pおれたち いい ライバルに なれそうだな。\nそれじゃ また!$"

MatchCall_BattleFrontierStreakText1::
	.string "{JPN}やあ! {STR_VAR_1}だよ。\nうわさを きいたよ!\p{STR_VAR_2}で すごい せいせきを\nだしたんだって?\pすごいね {STR_VAR_3}れんしょうだって?\nそれじゃ また!$"

MatchCall_BattleFrontierStreakText2::
	.string "{JPN}こんにちは {STR_VAR_1}です!\nうわさを ききました!\p{STR_VAR_2}で {STR_VAR_3}れんしょうを\nしたそうですね。\pすごい! わたしも がんばらないと!\nそれでは!$"

MatchCall_BattleFrontierStreakText3::
	.string "{JPN}よお {PLAYER}! おれだ\n{STR_VAR_1}だ。\p{STR_VAR_2}で\nあばれまわったそうだな!\p{STR_VAR_3}れんしょうか… たいした\nきろくじゃないか。\pおれも しっかり しないとな!\nまたな!$"

MatchCall_BattleFrontierStreakText4::
	.string "{JPN}よお {PLAYER}{KUN}。 {STR_VAR_1}だ。\nどうだ?\p{STR_VAR_2}で {STR_VAR_3}れんしょう したと\nうわさに なって\lいるぞ。\pおれも がんばらないとな。\nそれじゃ!$"

MatchCall_BattleFrontierStreakText5::
	.string "{JPN}やあ {PLAYER}{KUN}!\n{STR_VAR_1}よ。\p{STR_VAR_2}で {STR_VAR_3}れんしょう\nしたの?\lすごいじゃない!\pわたしも もっと ポケモンを そだてないと。 また\nね!$"

MatchCall_BattleFrontierStreakText6::
	.string "{JPN}よお {PLAYER}{KUN}。 {STR_VAR_1}だ。\nげんきか?\pところで {STR_VAR_2}で\n{STR_VAR_3}れんしょう したと\lきいたぞ。\pおれも てもちを そだてる きに\nなったよ。$"

MatchCall_BattleFrontierStreakText7::
	.string "{JPN}…あの {PLAYER}{KUN}?\n{STR_VAR_1}です…\pそうそう {STR_VAR_2}に\nいって いたのですよね?\pそこで {STR_VAR_3}れんしょう したとか。\pあっ めずらしい ポケモンが!\nいかないと!$"

MatchCall_BattleFrontierStreakText8::
	.string "{JPN}あら {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。 おげんきで\lなによりです。\pそうそう {STR_VAR_2}で\n{STR_VAR_3}れんしょう\lしたそうですね。\pとても みごとです! これからも がんばって\nください。$"

MatchCall_BattleFrontierStreakText9::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}よ!\pきいたわ! {STR_VAR_2}で\n{STR_VAR_3}れんしょうですって!\pすごいじゃない!\nわたしも がんばらないと!$"

MatchCall_BattleFrontierStreakText10::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは…\n{STR_VAR_1}です。\p{STR_VAR_2}で {STR_VAR_3}れんしょう\nしたのですか?\pたいした ものですね。\nわたしも がんばらないと。$"

MatchCall_BattleFrontierStreakText11::
	.string "{JPN}ああ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\p{STR_VAR_2}で おそれられて\nいるそうだな?\pたしか {STR_VAR_3}れんしょう\nだったか?\pたいした ものだ。 わしは なんかい\nかてるかな?$"

MatchCall_BattleFrontierStreakText12::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\lおげんきですか?\pあなたの うわさを\nききました。 {STR_VAR_2}で {STR_VAR_3}れんしょう\lしたとか。\pたいした ものですね。\nそれでは!$"

MatchCall_BattleFrontierStreakText13::
	.string "{JPN}ああ こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\lおげんきで なによりです。\p{STR_VAR_2}で {STR_VAR_3}れんしょう\nしたそうですね。\pその げんきさが うらやましい!\nでは また。$"

MatchCall_BattleFrontierStreakText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\pうわさを ききましたよ!\n{STR_VAR_2}で {STR_VAR_3}れんしょう\lしたのでしょう?\pはげみに なりますわ!\nバイバイ!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "{JPN}やあ! {STR_VAR_1}だよ。\nうわさを きいたよ!\p{STR_VAR_2}で すごい せいせきを\nだしたんだって?\pすごいね {STR_VAR_3}れんしょうだよ!\nそれじゃ また!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "{JPN}こんにちは {STR_VAR_1}です!\nうわさを ききました!\p{STR_VAR_2}で {STR_VAR_3}れんしょうを\nしたそうですね。\pすごい! わたしも がんばらないと!\nそれでは!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "{JPN}よお {PLAYER}! おれだ\n{STR_VAR_1}だ。\p{STR_VAR_2}で\nあばれまわったそうだな!\p{STR_VAR_3}れんしょうか… たいした\nきろくじゃないか。\pおれも しっかり しないとな!\nまたな!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "{JPN}よお {PLAYER}{KUN}。 {STR_VAR_1}だ。\nどうだ?\p{STR_VAR_2}で {STR_VAR_3}れんしょう したと\nうわさに なって\lいるぞ。\pおれも がんばらないとな。\nそれじゃ!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "{JPN}やあ {PLAYER}{KUN}!\n{STR_VAR_1}よ。\p{STR_VAR_2}で {STR_VAR_3}れんしょう\nしたの?\lすごいじゃない!\pわたし? まあまあ ってところね。 また\nね!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "{JPN}よお {PLAYER}{KUN}。 {STR_VAR_1}だ。\nげんきか?\pところで {STR_VAR_2}で\n{STR_VAR_3}れんしょう したと\lきいたぞ。\pおれも がんばらないとな!\nまたな!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "{JPN}…あの {PLAYER}{KUN}?\n{STR_VAR_1}です…\pそうそう {STR_VAR_2}に\nいって いたのですよね?\pそこで {STR_VAR_3}れんしょう したとか。\pあっ めずらしい ポケモンが!\nいかないと!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "{JPN}あら {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。 おげんきで\lなによりです。\pそうそう {STR_VAR_2}で\n{STR_VAR_3}れんしょう\lしたそうですね。\pとても みごとです! わたしも ポケモンを\nそだてないと!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}よ!\pきいたわ! {STR_VAR_2}で\n{STR_VAR_3}れんしょうですって!\pすごいじゃない!\nわたしも がんばらないと!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは…\n{STR_VAR_1}です。\p{STR_VAR_2}で {STR_VAR_3}れんしょう\nしたのですか?\pたいした ものですね。\nわたしも がんばらないと。$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "{JPN}ああ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\p{STR_VAR_2}で おそれられて\nいるそうだな?\pたしか {STR_VAR_3}れんしょう\nだったか?\pたいした ものだ。 わしは なんかい\nかてるかな?$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\lおげんきですか?\pあなたの うわさを\nききました。 {STR_VAR_2}で {STR_VAR_3}れんしょう\lしたとか。\pたいした ものですね。\nそれでは!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "{JPN}ああ こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\lおげんきで なによりです。\p{STR_VAR_2}で {STR_VAR_3}れんしょう\nしたそうですね。\pその げんきさが うらやましい!\nでは また。$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\lうわさを ききましたよ!\p{STR_VAR_2}で {STR_VAR_3}れんしょう\nしたのでしょう?\pはげみに なりますわ!\nバイバイ!$"

MatchCall_BattleDomeText1::
	.string "{JPN}やあ! {PLAYER}?\nこんにちは {STR_VAR_1}だよ!\lうわさを きいたよ!\p{STR_VAR_2}で {STR_VAR_3}かいも\nゆうしょう したんだって?\pすごいね! ぼくも がんばらないと!\nそれじゃ また!$"

MatchCall_BattleDomeText2::
	.string "{JPN}こんにちは {STR_VAR_1}です!\nうわさを ききました!\p{STR_VAR_2}で {STR_VAR_3}かい\nゆうしょう したそうですね。\pすごい! わたしも ゆうしょう\nできるでしょうか?$"

MatchCall_BattleDomeText3::
	.string "{JPN}よお {PLAYER}!\nおれだ {STR_VAR_1}だ。\lちょうしは どうだ?\p{STR_VAR_2}で {STR_VAR_3}かいも\nゆうしょう したそうだな!\pつぎは もう 1かい ふやせよ!\nまたな!$"

MatchCall_BattleDomeText4::
	.string "{JPN}よお {PLAYER}{KUN}。\n{STR_VAR_1}だ。\p{STR_VAR_2}で {STR_VAR_3}かい\nゆうしょう したそうだな。\pがんばって いるようだな。\nおれも おいつかないとな!$"

MatchCall_BattleDomeText5::
	.string "{JPN}やあ {PLAYER}{KUN}!\n{STR_VAR_1}よ。\p{STR_VAR_2}で {STR_VAR_3}かいも\nゆうしょう したんですって。\pわたしも がんばらないと!\nまた ね!$"

MatchCall_BattleDomeText6::
	.string "{JPN}よお {PLAYER}{KUN}? {STR_VAR_1}だ。\nげんきか?\pところで {STR_VAR_2}で {STR_VAR_3}かい\nゆうしょう したと\lきいたぞ。\pこれいじょう はなされる まえに ポケモンを\nそだてないとな。$"

MatchCall_BattleDomeText7::
	.string "{JPN}{PLAYER}{KUN}?\n{STR_VAR_1}です。\p{STR_VAR_2}で {STR_VAR_3}かいも\nゆうしょう したのですね?\pすてきです。 ところで さいきん\nめずらしい ポケモンは つかまえました?\pそう ですか。\nそれでは。$"

MatchCall_BattleDomeText8::
	.string "{JPN}あら {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。\lおげんきで なによりです。\lそうでしょうとも。\p{STR_VAR_2}で {STR_VAR_3}かい\nゆうしょう したと ききました。\pわたしも あなたのように\nポケモンを そだてないと。 では また。$"

MatchCall_BattleDomeText9::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}よ!\pきいたわ! {STR_VAR_2}で\n{STR_VAR_3}かいも ゆうしょうですって!\pすごいじゃない!\nわたしも がんばらないと!$"

MatchCall_BattleDomeText10::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\p{STR_VAR_2}で {STR_VAR_3}かい つづけて\nゆうしょう したのですか?\pたいした ものですね。\nわたしも がんばらないと。$"

MatchCall_BattleDomeText11::
	.string "{JPN}ああ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\p{STR_VAR_2}で おそれられて\nいるそうだな?\pたしか {STR_VAR_3}かい つづけて ゆうしょう\nしたとか?\pわしにも ゆうしょうが\nできるかのう?\p…まず むりかのう? では\nまた!$"

MatchCall_BattleDomeText12::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\lおげんきですか?\p{STR_VAR_2}と いう ところで\n{STR_VAR_3}かい ゆうしょう したとか?\pたいした ものですね。\nそれでは!$"

MatchCall_BattleDomeText13::
	.string "{JPN}ああ こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\lおげんきで なによりです。\p{STR_VAR_2}で {STR_VAR_3}かい\nゆうしょう したそうですね?\pその げんきさが うらやましい!\nでは また。$"

MatchCall_BattleDomeText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\lうわさを ききましたよ!\p{STR_VAR_2}で {STR_VAR_3}かい\nゆうしょう したのでしょう?\pはげみに なりますわ!\nまた ね!$"

MatchCall_BattlePikeText1::
	.string "{JPN}やあ! {PLAYER}?\nこんにちは {STR_VAR_1}だよ!\lうわさを きいたよ!\p{STR_VAR_2}で {STR_VAR_3}つの ルームを\nかちぬいたんだって!\pすごいね!\nそれじゃ また!$"

MatchCall_BattlePikeText2::
	.string "{JPN}こんにちは {STR_VAR_1}です!\nうわさを ききました!\p{STR_VAR_2}で {STR_VAR_3}つの ルームを\nかちぬいたそうですね。\pもっと がんばらないと!\nそれでは!$"

MatchCall_BattlePikeText3::
	.string "{JPN}よお {PLAYER}!\nおれだ {STR_VAR_1}だ。\lちょうしは どうだ?\p{STR_VAR_2}で {STR_VAR_3}つの ルームを\nかちぬいたそうだな!\pつぎは もっと いけよ!\nまたな!$"

MatchCall_BattlePikeText4::
	.string "{JPN}よお {PLAYER}{KUN}。\n{STR_VAR_1}だ。\p{STR_VAR_2}で {STR_VAR_3}つの ルームを\nかけぬけたそうだな。\pおれも ポケモンを きたえて\nおいつかないとな!$"

MatchCall_BattlePikeText5::
	.string "{JPN}やあ {PLAYER}{KUN}!\n{STR_VAR_1}よ。\p{STR_VAR_2}で {STR_VAR_3}つの ルームを\nこえたそうね。\pわたしも がんばらないと!\nまた ね!$"

MatchCall_BattlePikeText6::
	.string "{JPN}よお {PLAYER}{KUN}?\n{STR_VAR_1}だ。 げんきか?\pところで {STR_VAR_2}で {STR_VAR_3}つの\nルームを かちぬいたと きいたぞ。\pこれいじょう はなされる まえに\nポケモンを そだてないとな。$"

MatchCall_BattlePikeText7::
	.string "{JPN}{PLAYER}{KUN}?\n{STR_VAR_1}です。\p{STR_VAR_2}で {STR_VAR_3}つの ルームを\nかちぬいたのですね?\pすごいです。\pあっ めずらしい ポケモンが!\nそれでは。$"

MatchCall_BattlePikeText8::
	.string "{JPN}あら {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。\lおげんきで なによりです。\lそうでしょうとも。\p{STR_VAR_2}で {STR_VAR_3}つの ルームを\nかちぬいたと ききました。\pとても みごとです!\nわたしも あなたのように そだてないと。\lでは また。$"

MatchCall_BattlePikeText9::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}よ!\pきいたわ! {STR_VAR_2}で {STR_VAR_3}つの\nルームを かちぬいたんですって!\pすごいじゃない!\nわたしも がんばらないと!$"

MatchCall_BattlePikeText10::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\p{STR_VAR_2}で {STR_VAR_3}つの ルームを\nかちぬいたのですか?\pたいした ものですね。\nわたしも がんばらないと。$"

MatchCall_BattlePikeText11::
	.string "{JPN}ああ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\p{STR_VAR_2}で おそれられて\nいるそうだな?\pたしか {STR_VAR_3}つの ルームを こえたとか? それは\nたいした ものだ。\pわしにも ゆうしょうが\nできるかのう?\p…まず むりかのう? では\nまた!$"

MatchCall_BattlePikeText12::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\lおげんきですか?\p{STR_VAR_2}と いう ところで {STR_VAR_3}つの\nルームを かちぬいたとか?\pたいした ものですね。\nそれでは!$"

MatchCall_BattlePikeText13::
	.string "{JPN}ああ こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\lおげんきで なによりです。\p{STR_VAR_2}で {STR_VAR_3}つの ルームを\nかちぬいたそうですね?\pその げんきさが うらやましい!\nでは また。$"

MatchCall_BattlePikeText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\lうわさを ききましたよ!\p{STR_VAR_2}で {STR_VAR_3}つの ルームを\nかちぬいたのでしょう?\pはげみに なりますわ!\nまた ね!$"

MatchCall_BattlePyramidText1::
	.string "{JPN}やあ! {PLAYER}?\nこんにちは {STR_VAR_1}だよ!\lうわさを きいたよ!\p{STR_VAR_2}の なかを {STR_VAR_3}かい\nのぼったんだって?\pすごいね!\nぼくも ちょうせん して みようかな。$"

MatchCall_BattlePyramidText2::
	.string "{JPN}こんにちは {STR_VAR_1}です!\nうわさを ききました!\p{STR_VAR_2}の なかを {STR_VAR_3}かい\nかちぬいたそうですね。\pわあ すばらしい!\nわたしも ポケモンを そだてないと!$"

MatchCall_BattlePyramidText3::
	.string "{JPN}よお {PLAYER}!\nおれだ {STR_VAR_1}だ。\lちょうしは どうだ?\p{STR_VAR_2}の なかを {STR_VAR_3}かい\nのぼったそうだな!\pつぎは もっと うえまで いけよ!\nまたな!$"

MatchCall_BattlePyramidText4::
	.string "{JPN}よお {PLAYER}{KUN}。\n{STR_VAR_1}だ。\p{STR_VAR_2}の なかを {STR_VAR_3}かい\nのぼったそうだな。\pおれも がんばって\nおいつかないとな!$"

MatchCall_BattlePyramidText5::
	.string "{JPN}やあ {PLAYER}{KUN}!\n{STR_VAR_1}よ。\p{STR_VAR_2}の なかを {STR_VAR_3}かい\nのぼったそうね。\pわたしも がんばらないと!\nまた ね!$"

MatchCall_BattlePyramidText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you got through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "I'd better raise my POKéMON before\n"
	.string "you pull further ahead.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won your way up {STR_VAR_3} floors?\p"
	.string "Neat. Were there any rare POKéMON\n"
	.string "there?\p"
	.string "No, huh?\n"
	.string "Okay, bye.$"

MatchCall_BattlePyramidText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Oh, but, you are.\p"
	.string "I've heard that you got through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "That's quite impressive!\n"
	.string "I must raise my POKéMON like you.\l"
	.string "See you again.$"

MatchCall_BattlePyramidText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You won your way through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattlePyramidText10::
	.string "Oh, {PLAYER}{KUN}, hello.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You climbed {STR_VAR_3} floors inside\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattlePyramidText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You rose through, what, {STR_VAR_3} floors?\n"
	.string "That's gotta count for something.\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattlePyramidText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You've won through {STR_VAR_3} floors in\n"
	.string "a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattlePyramidText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattlePyramidText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you get through {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_Text_Mom1::
	.string "MOM: Your father and you…\n"
	.string "Everyone is captivated by POKéMON.\p"
	.string "What is the charm of POKéMON?\p"
	.string "Me?\n"
	.string "I adore POKéMON that help me with\l"
	.string "my everyday chores.$"

MatchCall_Text_Mom2::
	.string "MOM: Hi, {PLAYER}!\n"
	.string "Your father keeps himself locked\l"
	.string "away in the PETALBURG GYM.\p"
	.string "He comes home every so often.\n"
	.string "But he goes back to the GYM when\l"
	.string "he's eaten everything he can.\p"
	.string "I'm guessing that losing to you\n"
	.string "was a big blow to his pride!$"

MatchCall_Text_Mom3::
	.string "MOM: {PLAYER}…\n"
	.string "Don't worry about me or the house.\p"
	.string "Wear those RUNNING SHOES until\n"
	.string "they fall apart, honey!$"

MatchCall_Text_Roxanne1::
	.string "ROXANNE: Oh, hello, {PLAYER}!\p"
	.string "I've been hard at work retraining\n"
	.string "since we met.\p"
	.string "I will still need some more time\n"
	.string "before I can reopen the GYM.\p"
	.string "But when I do, please visit my GYM\n"
	.string "for a rematch!$"

MatchCall_Text_Roxanne2::
	.string "ROXANNE: Is this {PLAYER}?\n"
	.string "Congratulations!\l"
	.string "I've been hearing about you!\p"
	.string "As for me, I need some more time\n"
	.string "before I can reopen the GYM.\p"
	.string "But when I do, please visit my GYM\n"
	.string "for a rematch!$"

MatchCall_Text_Roxanne3::
	.string "ROXANNE: {PLAYER}!\n"
	.string "My GYM is ready!\p"
	.string "Please visit RUSTBORO whenever\n"
	.string "you can!$"

MatchCall_Text_Roxanne4::
	.string "ROXANNE: At the RUSTBORO GYM,\n"
	.string "the fact that we battled, {PLAYER},\l"
	.string "is a matter of pride.$"

MatchCall_Text_Brawly1::
	.string "BRAWLY: Hey, there, {PLAYER}{KUN}!\p"
	.string "I learned a lot from the battle we\n"
	.string "had together.\p"
	.string "I intend to do my training over,\n"
	.string "then reopen the GYM.\p"
	.string "It's going to take some time before\n"
	.string "I'm ready to run the GYM again.\p"
	.string "But if I can reopen the GYM,\n"
	.string "I want you to challenge us again.$"

MatchCall_Text_Brawly2::
	.string "BRAWLY: Hey, {PLAYER}{KUN}!\n"
	.string "Congratulations!\p"
	.string "Word about your exploits arrived\n"
	.string "on tidal winds!\p"
	.string "It appears as if I need to work on\n"
	.string "my training some more.\p"
	.string "It's going to take some time before\n"
	.string "I'm ready to run the GYM again.\p"
	.string "But if I can reopen the GYM,\n"
	.string "I want you to challenge us again.$"

MatchCall_Text_Brawly3::
	.string "BRAWLY: Hey, {PLAYER}{KUN}!\n"
	.string "My GYM's ready for action!\p"
	.string "Come back to DEWFORD anytime\n"
	.string "for another challenge!$"

MatchCall_Text_Brawly4::
	.string "BRAWLY: {PLAYER}{KUN}, I don't think\n"
	.string "I'll ever get bored of battling you!$"

MatchCall_Text_Wattson1::
	.string "WATTSON: Oh, it's you!\p"
	.string "After you left, I've been redoing\n"
	.string "my training from scratch.\p"
	.string "I'd say I could use a wee bit more\n"
	.string "time to reopen my GYM.\p"
	.string "You'll have to wait till then!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson2::
	.string "WATTSON: Wahahahaha!\p"
	.string "You've really done it, haven't you?\n"
	.string "I've been getting word about you!\p"
	.string "It seems I need to retrain some\n"
	.string "more still.\p"
	.string "I'd say I could use a wee bit more\n"
	.string "time to reopen my GYM.\p"
	.string "You'll have to wait till then!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson3::
	.string "WATTSON: Oh, it's you!\n"
	.string "My GYM's ready!\p"
	.string "Visit MAUVILLE anytime!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson4::
	.string "WATTSON: Wahahaha!\p"
	.string "A battle with you is always charged\n"
	.string "with shocking power!$"

MatchCall_Text_Flannery1::
	.string "FLANNERY: {PLAYER}…\p"
	.string "When we battled, I learned exactly\n"
	.string "how immature I was.\p"
	.string "But I'm not done yet!\p"
	.string "I'm going to redo my training and\n"
	.string "reopen the GYM.\p"
	.string "When the time comes, {PLAYER},\n"
	.string "please challenge us again.$"

MatchCall_Text_Flannery2::
	.string "FLANNERY: Hello, {PLAYER}?\n"
	.string "Congratulations!\p"
	.string "Word of your success has reached\n"
	.string "us like the heat of a volcano!\p"
	.string "Our training is coming along very\n"
	.string "well here.\p"
	.string "When the GYM's ready, a mark will\n"
	.string "appear beside my name in the\l"
	.string "MATCH CALL list.$"

MatchCall_Text_Flannery3::
	.string "FLANNERY: Oh, {PLAYER}?\n"
	.string "Our GYM's ready!\p"
	.string "Come to LAVARIDGE for a soak\n"
	.string "in the hot spring and a challenge!$"

MatchCall_Text_Flannery4::
	.string "FLANNERY: {PLAYER}…\n"
	.string "I'm positive that you keep getting\l"
	.string "better at training every time.$"

MatchCall_Text_Winona1::
	.string "WINONA: Hello, {PLAYER}!\p"
	.string "Thanks to our battle, I've come\n"
	.string "to understand my weak points!\p"
	.string "When I reopen the GYM, I won't go\n"
	.string "down in defeat again!$"

MatchCall_Text_Winona2::
	.string "WINONA: You've done it, {PLAYER}!\p"
	.string "News about the new CHAMPION\n"
	.string "has reached us in FORTREE!\p"
	.string "But… The next time we battle,\n"
	.string "it's not going to end the same way.$"

MatchCall_Text_Winona3::
	.string "WINONA: Is this {PLAYER}?\n"
	.string "Our GYM is back in operation!\p"
	.string "We're waiting for you in FORTREE!$"

MatchCall_Text_Winona4::
	.string "WINONA: {PLAYER}…\n"
	.string "Though I have lost, my wings will\l"
	.string "never break.\p"
	.string "Yes, in exactly the same way that\n"
	.string "you never lost sight of your dream.$"

MatchCall_Text_TateLiza1::
	.string "TATE: Oh! You're…\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: We're in training again…\n"
	.string "LIZA: So we can reopen our GYM!\p"
	.string "TATE: When our GYM is ready…\n"
	.string "LIZA: When our GYM is ready…\p"
	.string "TATE: A mark'll appear by our name…\n"
	.string "LIZA: On the MATCH CALL list.$"

MatchCall_Text_TateLiza2::
	.string "TATE: {PLAYER}, congratulations!\n"
	.string "LIZA: {PLAYER}, congratulations!\p"
	.string "TATE: The two of us are…\n"
	.string "LIZA: Still in training!\p"
	.string "TATE: We need some more time, but…\n"
	.string "LIZA: When our GYM is ready…\p"
	.string "TATE: A mark'll appear by our name…\n"
	.string "LIZA: On the MATCH CALL list.$"

MatchCall_Text_TateLiza3::
	.string "TATE: {PLAYER}!\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: Our GYM is ready!\n"
	.string "LIZA: Our GYM is ready!\p"
	.string "TATE: Please come visit…\n"
	.string "LIZA: MOSSDEEP anytime!$"

MatchCall_Text_TateLiza4::
	.string "TATE: {PLAYER}, the battle we had…\n"
	.string "LIZA: Is an invaluable experience.\p"
	.string "TATE: It would be nice if…\n"
	.string "LIZA: We could all battle again!$"

MatchCall_Text_Juan1::
	.string "JUAN: Hmm…\n"
	.string "{PLAYER}{KUN}… Was it?\p"
	.string "Our battle together--it brought\n"
	.string "to me memories of when I first\l"
	.string "encountered WALLACE.\p"
	.string "Perhaps you are a genius who may\n"
	.string "yet surpass WALLACE!$"

MatchCall_Text_Juan2::
	.string "JUAN: Fufu… {PLAYER}{KUN}…\n"
	.string "You've finally achieved your goal.\p"
	.string "My eye for appraising talent wasn't\n"
	.string "mistaken…\p"
	.string "I wish for another chance to meet\n"
	.string "you, for you have scaled the peak\l"
	.string "of power and prestige.$"

MatchCall_Text_Juan3::
	.string "JUAN: Hoho… {PLAYER}{KUN}…\p"
	.string "Our SOOTOPOLIS GYM has finally\n"
	.string "reopened.\p"
	.string "If you wish to see me, you are\n"
	.string "welcome to visit anytime.$"

MatchCall_Text_Juan4::
	.string "JUAN: {PLAYER}{KUN}…\p"
	.string "Like the finest music, the battles\n"
	.string "we wage together strike chords\l"
	.string "of inspiration in my heart…\p"
	.string "When I close my eyes, I see visions\n"
	.string "of you soaring with the melody…$"

MatchCall_Text_Sidney::
	.string "SIDNEY: Yo, {PLAYER}!\p"
	.string "If you want to battle with me\n"
	.string "again, you come on back whenever\l"
	.string "you like to the POKéMON LEAGUE.\p"
	.string "I'll always be here!\n"
	.string "I'll be waiting!$"

MatchCall_Text_Phoebe::
	.string "PHOEBE: Hi, {PLAYER}!\p"
	.string "How about coming back here again\n"
	.string "sometime?\p"
	.string "I'd like to see how much tighter\n"
	.string "your bond has grown with your\l"
	.string "POKéMON.$"

MatchCall_Text_Glacia::
	.string "GLACIA: Hello, {PLAYER}.\p"
	.string "I trust you haven't become\n"
	.string "complacent with your power?\p"
	.string "If you feel the need to cool your\n"
	.string "hot emotions just a little, do come\l"
	.string "to the POKéMON LEAGUE…$"

MatchCall_Text_Drake::
	.string "DRAKE: That voice… {PLAYER}, is it?\n"
	.string "You sound well…\p"
	.string "I understand that there is now\n"
	.string "a facility called the BATTLE\l"
	.string "FRONTIER that tests the skills of\l"
	.string "TRAINERS.\p"
	.string "However, if you wish to have real\n"
	.string "battles, there is no substitute for\l"
	.string "the POKéMON LEAGUE!\p"
	.string "Don't you agree, {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "WALLACE: Hello, {PLAYER}{KUN}.\n"
	.string "Have you met STEVEN?\p"
	.string "He is…\n"
	.string "Actually incredibly skilled.\p"
	.string "However, he's an odd soul who\n"
	.string "rarely battles.\p"
	.string "Instead, he would rather look for\n"
	.string "rare stones.\p"
	.string "I'm sure he's digging in a cave or\n"
	.string "a craggy mountain somewhere.\p"
	.string "But what is a rare stone exactly?\n"
	.string "All I can think of is a METEORITE…$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Beep!\p"
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "I was just in PACIFIDLOG a little\n"
	.string "while ago.\p"
	.string "I saw a giant green POKéMON\n"
	.string "flying high in the sky.\p"
	.string "I…\n"
	.string "I've never seen anything like it.\p"
	.string "I wonder what it was.\n"
	.string "Is this maybe a major discovery?\p"
	.string "… … … … … …\n"
	.string "… … … … … Click!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Beep!\p"
	.string "BRENDAN: Hey, {PLAYER}!\n"
	.string "I was in PACIFIDLOG just now.\p"
	.string "I saw this huge green POKéMON\n"
	.string "flying across the sky.\p"
	.string "I've never seen anything that\n"
	.string "amazing before.\p"
	.string "I wish you could've seen it,\n"
	.string "{PLAYER}.\p"
	.string "… … … … … …\n"
	.string "… … … … … Click!$"

MatchCall_Text_May1::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "MR. BRINEY retired as a SAILOR,\n"
	.string "but I still see him out on the sea\l"
	.string "with his pet PEEKO sometimes.\p"
	.string "He must love the sea still.$"

MatchCall_Text_May2::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "You know how little towns like\n"
	.string "PETALBURG and DEWFORD have GYMS?\p"
	.string "For some reason, the big port of\n"
	.string "SLATEPORT doesn't have a GYM.\p"
	.string "When they finally build a GYM there,\n"
	.string "I should apply to be the LEADER.$"

MatchCall_Text_May3::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "Do you remember a man named\n"
	.string "the CUTTER in RUSTBORO?\l"
	.string "He had a house there, remember?\p"
	.string "Well, I found out his younger\n"
	.string "brother lives in MAUVILLE.\p"
	.string "Can you guess his name?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "The ROCK SMASH GUY!$"

MatchCall_Text_May4::
	.string "MAY: {PLAYER}{KUN}?\p"
	.string "RUSTURF TUNNEL…\n"
	.string "They named it that because it\l"
	.string "joins RUSTBORO and VERDANTURF.$"

MatchCall_Text_May5::
	.string "MAY: {PLAYER}{KUN}, how are you?\p"
	.string "I'm out on ROUTE 111 now.\p"
	.string "I'm going to get a rest at an old\n"
	.string "lady's house.\p"
	.string "She lives just north of\n"
	.string "the desert.$"

MatchCall_Text_May6::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "Did you know about the MIRAGE\n"
	.string "TOWER in the desert?\p"
	.string "They say, like a mirage, it seems\n"
	.string "to mysteriously come and go.\p"
	.string "I wish I could see it.$"

MatchCall_Text_May7::
	.string "MAY: {PLAYER}{KUN}, yahoo!\n"
	.string "I'm on ROUTE 119 now.\p"
	.string "There's a big river here, and\n"
	.string "it often rains.\p"
	.string "I got soaked!$"

MatchCall_Text_May8::
	.string "MAY: {PLAYER}{KUN}, hi.\p"
	.string "MT. PYRE is a memorial to POKéMON\n"
	.string "whose lives have ended.\p"
	.string "Maybe as a result, it's infested\n"
	.string "with many GHOST-type POKéMON!$"

MatchCall_Text_May9::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "I was thinking of going to the hot\n"
	.string "spring in LAVARIDGE.\p"
	.string "But on the way, around JAGGED\n"
	.string "PASS, I ran into some bad-looking\l"
	.string "characters. The mood was ugly!$"

MatchCall_Text_May10::
	.string "MAY: Hi, {PLAYER}{KUN}!\n"
	.string "Did you see the news?\p"
	.string "They say CAPT. STERN discovered\n"
	.string "the SEAFLOOR CAVERN while on his\l"
	.string "submarine expedition.$"

MatchCall_Text_May11::
	.string "MAY: Hi, {PLAYER}{KUN}!\n"
	.string "Don't you think it's neat?\p"
	.string "Even if you don't have a boat,\n"
	.string "you can cross the sea using\l"
	.string "a POKéMON's move.\p"
	.string "Did you know there's more?\p"
	.string "There's a POKéMON move that lets\n"
	.string "you go to the bottom of the sea.$"

MatchCall_Text_May12::
	.string "MAY: Hi, {PLAYER}{KUN}!\n"
	.string "Hope things are okay!\p"
	.string "Have you been on the sea and\n"
	.string "found your way to the other side\l"
	.string "blocked?\p"
	.string "Try diving deep underwater and\n"
	.string "following trenches.\p"
	.string "When you get to the other side,\n"
	.string "come up to the surface. Easy!$"

MatchCall_Text_May13::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "How's it going?\n"
	.string "Are you filling your POKéDEX?\p"
	.string "I heard a rumor that there are\n"
	.string "super-ancient POKéMON out there.\l"
	.string "And there are three of them!\p"
	.string "I would love to see even one…$"

MatchCall_Text_May14::
	.string "MAY: {PLAYER}{KUN}!\n"
	.string "I heard the rumors!\p"
	.string "You beat the SOOTOPOLIS GYM\n"
	.string "LEADER?\p"
	.string "That means you don't have far\n"
	.string "to go, do you?$"

MatchCall_Text_May15::
	.string "MAY: There isn't a single TRAINER\n"
	.string "left in HOENN who doesn't know who\l"
	.string "you are, {PLAYER}{KUN}!\p"
	.string "When I tell people that I'm friends\n"
	.string "with you, {PLAYER}{KUN}, they're all\l"
	.string "surprised!$"

MatchCall_Text_Brendan1::
	.string "BRENDAN: Hey, {PLAYER}!\p"
	.string "MR. BRINEY retired as a SAILOR,\n"
	.string "but I still see him out on the sea\l"
	.string "with his pet PEEKO sometimes.\p"
	.string "I guess he must love\n"
	.string "the sea still.$"

MatchCall_Text_Brendan2::
	.string "BRENDAN: Hey, {PLAYER}!\p"
	.string "I don't get how little towns like\n"
	.string "PETALBURG and DEWFORD have GYMS.\p"
	.string "I mean, not when the big port of\n"
	.string "SLATEPORT doesn't have a GYM.\p"
	.string "When they finally build a GYM there,\n"
	.string "I should apply to be the LEADER.$"

MatchCall_Text_Brendan3::
	.string "BRENDAN: Yo, {PLAYER}!\p"
	.string "Do you remember a guy named\n"
	.string "the CUTTER in RUSTBORO?\l"
	.string "He had a house there, right?\p"
	.string "Well, it turns out his little\n"
	.string "brother lives in MAUVILLE.\p"
	.string "Can you guess his name?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "The ROCK SMASH GUY!$"

MatchCall_Text_Brendan4::
	.string "BRENDAN: This voice… {PLAYER}?\p"
	.string "They gave RUSTURF TUNNEL its name\n"
	.string "because it joins RUSTBORO and\l"
	.string "VERDANTURF.\p"
	.string "Did you know that?$"

MatchCall_Text_Brendan5::
	.string "BRENDAN: {PLAYER}, what's up?\p"
	.string "Hey, I'm out on ROUTE 111 now.\p"
	.string "I'm going to rest up at an old\n"
	.string "lady's house north of the desert.\p"
	.string "If you're in the area, you should\n"
	.string "visit her, too.$"

MatchCall_Text_Brendan6::
	.string "BRENDAN: Hey, {PLAYER}!\p"
	.string "Did you know about the MIRAGE\n"
	.string "TOWER in the desert?\p"
	.string "They say, like a mirage, it can be\n"
	.string "seen only sometimes.\p"
	.string "I'd like to see that!$"

MatchCall_Text_Brendan7::
	.string "BRENDAN: Who's this? Oh, {PLAYER}?\n"
	.string "Guess what? I'm on ROUTE 119 now.\p"
	.string "There's a big river here, and\n"
	.string "it rains all the time.\p"
	.string "I got soaked to the bone!$"

MatchCall_Text_Brendan8::
	.string "BRENDAN: {PLAYER}!\p"
	.string "MT. PYRE is a memorial to POKéMON\n"
	.string "whose lives have ended.\p"
	.string "That's probably why it's infested\n"
	.string "with many GHOST-type POKéMON!$"

MatchCall_Text_Brendan9::
	.string "BRENDAN: Hey there, {PLAYER}.\p"
	.string "I was on my way back to the hot\n"
	.string "spring in LAVARIDGE.\p"
	.string "But around JAGGED PASS, I ran into\n"
	.string "some nasty-looking characters.\p"
	.string "Those creeps…\n"
	.string "I think they were TEAM MAGMA.$"

MatchCall_Text_Brendan10::
	.string "BRENDAN: Hi, {PLAYER}!\n"
	.string "Did you catch the news?\p"
	.string "They say CAPT. STERN discovered\n"
	.string "the SEAFLOOR CAVERN while on his\l"
	.string "submarine expedition.$"

MatchCall_Text_Brendan11::
	.string "BRENDAN: Hey there, {PLAYER}!\n"
	.string "Don't you think it's awesome?\p"
	.string "Even if you don't have a boat,\n"
	.string "you can cross the sea using\l"
	.string "a POKéMON's move.\p"
	.string "And, there's a move that lets you\n"
	.string "travel to the bottom of the sea.\p"
	.string "Man, POKéMON can do anything!$"

MatchCall_Text_Brendan12::
	.string "BRENDAN: Howdy, {PLAYER}!\n"
	.string "How are you holding up?\p"
	.string "Ever found your way to the other\n"
	.string "side blocked while on the sea?\p"
	.string "Try diving deep underwater and\n"
	.string "following trenches at the bottom.\p"
	.string "When you get to the other side,\n"
	.string "come up to the surface. Simple!$"

MatchCall_Text_Brendan13::
	.string "BRENDAN: Hey there, {PLAYER}!\p"
	.string "How's it going? Filling up your\n"
	.string "POKéDEX successfully?\p"
	.string "I heard a rumor that there are\n"
	.string "super-ancient POKéMON out there.\l"
	.string "And not just one--three!\p"
	.string "I'd love to catch even one…$"

MatchCall_Text_Brendan14::
	.string "BRENDAN: {PLAYER}!\n"
	.string "I heard the rumors!\p"
	.string "You beat the SOOTOPOLIS GYM\n"
	.string "LEADER? Awesome!\p"
	.string "You're getting awful close now!$"

MatchCall_Text_Brendan15::
	.string "BRENDAN: There isn't a TRAINER in\n"
	.string "all of HOENN who doesn't know who\l"
	.string "you are, {PLAYER}!\p"
	.string "When I tell people that I'm friends\n"
	.string "with you, {PLAYER}, they get pretty\l"
	.string "envious!$"

MatchCall_Text_Wally1::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "I've been getting healthier and\n"
	.string "more physically fit.\p"
	.string "I hope I can become a TRAINER like\n"
	.string "you soon, {PLAYER}!$"

MatchCall_Text_Wally2::
	.string "WALLY: {PLAYER}, hello!\p"
	.string "After RUSTURF TUNNEL went\n"
	.string "through, WANDA's been very happy!$"

MatchCall_Text_Wally3::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "I… I left my uncle's place in\n"
	.string "VERDANTURF without telling anyone.\p"
	.string "I wonder if he's furious with me…\p"
	.string "{PLAYER}, you understand how\n"
	.string "I feel, don't you?$"

MatchCall_Text_Wally4::
	.string "WALLY: {PLAYER}?\n"
	.string "It's me, WALLY!\p"
	.string "The world of TRAINERS is amazing!\p"
	.string "When I have my POKéMON with me,\n"
	.string "all sorts of people say hi!\p"
	.string "It's as if everyone's getting\n"
	.string "connected through POKéMON!$"

MatchCall_Text_Wally5::
	.string "WALLY: {PLAYER}? It's awesome!\n"
	.string "That RALTS we caught together?\l"
	.string "It evolved, {PLAYER}!\p"
	.string "Maybe I'm talented…\p"
	.string "Oh, but I shouldn't get a big head\n"
	.string "like that!\p"
	.string "After all, it's the POKéMON that\n"
	.string "should be praised!$"

MatchCall_Text_Wally6::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "WALLY appears to be out of\n"
	.string "the POKéNAV's service area…$"

MatchCall_Text_Wally7::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "Before I met you, I hardly ever\n"
	.string "left my house…\p"
	.string "But now, I'm on an adventure with\n"
	.string "my very own POKéMON…\p"
	.string "{PLAYER}…\n"
	.string "Thank you…$"

MatchCall_Text_Scott1::
	.string "SCOTT: Howdy, {PLAYER}{KUN}!\p"
	.string "You know how POKéMON can be found\n"
	.string "everywhere?\p"
	.string "Like in the mountains, in the sea,\n"
	.string "in tall grass anywhere?\p"
	.string "Just like POKéMON, you can find\n"
	.string "TRAINERS everywhere, too.\p"
	.string "As a result, I have to hurry\n"
	.string "everywhere, too. Busy, busy!$"

MatchCall_Text_Scott2::
	.string "SCOTT: I'm on ROUTE 119 right now.\n"
	.string "It's teeming with TRAINERS!\p"
	.string "It's also overgrown with tall grass\n"
	.string "everywhere, it seems.\p"
	.string "Walking around in shorts here\n"
	.string "makes me all ticklish!$"

MatchCall_Text_Scott3::
	.string "SCOTT: Hi, hi, {PLAYER}{KUN}!\p"
	.string "Have you had the chance to climb\n"
	.string "MT. PYRE?\p"
	.string "The place is a memorial to POKéMON\n"
	.string "that have passed away.\p"
	.string "It's somewhere every TRAINER\n"
	.string "should climb to the top of once.$"

MatchCall_Text_Scott4::
	.string "SCOTT: Hi, {PLAYER}{KUN}!\p"
	.string "I've been hearing about these odd\n"
	.string "gangs being a nuisance.\p"
	.string "TEAM MAGMA and TEAM AQUA,\n"
	.string "I think they were.\p"
	.string "I would think there'd be some\n"
	.string "skilled TRAINERS among them.\p"
	.string "…But if they're thugs…$"

MatchCall_Text_Scott5::
	.string "SCOTT: Oh, hi, {PLAYER}{KUN}.\p"
	.string "Might there be tough TRAINERS\n"
	.string "at the bottom of the sea?\p"
	.string "I can't go check for myself.\n"
	.string "I can't swim, for one.\l"
	.string "And I don't raise POKéMON…$"

MatchCall_Text_Scott6::
	.string "SCOTT: Hi, hi, {PLAYER}{KUN}!\p"
	.string "You know that you can challenge\n"
	.string "the POKéMON LEAGUE when you've\l"
	.string "collected all the GYM BADGES?\p"
	.string "With your talent, becoming the\n"
	.string "CHAMPION isn't a pipe dream.\p"
	.string "But did you know?\n"
	.string "There's somewhere even better.\p"
	.string "But, that's all I'm willing to say\n"
	.string "for the time being.\p"
	.string "It's something you can look\n"
	.string "forward to.\p"
	.string "When you've won your way through\n"
	.string "the POKéMON LEAGUE into the HALL\l"
	.string "OF FAME!$"

MatchCall_Text_Scott7::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "SCOTT appears to be out of\n"
	.string "the POKéNAV's service area…$"

MatchCall_Text_Norman1::
	.string "DAD: In RUSTBORO, there's a man\n"
	.string "that goes by the odd name of\l"
	.string "the CUTTER.\p"
	.string "If you're in the area, you should\n"
	.string "pay him a visit.$"

MatchCall_Text_Norman2::
	.string "DAD: Hm… Little by little, but also\n"
	.string "very surely, you're getting\l"
	.string "tougher, {PLAYER}.\p"
	.string "The stronger you get, the farther\n"
	.string "and higher you soar from Mother\l"
	.string "and me…\p"
	.string "This feeling is hard to explain.$"

MatchCall_Text_Norman3::
	.string "DAD: I see…\n"
	.string "You've collected four GYM BADGES…\p"
	.string "There's no avoiding it now.\n"
	.string "We will battle like I promised.\p"
	.string "Come anytime.\n"
	.string "We'll all be waiting for you!$"

MatchCall_Text_Norman4::
	.string "DAD: {PLAYER}! You'd better go visit\n"
	.string "Mother every so often.\p"
	.string "I'm going to remain here and\n"
	.string "redouble my training.\p"
	.string "The way of battling is deep\n"
	.string "and unforgiving!$"

MatchCall_Text_Norman5::
	.string "DAD: Oh, hi, {PLAYER}!\p"
	.string "What's that? MAGMA EMBLEM?\n"
	.string "I don't know what that's about.\p"
	.string "But with a name like that, it may\n"
	.string "be somehow linked to a volcano!$"

MatchCall_Text_Norman6::
	.string "DAD: Hiyah! Haah! Dwah!\p"
	.string "…Oh? {PLAYER}!\p"
	.string "You caught me right in the middle\n"
	.string "of a POKéMON training session!$"

MatchCall_Text_Norman7::
	.string "DAD: {PLAYER}!\p"
	.string "Who would've thought you'd become\n"
	.string "the POKéMON LEAGUE CHAMPION…\p"
	.string "Okay!\n"
	.string "I won't be left behind!$"

MatchCall_Text_Norman8::
	.string "DAD: Hm? {PLAYER}?\n"
	.string "What good timing!\p"
	.string "This time, I'm going to challenge\n"
	.string "you to battle.\p"
	.string "I'm waiting in the PETALBURG GYM.\n"
	.string "Accept my challenge anytime!$"

MatchCall_Text_Norman9::
	.string "DAD: …You amaze me, {PLAYER}.\n"
	.string "How much higher will you soar?$"

MatchCall_Text_Steven1::
	.string "STEVEN: Hi, {PLAYER}{KUN}!\p"
	.string "Have you been to MAUVILLE\n"
	.string "already?\p"
	.string "You should visit the BIKE SHOP\n"
	.string "and get a MACH BIKE.\p"
	.string "Then, try exploring the GRANITE\n"
	.string "CAVE thoroughly.\p"
	.string "You may make a new discovery\n"
	.string "there.$"

MatchCall_Text_Steven2::
	.string "STEVEN: Hi, {PLAYER}{KUN}!\p"
	.string "I've met a lot of different\n"
	.string "TRAINERS so far.\p"
	.string "But you're one of a kind.\n"
	.string "You're not like anyone else.$"

MatchCall_Text_Steven3::
	.string "STEVEN: Hi, {PLAYER}{KUN}!\p"
	.string "When you're on an adventure with\n"
	.string "your POKéMON, what do you think?\p"
	.string "Do you consider them to be strong\n"
	.string "partners?\p"
	.string "Do you think of them as fun\n"
	.string "companions?\p"
	.string "Depending on how you think, your\n"
	.string "adventure's significance changes.$"

MatchCall_Text_Steven4::
	.string "STEVEN: Hello?\n"
	.string "{PLAYER}{KUN}?\p"
	.string "I'm involved in a spot of trouble\n"
	.string "at the SPACE CENTER.\p"
	.string "I'm sorry, but I can't talk now.\n"
	.string "Bye!$"

MatchCall_Text_Steven5::
	.string "STEVEN: Oh!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "There's no need to talk.\n"
	.string "It's past time for talking.\p"
	.string "You have to believe in yourself\n"
	.string "and do what's right.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\p"
	.string "STEVEN appears not to be getting\n"
	.string "the call…$"

MatchCall_Text_Steven7::
	.string "STEVEN: {PLAYER}{KUN}… Congratulations\n"
	.string "for entering the HALL OF FAME.\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "I hope we can meet again\n"
	.string "somewhere!$"

MatchCall_Text_BirchRegisterCall:
	.string "PROF. BIRCH: Oh, {PLAYER}{KUN}!\n"
	.string "I've already heard about you!\p"
	.string "It seems your POKéNAV's been\n"
	.string "upgraded with MATCH CALL.\p"
	.string "Well, I should register, too!\p"
	.string "That way, I'd be able to examine\n"
	.string "your POKéDEX even while you're\l"
	.string "out in the field.\p"
	.string "… … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "Registered PROF. BIRCH\n"
	.string "in the POKéNAV.$"

MatchCall_Text_UnusedProfBirch:
	.string "PROF. BIRCH: When one has both\n"
	.string "the POKéDEX and POKéNAV, studying\l"
	.string "POKéMON becomes more fun, eh?$"

MatchCall_Text_MrStone1::
	.string "MR. STONE: Oh? {PLAYER}{KUN}!\p"
	.string "Since you called me, the POKéNAV\n"
	.string "must be working properly!\p"
	.string "Other people will be registered,\n"
	.string "so try calling them up, too!\p"
	.string "Good! Good!\n"
	.string "You seem to be quite happy!\p"
	.string "Hm…\n"
	.string "How could I know that?\p"
	.string "It's because I'm looking down at\n"
	.string "you from my office window!\p"
	.string "Wahahaha!\n"
	.string "See you again!$"

MatchCall_Text_MrStone2::
	.string "MR. STONE: Oh? {PLAYER}{KUN}!\p"
	.string "What's wrong? Have you forgotten\n"
	.string "about that little errand of mine?\p"
	.string "I need you to deliver my letter\n"
	.string "to STEVEN in DEWFORD.\p"
	.string "After that, deliver our parcel to\n"
	.string "CAPT. STERN in SLATEPORT.\p"
	.string "You remember, don't you?\p"
	.string "Now, since I am a busy PRESIDENT,\n"
	.string "I have to go! Bye-bye!$"

MatchCall_Text_MrStone3::
	.string "MR. STONE: Oh! {PLAYER}{KUN}!\p"
	.string "Ah, so you've met STEVEN!\n"
	.string "I'd better reward you, then!\p"
	.string "When you visit RUSTBORO again,\n"
	.string "come see me at my office.\p"
	.string "I'll be waiting for you!$"

MatchCall_Text_MrStone4::
	.string "MR. STONE: Oh! {PLAYER}{KUN}!\p"
	.string "Did you know that DEVON was\n"
	.string "digging the RUSTURF TUNNEL?\p"
	.string "But we shut down the operation to\n"
	.string "protect the POKéMON in the area.\p"
	.string "It's a no-brainer, really.\p"
	.string "It's more important to let POKéMON\n"
	.string "live in peace than worry about our\l"
	.string "own convenience.$"

MatchCall_Text_MrStone5::
	.string "MR. STONE: Hello, hello, {PLAYER}{KUN}!\p"
	.string "I heard from someone in PETALBURG\n"
	.string "that you're NORMAN's child!\p"
	.string "No wonder you're such a capable\n"
	.string "being!$"

MatchCall_Text_MrStone6::
	.string "MR. STONE: What's that?\p"
	.string "You battled your own father and\n"
	.string "defeated him?\p"
	.string "That's astounding!\p"
	.string "I had no idea that I befriended\n"
	.string "someone so special! Wahaha!$"

MatchCall_Text_MrStone7::
	.string "Hello!\n"
	.string "This is DEVON CORPORATI…\l"
	.string "Oh, hello, {PLAYER}!\p"
	.string "Our PRESIDENT was here a little\n"
	.string "while ago, but he's gone out.\p"
	.string "Our PRESIDENT is busy, but you\n"
	.string "seem to be just as busy, {PLAYER}.$"

MatchCall_Text_MrStone8::
	.string "…Huh? …What's that?\p"
	.string "GROU… Yes? …DON?\p"
	.string "You're breaking up…\n"
	.string "…can't hear…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone9::
	.string "…Huh? …What's that?\p"
	.string "Seaflo… Yes? …Caver…?\p"
	.string "You're breaking up…\n"
	.string "…can't hear…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone10::
	.string "MR. STONE: {PLAYER}{KUN}! It's me!\p"
	.string "You were apparently involved in all\n"
	.string "sorts of things, but I, being busy,\l"
	.string "haven't a clue exactly what!\p"
	.string "However, I urge you to take\n"
	.string "the road you believe in and walk it.\p"
	.string "I'll always be in your corner!\n"
	.string "Take care!$"

MatchCall_Text_MrStone11::
	.string "MR. STONE: … … … … … …\n"
	.string "Is this maybe {PLAYER}{KUN}?\p"
	.string "Your voice is so full of confidence,\n"
	.string "I didn't recognize you right off!\p"
	.string "Hm! You must come visit us at DEVON\n"
	.string "sometime!$"
