MatchCall_WildBattleText1::
	.string "{JPN}やあ! {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}だよ。\pさっき {STR_VAR_2}を みかけたんだけど\nつかまえられなかったんだ。\pおしかったのになあ!\nじゃあ また ね!$"

MatchCall_WildBattleText2::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\pさっき いい {STR_VAR_2}を\nつかまえようと したの。\pでも にげられちゃって。\nがっかりしたわ!\pじゃあ またね!$"

MatchCall_WildBattleText3::
	.string "{JPN}よお {PLAYER}!\nおれだ {STR_VAR_1}だ。\pさっき {STR_VAR_2}を つかまえようと\nしたんだが にげられた。\pおしかったんだがなあ!\pきぶんが だいなしだよ…\nそれじゃ またな!$"

MatchCall_WildBattleText4::
	.string "{JPN}やあ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\p{STR_VAR_2}って ポケモンを しって るか?\nもう すこしで つかまえられたんだ。\pついさっきの ことさ。\nいけると おもったのに にげられた。\pこんど みかけたら かならず\nつかまえて みせるよ。\pそれじゃ またな。$"

MatchCall_WildBattleText5::
	.string "{JPN}やあ {PLAYER}{KUN}!\n{STR_VAR_1}よ。\lさいきん ポケモン つかまえて る?\pさっき もうすこしで つかまえられたのに\nにげられちゃったの。\pそれじゃ きを つけてね!$"

MatchCall_WildBattleText6::
	.string "{JPN}やあ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\lさいきん ポケモンは つかまえたか?\pこの あいだ もうすこしで\nつかまえられたのに にげられたよ。\pきを つけてな。$"

MatchCall_WildBattleText7::
	.string "{JPN}…あの {PLAYER}{KUN}?\nわたし {STR_VAR_1}です。\pあっ まって! まって!\nこの {STR_VAR_2}が つかまえられそう…\pああっ! にげられた!\nおしいなんて ものじゃ ないわ!$"

MatchCall_WildBattleText8::
	.string "{JPN}おや {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。\pさいきん ポケモンは うまく\nつかまえられて いますか?\pさきほど おしい ところまで\nいったのですが にげられました。\pもっと がんばらなければ!\nでは また!$"

MatchCall_WildBattleText9::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}よ!\pどう? ポケモンは あつまって\nる?\pわたしは さんざん! みんな\nにげられちゃうの!\pじゃあね!$"

MatchCall_WildBattleText10::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは…\n{STR_VAR_1}です。\pあのね もうすこしで {STR_VAR_2}を\nつかまえられそうだったの…\pでも にげられて しまって…\pもっと がんばらないと。\nそれじゃ また。$"

MatchCall_WildBattleText11::
	.string "{JPN}ああ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\lちょうしは どうかね?\pさっき やせいの {STR_VAR_2}を\nつかまえようと したが にげられた。\pなさけない ものだ…$"

MatchCall_WildBattleText12::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\lまだ ポケモンを つかまえて いますか?\pわたしも つかまえようと して いますが\nなかなか むずかしい ものですね。\pポケモンの みちは おくが ふかい!$"

MatchCall_WildBattleText13::
	.string "{JPN}ああ こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\lポケモンは つかまえて いますか?\pわたしも つかまえようと して いますが\nうまく いきません。\pポケモンの みちは おくが ふかい!$"

MatchCall_WildBattleText14::
	.string "{JPN}あら {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。\pいま かわいい {STR_VAR_2}を\nつかまえようと したの。\pでも にげられちゃった!\nがっかりしたわ!\pバイバイ!$"

MatchCall_WildBattleText15::
	.string "{JPN}よお {PLAYER}!\n{STR_VAR_1}だぜ!\pポケモンを つかまえて みようかと\nおもって いたんだ。\pだが みつからなくてな。\nさっぱり わからん!\pおてあげだよ!\nそれじゃ またな!$"

MatchCall_NegativeBattleText1::
	.string "{JPN}やあ! {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}だよ。\pほかの トレーナーと しょうぶ したけど\nまけちゃった。\pすごく くやしかったよ。\nじゃあ また ね!$"

MatchCall_NegativeBattleText2::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\pあなたと しょうぶした あと\nべつの ひとに いどんだの。\pおしかったけど まけちゃった。\nしかたないわね!$"

MatchCall_NegativeBattleText3::
	.string "{JPN}よお {PLAYER}!\nおれだ {STR_VAR_1}だ。\pしょうぶで こてんぱんに やられたよ。\pもっと てもちを きたえないと\nだめみたいだ!$"

MatchCall_NegativeBattleText4::
	.string "{JPN}よお {PLAYER}。\n{STR_VAR_1}だ。\pきのう また しょうぶ したんだが\nかちきれなかった。\pもっと きたえないとな。\nそれじゃ またな。$"

MatchCall_NegativeBattleText5::
	.string "{JPN}やあ {PLAYER}!\n{STR_VAR_1}よ。\pちょうしは どう?\pしょうぶは つづけて いるけど\nあまり かてて いないの。\pどうも ちょうしが でないわ。\nそれじゃ きを つけてね!$"

MatchCall_NegativeBattleText6::
	.string "{JPN}よお {PLAYER}。\n{STR_VAR_1}だ。\pちょうしは どうだ?\pさいきん しょうぶを つづけて いるが\nあまり かてて いない。\pどうも ノれないんだ。\nきを つけてな。$"

MatchCall_NegativeBattleText7::
	.string "{JPN}{STR_VAR_1}だ。\nさいきん どうだ?\pきのう しょうぶに まけて\nずっと その ことを かんがえて いる。\pさくせんを ねりなおさないと…\nそれじゃ。$"

MatchCall_NegativeBattleText8::
	.string "{JPN}あら {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。\pポケモンは げんきですか?\nわたしは このあいだ まけました。\pもっと がんばらないと!\nでは また!$"

MatchCall_NegativeBattleText9::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}よ!\pねえ ねえ\nきいて!\pさっき ポケモンの しょうぶを したけど さいごの\nさいごで まけちゃったの。\pああ くやしい!$"

MatchCall_NegativeBattleText10::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは…\n{STR_VAR_1}です。\pすこし まえに しょうぶを しました。\nまけて しまいましたけど。\pもっと ポケモンを そだてないと。\nそれじゃ また。$"

MatchCall_NegativeBattleText11::
	.string "{JPN}ああ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\lポケモンは げんきかね?\pまた しょうぶに まけて しまったよ。\pでは また!$"

MatchCall_NegativeBattleText12::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\lしょうぶは がんばって いますか?\pわたしは このあいだ まけたので\nてもちを きたえなおして います。\pまた あいましょう。$"

MatchCall_NegativeBattleText13::
	.string "{JPN}ああ こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\pげんきに して いますか。\pついさっき しょうぶを して\nきたところです。\p{PLAYER}{KUN}も わたしのように\nげんきに いきましょう。 では また!$"

MatchCall_NegativeBattleText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\pげんきに して る?\pたまには いえにも\nかえりなさいね。\pバイバイ!$"

MatchCall_PositiveBattleText1::
	.string "{JPN}やあ! {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}だよ!\pさっき トレーナーと しょうぶ して\nかったんだ! かったよ!\pうちの {STR_VAR_2}が すごく\nがんばって くれた。 さいこうだ!$"

MatchCall_PositiveBattleText2::
	.string "{JPN}こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\pきのう しょうぶを して\nかったの! すごいでしょう!$"

MatchCall_PositiveBattleText3::
	.string "{JPN}よお {PLAYER}!\nおれだ {STR_VAR_1}だ!\lしょうぶは どうだ?\pこの あいだ しょうぶ してな\nうちの {STR_VAR_2}が おおかつやくだ!\pつぎに {PLAYER}と やる ときは\nまける きは ないぞ!$"

MatchCall_PositiveBattleText4::
	.string "{JPN}よお {PLAYER}。\n{STR_VAR_1}だ。\pさっき しょうぶが あってな。\nきわどかったが かてたよ。\pうちの {STR_VAR_2}が\nみごとな はたらきを した。$"

MatchCall_PositiveBattleText5::
	.string "{JPN}やあ {PLAYER}{KUN}!\n{STR_VAR_1}よ。\pちょうしは どう? しょうぶ\nしてる?\pさっき かったところよ! うちの {STR_VAR_2}が\nみごとだったの!\pみてなさい つぎは あなたに かつわ! それじゃ\nきを つけてね!$"

MatchCall_PositiveBattleText6::
	.string "{JPN}よお {PLAYER}{KUN}。\n{STR_VAR_1}だ。\pちょうしは どうだ?\pおれは ちょうしが いいぞ。\nさっきも しょうぶに かった。\pこんど おまえと やる ときは\nぜったいに まけないからな!$"

MatchCall_PositiveBattleText7::
	.string "{JPN}{PLAYER}{KUN}?\n{STR_VAR_1}だ。\pうちの {STR_VAR_2}は たいした ものだ!\nさっきも しょうぶに かたせて くれた!\pまた きみと しょうぶ するのが\nたのしみだよ。$"

MatchCall_PositiveBattleText8::
	.string "{JPN}あら {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。\pおげんきで なによりです。\nさっき しょうぶに かちました。\pうちの {STR_VAR_2}が とくに\nがんばって くれたのです。\pでは また!$"

MatchCall_PositiveBattleText9::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}よ!\pポケモンは げんき?\nうちの こは しょうぶに かったの!\pうちの {STR_VAR_2}が それはもう\nみごとだったのよ!\pみせて あげたかったわ!\nそれじゃ また!$"

MatchCall_PositiveBattleText10::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは…\n{STR_VAR_1}です。\pさいきん いかがですか?\pうちの ポケモンは ちからが\nみなぎって いるようです。\pさっき しょうぶに かちました。\nそれじゃ また。$"

MatchCall_PositiveBattleText11::
	.string "{JPN}ああ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\pさいきん しょうぶは して いるか?\nわしは きょうも かったぞ!\pのって おるわ! がはははは!\nでは また!$"

MatchCall_PositiveBattleText12::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\pおげんきでしたか?\nわたしは まだまだ げんきですよ!\pついさっきも しょうぶに かちました。\nわかい ひとに ゆずる きは\lまだ ありません!$"

MatchCall_PositiveBattleText13::
	.string "{JPN}ああ こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\pおげんきで なによりです。\nわたしも まだまだ げんきです!\pついさっきも また しょうぶに かちました。\nわかい ひとには まだまだ\lまけませんよ!\pでは また!$"

MatchCall_PositiveBattleText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\pこの あいだ しょうぶを して\nうちの {STR_VAR_2}が みごとでした!\p{PLAYER}{KUN}にも みせたかったわ。\nバイバイ!$"

MatchCall_SameRouteBattleRequestText1::
	.string "{JPN}やあ! {PLAYER} こんにちは!\n{STR_VAR_1}だよ。\pえ? いま {STR_VAR_2}の\nちかくに いるの?\pそれなら しょうぶ しよう!\nまって るよ! それじゃ!$"

MatchCall_SameRouteBattleRequestText2::
	.string "{JPN}こんにちは {PLAYER}!\n{STR_VAR_1}です。\pあら? いま {STR_VAR_2}の\nあたりに いるの?\pいま しょうぶ しませんか?\nまって います! それじゃ!$"

MatchCall_SameRouteBattleRequestText3::
	.string "{JPN}よお {PLAYER}! おれだ\n{STR_VAR_1}だ。\pおい いま {STR_VAR_2}の ちかくに\nいるのか?\pいま おれと しょうぶ\nしないか?\pもう まけないぞ! まって るからな!\nまたな!$"

MatchCall_SameRouteBattleRequestText4::
	.string "{JPN}よお {PLAYER}{KUN}。\n{STR_VAR_1}だ。\pいま どこに いる?\nえ? {STR_VAR_2}?\pいま しょうぶ しないか?\nまって るぞ。 それじゃ!$"

MatchCall_SameRouteBattleRequestText5::
	.string "{JPN}やあ {PLAYER}{KUN}!\n{STR_VAR_1}よ。\lちょうしは どう?\pいま どこに いるの?\n{STR_VAR_2}?\pそれなら いますぐ もういちど\nしょうぶ しない?\pさがして るわね。\nまた すぐに!$"

MatchCall_SameRouteBattleRequestText6::
	.string "{JPN}よお {PLAYER}{KUN}。\n{STR_VAR_1}だ。\lポケモンは げんきか?\pほう そうなのか? {STR_VAR_2}の\nあたりに いるのか?\pそれなら もういちど\nしょうぶ しないとな。\pまって るぞ。\nそれじゃ!$"

MatchCall_SameRouteBattleRequestText7::
	.string "{JPN}…あの {PLAYER}{KUN}?\n{STR_VAR_1}です…\pあら {STR_VAR_2}の あたりに\nいるのですか?\pそれなら しょうぶ しましょう。\nいますぐ。\pわたしの ポケモンを みせて あげます。\nまって います。$"

MatchCall_SameRouteBattleRequestText8::
	.string "{JPN}あら {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。\pおげんきで なによりです。\nあら {STR_VAR_2}の ちかくですね。\pそれなら わたしと しょうぶを\nしませんか?\pまって います。\nでは また すぐに!$"

MatchCall_SameRouteBattleRequestText9::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}よ!\pがんばって る?\nあら {STR_VAR_2}の ちかく?\pそれなら しょうぶ するしか\nないと おもわない?\pあまり またせないでね!$"

MatchCall_SameRouteBattleRequestText10::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは…\n{STR_VAR_1}です。\pちょうしは いかがですか?\nあら {STR_VAR_2}の ちかくですね。\pそれなら いま しょうぶ しましょう。\pじゅんびして まって います。\nはやく きてね!$"

MatchCall_SameRouteBattleRequestText11::
	.string "{JPN}ああ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\pほう いま いる ところは\n{STR_VAR_2}か?\pそれなら しょうぶを するしか\nないと おもわないか?\pまって いるぞ!\nすぐに あおう!$"

MatchCall_SameRouteBattleRequestText12::
	.string "{JPN}こんにちは {PLAYER}{KUN}。 {STR_VAR_1}です。\nいま どこに\lいますか?\p{STR_VAR_2}? ずいぶん\nちかいですね!\pいま しょうぶを\nしませんか?\pまって いますよ。\nそれじゃ!$"

MatchCall_SameRouteBattleRequestText13::
	.string "{JPN}ああ こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\pおげんきで なによりです。\nあら {STR_VAR_2}の ちかくですか?\pそれほど とおくないので\nしょうぶに きて ください。\pまって います。\nでは また。$"

MatchCall_SameRouteBattleRequestText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\pいま どこ? …{STR_VAR_2}?\nとても ちかいわね。\pそれなら しょうぶ するべきだと\nおもわない?\pさがして るわね!\nバイバイ!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "{JPN}やあ! {PLAYER} こんにちは!\n{STR_VAR_1}だよ。\pぼくと しょうぶ しないかい?\p{STR_VAR_2}の あたりで\nまって るよ!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "{JPN}こんにちは {PLAYER}!\n{STR_VAR_1}です。\pまた わたしと しょうぶ\nしませんか?\p{STR_VAR_2}の あたりに います。\nまって いますね!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "{JPN}よお {PLAYER}!\nおれだ {STR_VAR_1}だ。\pまえより ポケモンが ずいぶん\nつよく なったんだ。\pどれくらい つよく なったか\n{PLAYER}の ポケモンで ためしたい。\pだから しょうぶ しよう!\p{STR_VAR_2}の あたりで\nまって るからな。$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "{JPN}よお {PLAYER}{KUN}。\n{STR_VAR_1}だ。\lちょうしは どうだ?\pさいきん ポケモンが かなり\nつよく なってな。\pなあ また おれと しょうぶ\nしないか?\p{STR_VAR_2}の あたりで\nあおうじゃないか。$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "{JPN}やあ {PLAYER}{KUN}!\n{STR_VAR_1}よ。\pうちの ポケモンは いい かんじに\nそだって いるの。\pぜひ また あなたと しょうぶ\nしたいわ。\p{STR_VAR_2}の あたりで\nさがして るわね。 また すぐに!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "{JPN}よお {PLAYER}{KUN}。\n{STR_VAR_1}だ。\lうまく やって いるか?\pまた きみと しょうぶ したいと\nおもって いたんだ。 どうだ?\pその きが あるなら\n{STR_VAR_2}に きて くれ。\pそれじゃ!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "{JPN}…あの {PLAYER}{KUN}?\n{STR_VAR_1}です…\lポケモンは そだって いますか?\pうちの こは つよく なりました。\nみせて あげたいです。\p{STR_VAR_2}の あたりに います。\nしょうぶに きて ください。\pそれじゃ また。$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "{JPN}あら {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。\pおげんきで なによりです。\nうちの ポケモンは げんきいっぱい。\pこの あたりに きたら ぜひ\nもういちど しょうぶを。\p{STR_VAR_2}の あたりに います。\nそれでは また!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}よ!\lポケモンは げんき?\pうちの ポケモンは どんどん よく\nなって いるの。 {PLAYER}{KUN}に みせたいわ。\pいまは {STR_VAR_2}の あたりに\nいるから ちかければ しょうぶ しましょう。\pまって るわね!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは…\n{STR_VAR_1}です。\lちょうしは いかがですか?\pうちの ポケモンは まえより\nずっと つよく なりました。\pぜひ また {PLAYER}{KUN}と\nしょうぶ したいです。\p{STR_VAR_2}の あたりに います。\nちかければ きて ください。$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "{JPN}ああ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\lいま どこに いる?\pうちの ポケモンは げんきいっぱいだ。\n{PLAYER}{KUN}の ポケモンに あうのを\lたのしみに して いるようだ。\pいまは {STR_VAR_2}の あたりに いる。\nさがしに きて くれると うれしい。$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\pうちの ポケモンは さいきん\nずいぶん たくましく なりました。\p{PLAYER}{KUN}との しょうぶで\nその すがたを みたいのです。\p{STR_VAR_2}の あたりに います。\nいつでも きて ください!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "{JPN}ああ こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\lポケモンは げんきですか?\pうちの ポケモンは とても げんきで\nまける きが しません!\pぜひ また しょうぶを\nして みたいのです。\p{STR_VAR_2}の ちかくなら\nきて ください。$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\lおげんきですか。\pそうそう! うちの ポケモンは\nまえより ずっと つよいのよ。\p{PLAYER}{KUN} しょうぶ するべきだと\nおもわない?\p{STR_VAR_2}の あたりで\nまって いるわ。\pいつでも きてね?$"

MatchCall_PersonalizedText1::
	.string "{JPN}やまずきの\n{STR_VAR_1}だ!\pあれから やまの よさが わかって\nきたかね?\pやまでは あまり きみを みかけないな…\pこんどは {STR_VAR_2}の あたりで\nあおうじゃないか。$"

MatchCall_PersonalizedText2::
	.string "{JPN}{STR_VAR_1}です。\nこんにちは。\pあたらしい トレーナーに\nあなたの ことを はなして いました。\pポケモンを たいせつに そだてる\nつよい トレーナーが いると。\pみんなに あこがれられる トレーナーに\nなって くださいね。\pまた あいましょう!$"

MatchCall_PersonalizedText3::
	.string "{JPN}こんにちは! {STR_VAR_1}です。\pいまいる ところが だいすきなの。\nあまい かおりで こころちよいわ!\pだれかが きのみを うえたようで\nいっせいに はなが さいたの。\pまた いつか!$"

MatchCall_PersonalizedText4::
	.string "{JPN}こんにちは! たんけん 30ねん\n{STR_VAR_1}だ!\pきみは あちこちを げんきに\nたびして いるようだな。\pあたらしい いせきは みつけたかね?\nみつけたら おしえて くれたまえ!\pでは しつれい するよ。\nいせきの たんけんが あるのでね。$"

MatchCall_PersonalizedText5::
	.string "{JPN}{STR_VAR_1}よ!\pきょう なにを して いると おもう?\nはまべで なみを ながめて いるの!\pはあ… なみが きらきらして るわ。\nうみは ここから みるのが いちばん きれい。\lおなかが すいたから バイバイ!$"

MatchCall_PersonalizedText6::
	.string "{JPN}もぐもぐ…\nあら {STR_VAR_1}よ。\lはまべで たべるのが すきなの。\pポケモンも わたしも げんきよ。\nエネルギー まんタン!\lおよいで くるわね バイバイ!$"

MatchCall_PersonalizedText7::
	.string "{JPN}こんにちは {STR_VAR_1}です…\pエリートトレーナーと いうのに すこし つかれて\nしまって…\pみんな わたしを かんぺきな トレーナーだと\nおもうから それに こたえようと\lしてしまうの。\pでも それが エリートトレーナーと いう\nものよね。\pはらを くくって… がまん するしか\nないわ。\pこんな はなしが できるのは\nあなただけよ。\pつぎに あう ときは\nわすれてね。$"

MatchCall_PersonalizedText8::
	.string "{JPN}ヤッホー {STR_VAR_1}よ!\nごきげん いかが?\pあなたを めざして ポケモンを\nそだてて いるの。\pつぎに しょうぶする ときは\nまける つもりは ないわ。\pトレーナーの ともだちって いいわね!\nまた あいましょう!$"

MatchCall_PersonalizedText9::
	.string "{JPN}{STR_VAR_1}です…\nいま あなたの うしろに…\lなにか いませんでしたか…?\pおくりびやまに ねむる ポケモンの\nちからが…\pあなたの ことを おしえて くれるの…\pはやく そこを はなれて\nいちども ふりかえらない ことね…\pうふふ…\nさようなら…$"

MatchCall_PersonalizedText10::
	.string "{JPN}{STR_VAR_1}です。\nごきげんよう。\pこうして はなれて いても はなせるのは\nべんりですわね?\pむかしは だれかと はなすのに\nパパに くるまを だして もらわないと\lいけませんでしたの…\pそろそろ しつれい しますわ。\nおはなし できて うれしかった。$"

MatchCall_PersonalizedText11::
	.string "{JPN}{STR_VAR_1}よ! きいて\nくれる?\pサファリゾーンが だいすきなんだけど いくと\nかならず まいごに なるの!\pくさむらだらけだし\nひろすぎるのよ!\pはなしたら\nすっきりしたわ!\pまた サファリゾーンに いってくるね!\nそれじゃ!$"

MatchCall_PersonalizedText12::
	.string "{JPN}こんにちは {STR_VAR_1}です。 ええ そうです わたしは\nかねもち。\pいって おきますが まえに あったときより\nざいさんが ふえましたのよ。\pさらに ポケモンも つよく\nなりました。\pこの よは わたしの ために あるような きが して\nなりません!\pああ なにも いわなくて けっこう! みんな しって\nいる ことですもの!\pでは しつれい しますわ。 しょくじかいが\nありますの。$"

MatchCall_PersonalizedText13::
	.string "{JPN}うふふふふ…\nわたしよ {STR_VAR_1}…\pいま なにを みて いると おもう?\n{STR_VAR_2}が 2ひきで しょうぶ してるの。\pかった ほうを つかまえようかしら…\nうふふふふ…\pわ わたし いま すこし いそがしいの。\nきらないと。$"

MatchCall_PersonalizedText14::
	.string "{JPN}おや {STR_VAR_1}だ!\pすてられぶねにも あきてきたなと おもって いた\nところさ。\pだが せっかく ここに いるんだし いちどは\nきみに かちたいから もうすこし いる ことに\lするよ。\pその きに なったら あいに きて\nくれないか?\pきょうこそ となりの おとこに\nしょうぶを いどんで みる\lつもりだ。\pそれじゃ また!$"

MatchCall_PersonalizedText15::
	.string "{JPN}おれは {STR_VAR_1}!\nうみの おとこだ!\pなにを おもうか わかるか?\pうみに でる トレーナーこそ\nいちばん てごわいのさ!\pきみも おれを みならって\nうみで きたえると いい…\pおっと おおなみが きた!\pれんしゅうには もってこいだ!\nわるいが きるぞ!$"

MatchCall_PersonalizedText16::
	.string "{JPN}{STR_VAR_1}だ! きいてくれ ポケモンに からてを おしえて\nいたんだ。\pだが いまでは おれより つよくてな!\nまけてばかりだ!\pポケモンには まけても\nほかの トレーナーには\lまけないぞ!\pまた しょうぶ しようじゃないか!\nうおおお!$"

MatchCall_PersonalizedText17::
	.string "{JPN}おれだ {STR_VAR_1}だ。\nたびの ちょうしは どうだい?\p…おっと そうなのか?\nずいぶん しげきてきだな!\pきみの できごとを きょくに\nできそうだよ。\p…おっ きた。\nあたまの なかで リフが なって いる。\pちゃんと かきとめないと いけない。\nいくぞ! またな!$"

MatchCall_PersonalizedText18::
	.string "{JPN}{STR_VAR_1}だ…\nあたらしい きょくを きいて くれ。\pラララ {STR_VAR_2} {STR_VAR_2}!\nなぜ きみは {STR_VAR_2}なんだ?\lなぜ おれは {STR_VAR_2}に なれない?\lララ {STR_VAR_2}と {STR_VAR_1}\l{STR_VAR_1}と {STR_VAR_2}…\pくりかえして フェードアウト…$"

MatchCall_PersonalizedText19::
	.string "{JPN}キャンプの めいじん\n{STR_VAR_1}だ!\pしょうぶの ときは きみに まける しか\nなかったな。\pなにしろ おれの とくいは\nキャンプだからな。\pだが かっても まけても キャンプでの しょうぶは\nたのしい。\pまた しょうぶ しような? それと キャンプにも\nいこう!$"

MatchCall_PersonalizedText20::
	.string "{JPN}おれ おれ {STR_VAR_1}だ!\pしょうじきに いうと ほかの やまにも\nのぼって みたいんだ。\pでも えんとつやまの ような\nおじょうさんが いるかは わからないな。\pほかに おじょうさんの いる やまを\nしって いたら おしえて くれ!\pえへへ またな!$"

MatchCall_PersonalizedText21::
	.string "{JPN}… … … … … …\n… … … … … …\l{STR_VAR_1}です…\p… … … … … …\n… … … … … …\lきょうは これだけ…$"

MatchCall_PersonalizedText22::
	.string "{JPN}{STR_VAR_1}だ。 きょうは きみと\nはなす きが したんだ。\pきみを たおしたいと いう おもいは\nひごとに つよく なる。\pきみにも そんな ライバルが いるだろう?\nそれが おれだと いいのだが…\pきいて くれて ありがとう。\nまたな!$"

MatchCall_PersonalizedText23::
	.string "{JPN}{STR_VAR_1}だ。\pちかくに つよい トレーナーが いると\nなんとなく かんじる ことが\lあるんだ。\p{PLAYER}{KUN} ちかくを とおったか? きみ だったのかも\nしれないな。\pきみが くるのを まって いる。\nそれじゃ!$"

MatchCall_PersonalizedText24::
	.string "{JPN}こんにちは {STR_VAR_1}です。\nおげんきそうですね {PLAYER}{KUN}。\pせかいじゅうを たびして きましたが\nこの ちほうが すっかり きに\lいって しまいました。\pしばらく ここに いる つもりです。\nまた あえますか?\pあなたの みごとな わざは\nわすれて いません。\pぜひ もういちど しょうぶを。$"

MatchCall_PersonalizedText25::
	.string "{JPN}ぐすん… {STR_VAR_1}です…\n…ぐすっ…\pきょう じゅぎょうで ツツジせんせいに\nしかられちゃった。\pでも きらいじゃ ないんだ。\pツツジせんせいは どこが だめだったか\nちゃんと おしえて くれるから。\pあしたも トレーナーズスクールに\nいくよ!\pそれじゃ また!$"

MatchCall_PersonalizedText26::
	.string "{JPN}{STR_VAR_1}だよ!\pきのう ツツジせんせいが しょうぶを して\nくれたんだ。\pけっかは… きくまでも なく\nさんざんだったよ。\pでも ツツジせんせいが しょうぶを うけて くれた\nことが うれしかった!\pますます\nあこがれちゃった!\pしっかり がんばるよ! それじゃ\nまた!$"

MatchCall_PersonalizedText27::
	.string "{JPN}アンナよ! きょうも こうはいの メグと\nいっしょ。\pメグと ポケモンの せわを するのが だいすきなの。\nかわいいのよ!\pきょうだいの ように せわが できたら\nいいのに!\pあら メグ! パンは かって\nきた?\pえ? ちがう ちがう! こきつかって なんて\nいないわ!\pしょうぶに まけたんだから ばつとして パンを\nかって くるのよ!\pこきつかって なんて いないでしょう メグ?\nあなたは たいせつな こうはいよ!\pそれじゃ また\nね!$"

MatchCall_PersonalizedText28::
	.string "{JPN}ポケモンが だいすき!\nファンクラブの {STR_VAR_1}です!\pきいて ください!\nうちの かわいい ポケモンが…\pふふっ わははは!\nこれいじょうは いえません! ひみつです!\lかわいすぎて ことばに なりません!\pあら うちの {STR_VAR_2}が\n{POKEBLOCK}を ねだって います!\pかわいさの きわみです!\pすみませんが いまは はなせません!\nまた こんど!$"

MatchCall_PersonalizedText29::
	.string "{JPN}おほほ!\p{STR_VAR_1}です! かわいい ポケモンの\nはなしを させて ください!\pぜひ きいて ください。\nうちの {STR_VAR_2}の ことです。\pだれかが だきあげると まっすぐ\nわたしの うでに とんで くるの!\pああ… ああ… これほどの\nしあわせが あるかしら?\pもう てんごくの きぶんですわ!\pこの しあわせを すこし わけられて\nうれしかった ですわ。\pそれでは しつれい します。\nまた ね!$"

MatchCall_PersonalizedText30::
	.string "{JPN}わたしは… {STR_VAR_1}。\nひとは わたしを たつじんと よぶ。\pだが ひとつ わかって いる ことが ある。\nわたし ひとりの ちからでは\lたつじんには なれなかった。\pポケモンの たすけが あってこそ\nトレーナーは たつじんに なれるのだ。\pふむ! いま なかなか ふかい ことを\nいった きが するぞ!\pよい きぶんで しつれい しよう!$"

MatchCall_PersonalizedText31::
	.string "{JPN}{STR_VAR_1}じゃ。\nはなせて うれしいのう!\pおんせんに つかって からだが\nいきかえるようじゃ。\pあれから わかい トレーナーと\nしょうぶを して おるが きみが\lいまでも いちばん つよいのう。\pきみも としを とれば たつじんに\nなるじゃろう! ほっほっほ…$"

MatchCall_PersonalizedText32::
	.string "{JPN}やった! {STR_VAR_1}だよ!\nどうしてる?\pきの せいかも しれないけど しょうぶに\nかつと はんズボンの はきごこちが\lよく なる きが するんだ。\pどういう ことかって?\nうまく いえないんだけど…\lなんて いうかな…\lはんズボンが すべすべに なるんだ!\p{PLAYER}{KUN}と しょうぶ した ときは\nはんズボンが ざらざら して いたよ。\p… … … … … …\nいまのを ほんきに した?\lえへへ それだけ! またね!$"

MatchCall_PersonalizedText33::
	.string "{JPN}よお!\n{STR_VAR_1}だ!\pあいかわらず むちゅうで\nつりを して いるぜ!\pうみや かわ いがいにも\nつりが できる ところは あるのか?\pどこでも つりたく なる ときが\nあるんだよなあ!\pおっと しまった!\nいとが からまった!\pきるぞ!\nあたらしい つりばを さがして おいて くれ!$"

MatchCall_PersonalizedText34::
	.string "{JPN}やあ! {STR_VAR_1}だ。 のんびり やって\nるかい?\pこどもの ころから おれは ずっと\nのんびりやでね。\pあせったり いそいだり するのは どうも\nにがてだった。\pそれが どういう わけか いまでは\nトライアスリートさ。\pじんせいは どこへ ころがるか わからない\nものだな。\pきみも いまは トレーナーだが さきの ことは\nわからないぞ?\pせんせいに なった じぶんを そうぞう して\nみるのも おもしろい。\pそれじゃ\nまたな!$"

MatchCall_PersonalizedText35::
	.string "{JPN}{STR_VAR_1}だ!\nいま じてんしゃに のって いる。\pすいえいも ランニングも すきだが\nじてんしゃが いちばん すきなんだ!\pぜんしんが かぜと ひとつに\nなった ような きぶんに なる。\pそらを とんで いるみたいで\nたまらないんだ!\pよし きょうこそ じてんしゃロードの\nきろくを こうしんするぞ!\pきみも ちょうせん して みろよ!\nまたな!$"

MatchCall_PersonalizedText36::
	.string "{JPN}よお {STR_VAR_1}だ! いま トライアスロンの\nまっさいちゅうだ!\pだが おしゃべりの じかんは\nいつでも あるぜ!\pポケモンと からだを うごかすのは\nじつに きもちが いい!\pことばを かわさなくても こころが\nひとつに なった ように そろうんだ。\pしびれるぜ!\pはあ… はしりながら はなして いたら…\nばてて きたな…\lはあ… はあ…$"

MatchCall_PersonalizedText37::
	.string "{JPN}やあ {STR_VAR_1}だ。\nもちりょくを つけたいなら\lこうちで きたえるに かぎる!\pやまの うえで はしって みろ。\nすぐに いきが あがるぞ!\pおれも さんそが たりなく なって きた!\nまたな!$"

MatchCall_PersonalizedText38::
	.string "{JPN}おや {STR_VAR_1}だ こんにちは。\pずいぶん およいで いるのに\nサイユウシティに つかないんだ。\pぐるぐる まわって いるのかな。\pいや いや そんな はずは ない。\nわははは。\lきを つけてな!$"

MatchCall_PersonalizedText39::
	.string "{JPN}よお {STR_VAR_1}だ…\nおっと!\pばしゃっ!\pごぼごぼごぼ…\pざぶーん!\pふうふう! ふうふう!\pおっと わるい わるい! ひやけどめを ぬった\nばかりでな。\pポケナビが てから すべって みずに おちて\nしまったんだ!\pだが デボンの ポケナビは じょうぶだな。 みずに\nおちても へいきだ!\pそれじゃ ひなたぼっこの\nつづきだ!$"

MatchCall_PersonalizedText40::
	.string "{JPN}こんにちは {STR_VAR_1}です。\pトライアスロンの 3しゅもくの なかでは\nすいえいが いちばん すきなの。\pでも うみに ながく つかって いると\nてが しわしわに ならないかしら?\pああ トライアスロンは にんげんの\nがまんの げんかいへの ちょうせんね! それじゃ!$"

MatchCall_PersonalizedText41::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}だ。\pポケモンは げんきかね?\pうちの ドラゴンポケモンは\nちょうしが いいようだ。 それでは。$"

MatchCall_PersonalizedText42::
	.string "{JPN}{STR_VAR_1}だ。\pうちの {STR_VAR_2}は まえより\nずっと つよく なったぞ。\pこんどは まけない。\nつぎを たのしみに して いろ!\pそれじゃ またな!$"

MatchCall_PersonalizedText43::
	.string "{JPN}{STR_VAR_1}で ござる。\pかくれみの わざを みがきつづけて\nおり ました。\pだが うまく いきすぎて だれにも\nみつけて もらえませぬ。\lうまく いくほど さびしい ものよ…\pけむりの ごとく きえまする!\nさらば!$"

MatchCall_PersonalizedText44::
	.string "{JPN}{STR_VAR_1}だ。\nあれから きたえつづけて いる。\pうちの {STR_VAR_2}は かなり\nつよく なって きたぞ。\pはまべでの れんしゅうは やはり\nききめが あるな。 それじゃ!$"

MatchCall_PersonalizedText45::
	.string "{JPN}ごきげんよう。\n{STR_VAR_1}です。\pこの いやな かざんばいは\nいつまで ふるのかしら?\pつもりすぎると ひがさの もようが\nみえなく なって しまうわ…\pまた あう やくそくを しましょう!$"

MatchCall_PersonalizedText46::
	.string "{JPN}やあ {STR_VAR_1}だ。\pプールより うみの ほうが うかびやすいのを\nしって いたかい?\pじっと して いるだけで からだが\nかってに うくんだ。\pただし ながく うかんで いると\nとおくまで ながされるから\lきを つけるんだぞ。\p…ところで ここは どこだ?\nいかないと!$"

MatchCall_PersonalizedText47::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}です。\lいま やまの なかに います。\pでも じめんが でこぼこで\nテントが はれないの…\pあ! いい ことを おもいついた!\pポケモンに じめんを ふみかためて\nもらえば いいんだわ!\pためして みるわね!\nバイバイ!$"

MatchCall_PersonalizedText48::
	.string "{JPN}あ こんにちは {STR_VAR_1}です!\pリブと いっしょに ポケモンを\nそだてて いるの! がんばって るわ!\pもっと がんばれば 1ばんに\nなれるかしら? バイバイ!$"

MatchCall_PersonalizedText49::
	.string "{JPN}{STR_VAR_1}だ!\pふなのりだが いまは ふねに\nのって いない。\pりくに いる ふなのりは なんと\nよべば いいのかな?\pなみを ながめながら そんな ことを\nかんがえて いたんだ。\pそれじゃ また こんど!$"

MatchCall_PersonalizedText50::
	.string "{JPN}{STR_VAR_1}だ。\nどうだ ポケモンは ふえたか?\pあたらしい ポケモンを つかまえたら\nみせに きて くれよ。\pねだったり しないから ほんとうだ。\nまって るぞ。 それじゃ。$"

MatchCall_PersonalizedText51::
	.string "{JPN}{STR_VAR_1}です。\pポケモンを いちばん よい かたちで そだてて\nいますか?\pわたしの いる ところは くうきが\nきれい。 ポケモンを そだてるのに\lぴったりです。\pそだてる ことに うちこむなら\n{STR_VAR_2}に きて ください。 それでは\lまた。$"

MatchCall_PersonalizedText52::
	.string "{JPN}こんにちは {STR_VAR_1}です。\pうちの {STR_VAR_2}に {POKEBLOCK}を\nあげたら とても よろこびました。\pポケモンにも {POKEBLOCK}の すききらいが\nあるようですね。\pとても おもしろいと おもいます。\nそれでは また。$"

MatchCall_PersonalizedText53::
	.string "{JPN}{STR_VAR_1}だ。\pポケモンと ちからを あわせれば\nやせいでも こころよく くらせる。\pみんな それに きづいて もっと\nポケモンと ちからを あわせるべきだ。\pそれが りそうだと\nほんきで おもって いる。\pきみは いい みちを あるいて いるな!\nまたな!$"

MatchCall_PersonalizedText54::
	.string "{JPN}やあ {STR_VAR_1}だ。 いつでも じゅんびばんたんの\nトレーナーさ!\p{PLAYER}{KUN} どうぐは たりて いるか? ポケモンの ちょうしは\nいいか?\pみのまわりを いつも きちんと して\nおくのが たびを つづける\lひけつなんだ。\pおれも じゅんびを たしかめて くる! ゆだんは\nきんもつだぞ!$"

MatchCall_PersonalizedText55::
	.string "{JPN}{STR_VAR_1}よ!\n{STR_VAR_1}よ!\p{STR_VAR_2}は ひとどおりが おおいから\nまいにち いろんな トレーナーに\lしょうぶを いどまれるの。\pきょうは 5かい かって\n3かいしか まけなかったわ!\pあなたは どうだった?\nこんど おしえてね!$"

MatchCall_PersonalizedText56::
	.string "{JPN}おれだ {STR_VAR_1}だ。\pむしポケモンを たくさん もって いるから\nにんきものなんだ そうだろう?\pきょう おきにいりの むしを\nがっこうに もって いったんだ。\pすきな こが ないちゃった!\nわらいたければ わらって くれ。\pむしポケモンの みりょくを\nおしえないと いけないな。\pぐすん…\nそれじゃ!$"

MatchCall_PersonalizedText57::
	.string "{JPN}はあ! はあ! はあ! はあ!\pやあ! {STR_VAR_1}だ! はあ! はあ!\pのぼりながら…\nはなすのは…\lきつい うんどうだ… はあ! はあ!\pうっ ふう…\nきゅうに なって きた…\lはなしは… また こんど…\lはあ! はあ! はあ!$"

MatchCall_PersonalizedText58::
	.string "{JPN}やあ こんにちは!\pキリと いっしょに たからものを\nさがして いるんだ!\pここには なにも ないのかも\nしれないけどね…\pだいじなのは キリと いっしょに\nさがす ことなんだ。\pあっ キリ!\nな なんで おこって るんだ?\pむし して なんか いないよ!\nきみが いちばん たいせつさ!\p…{PLAYER} きるよ またね!$"

MatchCall_PersonalizedText59::
	.string "{JPN}{STR_VAR_1}だ!\pムロタウンの ジムに また\nきたえに いって きたよ。\pジムリーダーの トウキさんは\nまた つよく なった みたいだ。\pあらい なみに きたえられたとか\nなんとか いって いたな…\pだが あいかわらず かっこいい。\nおんなの ひとに もてるんだ!\lうらやましい かぎりだよ。\pなあ… トウキさんの ともだちの\nシバさんも おなじ かんじなのかな?\pあせくさかったり ひとを「おおなみ」と\nよんだり する かんじ なのかな?\lきに なるなあ。\pうーん わからないな。\pともかく また きたえに いくよ。\pそれじゃ また!$"

MatchCall_PersonalizedText60::
	.string "{JPN}きみのような わかい トレーナーと\nはなせるのは うれしい ものじゃ。\pいくつに なっても ポケモンを\nたのしむ ことは できるはずじゃ。\pわしらの ような つながりを\nもてたら すてきだと おもわんかね?\pもっとも {PLAYER}{KUN}は すでに\nポケモンと しんらいで むすばれて\lおるがのう。\pながく つづく きずなの めばえが\nもう そこに あるのじゃ。\pはっはっは!\nくじけては いかんぞ!$"

MatchCall_PersonalizedText61::
	.string "{JPN}やあ {STR_VAR_1}よ! いま しょうぶに\nかったの!\pめったに かてないのに あいては かっこいい\nスイマーの おにいさん。\pおねえちゃんは かんかん!\pよわい ふりを して\nみせたかったんだって!\pかっても まけても わたしを\nしかるのよ!\p{PLAYER}{KUN} こんど なにか いって\nあげて!\pそれじゃ また!$"

MatchCall_PersonalizedText62::
	.string "{JPN}{STR_VAR_1}です はい。 きのう うみへ\nでました。\pあたらしい いせきを みつけたいと\nおもったのです。\pですが しおに ながされて もとの ばしょに\nもどって しまい ました。\pしょうぶも まだ よわいまま… わらって\nくださって けっこう… でも\lあきらめません。\pいつか あたらしい いせきを みつけて\nみせます!\pおはなしは\nこれだけです。$"

MatchCall_PersonalizedText63::
	.string "{JPN}おーい!\nおれだ {STR_VAR_1}だ!\lいま 108ばんすいどうに いる!\lつまり いつもの ばしょだ!\pきょう きれいな スイマーの\nおねえさんが およいで きた!\pだから おおごえで おどろかせた!\pそうしたら すごい めで にらまれた!\p108ばんすいどうから\n{STR_VAR_1}が おとどけ しました!$"

MatchCall_PersonalizedText64::
	.string "{JPN}{STR_VAR_1}だ!\pすこし いそがしいんだが きょうも\nトレーナーを 5にん たおしたと\lつたえて おきたくてな。\pこの ちょうしなら つぎは\nきみにも かてそうだ。\pおれたち いい ライバルに なれそうだな。\nそれじゃ また!$"

MatchCall_BattleFrontierStreakText1::
	.string "{JPN}やあ! {STR_VAR_1}だよ。\nうわさを きいたよ!\p{STR_VAR_2}で すごい せいせきを\nだしたんだって?\pすごいね {STR_VAR_3}れんしょうだって?\nそれじゃ また!$"

MatchCall_BattleFrontierStreakText2::
	.string "{JPN}こんにちは {STR_VAR_1}です!\nうわさを ききました!\p{STR_VAR_2}で {STR_VAR_3}れんしょうを\nしたそうですね。\pすごい! わたしも がんばらないと!\nそれでは!$"

MatchCall_BattleFrontierStreakText3::
	.string "{JPN}よお {PLAYER}! おれだ\n{STR_VAR_1}だ。\p{STR_VAR_2}で\nあばれまわったそうだな!\p{STR_VAR_3}れんしょうか… たいした\nきろくじゃないか。\pおれも しっかり しないとな!\nまたな!$"

MatchCall_BattleFrontierStreakText4::
	.string "{JPN}よお {PLAYER}{KUN}。 {STR_VAR_1}だ。\nどうだ?\p{STR_VAR_2}で {STR_VAR_3}れんしょう したと\nうわさに なって\lいるぞ。\pおれも がんばらないとな。\nそれじゃ!$"

MatchCall_BattleFrontierStreakText5::
	.string "{JPN}やあ {PLAYER}{KUN}!\n{STR_VAR_1}よ。\p{STR_VAR_2}で {STR_VAR_3}れんしょう\nしたの?\lすごいじゃない!\pわたしも もっと ポケモンを そだてないと。 また\nね!$"

MatchCall_BattleFrontierStreakText6::
	.string "{JPN}よお {PLAYER}{KUN}。 {STR_VAR_1}だ。\nげんきか?\pところで {STR_VAR_2}で\n{STR_VAR_3}れんしょう したと\lきいたぞ。\pおれも てもちを そだてる きに\nなったよ。$"

MatchCall_BattleFrontierStreakText7::
	.string "{JPN}…あの {PLAYER}{KUN}?\n{STR_VAR_1}です…\pそうそう {STR_VAR_2}に\nいって いたのですよね?\pそこで {STR_VAR_3}れんしょう したとか。\pあっ めずらしい ポケモンが!\nいかないと!$"

MatchCall_BattleFrontierStreakText8::
	.string "{JPN}あら {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。 おげんきで\lなによりです。\pそうそう {STR_VAR_2}で\n{STR_VAR_3}れんしょう\lしたそうですね。\pとても みごとです! これからも がんばって\nください。$"

MatchCall_BattleFrontierStreakText9::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}よ!\pきいたわ! {STR_VAR_2}で\n{STR_VAR_3}れんしょうですって!\pすごいじゃない!\nわたしも がんばらないと!$"

MatchCall_BattleFrontierStreakText10::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは…\n{STR_VAR_1}です。\p{STR_VAR_2}で {STR_VAR_3}れんしょう\nしたのですか?\pたいした ものですね。\nわたしも がんばらないと。$"

MatchCall_BattleFrontierStreakText11::
	.string "{JPN}ああ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\p{STR_VAR_2}で おそれられて\nいるそうだな?\pたしか {STR_VAR_3}れんしょう\nだったか?\pたいした ものだ。 わしは なんかい\nかてるかな?$"

MatchCall_BattleFrontierStreakText12::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\lおげんきですか?\pあなたの うわさを\nききました。 {STR_VAR_2}で {STR_VAR_3}れんしょう\lしたとか。\pたいした ものですね。\nそれでは!$"

MatchCall_BattleFrontierStreakText13::
	.string "{JPN}ああ こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\lおげんきで なによりです。\p{STR_VAR_2}で {STR_VAR_3}れんしょう\nしたそうですね。\pその げんきさが うらやましい!\nでは また。$"

MatchCall_BattleFrontierStreakText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\pうわさを ききましたよ!\n{STR_VAR_2}で {STR_VAR_3}れんしょう\lしたのでしょう?\pはげみに なりますわ!\nバイバイ!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "{JPN}やあ! {STR_VAR_1}だよ。\nうわさを きいたよ!\p{STR_VAR_2}で すごい せいせきを\nだしたんだって?\pすごいね {STR_VAR_3}れんしょうだよ!\nそれじゃ また!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "{JPN}こんにちは {STR_VAR_1}です!\nうわさを ききました!\p{STR_VAR_2}で {STR_VAR_3}れんしょうを\nしたそうですね。\pすごい! わたしも がんばらないと!\nそれでは!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "{JPN}よお {PLAYER}! おれだ\n{STR_VAR_1}だ。\p{STR_VAR_2}で\nあばれまわったそうだな!\p{STR_VAR_3}れんしょうか… たいした\nきろくじゃないか。\pおれも しっかり しないとな!\nまたな!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "{JPN}よお {PLAYER}{KUN}。 {STR_VAR_1}だ。\nどうだ?\p{STR_VAR_2}で {STR_VAR_3}れんしょう したと\nうわさに なって\lいるぞ。\pおれも がんばらないとな。\nそれじゃ!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "{JPN}やあ {PLAYER}{KUN}!\n{STR_VAR_1}よ。\p{STR_VAR_2}で {STR_VAR_3}れんしょう\nしたの?\lすごいじゃない!\pわたし? まあまあ ってところね。 また\nね!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "{JPN}よお {PLAYER}{KUN}。 {STR_VAR_1}だ。\nげんきか?\pところで {STR_VAR_2}で\n{STR_VAR_3}れんしょう したと\lきいたぞ。\pおれも がんばらないとな!\nまたな!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "{JPN}…あの {PLAYER}{KUN}?\n{STR_VAR_1}です…\pそうそう {STR_VAR_2}に\nいって いたのですよね?\pそこで {STR_VAR_3}れんしょう したとか。\pあっ めずらしい ポケモンが!\nいかないと!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "{JPN}あら {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。 おげんきで\lなによりです。\pそうそう {STR_VAR_2}で\n{STR_VAR_3}れんしょう\lしたそうですね。\pとても みごとです! わたしも ポケモンを\nそだてないと!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}よ!\pきいたわ! {STR_VAR_2}で\n{STR_VAR_3}れんしょうですって!\pすごいじゃない!\nわたしも がんばらないと!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは…\n{STR_VAR_1}です。\p{STR_VAR_2}で {STR_VAR_3}れんしょう\nしたのですか?\pたいした ものですね。\nわたしも がんばらないと。$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "{JPN}ああ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\p{STR_VAR_2}で おそれられて\nいるそうだな?\pたしか {STR_VAR_3}れんしょう\nだったか?\pたいした ものだ。 わしは なんかい\nかてるかな?$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\lおげんきですか?\pあなたの うわさを\nききました。 {STR_VAR_2}で {STR_VAR_3}れんしょう\lしたとか。\pたいした ものですね。\nそれでは!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "{JPN}ああ こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\lおげんきで なによりです。\p{STR_VAR_2}で {STR_VAR_3}れんしょう\nしたそうですね。\pその げんきさが うらやましい!\nでは また。$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\lうわさを ききましたよ!\p{STR_VAR_2}で {STR_VAR_3}れんしょう\nしたのでしょう?\pはげみに なりますわ!\nバイバイ!$"

MatchCall_BattleDomeText1::
	.string "{JPN}やあ! {PLAYER}?\nこんにちは {STR_VAR_1}だよ!\lうわさを きいたよ!\p{STR_VAR_2}で {STR_VAR_3}かいも\nゆうしょう したんだって?\pすごいね! ぼくも がんばらないと!\nそれじゃ また!$"

MatchCall_BattleDomeText2::
	.string "{JPN}こんにちは {STR_VAR_1}です!\nうわさを ききました!\p{STR_VAR_2}で {STR_VAR_3}かい\nゆうしょう したそうですね。\pすごい! わたしも ゆうしょう\nできるでしょうか?$"

MatchCall_BattleDomeText3::
	.string "{JPN}よお {PLAYER}!\nおれだ {STR_VAR_1}だ。\lちょうしは どうだ?\p{STR_VAR_2}で {STR_VAR_3}かいも\nゆうしょう したそうだな!\pつぎは もう 1かい ふやせよ!\nまたな!$"

MatchCall_BattleDomeText4::
	.string "{JPN}よお {PLAYER}{KUN}。\n{STR_VAR_1}だ。\p{STR_VAR_2}で {STR_VAR_3}かい\nゆうしょう したそうだな。\pがんばって いるようだな。\nおれも おいつかないとな!$"

MatchCall_BattleDomeText5::
	.string "{JPN}やあ {PLAYER}{KUN}!\n{STR_VAR_1}よ。\p{STR_VAR_2}で {STR_VAR_3}かいも\nゆうしょう したんですって。\pわたしも がんばらないと!\nまた ね!$"

MatchCall_BattleDomeText6::
	.string "{JPN}よお {PLAYER}{KUN}? {STR_VAR_1}だ。\nげんきか?\pところで {STR_VAR_2}で {STR_VAR_3}かい\nゆうしょう したと\lきいたぞ。\pこれいじょう はなされる まえに ポケモンを\nそだてないとな。$"

MatchCall_BattleDomeText7::
	.string "{JPN}{PLAYER}{KUN}?\n{STR_VAR_1}です。\p{STR_VAR_2}で {STR_VAR_3}かいも\nゆうしょう したのですね?\pすてきです。 ところで さいきん\nめずらしい ポケモンは つかまえました?\pそう ですか。\nそれでは。$"

MatchCall_BattleDomeText8::
	.string "{JPN}あら {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。\lおげんきで なによりです。\lそうでしょうとも。\p{STR_VAR_2}で {STR_VAR_3}かい\nゆうしょう したと ききました。\pわたしも あなたのように\nポケモンを そだてないと。 では また。$"

MatchCall_BattleDomeText9::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}よ!\pきいたわ! {STR_VAR_2}で\n{STR_VAR_3}かいも ゆうしょうですって!\pすごいじゃない!\nわたしも がんばらないと!$"

MatchCall_BattleDomeText10::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\p{STR_VAR_2}で {STR_VAR_3}かい つづけて\nゆうしょう したのですか?\pたいした ものですね。\nわたしも がんばらないと。$"

MatchCall_BattleDomeText11::
	.string "{JPN}ああ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\p{STR_VAR_2}で おそれられて\nいるそうだな?\pたしか {STR_VAR_3}かい つづけて ゆうしょう\nしたとか?\pわしにも ゆうしょうが\nできるかのう?\p…まず むりかのう? では\nまた!$"

MatchCall_BattleDomeText12::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\lおげんきですか?\p{STR_VAR_2}と いう ところで\n{STR_VAR_3}かい ゆうしょう したとか?\pたいした ものですね。\nそれでは!$"

MatchCall_BattleDomeText13::
	.string "{JPN}ああ こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\lおげんきで なによりです。\p{STR_VAR_2}で {STR_VAR_3}かい\nゆうしょう したそうですね?\pその げんきさが うらやましい!\nでは また。$"

MatchCall_BattleDomeText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\lうわさを ききましたよ!\p{STR_VAR_2}で {STR_VAR_3}かい\nゆうしょう したのでしょう?\pはげみに なりますわ!\nまた ね!$"

MatchCall_BattlePikeText1::
	.string "{JPN}やあ! {PLAYER}?\nこんにちは {STR_VAR_1}だよ!\lうわさを きいたよ!\p{STR_VAR_2}で {STR_VAR_3}つの ルームを\nかちぬいたんだって!\pすごいね!\nそれじゃ また!$"

MatchCall_BattlePikeText2::
	.string "{JPN}こんにちは {STR_VAR_1}です!\nうわさを ききました!\p{STR_VAR_2}で {STR_VAR_3}つの ルームを\nかちぬいたそうですね。\pもっと がんばらないと!\nそれでは!$"

MatchCall_BattlePikeText3::
	.string "{JPN}よお {PLAYER}!\nおれだ {STR_VAR_1}だ。\lちょうしは どうだ?\p{STR_VAR_2}で {STR_VAR_3}つの ルームを\nかちぬいたそうだな!\pつぎは もっと いけよ!\nまたな!$"

MatchCall_BattlePikeText4::
	.string "{JPN}よお {PLAYER}{KUN}。\n{STR_VAR_1}だ。\p{STR_VAR_2}で {STR_VAR_3}つの ルームを\nかけぬけたそうだな。\pおれも ポケモンを きたえて\nおいつかないとな!$"

MatchCall_BattlePikeText5::
	.string "{JPN}やあ {PLAYER}{KUN}!\n{STR_VAR_1}よ。\p{STR_VAR_2}で {STR_VAR_3}つの ルームを\nこえたそうね。\pわたしも がんばらないと!\nまた ね!$"

MatchCall_BattlePikeText6::
	.string "{JPN}よお {PLAYER}{KUN}?\n{STR_VAR_1}だ。 げんきか?\pところで {STR_VAR_2}で {STR_VAR_3}つの\nルームを かちぬいたと きいたぞ。\pこれいじょう はなされる まえに\nポケモンを そだてないとな。$"

MatchCall_BattlePikeText7::
	.string "{JPN}{PLAYER}{KUN}?\n{STR_VAR_1}です。\p{STR_VAR_2}で {STR_VAR_3}つの ルームを\nかちぬいたのですね?\pすごいです。\pあっ めずらしい ポケモンが!\nそれでは。$"

MatchCall_BattlePikeText8::
	.string "{JPN}あら {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。\lおげんきで なによりです。\lそうでしょうとも。\p{STR_VAR_2}で {STR_VAR_3}つの ルームを\nかちぬいたと ききました。\pとても みごとです!\nわたしも あなたのように そだてないと。\lでは また。$"

MatchCall_BattlePikeText9::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}よ!\pきいたわ! {STR_VAR_2}で {STR_VAR_3}つの\nルームを かちぬいたんですって!\pすごいじゃない!\nわたしも がんばらないと!$"

MatchCall_BattlePikeText10::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\p{STR_VAR_2}で {STR_VAR_3}つの ルームを\nかちぬいたのですか?\pたいした ものですね。\nわたしも がんばらないと。$"

MatchCall_BattlePikeText11::
	.string "{JPN}ああ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\p{STR_VAR_2}で おそれられて\nいるそうだな?\pたしか {STR_VAR_3}つの ルームを こえたとか? それは\nたいした ものだ。\pわしにも ゆうしょうが\nできるかのう?\p…まず むりかのう? では\nまた!$"

MatchCall_BattlePikeText12::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\lおげんきですか?\p{STR_VAR_2}と いう ところで {STR_VAR_3}つの\nルームを かちぬいたとか?\pたいした ものですね。\nそれでは!$"

MatchCall_BattlePikeText13::
	.string "{JPN}ああ こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\lおげんきで なによりです。\p{STR_VAR_2}で {STR_VAR_3}つの ルームを\nかちぬいたそうですね?\pその げんきさが うらやましい!\nでは また。$"

MatchCall_BattlePikeText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\lうわさを ききましたよ!\p{STR_VAR_2}で {STR_VAR_3}つの ルームを\nかちぬいたのでしょう?\pはげみに なりますわ!\nまた ね!$"

MatchCall_BattlePyramidText1::
	.string "{JPN}やあ! {PLAYER}?\nこんにちは {STR_VAR_1}だよ!\lうわさを きいたよ!\p{STR_VAR_2}の なかを {STR_VAR_3}かい\nのぼったんだって?\pすごいね!\nぼくも ちょうせん して みようかな。$"

MatchCall_BattlePyramidText2::
	.string "{JPN}こんにちは {STR_VAR_1}です!\nうわさを ききました!\p{STR_VAR_2}の なかを {STR_VAR_3}かい\nかちぬいたそうですね。\pわあ すばらしい!\nわたしも ポケモンを そだてないと!$"

MatchCall_BattlePyramidText3::
	.string "{JPN}よお {PLAYER}!\nおれだ {STR_VAR_1}だ。\lちょうしは どうだ?\p{STR_VAR_2}の なかを {STR_VAR_3}かい\nのぼったそうだな!\pつぎは もっと うえまで いけよ!\nまたな!$"

MatchCall_BattlePyramidText4::
	.string "{JPN}よお {PLAYER}{KUN}。\n{STR_VAR_1}だ。\p{STR_VAR_2}の なかを {STR_VAR_3}かい\nのぼったそうだな。\pおれも がんばって\nおいつかないとな!$"

MatchCall_BattlePyramidText5::
	.string "{JPN}やあ {PLAYER}{KUN}!\n{STR_VAR_1}よ。\p{STR_VAR_2}の なかを {STR_VAR_3}かい\nのぼったそうね。\pわたしも がんばらないと!\nまた ね!$"

MatchCall_BattlePyramidText6::
	.string "{JPN}よお {PLAYER}{KUN}?\n{STR_VAR_1}だ。 げんきか?\pところで {STR_VAR_2}の なかを\n{STR_VAR_3}かい のぼったと きいたぞ。\pこれいじょう はなされる まえに\nポケモンを そだてないとな。$"

MatchCall_BattlePyramidText7::
	.string "{JPN}{PLAYER}{KUN}?\n{STR_VAR_1}です。\p{STR_VAR_2}の なかを\n{STR_VAR_3}かい のぼったのですね?\pすてきです。 めずらしい ポケモンは\nいましたか?\pいなかったのですね。\nそれでは。$"

MatchCall_BattlePyramidText8::
	.string "{JPN}あら {PLAYER}{KUN} ごきげんよう。\n{STR_VAR_1}です。\lおげんきで なによりです。\lそうでしょうとも。\p{STR_VAR_2}の なかを {STR_VAR_3}かい\nのぼったと ききました。\pとても みごとです!\nわたしも あなたのように そだてないと。\lでは また。$"

MatchCall_BattlePyramidText9::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは!\n{STR_VAR_1}よ!\pきいたわ! {STR_VAR_2}の なかを\n{STR_VAR_3}かいも のぼったんですって!\pすごいじゃない!\nわたしも がんばらないと!$"

MatchCall_BattlePyramidText10::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\p{STR_VAR_2}の なかを {STR_VAR_3}かい\nのぼったのですか?\pたいした ものですね。\nわたしも がんばらないと。$"

MatchCall_BattlePyramidText11::
	.string "{JPN}ああ {PLAYER}{KUN}。\n{STR_VAR_1}だ。\p{STR_VAR_2}で おそれられて\nいるそうだな?\pたしか {STR_VAR_3}かい のぼったとか? それは たいした\nものだ。\pわしにも ゆうしょうが\nできるかのう?\p…まず むりかのう? では\nまた!$"

MatchCall_BattlePyramidText12::
	.string "{JPN}こんにちは {PLAYER}{KUN}。\n{STR_VAR_1}です。\lおげんきですか?\p{STR_VAR_2}と いう ところで\n{STR_VAR_3}かい のぼったとか?\pたいした ものですね。\nそれでは!$"

MatchCall_BattlePyramidText13::
	.string "{JPN}ああ こんにちは {PLAYER}{KUN}!\n{STR_VAR_1}です!\lおげんきで なによりです。\p{STR_VAR_2}の なかを {STR_VAR_3}かい\nのぼったそうですね?\pその げんきさが うらやましい!\nでは また。$"

MatchCall_BattlePyramidText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは。\n{STR_VAR_1}です。\lうわさを ききましたよ!\p{STR_VAR_2}の なかを {STR_VAR_3}かい\nのぼったのでしょう?\pはげみに なりますわ!\nまた ね!$"

MatchCall_Text_Mom1::
	.string "{JPN}ママ: おとうさんも あなたも…\nみんな ポケモンに むちゅうね。\pポケモンの みりょくって なにかしら?\pわたし?\nわたしは かじを てつだって くれる\lポケモンが だいすきよ。$"

MatchCall_Text_Mom2::
	.string "{JPN}ママ: あら {PLAYER}!\nおとうさんは トウカジムに\lこもりっきりよ。\pときどき かえっては くるけれど\nたべる ものを たべると\lまた ジムに もどって しまうの。\pあなたに まけたのが よほど\nくやしかったのね!$"

MatchCall_Text_Mom3::
	.string "{JPN}ママ: {PLAYER}…\nわたしや いえの ことは しんぱい しないで。\pその ランニングシューズが\nすりきれるまで はしりなさい!$"

MatchCall_Text_Roxanne1::
	.string "{JPN}ツツジ: あら こんにちは {PLAYER}!\pあれから きたえなおしを\nがんばって いるの。\pジムを ひらきなおすまでには\nもうすこし じかんが かかりそう。\pひらいたら ぜひ もういちど\nジムに ちょうせんに きて ね!$"

MatchCall_Text_Roxanne2::
	.string "{JPN}ツツジ: {PLAYER}?\nおめでとう!\lうわさを きいて いるわ!\pわたしは ジムを ひらきなおすまで\nもうすこし じかんが かかりそう。\pひらいたら ぜひ もういちど\nジムに ちょうせんに きて ね!$"

MatchCall_Text_Roxanne3::
	.string "{JPN}ツツジ: {PLAYER}! ジムの じゅんびが\nできたわ!\pいつでも カナズミに きて\nね!$"

MatchCall_Text_Roxanne4::
	.string "{JPN}ツツジ: カナズミジムでは {PLAYER}と\nしょうぶ した ことが\lほこりに なって いるのよ。$"

MatchCall_Text_Brawly1::
	.string "{JPN}トウキ: よお {PLAYER}{KUN}!\pきみとの しょうぶで たくさん\nまなばせて もらったよ。\pきたえなおしてから ジムを\nひらきなおす つもりだ。\pジムを うごかせるように なるまでは\nもうすこし じかんが かかる。\pひらいたら また ちょうせんに\nきて くれよな。$"

MatchCall_Text_Brawly2::
	.string "{JPN}トウキ: よお {PLAYER}{KUN}!\nおめでとう!\pきみの かつやくは しおかぜに のって\nここまで とどいて いるぜ!\pおれは もっと きたえないと\nだめみたいだな。\pジムを うごかせるように なるまでは\nもうすこし じかんが かかる。\pひらいたら また ちょうせんに\nきて くれよな。$"

MatchCall_Text_Brawly3::
	.string "{JPN}トウキ: よお {PLAYER}{KUN}!\nジムの じゅんびは ばんたんだ!\pいつでも ムロタウンに\nちょうせんに きて くれ!$"

MatchCall_Text_Brawly4::
	.string "{JPN}トウキ: {PLAYER}{KUN} きみとの しょうぶは\nいつまでも あきないぜ!$"

MatchCall_Text_Wattson1::
	.string "{JPN}テッセン: おお きみか!\pきみが いってから きたえなおしを\nいちから やりなおして おる。\pジムを ひらくには もうすこし\nじかんが ほしいのう。\pそれまで まって おれ!\nわはははは!$"

MatchCall_Text_Wattson2::
	.string "{JPN}テッセン: わはははは!\pやって のけたようじゃな?\nうわさは とどいて おるぞ!\pわしは まだまだ きたえなおしが\nひつような ようじゃ。\pジムを ひらくには もうすこし\nじかんが ほしいのう。\pそれまで まって おれ!\nわはははは!$"

MatchCall_Text_Wattson3::
	.string "{JPN}テッセン: おお きみか!\nジムの じゅんびが できたぞ!\pいつでも キンセツに こい!\nわはははは!$"

MatchCall_Text_Wattson4::
	.string "{JPN}テッセン: わははは!\pきみとの しょうぶは いつも\nしびれる ちからに みちて おるわい!$"

MatchCall_Text_Flannery1::
	.string "{JPN}アスナ: {PLAYER}…\pあなたと しょうぶ して じぶんが\nどれだけ みじゅくか わかったわ。\pでも まだ おわりじゃ ない!\pきたえなおして ジムを\nひらきなおすわ。\pその ときは {PLAYER}\nまた ちょうせん して ね。$"

MatchCall_Text_Flannery2::
	.string "{JPN}アスナ: もしもし {PLAYER}?\nおめでとう!\pあなたの かつやくは かざんの ねつのように\nここまで とどいて いるわ!\pこちらの とっくんも\nじゅんちょうに すすんで いるの。\pジムの じゅんびが できたら\nでんわの リストの なまえの よこに\lしるしが つくわ。$"

MatchCall_Text_Flannery3::
	.string "{JPN}アスナ: あら {PLAYER}?\nジムの じゅんびが できたわ!\pフエンに きて おんせんに つかって\nちょうせん して ね!$"

MatchCall_Text_Flannery4::
	.string "{JPN}アスナ: {PLAYER}…\nあなたは あう たびに きたえかたが\lうまく なって いる きが するわ。$"

MatchCall_Text_Winona1::
	.string "{JPN}ナギ: こんにちは {PLAYER}!\pあなたとの しょうぶの おかげで\nじぶんの よわさが わかったわ!\pジムを ひらきなおしたら\nこんどは まけないわよ!$"

MatchCall_Text_Winona2::
	.string "{JPN}ナギ: やったのね {PLAYER}!\pあたらしい チャンピオンの しらせは\nヒワマキにも とどいたわ!\pでも… つぎに しょうぶ する ときは\nおなじ けっかには ならないわよ。$"

MatchCall_Text_Winona3::
	.string "{JPN}ナギ: {PLAYER}?\nジムを ひらきなおしたわ!\pヒワマキで まって いるわ!$"

MatchCall_Text_Winona4::
	.string "{JPN}ナギ: {PLAYER}…\nまけは したけれど わたしの つばさは\lけっして おれない。\pそう あなたが ゆめを みうしなわなかったのと\nおなじように ね。$"

MatchCall_Text_TateLiza1::
	.string "{JPN}フウ: おっ きみは…\nラン: {PLAYER}!\pフウ: ぼくたちは また とっくんちゅう…\nラン: ジムを ひらきなおす ために!\pフウ: ジムの じゅんびが できたら…\nラン: ジムの じゅんびが できたら…\pフウ: なまえの よこに しるしが…\nラン: でんわの リストに つくよ。$"

MatchCall_Text_TateLiza2::
	.string "{JPN}フウ: {PLAYER} おめでとう!\nラン: {PLAYER} おめでとう!\pフウ: ぼくたち ふたりは…\nラン: まだ とっくんちゅう!\pフウ: もうすこし かかるけど…\nラン: ジムの じゅんびが できたら…\pフウ: なまえの よこに しるしが…\nラン: でんわの リストに つくよ。$"

MatchCall_Text_TateLiza3::
	.string "{JPN}フウ: {PLAYER}!\nラン: {PLAYER}!\pフウ: ジムの じゅんびが できたよ!\nラン: ジムの じゅんびが できたよ!\pフウ: いつでも きて…\nラン: トクサネに きて ね!$"

MatchCall_Text_TateLiza4::
	.string "{JPN}フウ: {PLAYER} ぼくたちの しょうぶは…\nラン: かけがえの ない けいけんだよ。\pフウ: できる ことなら…\nラン: また しょうぶ したいね!$"

MatchCall_Text_Juan1::
	.string "{JPN}アダン: ふむ…\n{PLAYER}{KUN}… だったかな?\pきみとの しょうぶは わたしが はじめて\nミクリと であった ときの ことを\lおもいださせて くれた。\pきみは ミクリを こえるかも しれない\nてんさいかも しれんな!$"

MatchCall_Text_Juan2::
	.string "{JPN}アダン: ふふ… {PLAYER}{KUN}… ついに もくひょうを\nはたしたな。\pわたしの ひとを みる めは まちがって\nいなかった…\pちからと ほまれの いただきに\nたった きみと また あいたい\lものだ。$"

MatchCall_Text_Juan3::
	.string "{JPN}アダン: ほほう… {PLAYER}{KUN}…\pルネジムが ついに\nひらきなおされた。\pわたしに あいたければ\nいつでも きて くれたまえ。$"

MatchCall_Text_Juan4::
	.string "{JPN}アダン: {PLAYER}{KUN}…\pさいこうの おんがくのように きみとの\nしょうぶは わたしの こころに\lひびきを のこして いく…\pめを とじると メロディに のって\nまいあがる きみの すがたが みえる…$"

MatchCall_Text_Sidney::
	.string "{JPN}カゲツ: よお {PLAYER}!\pまた おれと しょうぶ したければ\nいつでも ポケモンリーグに\lもどって くれば いい。\pおれは いつでも ここに いる!\nまって るぜ!$"

MatchCall_Text_Phoebe::
	.string "{JPN}フヨウ: こんにちは {PLAYER}!\pまた いつか ここに\nきて くれない?\pあなたと ポケモンの きずなが\nどれだけ ふかく なったか\lみて みたいの。$"

MatchCall_Text_Glacia::
	.string "{JPN}プリム: こんにちは {PLAYER}。\pその ちからに おごって いないと\nしんじて いますよ?\pあつく なった こころを すこし\nひやしたく なったら ポケモンリーグへ\lいらっしゃい…$"

MatchCall_Text_Drake::
	.string "{JPN}ゲンジ: その こえ… {PLAYER}か?\nげんきそうだな…\pトレーナーの うでを ためす\nバトルフロンティアと いう しせつが\lできたと きいた。\pだが ほんとうの しょうぶを のぞむなら\nポケモンリーグに かなう ものは\lないと おもう。\lそうでは ないか?\pそう おもわんか {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "{JPN}ミクリ: こんにちは {PLAYER}{KUN}。 ダイゴには\nあったかな?\pかれは… じつは とんでもなく\nつよいのだよ。\pだが めったに しょうぶを しない かわった\nおとこでね。\pそれよりも めずらしい いしを さがして いる\nほうが すきなのだ。\pいまごろ どこかの どうくつか いわやまを ほって\nいるだろう。\pしかし めずらしい いしとは いったい\nなんだろうね? わたしには わからないよ。$"

MatchCall_Text_MayRayquazaCall:
	.string "{JPN}… … … … … … … … … … …\nピッ!\pハルカ: やあ {PLAYER}{KUN}!\pさっき キナギタウンに\nいたの。\pおおきな みどりいろの ポケモンが そらを とんで\nいくのを みたわ。\pわたし… あんなの みた ことが\nない。\pなんだったのかしら。 おおきな\nはっけんかも?\p… … … … … … … … … … …\nピッ!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "{JPN}… … … … … … … … … … …\nピッ!\pユウキ: よお {PLAYER}! さっき キナギタウンに\nいたんだ。\pおおきな みどりいろの ポケモンが そらを とんで\nいくのを みたぞ。\pあんな すごい ものは みた ことが\nない。\p{PLAYER}にも\nみせたかったな。\p… … … … … … … … … … …\nピッ!$"

MatchCall_Text_May1::
	.string "{JPN}ハルカ: やあ {PLAYER}{KUN}!\pウシオさんは ふなのりを やめたけど\nいまでも あいぼうの チャーリーと\lうみに でて いるのを みかけるの。\pやっぱり うみが すきなのね。$"

MatchCall_Text_May2::
	.string "{JPN}ハルカ: やあ {PLAYER}{KUN}!\pトウカや ムロみたいな ちいさな まちにも\nジムが あるでしょう?\pなのに おおきな みなとの カイナには\nどうして ジムが ないのかしら。\pいつか カイナに ジムが できたら\nリーダーに おうぼ しようかな。$"

MatchCall_Text_May3::
	.string "{JPN}ハルカ: やあ {PLAYER}{KUN}!\pカナズミに いあいぎりの おじさんが\nいたのを おぼえて る?\lいえが あったでしょう?\pその おとうとが キンセツに\nすんで いるって わかったの。\pなんて よばれて いると おもう?\p… … … … … …\n… … … … … …\pいわくだきの おじさん!$"

MatchCall_Text_May4::
	.string "{JPN}ハルカ: {PLAYER}{KUN}?\pカナシダトンネル…\nカナズミと シダケを つなぐから\lその なまえに なったのよ。$"

MatchCall_Text_May5::
	.string "{JPN}ハルカ: {PLAYER}{KUN} げんき?\pいま 111ばんどうろに いるの。\pおばあさんの いえで\nひとやすみ する つもり。\pさばくの すぐ きたに\nすんで いる ひとよ。$"

MatchCall_Text_May6::
	.string "{JPN}ハルカ: やあ {PLAYER}{KUN}!\pさばくの しんきろうのとうを\nしって る?\pしんきろうみたいに あらわれたり\nきえたり するんだって。\pいちど みて みたいなあ。$"

MatchCall_Text_May7::
	.string "{JPN}ハルカ: {PLAYER}{KUN} ヤッホー!\nいま 119ばんどうろに いるの。\pおおきな かわが あって\nよく あめが ふるのよ。\pびしょぬれに なっちゃった!$"

MatchCall_Text_May8::
	.string "{JPN}ハルカ: {PLAYER}{KUN} こんにちは。\pおくりびやまは いのちを おえた\nポケモンを まつる ばしょなの。\pそのせいか ゴーストタイプの\nポケモンが たくさん いるわ!$"

MatchCall_Text_May9::
	.string "{JPN}ハルカ: やあ {PLAYER}{KUN}!\pフエンの おんせんに いこうと\nおもって いたの。\pでも とちゅうの ゴツゴツやまみちで\nあやしい ひとたちに あったの。\lいやな かんじ だったわ!$"

MatchCall_Text_May10::
	.string "{JPN}ハルカ: やあ {PLAYER}{KUN}!\nニュースを みた?\pウズシオはかせが せんすいていの\nちょうさで かいていどうくつを\lみつけたんですって。$"

MatchCall_Text_May11::
	.string "{JPN}ハルカ: やあ {PLAYER}{KUN}! すごいと\nおもわない?\pふねが なくても ポケモンの\nわざで うみを\lわたれるのよ。\pもっと すごいのが あるの。\pうみの そこまで もぐれる ポケモンの わざも\nあるのよ。$"

MatchCall_Text_May12::
	.string "{JPN}ハルカ: やあ {PLAYER}{KUN}! うまく\nいってる?\pうみで むこうがわに\nいけなく なった ことは\lない?\pふかく もぐって みぞを たどって\nみて。\pむこうがわに ついたら うかびあがれば いいの。\nかんたん!$"

MatchCall_Text_May13::
	.string "{JPN}ハルカ: やあ {PLAYER}{KUN}!\pちょうしは どう?\nずかんは うまって きた?\pちょうこだいの ポケモンが いると\nいう うわさを きいたの。\lしかも 3びきも!\p1ぴきでも いいから みて みたいわ…$"

MatchCall_Text_May14::
	.string "{JPN}ハルカ: {PLAYER}{KUN}! うわさを\nきいたわ!\pルネジムの リーダーに\nかったの?\pそれなら ゴールまで あと\nすこしじゃない?$"

MatchCall_Text_May15::
	.string "{JPN}ハルカ: ホウエンには {PLAYER}{KUN}を\nしらない トレーナーは もう\lいないわ!\p{PLAYER}{KUN}の ともだちだと いうと\nみんな びっくり\lするのよ!$"

MatchCall_Text_Brendan1::
	.string "{JPN}ユウキ: よお {PLAYER}!\pウシオさんは ふなのりを やめたけど いまでも\nあいぼうの チャーリーと うみに でて いるのを\lみかけるぞ。\pやっぱり うみが\nすきなんだろうな。$"

MatchCall_Text_Brendan2::
	.string "{JPN}ユウキ: よお {PLAYER}!\pトウカや ムロみたいな ちいさな まちに\nジムが あるのが よく わからないんだ。\pおおきな みなとの カイナに\nジムが ないっていうのにさ。\pいつか カイナに ジムが できたら\nリーダーに おうぼ しようかな。$"

MatchCall_Text_Brendan3::
	.string "{JPN}ユウキ: よお {PLAYER}!\pカナズミに いあいぎりの おじさんが\nいたのを おぼえて るか?\lいえが あったよな?\pその おとうとが キンセツに\nすんで いる ことが わかったんだ。\pなんて よばれて いると おもう?\p… … … … … …\n… … … … … …\pいわくだきの おじさん!$"

MatchCall_Text_Brendan4::
	.string "{JPN}ユウキ: この こえ… {PLAYER}?\pカナシダトンネルは カナズミと\nシダケを つなぐから その なまえに\lなったんだって。\pしって いたか?$"

MatchCall_Text_Brendan5::
	.string "{JPN}ユウキ: {PLAYER} どうした?\pいま 111ばんどうろに いるんだ。\pさばくの きたに ある おばあさんの\nいえで ひとやすみ する つもりだ。\pちかくに きたら きみも\nよって みると いいぞ。$"

MatchCall_Text_Brendan6::
	.string "{JPN}ユウキ: よお {PLAYER}!\pさばくの しんきろうのとうを\nしって るか?\pしんきろうみたいに ときどきしか\nみえないんだって。\pいちど みて みたいな!$"

MatchCall_Text_Brendan7::
	.string "{JPN}ユウキ: だれだ? おっ {PLAYER}?\nいま 119ばんどうろに いるんだ。\pおおきな かわが あって\nいつも あめが ふって いる。\pずぶぬれに なったよ!$"

MatchCall_Text_Brendan8::
	.string "{JPN}ユウキ: {PLAYER}!\pおくりびやまは いのちを おえた\nポケモンを まつる ばしょなんだ。\pだから ゴーストタイプの ポケモンが\nたくさん いるんだろうな!$"

MatchCall_Text_Brendan9::
	.string "{JPN}ユウキ: よお {PLAYER}。\pフエンの おんせんに もどる\nとちゅう だったんだ。\pでも ゴツゴツやまみちで\nあやしい やつらに あった。\pあいつら…\nマグマだん だったと おもう。$"

MatchCall_Text_Brendan10::
	.string "{JPN}ユウキ: よお {PLAYER}!\nニュースを みたか?\pウズシオはかせが せんすいていの\nちょうさで かいていどうくつを\lみつけたんだってさ。$"

MatchCall_Text_Brendan11::
	.string "{JPN}ユウキ: よお {PLAYER}! すごいと\nおもわないか?\pふねが なくても ポケモンの\nわざで うみを\lわたれるんだ。\pしかも うみの そこまで もぐれる わざも\nあるんだぜ。\pポケモンは なんでも できるな!$"

MatchCall_Text_Brendan12::
	.string "{JPN}ユウキ: よお {PLAYER}!\nちょうしは どうだ?\pうみで むこうがわに いけなく\nなった ことは ないか?\pふかく もぐって そこの みぞを\nたどって みろ。\pむこうがわに ついたら\nうかびあがれば いい。 かんたんだ!$"

MatchCall_Text_Brendan13::
	.string "{JPN}ユウキ: よお {PLAYER}!\pちょうしは どうだ? ずかんは\nうまって きて いるか?\pちょうこだいの ポケモンが いると\nいう うわさを きいたぞ。\lしかも 1ぴきじゃ なく 3びき!\p1ぴきでも つかまえて みたいな…$"

MatchCall_Text_Brendan14::
	.string "{JPN}ユウキ: {PLAYER}!\nうわさを きいたぞ!\pルネジムの リーダーに かったって?\nすごいな!\pゴールまで あと すこしじゃないか!$"

MatchCall_Text_Brendan15::
	.string "{JPN}ユウキ: ホウエンじゅうに {PLAYER}を\nしらない トレーナーは もう\lいないぞ!\p{PLAYER}の ともだちだと いうと\nみんな\lうらやましがるんだ!$"

MatchCall_Text_Wally1::
	.string "{JPN}ミツル: あっ {PLAYER}!\pぼく だんだん からだが\nじょうぶに なって きたよ。\pはやく {PLAYER}みたいな\nトレーナーに なりたいな!$"

MatchCall_Text_Wally2::
	.string "{JPN}ミツル: {PLAYER} こんにちは!\pカナシダトンネルが つうじてから\nミオさんは とても うれしそうだよ!$"

MatchCall_Text_Wally3::
	.string "{JPN}ミツル: あっ {PLAYER}!\pぼく… だれにも いわずに シダケの\nおじさんの いえを でて きたんだ。\pおこって いるかな…\p{PLAYER}なら ぼくの きもち\nわかって くれるよね?$"

MatchCall_Text_Wally4::
	.string "{JPN}ミツル: {PLAYER}?\nぼくだよ ミツル!\pトレーナーの せかいって すごいね!\pポケモンと いっしょに いると\nいろんな ひとが こえを かけて くれる!\pポケモンを つうじて みんなが\nつながって いくみたいだ!$"

MatchCall_Text_Wally5::
	.string "{JPN}ミツル: {PLAYER}? すごいんだ!\nいっしょに つかまえた ラルトスが\lしんか したんだよ {PLAYER}!\pぼくにも さいのうが あるのかな…\pあっ でも いい きに\nなっちゃ だめだね!\pほめられるべきなのは\nポケモンの ほうだもんね!$"

MatchCall_Text_Wally6::
	.string "{JPN}… … … … … …\n… … … … … …\pミツルは ポケナビの つうじない\nところに いるようだ…$"

MatchCall_Text_Wally7::
	.string "{JPN}ミツル: あっ {PLAYER}!\pきみに あう まえは いえから\nほとんど でられなかった…\pでも いまは じぶんの ポケモンと\nぼうけんを して いる…\p{PLAYER}…\nありがとう…$"

MatchCall_Text_Scott1::
	.string "{JPN}スミオ: やあ {PLAYER}{KUN}!\pポケモンは どこにでも\nいるだろう?\pやまにも うみにも どこの くさむらにも\nいる。\pポケモンと おなじで トレーナーも どこにでも\nいるんだ。\pだから おれも あちこち いそがしくてね。\nいそがしい いそがしい!$"

MatchCall_Text_Scott2::
	.string "{JPN}スミオ: いま 119ばんどうろに いる。\nトレーナーだらけだ!\pそれに\nくさむらだらけでもある。\pはんズボンで あるくと くすぐったくて\nたまらないよ!$"

MatchCall_Text_Scott3::
	.string "{JPN}スミオ: やあ やあ {PLAYER}{KUN}!\pおくりびやまには\nのぼったかい?\pあそこは いのちを おえた ポケモンを まつる\nばしょなんだ。\pトレーナーなら いちどは てっぺんまで\nのぼるべきだよ。$"

MatchCall_Text_Scott4::
	.string "{JPN}スミオ: やあ {PLAYER}{KUN}!\pへんな しゅうだんが めいわくを\nかけて いると きいたよ。\pマグマだんと アクアだん\nだったかな。\pその なかにも うでの たつ\nトレーナーは いるだろうな。\p…だが ならずものでは なあ…$"

MatchCall_Text_Scott5::
	.string "{JPN}スミオ: やあ {PLAYER}{KUN}。\pうみの そこにも つよい トレーナーが\nいるのかな?\pじぶんでは たしかめられない。\nおよげないしね。\lポケモンも そだてて いないし…$"

MatchCall_Text_Scott6::
	.string "{JPN}スミオ: やあ やあ {PLAYER}{KUN}!\pジムバッジを ぜんぶ あつめると\nポケモンリーグに ちょうせん できるのは\lしって いるね?\pきみの さいのうなら チャンピオンに\nなるのも ゆめじゃ ない。\pだが しって いるかい?\nもっと いい ところが あるんだ。\pまあ いまの ところは\nここまでに して おこうか。\pきみが じぶんで きづく ことに\nいみが あるからね。\pきみなら きっと じぶんで\nみつけられるはずさ!\lたのしみに して いるよ!$"

MatchCall_Text_Scott7::
	.string "{JPN}… … … … … …\n… … … … … …\pスミオは ポケナビの つうじない\nところに いるようだ…$"

MatchCall_Text_Norman1::
	.string "{JPN}パパ: カナズミに いあいぎりと\nいう かわった なまえの おとこが\lいる。\pちかくに いく ことが あったら たずねて みると\nいい。$"

MatchCall_Text_Norman2::
	.string "{JPN}パパ: ふむ… すこしずつ しかし\nたしかに おまえは つよく なって いるな\l{PLAYER}。\pつよく なるほど ママと\nわたしから とおく たかく とんで\lいく…\pなんとも いえない きもちだ。$"

MatchCall_Text_Norman3::
	.string "{JPN}パパ: そうか…\nジムバッジを 4つ あつめたか…\pもう さけては とおれないな。\nやくそくどおり しょうぶ しよう。\pいつでも きなさい。\nみんなで まって いるぞ!$"

MatchCall_Text_Norman4::
	.string "{JPN}パパ: {PLAYER}! ときどきは ママの\nかおを みに かえりなさい。\pわたしは ここに のこって\nきたえなおす つもりだ。\pしょうぶの みちは ふかく\nきびしい ものだ!$"

MatchCall_Text_Norman5::
	.string "{JPN}パパ: おお {PLAYER}!\pなに? マグマのエンブレム?\nなんの ことか わからんな。\pだが その なまえなら かざんと\nかんけいが あるのかも しれん!$"

MatchCall_Text_Norman6::
	.string "{JPN}パパ: やあっ! はあっ! だあっ!\p…ん? {PLAYER}!\pちょうど ポケモンの とっくんの\nさいちゅう だったんだ!$"

MatchCall_Text_Norman7::
	.string "{JPN}パパ: {PLAYER}!\pまさか おまえが ポケモンリーグの\nチャンピオンに なるとはな…\pよし!\nわたしも まけては いられん!$"

MatchCall_Text_Norman8::
	.string "{JPN}パパ: ん? {PLAYER}?\nちょうど よかった!\pこんどは わたしから\nしょうぶを いどむぞ。\pトウカジムで まって いる。\nいつでも うけて たて!$"

MatchCall_Text_Norman9::
	.string "{JPN}パパ: …おまえには おどろかされる {PLAYER}。\nどこまで たかく とんで いくのだ?$"

MatchCall_Text_Steven1::
	.string "{JPN}ダイゴ: やあ {PLAYER}{KUN}!\pもう キンセツには\nいったかい?\pじてんしゃやで マッハじてんしゃを もらうと\nいいよ。\pそれから いしのどうくつを すみずみまで しらべて\nみるんだ。\pあたらしい はっけんが あるかも\nしれないよ。$"

MatchCall_Text_Steven2::
	.string "{JPN}ダイゴ: やあ {PLAYER}{KUN}!\pこれまで たくさんの トレーナーに\nあって きた。\pだが きみは とくべつだ。\nだれとも にて いない。$"

MatchCall_Text_Steven3::
	.string "{JPN}ダイゴ: やあ {PLAYER}{KUN}!\pポケモンと ぼうけんを して いる とき なにを\nかんじる?\pたよれる なかまだと\nおもう?\pたのしい ともだちだと\nおもう?\pその かんがえかたで ぼうけんの いみは かわって\nいくんだ。$"

MatchCall_Text_Steven4::
	.string "{JPN}ダイゴ: もしもし?\n{PLAYER}{KUN}?\pうちゅうセンターで ちょっとした\nもんだいが おきて いてね。\pすまないが いまは はなせない。\nまた!$"

MatchCall_Text_Steven5::
	.string "{JPN}ダイゴ: おお!\n{PLAYER}{KUN}!\pことばは いらない。\nもう そういう ときでは ない。\pじぶんを しんじて ただしいと\nおもう ことを するんだ。$"

MatchCall_Text_Steven6::
	.string "{JPN}… … … … … …\pダイゴは でんわに でられない\nようだ…$"

MatchCall_Text_Steven7::
	.string "{JPN}ダイゴ: {PLAYER}{KUN}… でんどういり\nおめでとう。\p… … … … … …\n… … … … … …\pまた どこかで あえると\nいいね!$"

MatchCall_Text_BirchRegisterCall:
	.string "{JPN}オダマキはかせ: おお {PLAYER}{KUN}! うわさは きいて\nいるよ!\pポケナビに でんわの きのうが\nついたそうだね。\pでは わたしも とうろく しよう!\pそうすれば きみが そとに\nいても ずかんを みせて\lもらえるからね。\p… … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "{JPN}オダマキはかせを\nポケナビに とうろく した。$"

MatchCall_Text_UnusedProfBirch:
	.string "{JPN}オダマキはかせ: ずかんと ポケナビの\nりょうほうが あると ポケモンの\lけんきゅうが もっと たのしく なるね?$"

MatchCall_Text_MrStone1::
	.string "{JPN}ツワブキ: おや? {PLAYER}{KUN}!\pでんわが かかって きたと いう ことは\nポケナビは ちゃんと うごいて おるな!\pほかの ひとも とうろく されるから\nかけて みると よい!\pよし よし!\nずいぶん うれしそうだな!\pふむ…\nなぜ わかるのかって?\pしゃちょうしつの まどから\nきみを みおろして いるからだ!\pわははは!\nまた あおう!$"

MatchCall_Text_MrStone2::
	.string "{JPN}ツワブキ: おや? {PLAYER}{KUN}!\pどうした? たのんだ ようじを\nわすれて しまったのか?\pムロタウンの ダイゴに\nてがみを とどけて くれ。\pその あとは カイナの ウズシオはかせに\nにもつを とどけて くれたまえ。\pおぼえて いるだろう?\pさて いそがしい しゃちょうなので\nこれで しつれい! またな!$"

MatchCall_Text_MrStone3::
	.string "{JPN}ツワブキ: おお! {PLAYER}{KUN}!\pほう ダイゴに あったのか!\nそれなら れいを せねばな!\pカナズミに きた ときは\nしゃちょうしつに よって くれ。\pまって いるぞ!$"

MatchCall_Text_MrStone4::
	.string "{JPN}ツワブキ: おお! {PLAYER}{KUN}!\pデボンが カナシダトンネルを\nほって いたのを しって おるかね?\pだが その あたりの ポケモンを\nまもる ために こうじを やめたのだ。\pあたりまえの ことだよ。\pわれわれの つごうより ポケモンが\nおだやかに くらせる ほうが\lたいせつだからな。$"

MatchCall_Text_MrStone5::
	.string "{JPN}ツワブキ: やあ やあ {PLAYER}{KUN}!\pトウカの ものから きみが センリの こどもだと\nきいたぞ!\pどうりで しっかり して\nおるわけだ!$"

MatchCall_Text_MrStone6::
	.string "{JPN}ツワブキ: なんだと?\pじぶんの ちちおやと しょうぶ して\nかったと いうのか?\pそれは たいした ものだ!\pそんな とくべつな ものと ともだちに\nなって いたとは! わははは!$"

MatchCall_Text_MrStone7::
	.string "{JPN}はい!\nこちら デボンコーポレーショ…\lおや {PLAYER}!\pしゃちょうは すこし まえまで\nおりましたが でかけました。\pしゃちょうも いそがしいですが\n{PLAYER}も おなじくらい いそがしそうですね。$"

MatchCall_Text_MrStone8::
	.string "{JPN}…え? …なんですって?\pグラー… はい? …ドン?\pとぎれとぎれで…\n…きこえません…\pザザザ…$"

MatchCall_Text_MrStone9::
	.string "{JPN}…え? …なんですって?\pかいてい… はい? …どうくつ?\pとぎれとぎれで…\n…きこえません…\pザザザ…$"

MatchCall_Text_MrStone10::
	.string "{JPN}ツワブキ: {PLAYER}{KUN}! わしだ!\pいろいろな ことに かかわって\nいたようだが いそがしくて\lなにが なんだか わからん!\pだが じぶんが しんじる みちを\nえらんで あるいて いきなさい。\pわしは いつでも きみの みかただ!\nげんきでな!$"

MatchCall_Text_MrStone11::
	.string "{JPN}ツワブキ: … … … … … …\nもしや {PLAYER}{KUN}かね?\pじしんに みちた こえで\nすぐには わからなかったぞ!\pふむ! いちど デボンにも\nあそびに きなさい!$"
