@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string "{JPN} とても きれい!$"

GiddyText_SoDarling::
	.string "{JPN} とても かわいい!$"

GiddyText_SoRelaxed::
	.string "{JPN} とても のんびり!$"

GiddyText_SoSunny::
	.string "{JPN} とても はれやか!$"

GiddyText_SoDesirable::
	.string "{JPN} とても すてき!$"

GiddyText_SoExciting::
	.string "{JPN} とても わくわく!$"

GiddyText_SoAmusing::
	.string "{JPN} とても ゆかい!$"

GiddyText_SoMagical::
	.string "{JPN} とても ふしぎ!$"

GiddyText_Is::
	.string "{JPN}は$"

GiddyText_DontYouAgree::
	.string "{JPN}\nそう おもわない?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "{JPN}りょこうに いきたいなあ。\nどこか いい ところ しらない?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "{JPN}120いろの クレヨンを かったの!\nすてきだと おもわない?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "{JPN}あわの くもに のって ふわふわ\nとんで いけたら すてきだと おもわない?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "{JPN}すなはまに かいた じは ながされて しまうの。\nかなしく なっちゃう。$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "{JPN}うみの そこって どんな ところかしら?\nいちどでいいから いって みたいわ!$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "{JPN}ゆうひを みると おうちに かえりたく\nならない?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "{JPN}みどりの くさに ねころぶと…\nああ とても とても きもちが いいの!$"

GiddyText_SecretBasesAreSoWonderful::
	.string "{JPN}ひみつきちって すてきよね!\nわくわく して こない?$"
