MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "{JPN}この わざは いちどしか おしえられません。\nそれでも いいですか?$"

MoveTutor_Text_SwaggerTeach:
	.string "{JPN}へへっ! おれの ポケモンは さいこうだぜ! どの\nポケモンより かっこいい!\pなんて いばって いたら\nかいちょうに しかられて\lしまってな。\pすっかり いばれなく なったよ。 へこむよなあ。\pよければ きみの ポケモンに いばるを おしえて\nやろうか?$"

MoveTutor_Text_SwaggerDeclined:
	.string "{JPN}なんだ ことわるのか?\nノリが わるいなあ?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "{JPN}よし どの ポケモンに いばるを\nおしえようか?$"

MoveTutor_Text_SwaggerTaught:
	.string "{JPN}これからは いばらずに ポケモンを\nほめる ことに するよ。$"

MoveTutor_Text_RolloutTeach:
	.string "{JPN}ここから あっちへ むきを かえずに\nずっと いけるのを しって\lいたかい?\pおれなら ころがって\nいけそうだ。\pきみの ポケモンも ころがりたいと おもわないか?\nそうだ いい ことを おもいついた。\pよければ ころがるを おしえて\nやるよ。$"

MoveTutor_Text_RolloutDeclined:
	.string "{JPN}えんりょ しなくて いいんだぞ。\nさあ ころがろう!$"

MoveTutor_Text_RolloutWhichMon:
	.string "{JPN}えへへ もちろん! おれに にた\nポケモンだと うれしいな。$"

MoveTutor_Text_RolloutTaught:
	.string "{JPN}くさの うえを ころがるのは たのしいぞ。\nさあ ころがろう!$"

MoveTutor_Text_FuryCutterTeach:
	.string "{JPN}つづけて つかうと つよく なる わざが\nあるんだ。\pむしタイプの わざで とんでもなく\nかっこいいんだ。\pれんぞくぎりって いうんだ。\nポケモンに おしえて やろうか?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "{JPN}はなしが あわないな。$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "{JPN}やった!\nどの ポケモンに おしえるか みせて。$"

MoveTutor_Text_FuryCutterTaught:
	.string "{JPN}つづけて あたるか みて いるのが\nたまらないんだ!$"

MoveTutor_MimicTeach:
	.string "{JPN}おお わかいの!\pわしも わかいのだが この まちの\nとしよりの はなしかたを\lまねて おってな。\pどうじゃ わかいの?\nものまねを おしえて やると\lいったら うけて くれるかね?$"

MoveTutor_MimicDeclined:
	.string "{JPN}ああ ざんねん! きみの ポケモンに\nものまねを おしえたかったのに!$"

MoveTutor_Text_MimicWhichMon:
	.string "{JPN}ほほう! では おしえよう!\nおしえて ほしい ポケモンを\lみせなさい。$"

MoveTutor_Text_MimicTaught:
	.string "{JPN}ものまねは おくの ふかい わざじゃ。\pわしのように みごとに\nつかいこなせるかな…?$"

MoveTutor_Text_MetronomeTeach:
	.string "{JPN}いろいろ ほしい ものが あるの!\nでも こづかいを つかいきっちゃった…\pゆびを ふると おかねが でてくる\nまほうが あったら いいのに。\lそう おもわない?\pよければ ポケモンに ゆびをふるを\nおしえて あげる。\pおかねは でないけど ポケモンが\nゆびを ふるわよ。 いい?$"

MoveTutor_Text_MetronomeDeclined:
	.string "{JPN}わかった。 きが かわったら\nここに いるからね。$"

MoveTutor_Text_MetronomeWhichMon:
	.string "{JPN}いいわよ! おしえて あげる!\nどの ポケモンに おしえる?$"

MoveTutor_Text_MetronomeTaught:
	.string "{JPN}ポケモンが メトロノームみたいに ゆびを\nふると いろいろな いい ことが\lおきるの。\pわたしたちにも つかえたら\nいいのにね?$"

MoveTutor_Text_SleepTalkTeach:
	.string "{JPN}ふん! つまは ねむけを さますのに\nめざめるパワーに たよって おる。\pわしのように ひるねを して\nねごとを いえば よいのだ。\pきみの ポケモンには ねごとを\nおしえて やろう。 どうかね?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "{JPN}ああ よい よい。 きみも めざめるパワーで\nおきて いたいのだな…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "{JPN}おお ものわかりの よい こじゃ!\nどの ポケモンに おしえようか?$"

MoveTutor_Text_SleepTalkTaught:
	.string "{JPN}つまの コインの てじなは いちども うまく できた\nためしが ない。\pねごとで いいから せいこう\nしたいものだ…$"

MoveTutor_Text_SubstituteTeach:
	.string "{JPN}やねの うえから ひろい せかいを みて\nいると…\pじぶんが ひとりでは なくて いろいろな\nじんせいを たのしめたら いいのにと\lおもうの。\pもちろん むりだけどね。\nうふふ…\pそうだ! ポケモンに みがわりを おぼえさせて\nみない?$"

MoveTutor_Text_SubstituteDeclined:
	.string "{JPN}あら ちがうの?\pポケモンが じぶんの ぶんしんを\nつくれるのよ?$"

MoveTutor_Text_SubstituteWhichMon:
	.string "{JPN}うふふ…\nどの ポケモンに みがわりを\lおしえましょうか?$"

MoveTutor_Text_SubstituteTaught:
	.string "{JPN}わたしたち にんげんは じぶんの じんせいを\nめいっぱい たのしむべきよ!\pあなたも そう なって ほしいわ!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "{JPN}もう むりだ!\pまったく のぞみが ない!\pおれは かくとうタイプの トレーナーだ。\nどんなに がんばっても トクサネジムでは\lかてないんだ!\pうおお! パンチ! パンチ! パンチ!\nパンチ! パンチ! パンチ!\pなんだ そんな めで みるな!\nじめんを なぐって いるだけだ!\pそれとも きみの ポケモンに\nばくれつパンチを おしえようか?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "{JPN}くそっ! きみまで ばかに するのか?\nパンチ! パンチ! パンチ!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "{JPN}なに? いいのか? いい やつだな!\nどの ポケモンに おしえようか?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "{JPN}その ばくれつパンチで トクサネジムに\nかって くれよ!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "{JPN}はあ…\pルネシティの ジムリーダーは ほんとうに すてきな\nかた。\pでも それだけ ライバルも\nおおいの。\pすてみタックルのような みりょくが あって\nわたしなど めに とめて くれないわ。\pおねがい あなたの ポケモンに すてみタックルを\nおしえさせて!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "{JPN}ああ…\nあなたにまで ことわられるなんて…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "{JPN}それで どの ポケモンに すてみタックルを\nおしえましょうか?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "{JPN}もう こいには いきないわ!\nつよく なるのよ!$"

MoveTutor_Text_ExplosionTeach:
	.string "{JPN}こんな いなかで くすぶって いる\nつもりは ないんだ。\pみて いろ まちへ でて\nおおものに なって みせる。\pほんきだぞ にんきの だいばくはつを\nおこして やる!\pいまの ことばを きいたなら きみの\nポケモンに だいばくはつを おしえて やる!$"

MoveTutor_Text_ExplosionDeclined:
	.string "{JPN}ぐあっ! いなかものだからと\nことわるのか?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "{JPN}よし! だいばくはつだ!\nどの ポケモンが ばくはつ したい?$"

MoveTutor_Text_ExplosionTaught:
	.string "{JPN}ながい あいだ ポケモンに だいばくはつを\nおしえて きたが じぶんの ばくはつは\lまだ おこせて いない…\pこころの どこかで ここに のこりたいと\nおもって いるからかも しれないな…$"
