gText_ObtainedTheItem::
	.string "{JPN}{STR_VAR_2}を てにいれた!$"

gText_TheBagIsFull::
	.string "{JPN}バッグが いっぱいだ…$"

gText_PutItemInPocket::
	.string "{JPN}{PLAYER}は {STR_VAR_2}を\n{STR_VAR_3}ポケットに しまった。$"

gText_PlayerFoundOneItem::
	.string "{JPN}{PLAYER}は {STR_VAR_2}を みつけた!$"

gText_TooBadBagIsFull::
	.string "{JPN}ざんねん!\nバッグが いっぱいだ…$"

gText_PlayerPutItemInBag::
	.string "{JPN}{PLAYER}は {STR_VAR_2}を\nバッグに しまった。$"

gText_ObtainedTheDecor::
	.string "{JPN}{STR_VAR_2}を てにいれた!$"

gText_NoRoomLeftForAnother::
	.string "{JPN}ざんねん! {STR_VAR_2}を\nこれいじょう もてない…$"

gText_TheDecorWasTransferredToThePC::
	.string "{JPN}{STR_VAR_2}は パソコンに\nおくられた。$"
