gText_PkmnTransferredSomeonesPC::
	.string "{JPN}{STR_VAR_2}は だれかの パソコンに\nおくられた。\pボックス「{STR_VAR_1}」に\nはいりました。$"

gText_PkmnTransferredLanettesPC::
	.string "{JPN}{STR_VAR_2}は マサキの パソコンに\nおくられた。\pボックス「{STR_VAR_1}」に\nはいりました。$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "{JPN}だれかの パソコンの\nボックス「{STR_VAR_3}」は いっぱいでした。\p{STR_VAR_2}は ボックス「{STR_VAR_1}」に\nはいりました。$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "{JPN}マサキの パソコンの\nボックス「{STR_VAR_3}」は いっぱいでした。\p{STR_VAR_2}は ボックス「{STR_VAR_1}」に\nはいりました。$"

gText_NoMoreRoomForPokemon::
	.string "{JPN}ポケモンを あずける ばしょが ない!\pボックスが すべて いっぱいで\nこれいじょう あずけられない!$"

gText_NicknameThisPokemon::
	.string "{JPN}この {STR_VAR_1}に\nニックネームを つけますか?$"
