gText_WouldYouLikeToRestYourPkmn::
	.string "{JPN}ようこそ\nポケモンセンターへ。\pおつかれの ポケモンを\nげんきに いたします。\pポケモンを やすませますか?$"

gText_IllTakeYourPkmn::
	.string "{JPN}それでは ポケモンを\nすこしの あいだ おあずかりします。$"

gText_RestoredPkmnToFullHealth::
	.string "{JPN}おまたせしました。\pポケモンは すっかり\nげんきに なりました。$"

gText_WeHopeToSeeYouAgain::
	.string "{JPN}また おこし くださいませ!$"

gText_WelcomeCutShort::
	.string "{JPN}ようこそ\nポケモンセンターへ。\pおつかれの ポケモンを\nげんきに いたします。\pごようけんは…$"

gText_NoticesGoldCard::
	.string "{JPN}そ その カードは…\nまさか… ゴールドカード?!\pまあ きんいろが まぶしい!\nよっつの ほしが かがやいて います!\pシルバーカードの トレーナーさんは\nなんにんか みましたが {PLAYER}さん\lゴールドカードの トレーナーさんは\lはじめて です!\pでは {PLAYER}さん ぜひとも\nポケモンを やすませて ください!$"

gText_YouWantTheUsual::
	.string "{JPN}{PLAYER}さん おまちして いました!\nいつもの ように いたしますか?$"

gText_IllTakeYourPkmn2::
	.string "{JPN}それでは ポケモンを\nすこしの あいだ おあずかりします。$"

gText_ThankYouForWaiting::
	.string "{JPN}おまたせしました。$"

gText_WeHopeToSeeYouAgain2::
	.string "{JPN}また おこし くださいませ!$"
