gBirchDexRatingText_AreYouCurious::
	.string "{JPN}オダマキはかせ: おお {PLAYER}{KUN}!\pポケモンずかんの ぐあいが\nきに なるのかね?$"

gBirchDexRatingText_Cancel::
	.string "{JPN}ん? まだ しらべる ほどには\nポケモンを つかまえて いないな。$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "{JPN}ふむふむ…\pみつけた ポケモンが {STR_VAR_1}ひき\nつかまえた ポケモンが {STR_VAR_2}ひき…$"

gBirchDexRatingText_LessThan10::
	.string "{JPN}くさむらに もっと はいって\nポケモンを よく さがして みなさい。$"

gBirchDexRatingText_LessThan20::
	.string "{JPN}だいぶ なれて きた ようだね。\nだが ここからが たいへんだぞ。$"

gBirchDexRatingText_LessThan30::
	.string "{JPN}とくべつな ばしょにしか でない\nポケモンも いる。\lあきらめずに さがす ことだ。$"

gBirchDexRatingText_LessThan40::
	.string "{JPN}かずは もうすこし ほしいが\nずいぶん ずかんらしく\lなって きたね。$"

gBirchDexRatingText_LessThan50::
	.string "{JPN}なかなか いい ちょうしだ。\nこの ちょうしで がんばりなさい。$"

gBirchDexRatingText_LessThan60::
	.string "{JPN}つりざおは つかって いるかね?\nうみには ポケモンが たくさん いる。$"

gBirchDexRatingText_LessThan70::
	.string "{JPN}つかまえる だけでは なく\nしんかも させて みては どうかね?$"

gBirchDexRatingText_LessThan80::
	.string "{JPN}すばらしい ずかんに\nなりそうだ。\lそんな よかんが するよ。$"

gBirchDexRatingText_LessThan90::
	.string "{JPN}これだけ あつめたとは…\nきみの さいのうは たいしたものだ!$"

gBirchDexRatingText_LessThan100::
	.string "{JPN}サファリゾーンには いったかね?\pあそこでしか つかまえられない\nポケモンが いると きくよ。$"

gBirchDexRatingText_LessThan110::
	.string "{JPN}ついに 100しゅるいに\nとどいたね。\pみごとな ずかんだ!$"

gBirchDexRatingText_LessThan120::
	.string "{JPN}いわくだきを つかうと みつかる\nポケモンも いるかも しれん。$"

gBirchDexRatingText_LessThan130::
	.string "{JPN}ほかの ひとと こうかんすれば\nもっと ポケモンが あつまるぞ。$"

gBirchDexRatingText_LessThan140::
	.string "{JPN}トレーナーを こころから すきに なると\nしんかする ポケモンが いると\lきいた ことが ある。$"

gBirchDexRatingText_LessThan150::
	.string "{JPN}ホウエンちほうに こんなに たくさんの\nポケモンが いるとは\lしらなかったよ。$"

gBirchDexRatingText_LessThan160::
	.string "{JPN}ときには ポケモンが たいりょうに\nあらわれる ことも ある。\pそんな チャンスを\nのがさない ことだ。$"

gBirchDexRatingText_LessThan170::
	.string "{JPN}きみの ずかんを みれば ホウエンちほうの\nポケモンの ことが とても よく\lわかるように なって いる。$"

gBirchDexRatingText_LessThan180::
	.string "{JPN}きみは もう りっぱな\nポケモンはかせだと いっても\lいいくらいだ!$"

gBirchDexRatingText_LessThan190::
	.string "{JPN}ここまで そろえるとは\nきみは まさに プロだね!$"

gBirchDexRatingText_LessThan200::
	.string "{JPN}ずかんの かんせいまで\nあと すこしだ。\lわしには わかるぞ!$"

gBirchDexRatingText_DexCompleted::
	.string "{JPN}おめでとう!\nポケモンずかん かんせいだ!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "{JPN}ふむふむ…\nぜんこくで みると…\pみつけた ポケモンが {STR_VAR_1}ひき\nつかまえた ポケモンが {STR_VAR_2}ひき…$"
