Questionnaire_Text_FillOut::
	.string "{JPN}アンケートが ある。\nかいて みますか?$"

Questionnaire_Text_ThankYou::
	.string "{JPN}アンケートに おこたえ いただき\nありがとう ございました。\pいただいた ごいけんは これからの\nさんこうに させて いただきます。$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "{JPN}おや こんにちは!\nその ことばを しって いるのですね?\pという ことは ふしぎなおくりものを\nごぞんじ なのですね。\pこれから ふしぎなおくりものが\nとどく ように なりますよ!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "{JPN}レポートを かいたら ふしぎなおくりものが\nつかえる ように なります。$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "{JPN}おや こんにちは!\nその ことばを しって いるのですね?\pという ことは ふしぎイベントを\nごぞんじ なのですね。$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "{JPN}レポートを かいたら ふしぎイベントが\nつかえる ように なります。$"

MysteryGift_Text_TheresATicketForYou::
	.string "{JPN}ふしぎイベントシステムを\nごりよう ありがとう ございます。\p{PLAYER}さん ですね。\nあなたに チケットが とどいて います。$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "{JPN}ミナモシティの みなとで\nつかう もののようです。\pいちど ためして みては\nいかがでしょうか?$"
