	.align 2
gText_ConfirmSave::
	.string "{JPN}レポートを かきますか?$"

gText_AlreadySavedFile::
	.string "{JPN}すでに レポートが あります。\nうわがき しても いいですか?$"

gText_SavingDontTurnOff::
	.string "{JPN}レポートに かきこんで います…\nでんげんを きらないで ください。$"

gText_PlayerSavedGame::
	.string "{JPN}{PLAYER}は レポートに\nぼうけんの きろくを かきこんだ。$"

gText_DifferentSaveFile::
	.string "{JPN}けいこく!\pべつの ゲームの データが\nすでに ほぞん されて います。\pいま かきこむと そちらの ぼうけんは\nどうぐも ポケモンも すべて\lきえて しまいます。\pそれでも かきこんで\nうわがき しますか?$"

gText_SaveError::
	.string "{JPN}セーブに しっぱいしました。\pバックアップメモリを\nこうかん して ください。$"

gText_SavingDontTurnOffPower::
	.string "{JPN}レポートに かきこんで います…\nでんげんを きらないで ください。$"
