SecretBase_Text_Trainer0Intro:
	.string "{JPN}もう ひみつきちは つくった?\pここに きめるまで あちこち\nさがしまわったんだ。\pせっかくだから しょうぶ しない?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "{JPN}よし!\nいくよ!$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "{JPN}え?\nああ いまは むりなんだね…$"

SecretBase_Text_Trainer0Defeated::
	.string "{JPN}うわあ! つよすぎる!\nまけた ことは ないしょに してね!$"

SecretBase_Text_Trainer0PostBattle:
	.string "{JPN}わたしの ひみつきち どうかな?\nまた あした あそびに きてね。$"

SecretBase_Text_Trainer0PreChampion:
	.string "{JPN}もう ひみつきちは つくった?\pここに きめるまで あちこち\nさがしまわったんだ。\pゆっくり して いってね!$"

SecretBase_Text_Trainer5Intro:
	.string "{JPN}ひみつきちに できる ばしょは\nたくさん あるけど。\pぼくは ここが いちばん すきなんだ。\nいい ばしょだと おもわない?\pあ しょうぶ しない?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "{JPN}よし いくぞ!$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "{JPN}そう…\nいまは むりなんだね。$"

SecretBase_Text_Trainer5Defeated::
	.string "{JPN}うーん ぼくらの まけだ…\nでも だれにも いわないでよ!\lこれは ひみつだからね!$"

SecretBase_Text_Trainer5PostBattle:
	.string "{JPN}この あたりに きたら\nまた よって いってね。$"

SecretBase_Text_Trainer5PreChampion:
	.string "{JPN}ひみつきちに できる ばしょは\nたくさん あるけど。\pぼくは ここが いちばん すきなんだ。\nいい ばしょだと おもわない?$"

SecretBase_Text_Trainer1Intro:
	.string "{JPN}ここは にんきの ばしょでね。\nいつも ふさがって いるんだ。\pおや! きみも ここを ねらって いたのかい?\pよし ぼくに かてたら\nこの ばしょを ゆずって あげよう。$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "{JPN}よし!\nひみつきちを まもって みせる!$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "{JPN}あれ? そうなの?\nここには きょうみが ないのかい?$"

SecretBase_Text_Trainer1Defeated::
	.string "{JPN}もう だめだ!\nこうさん!$"

SecretBase_Text_Trainer1PostBattle:
	.string "{JPN}よし いつか ひっこす ときが きたら\nここは きみの ものだ!$"

SecretBase_Text_Trainer1PreChampion:
	.string "{JPN}ここは にんきの ばしょでね。\nいつも ふさがって いるんだ。\pあくのを ずっと まって いたんだ。\nやっと つかえる ように なったよ!$"

SecretBase_Text_Trainer6Intro:
	.string "{JPN}ぼくの ポケモンラボへ ようこそ。\pここで ひそかに しょうぶの けんきゅうを\nして いるんだ。\pぼくの つよさを みて みるかい?$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "{JPN}ぜんりょくで いくよ!$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "{JPN}そうか。\nでは また こんど!$"

SecretBase_Text_Trainer6Defeated::
	.string "{JPN}うーん まだまだ まなぶ ことが おおいな。\nもっと けんきゅう しないと。$"

SecretBase_Text_Trainer6PostBattle:
	.string "{JPN}しょうぶ ありがとう。\nまた あした きて くれよ。$"

SecretBase_Text_Trainer6PreChampion:
	.string "{JPN}ぼくの ポケモンラボへ ようこそ。\pここで ひそかに しょうぶの けんきゅうを\nして いるんだ。$"

SecretBase_Text_Trainer2Intro:
	.string "{JPN}おおきな やしきも いいけど\nこういう ばしょの ほうが すきなんだ。\pいろいろな ひとが たずねて くるからね。\pどうだい しょうぶ しないか?$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "{JPN}その いきだ!$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "{JPN}きが むいたら こえを かけて くれ!$"

SecretBase_Text_Trainer2Defeated::
	.string "{JPN}ああ! やられた!\nでも しょうぶは やっぱり たのしいな!$"

SecretBase_Text_Trainer2PostBattle:
	.string "{JPN}さて かざりや かぐを かいに\nいかないとな。\pひみつきちを みんなが たのしめる\nばしょに したいんだ。$"

SecretBase_Text_Trainer2PreChampion:
	.string "{JPN}おおきな やしきも いいけど\nこういう ばしょの ほうが すきなんだ。\pいろいろな ひとが たずねて くるからね。$"

SecretBase_Text_Trainer7Intro:
	.string "{JPN}かざりや かぐの かいものが\nだいすきなの。\pポケモンを そだてるのも\nおなじくらい すきよ。\pよければ わたしの ポケモンと\nしょうぶ して くれる?$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "{JPN}ありがとう。\nはじめましょうか?$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "{JPN}あら。\nざんねんだわ…$"

SecretBase_Text_Trainer7Defeated::
	.string "{JPN}まけを みとめるわ…$"

SecretBase_Text_Trainer7PostBattle:
	.string "{JPN}とても たのしかったわ!\nさあ かいものに いって こようかしら。$"

SecretBase_Text_Trainer7PreChampion:
	.string "{JPN}かざりや かぐの かいものが\nだいすきなの。\pポケモンを そだてるのも\nおなじくらい すきよ。$"

SecretBase_Text_Trainer3Intro:
	.string "{JPN}みつかりにくい ばしょに ひみつきちを\nつくる ひとも いるのよね。\lめだちたく ないのかしら?\pでも みつけて くれたんだから\nしょうぶ しない?$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "{JPN}かんたんには まけないわよ!$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "{JPN}あら… ここを さがして つかれちゃった?$"

SecretBase_Text_Trainer3Defeated::
	.string "{JPN}まいったわ…$"

SecretBase_Text_Trainer3PostBattle:
	.string "{JPN}あなたの ひみつきちは どこ?\nこんどは わたしが あそびに いくわ。$"

SecretBase_Text_Trainer3PreChampion:
	.string "{JPN}みつかりにくい ばしょに ひみつきちを\nつくる ひとも いるのよね。\lめだちたく ないのかしら?$"

SecretBase_Text_Trainer8Intro:
	.string "{JPN}かざりの あつめかたは いろいろ あると\nきいたわ。\pどちらが すてきな かざりや かぐを\nあつめられるか きょうそう しましょう!\pところで しょうぶ しない?$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "{JPN}ここは わたしの ひみつきち。\nまけられないわ!$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "{JPN}いつでも しょうぶ するわよ。$"

SecretBase_Text_Trainer8Defeated::
	.string "{JPN}え?\nいま まけたの?$"

SecretBase_Text_Trainer8PostBattle:
	.string "{JPN}かざりあつめでは まけないわ。\nまた あそびに きてね!$"

SecretBase_Text_Trainer8PreChampion:
	.string "{JPN}かざりの あつめかたは いろいろ あると\nきいたわ。\pどちらが すてきな かざりや かぐを\nあつめられるか きょうそう しましょう!$"

SecretBase_Text_Trainer4Intro:
	.string "{JPN}きに いった ばしょを みつけて\nすきな かざりで かざったんだ。\pすきな ポケモンを そだてて\nいっしょに つよく なる。\pそれが ぼくの やりかたさ。\nしょうぶ しないか?$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "{JPN}きみの じつりょくを みせて くれ!$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "{JPN}そういう きぶんじゃ ない ときも あるよね。$"

SecretBase_Text_Trainer4Defeated::
	.string "{JPN}きみの じつりょくが よく わかったよ。$"

SecretBase_Text_Trainer4PostBattle:
	.string "{JPN}おたがい もっと つよく なれる。\nがんばろう!$"

SecretBase_Text_Trainer4PreChampion:
	.string "{JPN}きに いった ばしょを みつけて\nすきな かざりで かざったんだ。\pすきな ポケモンを そだてて\nいっしょに つよく なる。\pまいにちが たのしいよ。$"

SecretBase_Text_Trainer9Intro:
	.string "{JPN}どんな かざりを もって いて どう\nかざって いるかで その ひとの\lセンスが よく わかるものだ。\lそう おもわないか?\pわたしの センスは どうかね?\nことばも でないかな?\pしょうぶの センスも みて みるかね?$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "{JPN}てかげんは しないぞ!$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "{JPN}いつでも わたしの スタイルを\nみせて あげよう。$"

SecretBase_Text_Trainer9Defeated::
	.string "{JPN}すばらしい さいのうだ!\nきみの ちからには かぎりが ないようだ…$"

SecretBase_Text_Trainer9PostBattle:
	.string "{JPN}わたしの スタイルは どうだったかね?\nこれからも みがきつづけるよ!$"

SecretBase_Text_Trainer9PreChampion:
	.string "{JPN}どんな かざりを もって いて どう\nかざって いるかで その ひとの\lセンスが よく わかるものだ。\lそう おもわないか?\pわたしの センスは どうかね?\nことばも でないかな?$"
