ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "{JPN}おくまで はいる つもりかい?\pしおのかけらと かいのかせきを\nもって きて くれないか?\pざいりょうさえ あれば\nいい ものを つくって やるよ。$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "{JPN}しおのかけらと かいのかせきを\nよっつずつ もって きて くれたら\lかいがらのすずを つくって やろう…\pざいりょうは まいにち\nてに はいるからな。$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "{JPN}おっ! しおのかけらと かいのかせき!\nかずも じゅうぶんだ!\pこれで かいがらのすずを\nつくって やろうか?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "{JPN}よし きまりだ! すぐに\nかいがらのすずを つくって やる。\p… … … … … … … …\n… … … … … … … …\pほら できたぞ!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "{JPN}ポケモンに もたせて やりな。\nきっと よろこぶ はずだ。\pなにしろ かいがらのすずの ねいろは…\nそりゃあ みごとな もんだ!\pざいりょうは まいにち てに はいるから\nまた つくって やれるぞ。$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "{JPN}そうか… そうかい…\nかいがらのすずを つくりたかったが…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "{JPN}つくって やっても バッグに\nあきが ないな。\pあきを つくってから\nかいがらのすずを とりに おいで。$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "{JPN}ここに しおのかけらが あったが\nいまは なにも ない。$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "{JPN}ここに かいのかせきが あったが\nいまは なにも ない。$"
