Route102_Text_CalvinIntro:
	.string "{JPN}ポケモンを つれて いるなら\nりっぱな ポケモントレーナー!\lわたしの しょうぶを ことわれないよ!$"

Route102_Text_CalvinDefeated:
	.string "{JPN}ああ まけた…\nもっと きたえて おくべきだった…$"

Route102_Text_CalvinPostBattle:
	.string "{JPN}ちょっと つよいなら\nさきに いって おいてよ!$"

Route102_Text_CalvinRegister:
	.string "{JPN}まえに あってから ずっと\nがんばって きたんだ。\pまた しょうぶ したいから ポケナビに\nとうろく して くれないかな?$"

Route102_Text_CalvinRegisterShort:
	.string "{JPN}また しょうぶ したいから ポケナビに\nとうろく して くれないかな?$"

Route102_Text_CalvinRematchIntro:
	.string "{JPN}きみに まけてから ひっしで\nポケモンを きたえて きた。\lしょうぶを ことわらせないよ!$"

Route102_Text_CalvinRematchDefeated:
	.string "{JPN}ああ まけた…\nきたえかたが まちがって いるのかな?$"

Route102_Text_CalvinRematchPostBattle:
	.string "{JPN}きみが つよく なるなら\nわたしも つよく なる。$"

Route102_Text_AllenIntro:
	.string "{JPN}トレーナーに なったばかり?\nおたがい しんまいだね!$"

Route102_Text_AllenDefeated:
	.string "{JPN}かてると おもって\nよんだのに…$"

Route102_Text_AllenPostBattle:
	.string "{JPN}まだ 1かいも かって いない…\nそろそろ かちたいなあ…$"

Route102_Text_RickIntro:
	.string "{JPN}ははっ めが あったね!\nむしポケモンで あいてに なるよ!$"

Route102_Text_RickDefeated:
	.string "{JPN}うっ のされた!$"

Route102_Text_RickPostBattle:
	.string "{JPN}トレーナーと めが あったら\nしょうぶ! それが ルール!$"

Route102_Text_TianaIntro:
	.string "{JPN}かちつづけて さいこうの トレーナーを\nめざすんだ。\pわたしの しゅっせに つきあって!$"

Route102_Text_TianaDefeated:
	.string "{JPN}きみの しゅっせを てつだって しまった…$"

Route102_Text_TianaPostBattle:
	.string "{JPN}かちあがるには もっと ポケモンを\nつかまえないと だめみたい。$"

Route103_Text_DaisyIntro:
	.string "{JPN}こころ やすらぐ かおりに\nひきよせられたの?$"

Route103_Text_DaisyDefeated:
	.string "{JPN}かおりに まどわされ なかったのね…$"

Route103_Text_DaisyPostBattle:
	.string "{JPN}アロマセラピーは かおりで こころを\nいやす ほうほうなの。$"

Route103_Text_AmyIntro:
	.string "{JPN}アミ: わたしは アミ。\nこちらは いもうとの リブ。\lふたりで たたかうの!$"

Route103_Text_AmyDefeated:
	.string "{JPN}アミ: あーあ まけちゃった。$"

Route103_Text_AmyPostBattle:
	.string "{JPN}アミ: トレーナー ふたりを あいてに\nするときは いろいろ かんがえないと\lいけないのよ。$"

Route103_Text_AmyNotEnoughPokemon:
	.string "{JPN}アミ: あら ポケモンが 1ぴきしか\nいないのね。\lそれでは しょうぶに ならないわ。$"

Route103_Text_LivIntro:
	.string "{JPN}リブ: わたしたち ひとつの チームで\nたたかうの。$"

Route103_Text_LivDefeated:
	.string "{JPN}リブ: ああ まけちゃった おねえちゃん…$"

Route103_Text_LivPostBattle:
	.string "{JPN}リブ: おねえちゃんとは ぴったり\nあうのに…\pそれでも まけちゃった…$"

Route103_Text_AmyLivRegister:
	.string "{JPN}リブ: ほんとは もっと つよいのよ…\nほんとだもん! こんどは みせて あげる!$"

Route103_Text_LivNotEnoughPokemon:
	.string "{JPN}リブ: わたしたちと しょうぶ するなら\nポケモンが 2ひき いるのよ!\lそうじゃないと ずるいわ!$"

Route103_Text_AmyRematchIntro:
	.string "{JPN}アミ: わたしは アミ。\nこちらは いもうとの リブ。\lふたりで たたかうの!$"

Route103_Text_AmyRematchDefeated:
	.string "{JPN}アミ: ああ もう!\nまた かてなかった…$"

Route103_Text_AmyRematchPostBattle:
	.string "{JPN}アミ: トレーナー ふたりを あいてに\nするときは いろいろ かんがえないと\lいけないのよ。$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "{JPN}アミ: あら ポケモンが 1ぴきしか\nいないのね。\lそれでは しょうぶに ならないわ。$"

Route103_Text_LivRematchIntro:
	.string "{JPN}リブ: わたしたち ひとつの チームで\nたたかうの。$"

Route103_Text_LivRematchDefeated:
	.string "{JPN}リブ: ああ また まけちゃった…\nおねえちゃん…$"

Route103_Text_LivRematchPostBattle:
	.string "{JPN}リブ: おねえちゃんとは ぴったり\nあうのに…\pどうして また まけたの?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "{JPN}リブ: わたしたちと しょうぶ するなら\nポケモンが 2ひき いるのよ!\lそうじゃないと ずるいわ!$"

Route103_Text_AndrewIntro:
	.string "{JPN}ぐあ! つりいとが からまった!\nいらいらして きたぞ!\lよし しょうぶだ!$"

Route103_Text_AndrewDefeated:
	.string "{JPN}ぐあ! まけた!\nますます いらいら するぞ!$"

Route103_Text_AndrewPostBattle:
	.string "{JPN}ぐぬぬ まだ はらが たつ…\nぐぬぬぬ…$"

Route103_Text_MiguelIntro:
	.string "{JPN}わたしの ポケモン とっても かわいいの!\nえんりょ しないで みて!$"

Route103_Text_MiguelDefeated:
	.string "{JPN}ああ そんな!\nかわいい わたしの ポケモン!$"

Route103_Text_MiguelPostBattle:
	.string "{JPN}わたしの ポケモンは ひんしに なっても\nかわいいの!$"

Route103_Text_MiguelRegister:
	.string "{JPN}また わたしの かわいい ポケモンを\nみに きて もらうんだから!$"

Route103_Text_MiguelRematchIntro:
	.string "{JPN}あら! わたしの かわいい ポケモンが\nもっと かわいく なったの!$"

Route103_Text_MiguelRematchDefeated:
	.string "{JPN}ああ!\nかわいい わたしの ポケモン!$"

Route103_Text_MiguelRematchPostBattle:
	.string "{JPN}いっしょに いる ときが ながいほど\nポケモンは かわいく なるの。$"

Route103_Text_PeteIntro:
	.string "{JPN}これくらいの きょりなら…\nおよいだら いいのに!$"

Route103_Text_PeteDefeated:
	.string "{JPN}やるじゃない!$"

Route103_Text_PetePostBattle:
	.string "{JPN}ああ きみの きもちが\nわかったわ。\pそんなに たよれる ポケモンが いたら わたしも\nなみのり したく なるもの!$"

Route103_Text_IsabelleIntro:
	.string "{JPN}まえを みて!\nぶつかっちゃう!$"

Route103_Text_IsabelleDefeated:
	.string "{JPN}うーん…$"

Route103_Text_IsabellePostBattle:
	.string "{JPN}およぎが へたで れんしゅう してたの…\nぶつかりそうに なって ごめんね。$"

Route103_Text_RhettIntro:
	.string "{JPN}うわっ!\nこんな せまい ところに よく きたな?$"

Route103_Text_RhettDefeated:
	.string "{JPN}うわっ!\nこの こ やるな!$"

Route103_Text_RhettPostBattle:
	.string "{JPN}こういう せまい ところが\nすきなのか?$"

Route103_Text_MarcosIntro:
	.string "{JPN}おれの ギターの ねに ひかれたか?$"

Route103_Text_MarcosDefeated:
	.string "{JPN}ひとりの ステージが だいなしだ…$"

Route103_Text_MarcosPostBattle:
	.string "{JPN}ひとの すくない ところで ひいて いたのに\nファンが たくさん あつまって きた。\lうれしいね。\pふふん プロに なろうかな。$"

Route104_Text_GinaIntro:
	.string "{JPN}ジナ: さあ ポケモンで\nしょうぶよ!$"

Route104_Text_GinaDefeat:
	.string "{JPN}ジナ: まけるのは くやしい!$"

Route104_Text_GinaPostBattle:
	.string "{JPN}ジナ: あなた つよいのね!\nもっと きたえないと!$"

Route104_Text_GinaNotEnoughMons:
	.string "{JPN}ジナ: あら? ポケモンが 1ぴきだけ?\nそれじゃ しょうぶ しないわ。\pポケモンが 1ぴきだと さびしいもの。\nかわいそうよ。$"

Route104_Text_MiaIntro:
	.string "{JPN}ミア: わたしたち ふたごだから\nいっしょに しょうぶ するの。$"

Route104_Text_MiaDefeat:
	.string "{JPN}ミア: ふたりで たたかったのに\nどっちも まけちゃった…$"

Route104_Text_MiaPostBattle:
	.string "{JPN}ミア: もっと ポケモンを きたえて\nあなたみたいに つよく なるわ。$"

Route104_Text_MiaNotEnoughMons:
	.string "{JPN}ミア: わたしたちと しょうぶ したいの?\pポケモンが 2ひき いないと\nだめよ。 わたしたちのほうが\lつよいもの!$"

Route104_Text_IvanIntro:
	.string "{JPN}かくす ことは ない。\nおれは みずポケモンの めいじんだ!\pん?\nおれを しらないのか?$"

Route104_Text_IvanDefeat:
	.string "{JPN}そこそこ やれると おもって いたが\nそうでも なかったか… うう…$"

Route104_Text_IvanPostBattle:
	.string "{JPN}つりに むちゅうに なりすぎた。\nポケモンを そだてるのを わすれて いた…$"

Route104_Text_BillyIntro:
	.string "{JPN}すなはまに あしあとを のこすのが\nたのしいの!$"

Route104_Text_BillyDefeat:
	.string "{JPN}わあ! くつに すなが はいった!\nじゃりじゃり する!$"

Route104_Text_BillyPostBattle:
	.string "{JPN}どこにでも あしあとを のこしたいけど\nすぐに きえちゃうのよね…\lざんねん。$"

Route104_Text_HaleyIntro:
	.string "{JPN}しようかな…\nやめようかな?\pよし しょうぶ するわ!$"

Route104_Text_HaleyDefeat:
	.string "{JPN}しょうぶ しなければ よかった…$"

Route104_Text_HaleyPostBattle:
	.string "{JPN}まよった とき ほかの ひとに\nきめさせると どんな けっかに なっても\lこうかい する ものよ。\lおぼえて おいてね。$"

Route104_Text_HaleyRegister1:
	.string "{JPN}あなた つよいけど ポケナビに\nとうろく しようかしら…\lやめようかしら…\pよし とうろく するわ!$"

Route104_Text_HaleyRegister2:
	.string "{JPN}あなた つよいけど ポケナビに\nとうろく しようかしら…\lやめようかしら…\pよし とうろく するわ!$"

Route104_Text_HaleyRematchIntro:
	.string "{JPN}さあ しょうぶ しましょう!$"

Route104_Text_HaleyRematchDefeat:
	.string "{JPN}ああ…\nかてると おもったのに…$"

Route104_Text_HaleyPostRematch:
	.string "{JPN}じぶんで しょうぶを えらんだから\nまけも うけいれるわ。\pでも やっぱり くやしい!$"

Route104_Text_WinstonIntro:
	.string "{JPN}ええ しょうぶを うけて あげましょう。\nおかねは たくさん あるのよ。$"

Route104_Text_WinstonDefeat:
	.string "{JPN}どうして かてなかったの?$"

Route104_Text_WinstonPostBattle:
	.string "{JPN}おかねで かえない ものも あるのね。\nポケモンが そうだわ…$"

Route104_Text_WinstonRegister1:
	.string "{JPN}あら?\nポケナビを もって いるのね。\pよろこんで とうろく するわ。\nおかねなら たっぷり あるもの。$"

Route104_Text_WinstonRegister2:
	.string "{JPN}あら?\nポケナビを もって いるのね。\pよろこんで とうろく するわ。\nおかねなら たっぷり あるもの。$"

Route104_Text_WinstonRematchIntro:
	.string "{JPN}あなたに まけてから ポケモンに ついて\nいろいろ まなんだのよ。$"

Route104_Text_WinstonRematchDefeat:
	.string "{JPN}また まけたの?\nどうして かてないのかしら?$"

Route104_Text_WinstonPostRematch:
	.string "{JPN}おかねは ありあまる ほど あるのに\nポケモンでは かてない…\pポケモンの せかいは おくが ふかいわ…$"

Route104_Text_CindyIntro:
	.string "{JPN}わたしたち であう うんめい だったのね。\nしょうぶを おねがい できるかしら?$"

Route104_Text_CindyDefeat:
	.string "{JPN}あらまあ!$"

Route104_Text_CindyPostBattle:
	.string "{JPN}「こんにちは」は「さようなら」の はじまり。\nまた あえると いいわね。$"

Route104_Text_CindyRegister1:
	.string "{JPN}こんにちは また あったわね。\pひかれあって いるみたい。 おたがいの\nポケナビに とうろく しましょう。$"

Route104_Text_CindyRegister2:
	.string "{JPN}ひかれあって いる\nきねんに\pおたがいの ポケナビに とうろく\nしましょう。$"

Route104_Text_CindyRematchIntro:
	.string "{JPN}こんにちは また あったわね。\nしょうぶを おねがい できるかしら?$"

Route104_Text_CindyRematchDefeat:
	.string "{JPN}あらまあ…\nせいいっぱい やったのだけれど…$"

Route104_Text_CindyPostRematch:
	.string "{JPN}「こんにちは」は「さようなら」の はじまり。\nまた あえると いいわね。$"

Route104_Text_DarianIntro:
	.string "{JPN}つよそうな ポケモンを つりあげたぞ!\pなにか ふしぎな かんじが する!\nきっと つよいはずだ そうにちがいない!$"

Route104_Text_DarianDefeat:
	.string "{JPN}なんだと…$"

Route104_Text_DarianPostBattle:
	.string "{JPN}おい コイキング なまえまけ して\nいるぞ?$"

Route105_Text_FosterIntro:
	.string "{JPN}この あたりに ふしぎな いわが\nあるらしいんだ。\lなにか しらないか?$"

Route105_Text_FosterDefeated:
	.string "{JPN}いわの ことばかり かんがえて いて\nポケモンが よわいままだった…$"

Route105_Text_FosterPostBattle:
	.string "{JPN}いい いわは なんじかん ながめて いても\nあきないんだ。$"

Route105_Text_LuisIntro:
	.string "{JPN}ふう! こどもが おぼれて いるのかと\nしんぱい したよ。\pだいじょうぶ そうだね しょうぶでも\nどうかな?$"

Route105_Text_LuisDefeated:
	.string "{JPN}ごぼ… ごぼ…$"

Route105_Text_LuisPostBattle:
	.string "{JPN}おぼれた ときは かたほうの うでを\nはまべに むけて ふるんだよ。$"

Route105_Text_DominikIntro:
	.string "{JPN}まっさおな うみを およぐ…\nさいこうの きぶんだ!$"

Route105_Text_DominikDefeated:
	.string "{JPN}まけた…\nきぶんが しずむよ…$"

Route105_Text_DominikPostBattle:
	.string "{JPN}うみは なぜ あおいのか?\pカイナの はくぶつかんで ならったのに\nわすれて しまった。$"

Route105_Text_BeverlyIntro:
	.string "{JPN}みずの なかだと からだが かるいの。\nやせた みたい!$"

Route105_Text_BeverlyDefeated:
	.string "{JPN}うかんで いる…$"

Route105_Text_PostBattle:
	.string "{JPN}みずの なかでは たいじゅうが\n10ぶんの1に なるのよ。\pということは わたしは…\nおっと たいじゅうは ないしょ!$"

Route105_Text_ImaniIntro:
	.string "{JPN}あおい あおい そら…\nひろい うみ…\lなんて おだやかなの…$"

Route105_Text_ImaniDefeated:
	.string "{JPN}のんびり して いたら まけたわ!$"

Route105_Text_ImaniPostBattle:
	.string "{JPN}いっしょに いると おちつくって\nいわれたいの。 うふふ。$"

Route105_Text_AndresIntro:
	.string "{JPN}うみは わたしたちに ひみつを\nかくして いると おもうの。$"

Route105_Text_AndresDefeated:
	.string "{JPN}ええ…\nしょうぶは にがてなの…$"

Route105_Text_AndresPostBattle:
	.string "{JPN}せかいの うみには まだ たくさんの\nひみつが あるはず。\pぜんぶ みつけて みせるわ!$"

Route105_Text_AndresRegister:
	.string "{JPN}あら? こんなに よわいのに\nポケナビに とうろく して くれるの?$"

Route105_Text_AndresRematchIntro:
	.string "{JPN}よわいって いったでしょう…\nほんとうに いいの?$"

Route105_Text_AndresRematchDefeated:
	.string "{JPN}ええ…\nかてるとは おもって いなかったわ。$"

Route105_Text_AndresRematchPostBattle:
	.string "{JPN}しょうぶは よわくても たんけんへの じょうねつは\nまけないわ。\pせかいじゅうの うみを\nたびするの!$"

Route105_Text_JosueIntro:
	.string "{JPN}およいで つかれた。\nなれて いないんだ。\pきぶんてんかんに しょうぶ しよう!$"

Route105_Text_JosueDefeated:
	.string "{JPN}うみで しょうぶ したから まけたんだ。$"

Route105_Text_JosuePostBattle:
	.string "{JPN}うん ぼくには うみより そらの ほうが\nあって いる みたいだ。$"

Route106_Text_ElliotIntro:
	.string "{JPN}つりは うみと かわ どちらが\nすき?$"

Route106_Text_ElliotDefeated:
	.string "{JPN}ふかうみの つりの ように\nみごとに まけたよ!$"

Route106_Text_ElliotPostBattle:
	.string "{JPN}うみでも かわでも つりは さいこうだ。\nきみも そう おもうだろう?\lちがうかい?$"

Route106_Text_ElliotRegister:
	.string "{JPN}つりも いいが しょうぶも いい。\nよければ また あわないか?$"

Route106_Text_ElliotRematchIntro:
	.string "{JPN}つりで ポケモンを たくさん つかまえた。\nみごとな しょうぶを みせて やろう!$"

Route106_Text_ElliotRematchDefeated:
	.string "{JPN}また みごとに まけた!$"

Route106_Text_ElliotRematchPostBattle:
	.string "{JPN}かっても まけても ポケモンは さいこうだ!\nきみも そう おもうだろう?$"

Route106_Text_NedIntro:
	.string "{JPN}トイレに いきたく なったら\nみんな どう するんだ?\pトイレの あいだに おおものが かかったら\nこまる。 だから いけないんだ…$"

Route106_Text_NedDefeated:
	.string "{JPN}トイレを がまん して いたから\nまけた…$"

Route106_Text_NedPostBattle:
	.string "{JPN}まずい! おおものが かかる きが\nする!$"

Route106_Text_DouglasIntro:
	.string "{JPN}はははっ! はしるのは にがてだが\nみずの なかなら つかまらないぞ!$"

Route106_Text_DouglasDefeated:
	.string "{JPN}まいった!$"

Route106_Text_DouglasPostBattle:
	.string "{JPN}およぎの きょうそうなら まけないのに…$"

Route106_Text_KylaIntro:
	.string "{JPN}うみは おれの にわだ。 こどもだからと\nてかげんは しないぞ!$"

Route106_Text_KylaDefeated:
	.string "{JPN}もしかして てかげん\nしたのか?$"

Route106_Text_KylaPostBattle:
	.string "{JPN}なみに ゆられて ただよう…\nすきなの! あなたも やってみたら?$"

Route107_Text_DarrinIntro:
	.string "{JPN}ふわあ…\pなみに ゆられて いるうちに\nねむって しまった みたい。$"

Route107_Text_DarrinDefeated:
	.string "{JPN}あはは まけちゃった…\nひとねむり しようかしら…$"

Route107_Text_DarrinPostBattle:
	.string "{JPN}なみに ゆられて うかぶのは\nふかふかの きもちいい ベッドで\lねむって いるみたい。$"

Route107_Text_TonyIntro:
	.string "{JPN}うみは わたしの にわの ような もの。\nしょうぶ しましょう!$"

Route107_Text_TonyDefeated:
	.string "{JPN}ホームで まけるなんて…\nショックだわ!$"

Route107_Text_TonyPostBattle:
	.string "{JPN}ゆめを むねに うみを\nおよぐ…\pうたよ! さて もう ひとおよぎ\nしてくるわ。$"

Route107_Text_TonyRegister:
	.string "{JPN}ほねの ずいまで おどろいたわ!\nわすれられない ように…$"

Route107_Text_TonyRematchIntro:
	.string "{JPN}ひろい うみを およいで\nポケモンが つよく なったの!$"

Route107_Text_TonyRematchDefeated:
	.string "{JPN}おどろいたわ!\pポケモンは つよく なったのに\nトレーナーの わたしは よわいまま!$"

Route107_Text_TonyRematchPostBattle:
	.string "{JPN}しょうぶで まなんだ ことが トレーナーを\nつよく するの。\lなみが おしえて くれたわ。$"

Route107_Text_DeniseIntro:
	.string "{JPN}ムロタウンって ちいさな まちを\nしって いる?$"

Route107_Text_DeniseDefeated:
	.string "{JPN}やだ もう!$"

Route107_Text_DenisePostBattle:
	.string "{JPN}ムロタウンの ホールで へんな ことばが\nはやって いるのよ。$"

Route107_Text_BethIntro:
	.string "{JPN}しょうぶ したいの?\nいいわよ おつきあい するわ!$"

Route107_Text_BethDefeated:
	.string "{JPN}あなたには およばなかったわ。$"

Route107_Text_BethPostBattle:
	.string "{JPN}あなたは これからも つよく なりそうね。\nわたしも がんばるわ!$"

Route107_Text_LisaIntro:
	.string "{JPN}リサ: きょうだいで しょうぶを\nいどむわ!$"

Route107_Text_LisaDefeated:
	.string "{JPN}リサ: すごい。\nつよさの けたが ちがうわ。$"

Route107_Text_LisaPostBattle:
	.string "{JPN}リサ: いっしょに うみへ いく ともだちは\nいるの?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "{JPN}リサ: しょうぶ するなら ポケモンを\nもっと つれて きて。$"

Route107_Text_RayIntro:
	.string "{JPN}レイ: ねえさんと いつも ポケモンで\nしょうぶ してるんだ。\pいつも まけるけど ふたりなら\nきみに かてる!$"

Route107_Text_RayDefeated:
	.string "{JPN}レイ: うわあ ぼくらより ずっと\nうえだ!$"

Route107_Text_RayPostBattle:
	.string "{JPN}レイ: この ポケモンは ねえさんに\nもらったんだ。 そだてて いまでは\lたいせつな あいぼうだよ!$"

Route107_Text_RayNotEnoughPokemon:
	.string "{JPN}レイ: しょうぶ するなら ポケモンを\nもっと つれて きてよ!$"

Route107_Text_CamronIntro:
	.string "{JPN}トライアスロンの とちゅうだけど\nぜんぜん つかれて いないぞ!$"

Route107_Text_CamronDefeated:
	.string "{JPN}つかれた…$"

Route107_Text_CamronPostBattle:
	.string "{JPN}このあと まだ すいえいと ランニングが\nのこって いる。\pだいじょうぶ かな?$"

Route108_Text_JeromeIntro:
	.string "{JPN}せかいの ななつの うみを およぐのが\nゆめなの!$"

Route108_Text_JeromeDefeated:
	.string "{JPN}これじゃ ななつの うみは\nおよげないわ…$"

Route108_Text_JeromePostBattle:
	.string "{JPN}うみの ポケモンと あそぶのも\nすいえいの たのしみ!$"

Route108_Text_MatthewIntro:
	.string "{JPN}おーい きみも すてられぶねに\nいくのかい?$"

Route108_Text_MatthewDefeated:
	.string "{JPN}しずむ!\nごぼ… ごぼ…$"

Route108_Text_MatthewPostBattle:
	.string "{JPN}あの すてられぶねの なかに はいる\nひとも いるらしいよ。$"

Route108_Text_TaraIntro:
	.string "{JPN}うそつきの かれしが みずぎが にあうって\nいったのよ…$"

Route108_Text_TaraDefeated:
	.string "{JPN}ああ もう!$"

Route108_Text_TaraPostBattle:
	.string "{JPN}うそでも にあうって いわれるのは\nうれしいの…\lおんなごころは ふくざつなのよ…$"

Route108_Text_MissyIntro:
	.string "{JPN}うみが だいすき!\nおよぐと なやみを わすれられるの!$"

Route108_Text_MissyDefeated:
	.string "{JPN}しょうぶに まけると ストレスが\nたまる!$"

Route108_Text_MissyPostBattle:
	.string "{JPN}ストレスは およいで はっさん!\nけんこうに いいのよ!$"

Route108_Text_CoryIntro:
	.string "{JPN}みずタイプの ポケモンが すき。\nほかの ポケモンも すきよ!$"

Route108_Text_CoryDefeated:
	.string "{JPN}わあん! まけた!\nわあん! わあん!$"

Route108_Text_CoryPostBattle:
	.string "{JPN}さけぶと すっきり する!\nげんきが でるの!$"

Route108_Text_CoryRegister:
	.string "{JPN}つよい トレーナーも だいすき!\nポケナビに とうろく して!$"

Route108_Text_CoryRematchIntro:
	.string "{JPN}かっても まけても うみでの しょうぶは だいすき!$"

Route108_Text_CoryRematchDefeated:
	.string "{JPN}わあん! また まけた!\nわあん! わあん!$"

Route108_Text_CoryRematchPostBattle:
	.string "{JPN}こまった ときは うみに むかって\nさけんで みて!$"

Route108_Text_CarolinaIntro:
	.string "{JPN}わたしの ポケモンが じまんなの。\nすばやい しょうぶを みせて あげる!$"

Route108_Text_CarolinaDefeated:
	.string "{JPN}ぜんぜん かわいく なかったわ。$"

Route108_Text_CarolinaPostBattle:
	.string "{JPN}こうして うみに いるんだから\nピンクの ひらひらした みずぎも いいかも…$"

Route109_Text_DavidIntro:
	.string "{JPN}ふん! この きたえた ふっきんを みろ!\nこれが われた はらと いう ものだ!$"

Route109_Text_DavidDefeated:
	.string "{JPN}あいたっ!\nしくじった!$"

Route109_Text_DavidPostBattle:
	.string "{JPN}ふん!\pきたえた ふっきんと ポケモンの しょうぶは\nかんけいが なかったか!$"

Route109_Text_AliceIntro:
	.string "{JPN}ひやけどめは ちゃんと ぬって\nいる?$"

Route109_Text_AliceDefeated:
	.string "{JPN}いたた いたた!$"

Route109_Text_AlicePostBattle:
	.string "{JPN}ほおが いちばん やけやすいのよ!$"

Route109_Text_HueyIntro:
	.string "{JPN}せかいじゅうの みなとに よったが\nカイナが いちばんだ。$"

Route109_Text_HueyDefeated:
	.string "{JPN}きみが いちばんだ!$"

Route109_Text_HueyPostBattle:
	.string "{JPN}さいこうの みなとに さいこうの\nトレーナーが いた…$"

Route109_Text_EdmondIntro:
	.string "{JPN}うっぷ…\nしょうぶ? おれと?$"

Route109_Text_EdmondDefeated:
	.string "{JPN}うっ おおおおお…\nうっぷ…$"

Route109_Text_EdmondPostBattle:
	.string "{JPN}ふだんは もっと つよいんだ!\nふなよいが ひどくて…\pふなのりなのに…$"

Route109_Text_RickyIntro:
	.string "{JPN}のどが かわいた… かいはまハウスで\nソーダすいでも のみたいな…$"

Route109_Text_RickyDefeated:
	.string "{JPN}うーん…$"

Route109_Text_RickyPostBattle:
	.string "{JPN}はらが へって きた… うきわが おおきな\nドーナツに みえる…$"

Route109_Text_RickyRegister:
	.string "{JPN}のどが かわいて いない ときに\nまた しょうぶ して くれるかい?$"

Route109_Text_RickyRematchIntro:
	.string "{JPN}はらぺこだが しょうぶ するくらいの\nげんきは あるぞ!$"

Route109_Text_RickyRematchDefeated:
	.string "{JPN}まけた…\nはらが へって いたからだ…$"

Route109_Text_RickyRematchPostBattle:
	.string "{JPN}はまべで たべると なんでも\nすこし おいしく かんじるの。$"

Route109_Text_LolaIntro:
	.string "{JPN}ビーチパラソルって おおきな はなに\nみえない?$"

Route109_Text_LolaDefeated:
	.string "{JPN}ママー!$"

Route109_Text_LolaPostBattle:
	.string "{JPN}そらから はまべを みたら\nおおきな はなばたけに みえるはず!$"

Route109_Text_LolaRegister:
	.string "{JPN}わたし?\nまいにち ここに いるわ!$"

Route109_Text_LolaRematchIntro:
	.string "{JPN}もう まけないわ!\nうきわが あるんだから!$"

Route109_Text_LolaRematchDefeated:
	.string "{JPN}ママー!$"

Route109_Text_LolaRematchPostBattle:
	.string "{JPN}うきわが あると わたしも ポケモンも\nかわいさが ぐんと あがるの!$"

Route109_Text_AustinaIntro:
	.string "{JPN}うきわが ないと およげないけど\nポケモンでは まけないわ!$"

Route109_Text_AustinaDefeated:
	.string "{JPN}うきわが あるから\nまけたのかしら?$"

Route109_Text_AustinaPostBattle:
	.string "{JPN}うきわは おしゃれの ひとつ。\nこれが ないと でられないの。$"

Route109_Text_GwenIntro:
	.string "{JPN}ねえ おおきい トレーナー。\nしょうぶ して くれる?$"

Route109_Text_GwenDefeated:
	.string "{JPN}わあ つよいんだね。$"

Route109_Text_GwenPostBattle:
	.string "{JPN}どうやって そんなに つよく なったの?$"

Route109_Text_CarterIntro:
	.string "{JPN}わははは! おれさまが おおものを\nつりあげて やるぜ!$"

Route109_Text_CarterDefeated:
	.string "{JPN}おれさま いっぴき にがした…$"

Route109_Text_CarterPostBattle:
	.string "{JPN}おれさまが みるに きみは おおものだ。\nいや これから おおものに なる!$"

Route109_Text_PaulIntro:
	.string "{JPN}ポール: ああ しらけるな。\pふたりの たいせつな じかんを\nじゃま しないで ほしいな。$"

Route109_Text_PaulDefeated:
	.string "{JPN}ポール: まあ こうさん だね。$"

Route109_Text_PaulPostBattle:
	.string "{JPN}ポール: ここに いる ことは\nだれにも いわないで くれよ。\lふたりだけの せかいなんだ!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "{JPN}ポール: ぼくらは ふかく あいしあって いる。\nだから ポケモンも いっしょに\lたたかわせるのさ。$"

Route109_Text_MelIntro:
	.string "{JPN}メル: わたしたち ラブラブなの。\nこの あつさは ホウエンじゅうに とどくわ!$"

Route109_Text_MelDefeated:
	.string "{JPN}メル: まけちゃった わたしの せいね!\nポールに きらわれちゃう!$"

Route109_Text_MelPostBattle:
	.string "{JPN}メル: ねえ ポール おこってる?\nおこらないで。$"

Route109_Text_MelNotEnoughPokemon:
	.string "{JPN}メル: わたしたち ほんとうに\nあいしあって いるの。 だから ポケモンも\lいっしょに たたかわせるのよ。$"

Route109_Text_ChandlerIntro:
	.string "{JPN}じゃーん! みて?\nぼくの うきわ まんまるだよ!$"

Route109_Text_ChandlerDefeated:
	.string "{JPN}ああ ああ!\nざんねん!$"

Route109_Text_ChandlerPostBattle:
	.string "{JPN}まんまるの うきわを みせて\nあげたのに…$"

Route109_Text_HaileyIntro:
	.string "{JPN}およげないから およぐ まねを して\nいるの。$"

Route109_Text_HaileyDefeated:
	.string "{JPN}やっぱり!\nかてるとは おもって いなかったわ。$"

Route109_Text_HaileyPostBattle:
	.string "{JPN}およげるように なったら ポケモンも\nつよく なる きが するの。$"

Route109_Text_ElijahIntro:
	.string "{JPN}おれさまの ような マッチョには\nこういう ポケモンが ぴったりだ!$"

Route109_Text_ElijahDefeated:
	.string "{JPN}まけても かっこいい だろう?$"

Route109_Text_ElijahPostBattle:
	.string "{JPN}おれさまの ような マッチョには\nみなとが にあうんだ!\pカイナへ いくと するか。$"

Route110_Text_JacobIntro:
	.string "{JPN}うわっ あぶない!\n じてんしゃレースに なれて いないな。$"

Route110_Text_JacobDefeated:
	.string "{JPN}うわっ!\nブレーキが きかない!$"

Route110_Text_JacobPostBattle:
	.string "{JPN}パンクや ブレーキの ふぐあいは\nおおけがの もとだ!\lじてんしゃは よく てんけん しよう!$"

Route110_Text_AnthonyIntro:
	.string "{JPN}よお きみ!\nおれの スピードに ついてこられるか?$"

Route110_Text_AnthonyDefeated:
	.string "{JPN}はでに ころんだ!$"

Route110_Text_AnthonyPostBattle:
	.string "{JPN}はやさだけでは ポケモンで かてないか。\nかんがえなおさないとな…$"

Route110_Text_BenjaminIntro:
	.string "{JPN}じてんしゃが はやくても あわてるなよ!$"

Route110_Text_BenjaminDefeated:
	.string "{JPN}ポケモンの しょうぶでも\nあわてては いけないな…$"

Route110_Text_BenjaminPostBattle:
	.string "{JPN}あわてる ことも あせる ことも ない。\nゆっくり いこう。 じかんは たっぷりある。$"

Route110_Text_BenjaminRegister:
	.string "{JPN}あせらず こつこつ いくよ。\nその きが あったら こえを かけてくれ。$"

Route110_Text_BenjaminRematchIntro:
	.string "{JPN}すこし いそぎすぎでは ないか?\nおちついて しょうぶ しよう。$"

Route110_Text_BenjaminRematchDefeated:
	.string "{JPN}あわてなかったのに まけたな…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "{JPN}あわてる ことも あせる ことも ない。\nゆっくり いこう。 じかんは たっぷりある。$"

Route110_Text_AbigailIntro:
	.string "{JPN}トライアスロンは とても きびしい。\pすいえい じてんしゃ ランニングの\n3つを こなさないと いけないんだ。$"

Route110_Text_AbigailDefeated:
	.string "{JPN}ポケモンの しょうぶも きびしいな!$"

Route110_Text_AbigailPostBattle:
	.string "{JPN}つかれたから やすむよ。\nちゃんと やすむのも たいせつだ。$"

Route110_Text_AbigailRegister:
	.string "{JPN}きみの ことが きに いった!\nじてんしゃロードで また しょうぶ しよう。$"

Route110_Text_AbigailRematchIntro:
	.string "{JPN}じてんしゃに のりながらの しょうぶも\nいい ものだろう?$"

Route110_Text_AbigailRematchDefeated:
	.string "{JPN}すごい…\nどうして そんなに つよいんだ?$"

Route110_Text_AbigailRematchPostBattle:
	.string "{JPN}きろくを ねらって いたのかい?\pじゃま したなら ごめんよ!$"

Route110_Text_JasmineIntro:
	.string "{JPN}やすまずに こぎつづけて いる。\nふとももが いわの ようだ!$"

Route110_Text_JasmineDefeated:
	.string "{JPN}あしが つらないか しんぱいだ…$"

Route110_Text_JasminePostBattle:
	.string "{JPN}おや ジムバッジを もって いるのか?\nどうりで つよいわけだ!$"

Route110_Text_EdwardIntro:
	.string "{JPN}あなたの かんがえは よんで いる!\nまける はずが ない!$"

Route110_Text_EdwardDefeated:
	.string "{JPN}じぶんの まけは よめなかった!$"

Route110_Text_EdwardPostBattle:
	.string "{JPN}あなたの みらいが みえる…\pうむ…\nまばゆい ひかりが みえる…$"

Route110_Text_JaclynIntro:
	.string "{JPN}あははは!\nふしぎな ちからで まどわせて あげる!$"

Route110_Text_JaclynDefeated:
	.string "{JPN}ふしぎと まけて しまったわ!$"

Route110_Text_JaclynPostBattle:
	.string "{JPN}かてたのは ふしぎな ちからの\nおかげよ! いつも かてると おもわない\lことね!$"

Route110_Text_EdwinIntro:
	.string "{JPN}あなたの ポケモンを みせて くれる?\nひとめだけで いいの!$"

Route110_Text_EdwinDefeated:
	.string "{JPN}コレクションを かんせい\nさせたかったのに…$"

Route110_Text_EdwinPostBattle:
	.string "{JPN}しらない ポケモンを みると\nあつめたい きもちに ひが つくの!$"

Route110_Text_EdwinRegister:
	.string "{JPN}れんらくさきを あつめるのも\nすきなの…$"

Route110_Text_EdwinRematchIntro:
	.string "{JPN}やあ あたらしい ポケモンは つかまえた?\pあなたの ポケモンを みせて くれる?\nひとめだけで いいの!$"

Route110_Text_EdwinRematchDefeated:
	.string "{JPN}あなたの ポケモン…\nうらやましいわ。$"

Route110_Text_EdwinRematchPostBattle:
	.string "{JPN}めずらしい ポケモンは ぜんぶ\nじぶんの ものに したいわ!$"

Route110_Text_DaleIntro:
	.string "{JPN}おい!\nうしろから そっと ちかづくなよ!$"

Route110_Text_DaleDefeated:
	.string "{JPN}まけた!\nくそっ!$"

Route110_Text_DalePostBattle:
	.string "{JPN}つりは しゅうちゅうりょくが すべてだ。\nうきに めを こらすんだ。$"

Route110_Text_IsabelIntro:
	.string "{JPN}あははは! かわいい ポケモンを\nみせびらかすためなら どこへでも いくわ。$"

Route110_Text_IsabelDefeated:
	.string "{JPN}あらまあ これは いけないわ。$"

Route110_Text_IsabelPostBattle:
	.string "{JPN}しょうぶより ファンクラブで ポケモンを\nみせびらかす ほうが いいかしら。$"

Route110_Text_IsabelRegister:
	.string "{JPN}ポケモンを みせびらかすには ぜんぜん\nたりなかったわ。\pできるだけ たくさん みて\nもらうわよ!$"

Route110_Text_IsabelRematchIntro:
	.string "{JPN}あははは! いくらでも わたしの ポケモンを\nみせて あげるわ!$"

Route110_Text_IsabelRematchDefeated:
	.string "{JPN}あらまあ これは いけないわ。$"

Route110_Text_IsabelRematchPostBattle:
	.string "{JPN}ポケモンを みせびらかすのは\nやめられそうに ないわ。\pでも しょうぶも すきなの!$"

Route110_Text_TimmyIntro:
	.string "{JPN}この あたりの くさむらで かっこいい\nポケモンを みつけたぞ!$"

Route110_Text_TimmyDefeated:
	.string "{JPN}かっこよさだけでは かてないか…$"

Route110_Text_TimmyPostBattle:
	.string "{JPN}つかまえたばかりの ポケモンで\nたたかうのは むずかしいな。$"

Route110_Text_AlyssaIntro:
	.string "{JPN}じてんしゃロードから おちて しまった…\pはずかしさを しょうぶで\nまぎらわせるぞ!$"

Route110_Text_AlyssaDefeated:
	.string "{JPN}おっと!\nまけて しまった!$"

Route110_Text_AlyssaPostBattle:
	.string "{JPN}おちて まけて…\nはずかしくて たまらない!$"

Route110_Text_JosephIntro:
	.string "{JPN}よし ぜんかいで いくぜ! ノリが わるいと\nおいて いかれるぞ!$"

Route110_Text_JosephDefeated:
	.string "{JPN}すっかり ノって いたな…$"

Route110_Text_JosephPostBattle:
	.string "{JPN}この くらいで へこたれないぜ!\nまけて おとこを あげたのさ!$"

Route110_Text_KalebIntro:
	.string "{JPN}かわいい ポケモンどうしが たすけあう…\nこんなに かわいい ものは ないわ!$"

Route110_Text_KalebDefeated:
	.string "{JPN}なさけも あわれみも ないのね?$"

Route110_Text_KalebPostBattle:
	.string "{JPN}はいはい よく がんばったわ かわいい\nこたち。$"

Route111_Text_DrewIntro:
	.string "{JPN}あら! その ゴーグル にあうわね。 でも わたしの\nほうが にあうと おもうの。\pどちらが にあうか しょうぶで\nきめましょう!$"

Route111_Text_DrewDefeat:
	.string "{JPN}ゴーグルの せいで よこが\nみえなかったわ。$"

Route111_Text_DrewPostBattle:
	.string "{JPN}ゴーグルが あれば すなあらしも\nとおれるのよ。\lうれしいわ!$"

Route111_Text_HeidiIntro:
	.string "{JPN}さばくで ピクニックを して いるの。\pトレーナーも かならず いるから\nここでも しょうぶが たのしめるわ!$"

Route111_Text_HeidiDefeat:
	.string "{JPN}ああ! いじわる!$"

Route111_Text_HeidiPostBattle:
	.string "{JPN}すなあらしの なかで たたかう ときは ポケモンの\nHPに きを つけてね。\pみて いないと ひんしに なって\nしまうわ!$"

Route111_Text_BeauIntro:
	.string "{JPN}この ゴーグルを つけると ヒーローに\nなった きぶんだ。\lいまの おれには だれも かてない!$"

Route111_Text_BeauDefeat:
	.string "{JPN}きあいだけでは かてないか…$"

Route111_Text_BeauPostBattle:
	.string "{JPN}いつか ほんものの ヒーローに なる。\nもっと がんばって じぶんも ポケモンも\lつよく するぞ。$"

Route111_Text_BeckyIntro:
	.string "{JPN}さばくで かせきが みつかると きいた。\nどこに あるのだろう?$"

Route111_Text_BeckyDefeat:
	.string "{JPN}およばなかった…$"

Route111_Text_BeckyPostBattle:
	.string "{JPN}さばくで かせきが みつかるなら\nむかしは うみ だったに ちがいない。$"

Route111_Text_DustyIntro:
	.string "{JPN}30ねんかん いせきを さがして きた!\nこの わたしに\lしょうぶを いどむと いうのか?$"

Route111_Text_DustyDefeat:
	.string "{JPN}いせきは さがして きたが\nつよい ポケモンは さがして いなかった。$"

Route111_Text_DustyPostBattle:
	.string "{JPN}30ねんかん いせきを さがして\nきた!\pいや まてよ 40ねん だったか? どっち\nだったかな?$"

Route111_Text_DustyRegister:
	.string "{JPN}つよい ポケモンは さがして\nいない。\pだが なぜか ポケナビは\nすきなんだ。$"

Route111_Text_DustyRematchIntro:
	.string "{JPN}30ねんかん いせきを さがして\nきた!\pいや まてよ 40ねん だったか? ともかく\nしょうぶを いどむのか?$"

Route111_Text_DustyRematchDefeat:
	.string "{JPN}いせきも みつからず つよい ポケモンも\nみつからず…$"

Route111_Text_DustyPostRematch:
	.string "{JPN}30ねんかん いせきを さがして\nきた!\pいや まてよ 40ねん\nだったか?\pうーむ 50ねんかも しれん… どれだけ さがして\nいるのだろう?$"

Route111_Text_TravisIntro:
	.string "{JPN}げんきいっぱい!\nポケモンも げんきいっぱい!$"

Route111_Text_TravisDefeat:
	.string "{JPN}ポケモンの げんきが なくなった…$"

Route111_Text_TravisPostBattle:
	.string "{JPN}げんきな トレーナーを みると\nつい めが いって しまうんだ。$"

Route111_Text_IreneIntro:
	.string "{JPN}どこへ いくのか しらないが\nしょうぶ しないか?$"

Route111_Text_IreneDefeat:
	.string "{JPN}いやに つよいな!$"

Route111_Text_IrenePostBattle:
	.string "{JPN}えんとつやまへ いこうと おもって いるが\nこの あたりの けしきも\lなかなか わるくない。$"

Route111_Text_DaisukeIntro:
	.string "{JPN}じぶんを きたえるため であう ものすべてに\nしょうぶを いどむ!$"

Route111_Text_DaisukeDefeat:
	.string "{JPN}まいった! こうさんだ!$"

Route111_Text_DaisukePostBattle:
	.string "{JPN}きみの ような つよい トレーナーに\nかてる ように なるまで\lきたえつづける しかない。$"

Route111_Text_WiltonIntro:
	.string "{JPN}どれだけ ポケモンを きたえたか\nみせて もらおう。$"

Route111_Text_WiltonDefeat:
	.string "{JPN}なるほど かなり きたえて\nあるな。$"

Route111_Text_WiltonPostBattle:
	.string "{JPN}ポケモンも トレーナーも しょうぶから おおくを\nまなぶ。\pだいじなのは まけても あきらめない\nことだ。$"

Route111_Text_WiltonRegister:
	.string "{JPN}きみの きたえかたには まなぶ ことが\nおおい。\pよければ また しょうぶ して\nほしい。$"

Route111_Text_WiltonRematchIntro:
	.string "{JPN}つぎの だんかいへ すすむために\nここで きたえて いる。\lきみも いっしょに どうだ!$"

Route111_Text_WiltonRematchDefeat:
	.string "{JPN}ほう なかなか やるな!$"

Route111_Text_WiltonPostRematch:
	.string "{JPN}それだけ つよいなら ポケモンリーグを\nめざすと いい。$"

Route111_Text_BrookeIntro:
	.string "{JPN}おお きみの ポケモンは いい やくしゃの\nようだ。\lぜひ しゅつえんを おねがいしたい。$"

Route111_Text_BrookeDefeat:
	.string "{JPN}つよそうなだけでは なく\nほんとうに つよかった!$"

Route111_Text_BrookePostBattle:
	.string "{JPN}ねっしんに そだてて きた つもりだが\nいやはや まだまだ\lやる ことが おおいな。$"

Route111_Text_BrookeRegister:
	.string "{JPN}きみの ような つよい ひとと\nもっと ともだちに なりたいものだ!$"

Route111_Text_BrookeRematchIntro:
	.string "{JPN}おぼえさせる わざで ポケモンは\nつよくも よわくも なる。\lそれを わすれては いけない。\pきみの ポケモンは どんな わざを\nおぼえて いるのかな?$"

Route111_Text_BrookeRematchDefeat:
	.string "{JPN}いい わざを おぼえさせて いるな!$"

Route111_Text_BrookePostRematch:
	.string "{JPN}いい わざを おぼえるまで\nポケモンの しんかを とめて\lおくべき だったかな…$"

Route111_Text_CeliaIntro:
	.string "{JPN}こんな ところで ピクニックを\nするんじゃ なかった!$"

Route111_Text_CeliaDefeat:
	.string "{JPN}ああ!\nやっぱり くるんじゃ なかった!$"

Route111_Text_CeliaPostBattle:
	.string "{JPN}これだけ すなあらしが ひどいと\nゴーグルが あっても ピクニックの\lしたくが できないわ…$"

Route111_Text_BryanIntro:
	.string "{JPN}どれほど つよいのか?\nその ひみつを あばいて みせよう!$"

Route111_Text_BryanDefeat:
	.string "{JPN}おお その つよさ!\nまさに なぞに つつまれて いる!$"

Route111_Text_BryanPostBattle:
	.string "{JPN}この さばくは うごく すなの なかに\nなぞを かくして いるのだ!$"

Route111_Text_BrandenIntro:
	.string "{JPN}まけて くれたら サンドイッチを\nわけて あげるよ。$"

Route111_Text_BrandenDefeat:
	.string "{JPN}ちぇっ! サンドイッチで じゅうぶんだと\nおもったのに…$"

Route111_Text_BrandenPostBattle:
	.string "{JPN}うちの サンドは サンドイッチが\nだいすきなんだ。$"

Route111_Text_TyronIntro:
	.string "{JPN}これが おきにいりの ポケモンだ!$"

Route111_Text_TyronDefeat:
	.string "{JPN}まって!\nおれの ポケモンを よく みたか?$"

Route111_Text_TyronPostBattle:
	.string "{JPN}しょうぶの ときは ポケモンを みせびらかせるのが\nうれしいんだ。\pみんな そう おもって\nいるはずだ!$"

Route111_Text_CelinaIntro:
	.string "{JPN}わたしの まいにちに すこし\nどきどきを ください。$"

Route111_Text_CelinaDefeat:
	.string "{JPN}ああ…\nどきどきしすぎたわ。$"

Route111_Text_CelinaPostBattle:
	.string "{JPN}むねの どうきが まだ おさまらない。\nすばらしい トレーナーね。$"

Route111_Text_HaydenIntro:
	.string "{JPN}これだけ はらが へって いると\nなさけを かける よゆうは ない!$"

Route111_Text_HaydenDefeat:
	.string "{JPN}うーん…$"

Route111_Text_HaydenPostBattle:
	.string "{JPN}はらが なる!\nきのみでも やこうかな…$"

Route111_Text_BiancaIntro:
	.string "{JPN}キンセツから きたのか?\nそれなら げんきいっぱい だろう!$"

Route111_Text_BiancaDefeat:
	.string "{JPN}おお!\nこれは こたえるな!$"

Route111_Text_BiancaPostBattle:
	.string "{JPN}この みちは…\nまだまだ さきが ながいぞ。$"

Route112_Text_BriceIntro:
	.string "{JPN}はははは!\nしょうぶ しないか?\lきみと おれで!\lはははは!$"

Route112_Text_BriceDefeat:
	.string "{JPN}まけた!\nはははは!$"

Route112_Text_BricePostBattle:
	.string "{JPN}はははは! はなに なにか はいった!\nははは はっくしょん!$"

Route112_Text_TrentIntro:
	.string "{JPN}やまを のぼりおりして あしは\nがちがちだ。\pそう かんたんには\nへこたれないぞ!$"

Route112_Text_TrentDefeat:
	.string "{JPN}いてっ! あしが つった!$"

Route112_Text_TrentPostBattle:
	.string "{JPN}じゅっキロも ある にもつを せおって\nやまみちを ほんきで\lあるいて みると いい。\lきみも やって みないか。\pそうすれば からだは しっかり\nしあがるんだ。$"

Route112_Text_TrentRegister:
	.string "{JPN}いてて あしが つった。\nリュックから ほうたいを\lとって くれるか?\pいや それは ポケナビだ!\nまあ いい とうろく して やろう。$"

Route112_Text_TrentRematchIntro:
	.string "{JPN}やまあるきで からだを きたえて いる。\nちからなら じしんが ある!$"

Route112_Text_TrentRematchDefeat:
	.string "{JPN}ちからで まけたのか?$"

Route112_Text_TrentRematchPostBattle:
	.string "{JPN}えんとつやまの うえに とんでもなく つよい\nトレーナーが いるらしい。\pのぼって いって しょうぶを\nいどむぞ!$"

Route112_Text_LarryIntro:
	.string "{JPN}ぼくは つよいんだ。\nまけても なかないぞ。$"

Route112_Text_LarryDefeat:
	.string "{JPN}うわあああん!$"

Route112_Text_LarryPostBattle:
	.string "{JPN}ママが こいしくて ないて いるんじゃ ないぞ!\nぐすん…$"

Route112_Text_CarolIntro:
	.string "{JPN}ピクニックに きたら やっぱり\nうたわなくちゃ!\lいっしょに うたいましょう!$"

Route112_Text_CarolDefeat:
	.string "{JPN}まあ とても つよいのね!$"

Route112_Text_CarolPostBattle:
	.string "{JPN}うたも ポケモンも じょうずでも へたでも\nかまわないの。\pいちばん たのしんだ ひとの かちよ!$"

Route112_Text_BryantIntro:
	.string "{JPN}えんとつやまの みちで あつい ポケモンを\nつかまえたぞ! みて くれ!$"

Route112_Text_BryantDefeat:
	.string "{JPN}はでに ふきとばされたな!$"

Route112_Text_BryantPostBattle:
	.string "{JPN}きみの たたかいかたが きに いった。\nどこか かっこいいんだ。$"

Route112_Text_ShaylaIntro:
	.string "{JPN}あら かわいい トレーナーね!\nロマンチックな しょうぶを おねがい!\lわたしも そこそこ やるのよ!$"

Route112_Text_ShaylaDefeat:
	.string "{JPN}まあ なんて つよいの!\nおどろいて しまったわ!$"

Route112_Text_ShaylaPostBattle:
	.string "{JPN}いま いそがしい?\nよければ すぐにでも また しょうぶを\lしたいのだけど…\lいそがしいなら いいのよ。$"

Route113_Text_JaylenIntro:
	.string "{JPN}この あたりが すずしい わけが\nわかるかしら?$"

Route113_Text_JaylenDefeat:
	.string "{JPN}うわあ!\nくさい!$"

Route113_Text_JaylenPostBattle:
	.string "{JPN}かざんばいが たいようを さえぎるから\nあまり あつく ならないの。\pあつさが にがてな わたしには ありがたいわ!$"

Route113_Text_DillonIntro:
	.string "{JPN}かざんの ふんかは だいちが いきて いる\nしょうこなの。$"

Route113_Text_DillonDefeat:
	.string "{JPN}とんでもなく つよいのね!$"

Route113_Text_DillonPostBattle:
	.string "{JPN}いたた! みえない!\nまつげに はいが はいったわ!\pはいと まつげ… なんてね?\pいまのは よくなかったわね ごめんなさい…$"

Route113_Text_MadelineIntro:
	.string "{JPN}この ひがさで かわいい ドンメルを\nよごれた かざんばいから\lまもって いるの。$"

Route113_Text_MadelineDefeat:
	.string "{JPN}はあ はあ…\nつかれたわ…$"

Route113_Text_MadelinePostBattle:
	.string "{JPN}あなた とても じょうずね。\nかんしん したわ!$"

Route113_Text_MadelineRegister:
	.string "{JPN}さあ ひがさの したへ どうぞ。\nポケナビに とうろく させて。$"

Route113_Text_MadelineRematchIntro:
	.string "{JPN}あら こんにちは ひさしぶりね?\nしょうぶに さそっても いいかしら?$"

Route113_Text_MadelineRematchDefeat:
	.string "{JPN}まあ すてき!$"

Route113_Text_MadelinePostRematch:
	.string "{JPN}あいかわらず じょうずね。\nかんしん するわ!$"

Route113_Text_LaoIntro:
	.string "{JPN}はいの なかから とびだす! やあっ!\nしょうぶを いどむ!$"

Route113_Text_LaoDefeat:
	.string "{JPN}いさぎよく まけを みとめよう!$"

Route113_Text_LaoPostBattle:
	.string "{JPN}かくれる わざを もっと みがかねば。\nさらばだ。$"

Route113_Text_LaoRegister:
	.string "{JPN}やあっ! にんじゃ ひでんの\nポケナビ とうろくを みよ!$"

Route113_Text_LaoRematchIntro:
	.string "{JPN}はいの なかから とびだす! やあっ!\nしょうぶを いどむ!$"

Route113_Text_LaoRematchDefeat:
	.string "{JPN}いさぎよく まけを みとめよう!$"

Route113_Text_LaoPostRematch:
	.string "{JPN}かんぺきな かくれみも みじゅくな\nしょうぶの うでで だいなしか…\pさらばだ。$"

Route113_Text_LungIntro:
	.string "{JPN}みつけて くれて ありがとう!\nだが しょうぶは してもらうぞ!$"

Route113_Text_LungDefeat:
	.string "{JPN}にんぽう…\n「かざんばい うずまきがくれ」!\p…なに?\nもう おわりだと?$"

Route113_Text_LungPostBattle:
	.string "{JPN}かくれる ことの こまった ところは\nだれも こないと さびしい ことだ。$"

Route113_Text_ToriIntro:
	.string "{JPN}トリ: ふたりで はいを あつめて いるの。\nポケモンの しょうぶも するわ。$"

Route113_Text_ToriDefeat:
	.string "{JPN}トリ: まけちゃった… つまらないから\nはいを もっと あつめて くる。$"

Route113_Text_ToriPostBattle:
	.string "{JPN}トリ: はいは どれくらい たまったかな?\nしろいふえに なると いいな。$"

Route113_Text_ToriNotEnoughMons:
	.string "{JPN}トリ: 2たい2で しょうぶ したいの。\nそうじゃないと まけちゃうもの!$"

Route113_Text_TiaIntro:
	.string "{JPN}ティア: ふたりで はいを あつめて いるの。\nポケモンの しょうぶも するわ。$"

Route113_Text_TiaDefeat:
	.string "{JPN}ティア: かてなかった… つまらないから\nはいを もっと あつめて くる。$"

Route113_Text_TiaPostBattle:
	.string "{JPN}ティア: はいが たくさん たまったわ!\nしろいふえに できそう!$"

Route113_Text_TiaNotEnoughMons:
	.string "{JPN}ティア: 2たい2で しょうぶ したいの。\nそうじゃないと かてないもの!$"

Route113_Text_CobyIntro:
	.string "{JPN}ふん この つばさで きみなんか\nはらいのけて やる!$"

Route113_Text_CobyDefeat:
	.string "{JPN}あ… え?$"

Route113_Text_CobyPostBattle:
	.string "{JPN}こんなに かんたんに まけると\nいう ことばも ない…$"

Route113_Text_SophieIntro:
	.string "{JPN}ここは あたたかくて ねむく なる。\nおきて いられるよう しょうぶ しよう。$"

Route113_Text_SophieDefeat:
	.string "{JPN}これは ゆめだ。\nきっと そうだ…$"

Route113_Text_SophiePostBattle:
	.string "{JPN}まけると あたまに くる…\nもう ここで ねて しまおう!\lぐう!$"

Route113_Text_LawrenceIntro:
	.string "{JPN}もしかして かざんばいを\nあつめて いる とちゅう?$"

Route113_Text_LawrenceDefeat:
	.string "{JPN}えへへ。\nみごとに まけちゃった。$"

Route113_Text_LawrencePostBattle:
	.string "{JPN}わたしも はいの したに かくれようかな。$"

Route113_Text_WyattIntro:
	.string "{JPN}わ わたしと しょうぶ するの?\nポケモンを つかまえたばかりなのに?$"

Route113_Text_WyattDefeat:
	.string "{JPN}か かって うれしいの?\nわたし あいてなのに?$"

Route113_Text_WyattPostBattle:
	.string "{JPN}まけた ものに なにか\nいうつもり?\pずいぶん えらそうね?\nふん!$"

Route114_Text_LennyIntro:
	.string "{JPN}ヤッホー!\p… …\pここは やまびこが かえらないから\nじぶんで「ヤッホー」って\lいわないと だめなの!$"

Route114_Text_LennyDefeat:
	.string "{JPN}ヤッホー!$"

Route114_Text_LennyPostBattle:
	.string "{JPN}ちいさい ころは だれかが まねを して\n「ヤッホー」と かえして くれるんだと\lしんじて いたわ。$"

Route114_Text_LucasIntro:
	.string "{JPN}じゅんびも なしに やまに\nはいるものでは ないぞ!$"

Route114_Text_LucasDefeat:
	.string "{JPN}やまは きびしい…$"

Route114_Text_LucasPostBattle:
	.string "{JPN}ふゆの やまは ふぶきや なだれで\nいのちに かかわるんだ。$"

Route114_Text_ShaneIntro:
	.string "{JPN}キャンプは たのしい! つりも できるし こわい\nはなしも できる!\pでも いちばんは ポケモンの\nしょうぶだ!$"

Route114_Text_ShaneDefeat:
	.string "{JPN}つよすぎる!$"

Route114_Text_ShanePostBattle:
	.string "{JPN}ポケモンと キャンプに こられるのが\nうれしいんだ。$"

Route114_Text_NancyIntro:
	.string "{JPN}しょくごの うんどうが ひつようだ。\nいっしょうぶ しよう!$"

Route114_Text_NancyDefeat:
	.string "{JPN}しまった!$"

Route114_Text_NancyPostBattle:
	.string "{JPN}おいしい ものを たべたばかりだ。\nねむく なって きたな…$"

Route114_Text_SteveIntro:
	.string "{JPN}うふふふふ…\nわたしの ポケモンと しょうぶ する?$"

Route114_Text_SteveDefeat:
	.string "{JPN}わ わたしの ポケモンが…$"

Route114_Text_StevePostBattle:
	.string "{JPN}ごつごつ した おおきな からだに\nりっぱな つのと するどい きば…\pうふふふ…\nそんな ポケモンが ほしいわ…$"

Route114_Text_SteveRegister:
	.string "{JPN}わたしに した ことを わすれないで!\nわすれられない ように して あげる!$"

Route114_Text_SteveRematchIntro:
	.string "{JPN}うふふふふ…\nさあ わたしの ポケモンと しょうぶよ…$"

Route114_Text_SteveRematchDefeat:
	.string "{JPN}あなたの ポケモンを みられて\nしあわせだわ…$"

Route114_Text_StevePostRematch:
	.string "{JPN}うふふふふ…\pポケモンの しょうぶを みて いると\nぞくぞく して ふるえて しまうの…$"

Route114_Text_BernieIntro:
	.string "{JPN}たきびを するなら みずを\nよういして おくんだよ。$"

Route114_Text_BernieDefeat:
	.string "{JPN}ひを けして くれて ありがとう!$"

Route114_Text_BerniePostBattle:
	.string "{JPN}もりの なかでは ひの あつかいに じゅうぶん きを\nつけないと いけない。\pひの ちからを あなどっては\nいけないよ。$"

Route114_Text_BernieRegister:
	.string "{JPN}きみに こころを もやされたよ。\nおたがい とうろく しよう!$"

Route114_Text_BernieRematchIntro:
	.string "{JPN}たきびには みずを よういする ことを\nおぼえたかい?$"

Route114_Text_BernieRematchDefeat:
	.string "{JPN}もえあがる まえに みずを\nかけられた かんじだな。$"

Route114_Text_BerniePostRematch:
	.string "{JPN}もりの なかでは ひの あつかいに じゅうぶん きを\nつけないと いけない。\pひの ちからを あなどっては\nいけないよ。$"

Route114_Text_ClaudeIntro:
	.string "{JPN}つりなら きみに まける きは しない。\nだから ポケモンで\lしょうぶ しようじゃないか!$"

Route114_Text_ClaudeDefeat:
	.string "{JPN}つりなら かって いたのに…$"

Route114_Text_ClaudePostBattle:
	.string "{JPN}りゅうせいのたきで おおものを\nねらって みるかな。\pあそこには かならず なにか いる。\nそんな きが するんだ。$"

Route114_Text_NolanIntro:
	.string "{JPN}つりも すきだが しょうぶも\nすきだ!\pだれかに いどまれたら つりの とちゅうでも うけて\nたつぞ。$"

Route114_Text_NolanDefeat:
	.string "{JPN}しょうぶは すきだが\nじょうずとは かぎらないな…$"

Route114_Text_NolanPostBattle:
	.string "{JPN}こんどこそ うまく いく!\pいつも そう おもうから つりも ポケモンも\nやめられないんだ。$"

Route114_Text_TyraIntro:
	.string "{JPN}タイラ: ええ いいわよ。\nちょうど その きぶんだったの。\lポケモンの ことを すこし おしえて あげる。$"

Route114_Text_TyraDefeat:
	.string "{JPN}タイラ: なんて みごとな たたかいかた!$"

Route114_Text_TyraPostBattle:
	.string "{JPN}タイラ: こうはいの アイビーに\nポケモンを おしえて いたの。$"

Route114_Text_TyraNotEnoughMons:
	.string "{JPN}タイラ: うふふ…\nわたしたちと しょうぶ するなら\lポケモン 1ぴきでは たりないわ!$"

Route114_Text_IvyIntro:
	.string "{JPN}アイビー: ポケモンの ことは\nだれに おそわったの?$"

Route114_Text_IvyDefeat:
	.string "{JPN}アイビー: なんて みごとな たたかいかた!$"

Route114_Text_IvyPostBattle:
	.string "{JPN}アイビー: せんぱいの タイラに\nおそわって ポケモンを\lそだてはじめたの!$"

Route114_Text_IvyNotEnoughMons:
	.string "{JPN}アイビー: ポケモンは 1ぴきだけ?\nさびしいと おもうな。$"

Route114_Text_KaiIntro:
	.string "{JPN}おおものを つりあげたぞ!\nとんでもなく でかいんだ!$"

Route114_Text_KaiDefeat:
	.string "{JPN}なんだったんだ?\nおおきさで まけたのか?$"

Route114_Text_KaiPostBattle:
	.string "{JPN}よし!\nもっと おおきいのを つって やる!$"

Route114_Text_CharlotteIntro:
	.string "{JPN}わたし!\nかおだけじゃ ないのよ!$"

Route114_Text_CharlotteDefeat:
	.string "{JPN}ぜんぜん かわいく なかったわ!$"

Route114_Text_CharlottePostBattle:
	.string "{JPN}かわいいだけの ポケモンは\nいらないの。\pすこし かわった ところが ある かわいい こが\nすきなの!$"

Route114_Text_AngelinaIntro:
	.string "{JPN}ポケモンを しんかさせて\nいる?$"

Route114_Text_AngelinaDefeat:
	.string "{JPN}あら そうなの。\nいい ことを きいたわ。$"

Route114_Text_AngelinaPostBattle:
	.string "{JPN}しんかすると すがたが すっかり かわる\nポケモンも いて おどろくわ!$"

Route115_Text_TimothyIntro:
	.string "{JPN}ふむ…\nなかなか できるようだな…\lあいてを して やろう!$"

Route115_Text_TimothyDefeat:
	.string "{JPN}おもって いたより ずっと\nつよいな!$"

Route115_Text_TimothyPostBattle:
	.string "{JPN}うまれつきの てんさいなど いない。\nすべては どりょくしだい!\lわたしは そう しんじて いる…$"

Route115_Text_TimothyRegister:
	.string "{JPN}うむ… ここまで みごとに まけたのは\nひさしぶりだ。\pよければ また しょうぶを して\nほしい。$"

Route115_Text_TimothyRematchIntro:
	.string "{JPN}ふむ あいかわらず みのこなしが\nいいな。 さあ あいてを して\lくれ!$"

Route115_Text_TimothyRematchDefeat:
	.string "{JPN}あいかわらず つよいな!$"

Route115_Text_TimothyPostRematch:
	.string "{JPN}すべては どりょくだ!\pどりょくが たりなかったから\nまけたのだ!$"

Route115_Text_KoichiIntro:
	.string "{JPN}きみ!\pおれの ワンリキーが!\pしょうぶを のぞんで いる!$"

Route115_Text_KoichiDefeat:
	.string "{JPN}いたた いたた!$"

Route115_Text_KoichiPostBattle:
	.string "{JPN}おれの ワンリキーたち!\pちからを もとめる かぎり\nおれも ともに つよく なる!$"

Route115_Text_NobIntro:
	.string "{JPN}とくいわざは ひたいで\nかわらわりだ!$"

Route115_Text_NobDefeat:
	.string "{JPN}ぐわあああ!\nあたまが われる!$"

Route115_Text_NobPostBattle:
	.string "{JPN}ポケモンに からてを おしえて いる。\pおれより ずっと つよく なりそうだ。\nそれが たのしみなんだ。$"

Route115_Text_NobRegister:
	.string "{JPN}みごとだ! きたえなおしたら\nまた しょうぶ して くれ!$"

Route115_Text_NobRematchIntro:
	.string "{JPN}きみに まけてから ひっしに\nうでを みがいて きた。\lさあ もういちど しょうぶだ!$"

Route115_Text_NobRematchDefeat:
	.string "{JPN}ぐわあ!\nまた まけた!$"

Route115_Text_NobPostRematch:
	.string "{JPN}ポケモンは もっと つよく なる!\nきたえなおしだ!$"

Route115_Text_CyndyIntro:
	.string "{JPN}この はまべは おれの ひみつの\nれんしゅうばだ! じゃまを するな!$"

Route115_Text_CyndyDefeat:
	.string "{JPN}きたえかたが たりなかった!$"

Route115_Text_CyndyPostBattle:
	.string "{JPN}すなは しょうげきを やわらげて\nけがを ふせいで くれる。\lれんしゅうに もってこいの ばしょだ。$"

Route115_Text_CyndyRegister:
	.string "{JPN}わかった ここに きても いい。\nそのかわり また しょうぶ して くれ。$"

Route115_Text_CyndyRematchIntro:
	.string "{JPN}よし しょうぶ しよう!$"

Route115_Text_CyndyRematchDefeat:
	.string "{JPN}おれは たたかえるが ポケモンが…$"

Route115_Text_CyndyPostRematch:
	.string "{JPN}まけても どこか\nたのしいんだ。 ポケモンが\lすきだからだろうな。$"

Route115_Text_HectorIntro:
	.string "{JPN}めずらしい ポケモンを もって いるんだ!\nみせて あげようか?$"

Route115_Text_HectorDefeat:
	.string "{JPN}きみ…\nおれの ポケモンが ほしいんだろう?$"

Route115_Text_HectorPostBattle:
	.string "{JPN}この めずらしい ポケモンが いれば\nおれは じゅうぶん まんぞくだ。$"

Route115_Text_KyraIntro:
	.string "{JPN}はしりながら しょうぶ するぞ!\nついてこられるか!$"

Route115_Text_KyraDefeat:
	.string "{JPN}はあ はあ…$"

Route115_Text_KyraPostBattle:
	.string "{JPN}はしりながら しょうぶ したのが\nまちがい だった!\pはしって おちつくと するか…$"

Route115_Text_JaidenIntro:
	.string "{JPN}くらえ!\nウルトラ ポケモン にんぽう!$"

Route115_Text_JaidenDefeat:
	.string "{JPN}わあ!\nさくせんが しっぱい した!$"

Route115_Text_JaidenPostBattle:
	.string "{JPN}でも ぼくの ポケモンは ウルトラ\nだったろう?$"

Route115_Text_HeleneIntro:
	.string "{JPN}おれの ポケモンは くろおびきゅうの\nちからを もって いる!$"

Route115_Text_HeleneDefeat:
	.string "{JPN}はずかしくて たまらない!$"

Route115_Text_HelenePostBattle:
	.string "{JPN}おれより つよい やつには\nめったに あわないのだが…\pわかったぞ!\nきみは ジムリーダーだな?$"

Route115_Text_AlixIntro:
	.string "{JPN}めが あった!\nもう にげられないぞ!$"

Route115_Text_AlixDefeat:
	.string "{JPN}ぐっ!\nなかなか やるな!$"

Route115_Text_AlixPostBattle:
	.string "{JPN}しかたない。\nテレポートで いえに かえるとしよう。$"

Route115_Text_MarleneIntro:
	.string "{JPN}わたしの めいそうを じゃま したな…\nばつを うけて もらおう。$"

Route115_Text_MarleneDefeat:
	.string "{JPN}しゅうちゅうを みだされた!$"

Route115_Text_MarlenePostBattle:
	.string "{JPN}ポケモンと めいそう して いたのだ。\nだが ここは しずかとは いえないな…$"

Route116_Text_ClarkIntro:
	.string "{JPN}トンネルが とおれないなら\nうえを こえて いくまでだ。$"

Route116_Text_ClarkDefeat:
	.string "{JPN}はあ はあ…\nまけて つかれたぞ…$"

Route116_Text_ClarkPostBattle:
	.string "{JPN}トンネルが なくても かまわん。\nやまおとこに とって やまは みちだ!$"

Route116_Text_JoeyIntro:
	.string "{JPN}おれの ポケモンは さいこうだ!\nみて くれ!$"

Route116_Text_JoeyDefeat:
	.string "{JPN}いてっ! すりむいた!\nばんそうこうを はらないと!$"

Route116_Text_JoeyPostBattle:
	.string "{JPN}ばんそうこうは つよさの あかし!\nもう 1まい あるぞ!$"

Route116_Text_JoseIntro:
	.string "{JPN}ぼくの むしポケモンは つよいぞ!\nしょうぶだ!$"

Route116_Text_JoseDefeat:
	.string "{JPN}まけた!\nかてると おもったのに!$"

Route116_Text_JosePostBattle:
	.string "{JPN}むしポケモンは しんかが はやい。\nだから つよく なるのも はやいんだ。$"

Route116_Text_JaniceIntro:
	.string "{JPN}わたしの かわいい ポケモンの つよさを\nおしえて あげる!$"

Route116_Text_JaniceDefeat:
	.string "{JPN}わたしより ひとつ うえね…$"

Route116_Text_JanicePostBattle:
	.string "{JPN}かわいさと つよさを あわせもつ\nポケモンが りそうだと おもうの。$"

Route116_Text_JerryIntro:
	.string "{JPN}トレーナーズスクールでは いろいろな\nことを ならうんだ。\pほんばんで ためして みたい!$"

Route116_Text_JerryDefeat:
	.string "{JPN}がっこうで さぼって いたから\nまけたんだ…$"

Route116_Text_JerryPostBattle:
	.string "{JPN}トレーナーズスクールで べんきょうを\nやりなおさないと。\lそうしないと ツツジせんせいに おこられる。$"

Route116_Text_JerryRegister1:
	.string "{JPN}ポケナビで トレーナーを とうろく できると\nトレーナーズスクールで ならったんだ。\pよく わからないから\nためして みても いい?$"

Route116_Text_JerryRegister2:
	.string "{JPN}ポケナビで トレーナーを とうろく できると\nトレーナーズスクールで ならったんだ。\pよく わからないから\nためして みても いい?$"

Route116_Text_JerryRematchIntro:
	.string "{JPN}トレーナーズスクールで まじめに\nべんきょう して きた。\lまえの ようには まけないぞ。$"

Route116_Text_JerryRematchDefeat:
	.string "{JPN}え?\nちゃんと べんきょう したのに。$"

Route116_Text_JerryPostRematch:
	.string "{JPN}トレーナーズスクールで べんきょうを\nやりなおさないと。\lそうしないと ツツジせんせいに おこられる。$"

Route116_Text_KarenIntro:
	.string "{JPN}がっこうでも かえりみちでも\nべんきょう して いるんだ!$"

Route116_Text_KarenDefeat:
	.string "{JPN}ショックだ… まけたのか?$"

Route116_Text_KarenPostBattle:
	.string "{JPN}ああ これじゃ ツツジせんせいの ような\nりっぱな トレーナーに なれないよ!$"

Route116_Text_KarenRegister1:
	.string "{JPN}わあ! それ ポケナビ?\nぼくも もって いる! とうろく して!$"

Route116_Text_KarenRegister2:
	.string "{JPN}わあ! それ ポケナビ?\nぼくも もって いる! とうろく して!$"

Route116_Text_KarenRematchIntro:
	.string "{JPN}まえに あってから たくさん べんきょう した。\nその せいかを みて くれ!$"

Route116_Text_KarenRematchDefeat:
	.string "{JPN}ショックだ。\nまた まけたのか?$"

Route116_Text_KarenPostRematch:
	.string "{JPN}ツツジせんせいに かったの?\nそれじゃ ぼくには まだ かてないや。$"

Route116_Text_SarahIntro:
	.string "{JPN}いって おくけれど わたくしは なにごとも\nひとに おくれを とった ことが ないの。$"

Route116_Text_SarahDefeat:
	.string "{JPN}まあ おどろいた。\nはじめての けいけんだわ。$"

Route116_Text_SarahPostBattle:
	.string "{JPN}ぜいたくな くらしで ほしい ものは\nなんでも てに はいるの。\pでも ポケモンに かんしては\nおかねなど いみが ないのね。$"

Route116_Text_DawsonIntro:
	.string "{JPN}わたくしの ポケモンの うつくしい\nけなみを みたら あなたは\lみとれて しまうわ!$"

Route116_Text_DawsonDefeat:
	.string "{JPN}まあ そんな ことって!$"

Route116_Text_DawsonPostBattle:
	.string "{JPN}ああ もう!\nポケモンの けなみが みだれたわ!\lわたくしの かみも ぐしゃぐしゃ!\lびようしを よばなくては!$"

Route116_Text_DevanIntro:
	.string "{JPN}はでに いくぜ!$"

Route116_Text_DevanDefeat:
	.string "{JPN}あいたた!\nまるで しょうぶに ならなかった!$"

Route116_Text_DevanPostBattle:
	.string "{JPN}ちがう タイプの ポケモンも\nためして みるべきだな。$"

Route116_Text_JohnsonIntro:
	.string "{JPN}ここは いきどまりよ。\nたいくつだから しょうぶ しない?$"

Route116_Text_JohnsonDefeat:
	.string "{JPN}まけたけど たのしかったわ。$"

Route116_Text_JohnsonPostBattle:
	.string "{JPN}ここに のこって わたしの あいてを\nして くれない?$"

Route117_Text_IsaacIntro:
	.string "{JPN}ねえ わたしが そだてて いる ポケモンと\nしょうぶ して くれない?$"

Route117_Text_IsaacDefeat:
	.string "{JPN}みごとに そだてて いるのね…$"

Route117_Text_IsaacPostBattle:
	.string "{JPN}ポケモンは ちからが すべてでは ないの。\pその こだけの みりょくを みがくのも\nポケモンの たのしみかたの\lひとつなのよ。$"

Route117_Text_IsaacRegister:
	.string "{JPN}もっと きたえなおすわ。\nようすを みに きて くれる?$"

Route117_Text_IsaacRematchIntro:
	.string "{JPN}そだてて いる ポケモンは\nまえと おなじく いい かんじよ。$"

Route117_Text_IsaacRematchDefeat:
	.string "{JPN}そだてかたが じょうずね。\nあずかりやの さいのうが あるかも…$"

Route117_Text_IsaacPostRematch:
	.string "{JPN}ポケモンが よく そだって いるわ!\nコンテストに でて みたら?$"

Route117_Text_LydiaIntro:
	.string "{JPN}あなたが ポケモンを ちゃんと\nそだてて いるか みせて もらうわ。$"

Route117_Text_LydiaDefeat:
	.string "{JPN}ええ ちゃんと そだって いるわね。$"

Route117_Text_LydiaPostBattle:
	.string "{JPN}その こらしさを もっと たいせつに\nそだてて みると いいわ。$"

Route117_Text_LydiaRegister:
	.string "{JPN}すばらしい トレーナーに あえて うれしいわ。\nまた あいましょう。$"

Route117_Text_LydiaRematchIntro:
	.string "{JPN}ポケモンを ちゃんと そだてて いるか\nもういちど みせて もらうわ。$"

Route117_Text_LydiaRematchDefeat:
	.string "{JPN}みごとに そだって いるわね。$"

Route117_Text_LydiaPostRematch:
	.string "{JPN}ポケモンは せいかくに よって すきな\n{POKEBLOCK}が ちがうみたい。$"

Route117_Text_DylanIntro:
	.string "{JPN}トライアスロンの とちゅうだけど\nまあ しょうぶ しよう!$"

Route117_Text_DylanDefeat:
	.string "{JPN}ちからが つきた!$"

Route117_Text_DylanPostBattle:
	.string "{JPN}やって しまった…\pいまの しょうぶで さいかいに\nおちたかも しれない…$"

Route117_Text_DylanRegister:
	.string "{JPN}ポケモンも つよく ないと だめなのか?\nきたえて ほしいくらいだ!$"

Route117_Text_DylanRematchIntro:
	.string "{JPN}トライアスロンの まっさいちゅうだが\nよゆうで さきを はしって いる。\lさっと しょうぶを すませよう!$"

Route117_Text_DylanRematchDefeat:
	.string "{JPN}また ちからが つきた!$"

Route117_Text_DylanPostRematch:
	.string "{JPN}すいえいと じてんしゃは いちばん\nだったが ポケモンには\lまだ じしんが ないな。$"

Route117_Text_MariaIntro:
	.string "{JPN}ポケモンと トライアスロンの れんしゅうを\nして いるから はやさには じしんが ある。$"

Route117_Text_MariaDefeat:
	.string "{JPN}もっと れんしゅうが\nひつようだな。$"

Route117_Text_MariaPostBattle:
	.string "{JPN}れんしゅうは つづけてこそ いみが\nある。\pよし れんしゅうを さいかいだ!\nあしたから!$"

Route117_Text_MariaRegister:
	.string "{JPN}ちゃんと きたえて いるようだな…\nよければ あとで しょうぶ しよう!$"

Route117_Text_MariaRematchIntro:
	.string "{JPN}れんしゅうは つづけて いるか?\nおれは つづけて いるぞ!\lその しょうこを みせて やる!$"

Route117_Text_MariaRematchDefeat:
	.string "{JPN}もっと れんしゅうが\nひつようだな。$"

Route117_Text_MariaPostRematch:
	.string "{JPN}れんしゅうは あしたから さいかいだ。\nまた いつか しょうぶ しよう!$"

Route117_Text_DerekIntro:
	.string "{JPN}むかしは むしとりしょうねん! いまは\nむしマニア!\pだが ポケモンへの あいは\nかわらない!$"

Route117_Text_DerekDefeat:
	.string "{JPN}へたなのも\nかわらないな…$"

Route117_Text_DerekPostBattle:
	.string "{JPN}すきな ことを つづけて いたら\nむしマニアと よばれる ように なった…\pまあ むしポケモンの めいじんだから\nむしマニアと よばれるのも\lとうぜんの ことだな。$"

Route117_Text_AnnaIntro:
	.string "{JPN}アンナ: かわいい こうはいと いっしょよ。\nいい ところを みせないと!$"

Route117_Text_AnnaDefeat:
	.string "{JPN}アンナ: かわいい こうはいと いっしょ!\nかたせて もらうわ!$"

Route117_Text_AnnaPostBattle:
	.string "{JPN}アンナ: あなたの ポケモンは\nくみあわせが いいわね。\pわたしたちの つぎに つよいわ!$"

Route117_Text_AnnaAndMegRegister:
	.string "{JPN}アンナ: このままでは おわれないわ!\nまた きて くれるわよね?$"

Route117_Text_AnnaNotEnoughMons:
	.string "{JPN}アンナ: わたしたちと しょうぶ するなら\nポケモンを 2ひき つれて きて。$"

Route117_Text_MegIntro:
	.string "{JPN}メグ: すごい せんぱいと くんで\nあなたを たおすわ!$"

Route117_Text_MegDefeat:
	.string "{JPN}メグ: ああ そんな!\nごめんね アンナせんぱい わたしの せいで…$"

Route117_Text_MegPostBattle:
	.string "{JPN}メグ: わたしが アンナせんぱいの あしを\nひっぱったの… そうでなければ かって いたのに!$"

Route117_Text_MegNotEnoughMons:
	.string "{JPN}メグ: ポケモンは 1ぴきだけ?\nそれでは しょうぶ できないわ。\pわたしたちは 2たい2で たたかいたいの。$"

Route117_Text_AnnaRematchIntro:
	.string "{JPN}アンナ: こうはいの まえで\nまけつづける わけには いかないわ?$"

Route117_Text_AnnaRematchDefeat:
	.string "{JPN}アンナ: ちょうしに のれなかったわ。$"

Route117_Text_AnnaPostRematch:
	.string "{JPN}アンナ: あなたの ポケモンは\nくみあわせが いいわね。\pわたしたちの つぎに つよいわ!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "{JPN}アンナ: わたしたちと しょうぶ するなら\nポケモンを 2ひき つれて きて。$"

Route117_Text_MegRematchIntro:
	.string "{JPN}メグ: せんぱいと くんで\nこんどこそ かつわ!$"

Route117_Text_MegRematchDefeat:
	.string "{JPN}メグ: つよすぎる!$"

Route117_Text_MegPostRematch:
	.string "{JPN}メグ: せんぱいと いっしょに たたかったのに\nまけちゃった…\pがっかりだわ…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "{JPN}メグ: ポケモンは 1ぴきだけ?\nそれでは しょうぶ できないわ。\pわたしたちは 2たい2で たたかいたいの。$"

Route117_Text_MelinaIntro:
	.string "{JPN}きれいな はなを ながめながらの しょうぶ。\nすてきだと おもわない?$"

Route117_Text_MelinaDefeat:
	.string "{JPN}あら みごとね!$"

Route117_Text_MelinaPostBattle:
	.string "{JPN}はなを みながら はしるのは\nきもちが いいの。$"

Route117_Text_BrandiIntro:
	.string "{JPN}エスパーポケモンに ひめられた ちからを\nみせて あげよう!$"

Route117_Text_BrandiDefeat:
	.string "{JPN}おどろいた!$"

Route117_Text_BrandiPostBattle:
	.string "{JPN}エスパーポケモンは おくが ふかい。\nきみも つかまえて みると いい。$"

Route117_Text_AishaIntro:
	.string "{JPN}かつ ことに しゅうちゅう する。\nそれが わたしの たたかいかた!$"

Route117_Text_AishaDefeat:
	.string "{JPN}まけて おこって いる ひまが あるなら\nきたえた ほうが いい。$"

Route117_Text_AishaPostBattle:
	.string "{JPN}まけを おそれると よけいに\nまけやすく なると おもうの。$"

Route118_Text_RoseIntro:
	.string "{JPN}はなの かおりには ふしぎな ちからが あるの。\nからだも こころも きよめて くれるわ。$"

Route118_Text_RoseDefeat:
	.string "{JPN}あらまあ。\nまけて しまった みたい。$"

Route118_Text_RosePostBattle:
	.string "{JPN}はなも ポケモンも…\nいい かおりの ものは なんでも すき。\pくさい ものは…\nえんりょ するわ。$"

Route118_Text_RoseRegister:
	.string "{JPN}くんくん… この かおりは ポケナビ!\nおたがい とうろく しましょう!$"

Route118_Text_RoseRematchIntro:
	.string "{JPN}あまい かおりに ひかれて\nきたの?$"

Route118_Text_RoseRematchDefeat:
	.string "{JPN}かおりの ちからも\nあまり きかなかったわね。$"

Route118_Text_RosePostRematch:
	.string "{JPN}あまい かおりを うまく つかうと\nポケモンが よって くるのよ。$"

Route118_Text_PerryIntro:
	.string "{JPN}そらを ゆうがに とぶ とりポケモン…\nさいこうだよね!$"

Route118_Text_PerryDefeat:
	.string "{JPN}うう…\nついらく した…$"

Route118_Text_PerryPostBattle:
	.string "{JPN}いい ポケモンを もって いるね。\nもっと きたえないと いけないな。$"

Route118_Text_ChesterIntro:
	.string "{JPN}とべ!\nおれの とりポケモン!$"

Route118_Text_ChesterDefeat:
	.string "{JPN}たしかに とんで いったな…$"

Route118_Text_ChesterPostBattle:
	.string "{JPN}もっと つよく なれば もっと じゆうに\nとべるはずなんだが…$"

Route118_Text_BarnyIntro:
	.string "{JPN}つりびとだが トレーナーでも ある。\nつった ポケモンを そだてて いるんだ。$"

Route118_Text_BarnyDefeat:
	.string "{JPN}そだてかたは わるく ないと\nおもって いたが…$"

Route118_Text_BarnyPostBattle:
	.string "{JPN}つりながら ポケモンを そだてて いては\nかてなかったか…\pどちらも ちゅうとはんぱ だったかな?$"

Route118_Text_WadeIntro:
	.string "{JPN}つりびとには どうぐが たいせつだ。\pだが トレーナーに たいせつなのは\nポケモンと こころだろう!$"

Route118_Text_WadeDefeat:
	.string "{JPN}こころで まけたのか?$"

Route118_Text_WadePostBattle:
	.string "{JPN}かんがえて みれば つりも つりびとと\nポケモンの しょうぶだな。$"

Route118_Text_DaltonIntro:
	.string "{JPN}おれの メロディで こころを ゆさぶってやる!$"

Route118_Text_DaltonDefeat:
	.string "{JPN}ラ ラララ…$"

Route118_Text_DaltonPostBattle:
	.string "{JPN}エレキギターは うるさい だけの\nがっきじゃ ない…\pこころに ひびく メロディも\nかなでる ことが できるんだ…$"

Route118_Text_DaltonRegister:
	.string "{JPN}もっと いい きょくが できたら\nききに きて くれよ?$"

Route118_Text_DaltonRematchIntro:
	.string "{JPN}おれと ポケモンの メロディを…\nきみの こころに とどけよう。$"

Route118_Text_DaltonRematchDefeat:
	.string "{JPN}ラ ラララ…$"

Route118_Text_DaltonPostRematch:
	.string "{JPN}ひいて いれば おれの きもちは\nエレキギターを とおして とどくはずだ…$"

Route118_Text_DeandreIntro:
	.string "{JPN}いけ いけ いけ!\nポケモン 1 2 3!$"

Route118_Text_DeandreDefeat:
	.string "{JPN}おうとう せよ ポケモン! ぶじか?\nポケモン 1 2 3!?$"

Route118_Text_DeandrePostBattle:
	.string "{JPN}ポケモンの しょうぶチームって\nかっこいい だろう?\pまねしても かまわないぞ!$"

Route119_Text_BrentIntro:
	.string "{JPN}わたしたちは ものまねサークル!\nあなたの まねを するの!$"

Route119_Text_BrentDefeat:
	.string "{JPN}おっと!\nまけちゃった!$"

Route119_Text_BrentPostBattle:
	.string "{JPN}ものまねの なにが たのしいかって?\pふふふ…\nあなたには わからないでしょうね…$"

Route119_Text_DonaldIntro:
	.string "{JPN}ついに あえたね!\nぼくの むしポケモンが あいてを するよ!$"

Route119_Text_DonaldDefeat:
	.string "{JPN}あわなければ よかった…$"

Route119_Text_DonaldPostBattle:
	.string "{JPN}もっと まねを したいの。\nはやく うごいて くれない?$"

Route119_Text_TaylorIntro:
	.string "{JPN}あなたが すすめば わたしたちも すすむ。\pあなたが みぎを むけば わたしたちも むく…$"

Route119_Text_TaylorDefeat:
	.string "{JPN}でも あなたが かつと わたしは まける…$"

Route119_Text_TaylorPostBattle:
	.string "{JPN}あなたが かつ ところは まねできない。\nそんなの むりだもの…\lくやしいわ…$"

Route119_Text_DougIntro:
	.string "{JPN}やっと つかまえたね!\nそれとも さけて いたのかな?$"

Route119_Text_DougDefeat:
	.string "{JPN}おっと いい しょうぶだった!$"

Route119_Text_DougPostBattle:
	.string "{JPN}わたしたちは ものまねサークル!\nえんぎを たのしんで もらえたかしら。$"

Route119_Text_GregIntro:
	.string "{JPN}わたしが だれだか しらないでしょう?\pでも わたしも あなたを しらない。\nだから しょうぶ しましょう!$"

Route119_Text_GregDefeat:
	.string "{JPN}なかなか つよいのね!$"

Route119_Text_GregPostBattle:
	.string "{JPN}あなたが どこかへ いくまで\nうごきを まねしつづけるわ。$"

Route119_Text_KentIntro:
	.string "{JPN}ものまねサークルは まねが すきな ひとで\nつくった あつまりなの。\pであった しゅんかんから しょうぶよ!$"

Route119_Text_KentDefeat:
	.string "{JPN}まいった!$"

Route119_Text_KentPostBattle:
	.string "{JPN}ものまねサークルに はいらない?$"

Route119_Text_JacksonIntro:
	.string "{JPN}いきのこる ちしきと ぎじゅつを\nもって いるのは だれか?\pポケモンレンジャーさ!$"

Route119_Text_JacksonDefeat:
	.string "{JPN}ポケモンの ちしきが\nたりなかった…$"

Route119_Text_JacksonPostBattle:
	.string "{JPN}まちを はなれ うちなる やせいの こころを\nめざめさせる!\pそれが おれたちの めざす ものだ。$"

Route119_Text_JacksonRegister:
	.string "{JPN}ちしきぶそくを わらわずに\nまた しょうぶ して ほしい。$"

Route119_Text_JacksonRematchIntro:
	.string "{JPN}ポケモンと ともに いる ことで\nやせいの こころを とりもどすんだ。$"

Route119_Text_JacksonRematchDefeat:
	.string "{JPN}あいかわらず つよいな!$"

Route119_Text_JacksonPostRematch:
	.string "{JPN}ポケモンを しんじろ。\nじぶんを しんじろ。\pそうすれば みちは ひらける。$"

Route119_Text_CatherineIntro:
	.string "{JPN}おや? きみを みて いると…\pぼうけんの わりに ずいぶん\nみがるな かっこうだね。$"

Route119_Text_CatherineDefeat:
	.string "{JPN}じゅんびが たりないと\nじこが おきるものだぞ!$"

Route119_Text_CatherinePostBattle:
	.string "{JPN}みがるだが ひつような ものは そろって\nいるな。\pこころも からだも しっかり して\nいる。$"

Route119_Text_CatherineRegister:
	.string "{JPN}ポケナビは もって いるか?\nトレーナーには かかせない どうぐだ。\pおお もって いるのか!\nでは とうろく しあおう!$"

Route119_Text_CatherineRematchIntro:
	.string "{JPN}ポケモンとの たびは\nどうだい?$"

Route119_Text_CatherineRematchDefeat:
	.string "{JPN}まだ なにかが たりないな…$"

Route119_Text_CatherinePostRematch:
	.string "{JPN}トレーナーが ポケモンを たよる ように\nポケモンも きみの ことを\lたよって いるんだ。$"

Route119_Text_HughIntro:
	.string "{JPN}ひろい そらには むげんの かのうせいが ある!\pとぶ ことの きもちよさに かなう ものは\nなにも ない!$"

Route119_Text_HughDefeat:
	.string "{JPN}のされた!$"

Route119_Text_HughPostBattle:
	.string "{JPN}とりポケモンが とぶ ゆめを\nかなえて くれたんだ!$"

Route119_Text_PhilIntro:
	.string "{JPN}おれと とりポケモンの ほんとうの ちからを\nみせて やる!$"

Route119_Text_PhilDefeat:
	.string "{JPN}ちからが たりなかった…$"

Route119_Text_PhilPostBattle:
	.string "{JPN}ちいさい ころから とりポケモンに\nあこがれて いたんだ…$"

Route119_Text_YasuIntro:
	.string "{JPN}かげに ひそみ やみに いきる…\nそれが わが さだめ。\pいまこそ すがたを あらわし いどむ!$"

Route119_Text_YasuDefeat:
	.string "{JPN}まけを みとめよう!$"

Route119_Text_YasuPostBattle:
	.string "{JPN}やぶれた ものは しずかに\nかげへ かえる。 それもまた\lさだめ…$"

Route119_Text_TakashiIntro:
	.string "{JPN}ゆだんして いると いたい めを\nみるぞ!$"

Route119_Text_TakashiDefeat:
	.string "{JPN}おどろく ほど つよいな!$"

Route119_Text_TakashiPostBattle:
	.string "{JPN}ふいうちは しっぱいに\nおわった…$"

Route119_Text_HideoIntro:
	.string "{JPN}きを かくすなら もりの なか!$"

Route119_Text_HideoDefeat:
	.string "{JPN}きみの ほうが うえだ みとめよう。$"

Route119_Text_HideoPostBattle:
	.string "{JPN}きを かくすなら もりの なか! ポケモンを\nかくすなら ポケモンの なか!\pふかい いみは とくに\nない。$"

Route119_Text_ChrisIntro:
	.string "{JPN}はなしかけて きたな…\nつまり しょうぶを のぞむのだな!\pいいだろう! なみのりの とちゅうで\nつかまえた ポケモンを ためして やる!$"

Route119_Text_ChrisDefeat:
	.string "{JPN}かつには なにが ひつようなのか\nさっぱり わからん。$"

Route119_Text_ChrisPostBattle:
	.string "{JPN}ポケモンに のって なみのり…\pその せなかから つりを する…\pなんとも ぜいたくな ひとときだ!$"

Route119_Text_FabianIntro:
	.string "{JPN}はでな コードを ならして いくぜ!\nしょうりは おれの ものだ!\lいまこそ かがやく ときだぜ!$"

Route119_Text_FabianDefeat:
	.string "{JPN}どっちが うえか おもいしらされた!\nまけを みとめる しかないぜ!$"

Route119_Text_FabianPostBattle:
	.string "{JPN}もう いっぱつ はでな コードを ならすぜ!\nほうって おいて くれ!\lかった つみは おもいぜ!$"

Route119_Text_DaytonIntro:
	.string "{JPN}ほっほっほ!\nこどもの トレーナーは すきじゃ!\lいい しょうぶを しようぞ!$"

Route119_Text_DaytonDefeat:
	.string "{JPN}なかなか みごとじゃ!\nほっほっほ!$"

Route119_Text_DaytonPostBattle:
	.string "{JPN}ほっほっほ!\nおまえさんのような わかい トレーナーの\lげんきを みならうと しようかの!$"

Route119_Text_RachelIntro:
	.string "{JPN}いつ どこに いても\nひがさは てばなさないの。$"

Route119_Text_RachelDefeat:
	.string "{JPN}あら でも…\nそれは ずるいわ。$"

Route119_Text_RachelPostBattle:
	.string "{JPN}ひがさが おもそうって?\nあなたの バッグの ほうが よっぽど\lいろいろ つまって いるじゃない。$"

Route120_Text_ColinIntro:
	.string "{JPN}そらに いる ポケモンに あたる わざは\nもって いるかしら?$"

Route120_Text_ColinDefeat:
	.string "{JPN}うえを いかれたわ!$"

Route120_Text_ColinPostBattle:
	.string "{JPN}そらをとぶは べんりな わざだと\nおもわない?\pとんで いる あいだは ほとんどの わざが\nあたらないもの。$"

Route120_Text_RobertIntro:
	.string "{JPN}わたしの ポケモンは つよいわよ!\nあなたの ポケモンは どう?$"

Route120_Text_RobertDefeat:
	.string "{JPN}あなたの ポケモンの ほうが つよかったわ…$"

Route120_Text_RobertPostBattle:
	.string "{JPN}じっくり そだった ポケモンは\nたよりに なるものよ。$"

Route120_Text_RobertRegister:
	.string "{JPN}あなたは まだまだ のびそうね。\nポケナビに とうろく させて!$"

Route120_Text_RobertRematchIntro:
	.string "{JPN}じっくり そだった ポケモンは\nたよりに なるものよ。$"

Route120_Text_RobertRematchDefeat:
	.string "{JPN}あなたの ポケモンは ほんとうに つよいわ。$"

Route120_Text_RobertPostRematch:
	.string "{JPN}ポケモンは つよく なって いる。\nわたしも つよく ならないと。$"

Route120_Text_LorenzoIntro:
	.string "{JPN}あなたの ポケモンが やがいに むいて いるか\nみせて もらうわ。$"

Route120_Text_LorenzoDefeat:
	.string "{JPN}それだけ つよい ポケモンが いれば\nきゅうじょは いらないわね!$"

Route120_Text_LorenzoPostBattle:
	.string "{JPN}ポケモンと ともに いきたい ところへ\nいく… それが トレーナーの\lよろこびよ。$"

Route120_Text_JennaIntro:
	.string "{JPN}たいりょくは ある?\nたいりょくが ないと いざと いう ときに\lこまるわよ。$"

Route120_Text_JennaDefeat:
	.string "{JPN}たいりょくは じゅうぶん なのに…$"

Route120_Text_JennaPostBattle:
	.string "{JPN}たいりょくづくりは にっかなの。\nいつも ポケモンと はしって いるわ。$"

Route120_Text_JeffreyIntro:
	.string "{JPN}… … … … … …\n… … … … … …\lしょうぶ する?$"

Route120_Text_JeffreyDefeat:
	.string "{JPN}まけた…$"

Route120_Text_JeffreyPostBattle:
	.string "{JPN}… … … … … …\n… … … … … …\lもっと がんばる…$"

Route120_Text_JeffreyRegister:
	.string "{JPN}… … … … … …\n… … … … … …\lポケナビは もって いる…?$"

Route120_Text_JeffreyRematchIntro:
	.string "{JPN}… … … … … …\n… … … … … …\lまた しょうぶ する?$"

Route120_Text_JeffreyRematchDefeat:
	.string "{JPN}… … … … … …\nまた まけた…$"

Route120_Text_JeffreyPostRematch:
	.string "{JPN}… … … … … …\n… … … … … …\lもっと がんばる…\lたいせつな むしポケモンの ために…$"

Route120_Text_JenniferIntro:
	.string "{JPN}ポケモンには いろいろな とくせいが ある。\nいちりゅうの トレーナーを めざすなら\lそれを まなぶ ことだ。$"

Route120_Text_JenniferDefeat:
	.string "{JPN}よく かんがえて いるようだな。$"

Route120_Text_JenniferPostBattle:
	.string "{JPN}ポケモンの とくせいで\nたたかいかたは かわるのだ。$"

Route120_Text_ChipIntro:
	.string "{JPN}きみは だれかね?\pもしや でんせつに あると いわれる\nいせきを さがして\lいるのでは ないかね?$"

Route120_Text_ChipDefeat:
	.string "{JPN}なんとも なさけない…$"

Route120_Text_ChipPostBattle:
	.string "{JPN}あの おおきな いわ… なかに いせきが\nあるのだと しんじたい。\lだが いりぐちが みあたらんのだ。$"

Route120_Text_ClarissaIntro:
	.string "{JPN}なぜ ひがさを さして いるかって?\pわたしに かてたら おしえて あげるわ。$"

Route120_Text_ClarissaDefeat:
	.string "{JPN}ひがさでは ポケモンの こうげきは\nふせげないわね…$"

Route120_Text_ClarissaPostBattle:
	.string "{JPN}つよい ひざしは ポケモンに よくないと\nおもうの。\lだから ひがさで まもって いるのよ。$"

Route120_Text_AngelicaIntro:
	.string "{JPN}わたしと ポケモンと ひがさ…\pどれが かけても\nうつくしい えは できないの。$"

Route120_Text_AngelicaDefeat:
	.string "{JPN}わたしの うつくしさが すっかり だいなしね…$"

Route120_Text_AngelicaPostBattle:
	.string "{JPN}あなたには ひがさは にあわないわ。\pこんな ものは じゃまに\nなるだけよ。$"

Route120_Text_KeigoIntro:
	.string "{JPN}ポケモンの うごきを とりいれて\nあたらしい にんぽうを つくるのだ。$"

Route120_Text_KeigoDefeat:
	.string "{JPN}あたらしい にんぽうづくりは\nまだまだ とおい ゆめだ…$"

Route120_Text_KeigoPostBattle:
	.string "{JPN}にんじゃの ししょうに でしいり\nするべきかも しれんな。$"

Route120_Text_RileyIntro:
	.string "{JPN}われら にんじゃは かくれみのを かぶって\nすがたを かくす。\lどこに いるか わからなかっただろう!$"

Route120_Text_RileyDefeat:
	.string "{JPN}まけた!\nはずかしさを かくさねば!$"

Route120_Text_RileyPostBattle:
	.string "{JPN}かくれみのは すべて\nてづくりなのだ。$"

Route120_Text_CallieIntro:
	.string "{JPN}きを つけて いないと\nけがを するぞ!$"

Route120_Text_CallieDefeat:
	.string "{JPN}いてっ!\nけがを したのは こちらだった。$"

Route120_Text_CalliePostBattle:
	.string "{JPN}ポケモンを しんかさせようかな…\nいまも じゅうぶん かわいいけど。$"

Route120_Text_LeonelIntro:
	.string "{JPN}てもちの ポケモン…\nタイプは ばらけて いる?$"

Route120_Text_LeonelDefeat:
	.string "{JPN}あなたの かんがえかたが よく わかったわ!$"

Route120_Text_LeonelPostBattle:
	.string "{JPN}すきな ポケモンで そこまで つよいのは\nすばらしい ことだと おもうわ。$"

Route121_Text_VanessaIntro:
	.string "{JPN}わたしの とても かわいい ポケモンと\nあそんで くれる?$"

Route121_Text_VanessaDefeat:
	.string "{JPN}こういう ことじゃ なかったのに!$"

Route121_Text_VanessaPostBattle:
	.string "{JPN}ミナモの コンテストに いくの。\pうちの ポケモンなら マスタークラスも\nかんたんに かちぬけるわ。$"

Route121_Text_WalterIntro:
	.string "{JPN}ポケモンと ともに せかいの すみずみまで\nたびを して きた。\pうでには すこし じしんが あると\nいっても いいだろう。$"

Route121_Text_WalterDefeat:
	.string "{JPN}うむ みごとだ。$"

Route121_Text_WalterPostBattle:
	.string "{JPN}ポケモンと ともに もういちど\nせかいを まわりたいものだ。$"

Route121_Text_WalterRegister:
	.string "{JPN}きみの ポケモンの うでまえは みごとだ。\nきねんに とうろく させて くれ。$"

Route121_Text_WalterRematchIntro:
	.string "{JPN}ポケモンと ともに せかいの すみずみまで\nたびを して きた。\pうでには すこし じしんが あると\nいっても いいだろう。$"

Route121_Text_WalterRematchDefeat:
	.string "{JPN}うむ みごとだ。$"

Route121_Text_WalterPostRematch:
	.string "{JPN}きみと きみの ポケモン…\pその ちからは かいがいでも\nじゅうぶん つうよう するだろう。$"

Route121_Text_TammyIntro:
	.string "{JPN}この よには わたしたちの りかいを こえた\nちからが ある…$"

Route121_Text_TammyDefeat:
	.string "{JPN}まけて しまった…$"

Route121_Text_TammyPostBattle:
	.string "{JPN}おくりびやま…\nあそこには ふしぎな ちからが\lはたらいて いる…$"

Route121_Text_KateIntro:
	.string "{JPN}ケイト: ふたりなら こわい ものなし!\nつよさを みせて あげるわ!$"

Route121_Text_KateDefeat:
	.string "{JPN}ケイト: こうはいの まえで\nしくじったわ…$"

Route121_Text_KatePostBattle:
	.string "{JPN}ケイト: たよりに されると\nかっこよく みせたく なって\lしまうのよね…$"

Route121_Text_KateNotEnoughMons:
	.string "{JPN}ケイト: ポケモンが 1ぴきだけなら\nしょうぶは できないわ。\pそれでは いじめに なって しまうもの。$"

Route121_Text_JoyIntro:
	.string "{JPN}ジョイ: ふたりなら こわい ものなし!\nつよさを みせて あげるわ!$"

Route121_Text_JoyDefeat:
	.string "{JPN}ジョイ: ケイトせんぱい ゆるして!$"

Route121_Text_JoyPostBattle:
	.string "{JPN}ジョイ: えへへ ケイトせんぱいと\nまた れんしゅう しないと。$"

Route121_Text_JoyNotEnoughMons:
	.string "{JPN}ジョイ: わたしたちに いどむなら\nポケモンが 2ひきは ひつようよ!$"

Route121_Text_JessicaIntro:
	.string "{JPN}まって! わたしの たいせつな ポケモンを\nよく みて いって!$"

Route121_Text_JessicaDefeat:
	.string "{JPN}まあ ひどい!\nそんなに ほんきに ならなくても!$"

Route121_Text_JessicaPostBattle:
	.string "{JPN}サファリゾーンで ポケモンを もっと\nつかまえて こようかしら。$"

Route121_Text_JessicaRegister:
	.string "{JPN}こんかいは てかげん して あげたの!\nつぎは そう いかないわよ!$"

Route121_Text_JessicaRematchIntro:
	.string "{JPN}たいせつな ポケモンが そだったの!\nよく みて いって!$"

Route121_Text_JessicaRematchDefeat:
	.string "{JPN}まあ ひどい!\nやっぱり てかげん して くれないのね!$"

Route121_Text_JessicaPostRematch:
	.string "{JPN}サファリゾーンで ポケモンを もっと\nつかまえて こようかしら。$"

Route121_Text_CristinIntro:
	.string "{JPN}わたしの にっかは トレーナーを\n1にちに 5にん たおす こと。\lあなたが 5にんめよ!$"

Route121_Text_CristinDefeat:
	.string "{JPN}いや!\nひどい ひとね!$"

Route121_Text_CristinPostBattle:
	.string "{JPN}こんなに かんたんに まけるなんて…\nつぎは かつわ!$"

Route121_Text_CristinRegister:
	.string "{JPN}はずかしくて たまらないわ!\nあなたの ことは わすれない…\lポケナビを かしなさい!$"

Route121_Text_CristinRematchIntro:
	.string "{JPN}あたらしい にっかは トレーナーを\n1にちに 10にん たおす こと。\lあなたが 10にんめよ!$"

Route121_Text_CristinRematchDefeat:
	.string "{JPN}まって! ひどいわ!\nもういちど しょうぶよ!$"

Route121_Text_CristinPostRematch:
	.string "{JPN}どうしても かてない あいて…\nぐすん…\lこんな ことが あるなんて…$"

Route121_Text_CaleIntro:
	.string "{JPN}こんなに にもつを もって いるのが\nみえないの?\pそれでも しょうぶ しろと\nいうの?$"

Route121_Text_CaleDefeat:
	.string "{JPN}まけて とうぜんよ!\nりょうてが ふさがって いるもの!$"

Route121_Text_CalePostBattle:
	.string "{JPN}ミナモデパートで かいすぎて\nしまったの。\pこの さきに あるのよ。 あなたのような バッグが\nほしいわ。$"

Route121_Text_MylesIntro:
	.string "{JPN}ひとの ポケモンを みるのが\nなにより すきなの!$"

Route121_Text_MylesDefeat:
	.string "{JPN}とても すばらしいわ!$"

Route121_Text_MylesPostBattle:
	.string "{JPN}いい ポケモンね!\nどうやって そだてて いるの?$"

Route121_Text_PatIntro:
	.string "{JPN}そだてた ポケモンを みんなに\nみて もらいたいの!$"

Route121_Text_PatDefeat:
	.string "{JPN}わあ!\nみごとだわ!$"

Route121_Text_PatPostBattle:
	.string "{JPN}どの ポケモンも おなじだけ かわいがって\nそだてて いるの えこひいきは しないわ。$"

Route121_Text_MarcelIntro:
	.string "{JPN}わたしの ポケモンは まけしらず!\nつぎ かったら コンテストに\lでる つもりなの。$"

Route121_Text_MarcelDefeat:
	.string "{JPN}あら どうして こうなったの?$"

Route121_Text_MarcelPostBattle:
	.string "{JPN}コンテストに でる まえに もうすこし\nきたえた ほうが よさそうね。$"

Route123_Text_WendyIntro:
	.string "{JPN}じぶんの つよさを ためして みたい?\nわたしが あいてに なって あげる!$"

Route123_Text_WendyDefeat:
	.string "{JPN}みごとに ごうかくだわ!$"

Route123_Text_WendyPostBattle:
	.string "{JPN}わたしにまで かつなんて…\nすばらしい つよさね!$"

Route123_Text_BraxtonIntro:
	.string "{JPN}ジムバッジを たくさん\nもって いるようだな。\pその バッジに ふさわしいか\nためさせて もらおう!$"

Route123_Text_BraxtonDefeat:
	.string "{JPN}うむ ふさわしい!$"

Route123_Text_BraxtonPostBattle:
	.string "{JPN}バッジに はじない しょうぶ\nだったぞ!$"

Route123_Text_VioletIntro:
	.string "{JPN}たのしい ときは いい かおりで\nみちて いると いうわ。$"

Route123_Text_VioletDefeat:
	.string "{JPN}ああ…\nみじめな にがい かおりが する…$"

Route123_Text_VioletPostBattle:
	.string "{JPN}きのみはかせの にわは こころが はずむ\nかおりで みちて いるのよ。$"

Route123_Text_CameronIntro:
	.string "{JPN}エスパーは こころの ちからが すべて。\pだれにも まけないと きめて いる。\nだから つよいのだ!$"

Route123_Text_CameronDefeat:
	.string "{JPN}かなしい…$"

Route123_Text_CameronPostBattle:
	.string "{JPN}エスパーは こころの ちからが すべて。\nきみには まけないと おもって いたが…$"

Route123_Text_CameronRegister:
	.string "{JPN}かんじる!\nきみとは また しょうぶ する ことに なる!\lかてるかは わからないが…\pポケナビを みせて くれ。$"

Route123_Text_CameronRematchIntro:
	.string "{JPN}もう まけないと じぶんに いいきかせた。\nだから つよいのだ!$"

Route123_Text_CameronRematchDefeat:
	.string "{JPN}かなしい…$"

Route123_Text_CameronPostRematch:
	.string "{JPN}おくりびやまで きたえるべきか…\nこのままでは きみに かてない…$"

Route123_Text_JackiIntro:
	.string "{JPN}ポケモンが ちょうのうりょくに めざめても\nよろこびすぎては いけない。\pその ちからは みがかなければ\nやくに たたないのだ。$"

Route123_Text_JackiDefeat:
	.string "{JPN}あっとうされた!$"

Route123_Text_JackiPostBattle:
	.string "{JPN}だれもが ちょうのうりょくを もって いる。\nつかいかたを わすれて いるだけだ。$"

Route123_Text_JackiRegister:
	.string "{JPN}また きみと たいじ したい。\nかまわないかね?$"

Route123_Text_JackiRematchIntro:
	.string "{JPN}うちなる ちょうのうりょくに\nめざめたのかね?$"

Route123_Text_JackiRematchDefeat:
	.string "{JPN}おどろいた!$"

Route123_Text_JackiPostRematch:
	.string "{JPN}ポケモンを あつかう その ちから…\nそれも ちょうのうりょくかも しれないな。$"

Route123_Text_MiuIntro:
	.string "{JPN}ミウ: こんにちは トレーナーさん。\nまけても ポケモンが なきませんように。$"

Route123_Text_MiuDefeat:
	.string "{JPN}ミウ: あーあ まけちゃった。$"

Route123_Text_MiuPostBattle:
	.string "{JPN}ミウ: トレーナーさん ポケモンが つよいのは\nともだちだからね。$"

Route123_Text_MiuNotEnoughMons:
	.string "{JPN}ミウ: ポケモンが 2ひき いないと\nしょうぶ しても つまらないわ。$"

Route123_Text_YukiIntro:
	.string "{JPN}ユキ: よーし!\nトレーナーの ポケモンを たおすわ!$"

Route123_Text_YukiDefeat:
	.string "{JPN}ユキ: あーあ まけちゃった。$"

Route123_Text_YukiPostBattle:
	.string "{JPN}ユキ: どうして そんなに つよいの?\nいままで まけた ことが ないのに。$"

Route123_Text_YukiNotEnoughMons:
	.string "{JPN}ユキ: ポケモンが 2ひき いないと\nしょうぶ しても つまらないわ。$"

Route123_Text_KindraIntro:
	.string "{JPN}おくりびやま…\nポケモンの たましいが ねむる ところ…\lきみの ポケモンも ねむるかな?$"

Route123_Text_KindraDefeat:
	.string "{JPN}いのちが あふれて いる…$"

Route123_Text_KindraPostBattle:
	.string "{JPN}おくりびやま…\nポケモンの たましいが ねむる ところ…\pたましいを やすめる ちからが\nみちて いるのだろう…$"

Route123_Text_FernandoIntro:
	.string "{JPN}この きょくを かきならして\nきみを しずめて やるぜ!$"

Route123_Text_FernandoDefeat:
	.string "{JPN}おい まてよ!\nまだ イントロの とちゅうだぞ!$"

Route123_Text_FernandoPostBattle:
	.string "{JPN}きみは しっかり して いるな。\nきみの ことを きょくに したいくらいだ。$"

Route123_Text_FernandoRegister:
	.string "{JPN}こんどは さいごまで きいて\nくれよ?$"

Route123_Text_FernandoRematchIntro:
	.string "{JPN}きょうこそ やって みせる!\nうたいおわる まえに きみを\lしずめて みせるぜ!$"

Route123_Text_FernandoRematchDefeat:
	.string "{JPN}おい まてよ!\nまだ サビにも いって いないぞ!$"

Route123_Text_FernandoPostRematch:
	.string "{JPN}おれの きょくに みとれて まけるかと\nおもったのにな。$"

Route123_Text_DavisIntro:
	.string "{JPN}これが ぼくの すごい むしポケモン!\nおにいちゃんに もらったんだ。$"

Route123_Text_DavisDefeat:
	.string "{JPN}わあああん!\nいじわる!$"

Route123_Text_DavisPostBattle:
	.string "{JPN}まけた ことは おにいちゃんに\nいわないでよ。 ないしょだからね!$"

Route123_Text_JazmynIntro:
	.string "{JPN}あきらかに つよそうな あいてに かてば\nじしんが つくと いう ものだ!$"

Route123_Text_JazmynDefeat:
	.string "{JPN}じしんが なくなった…$"

Route123_Text_JazmynPostBattle:
	.string "{JPN}ひとは みかけで はんだん できないと\nいう。\pだが みかけは あんがい ただしい ものだ…$"

Route123_Text_FrederickIntro:
	.string "{JPN}やあ ぼうや!\nすこし じかんは あるかね?$"

Route123_Text_FrederickDefeat:
	.string "{JPN}ほう なかなか できる こどもだ!\nこづかいの たしに して くれたまえ。$"

Route123_Text_FrederickPostBattle:
	.string "{JPN}こづかいの たしにって?\nしょうきんでは たりなかったのか?$"

Route123_Text_AlbertoIntro:
	.string "{JPN}いって おくが おれは とりポケモンに\nむちゅうなんだ!\pとりは かっこいい!\nさいこうだ!$"

Route123_Text_AlbertoDefeat:
	.string "{JPN}まけても とりポケモンは かっこいい!$"

Route123_Text_AlbertoPostBattle:
	.string "{JPN}しょうぶで ちる とりポケモンの はねを あつめて\nいるんだ。\pとりポケモンの はねで ぼうしを\nつくるのさ。$"

Route123_Text_EdIntro:
	.string "{JPN}トレーナーが いない ときは ポケモンどうしを\nたたかわせて いるんだ。\lそれを ながめて いる。$"

Route123_Text_EdDefeat:
	.string "{JPN}きみの ポケモン なかなか いいな。$"

Route123_Text_EdPostBattle:
	.string "{JPN}へへ きみの たたかいかたを いただくよ!\nそのほうが つよく なれそうだ。$"

Route123_Text_JonasIntro:
	.string "{JPN}まちぶせて いたら トレーナーが\nわなに かかったぞ!$"

Route123_Text_JonasDefeat:
	.string "{JPN}きみが まけて くれないと\nにんじゃごっこが たのしめないよ?$"

Route123_Text_JonasPostBattle:
	.string "{JPN}つぎは もっと よわそうな トレーナーを\nまちぶせよう。$"

Route123_Text_KayleyIntro:
	.string "{JPN}この ひがさ かったばかりなの。\nかわいさが 3わり ましね!$"

Route123_Text_KayleyDefeat:
	.string "{JPN}あなたは わたしの 5ばい\nつよいわ!$"

Route123_Text_KayleyPostBattle:
	.string "{JPN}かざりを うまく つかうのが\nおしゃれの ひけつなの。$"

Route124_Text_SpencerIntro:
	.string "{JPN}おい うみで まよったのか?\pおれの ポケモンに かてたら\nみちあんないを して やろう。$"

Route124_Text_SpencerDefeat:
	.string "{JPN}しょうぶで まよって しまった!$"

Route124_Text_SpencerPostBattle:
	.string "{JPN}うみで まよう ひとは おおい。\pそういう ときは ポケナビの タウンマップを\nみると いい。$"

Route124_Text_RolandIntro:
	.string "{JPN}ほう! じぶんで およがずに\nポケモンに のって いるのか…\pうらやましいな!$"

Route124_Text_RolandDefeat:
	.string "{JPN}ああ!\nだめだ…$"

Route124_Text_RolandPostBattle:
	.string "{JPN}からだが ひえて きた…\nみずに つかりすぎたな…\pきみのように ポケモンに のりたいものだ…$"

Route124_Text_JennyIntro:
	.string "{JPN}こうして うみに うかんで いると\nポケモンが あそびに くるの。$"

Route124_Text_JennyDefeat:
	.string "{JPN}あら いやだ。\nまけちゃったわ。$"

Route124_Text_JennyPostBattle:
	.string "{JPN}およいで いると こうげきして くる ポケモンも\nみて いるだけの ポケモンも いるの。\pポケモンにも せいかくが\nあるのね。$"

Route124_Text_JennyRegister:
	.string "{JPN}きまぐれだけど ポケナビに\nとうろく して もらおうかしら。$"

Route124_Text_JennyRematchIntro:
	.string "{JPN}こうして うみに うかんで いると\nトレーナーが しょうぶを いどんで くるの!$"

Route124_Text_JennyRematchDefeat:
	.string "{JPN}おかしいわね…\nまた まけて しまった…$"

Route124_Text_JennyPostRematch:
	.string "{JPN}かんけいない けど カラクリやしきに\nいって みようかしら。$"

Route124_Text_GraceIntro:
	.string "{JPN}およぐのに あきて きたわ…\nしょうぶでも しない?$"

Route124_Text_GraceDefeat:
	.string "{JPN}こんなに つよいなんて\nおもわなかった!$"

Route124_Text_GracePostBattle:
	.string "{JPN}つみかさねた どりょくが\nあなたを つよく したのね。$"

Route124_Text_ChadIntro:
	.string "{JPN}ふふふ… ふかく もぐって\nすがたを かくす。\lふかい ところこそ わが しょうちだ!$"

Route124_Text_ChadDefeat:
	.string "{JPN}ごぼ ごぼ ごぼ…\nしずんで いく…$"

Route124_Text_ChadPostBattle:
	.string "{JPN}この あたりに ダイビングの ばしょが あると\nたしかな すじから きいた。\pまた もぐりたく なって\nきたぞ…$"

Route124_Text_LilaIntro:
	.string "{JPN}リラ: はあ…\pせっかく うみに きたのに となりに\nいるのは おとうとだけ!\pいやな ことを わすれるために\nしょうぶ しましょう!$"

Route124_Text_LilaDefeat:
	.string "{JPN}リラ: ロイ! あなたの せいで まけたのよ!\nあとで おぼえて なさい!$"

Route124_Text_LilaPostBattle:
	.string "{JPN}リラ: はあ…\pとなりに いるのが おとうとじゃ なくて\nすてきな かれしだったらな…$"

Route124_Text_LilaNotEnoughMons:
	.string "{JPN}リラ: わたしたちと しょうぶ するの?\nポケモンが 2ひき いないと むりよ。$"

Route124_Text_RoyIntro:
	.string "{JPN}ロイ: おねえちゃんは ポケモンが つよいんだ!\pまけても ないちゃ だめだよ!$"

Route124_Text_RoyDefeat:
	.string "{JPN}ロイ: あーあ…\nおねえちゃんに おこられる…$"

Route124_Text_RoyPostBattle:
	.string "{JPN}ロイ: おねえちゃんは おこると ほんとうに\nこわいんだ。\pだから かれしが\nできないんだよ。$"

Route124_Text_LilaRoyRegister:
	.string "{JPN}ロイ: また しょうぶ して くれる?\nつぎは てかげん して ね?$"

Route124_Text_RoyNotEnoughMons:
	.string "{JPN}ロイ: ぼくらと しょうぶ したいの?\nそれなら ポケモンを 2ひき つれて きて。$"

Route124_Text_LilaRematchIntro:
	.string "{JPN}リラ: はあ…\pせっかく うみに きたのに となりに\nいるのは おとうとだけ!\pあら ひさしぶりね。 いやな ことを\nわすれるために しょうぶ しましょう!$"

Route124_Text_LilaRematchDefeat:
	.string "{JPN}リラ: ロイ!\nまた あなたの せいで まけたのよ!\pあとで とっくんね!$"

Route124_Text_LilaPostRematch:
	.string "{JPN}リラ: はあ…\pすてきな かれしが いたら すばらしい\nコンビネーションで だれにでも かてるのに…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "{JPN}リラ: わたしたちと しょうぶ するの?\nポケモンが 2ひき いないと むりよ。$"

Route124_Text_RoyRematchIntro:
	.string "{JPN}ロイ: まけたら おこられる。\nぜんりょくで いくよ!$"

Route124_Text_RoyRematchDefeat:
	.string "{JPN}ロイ: あーあ…\nまた おねえちゃんに おこられる。$"

Route124_Text_RoyPostRematch:
	.string "{JPN}ロイ: おねえちゃんは おこると\nほんとうに こわいんだ。\pあとで ポケモンの とっくんを\nさせられるよ…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "{JPN}ロイ: ぼくらと しょうぶ したいの?\nそれなら ポケモンを 2ひき つれて きて。$"

Route124_Text_DeclanIntro:
	.string "{JPN}こんなに ひろくて きれいな うみを\nひとりで およいで いる。\pほかに いいようが ない。\nなさけない!$"

Route124_Text_DeclanDefeat:
	.string "{JPN}きぶんが しずむ。\nそらの ように あおく…$"

Route124_Text_DeclanPostBattle:
	.string "{JPN}おんなの ひとに こえを かけて\nとおおよぎに さそって みるか。$"

Route124_Text_IsabellaIntro:
	.string "{JPN}なみのりの トレーナーなんかに\nまける ものか。$"

Route124_Text_IsabellaDefeat:
	.string "{JPN}めに あせが はいっただけだ!\nないて なんか いないぞ!$"

Route124_Text_IsabellaPostBattle:
	.string "{JPN}この あたりでは きれいな いろの\nかけらが みつかるんだ。$"

Route125_Text_NolenIntro:
	.string "{JPN}ちかづいて くる おとが きこえたから\nまって いたんだ!$"

Route125_Text_NolenDefeat:
	.string "{JPN}こうさん!$"

Route125_Text_NolenPostBattle:
	.string "{JPN}おとは くうきの なかより みずの なかの\nほうが はやく つたわるんだ。$"

Route125_Text_StanIntro:
	.string "{JPN}やあ!\nわたしの かわいい ポケモンを みて!$"

Route125_Text_StanDefeat:
	.string "{JPN}うまく いかなかったわ…$"

Route125_Text_StanPostBattle:
	.string "{JPN}タッツーの かわいさに やられて\nわたしも およぐように なったの。$"

Route125_Text_TanyaIntro:
	.string "{JPN}およぐのに つかれたわ。\nしょうぶでも して くれない?$"

Route125_Text_TanyaDefeat:
	.string "{JPN}つよすぎるわ!$"

Route125_Text_TanyaPostBattle:
	.string "{JPN}ふう…\nトクサネシティは どっちかしら?$"

Route125_Text_SharonIntro:
	.string "{JPN}そだてた みずタイプの ポケモンと\nしょうぶ して みないか?$"

Route125_Text_SharonDefeat:
	.string "{JPN}まけた…$"

Route125_Text_SharonPostBattle:
	.string "{JPN}その ちから… ほんものだな。\nおどろいたよ!$"

Route125_Text_ErnestIntro:
	.string "{JPN}おう! おれは たくましい ふなのりだ!\nせかいじゅうの うみを こえて きた!$"

Route125_Text_ErnestDefeat:
	.string "{JPN}ぐおおお!\nかてなかった!$"

Route125_Text_ErnestPostBattle:
	.string "{JPN}すいちゅうどうくつでは しおが\nみちたり ひいたり するんだ。\pちなみに まんちょうから かんちょうまでは\nおよそ 6じかん。 しって いたかい?$"

Route125_Text_ErnestRegister:
	.string "{JPN}ポケナビに とうろく して くれたら\nいい ことを おしえて やろう。$"

Route125_Text_ErnestRematchIntro:
	.string "{JPN}そろそろ かりを かえす ときだ!\nさあ しょうぶだ!$"

Route125_Text_ErnestRematchDefeat:
	.string "{JPN}かてなかった!\nまるで かてなかった!$"

Route125_Text_ErnestRematchPostBattle:
	.string "{JPN}すいちゅうどうくつ…\pしおの みちひきで いける ところと\nいけない ところが\lあるんだ。\pちなみに まんちょうから かんちょうまでは\nおよそ 6じかん。 わすれるなよ!$"

Route125_Text_KimIntro:
	.string "{JPN}キム: すいちゅうどうくつに おもしろい\nおじいさんが いるんだって。\lあなたも あいに いくの?$"

Route125_Text_KimDefeat:
	.string "{JPN}キム: かてると おもったのに。$"

Route125_Text_KimPostBattle:
	.string "{JPN}キム: すいちゅうどうくつに おもしろい\nおじいさんが いるのよね?\pアイリス あいに いきましょう!$"

Route125_Text_KimNotEnoughMons:
	.string "{JPN}キム: だめだめ! ポケモンが 2ひき\nいないと しょうぶ できないわ!$"

Route125_Text_IrisIntro:
	.string "{JPN}アイリス: キム わたしたち なにを\nさがして いるのか おしえて くれる?$"

Route125_Text_IrisDefeat:
	.string "{JPN}アイリス: あら おしかったわね。$"

Route125_Text_IrisPostBattle:
	.string "{JPN}アイリス: キム ほんとうに すいちゅう\nどうくつに はいるの?\lびしょぬれに なっちゃう。$"

Route125_Text_IrisNotEnoughMons:
	.string "{JPN}アイリス: あら 2たい1の しょうぶなんて\nとても できないわ。$"

Route125_Text_PresleyIntro:
	.string "{JPN}とりつかいの おれが なぜ うみに\nきて いると おもう?$"

Route125_Text_PresleyDefeat:
	.string "{JPN}よし。\nわけを おしえて やろう。$"

Route125_Text_PresleyPostBattle:
	.string "{JPN}ビンに てがみを いれて うみに\nながしたんだ。\pきっと およぎが とくいな おんなのこが みつけて\nくれるはずさ!$"

Route125_Text_AuronIntro:
	.string "{JPN}おい! うみに ごみを すてたのは\nおまえか?$"

Route125_Text_AuronDefeat:
	.string "{JPN}そうか ごみを すてたのでは\nなかったのか。$"

Route125_Text_AuronPostBattle:
	.string "{JPN}さっき なみに ゆれる みぐるしい ビンを\nみつけたんだ。\pうみを よごす やつが いるとは\nはらが たつ!$"

Route126_Text_BarryIntro:
	.string "{JPN}すいえいは ぜんしんの うんどう!\nからだが しあがるぞ!$"

Route126_Text_BarryDefeat:
	.string "{JPN}みとめよう!\nきみの かちだ!$"

Route126_Text_BarryPostBattle:
	.string "{JPN}まいにちの すいえいの おかげだ…\nみろ! この からだを!$"

Route126_Text_DeanIntro:
	.string "{JPN}この しろくて たかい いわやまが\nルネシティだ。$"

Route126_Text_DeanDefeat:
	.string "{JPN}やられたか?$"

Route126_Text_DeanPostBattle:
	.string "{JPN}ルネへの いりぐちが みつからない。\nどこに あるのだろう?$"

Route126_Text_NikkiIntro:
	.string "{JPN}うふふふ!\nわたしは にんぎょよ!$"

Route126_Text_NikkiDefeat:
	.string "{JPN}ゆめが あわのように はじけたわ!\nぶくぶく…$"

Route126_Text_NikkiPostBattle:
	.string "{JPN}こてんぱんね… ぜつぼうの なみに\nのまれて きえて しまいたい…$"

Route126_Text_BrendaIntro:
	.string "{JPN}やあ ぼうや!\nわたしと しょうぶ しない?$"

Route126_Text_BrendaDefeat:
	.string "{JPN}ああ そんなあ!$"

Route126_Text_BrendaPostBattle:
	.string "{JPN}こうして うみで ポケモンと あそぶのが\nだいすきなの!$"

Route126_Text_PabloIntro:
	.string "{JPN}この きたえた からだを みろ!\nからておうより ひきしまって いるぞ!$"

Route126_Text_PabloDefeat:
	.string "{JPN}おっと つよすぎる!\nなかなか やるな! たいした ものだ!$"

Route126_Text_PabloPostBattle:
	.string "{JPN}きみに まけて めが さめた!\nじぶんも ポケモンも もっと きたえるぞ!$"

Route126_Text_PabloRegister:
	.string "{JPN}うむ なかなか やるな!\nもっと きみを しりたいものだ!$"

Route126_Text_PabloRematchIntro:
	.string "{JPN}この うつくしい からだを みて!\nスイマーより ひきしまって いるでしょう!$"

Route126_Text_PabloRematchDefeat:
	.string "{JPN}おっと ほんとうに つよいわ!\nやるわね! たいした ものよ!$"

Route126_Text_PabloPostRematch:
	.string "{JPN}もっと きたえるわ!\nあなたは いい はげみに なる!\lまた きて くれなくちゃ!$"

Route126_Text_LeonardoIntro:
	.string "{JPN}きょねんまで およげなかったのに\nいまでは そこそこの スイマーよ。\pいまなら なんでも できる きが するわ。$"

Route126_Text_LeonardoDefeat:
	.string "{JPN}やれやれ よくばっても\nなにも いい ことは なかったわ。$"

Route126_Text_LeonardoPostBattle:
	.string "{JPN}れんしゅうを すれば かならず\nじょうずに なるわ。\pわかいんだから いろいろな ことに\nおそれずに ちょうせん してね!$"

Route126_Text_IsobelIntro:
	.string "{JPN}うみの みずが はなに はいると\nつらいと おもわない?$"

Route126_Text_IsobelDefeat:
	.string "{JPN}うっ この…\nごぼっ!$"

Route126_Text_IsobelPostBattle:
	.string "{JPN}ああ みずを のんで しまった!\nにがい! しょっぱい!$"

Route126_Text_SiennaIntro:
	.string "{JPN}こころを こめて\nたたかうわ!$"

Route126_Text_SiennaDefeat:
	.string "{JPN}あなたの ほうが こころが つよかったわ!$"

Route126_Text_SiennaPostBattle:
	.string "{JPN}あたまを ひやさないと…\nもぐって こようかしら。$"

Route127_Text_CamdenIntro:
	.string "{JPN}かおを みれば わかるわ。\nしょうぶを いどみたいのね。$"

Route127_Text_CamdenDefeat:
	.string "{JPN}あわわわわ…$"

Route127_Text_CamdenPostBattle:
	.string "{JPN}いい しょうぶの あとは\nこころが すっきりと おちつくわ。$"

Route127_Text_DonnyIntro:
	.string "{JPN}どうしても まけたく ない ライバルは\nいるかしら?$"

Route127_Text_DonnyDefeat:
	.string "{JPN}ああ もう!\nまけるのは きらい!$"

Route127_Text_DonnyPostBattle:
	.string "{JPN}ライバルが いると もっと つよく\nならなくちゃと いう きに\lならないかしら?$"

Route127_Text_JonahIntro:
	.string "{JPN}つりを つうじて しずかな こころに\nたどりついた…\pさあ みせて しんぜよう…$"

Route127_Text_JonahDefeat:
	.string "{JPN}まけては しまったが こころは\nしずかな ままだ…$"

Route127_Text_JonahPostBattle:
	.string "{JPN}なにも つれなくても かまわない。\nいとを みずに たらして いれば よいのだ…$"

Route127_Text_HenryIntro:
	.string "{JPN}おっと! なみのりの ポケモンを\nひっかけて しまったか?$"

Route127_Text_HenryDefeat:
	.string "{JPN}ついて いけない!$"

Route127_Text_HenryPostBattle:
	.string "{JPN}きみの つよい ポケモンが かかったら\nてに おえないな!$"

Route127_Text_RogerIntro:
	.string "{JPN}おっ! ポケモンずきと つりずきの\nしょうぶだな!$"

Route127_Text_RogerDefeat:
	.string "{JPN}ああ! いとが からまった!\nおしまいだ!$"

Route127_Text_RogerPostBattle:
	.string "{JPN}つりいとが おどって いる!\nからまりダンスだ! はははは!$"

Route127_Text_AidanIntro:
	.string "{JPN}とりポケモンは めが いい。\nたかい そらから えものを みつけるんだ。$"

Route127_Text_AidanDefeat:
	.string "{JPN}ふう… こうさんだ。$"

Route127_Text_AidanPostBattle:
	.string "{JPN}この あたりの うみには もぐれる ばしょが\nたくさん ある。\pいろが こいから そらから みると\nすぐに わかるぞ。$"

Route127_Text_KojiIntro:
	.string "{JPN}はだしで はしるんだ。\nあしの うらが きたえられるぞ!$"

Route127_Text_KojiDefeat:
	.string "{JPN}いてっ!\nつめの したに いしが はいった!$"

Route127_Text_KojiPostBattle:
	.string "{JPN}はだしは きもちが いい。\nだが きみの ランニングシューズも いいな。$"

Route127_Text_KojiRegister:
	.string "{JPN}かった あいてには こう するんだ!\nまた しょうぶ しような。$"

Route127_Text_KojiRematchIntro:
	.string "{JPN}いまでも まいにち はだしで はしって いる。\nあしの うらは じょうぶだぞ!$"

Route127_Text_KojiRematchDefeat:
	.string "{JPN}いてっ!\nどかんに いしが くいこんだ!$"

Route127_Text_KojiPostRematch:
	.string "{JPN}すこし はだしに なって みないか?\nかわりに ランニングシューズを ためしたい。$"

Route127_Text_AthenaIntro:
	.string "{JPN}ゆっくり じっくり しょうぶ\nしよう。$"

Route127_Text_AthenaDefeat:
	.string "{JPN}さくせんを かんがえる ひまも\nなかった。$"

Route127_Text_AthenaPostBattle:
	.string "{JPN}あおい うみと そらに かこまれて いると\nときが ゆっくり ながれる きが する。$"

Route128_Text_IsaiahIntro:
	.string "{JPN}サイユウシティは まだまだ\nさきだ…$"

Route128_Text_IsaiahDefeat:
	.string "{JPN}はじめての しょうりも まだまだ\nさきだな…$"

Route128_Text_IsaiahPostBattle:
	.string "{JPN}まけてばかりの じんせいだけど\nぜったいに あきらめないぞ!$"

Route128_Text_IsaiahRegister:
	.string "{JPN}いまは よわいけど いつかは かてると\nおもって いるんだ。\pポケナビに とうろく して くれよ。$"

Route128_Text_IsaiahRematchIntro:
	.string "{JPN}まだまだ げんきだ。 サイユウシティまで\nおよぎつづけるぞ。$"

Route128_Text_IsaiahRematchDefeat:
	.string "{JPN}はじめての しょうりを まだ しらない…$"

Route128_Text_IsaiahPostRematch:
	.string "{JPN}いつかは サイユウシティに たどりつく。\nそこで いつかは かつんだ…$"

Route128_Text_KatelynIntro:
	.string "{JPN}トライアスロンは およいで こいで\nそれから マラソンを はしるんだ。\pみっつの きょうぎからなる\nきびしい レースだ。$"

Route128_Text_KatelynDefeat:
	.string "{JPN}ポケモンの しょうぶも きびしいな…$"

Route128_Text_KatelynPostBattle:
	.string "{JPN}つぎは じてんしゃだが…\nもう ギブアップ しそうだ…$"

Route128_Text_KatelynRegister:
	.string "{JPN}まあ せっかくだから たのしむよ。\nまた しょうぶ したいな。$"

Route128_Text_KatelynRematchIntro:
	.string "{JPN}トライアスロンは ながい。 だが ポケモンの\nチャンピオンへの みちも ながく きびしい\lものなんだろうな。$"

Route128_Text_KatelynRematchDefeat:
	.string "{JPN}ポケモンの しょうぶは ほんとうに\nきびしくて ようしゃが ないな…$"

Route128_Text_KatelynPostRematch:
	.string "{JPN}チャンピオンロードへの ちょうせんを\nしんけんに かんがえた ほうが いい。$"

Route128_Text_AlexaIntro:
	.string "{JPN}ポケモンリーグに いどむため\nずっと がんばって きたんだ…\pここで まける わけには いかない!$"

Route128_Text_AlexaDefeat:
	.string "{JPN}ああ!\nどうして こんな ことに!$"

Route128_Text_AlexaPostBattle:
	.string "{JPN}ここまで きたんだ。\nいちど まけたくらいで あきらめない。$"

Route128_Text_RubenIntro:
	.string "{JPN}わたしより つよい トレーナーは いない!$"

Route128_Text_RubenDefeat:
	.string "{JPN}そんな ばかな!$"

Route128_Text_RubenPostBattle:
	.string "{JPN}きみより つよい トレーナーは\nいないかも しれないな!$"

Route128_Text_WayneIntro:
	.string "{JPN}サイユウシティへ いきたくて たきのぼりを\nおぼえた ポケモンを つかまえたんだ。\lたきを のぼる ためにね。$"

Route128_Text_WayneDefeat:
	.string "{JPN}がっくりだ!$"

Route128_Text_WaynePostBattle:
	.string "{JPN}ああ もう!\pポケモンは たきのぼりを おぼえたのに\nルネジムの バッジが ない!$"

Route128_Text_HarrisonIntro:
	.string "{JPN}ずいぶん つよそうだね。\nわたしに かてるかしら?$"

Route128_Text_HarrisonDefeat:
	.string "{JPN}いたた!\nやっぱり むりだったのね。$"

Route128_Text_HarrisonPostBattle:
	.string "{JPN}サイユウの あたりには つよい トレーナーが\nたくさん いるわ。\pわたしには\nばあいちがいかしら?$"

Route128_Text_CarleeIntro:
	.string "{JPN}この あたりは ひざしが きつい\nみたいね。$"

Route128_Text_CarleeDefeat:
	.string "{JPN}ひざしが まぶしくて よく\nみえなかったわ。$"

Route128_Text_CarleePostBattle:
	.string "{JPN}そろそろ もどらないと。\nひやけどめを ぬりなおさなくちゃ。$"

Route129_Text_ChaseIntro:
	.string "{JPN}はじめての トライアスロンなんだ。\nきんちょうして いるよ!$"

Route129_Text_ChaseDefeat:
	.string "{JPN}ぐおおお!\nかてなかった!$"

Route129_Text_ChasePostBattle:
	.string "{JPN}きんちょうして いたら ぜんりょくを\nだせないな。$"

Route129_Text_AllisonIntro:
	.string "{JPN}トライアスロンの とちゅうだが\nしょうぶでも しようか?$"

Route129_Text_AllisonDefeat:
	.string "{JPN}かてると おもったのに!$"

Route129_Text_AllisonPostBattle:
	.string "{JPN}トライアスロンの いちばん いい ところが\nなにか わかるかい?\pしぜんを あいてに じぶんの ちからと\nがまんづよさの げんかいを\lためせる ことさ!$"

Route129_Text_ReedIntro:
	.string "{JPN}よお よお!\nさっさと はじめようぜ!$"

Route129_Text_ReedDefeat:
	.string "{JPN}のされた のされた。\nこれで おしまいだ!$"

Route129_Text_ReedPostBattle:
	.string "{JPN}まけた ものに のこる ものは ない。\nそろそろ かえると するか。$"

Route129_Text_TishaIntro:
	.string "{JPN}なにを いそいで いるの?\nゆっくり いきましょう。$"

Route129_Text_TishaDefeat:
	.string "{JPN}あらまあ。\nもうすこし のんびり したかったのに…$"

Route129_Text_TishaPostBattle:
	.string "{JPN}いそいで いると しっぱい しがちだと\nおもわない?\pだから わたしは ゆっくり\nやる ことに して いるの。$"

Route129_Text_ClarenceIntro:
	.string "{JPN}なみのりは みかけほど かんたんじゃ ない。\nそう おもわない?$"

Route129_Text_ClarenceDefeat:
	.string "{JPN}かつのも かんたんじゃ ないわね。$"

Route129_Text_ClarencePostBattle:
	.string "{JPN}ポケモンリーグを めざして いるの?\nがんばってね!$"

Route130_Text_RodneyIntro:
	.string "{JPN}おどろいた! うみで トレーナーに あうとは\nおもわなかった。\pこれは しょうぶ するしか ないな!$"

Route130_Text_RodneyDefeat:
	.string "{JPN}この こ とんでもなく つよいな…$"

Route130_Text_RodneyPostBattle:
	.string "{JPN}きみの めは きびしい しれんを\nこえて きた ものの めだ。\lよく にあって いるよ!$"

Route130_Text_KatieIntro:
	.string "{JPN}ふかい あおい うみで\nくだけた あおい こころが\lなみに いやされる。$"

Route130_Text_KatieDefeat:
	.string "{JPN}ひろい あおい うみのように\nポケモンの せかいも\lしんじられぬほど ふかい。$"

Route130_Text_KatiePostBattle:
	.string "{JPN}せかいじゅうの こどもが\nいつか ポケモンチャンピオンに\lなる ゆめを みる。$"

Route130_Text_SantiagoIntro:
	.string "{JPN}こうして うみに うかんで いると…\nおだやかだな。$"

Route130_Text_SantiagoDefeat:
	.string "{JPN}すこし おだやか すぎたか!$"

Route130_Text_SantiagoPostBattle:
	.string "{JPN}およいで しょうぶ して…\nしあわせな ものだ…$"

Route131_Text_RichardIntro:
	.string "{JPN}うみは ポケモンで いっぱいだ。\nおよぐのも らくじゃ ないぞ。$"

Route131_Text_RichardDefeat:
	.string "{JPN}トレーナーに そだてられた ポケモンは\nとんでもなく つよいな…$"

Route131_Text_RichardPostBattle:
	.string "{JPN}はあ はあ…\nへとへとだ…\pいきは よいよい かえりは\nこわい。\pかえりの ちからは のこって\nいるかな?$"

Route131_Text_HermanIntro:
	.string "{JPN}うみ うみ うみ…\nみわたす かぎり うみ!\lうみは もう うんざりだ!$"

Route131_Text_HermanDefeat:
	.string "{JPN}うええ!$"

Route131_Text_HermanPostBattle:
	.string "{JPN}うみに あきても およがずには いられない。\pうまれつきの スイマーなんだ!\nそういう ものさ。$"

Route131_Text_SusieIntro:
	.string "{JPN}ちょっと まって かわいこちゃん!\nわたしと しょうぶ しましょう!$"

Route131_Text_SusieDefeat:
	.string "{JPN}みかけに よらず\nつよいのね!$"

Route131_Text_SusiePostBattle:
	.string "{JPN}むこうで うみに あきたと ぼやいて いる\nおとこの ひとを みた?\pあれは くちだけよ。\nどうしようもなく うみが すきなの!$"

Route131_Text_KaraIntro:
	.string "{JPN}どうして おとこの ひとは みずぎが\nそんなに すきなの?\pみんな じろじろ みるのよ!$"

Route131_Text_KaraDefeat:
	.string "{JPN}てが とどかないわ!$"

Route131_Text_KaraPostBattle:
	.string "{JPN}みずぎでは なくて わたしの うつくしさを\nみて いるのかも しれないわ!$"

Route131_Text_ReliIntro:
	.string "{JPN}レリ: きょうだいで ちからを あわせて\nあいてに なるわ!$"

Route131_Text_ReliDefeat:
	.string "{JPN}レリ: ちからを あわせても\nかてなかったわ…$"

Route131_Text_ReliPostBattle:
	.string "{JPN}レリ: キナギの ひとは うまれた ときから\nうみと ポケモンと\lいっしょなの。$"

Route131_Text_ReliNotEnoughMons:
	.string "{JPN}レリ: ポケモンが 2ひき いないの?\nそれでは しょうぶを たのしめないわ。$"

Route131_Text_IanIntro:
	.string "{JPN}イアン: ねえさんと いっしょに\nがんばるぞ!$"

Route131_Text_IanDefeat:
	.string "{JPN}イアン: ねえさんと がんばったけど\nやっぱり かてなかった…$"

Route131_Text_IanPostBattle:
	.string "{JPN}イアン: キナギタウンが うかんで いる\nまちだって しって る?\pだから うみが ある ところは\nぜんぶ キナギタウンなんだ!$"

Route131_Text_IanNotEnoughMons:
	.string "{JPN}イアン: ポケモンが 2ひき いれば\nあいてに なるよ!$"

Route131_Text_TaliaIntro:
	.string "{JPN}おれに かてたら いい ことを\nおしえて やろう!$"

Route131_Text_TaliaDefeat:
	.string "{JPN}おや?\nまけたのか?$"

Route131_Text_TaliaPostBattle:
	.string "{JPN}この ちかくに かわった ばしょが ある。\nおおきな とうが たって いるんだ。\lいって みると いい。$"

Route131_Text_KevinIntro:
	.string "{JPN}キナギの ひとは\nおだやかなんだ。\pけっして おこらない。 おれも\nそうだ。$"

Route131_Text_KevinDefeat:
	.string "{JPN}おっと!$"

Route131_Text_KevinPostBattle:
	.string "{JPN}ちっ! …いや まて。\nおこって なんか いないぞ。 ほんとうだ!\pそれにしても つよいな!\nはははは!$"

Route132_Text_GilbertIntro:
	.string "{JPN}こどもの ころは よく かぜを ひいたが\nおよぐように なってからは じょうぶに\lなったんだ。$"

Route132_Text_GilbertDefeat:
	.string "{JPN}もっと ちからが ほしい…$"

Route132_Text_GilbertPostBattle:
	.string "{JPN}トレーナーは のはらや やまを たびする。\nだから じょうぶな はずだな。$"

Route132_Text_DanaIntro:
	.string "{JPN}ながれの つよい ところでは\nおよがない ように して いるの。$"

Route132_Text_DanaDefeat:
	.string "{JPN}ああ そんな!$"

Route132_Text_DanaPostBattle:
	.string "{JPN}ながされたら いまどこに いるのか\nわからなく なって しまうわ…$"

Route132_Text_RonaldIntro:
	.string "{JPN}かつか まけるかは やって みないと\nわからないわ!$"

Route132_Text_RonaldDefeat:
	.string "{JPN}わあ!\nまけて しずんで しまうわ!$"

Route132_Text_RonaldPostBattle:
	.string "{JPN}かつと わかって いる しょうぶは しないの。\nかちと まけの きわどい ところが\lすきなのよ!$"

Route132_Text_KiyoIntro:
	.string "{JPN}ポケモンの ことを 1にちじゅう かんがえて いる。\nきみに かてる はずが ないだろう?$"

Route132_Text_KiyoDefeat:
	.string "{JPN}まけだ。\nまけを みとめよう。$"

Route132_Text_KiyoPostBattle:
	.string "{JPN}うう…\nきみは ポケモンきちがいだな?\pきっと 1にちじゅう ポケモンの ことを\nかんがえて いるのだろう?$"

Route132_Text_MakaylaIntro:
	.string "{JPN}いつも おっとと いっしょだけど\nひとりでも かてるのよ。$"

Route132_Text_MakaylaDefeat:
	.string "{JPN}あら わたしでは たりなかったのね。$"

Route132_Text_MakaylaPostBattle:
	.string "{JPN}むこうに いる わかい ひとは\nわかい ころの おっとに そっくり。\pてれて しまうわ!$"

Route132_Text_JonathanIntro:
	.string "{JPN}だれかが じっと みて いるの。\nあなただったの?$"

Route132_Text_JonathanDefeat:
	.string "{JPN}まあ!\nずいぶん つよいのね!$"

Route132_Text_JonathanPostBattle:
	.string "{JPN}だれかに みられて いる きが して\nしかたないの。\pしゅうちゅう できないわ!$"

Route132_Text_PaxtonIntro:
	.string "{JPN}つまは どこへ いったのだろう?\nいつも いっしょに いるのに。\lひとりで かてるだろうか。$"

Route132_Text_PaxtonDefeat:
	.string "{JPN}ああ やはり ひとりでは\nかてなかったな。$"

Route132_Text_PaxtonPostBattle:
	.string "{JPN}つまが さがして いるだろう。\nすぐに さがしに いくと しよう。$"

Route132_Text_DarcyIntro:
	.string "{JPN}ここで ひとりで きたえるのが すきだった。\nひとが たくさん きて しまって いやだな!$"

Route132_Text_DarcyDefeat:
	.string "{JPN}わかった! ひとが いる ことに\nもんくは いわないよ。$"

Route132_Text_DarcyPostBattle:
	.string "{JPN}あの おじいさんと くんで\nむこうの ふたりに いどんで みるかな。$"

Route133_Text_FranklinIntro:
	.string "{JPN}きみも ながれに はこばれて きたのか?\nこれも えんだな。\lしょうぶ しよう!$"

Route133_Text_FranklinDefeat:
	.string "{JPN}つよい!\nつよすぎる!$"

Route133_Text_FranklinPostBattle:
	.string "{JPN}きみの ような つよい トレーナーが\nながれつくとは ついて いない…\lのろわれて いるのかも しれない…$"

Route133_Text_DebraIntro:
	.string "{JPN}なやみと かなしみの じんせい…\nすてられて ここに\lながれついたのだ…$"

Route133_Text_DebraDefeat:
	.string "{JPN}また まけた…$"

Route133_Text_DebraPostBattle:
	.string "{JPN}ながされる じんせい…\nもう いやだ!$"

Route133_Text_LindaIntro:
	.string "{JPN}ようこそ!\nまって いたぞ!$"

Route133_Text_LindaDefeat:
	.string "{JPN}だめだ! たのむ!$"

Route133_Text_LindaPostBattle:
	.string "{JPN}つよい こどもの トレーナー…\nいらいら するな!$"

Route133_Text_WarrenIntro:
	.string "{JPN}みんなと おなじように かちたい。\nでも みんなと おなじ そだてかたは しない。$"

Route133_Text_WarrenDefeat:
	.string "{JPN}くそっ!\nおれの やりかたは まだ あまいか!$"

Route133_Text_WarrenPostBattle:
	.string "{JPN}みんなと おなじに するより じぶんの\nやりたいように する ほうが ずっと たのしい。\lあたりまえの ことだろう!$"

Route133_Text_BeckIntro:
	.string "{JPN}とりポケモンと ともに\nこんな ところまで きたんだ。$"

Route133_Text_BeckDefeat:
	.string "{JPN}きみ…\nおどろく ほど かっこいいな!$"

Route133_Text_BeckPostBattle:
	.string "{JPN}ヒワマキに かえりたいが\nここも すきに なって しまった。$"

Route133_Text_MollieIntro:
	.string "{JPN}なんぜんかい しょうぶ したか\nもう かぞえて いない。$"

Route133_Text_MollieDefeat:
	.string "{JPN}なんぜんかい まけても\nまけは やはり くやしい ものだ。$"

Route133_Text_MolliePostBattle:
	.string "{JPN}わかいの がんばりなさい。 わたしや\nおっとの ように なれる ように。$"

Route133_Text_ConorIntro:
	.string "{JPN}わかい ひとは ながれに まかせすぎる。\nすすむ みちが さだまって いないのだ。$"

Route133_Text_ConorDefeat:
	.string "{JPN}きみには はっきりと めざす ものが あるな。$"

Route133_Text_ConorPostBattle:
	.string "{JPN}ひとに まどわされては いけない。\nとしを とっても みちを うしなわぬ ように。$"

Route134_Text_JackIntro:
	.string "{JPN}およげる ポケモンでさえ この はやい\nながれに はこばれて しまうんだ。$"

Route134_Text_JackDefeat:
	.string "{JPN}あいたたた!$"

Route134_Text_JackPostBattle:
	.string "{JPN}この あたりの はやい ながれを\nポケモンは たのしんで いると おもうんだ。$"

Route134_Text_LaurelIntro:
	.string "{JPN}うちの ラブカスが たのしい しょうぶを\nさがして いるの。 あいてに なって くれる?$"

Route134_Text_LaurelDefeat:
	.string "{JPN}あらら!$"

Route134_Text_LaurelPostBattle:
	.string "{JPN}ラブカスの ウロコを ほしがって いる\nコレクターが いるのよ。$"

Route134_Text_AlexIntro:
	.string "{JPN}よし! きゅうけいは おわりだ みんな!\nしょうぶの じかんだ!$"

Route134_Text_AlexDefeat:
	.string "{JPN}また ばてて しまった…$"

Route134_Text_AlexPostBattle:
	.string "{JPN}とりポケモンは ながく とんだあと\nすぐに つかれて しまうんだ…$"

Route134_Text_HitoshiIntro:
	.string "{JPN}きみは ポケモントレーナー。\nことばは いらぬ。 いざ しょうぶ。$"

Route134_Text_HitoshiDefeat:
	.string "{JPN}… … … … … …\n… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "{JPN}じぶんから いどんで おきながら まけるとは。\nふかく はじいる…$"

Route134_Text_AaronIntro:
	.string "{JPN}この あたりの あらい しおの ながれが\nわれらを より つよく するのだ。$"

Route134_Text_AaronDefeat:
	.string "{JPN}いさぎよく まけを みとめよう。$"

Route134_Text_AaronPostBattle:
	.string "{JPN}われらは りゅうせいのたきへ もどって\nきたえなおす。\pよければ きみも いくと よい。\nかならず つよく なれるぞ!$"

Route134_Text_KelvinIntro:
	.string "{JPN}ふ ふねが!\nしおに ながされて しまった!$"

Route134_Text_KelvinDefeat:
	.string "{JPN}あわわわわ!\nやめて たのむ!$"

Route134_Text_KelvinPostBattle:
	.string "{JPN}なみのりが できなければ どうやって\nかえれば いいんだ?\pひんしの ポケモンでも なみのりは\nできるが なんだか わるい きが する。$"

Route134_Text_MarleyIntro:
	.string "{JPN}われらの でんこうせっかの こうげきを\nきみの ポケモンは かわせるか?$"

Route134_Text_MarleyDefeat:
	.string "{JPN}そんな わざが あるとは しらなかった!\nみごとに やぶられたな。$"

Route134_Text_MarleyPostBattle:
	.string "{JPN}はやさへの じょうねつは うしなって いない。\nもっと はげむと しよう。$"

Route134_Text_ReynaIntro:
	.string "{JPN}わたしの ポケモンは そう かんたんには\nたおれないぞ!$"

Route134_Text_ReynaDefeat:
	.string "{JPN}うそだろう!\nどうして まけたのか せつめい してくれ!$"

Route134_Text_ReynaPostBattle:
	.string "{JPN}はは!\nきみの かちだ!\pであった トレーナーに いどんで\nはいあがって いくと するか!$"

Route134_Text_HudsonIntro:
	.string "{JPN}なあ この あたりで もうひとりの\nふなのりを みなかったか?$"

Route134_Text_HudsonDefeat:
	.string "{JPN}おお たいした ものだ!$"

Route134_Text_HudsonPostBattle:
	.string "{JPN}おれたちの ふねが うみに ながされたんだ。\pあいつは おくびょうだから\nしんぱいで しかたない。$"

VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "{JPN}じゅうでんが たりません。\pまんタンに するまでに ひつような ほすう\n{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "{JPN}ちかくに しょうぶ できる トレーナーは\nいません…\pサーチャーの でんげんを きりました。{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady::
	.string "{JPN}ほかの トレーナーは しょうぶの じゅんびが\nできて いないようです。\pあとで また しましょう。{PAUSE_UNTIL_PRESS}$"
