Route102_Text_CalvinIntro:
	.string "{JPN}ポケモンを つれて いるなら\nりっぱな ポケモントレーナー!\lわたしの しょうぶを ことわれないよ!$"

Route102_Text_CalvinDefeated:
	.string "{JPN}ああ まけた…\nもっと きたえて おくべきだった…$"

Route102_Text_CalvinPostBattle:
	.string "{JPN}ちょっと つよいなら\nさきに いって おいてよ!$"

Route102_Text_CalvinRegister:
	.string "{JPN}まえに あってから ずっと\nがんばって きたんだ。\pまた しょうぶ したいから ポケナビに\nとうろく して くれないかな?$"

Route102_Text_CalvinRegisterShort:
	.string "{JPN}また しょうぶ したいから ポケナビに\nとうろく して くれないかな?$"

Route102_Text_CalvinRematchIntro:
	.string "{JPN}きみに まけてから ひっしで\nポケモンを きたえて きた。\lしょうぶを ことわらせないよ!$"

Route102_Text_CalvinRematchDefeated:
	.string "{JPN}ああ まけた…\nきたえかたが まちがって いるのかな?$"

Route102_Text_CalvinRematchPostBattle:
	.string "{JPN}きみが つよく なるなら\nわたしも つよく なる。$"

Route102_Text_AllenIntro:
	.string "{JPN}トレーナーに なったばかり?\nおたがい しんまいだね!$"

Route102_Text_AllenDefeated:
	.string "{JPN}かてると おもって よんだのに…$"

Route102_Text_AllenPostBattle:
	.string "{JPN}まだ 1かいも かって いない…\nそろそろ かちたいなあ…$"

Route102_Text_RickIntro:
	.string "{JPN}ははっ めが あったね!\nむしポケモンで あいてに なるよ!$"

Route102_Text_RickDefeated:
	.string "{JPN}うっ のされた!$"

Route102_Text_RickPostBattle:
	.string "{JPN}トレーナーと めが あったら\nしょうぶ! それが ルール!$"

Route102_Text_TianaIntro:
	.string "{JPN}かちつづけて さいこうの トレーナーを\nめざすんだ。\pわたしの しゅっせに つきあって!$"

Route102_Text_TianaDefeated:
	.string "{JPN}きみの しゅっせを てつだって しまった…$"

Route102_Text_TianaPostBattle:
	.string "{JPN}かちあがるには もっと ポケモンを\nつかまえないと だめみたい。$"

Route103_Text_DaisyIntro:
	.string "{JPN}こころ やすらぐ かおりに\nひきよせられたの?$"

Route103_Text_DaisyDefeated:
	.string "{JPN}かおりに まどわされ なかったのね…$"

Route103_Text_DaisyPostBattle:
	.string "{JPN}アロマセラピーは かおりで こころを\nいやす ほうほうなの。$"

Route103_Text_AmyIntro:
	.string "{JPN}アミ: わたしは アミ。\nこちらは いもうとの リブ。\lふたりで たたかうの!$"

Route103_Text_AmyDefeated:
	.string "{JPN}アミ: あーあ まけちゃった。$"

Route103_Text_AmyPostBattle:
	.string "{JPN}アミ: トレーナー ふたりを あいてに\nするときは いろいろ かんがえないと\lいけないのよ。$"

Route103_Text_AmyNotEnoughPokemon:
	.string "{JPN}アミ: あら ポケモンが 1ぴきしか\nいないのね。\lそれでは しょうぶに ならないわ。$"

Route103_Text_LivIntro:
	.string "{JPN}リブ: わたしたち ひとつの チームで\nたたかうの。$"

Route103_Text_LivDefeated:
	.string "{JPN}リブ: ああ まけちゃった おねえちゃん…$"

Route103_Text_LivPostBattle:
	.string "{JPN}リブ: おねえちゃんとは ぴったり\nあうのに…\pそれでも まけちゃった…$"

Route103_Text_AmyLivRegister:
	.string "{JPN}リブ: ほんとは もっと つよいのよ…\nほんとだもん! こんどは みせて あげる!$"

Route103_Text_LivNotEnoughPokemon:
	.string "{JPN}リブ: わたしたちと しょうぶ するなら\nポケモンが 2ひき いるのよ!\lそうじゃないと ずるいわ!$"

Route103_Text_AmyRematchIntro:
	.string "{JPN}アミ: わたしは アミ。\nこちらは いもうとの リブ。\lふたりで たたかうの!$"

Route103_Text_AmyRematchDefeated:
	.string "{JPN}アミ: ああ もう!\nまた かてなかった…$"

Route103_Text_AmyRematchPostBattle:
	.string "{JPN}アミ: トレーナー ふたりを あいてに\nするときは いろいろ かんがえないと\lいけないのよ。$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "{JPN}アミ: あら ポケモンが 1ぴきしか\nいないのね。\lそれでは しょうぶに ならないわ。$"

Route103_Text_LivRematchIntro:
	.string "{JPN}リブ: わたしたち ひとつの チームで\nたたかうの。$"

Route103_Text_LivRematchDefeated:
	.string "{JPN}リブ: ああ また まけちゃった…\nおねえちゃん…$"

Route103_Text_LivRematchPostBattle:
	.string "{JPN}リブ: おねえちゃんとは ぴったり\nあうのに…\pどうして また まけたの?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "{JPN}リブ: わたしたちと しょうぶ するなら\nポケモンが 2ひき いるのよ!\lそうじゃないと ずるいわ!$"

Route103_Text_AndrewIntro:
	.string "{JPN}ぐあ! つりいとが からまった!\nいらいらして きたぞ!\lよし しょうぶだ!$"

Route103_Text_AndrewDefeated:
	.string "{JPN}ぐあ! まけた!\nますます いらいら するぞ!$"

Route103_Text_AndrewPostBattle:
	.string "{JPN}ぐぬぬ まだ はらが たつ…\nぐぬぬぬ…$"

Route103_Text_MiguelIntro:
	.string "{JPN}わたしの ポケモン とっても かわいいの!\nえんりょ しないで みて!$"

Route103_Text_MiguelDefeated:
	.string "{JPN}ああ そんな!\nかわいい わたしの ポケモン!$"

Route103_Text_MiguelPostBattle:
	.string "{JPN}わたしの ポケモンは ひんしに なっても\nかわいいの!$"

Route103_Text_MiguelRegister:
	.string "{JPN}また わたしの かわいい ポケモンを\nみに きて もらうんだから!$"

Route103_Text_MiguelRematchIntro:
	.string "{JPN}あら! わたしの かわいい ポケモンが\nもっと かわいく なったの!$"

Route103_Text_MiguelRematchDefeated:
	.string "{JPN}ああ!\nかわいい わたしの ポケモン!$"

Route103_Text_MiguelRematchPostBattle:
	.string "{JPN}いっしょに いる ときが ながいほど\nポケモンは かわいく なるの。$"

Route103_Text_PeteIntro:
	.string "{JPN}これくらいの きょりなら…\nおよいだら いいのに!$"

Route103_Text_PeteDefeated:
	.string "{JPN}やるじゃない!$"

Route103_Text_PetePostBattle:
	.string "{JPN}ああ きみの きもちが わかったわ。\pそんなに たよれる ポケモンが いたら\nわたしも なみのり したく なるもの!$"

Route103_Text_IsabelleIntro:
	.string "{JPN}まえを みて!\nぶつかっちゃう!$"

Route103_Text_IsabelleDefeated:
	.string "{JPN}うーん…$"

Route103_Text_IsabellePostBattle:
	.string "{JPN}およぎが へたで れんしゅう してたの…\nぶつかりそうに なって ごめんね。$"

Route103_Text_RhettIntro:
	.string "{JPN}うわっ!\nこんな せまい ところに よく きたな?$"

Route103_Text_RhettDefeated:
	.string "{JPN}うわっ!\nこの こ やるな!$"

Route103_Text_RhettPostBattle:
	.string "{JPN}こういう せまい ところが すきなのか?$"

Route103_Text_MarcosIntro:
	.string "{JPN}おれの ギターの ねに ひかれたか?$"

Route103_Text_MarcosDefeated:
	.string "{JPN}ひとりの ステージが だいなしだ…$"

Route103_Text_MarcosPostBattle:
	.string "{JPN}ひとの すくない ところで ひいて いたのに\nファンが たくさん あつまって きた。\lうれしいね。\pふふん プロに なろうかな。$"

Route104_Text_GinaIntro:
	.string "{JPN}ジナ: さあ ポケモンで しょうぶよ!$"

Route104_Text_GinaDefeat:
	.string "{JPN}ジナ: まけるのは くやしい!$"

Route104_Text_GinaPostBattle:
	.string "{JPN}ジナ: あなた つよいのね!\nもっと きたえないと!$"

Route104_Text_GinaNotEnoughMons:
	.string "{JPN}ジナ: あら? ポケモンが 1ぴきだけ?\nそれじゃ しょうぶ しないわ。\pポケモンが 1ぴきだと さびしいもの。\nかわいそうよ。$"

Route104_Text_MiaIntro:
	.string "{JPN}ミア: わたしたち ふたごだから\nいっしょに しょうぶ するの。$"

Route104_Text_MiaDefeat:
	.string "{JPN}ミア: ふたりで たたかったのに\nどっちも まけちゃった…$"

Route104_Text_MiaPostBattle:
	.string "{JPN}ミア: もっと ポケモンを きたえて\nあなたみたいに つよく なるわ。$"

Route104_Text_MiaNotEnoughMons:
	.string "{JPN}ミア: わたしたちと しょうぶ したいの?\pポケモンが 2ひき いないと だめよ。\lわたしたちのほうが つよいもの!$"

Route104_Text_IvanIntro:
	.string "{JPN}かくす ことは ない。\nおれは みずポケモンの めいじんだ!\pん?\nおれを しらないのか?$"

Route104_Text_IvanDefeat:
	.string "{JPN}そこそこ やれると おもって いたが\nそうでも なかったか… うう…$"

Route104_Text_IvanPostBattle:
	.string "{JPN}つりに むちゅうに なりすぎた。\nポケモンを そだてるのを わすれて いた…$"

Route104_Text_BillyIntro:
	.string "{JPN}すなはまに あしあとを のこすのが\nたのしいの!$"

Route104_Text_BillyDefeat:
	.string "{JPN}わあ! くつに すなが はいった!\nじゃりじゃり する!$"

Route104_Text_BillyPostBattle:
	.string "{JPN}どこにでも あしあとを のこしたいけど\nすぐに きえちゃうのよね…\lざんねん。$"

Route104_Text_HaleyIntro:
	.string "{JPN}しようかな…\nやめようかな?\pよし しょうぶ するわ!$"

Route104_Text_HaleyDefeat:
	.string "{JPN}しょうぶ しなければ よかった…$"

Route104_Text_HaleyPostBattle:
	.string "{JPN}まよった とき ほかの ひとに\nきめさせると どんな けっかに なっても\lこうかい する ものよ。\lおぼえて おいてね。$"

Route104_Text_HaleyRegister1:
	.string "{JPN}あなた つよいけど ポケナビに\nとうろく しようかしら…\lやめようかしら…\pよし とうろく するわ!$"

Route104_Text_HaleyRegister2:
	.string "{JPN}あなた つよいけど ポケナビに\nとうろく しようかしら…\lやめようかしら…\pよし とうろく するわ!$"

Route104_Text_HaleyRematchIntro:
	.string "{JPN}さあ しょうぶ しましょう!$"

Route104_Text_HaleyRematchDefeat:
	.string "{JPN}ああ…\nかてると おもったのに…$"

Route104_Text_HaleyPostRematch:
	.string "{JPN}じぶんで しょうぶを えらんだから\nまけも うけいれるわ。\pでも やっぱり くやしい!$"

Route104_Text_WinstonIntro:
	.string "{JPN}ええ しょうぶを うけて あげましょう。\nおかねは たくさん あるのよ。$"

Route104_Text_WinstonDefeat:
	.string "{JPN}どうして かてなかったの?$"

Route104_Text_WinstonPostBattle:
	.string "{JPN}おかねで かえない ものも あるのね。\nポケモンが そうだわ…$"

Route104_Text_WinstonRegister1:
	.string "{JPN}あら?\nポケナビを もって いるのね。\pよろこんで とうろく するわ。\nおかねなら たっぷり あるもの。$"

Route104_Text_WinstonRegister2:
	.string "{JPN}あら?\nポケナビを もって いるのね。\pよろこんで とうろく するわ。\nおかねなら たっぷり あるもの。$"

Route104_Text_WinstonRematchIntro:
	.string "{JPN}あなたに まけてから ポケモンに ついて\nいろいろ まなんだのよ。$"

Route104_Text_WinstonRematchDefeat:
	.string "{JPN}また まけたの?\nどうして かてないのかしら?$"

Route104_Text_WinstonPostRematch:
	.string "{JPN}おかねは ありあまる ほど あるのに\nポケモンでは かてない…\pポケモンの せかいは おくが ふかいわ…$"

Route104_Text_CindyIntro:
	.string "{JPN}わたしたち であう うんめい だったのね。\nしょうぶを おねがい できるかしら?$"

Route104_Text_CindyDefeat:
	.string "{JPN}あらまあ!$"

Route104_Text_CindyPostBattle:
	.string "{JPN}「こんにちは」は「さようなら」の はじまり。\nまた あえると いいわね。$"

Route104_Text_CindyRegister1:
	.string "{JPN}こんにちは また あったわね。\pひかれあって いるみたい。 おたがいの\nポケナビに とうろく しましょう。$"

Route104_Text_CindyRegister2:
	.string "{JPN}ひかれあって いる きねんに\pおたがいの ポケナビに\nとうろく しましょう。$"

Route104_Text_CindyRematchIntro:
	.string "{JPN}こんにちは また あったわね。\nしょうぶを おねがい できるかしら?$"

Route104_Text_CindyRematchDefeat:
	.string "{JPN}あらまあ…\nせいいっぱい やったのだけれど…$"

Route104_Text_CindyPostRematch:
	.string "{JPN}「こんにちは」は「さようなら」の はじまり。\nまた あえると いいわね。$"

Route104_Text_DarianIntro:
	.string "{JPN}つよそうな ポケモンを つりあげたぞ!\pなにか ふしぎな かんじが する!\nきっと つよいはずだ そうにちがいない!$"

Route104_Text_DarianDefeat:
	.string "{JPN}なんだと…$"

Route104_Text_DarianPostBattle:
	.string "{JPN}おい コイキング なまえまけ して いるぞ?$"

Route105_Text_FosterIntro:
	.string "{JPN}この あたりに ふしぎな いわが\nあるらしいんだ。\lなにか しらないか?$"

Route105_Text_FosterDefeated:
	.string "{JPN}いわの ことばかり かんがえて いて\nポケモンが よわいままだった…$"

Route105_Text_FosterPostBattle:
	.string "{JPN}いい いわは なんじかん ながめて いても\nあきないんだ。$"

Route105_Text_LuisIntro:
	.string "{JPN}ふう! こどもが おぼれて いるのかと\nしんぱい したよ。\pだいじょうぶ そうだね しょうぶでも\nどうかな?$"

Route105_Text_LuisDefeated:
	.string "{JPN}ごぼ… ごぼ…$"

Route105_Text_LuisPostBattle:
	.string "{JPN}おぼれた ときは かたほうの うでを\nはまべに むけて ふるんだよ。$"

Route105_Text_DominikIntro:
	.string "{JPN}まっさおな うみを およぐ…\nさいこうの きぶんだ!$"

Route105_Text_DominikDefeated:
	.string "{JPN}まけた…\nきぶんが しずむよ…$"

Route105_Text_DominikPostBattle:
	.string "{JPN}うみは なぜ あおいのか?\pカイナの はくぶつかんで ならったのに\nわすれて しまった。$"

Route105_Text_BeverlyIntro:
	.string "{JPN}みずの なかだと からだが かるいの。\nやせた みたい!$"

Route105_Text_BeverlyDefeated:
	.string "{JPN}うかんで いる…$"

Route105_Text_PostBattle:
	.string "{JPN}みずの なかでは たいじゅうが\n10ぶんの1に なるのよ。\pということは わたしは…\nおっと たいじゅうは ないしょ!$"

Route105_Text_ImaniIntro:
	.string "{JPN}あおい あおい そら…\nひろい うみ…\lなんて おだやかなの…$"

Route105_Text_ImaniDefeated:
	.string "{JPN}のんびり して いたら まけたわ!$"

Route105_Text_ImaniPostBattle:
	.string "{JPN}いっしょに いると おちつくって\nいわれたいの。 うふふ。$"

Route105_Text_AndresIntro:
	.string "{JPN}うみは わたしたちに ひみつを\nかくして いると おもうの。$"

Route105_Text_AndresDefeated:
	.string "{JPN}ええ…\nしょうぶは にがてなの…$"

Route105_Text_AndresPostBattle:
	.string "{JPN}せかいの うみには まだ たくさんの\nひみつが あるはず。\pぜんぶ みつけて みせるわ!$"

Route105_Text_AndresRegister:
	.string "{JPN}あら? こんなに よわいのに\nポケナビに とうろく して くれるの?$"

Route105_Text_AndresRematchIntro:
	.string "{JPN}よわいって いったでしょう…\nほんとうに いいの?$"

Route105_Text_AndresRematchDefeated:
	.string "{JPN}ええ…\nかてるとは おもって いなかったわ。$"

Route105_Text_AndresRematchPostBattle:
	.string "{JPN}しょうぶは よわくても たんけんへの\nじょうねつは まけないわ。\pせかいじゅうの うみを たびするの!$"

Route105_Text_JosueIntro:
	.string "{JPN}およいで つかれた。\nなれて いないんだ。\pきぶんてんかんに しょうぶ しよう!$"

Route105_Text_JosueDefeated:
	.string "{JPN}うみで しょうぶ したから まけたんだ。$"

Route105_Text_JosuePostBattle:
	.string "{JPN}うん ぼくには うみより そらの ほうが\nあって いる みたいだ。$"

Route106_Text_ElliotIntro:
	.string "{JPN}つりは うみと かわ どちらが すき?$"

Route106_Text_ElliotDefeated:
	.string "{JPN}ふかうみの つりの ように\nみごとに まけたよ!$"

Route106_Text_ElliotPostBattle:
	.string "{JPN}うみでも かわでも つりは さいこうだ。\nきみも そう おもうだろう?\lちがうかい?$"

Route106_Text_ElliotRegister:
	.string "{JPN}つりも いいが しょうぶも いい。\nよければ また あわないか?$"

Route106_Text_ElliotRematchIntro:
	.string "{JPN}つりで ポケモンを たくさん つかまえた。\nみごとな しょうぶを みせて やろう!$"

Route106_Text_ElliotRematchDefeated:
	.string "{JPN}また みごとに まけた!$"

Route106_Text_ElliotRematchPostBattle:
	.string "{JPN}かっても まけても ポケモンは さいこうだ!\nきみも そう おもうだろう?$"

Route106_Text_NedIntro:
	.string "{JPN}トイレに いきたく なったら\nみんな どう するんだ?\pトイレの あいだに おおものが かかったら\nこまる。 だから いけないんだ…$"

Route106_Text_NedDefeated:
	.string "{JPN}トイレを がまん して いたから まけた…$"

Route106_Text_NedPostBattle:
	.string "{JPN}まずい! おおものが かかる きが する!$"

Route106_Text_DouglasIntro:
	.string "{JPN}はははっ! はしるのは にがてだが\nみずの なかなら つかまらないぞ!$"

Route106_Text_DouglasDefeated:
	.string "{JPN}まいった!$"

Route106_Text_DouglasPostBattle:
	.string "{JPN}およぎの きょうそうなら まけないのに…$"

Route106_Text_KylaIntro:
	.string "{JPN}うみは おれの にわだ。 こどもだからと\nてかげんは しないぞ!$"

Route106_Text_KylaDefeated:
	.string "{JPN}もしかして てかげん したのか?$"

Route106_Text_KylaPostBattle:
	.string "{JPN}なみに ゆられて ただよう…\nすきなの! あなたも やってみたら?$"

Route107_Text_DarrinIntro:
	.string "{JPN}ふわあ…\pなみに ゆられて いるうちに\nねむって しまった みたい。$"

Route107_Text_DarrinDefeated:
	.string "{JPN}あはは まけちゃった…\nひとねむり しようかしら…$"

Route107_Text_DarrinPostBattle:
	.string "{JPN}なみに ゆられて うかぶのは\nふかふかの きもちいい ベッドで\lねむって いるみたい。$"

Route107_Text_TonyIntro:
	.string "{JPN}うみは わたしの にわの ような もの。\nしょうぶ しましょう!$"

Route107_Text_TonyDefeated:
	.string "{JPN}ホームで まけるなんて…\nショックだわ!$"

Route107_Text_TonyPostBattle:
	.string "{JPN}ゆめを むねに うみを およぐ…\pうたよ!\nさて もう ひとおよぎ してくるわ。$"

Route107_Text_TonyRegister:
	.string "{JPN}ほねの ずいまで おどろいたわ!\nわすれられない ように…$"

Route107_Text_TonyRematchIntro:
	.string "{JPN}ひろい うみを およいで\nポケモンが つよく なったの!$"

Route107_Text_TonyRematchDefeated:
	.string "{JPN}おどろいたわ!\pポケモンは つよく なったのに\nトレーナーの わたしは よわいまま!$"

Route107_Text_TonyRematchPostBattle:
	.string "{JPN}しょうぶで まなんだ ことが トレーナーを\nつよく するの。\lなみが おしえて くれたわ。$"

Route107_Text_DeniseIntro:
	.string "{JPN}ムロタウンって ちいさな まちを\nしって いる?$"

Route107_Text_DeniseDefeated:
	.string "{JPN}やだ もう!$"

Route107_Text_DenisePostBattle:
	.string "{JPN}ムロタウンの ホールで へんな ことばが\nはやって いるのよ。$"

Route107_Text_BethIntro:
	.string "{JPN}しょうぶ したいの?\nいいわよ おつきあい するわ!$"

Route107_Text_BethDefeated:
	.string "{JPN}あなたには およばなかったわ。$"

Route107_Text_BethPostBattle:
	.string "{JPN}あなたは これからも つよく なりそうね。\nわたしも がんばるわ!$"

Route107_Text_LisaIntro:
	.string "{JPN}リサ: きょうだいで しょうぶを\nいどむわ!$"

Route107_Text_LisaDefeated:
	.string "{JPN}リサ: すごい。\nつよさの けたが ちがうわ。$"

Route107_Text_LisaPostBattle:
	.string "{JPN}リサ: いっしょに うみへ いく ともだちは\nいるの?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "{JPN}リサ: しょうぶ するなら ポケモンを\nもっと つれて きて。$"

Route107_Text_RayIntro:
	.string "{JPN}レイ: ねえさんと いつも ポケモンで\nしょうぶ してるんだ。\pいつも まけるけど ふたりなら\nきみに かてる!$"

Route107_Text_RayDefeated:
	.string "{JPN}レイ: うわあ ぼくらより ずっと うえだ!$"

Route107_Text_RayPostBattle:
	.string "{JPN}レイ: この ポケモンは ねえさんに\nもらったんだ。 そだてて いまでは\lたいせつな あいぼうだよ!$"

Route107_Text_RayNotEnoughPokemon:
	.string "{JPN}レイ: しょうぶ するなら ポケモンを\nもっと つれて きてよ!$"

Route107_Text_CamronIntro:
	.string "{JPN}トライアスロンの とちゅうだけど\nぜんぜん つかれて いないぞ!$"

Route107_Text_CamronDefeated:
	.string "{JPN}つかれた…$"

Route107_Text_CamronPostBattle:
	.string "{JPN}このあと まだ すいえいと ランニングが\nのこって いる。\pだいじょうぶ かな?$"

Route108_Text_JeromeIntro:
	.string "{JPN}せかいの ななつの うみを およぐのが\nゆめなの!$"

Route108_Text_JeromeDefeated:
	.string "{JPN}これじゃ ななつの うみは およげないわ…$"

Route108_Text_JeromePostBattle:
	.string "{JPN}うみの ポケモンと あそぶのも\nすいえいの たのしみ!$"

Route108_Text_MatthewIntro:
	.string "{JPN}おーい きみも すてられぶねに\nいくのかい?$"

Route108_Text_MatthewDefeated:
	.string "{JPN}しずむ!\nごぼ… ごぼ…$"

Route108_Text_MatthewPostBattle:
	.string "{JPN}あの すてられぶねの なかに はいる\nひとも いるらしいよ。$"

Route108_Text_TaraIntro:
	.string "{JPN}うそつきの かれしが みずぎが にあうって\nいったのよ…$"

Route108_Text_TaraDefeated:
	.string "{JPN}ああ もう!$"

Route108_Text_TaraPostBattle:
	.string "{JPN}うそでも にあうって いわれるのは\nうれしいの…\lおんなごころは ふくざつなのよ…$"

Route108_Text_MissyIntro:
	.string "{JPN}うみが だいすき!\nおよぐと なやみを わすれられるの!$"

Route108_Text_MissyDefeated:
	.string "{JPN}しょうぶに まけると ストレスが たまる!$"

Route108_Text_MissyPostBattle:
	.string "{JPN}ストレスは およいで はっさん!\nけんこうに いいのよ!$"

Route108_Text_CoryIntro:
	.string "{JPN}みずタイプの ポケモンが すき。\nほかの ポケモンも すきよ!$"

Route108_Text_CoryDefeated:
	.string "{JPN}わあん! まけた!\nわあん! わあん!$"

Route108_Text_CoryPostBattle:
	.string "{JPN}さけぶと すっきり する!\nげんきが でるの!$"

Route108_Text_CoryRegister:
	.string "{JPN}つよい トレーナーも だいすき!\nポケナビに とうろく して!$"

Route108_Text_CoryRematchIntro:
	.string "{JPN}かっても まけても うみでの しょうぶは\nだいすき!$"

Route108_Text_CoryRematchDefeated:
	.string "{JPN}わあん! また まけた!\nわあん! わあん!$"

Route108_Text_CoryRematchPostBattle:
	.string "{JPN}こまった ときは うみに むかって\nさけんで みて!$"

Route108_Text_CarolinaIntro:
	.string "{JPN}わたしの ポケモンが じまんなの。\nすばやい しょうぶを みせて あげる!$"

Route108_Text_CarolinaDefeated:
	.string "{JPN}ぜんぜん かわいく なかったわ。$"

Route108_Text_CarolinaPostBattle:
	.string "{JPN}こうして うみに いるんだから\nピンクの ひらひらした みずぎも いいかも…$"

Route109_Text_DavidIntro:
	.string "{JPN}ふん! この きたえた ふっきんを みろ!\nこれが われた はらと いう ものだ!$"

Route109_Text_DavidDefeated:
	.string "{JPN}あいたっ!\nしくじった!$"

Route109_Text_DavidPostBattle:
	.string "{JPN}ふん!\pきたえた ふっきんと ポケモンの しょうぶは\nかんけいが なかったか!$"

Route109_Text_AliceIntro:
	.string "{JPN}ひやけどめは ちゃんと ぬって いる?$"

Route109_Text_AliceDefeated:
	.string "{JPN}いたた いたた!$"

Route109_Text_AlicePostBattle:
	.string "{JPN}ほおが いちばん やけやすいのよ!$"

Route109_Text_HueyIntro:
	.string "{JPN}せかいじゅうの みなとに よったが\nカイナが いちばんだ。$"

Route109_Text_HueyDefeated:
	.string "{JPN}きみが いちばんだ!$"

Route109_Text_HueyPostBattle:
	.string "{JPN}さいこうの みなとに さいこうの\nトレーナーが いた…$"

Route109_Text_EdmondIntro:
	.string "{JPN}うっぷ…\nしょうぶ? おれと?$"

Route109_Text_EdmondDefeated:
	.string "{JPN}うっ おおおおお…\nうっぷ…$"

Route109_Text_EdmondPostBattle:
	.string "{JPN}ふだんは もっと つよいんだ!\nふなよいが ひどくて…\pふなのりなのに…$"

Route109_Text_RickyIntro:
	.string "{JPN}のどが かわいた… かいはまハウスで\nソーダすいでも のみたいな…$"

Route109_Text_RickyDefeated:
	.string "{JPN}うーん…$"

Route109_Text_RickyPostBattle:
	.string "{JPN}はらが へって きた… うきわが おおきな\nドーナツに みえる…$"

Route109_Text_RickyRegister:
	.string "{JPN}のどが かわいて いない ときに\nまた しょうぶ して くれるかい?$"

Route109_Text_RickyRematchIntro:
	.string "{JPN}はらぺこだが しょうぶ するくらいの\nげんきは あるぞ!$"

Route109_Text_RickyRematchDefeated:
	.string "{JPN}まけた…\nはらが へって いたからだ…$"

Route109_Text_RickyRematchPostBattle:
	.string "{JPN}はまべで たべると なんでも\nすこし おいしく かんじるの。$"

Route109_Text_LolaIntro:
	.string "{JPN}ビーチパラソルって おおきな はなに\nみえない?$"

Route109_Text_LolaDefeated:
	.string "{JPN}ママー!$"

Route109_Text_LolaPostBattle:
	.string "{JPN}そらから はまべを みたら\nおおきな はなばたけに みえるはず!$"

Route109_Text_LolaRegister:
	.string "{JPN}わたし?\nまいにち ここに いるわ!$"

Route109_Text_LolaRematchIntro:
	.string "{JPN}もう まけないわ!\nうきわが あるんだから!$"

Route109_Text_LolaRematchDefeated:
	.string "{JPN}ママー!$"

Route109_Text_LolaRematchPostBattle:
	.string "{JPN}うきわが あると わたしも ポケモンも\nかわいさが ぐんと あがるの!$"

Route109_Text_AustinaIntro:
	.string "{JPN}うきわが ないと およげないけど\nポケモンでは まけないわ!$"

Route109_Text_AustinaDefeated:
	.string "{JPN}うきわが あるから まけたのかしら?$"

Route109_Text_AustinaPostBattle:
	.string "{JPN}うきわは おしゃれの ひとつ。\nこれが ないと でられないの。$"

Route109_Text_GwenIntro:
	.string "{JPN}ねえ おおきい トレーナー。\nしょうぶ して くれる?$"

Route109_Text_GwenDefeated:
	.string "{JPN}わあ つよいんだね。$"

Route109_Text_GwenPostBattle:
	.string "{JPN}どうやって そんなに つよく なったの?$"

Route109_Text_CarterIntro:
	.string "{JPN}わははは! おれさまが おおものを\nつりあげて やるぜ!$"

Route109_Text_CarterDefeated:
	.string "{JPN}おれさま いっぴき にがした…$"

Route109_Text_CarterPostBattle:
	.string "{JPN}おれさまが みるに きみは おおものだ。\nいや これから おおものに なる!$"

Route109_Text_PaulIntro:
	.string "{JPN}ポール: ああ しらけるな。\pふたりの たいせつな じかんを\nじゃま しないで ほしいな。$"

Route109_Text_PaulDefeated:
	.string "{JPN}ポール: まあ こうさん だね。$"

Route109_Text_PaulPostBattle:
	.string "{JPN}ポール: ここに いる ことは\nだれにも いわないで くれよ。\lふたりだけの せかいなんだ!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "{JPN}ポール: ぼくらは ふかく あいしあって いる。\nだから ポケモンも いっしょに\lたたかわせるのさ。$"

Route109_Text_MelIntro:
	.string "{JPN}メル: わたしたち ラブラブなの。\nこの あつさは ホウエンじゅうに とどくわ!$"

Route109_Text_MelDefeated:
	.string "{JPN}メル: まけちゃった わたしの せいね!\nポールに きらわれちゃう!$"

Route109_Text_MelPostBattle:
	.string "{JPN}メル: ねえ ポール おこってる?\nおこらないで。$"

Route109_Text_MelNotEnoughPokemon:
	.string "{JPN}メル: わたしたち ほんとうに\nあいしあって いるの。 だから ポケモンも\lいっしょに たたかわせるのよ。$"

Route109_Text_ChandlerIntro:
	.string "{JPN}じゃーん! みて?\nぼくの うきわ まんまるだよ!$"

Route109_Text_ChandlerDefeated:
	.string "{JPN}ああ ああ!\nざんねん!$"

Route109_Text_ChandlerPostBattle:
	.string "{JPN}まんまるの うきわを みせて あげたのに…$"

Route109_Text_HaileyIntro:
	.string "{JPN}およげないから およぐ まねを して いるの。$"

Route109_Text_HaileyDefeated:
	.string "{JPN}やっぱり!\nかてるとは おもって いなかったわ。$"

Route109_Text_HaileyPostBattle:
	.string "{JPN}およげるように なったら ポケモンも\nつよく なる きが するの。$"

Route109_Text_ElijahIntro:
	.string "{JPN}おれさまの ような マッチョには\nこういう ポケモンが ぴったりだ!$"

Route109_Text_ElijahDefeated:
	.string "{JPN}まけても かっこいい だろう?$"

Route109_Text_ElijahPostBattle:
	.string "{JPN}おれさまの ような マッチョには\nみなとが にあうんだ!\pカイナへ いくと するか。$"

Route110_Text_JacobIntro:
	.string "{JPN}うわっ あぶない!\n じてんしゃレースに なれて いないな。$"

Route110_Text_JacobDefeated:
	.string "{JPN}うわっ!\nブレーキが きかない!$"

Route110_Text_JacobPostBattle:
	.string "{JPN}パンクや ブレーキの ふぐあいは\nおおけがの もとだ!\lじてんしゃは よく てんけん しよう!$"

Route110_Text_AnthonyIntro:
	.string "{JPN}よお きみ!\nおれの スピードに ついてこられるか?$"

Route110_Text_AnthonyDefeated:
	.string "{JPN}はでに ころんだ!$"

Route110_Text_AnthonyPostBattle:
	.string "{JPN}はやさだけでは ポケモンで かてないか。\nかんがえなおさないとな…$"

Route110_Text_BenjaminIntro:
	.string "{JPN}じてんしゃが はやくても あわてるなよ!$"

Route110_Text_BenjaminDefeated:
	.string "{JPN}ポケモンの しょうぶでも\nあわてては いけないな…$"

Route110_Text_BenjaminPostBattle:
	.string "{JPN}あわてる ことも あせる ことも ない。\nゆっくり いこう。 じかんは たっぷりある。$"

Route110_Text_BenjaminRegister:
	.string "{JPN}あせらず こつこつ いくよ。\nその きが あったら こえを かけてくれ。$"

Route110_Text_BenjaminRematchIntro:
	.string "{JPN}すこし いそぎすぎでは ないか?\nおちついて しょうぶ しよう。$"

Route110_Text_BenjaminRematchDefeated:
	.string "{JPN}あわてなかったのに まけたな…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "{JPN}あわてる ことも あせる ことも ない。\nゆっくり いこう。 じかんは たっぷりある。$"

Route110_Text_AbigailIntro:
	.string "{JPN}トライアスロンは とても きびしい。\pすいえい じてんしゃ ランニングの\n3つを こなさないと いけないんだ。$"

Route110_Text_AbigailDefeated:
	.string "{JPN}ポケモンの しょうぶも きびしいな!$"

Route110_Text_AbigailPostBattle:
	.string "{JPN}つかれたから やすむよ。\nちゃんと やすむのも たいせつだ。$"

Route110_Text_AbigailRegister:
	.string "{JPN}きみの ことが きに いった!\nじてんしゃロードで また しょうぶ しよう。$"

Route110_Text_AbigailRematchIntro:
	.string "{JPN}じてんしゃに のりながらの しょうぶも\nいい ものだろう?$"

Route110_Text_AbigailRematchDefeated:
	.string "{JPN}すごい…\nどうして そんなに つよいんだ?$"

Route110_Text_AbigailRematchPostBattle:
	.string "{JPN}きろくを ねらって いたのかい?\pじゃま したなら ごめんよ!$"

Route110_Text_JasmineIntro:
	.string "{JPN}やすまずに こぎつづけて いる。\nふとももが いわの ようだ!$"

Route110_Text_JasmineDefeated:
	.string "{JPN}あしが つらないか しんぱいだ…$"

Route110_Text_JasminePostBattle:
	.string "{JPN}おや ジムバッジを もって いるのか?\nどうりで つよいわけだ!$"

Route110_Text_EdwardIntro:
	.string "{JPN}あなたの かんがえは よんで いる!\nまける はずが ない!$"

Route110_Text_EdwardDefeated:
	.string "{JPN}じぶんの まけは よめなかった!$"

Route110_Text_EdwardPostBattle:
	.string "{JPN}あなたの みらいが みえる…\pうむ…\nまばゆい ひかりが みえる…$"

Route110_Text_JaclynIntro:
	.string "{JPN}あははは!\nふしぎな ちからで まどわせて あげる!$"

Route110_Text_JaclynDefeated:
	.string "{JPN}ふしぎと まけて しまったわ!$"

Route110_Text_JaclynPostBattle:
	.string "{JPN}かてたのは ふしぎな ちからの おかげよ!\lいつも かてると おもわない ことね!$"

Route110_Text_EdwinIntro:
	.string "{JPN}あなたの ポケモンを みせて くれる?\nひとめだけで いいの!$"

Route110_Text_EdwinDefeated:
	.string "{JPN}コレクションを かんせい させたかったのに…$"

Route110_Text_EdwinPostBattle:
	.string "{JPN}しらない ポケモンを みると\nあつめたい きもちに ひが つくの!$"

Route110_Text_EdwinRegister:
	.string "{JPN}れんらくさきを あつめるのも すきなの…$"

Route110_Text_EdwinRematchIntro:
	.string "{JPN}やあ あたらしい ポケモンは つかまえた?\pあなたの ポケモンを みせて くれる?\nひとめだけで いいの!$"

Route110_Text_EdwinRematchDefeated:
	.string "{JPN}あなたの ポケモン…\nうらやましいわ。$"

Route110_Text_EdwinRematchPostBattle:
	.string "{JPN}めずらしい ポケモンは ぜんぶ\nじぶんの ものに したいわ!$"

Route110_Text_DaleIntro:
	.string "{JPN}おい!\nうしろから そっと ちかづくなよ!$"

Route110_Text_DaleDefeated:
	.string "{JPN}まけた!\nくそっ!$"

Route110_Text_DalePostBattle:
	.string "{JPN}つりは しゅうちゅうりょくが すべてだ。\nうきに めを こらすんだ。$"

Route110_Text_IsabelIntro:
	.string "{JPN}あははは! かわいい ポケモンを\nみせびらかすためなら どこへでも いくわ。$"

Route110_Text_IsabelDefeated:
	.string "{JPN}あらまあ これは いけないわ。$"

Route110_Text_IsabelPostBattle:
	.string "{JPN}しょうぶより ファンクラブで ポケモンを\nみせびらかす ほうが いいかしら。$"

Route110_Text_IsabelRegister:
	.string "{JPN}ポケモンを みせびらかすには\nぜんぜん たりなかったわ。\pできるだけ たくさん みて もらうわよ!$"

Route110_Text_IsabelRematchIntro:
	.string "{JPN}あははは! いくらでも わたしの ポケモンを\nみせて あげるわ!$"

Route110_Text_IsabelRematchDefeated:
	.string "{JPN}あらまあ これは いけないわ。$"

Route110_Text_IsabelRematchPostBattle:
	.string "{JPN}ポケモンを みせびらかすのは\nやめられそうに ないわ。\pでも しょうぶも すきなの!$"

Route110_Text_TimmyIntro:
	.string "{JPN}この あたりの くさむらで かっこいい\nポケモンを みつけたぞ!$"

Route110_Text_TimmyDefeated:
	.string "{JPN}かっこよさだけでは かてないか…$"

Route110_Text_TimmyPostBattle:
	.string "{JPN}つかまえたばかりの ポケモンで\nたたかうのは むずかしいな。$"

Route110_Text_AlyssaIntro:
	.string "{JPN}じてんしゃロードから おちて しまった…\pはずかしさを しょうぶで まぎらわせるぞ!$"

Route110_Text_AlyssaDefeated:
	.string "{JPN}おっと!\nまけて しまった!$"

Route110_Text_AlyssaPostBattle:
	.string "{JPN}おちて まけて…\nはずかしくて たまらない!$"

Route110_Text_JosephIntro:
	.string "{JPN}よし ぜんかいで いくぜ! ノリが わるいと\nおいて いかれるぞ!$"

Route110_Text_JosephDefeated:
	.string "{JPN}すっかり ノって いたな…$"

Route110_Text_JosephPostBattle:
	.string "{JPN}この くらいで へこたれないぜ!\nまけて おとこを あげたのさ!$"

Route110_Text_KalebIntro:
	.string "{JPN}かわいい ポケモンどうしが たすけあう…\nこんなに かわいい ものは ないわ!$"

Route110_Text_KalebDefeated:
	.string "{JPN}なさけも あわれみも ないのね?$"

Route110_Text_KalebPostBattle:
	.string "{JPN}はいはい よく がんばったわ かわいい こたち。$"

Route111_Text_DrewIntro:
	.string "{JPN}あら! その ゴーグル にあうわね。\nでも わたしの ほうが にあうと おもうの。\pどちらが にあうか しょうぶで きめましょう!$"

Route111_Text_DrewDefeat:
	.string "{JPN}ゴーグルの せいで よこが みえなかったわ。$"

Route111_Text_DrewPostBattle:
	.string "{JPN}ゴーグルが あれば すなあらしも\nとおれるのよ。\lうれしいわ!$"

Route111_Text_HeidiIntro:
	.string "{JPN}さばくで ピクニックを して いるの。\pトレーナーも かならず いるから\nここでも しょうぶが たのしめるわ!$"

Route111_Text_HeidiDefeat:
	.string "{JPN}ああ! いじわる!$"

Route111_Text_HeidiPostBattle:
	.string "{JPN}すなあらしの なかで たたかう ときは\nポケモンの HPに きを つけてね。\pみて いないと ひんしに なって しまうわ!$"

Route111_Text_BeauIntro:
	.string "{JPN}この ゴーグルを つけると ヒーローに\nなった きぶんだ。\lいまの おれには だれも かてない!$"

Route111_Text_BeauDefeat:
	.string "{JPN}きあいだけでは かてないか…$"

Route111_Text_BeauPostBattle:
	.string "{JPN}いつか ほんものの ヒーローに なる。\nもっと がんばって じぶんも ポケモンも\lつよく するぞ。$"

Route111_Text_BeckyIntro:
	.string "{JPN}さばくで かせきが みつかると きいた。\nどこに あるのだろう?$"

Route111_Text_BeckyDefeat:
	.string "{JPN}およばなかった…$"

Route111_Text_BeckyPostBattle:
	.string "{JPN}さばくで かせきが みつかるなら\nむかしは うみ だったに ちがいない。$"

Route111_Text_DustyIntro:
	.string "{JPN}30ねんかん いせきを さがして きた!\nこの わたしに\lしょうぶを いどむと いうのか?$"

Route111_Text_DustyDefeat:
	.string "{JPN}いせきは さがして きたが\nつよい ポケモンは さがして いなかった。$"

Route111_Text_DustyPostBattle:
	.string "{JPN}30ねんかん いせきを さがして きた!\pいや まてよ 40ねん だったか?\nどっち だったかな?$"

Route111_Text_DustyRegister:
	.string "{JPN}つよい ポケモンは さがして いない。\pだが なぜか ポケナビは すきなんだ。$"

Route111_Text_DustyRematchIntro:
	.string "{JPN}30ねんかん いせきを さがして きた!\pいや まてよ 40ねん だったか?\nともかく しょうぶを いどむのか?$"

Route111_Text_DustyRematchDefeat:
	.string "{JPN}いせきも みつからず つよい ポケモンも\nみつからず…$"

Route111_Text_DustyPostRematch:
	.string "{JPN}30ねんかん いせきを さがして きた!\pいや まてよ 40ねん だったか?\pうーむ 50ねんかも しれん…\nどれだけ さがして いるのだろう?$"

Route111_Text_TravisIntro:
	.string "{JPN}げんきいっぱい!\nポケモンも げんきいっぱい!$"

Route111_Text_TravisDefeat:
	.string "{JPN}ポケモンの げんきが なくなった…$"

Route111_Text_TravisPostBattle:
	.string "{JPN}げんきな トレーナーを みると\nつい めが いって しまうんだ。$"

Route111_Text_IreneIntro:
	.string "{JPN}どこへ いくのか しらないが\nしょうぶ しないか?$"

Route111_Text_IreneDefeat:
	.string "{JPN}いやに つよいな!$"

Route111_Text_IrenePostBattle:
	.string "{JPN}えんとつやまへ いこうと おもって いるが\nこの あたりの けしきも\lなかなか わるくない。$"

Route111_Text_DaisukeIntro:
	.string "{JPN}じぶんを きたえるため であう ものすべてに\nしょうぶを いどむ!$"

Route111_Text_DaisukeDefeat:
	.string "{JPN}まいった! こうさんだ!$"

Route111_Text_DaisukePostBattle:
	.string "{JPN}きみの ような つよい トレーナーに\nかてる ように なるまで\lきたえつづける しかない。$"

Route111_Text_WiltonIntro:
	.string "{JPN}どれだけ ポケモンを きたえたか\nみせて もらおう。$"

Route111_Text_WiltonDefeat:
	.string "{JPN}なるほど かなり きたえて あるな。$"

Route111_Text_WiltonPostBattle:
	.string "{JPN}ポケモンも トレーナーも しょうぶから\nおおくを まなぶ。\pだいじなのは まけても あきらめない ことだ。$"

Route111_Text_WiltonRegister:
	.string "{JPN}きみの きたえかたには まなぶ ことが おおい。\pよければ また しょうぶ して ほしい。$"

Route111_Text_WiltonRematchIntro:
	.string "{JPN}つぎの だんかいへ すすむために\nここで きたえて いる。\lきみも いっしょに どうだ!$"

Route111_Text_WiltonRematchDefeat:
	.string "{JPN}ほう なかなか やるな!$"

Route111_Text_WiltonPostRematch:
	.string "{JPN}それだけ つよいなら ポケモンリーグを\nめざすと いい。$"

Route111_Text_BrookeIntro:
	.string "{JPN}おお きみの ポケモンは いい やくしゃの\nようだ。\lぜひ しゅつえんを おねがいしたい。$"

Route111_Text_BrookeDefeat:
	.string "{JPN}つよそうなだけでは なく\nほんとうに つよかった!$"

Route111_Text_BrookePostBattle:
	.string "{JPN}ねっしんに そだてて きた つもりだが\nいやはや まだまだ\lやる ことが おおいな。$"

Route111_Text_BrookeRegister:
	.string "{JPN}きみの ような つよい ひとと\nもっと ともだちに なりたいものだ!$"

Route111_Text_BrookeRematchIntro:
	.string "{JPN}おぼえさせる わざで ポケモンは\nつよくも よわくも なる。\lそれを わすれては いけない。\pきみの ポケモンは どんな わざを\nおぼえて いるのかな?$"

Route111_Text_BrookeRematchDefeat:
	.string "{JPN}いい わざを おぼえさせて いるな!$"

Route111_Text_BrookePostRematch:
	.string "{JPN}いい わざを おぼえるまで\nポケモンの しんかを とめて\lおくべき だったかな…$"

Route111_Text_CeliaIntro:
	.string "{JPN}こんな ところで ピクニックを\nするんじゃ なかった!$"

Route111_Text_CeliaDefeat:
	.string "{JPN}ああ!\nやっぱり くるんじゃ なかった!$"

Route111_Text_CeliaPostBattle:
	.string "{JPN}これだけ すなあらしが ひどいと\nゴーグルが あっても ピクニックの\lしたくが できないわ…$"

Route111_Text_BryanIntro:
	.string "{JPN}どれほど つよいのか?\nその ひみつを あばいて みせよう!$"

Route111_Text_BryanDefeat:
	.string "{JPN}おお その つよさ!\nまさに なぞに つつまれて いる!$"

Route111_Text_BryanPostBattle:
	.string "{JPN}この さばくは うごく すなの なかに\nなぞを かくして いるのだ!$"

Route111_Text_BrandenIntro:
	.string "{JPN}まけて くれたら サンドイッチを\nわけて あげるよ。$"

Route111_Text_BrandenDefeat:
	.string "{JPN}ちぇっ! サンドイッチで じゅうぶんだと\nおもったのに…$"

Route111_Text_BrandenPostBattle:
	.string "{JPN}うちの サンドは サンドイッチが\nだいすきなんだ。$"

Route111_Text_TyronIntro:
	.string "{JPN}これが おきにいりの ポケモンだ!$"

Route111_Text_TyronDefeat:
	.string "{JPN}まって!\nおれの ポケモンを よく みたか?$"

Route111_Text_TyronPostBattle:
	.string "{JPN}しょうぶの ときは ポケモンを\nみせびらかせるのが うれしいんだ。\pみんな そう おもって いるはずだ!$"

Route111_Text_CelinaIntro:
	.string "{JPN}わたしの まいにちに すこし\nどきどきを ください。$"

Route111_Text_CelinaDefeat:
	.string "{JPN}ああ…\nどきどきしすぎたわ。$"

Route111_Text_CelinaPostBattle:
	.string "{JPN}むねの どうきが まだ おさまらない。\nすばらしい トレーナーね。$"

Route111_Text_HaydenIntro:
	.string "{JPN}これだけ はらが へって いると\nなさけを かける よゆうは ない!$"

Route111_Text_HaydenDefeat:
	.string "{JPN}うーん…$"

Route111_Text_HaydenPostBattle:
	.string "{JPN}はらが なる!\nきのみでも やこうかな…$"

Route111_Text_BiancaIntro:
	.string "{JPN}キンセツから きたのか?\nそれなら げんきいっぱい だろう!$"

Route111_Text_BiancaDefeat:
	.string "{JPN}おお!\nこれは こたえるな!$"

Route111_Text_BiancaPostBattle:
	.string "{JPN}この みちは…\nまだまだ さきが ながいぞ。$"

Route112_Text_BriceIntro:
	.string "{JPN}はははは!\nしょうぶ しないか?\lきみと おれで!\lはははは!$"

Route112_Text_BriceDefeat:
	.string "{JPN}まけた!\nはははは!$"

Route112_Text_BricePostBattle:
	.string "{JPN}はははは! はなに なにか はいった!\nははは はっくしょん!$"

Route112_Text_TrentIntro:
	.string "{JPN}やまを のぼりおりして あしは\nがちがちだ。\pそう かんたんには へこたれないぞ!$"

Route112_Text_TrentDefeat:
	.string "{JPN}いてっ! あしが つった!$"

Route112_Text_TrentPostBattle:
	.string "{JPN}じゅっキロも ある にもつを せおって\nやまみちを ほんきで\lあるいて みると いい。\lきみも やって みないか。\pそうすれば からだは しっかり\nしあがるんだ。$"

Route112_Text_TrentRegister:
	.string "{JPN}いてて あしが つった。\nリュックから ほうたいを\lとって くれるか?\pいや それは ポケナビだ!\nまあ いい とうろく して やろう。$"

Route112_Text_TrentRematchIntro:
	.string "{JPN}やまあるきで からだを きたえて いる。\nちからなら じしんが ある!$"

Route112_Text_TrentRematchDefeat:
	.string "{JPN}ちからで まけたのか?$"

Route112_Text_TrentRematchPostBattle:
	.string "{JPN}えんとつやまの うえに とんでもなく\nつよい トレーナーが いるらしい。\pのぼって いって しょうぶを いどむぞ!$"

Route112_Text_LarryIntro:
	.string "{JPN}ぼくは つよいんだ。\nまけても なかないぞ。$"

Route112_Text_LarryDefeat:
	.string "{JPN}うわあああん!$"

Route112_Text_LarryPostBattle:
	.string "{JPN}ママが こいしくて ないて いるんじゃ ないぞ!\nぐすん…$"

Route112_Text_CarolIntro:
	.string "{JPN}ピクニックに きたら やっぱり\nうたわなくちゃ!\lいっしょに うたいましょう!$"

Route112_Text_CarolDefeat:
	.string "{JPN}まあ とても つよいのね!$"

Route112_Text_CarolPostBattle:
	.string "{JPN}うたも ポケモンも じょうずでも へたでも\nかまわないの。\pいちばん たのしんだ ひとの かちよ!$"

Route112_Text_BryantIntro:
	.string "{JPN}えんとつやまの みちで あつい ポケモンを\nつかまえたぞ! みて くれ!$"

Route112_Text_BryantDefeat:
	.string "{JPN}はでに ふきとばされたな!$"

Route112_Text_BryantPostBattle:
	.string "{JPN}きみの たたかいかたが きに いった。\nどこか かっこいいんだ。$"

Route112_Text_ShaylaIntro:
	.string "{JPN}あら かわいい トレーナーね!\nロマンチックな しょうぶを おねがい!\lわたしも そこそこ やるのよ!$"

Route112_Text_ShaylaDefeat:
	.string "{JPN}まあ なんて つよいの!\nおどろいて しまったわ!$"

Route112_Text_ShaylaPostBattle:
	.string "{JPN}いま いそがしい?\nよければ すぐにでも また しょうぶを\lしたいのだけど…\lいそがしいなら いいのよ。$"

Route113_Text_JaylenIntro:
	.string "{JPN}この あたりが すずしい わけが\nわかるかしら?$"

Route113_Text_JaylenDefeat:
	.string "{JPN}うわあ!\nくさい!$"

Route113_Text_JaylenPostBattle:
	.string "{JPN}かざんばいが たいようを さえぎるから\nあまり あつく ならないの。\pあつさが にがてな わたしには ありがたいわ!$"

Route113_Text_DillonIntro:
	.string "{JPN}かざんの ふんかは だいちが いきて いる\nしょうこなの。$"

Route113_Text_DillonDefeat:
	.string "{JPN}とんでもなく つよいのね!$"

Route113_Text_DillonPostBattle:
	.string "{JPN}いたた! みえない!\nまつげに はいが はいったわ!\pはいと まつげ… なんてね?\pいまのは よくなかったわね ごめんなさい…$"

Route113_Text_MadelineIntro:
	.string "{JPN}この ひがさで かわいい ドンメルを\nよごれた かざんばいから\lまもって いるの。$"

Route113_Text_MadelineDefeat:
	.string "{JPN}はあ はあ…\nつかれたわ…$"

Route113_Text_MadelinePostBattle:
	.string "{JPN}あなた とても じょうずね。\nかんしん したわ!$"

Route113_Text_MadelineRegister:
	.string "{JPN}さあ ひがさの したへ どうぞ。\nポケナビに とうろく させて。$"

Route113_Text_MadelineRematchIntro:
	.string "{JPN}あら こんにちは ひさしぶりね?\nしょうぶに さそっても いいかしら?$"

Route113_Text_MadelineRematchDefeat:
	.string "{JPN}まあ すてき!$"

Route113_Text_MadelinePostRematch:
	.string "{JPN}あいかわらず じょうずね。\nかんしん するわ!$"

Route113_Text_LaoIntro:
	.string "{JPN}はいの なかから とびだす! やあっ!\nしょうぶを いどむ!$"

Route113_Text_LaoDefeat:
	.string "{JPN}いさぎよく まけを みとめよう!$"

Route113_Text_LaoPostBattle:
	.string "{JPN}かくれる わざを もっと みがかねば。\nさらばだ。$"

Route113_Text_LaoRegister:
	.string "{JPN}やあっ! にんじゃ ひでんの\nポケナビ とうろくを みよ!$"

Route113_Text_LaoRematchIntro:
	.string "{JPN}はいの なかから とびだす! やあっ!\nしょうぶを いどむ!$"

Route113_Text_LaoRematchDefeat:
	.string "{JPN}いさぎよく まけを みとめよう!$"

Route113_Text_LaoPostRematch:
	.string "{JPN}かんぺきな かくれみも みじゅくな\nしょうぶの うでで だいなしか…\pさらばだ。$"

Route113_Text_LungIntro:
	.string "{JPN}みつけて くれて ありがとう!\nだが しょうぶは してもらうぞ!$"

Route113_Text_LungDefeat:
	.string "{JPN}にんぽう…\n「かざんばい うずまきがくれ」!\p…なに?\nもう おわりだと?$"

Route113_Text_LungPostBattle:
	.string "{JPN}かくれる ことの こまった ところは\nだれも こないと さびしい ことだ。$"

Route113_Text_ToriIntro:
	.string "{JPN}トリ: ふたりで はいを あつめて いるの。\nポケモンの しょうぶも するわ。$"

Route113_Text_ToriDefeat:
	.string "{JPN}トリ: まけちゃった… つまらないから\nはいを もっと あつめて くる。$"

Route113_Text_ToriPostBattle:
	.string "{JPN}トリ: はいは どれくらい たまったかな?\nしろいふえに なると いいな。$"

Route113_Text_ToriNotEnoughMons:
	.string "{JPN}トリ: 2たい2で しょうぶ したいの。\nそうじゃないと まけちゃうもの!$"

Route113_Text_TiaIntro:
	.string "{JPN}ティア: ふたりで はいを あつめて いるの。\nポケモンの しょうぶも するわ。$"

Route113_Text_TiaDefeat:
	.string "{JPN}ティア: かてなかった… つまらないから\nはいを もっと あつめて くる。$"

Route113_Text_TiaPostBattle:
	.string "{JPN}ティア: はいが たくさん たまったわ!\nしろいふえに できそう!$"

Route113_Text_TiaNotEnoughMons:
	.string "{JPN}ティア: 2たい2で しょうぶ したいの。\nそうじゃないと かてないもの!$"

Route113_Text_CobyIntro:
	.string "{JPN}ふん この つばさで きみなんか\nはらいのけて やる!$"

Route113_Text_CobyDefeat:
	.string "{JPN}あ… え?$"

Route113_Text_CobyPostBattle:
	.string "{JPN}こんなに かんたんに まけると\nいう ことばも ない…$"

Route113_Text_SophieIntro:
	.string "{JPN}ここは あたたかくて ねむく なる。\nおきて いられるよう しょうぶ しよう。$"

Route113_Text_SophieDefeat:
	.string "{JPN}これは ゆめだ。\nきっと そうだ…$"

Route113_Text_SophiePostBattle:
	.string "{JPN}まけると あたまに くる…\nもう ここで ねて しまおう!\lぐう!$"

Route113_Text_LawrenceIntro:
	.string "{JPN}もしかして かざんばいを\nあつめて いる とちゅう?$"

Route113_Text_LawrenceDefeat:
	.string "{JPN}えへへ。\nみごとに まけちゃった。$"

Route113_Text_LawrencePostBattle:
	.string "{JPN}わたしも はいの したに かくれようかな。$"

Route113_Text_WyattIntro:
	.string "{JPN}わ わたしと しょうぶ するの?\nポケモンを つかまえたばかりなのに?$"

Route113_Text_WyattDefeat:
	.string "{JPN}か かって うれしいの?\nわたし あいてなのに?$"

Route113_Text_WyattPostBattle:
	.string "{JPN}まけた ものに なにか いうつもり?\pずいぶん えらそうね?\nふん!$"

Route114_Text_LennyIntro:
	.string "{JPN}ヤッホー!\p… …\pここは やまびこが かえらないから\nじぶんで「ヤッホー」って\lいわないと だめなの!$"

Route114_Text_LennyDefeat:
	.string "{JPN}ヤッホー!$"

Route114_Text_LennyPostBattle:
	.string "{JPN}ちいさい ころは だれかが まねを して\n「ヤッホー」と かえして くれるんだと\lしんじて いたわ。$"

Route114_Text_LucasIntro:
	.string "{JPN}じゅんびも なしに やまに\nはいるものでは ないぞ!$"

Route114_Text_LucasDefeat:
	.string "{JPN}やまは きびしい…$"

Route114_Text_LucasPostBattle:
	.string "{JPN}ふゆの やまは ふぶきや なだれで\nいのちに かかわるんだ。$"

Route114_Text_ShaneIntro:
	.string "{JPN}キャンプは たのしい! つりも できるし\nこわい はなしも できる!\pでも いちばんは ポケモンの しょうぶだ!$"

Route114_Text_ShaneDefeat:
	.string "{JPN}つよすぎる!$"

Route114_Text_ShanePostBattle:
	.string "{JPN}ポケモンと キャンプに こられるのが\nうれしいんだ。$"

Route114_Text_NancyIntro:
	.string "{JPN}しょくごの うんどうが ひつようだ。\nいっしょうぶ しよう!$"

Route114_Text_NancyDefeat:
	.string "{JPN}しまった!$"

Route114_Text_NancyPostBattle:
	.string "{JPN}おいしい ものを たべたばかりだ。\nねむく なって きたな…$"

Route114_Text_SteveIntro:
	.string "{JPN}うふふふふ…\nわたしの ポケモンと しょうぶ する?$"

Route114_Text_SteveDefeat:
	.string "{JPN}わ わたしの ポケモンが…$"

Route114_Text_StevePostBattle:
	.string "{JPN}ごつごつ した おおきな からだに\nりっぱな つのと するどい きば…\pうふふふ…\nそんな ポケモンが ほしいわ…$"

Route114_Text_SteveRegister:
	.string "{JPN}わたしに した ことを わすれないで!\nわすれられない ように して あげる!$"

Route114_Text_SteveRematchIntro:
	.string "{JPN}うふふふふ…\nさあ わたしの ポケモンと しょうぶよ…$"

Route114_Text_SteveRematchDefeat:
	.string "{JPN}あなたの ポケモンを みられて\nしあわせだわ…$"

Route114_Text_StevePostRematch:
	.string "{JPN}うふふふふ…\pポケモンの しょうぶを みて いると\nぞくぞく して ふるえて しまうの…$"

Route114_Text_BernieIntro:
	.string "{JPN}たきびを するなら みずを\nよういして おくんだよ。$"

Route114_Text_BernieDefeat:
	.string "{JPN}ひを けして くれて ありがとう!$"

Route114_Text_BerniePostBattle:
	.string "{JPN}もりの なかでは ひの あつかいに\nじゅうぶん きを つけないと いけない。\pひの ちからを あなどっては いけないよ。$"

Route114_Text_BernieRegister:
	.string "{JPN}きみに こころを もやされたよ。\nおたがい とうろく しよう!$"

Route114_Text_BernieRematchIntro:
	.string "{JPN}たきびには みずを よういする ことを\nおぼえたかい?$"

Route114_Text_BernieRematchDefeat:
	.string "{JPN}もえあがる まえに みずを\nかけられた かんじだな。$"

Route114_Text_BerniePostRematch:
	.string "{JPN}もりの なかでは ひの あつかいに\nじゅうぶん きを つけないと いけない。\pひの ちからを あなどっては いけないよ。$"

Route114_Text_ClaudeIntro:
	.string "{JPN}つりなら きみに まける きは しない。\nだから ポケモンで\lしょうぶ しようじゃないか!$"

Route114_Text_ClaudeDefeat:
	.string "{JPN}つりなら かって いたのに…$"

Route114_Text_ClaudePostBattle:
	.string "{JPN}りゅうせいのたきで おおものを\nねらって みるかな。\pあそこには かならず なにか いる。\nそんな きが するんだ。$"

Route114_Text_NolanIntro:
	.string "{JPN}つりも すきだが しょうぶも すきだ!\pだれかに いどまれたら つりの とちゅうでも\nうけて たつぞ。$"

Route114_Text_NolanDefeat:
	.string "{JPN}しょうぶは すきだが\nじょうずとは かぎらないな…$"

Route114_Text_NolanPostBattle:
	.string "{JPN}こんどこそ うまく いく!\pいつも そう おもうから つりも ポケモンも\nやめられないんだ。$"

Route114_Text_TyraIntro:
	.string "{JPN}タイラ: ええ いいわよ。\nちょうど その きぶんだったの。\lポケモンの ことを すこし おしえて あげる。$"

Route114_Text_TyraDefeat:
	.string "{JPN}タイラ: なんて みごとな たたかいかた!$"

Route114_Text_TyraPostBattle:
	.string "{JPN}タイラ: こうはいの アイビーに\nポケモンを おしえて いたの。$"

Route114_Text_TyraNotEnoughMons:
	.string "{JPN}タイラ: うふふ…\nわたしたちと しょうぶ するなら\lポケモン 1ぴきでは たりないわ!$"

Route114_Text_IvyIntro:
	.string "{JPN}アイビー: ポケモンの ことは\nだれに おそわったの?$"

Route114_Text_IvyDefeat:
	.string "{JPN}アイビー: なんて みごとな たたかいかた!$"

Route114_Text_IvyPostBattle:
	.string "{JPN}アイビー: せんぱいの タイラに\nおそわって ポケモンを\lそだてはじめたの!$"

Route114_Text_IvyNotEnoughMons:
	.string "{JPN}アイビー: ポケモンは 1ぴきだけ?\nさびしいと おもうな。$"

Route114_Text_KaiIntro:
	.string "{JPN}おおものを つりあげたぞ!\nとんでもなく でかいんだ!$"

Route114_Text_KaiDefeat:
	.string "{JPN}なんだったんだ?\nおおきさで まけたのか?$"

Route114_Text_KaiPostBattle:
	.string "{JPN}よし!\nもっと おおきいのを つって やる!$"

Route114_Text_CharlotteIntro:
	.string "{JPN}わたし!\nかおだけじゃ ないのよ!$"

Route114_Text_CharlotteDefeat:
	.string "{JPN}ぜんぜん かわいく なかったわ!$"

Route114_Text_CharlottePostBattle:
	.string "{JPN}かわいいだけの ポケモンは いらないの。\pすこし かわった ところが ある\nかわいい こが すきなの!$"

Route114_Text_AngelinaIntro:
	.string "{JPN}ポケモンを しんかさせて いる?$"

Route114_Text_AngelinaDefeat:
	.string "{JPN}あら そうなの。\nいい ことを きいたわ。$"

Route114_Text_AngelinaPostBattle:
	.string "{JPN}しんかすると すがたが すっかり かわる\nポケモンも いて おどろくわ!$"

Route115_Text_TimothyIntro:
	.string "{JPN}ふむ…\nなかなか できるようだな…\lあいてを して やろう!$"

Route115_Text_TimothyDefeat:
	.string "{JPN}おもって いたより ずっと つよいな!$"

Route115_Text_TimothyPostBattle:
	.string "{JPN}うまれつきの てんさいなど いない。\nすべては どりょくしだい!\lわたしは そう しんじて いる…$"

Route115_Text_TimothyRegister:
	.string "{JPN}うむ… ここまで みごとに まけたのは\nひさしぶりだ。\pよければ また しょうぶを して ほしい。$"

Route115_Text_TimothyRematchIntro:
	.string "{JPN}ふむ あいかわらず みのこなしが いいな。\lさあ あいてを して くれ!$"

Route115_Text_TimothyRematchDefeat:
	.string "{JPN}あいかわらず つよいな!$"

Route115_Text_TimothyPostRematch:
	.string "{JPN}すべては どりょくだ!\pどりょくが たりなかったから まけたのだ!$"

Route115_Text_KoichiIntro:
	.string "{JPN}きみ!\pおれの ワンリキーが!\pしょうぶを のぞんで いる!$"

Route115_Text_KoichiDefeat:
	.string "{JPN}いたた いたた!$"

Route115_Text_KoichiPostBattle:
	.string "{JPN}おれの ワンリキーたち!\pちからを もとめる かぎり\nおれも ともに つよく なる!$"

Route115_Text_NobIntro:
	.string "{JPN}とくいわざは ひたいで かわらわりだ!$"

Route115_Text_NobDefeat:
	.string "{JPN}ぐわあああ!\nあたまが われる!$"

Route115_Text_NobPostBattle:
	.string "{JPN}ポケモンに からてを おしえて いる。\pおれより ずっと つよく なりそうだ。\nそれが たのしみなんだ。$"

Route115_Text_NobRegister:
	.string "{JPN}みごとだ! きたえなおしたら\nまた しょうぶ して くれ!$"

Route115_Text_NobRematchIntro:
	.string "{JPN}きみに まけてから ひっしに\nうでを みがいて きた。\lさあ もういちど しょうぶだ!$"

Route115_Text_NobRematchDefeat:
	.string "{JPN}ぐわあ!\nまた まけた!$"

Route115_Text_NobPostRematch:
	.string "{JPN}ポケモンは もっと つよく なる!\nきたえなおしだ!$"

Route115_Text_CyndyIntro:
	.string "{JPN}この はまべは おれの ひみつの\nれんしゅうばだ! じゃまを するな!$"

Route115_Text_CyndyDefeat:
	.string "{JPN}きたえかたが たりなかった!$"

Route115_Text_CyndyPostBattle:
	.string "{JPN}すなは しょうげきを やわらげて\nけがを ふせいで くれる。\lれんしゅうに もってこいの ばしょだ。$"

Route115_Text_CyndyRegister:
	.string "{JPN}わかった ここに きても いい。\nそのかわり また しょうぶ して くれ。$"

Route115_Text_CyndyRematchIntro:
	.string "{JPN}よし しょうぶ しよう!$"

Route115_Text_CyndyRematchDefeat:
	.string "{JPN}おれは たたかえるが ポケモンが…$"

Route115_Text_CyndyPostRematch:
	.string "{JPN}まけても どこか たのしいんだ。\lポケモンが すきだからだろうな。$"

Route115_Text_HectorIntro:
	.string "{JPN}めずらしい ポケモンを もって いるんだ!\nみせて あげようか?$"

Route115_Text_HectorDefeat:
	.string "{JPN}きみ…\nおれの ポケモンが ほしいんだろう?$"

Route115_Text_HectorPostBattle:
	.string "{JPN}この めずらしい ポケモンが いれば\nおれは じゅうぶん まんぞくだ。$"

Route115_Text_KyraIntro:
	.string "{JPN}はしりながら しょうぶ するぞ!\nついてこられるか!$"

Route115_Text_KyraDefeat:
	.string "{JPN}はあ はあ…$"

Route115_Text_KyraPostBattle:
	.string "{JPN}はしりながら しょうぶ したのが\nまちがい だった!\pはしって おちつくと するか…$"

Route115_Text_JaidenIntro:
	.string "{JPN}くらえ!\nウルトラ ポケモン にんぽう!$"

Route115_Text_JaidenDefeat:
	.string "{JPN}わあ!\nさくせんが しっぱい した!$"

Route115_Text_JaidenPostBattle:
	.string "{JPN}でも ぼくの ポケモンは ウルトラ\nだったろう?$"

Route115_Text_HeleneIntro:
	.string "{JPN}おれの ポケモンは くろおびきゅうの\nちからを もって いる!$"

Route115_Text_HeleneDefeat:
	.string "{JPN}はずかしくて たまらない!$"

Route115_Text_HelenePostBattle:
	.string "{JPN}おれより つよい やつには\nめったに あわないのだが…\pわかったぞ!\nきみは ジムリーダーだな?$"

Route115_Text_AlixIntro:
	.string "{JPN}めが あった!\nもう にげられないぞ!$"

Route115_Text_AlixDefeat:
	.string "{JPN}ぐっ!\nなかなか やるな!$"

Route115_Text_AlixPostBattle:
	.string "{JPN}しかたない。\nテレポートで いえに かえるとしよう。$"

Route115_Text_MarleneIntro:
	.string "{JPN}わたしの めいそうを じゃま したな…\nばつを うけて もらおう。$"

Route115_Text_MarleneDefeat:
	.string "{JPN}しゅうちゅうを みだされた!$"

Route115_Text_MarlenePostBattle:
	.string "{JPN}ポケモンと めいそう して いたのだ。\nだが ここは しずかとは いえないな…$"

Route116_Text_ClarkIntro:
	.string "{JPN}トンネルが とおれないなら\nうえを こえて いくまでだ。$"

Route116_Text_ClarkDefeat:
	.string "{JPN}はあ はあ…\nまけて つかれたぞ…$"

Route116_Text_ClarkPostBattle:
	.string "{JPN}トンネルが なくても かまわん。\nやまおとこに とって やまは みちだ!$"

Route116_Text_JoeyIntro:
	.string "{JPN}おれの ポケモンは さいこうだ!\nみて くれ!$"

Route116_Text_JoeyDefeat:
	.string "{JPN}いてっ! すりむいた!\nばんそうこうを はらないと!$"

Route116_Text_JoeyPostBattle:
	.string "{JPN}ばんそうこうは つよさの あかし!\nもう 1まい あるぞ!$"

Route116_Text_JoseIntro:
	.string "{JPN}ぼくの むしポケモンは つよいぞ!\nしょうぶだ!$"

Route116_Text_JoseDefeat:
	.string "{JPN}まけた!\nかてると おもったのに!$"

Route116_Text_JosePostBattle:
	.string "{JPN}むしポケモンは しんかが はやい。\nだから つよく なるのも はやいんだ。$"

Route116_Text_JaniceIntro:
	.string "{JPN}わたしの かわいい ポケモンの つよさを\nおしえて あげる!$"

Route116_Text_JaniceDefeat:
	.string "{JPN}わたしより ひとつ うえね…$"

Route116_Text_JanicePostBattle:
	.string "{JPN}かわいさと つよさを あわせもつ\nポケモンが りそうだと おもうの。$"

Route116_Text_JerryIntro:
	.string "{JPN}トレーナーズスクールでは いろいろな\nことを ならうんだ。\pほんばんで ためして みたい!$"

Route116_Text_JerryDefeat:
	.string "{JPN}がっこうで さぼって いたから\nまけたんだ…$"

Route116_Text_JerryPostBattle:
	.string "{JPN}トレーナーズスクールで べんきょうを\nやりなおさないと。\lそうしないと ツツジせんせいに おこられる。$"

Route116_Text_JerryRegister1:
	.string "{JPN}ポケナビで トレーナーを とうろく できると\nトレーナーズスクールで ならったんだ。\pよく わからないから\nためして みても いい?$"

Route116_Text_JerryRegister2:
	.string "{JPN}ポケナビで トレーナーを とうろく できると\nトレーナーズスクールで ならったんだ。\pよく わからないから\nためして みても いい?$"

Route116_Text_JerryRematchIntro:
	.string "{JPN}トレーナーズスクールで まじめに\nべんきょう して きた。\lまえの ようには まけないぞ。$"

Route116_Text_JerryRematchDefeat:
	.string "{JPN}え?\nちゃんと べんきょう したのに。$"

Route116_Text_JerryPostRematch:
	.string "{JPN}トレーナーズスクールで べんきょうを\nやりなおさないと。\lそうしないと ツツジせんせいに おこられる。$"

Route116_Text_KarenIntro:
	.string "{JPN}がっこうでも かえりみちでも\nべんきょう して いるんだ!$"

Route116_Text_KarenDefeat:
	.string "{JPN}ショックだ… まけたのか?$"

Route116_Text_KarenPostBattle:
	.string "{JPN}ああ これじゃ ツツジせんせいの ような\nりっぱな トレーナーに なれないよ!$"

Route116_Text_KarenRegister1:
	.string "{JPN}わあ! それ ポケナビ?\nぼくも もって いる! とうろく して!$"

Route116_Text_KarenRegister2:
	.string "{JPN}わあ! それ ポケナビ?\nぼくも もって いる! とうろく して!$"

Route116_Text_KarenRematchIntro:
	.string "{JPN}まえに あってから たくさん べんきょう した。\nその せいかを みて くれ!$"

Route116_Text_KarenRematchDefeat:
	.string "{JPN}ショックだ。\nまた まけたのか?$"

Route116_Text_KarenPostRematch:
	.string "{JPN}ツツジせんせいに かったの?\nそれじゃ ぼくには まだ かてないや。$"

Route116_Text_SarahIntro:
	.string "{JPN}いって おくけれど わたくしは なにごとも\nひとに おくれを とった ことが ないの。$"

Route116_Text_SarahDefeat:
	.string "{JPN}まあ おどろいた。\nはじめての けいけんだわ。$"

Route116_Text_SarahPostBattle:
	.string "{JPN}ぜいたくな くらしで ほしい ものは\nなんでも てに はいるの。\pでも ポケモンに かんしては\nおかねなど いみが ないのね。$"

Route116_Text_DawsonIntro:
	.string "{JPN}わたくしの ポケモンの うつくしい\nけなみを みたら あなたは\lみとれて しまうわ!$"

Route116_Text_DawsonDefeat:
	.string "{JPN}まあ そんな ことって!$"

Route116_Text_DawsonPostBattle:
	.string "{JPN}ああ もう!\nポケモンの けなみが みだれたわ!\lわたくしの かみも ぐしゃぐしゃ!\lびようしを よばなくては!$"

Route116_Text_DevanIntro:
	.string "{JPN}はでに いくぜ!$"

Route116_Text_DevanDefeat:
	.string "{JPN}あいたた!\nまるで しょうぶに ならなかった!$"

Route116_Text_DevanPostBattle:
	.string "{JPN}ちがう タイプの ポケモンも\nためして みるべきだな。$"

Route116_Text_JohnsonIntro:
	.string "{JPN}ここは いきどまりよ。\nたいくつだから しょうぶ しない?$"

Route116_Text_JohnsonDefeat:
	.string "{JPN}まけたけど たのしかったわ。$"

Route116_Text_JohnsonPostBattle:
	.string "{JPN}ここに のこって わたしの あいてを\nして くれない?$"

Route117_Text_IsaacIntro:
	.string "{JPN}ねえ わたしが そだてて いる ポケモンと\nしょうぶ して くれない?$"

Route117_Text_IsaacDefeat:
	.string "{JPN}みごとに そだてて いるのね…$"

Route117_Text_IsaacPostBattle:
	.string "{JPN}ポケモンは ちからが すべてでは ないの。\pその こだけの みりょくを みがくのも\nポケモンの たのしみかたの\lひとつなのよ。$"

Route117_Text_IsaacRegister:
	.string "{JPN}もっと きたえなおすわ。\nようすを みに きて くれる?$"

Route117_Text_IsaacRematchIntro:
	.string "{JPN}そだてて いる ポケモンは\nまえと おなじく いい かんじよ。$"

Route117_Text_IsaacRematchDefeat:
	.string "{JPN}そだてかたが じょうずね。\nあずかりやの さいのうが あるかも…$"

Route117_Text_IsaacPostRematch:
	.string "{JPN}ポケモンが よく そだって いるわ!\nコンテストに でて みたら?$"

Route117_Text_LydiaIntro:
	.string "{JPN}あなたが ポケモンを ちゃんと\nそだてて いるか みせて もらうわ。$"

Route117_Text_LydiaDefeat:
	.string "{JPN}ええ ちゃんと そだって いるわね。$"

Route117_Text_LydiaPostBattle:
	.string "{JPN}その こらしさを もっと たいせつに\nそだてて みると いいわ。$"

Route117_Text_LydiaRegister:
	.string "{JPN}すばらしい トレーナーに あえて うれしいわ。\nまた あいましょう。$"

Route117_Text_LydiaRematchIntro:
	.string "{JPN}ポケモンを ちゃんと そだてて いるか\nもういちど みせて もらうわ。$"

Route117_Text_LydiaRematchDefeat:
	.string "{JPN}みごとに そだって いるわね。$"

Route117_Text_LydiaPostRematch:
	.string "{JPN}ポケモンは せいかくに よって すきな\n{POKEBLOCK}が ちがうみたい。$"

Route117_Text_DylanIntro:
	.string "{JPN}トライアスロンの とちゅうだけど\nまあ しょうぶ しよう!$"

Route117_Text_DylanDefeat:
	.string "{JPN}ちからが つきた!$"

Route117_Text_DylanPostBattle:
	.string "{JPN}やって しまった…\pいまの しょうぶで さいかいに\nおちたかも しれない…$"

Route117_Text_DylanRegister:
	.string "{JPN}ポケモンも つよく ないと だめなのか?\nきたえて ほしいくらいだ!$"

Route117_Text_DylanRematchIntro:
	.string "{JPN}トライアスロンの まっさいちゅうだが\nよゆうで さきを はしって いる。\lさっと しょうぶを すませよう!$"

Route117_Text_DylanRematchDefeat:
	.string "{JPN}また ちからが つきた!$"

Route117_Text_DylanPostRematch:
	.string "{JPN}すいえいと じてんしゃは いちばん\nだったが ポケモンには\lまだ じしんが ないな。$"

Route117_Text_MariaIntro:
	.string "{JPN}ポケモンと トライアスロンの れんしゅうを\nして いるから はやさには じしんが ある。$"

Route117_Text_MariaDefeat:
	.string "{JPN}もっと れんしゅうが ひつようだな。$"

Route117_Text_MariaPostBattle:
	.string "{JPN}れんしゅうは つづけてこそ いみが ある。\pよし れんしゅうを さいかいだ!\nあしたから!$"

Route117_Text_MariaRegister:
	.string "{JPN}ちゃんと きたえて いるようだな…\nよければ あとで しょうぶ しよう!$"

Route117_Text_MariaRematchIntro:
	.string "{JPN}れんしゅうは つづけて いるか?\nおれは つづけて いるぞ!\lその しょうこを みせて やる!$"

Route117_Text_MariaRematchDefeat:
	.string "{JPN}もっと れんしゅうが ひつようだな。$"

Route117_Text_MariaPostRematch:
	.string "{JPN}れんしゅうは あしたから さいかいだ。\nまた いつか しょうぶ しよう!$"

Route117_Text_DerekIntro:
	.string "{JPN}むかしは むしとりしょうねん!\nいまは むしマニア!\pだが ポケモンへの あいは かわらない!$"

Route117_Text_DerekDefeat:
	.string "{JPN}へたなのも かわらないな…$"

Route117_Text_DerekPostBattle:
	.string "{JPN}すきな ことを つづけて いたら\nむしマニアと よばれる ように なった…\pまあ むしポケモンの めいじんだから\nむしマニアと よばれるのも\lとうぜんの ことだな。$"

Route117_Text_AnnaIntro:
	.string "{JPN}アンナ: かわいい こうはいと いっしょよ。\nいい ところを みせないと!$"

Route117_Text_AnnaDefeat:
	.string "{JPN}アンナ: かわいい こうはいと いっしょ!\nかたせて もらうわ!$"

Route117_Text_AnnaPostBattle:
	.string "{JPN}アンナ: あなたの ポケモンは\nくみあわせが いいわね。\pわたしたちの つぎに つよいわ!$"

Route117_Text_AnnaAndMegRegister:
	.string "{JPN}アンナ: このままでは おわれないわ!\nまた きて くれるわよね?$"

Route117_Text_AnnaNotEnoughMons:
	.string "{JPN}アンナ: わたしたちと しょうぶ するなら\nポケモンを 2ひき つれて きて。$"

Route117_Text_MegIntro:
	.string "{JPN}メグ: すごい せんぱいと くんで\nあなたを たおすわ!$"

Route117_Text_MegDefeat:
	.string "{JPN}メグ: ああ そんな!\nごめんね アンナせんぱい わたしの せいで…$"

Route117_Text_MegPostBattle:
	.string "{JPN}メグ: わたしが アンナせんぱいの\nあしを ひっぱったの…\lそうでなければ かって いたのに!$"

Route117_Text_MegNotEnoughMons:
	.string "{JPN}メグ: ポケモンは 1ぴきだけ?\nそれでは しょうぶ できないわ。\pわたしたちは 2たい2で たたかいたいの。$"

Route117_Text_AnnaRematchIntro:
	.string "{JPN}アンナ: こうはいの まえで\nまけつづける わけには いかないわ?$"

Route117_Text_AnnaRematchDefeat:
	.string "{JPN}アンナ: ちょうしに のれなかったわ。$"

Route117_Text_AnnaPostRematch:
	.string "{JPN}アンナ: あなたの ポケモンは\nくみあわせが いいわね。\pわたしたちの つぎに つよいわ!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "{JPN}アンナ: わたしたちと しょうぶ するなら\nポケモンを 2ひき つれて きて。$"

Route117_Text_MegRematchIntro:
	.string "{JPN}メグ: せんぱいと くんで\nこんどこそ かつわ!$"

Route117_Text_MegRematchDefeat:
	.string "{JPN}メグ: つよすぎる!$"

Route117_Text_MegPostRematch:
	.string "{JPN}メグ: せんぱいと いっしょに たたかったのに\nまけちゃった…\pがっかりだわ…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "{JPN}メグ: ポケモンは 1ぴきだけ?\nそれでは しょうぶ できないわ。\pわたしたちは 2たい2で たたかいたいの。$"

Route117_Text_MelinaIntro:
	.string "{JPN}きれいな はなを ながめながらの しょうぶ。\nすてきだと おもわない?$"

Route117_Text_MelinaDefeat:
	.string "{JPN}あら みごとね!$"

Route117_Text_MelinaPostBattle:
	.string "{JPN}はなを みながら はしるのは\nきもちが いいの。$"

Route117_Text_BrandiIntro:
	.string "{JPN}エスパーポケモンに ひめられた ちからを\nみせて あげよう!$"

Route117_Text_BrandiDefeat:
	.string "{JPN}おどろいた!$"

Route117_Text_BrandiPostBattle:
	.string "{JPN}エスパーポケモンは おくが ふかい。\nきみも つかまえて みると いい。$"

Route117_Text_AishaIntro:
	.string "{JPN}かつ ことに しゅうちゅう する。\nそれが わたしの たたかいかた!$"

Route117_Text_AishaDefeat:
	.string "{JPN}まけて おこって いる ひまが あるなら\nきたえた ほうが いい。$"

Route117_Text_AishaPostBattle:
	.string "{JPN}まけを おそれると よけいに\nまけやすく なると おもうの。$"

Route118_Text_RoseIntro:
	.string "{JPN}はなの かおりには ふしぎな ちからが あるの。\nからだも こころも きよめて くれるわ。$"

Route118_Text_RoseDefeat:
	.string "{JPN}あらまあ。\nまけて しまった みたい。$"

Route118_Text_RosePostBattle:
	.string "{JPN}はなも ポケモンも…\nいい かおりの ものは なんでも すき。\pくさい ものは…\nえんりょ するわ。$"

Route118_Text_RoseRegister:
	.string "{JPN}くんくん… この かおりは ポケナビ!\nおたがい とうろく しましょう!$"

Route118_Text_RoseRematchIntro:
	.string "{JPN}あまい かおりに ひかれて きたの?$"

Route118_Text_RoseRematchDefeat:
	.string "{JPN}かおりの ちからも\nあまり きかなかったわね。$"

Route118_Text_RosePostRematch:
	.string "{JPN}あまい かおりを うまく つかうと\nポケモンが よって くるのよ。$"

Route118_Text_PerryIntro:
	.string "{JPN}そらを ゆうがに とぶ とりポケモン…\nさいこうだよね!$"

Route118_Text_PerryDefeat:
	.string "{JPN}うう…\nついらく した…$"

Route118_Text_PerryPostBattle:
	.string "{JPN}いい ポケモンを もって いるね。\nもっと きたえないと いけないな。$"

Route118_Text_ChesterIntro:
	.string "{JPN}とべ!\nおれの とりポケモン!$"

Route118_Text_ChesterDefeat:
	.string "{JPN}たしかに とんで いったな…$"

Route118_Text_ChesterPostBattle:
	.string "{JPN}もっと つよく なれば もっと じゆうに\nとべるはずなんだが…$"

Route118_Text_BarnyIntro:
	.string "{JPN}つりびとだが トレーナーでも ある。\nつった ポケモンを そだてて いるんだ。$"

Route118_Text_BarnyDefeat:
	.string "{JPN}そだてかたは わるく ないと\nおもって いたが…$"

Route118_Text_BarnyPostBattle:
	.string "{JPN}つりながら ポケモンを そだてて いては\nかてなかったか…\pどちらも ちゅうとはんぱ だったかな?$"

Route118_Text_WadeIntro:
	.string "{JPN}つりびとには どうぐが たいせつだ。\pだが トレーナーに たいせつなのは\nポケモンと こころだろう!$"

Route118_Text_WadeDefeat:
	.string "{JPN}こころで まけたのか?$"

Route118_Text_WadePostBattle:
	.string "{JPN}かんがえて みれば つりも つりびとと\nポケモンの しょうぶだな。$"

Route118_Text_DaltonIntro:
	.string "{JPN}おれの メロディで こころを ゆさぶってやる!$"

Route118_Text_DaltonDefeat:
	.string "{JPN}ラ ラララ…$"

Route118_Text_DaltonPostBattle:
	.string "{JPN}エレキギターは うるさい だけの\nがっきじゃ ない…\pこころに ひびく メロディも\nかなでる ことが できるんだ…$"

Route118_Text_DaltonRegister:
	.string "{JPN}もっと いい きょくが できたら\nききに きて くれよ?$"

Route118_Text_DaltonRematchIntro:
	.string "{JPN}おれと ポケモンの メロディを…\nきみの こころに とどけよう。$"

Route118_Text_DaltonRematchDefeat:
	.string "{JPN}ラ ラララ…$"

Route118_Text_DaltonPostRematch:
	.string "{JPN}ひいて いれば おれの きもちは\nエレキギターを とおして とどくはずだ…$"

Route118_Text_DeandreIntro:
	.string "{JPN}いけ いけ いけ!\nポケモン 1 2 3!$"

Route118_Text_DeandreDefeat:
	.string "{JPN}おうとう せよ ポケモン! ぶじか?\nポケモン 1 2 3!?$"

Route118_Text_DeandrePostBattle:
	.string "{JPN}ポケモンの しょうぶチームって\nかっこいい だろう?\pまねしても かまわないぞ!$"

Route119_Text_BrentIntro:
	.string "{JPN}わたしたちは ものまねサークル!\nあなたの まねを するの!$"

Route119_Text_BrentDefeat:
	.string "{JPN}おっと!\nまけちゃった!$"

Route119_Text_BrentPostBattle:
	.string "{JPN}ものまねの なにが たのしいかって?\pふふふ…\nあなたには わからないでしょうね…$"

Route119_Text_DonaldIntro:
	.string "{JPN}ついに あえたね!\nぼくの むしポケモンが あいてを するよ!$"

Route119_Text_DonaldDefeat:
	.string "{JPN}あわなければ よかった…$"

Route119_Text_DonaldPostBattle:
	.string "{JPN}もっと まねを したいの。\nはやく うごいて くれない?$"

Route119_Text_TaylorIntro:
	.string "{JPN}あなたが すすめば わたしたちも すすむ。\pあなたが みぎを むけば わたしたちも むく…$"

Route119_Text_TaylorDefeat:
	.string "{JPN}でも あなたが かつと わたしは まける…$"

Route119_Text_TaylorPostBattle:
	.string "{JPN}あなたが かつ ところは まねできない。\nそんなの むりだもの…\lくやしいわ…$"

Route119_Text_DougIntro:
	.string "{JPN}やっと つかまえたね!\nそれとも さけて いたのかな?$"

Route119_Text_DougDefeat:
	.string "{JPN}おっと いい しょうぶだった!$"

Route119_Text_DougPostBattle:
	.string "{JPN}わたしたちは ものまねサークル!\nえんぎを たのしんで もらえたかしら。$"

Route119_Text_GregIntro:
	.string "{JPN}わたしが だれだか しらないでしょう?\pでも わたしも あなたを しらない。\nだから しょうぶ しましょう!$"

Route119_Text_GregDefeat:
	.string "{JPN}なかなか つよいのね!$"

Route119_Text_GregPostBattle:
	.string "{JPN}あなたが どこかへ いくまで\nうごきを まねしつづけるわ。$"

Route119_Text_KentIntro:
	.string "{JPN}ものまねサークルは まねが すきな ひとで\nつくった あつまりなの。\pであった しゅんかんから しょうぶよ!$"

Route119_Text_KentDefeat:
	.string "{JPN}まいった!$"

Route119_Text_KentPostBattle:
	.string "{JPN}ものまねサークルに はいらない?$"

Route119_Text_JacksonIntro:
	.string "{JPN}いきのこる ちしきと ぎじゅつを\nもって いるのは だれか?\pポケモンレンジャーさ!$"

Route119_Text_JacksonDefeat:
	.string "{JPN}ポケモンの ちしきが たりなかった…$"

Route119_Text_JacksonPostBattle:
	.string "{JPN}まちを はなれ うちなる やせいの こころを\nめざめさせる!\pそれが おれたちの めざす ものだ。$"

Route119_Text_JacksonRegister:
	.string "{JPN}ちしきぶそくを わらわずに\nまた しょうぶ して ほしい。$"

Route119_Text_JacksonRematchIntro:
	.string "{JPN}ポケモンと ともに いる ことで\nやせいの こころを とりもどすんだ。$"

Route119_Text_JacksonRematchDefeat:
	.string "{JPN}あいかわらず つよいな!$"

Route119_Text_JacksonPostRematch:
	.string "{JPN}ポケモンを しんじろ。\nじぶんを しんじろ。\pそうすれば みちは ひらける。$"

Route119_Text_CatherineIntro:
	.string "{JPN}おや? きみを みて いると…\pぼうけんの わりに ずいぶん\nみがるな かっこうだね。$"

Route119_Text_CatherineDefeat:
	.string "{JPN}じゅんびが たりないと\nじこが おきるものだぞ!$"

Route119_Text_CatherinePostBattle:
	.string "{JPN}みがるだが ひつような ものは\nそろって いるな。\pこころも からだも しっかり して いる。$"

Route119_Text_CatherineRegister:
	.string "{JPN}ポケナビは もって いるか?\nトレーナーには かかせない どうぐだ。\pおお もって いるのか!\nでは とうろく しあおう!$"

Route119_Text_CatherineRematchIntro:
	.string "{JPN}ポケモンとの たびは どうだい?$"

Route119_Text_CatherineRematchDefeat:
	.string "{JPN}まだ なにかが たりないな…$"

Route119_Text_CatherinePostRematch:
	.string "{JPN}トレーナーが ポケモンを たよる ように\nポケモンも きみの ことを\lたよって いるんだ。$"

Route119_Text_HughIntro:
	.string "{JPN}ひろい そらには むげんの かのうせいが ある!\pとぶ ことの きもちよさに かなう ものは\nなにも ない!$"

Route119_Text_HughDefeat:
	.string "{JPN}のされた!$"

Route119_Text_HughPostBattle:
	.string "{JPN}とりポケモンが とぶ ゆめを\nかなえて くれたんだ!$"

Route119_Text_PhilIntro:
	.string "{JPN}おれと とりポケモンの ほんとうの ちからを\nみせて やる!$"

Route119_Text_PhilDefeat:
	.string "{JPN}ちからが たりなかった…$"

Route119_Text_PhilPostBattle:
	.string "{JPN}ちいさい ころから とりポケモンに\nあこがれて いたんだ…$"

Route119_Text_YasuIntro:
	.string "{JPN}かげに ひそみ やみに いきる…\nそれが わが さだめ。\pいまこそ すがたを あらわし いどむ!$"

Route119_Text_YasuDefeat:
	.string "{JPN}まけを みとめよう!$"

Route119_Text_YasuPostBattle:
	.string "{JPN}やぶれた ものは しずかに かげへ かえる。\lそれもまた さだめ…$"

Route119_Text_TakashiIntro:
	.string "{JPN}ゆだんして いると いたい めを みるぞ!$"

Route119_Text_TakashiDefeat:
	.string "{JPN}おどろく ほど つよいな!$"

Route119_Text_TakashiPostBattle:
	.string "{JPN}ふいうちは しっぱいに おわった…$"

Route119_Text_HideoIntro:
	.string "{JPN}きを かくすなら もりの なか!$"

Route119_Text_HideoDefeat:
	.string "{JPN}きみの ほうが うえだ みとめよう。$"

Route119_Text_HideoPostBattle:
	.string "{JPN}きを かくすなら もりの なか!\nポケモンを かくすなら ポケモンの なか!\pふかい いみは とくに ない。$"

Route119_Text_ChrisIntro:
	.string "{JPN}はなしかけて きたな…\nつまり しょうぶを のぞむのだな!\pいいだろう! なみのりの とちゅうで\nつかまえた ポケモンを ためして やる!$"

Route119_Text_ChrisDefeat:
	.string "{JPN}かつには なにが ひつようなのか\nさっぱり わからん。$"

Route119_Text_ChrisPostBattle:
	.string "{JPN}ポケモンに のって なみのり…\pその せなかから つりを する…\pなんとも ぜいたくな ひとときだ!$"

Route119_Text_FabianIntro:
	.string "{JPN}はでな コードを ならして いくぜ!\nしょうりは おれの ものだ!\lいまこそ かがやく ときだぜ!$"

Route119_Text_FabianDefeat:
	.string "{JPN}どっちが うえか おもいしらされた!\nまけを みとめる しかないぜ!$"

Route119_Text_FabianPostBattle:
	.string "{JPN}もう いっぱつ はでな コードを ならすぜ!\nほうって おいて くれ!\lかった つみは おもいぜ!$"

Route119_Text_DaytonIntro:
	.string "{JPN}ほっほっほ!\nこどもの トレーナーは すきじゃ!\lいい しょうぶを しようぞ!$"

Route119_Text_DaytonDefeat:
	.string "{JPN}なかなか みごとじゃ!\nほっほっほ!$"

Route119_Text_DaytonPostBattle:
	.string "{JPN}ほっほっほ!\nおまえさんのような わかい トレーナーの\lげんきを みならうと しようかの!$"

Route119_Text_RachelIntro:
	.string "{JPN}いつ どこに いても\nひがさは てばなさないの。$"

Route119_Text_RachelDefeat:
	.string "{JPN}あら でも…\nそれは ずるいわ。$"

Route119_Text_RachelPostBattle:
	.string "{JPN}ひがさが おもそうって?\nあなたの バッグの ほうが よっぽど\lいろいろ つまって いるじゃない。$"

Route120_Text_ColinIntro:
	.string "{JPN}そらに いる ポケモンに あたる わざは\nもって いるかしら?$"

Route120_Text_ColinDefeat:
	.string "{JPN}うえを いかれたわ!$"

Route120_Text_ColinPostBattle:
	.string "{JPN}そらをとぶは べんりな わざだと\nおもわない?\pとんで いる あいだは ほとんどの わざが\nあたらないもの。$"

Route120_Text_RobertIntro:
	.string "{JPN}わたしの ポケモンは つよいわよ!\nあなたの ポケモンは どう?$"

Route120_Text_RobertDefeat:
	.string "{JPN}あなたの ポケモンの ほうが つよかったわ…$"

Route120_Text_RobertPostBattle:
	.string "{JPN}じっくり そだった ポケモンは\nたよりに なるものよ。$"

Route120_Text_RobertRegister:
	.string "{JPN}あなたは まだまだ のびそうね。\nポケナビに とうろく させて!$"

Route120_Text_RobertRematchIntro:
	.string "{JPN}じっくり そだった ポケモンは\nたよりに なるものよ。$"

Route120_Text_RobertRematchDefeat:
	.string "{JPN}あなたの ポケモンは ほんとうに つよいわ。$"

Route120_Text_RobertPostRematch:
	.string "{JPN}ポケモンは つよく なって いる。\nわたしも つよく ならないと。$"

Route120_Text_LorenzoIntro:
	.string "{JPN}あなたの ポケモンが やがいに むいて いるか\nみせて もらうわ。$"

Route120_Text_LorenzoDefeat:
	.string "{JPN}それだけ つよい ポケモンが いれば\nきゅうじょは いらないわね!$"

Route120_Text_LorenzoPostBattle:
	.string "{JPN}ポケモンと ともに いきたい ところへ いく…\lそれが トレーナーの よろこびよ。$"

Route120_Text_JennaIntro:
	.string "{JPN}たいりょくは ある?\nたいりょくが ないと いざと いう ときに\lこまるわよ。$"

Route120_Text_JennaDefeat:
	.string "{JPN}たいりょくは じゅうぶん なのに…$"

Route120_Text_JennaPostBattle:
	.string "{JPN}たいりょくづくりは にっかなの。\nいつも ポケモンと はしって いるわ。$"

Route120_Text_JeffreyIntro:
	.string "{JPN}… … … … … …\n… … … … … …\lしょうぶ する?$"

Route120_Text_JeffreyDefeat:
	.string "{JPN}まけた…$"

Route120_Text_JeffreyPostBattle:
	.string "{JPN}… … … … … …\n… … … … … …\lもっと がんばる…$"

Route120_Text_JeffreyRegister:
	.string "{JPN}… … … … … …\n… … … … … …\lポケナビは もって いる…?$"

Route120_Text_JeffreyRematchIntro:
	.string "{JPN}… … … … … …\n… … … … … …\lまた しょうぶ する?$"

Route120_Text_JeffreyRematchDefeat:
	.string "{JPN}… … … … … …\nまた まけた…$"

Route120_Text_JeffreyPostRematch:
	.string "{JPN}… … … … … …\n… … … … … …\lもっと がんばる…\lたいせつな むしポケモンの ために…$"

Route120_Text_JenniferIntro:
	.string "{JPN}ポケモンには いろいろな とくせいが ある。\nいちりゅうの トレーナーを めざすなら\lそれを まなぶ ことだ。$"

Route120_Text_JenniferDefeat:
	.string "{JPN}よく かんがえて いるようだな。$"

Route120_Text_JenniferPostBattle:
	.string "{JPN}ポケモンの とくせいで\nたたかいかたは かわるのだ。$"

Route120_Text_ChipIntro:
	.string "{JPN}きみは だれかね?\pもしや でんせつに あると いわれる\nいせきを さがして\lいるのでは ないかね?$"

Route120_Text_ChipDefeat:
	.string "{JPN}なんとも なさけない…$"

Route120_Text_ChipPostBattle:
	.string "{JPN}あの おおきな いわ… なかに いせきが\nあるのだと しんじたい。\lだが いりぐちが みあたらんのだ。$"

Route120_Text_ClarissaIntro:
	.string "{JPN}なぜ ひがさを さして いるかって?\pわたしに かてたら おしえて あげるわ。$"

Route120_Text_ClarissaDefeat:
	.string "{JPN}ひがさでは ポケモンの こうげきは\nふせげないわね…$"

Route120_Text_ClarissaPostBattle:
	.string "{JPN}つよい ひざしは ポケモンに よくないと\nおもうの。\lだから ひがさで まもって いるのよ。$"

Route120_Text_AngelicaIntro:
	.string "{JPN}わたしと ポケモンと ひがさ…\pどれが かけても\nうつくしい えは できないの。$"

Route120_Text_AngelicaDefeat:
	.string "{JPN}わたしの うつくしさが\nすっかり だいなしね…$"

Route120_Text_AngelicaPostBattle:
	.string "{JPN}あなたには ひがさは にあわないわ。\pこんな ものは じゃまに なるだけよ。$"

Route120_Text_KeigoIntro:
	.string "{JPN}ポケモンの うごきを とりいれて\nあたらしい にんぽうを つくるのだ。$"

Route120_Text_KeigoDefeat:
	.string "{JPN}あたらしい にんぽうづくりは\nまだまだ とおい ゆめだ…$"

Route120_Text_KeigoPostBattle:
	.string "{JPN}にんじゃの ししょうに でしいり\nするべきかも しれんな。$"

Route120_Text_RileyIntro:
	.string "{JPN}われら にんじゃは かくれみのを かぶって\nすがたを かくす。\lどこに いるか わからなかっただろう!$"

Route120_Text_RileyDefeat:
	.string "{JPN}まけた!\nはずかしさを かくさねば!$"

Route120_Text_RileyPostBattle:
	.string "{JPN}かくれみのは すべて てづくりなのだ。$"

Route120_Text_CallieIntro:
	.string "{JPN}きを つけて いないと\nけがを するぞ!$"

Route120_Text_CallieDefeat:
	.string "{JPN}いてっ!\nけがを したのは こちらだった。$"

Route120_Text_CalliePostBattle:
	.string "{JPN}ポケモンを しんかさせようかな…\nいまも じゅうぶん かわいいけど。$"

Route120_Text_LeonelIntro:
	.string "{JPN}てもちの ポケモン…\nタイプは ばらけて いる?$"

Route120_Text_LeonelDefeat:
	.string "{JPN}あなたの かんがえかたが よく わかったわ!$"

Route120_Text_LeonelPostBattle:
	.string "{JPN}すきな ポケモンで そこまで つよいのは\nすばらしい ことだと おもうわ。$"

Route121_Text_VanessaIntro:
	.string "{JPN}わたしの とても かわいい ポケモンと\nあそんで くれる?$"

Route121_Text_VanessaDefeat:
	.string "{JPN}こういう ことじゃ なかったのに!$"

Route121_Text_VanessaPostBattle:
	.string "{JPN}ミナモの コンテストに いくの。\pうちの ポケモンなら マスタークラスも\nかんたんに かちぬけるわ。$"

Route121_Text_WalterIntro:
	.string "{JPN}ポケモンと ともに せかいの すみずみまで\nたびを して きた。\pうでには すこし じしんが あると\nいっても いいだろう。$"

Route121_Text_WalterDefeat:
	.string "{JPN}うむ みごとだ。$"

Route121_Text_WalterPostBattle:
	.string "{JPN}ポケモンと ともに もういちど\nせかいを まわりたいものだ。$"

Route121_Text_WalterRegister:
	.string "{JPN}きみの ポケモンの うでまえは みごとだ。\nきねんに とうろく させて くれ。$"

Route121_Text_WalterRematchIntro:
	.string "{JPN}ポケモンと ともに せかいの すみずみまで\nたびを して きた。\pうでには すこし じしんが あると\nいっても いいだろう。$"

Route121_Text_WalterRematchDefeat:
	.string "{JPN}うむ みごとだ。$"

Route121_Text_WalterPostRematch:
	.string "{JPN}きみと きみの ポケモン…\pその ちからは かいがいでも\nじゅうぶん つうよう するだろう。$"

Route121_Text_TammyIntro:
	.string "{JPN}この よには わたしたちの りかいを こえた\nちからが ある…$"

Route121_Text_TammyDefeat:
	.string "{JPN}まけて しまった…$"

Route121_Text_TammyPostBattle:
	.string "{JPN}おくりびやま…\nあそこには ふしぎな ちからが\lはたらいて いる…$"

Route121_Text_KateIntro:
	.string "{JPN}ケイト: ふたりなら こわい ものなし!\nつよさを みせて あげるわ!$"

Route121_Text_KateDefeat:
	.string "{JPN}ケイト: こうはいの まえで しくじったわ…$"

Route121_Text_KatePostBattle:
	.string "{JPN}ケイト: たよりに されると\nかっこよく みせたく なって\lしまうのよね…$"

Route121_Text_KateNotEnoughMons:
	.string "{JPN}ケイト: ポケモンが 1ぴきだけなら\nしょうぶは できないわ。\pそれでは いじめに なって しまうもの。$"

Route121_Text_JoyIntro:
	.string "{JPN}ジョイ: ふたりなら こわい ものなし!\nつよさを みせて あげるわ!$"

Route121_Text_JoyDefeat:
	.string "{JPN}ジョイ: ケイトせんぱい ゆるして!$"

Route121_Text_JoyPostBattle:
	.string "{JPN}ジョイ: えへへ ケイトせんぱいと\nまた れんしゅう しないと。$"

Route121_Text_JoyNotEnoughMons:
	.string "{JPN}ジョイ: わたしたちに いどむなら\nポケモンが 2ひきは ひつようよ!$"

Route121_Text_JessicaIntro:
	.string "{JPN}まって! わたしの たいせつな ポケモンを\nよく みて いって!$"

Route121_Text_JessicaDefeat:
	.string "{JPN}まあ ひどい!\nそんなに ほんきに ならなくても!$"

Route121_Text_JessicaPostBattle:
	.string "{JPN}サファリゾーンで ポケモンを もっと\nつかまえて こようかしら。$"

Route121_Text_JessicaRegister:
	.string "{JPN}こんかいは てかげん して あげたの!\nつぎは そう いかないわよ!$"

Route121_Text_JessicaRematchIntro:
	.string "{JPN}たいせつな ポケモンが そだったの!\nよく みて いって!$"

Route121_Text_JessicaRematchDefeat:
	.string "{JPN}まあ ひどい!\nやっぱり てかげん して くれないのね!$"

Route121_Text_JessicaPostRematch:
	.string "{JPN}サファリゾーンで ポケモンを もっと\nつかまえて こようかしら。$"

Route121_Text_CristinIntro:
	.string "{JPN}わたしの にっかは トレーナーを\n1にちに 5にん たおす こと。\lあなたが 5にんめよ!$"

Route121_Text_CristinDefeat:
	.string "{JPN}いや!\nひどい ひとね!$"

Route121_Text_CristinPostBattle:
	.string "{JPN}こんなに かんたんに まけるなんて…\nつぎは かつわ!$"

Route121_Text_CristinRegister:
	.string "{JPN}はずかしくて たまらないわ!\nあなたの ことは わすれない…\lポケナビを かしなさい!$"

Route121_Text_CristinRematchIntro:
	.string "{JPN}あたらしい にっかは トレーナーを\n1にちに 10にん たおす こと。\lあなたが 10にんめよ!$"

Route121_Text_CristinRematchDefeat:
	.string "{JPN}まって! ひどいわ!\nもういちど しょうぶよ!$"

Route121_Text_CristinPostRematch:
	.string "{JPN}どうしても かてない あいて…\nぐすん…\lこんな ことが あるなんて…$"

Route121_Text_CaleIntro:
	.string "{JPN}こんなに にもつを もって いるのが\nみえないの?\pそれでも しょうぶ しろと いうの?$"

Route121_Text_CaleDefeat:
	.string "{JPN}まけて とうぜんよ!\nりょうてが ふさがって いるもの!$"

Route121_Text_CalePostBattle:
	.string "{JPN}ミナモデパートで かいすぎて しまったの。\pこの さきに あるのよ。\nあなたのような バッグが ほしいわ。$"

Route121_Text_MylesIntro:
	.string "{JPN}ひとの ポケモンを みるのが\nなにより すきなの!$"

Route121_Text_MylesDefeat:
	.string "{JPN}とても すばらしいわ!$"

Route121_Text_MylesPostBattle:
	.string "{JPN}いい ポケモンね!\nどうやって そだてて いるの?$"

Route121_Text_PatIntro:
	.string "{JPN}そだてた ポケモンを みんなに\nみて もらいたいの!$"

Route121_Text_PatDefeat:
	.string "{JPN}わあ!\nみごとだわ!$"

Route121_Text_PatPostBattle:
	.string "{JPN}どの ポケモンも おなじだけ かわいがって\nそだてて いるの えこひいきは しないわ。$"

Route121_Text_MarcelIntro:
	.string "{JPN}わたしの ポケモンは まけしらず!\nつぎ かったら コンテストに\lでる つもりなの。$"

Route121_Text_MarcelDefeat:
	.string "{JPN}あら どうして こうなったの?$"

Route121_Text_MarcelPostBattle:
	.string "{JPN}コンテストに でる まえに もうすこし\nきたえた ほうが よさそうね。$"

Route123_Text_WendyIntro:
	.string "{JPN}じぶんの つよさを ためして みたい?\nわたしが あいてに なって あげる!$"

Route123_Text_WendyDefeat:
	.string "You passed with flying colors!$"

Route123_Text_WendyPostBattle:
	.string "To best even me…\n"
	.string "Your strength is marvelous!$"

Route123_Text_BraxtonIntro:
	.string "You seem to have a big collection\n"
	.string "of GYM BADGES.\p"
	.string "Let me see if you're actually worthy of\n"
	.string "those BADGES!$"

Route123_Text_BraxtonDefeat:
	.string "Oh, you're worthy, all right!$"

Route123_Text_BraxtonPostBattle:
	.string "You did your BADGES proud in that\n"
	.string "match!$"

Route123_Text_VioletIntro:
	.string "They say that good times are filled\n"
	.string "with good aromas.$"

Route123_Text_VioletDefeat:
	.string "Oh…\n"
	.string "I smell the bitter scent of misery…$"

Route123_Text_VioletPostBattle:
	.string "The BERRY MASTER's garden is filled\n"
	.string "with uplifting fragrances.$"

Route123_Text_CameronIntro:
	.string "Being a psychic is about willpower.\p"
	.string "I've willed myself not to lose to\n"
	.string "anyone. That makes me strong!$"

Route123_Text_CameronDefeat:
	.string "I feel sad…$"

Route123_Text_CameronPostBattle:
	.string "Being a psychic is about willpower.\n"
	.string "I thought I wouldn't lose to you…$"

Route123_Text_CameronRegister:
	.string "I sense it!\n"
	.string "You and I shall battle again!\l"
	.string "I can't tell if I'll win, though…\p"
	.string "Let's see your POKéNAV.$"

Route123_Text_CameronRematchIntro:
	.string "I've convinced myself that I won't\n"
	.string "lose anymore. That makes me strong!$"

Route123_Text_CameronRematchDefeat:
	.string "I feel sad…$"

Route123_Text_CameronPostRematch:
	.string "I should train at MT. PYRE…\n"
	.string "I'll never beat you this way…$"

Route123_Text_JackiIntro:
	.string "Don't be too happy if your POKéMON\n"
	.string "develop psychic powers.\p"
	.string "You need to refine those powers to\n"
	.string "make them really useful.$"

Route123_Text_JackiDefeat:
	.string "Overwhelmed!$"

Route123_Text_JackiPostBattle:
	.string "We all have psychic powers.\n"
	.string "We've just forgotten how to use them.$"

Route123_Text_JackiRegister:
	.string "I would like to face you again.\n"
	.string "Is that okay with you?$"

Route123_Text_JackiRematchIntro:
	.string "Have you awoken the psychic powers\n"
	.string "within you?$"

Route123_Text_JackiRematchDefeat:
	.string "Astounding!$"

Route123_Text_JackiPostRematch:
	.string "Your power with POKéMON…\n"
	.string "That could be a psychic power, too.$"

Route123_Text_MiuIntro:
	.string "MIU: Hello, TRAINER. I hope your\n"
	.string "POKéMON won't cry when they lose.$"

Route123_Text_MiuDefeat:
	.string "MIU: Uh-oh, we lost.$"

Route123_Text_MiuPostBattle:
	.string "MIU: TRAINER, your POKéMON are\n"
	.string "strong because you are friends.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI: Okay!\n"
	.string "We're beating the TRAINER's POKéMON!$"

Route123_Text_YukiDefeat:
	.string "YUKI: Uh-oh, we lost.$"

Route123_Text_YukiPostBattle:
	.string "YUKI: Why are you so strong?\n"
	.string "We've never lost before.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_KindraIntro:
	.string "MT. PYRE…\n"
	.string "Where the spirits of POKéMON sleep…\l"
	.string "Will your POKéMON sleep?$"

Route123_Text_KindraDefeat:
	.string "Overflowing with vitality…$"

Route123_Text_KindraPostBattle:
	.string "MT. PYRE…\n"
	.string "Where the spirits of POKéMON sleep…\p"
	.string "It must overflow with a power that\n"
	.string "soothes spirits…$"

Route123_Text_FernandoIntro:
	.string "I'll turn your lights out while\n"
	.string "I rip through this tune!$"

Route123_Text_FernandoDefeat:
	.string "Hey, hold it!\n"
	.string "I was still playing the intro!$"

Route123_Text_FernandoPostBattle:
	.string "You're rock steady.\n"
	.string "I'd like to write a tune about you.$"

Route123_Text_FernandoRegister:
	.string "The next time, lend your ears to\n"
	.string "the full tune, will you?$"

Route123_Text_FernandoRematchIntro:
	.string "Today's the day I'm going to do it!\n"
	.string "I'll turn out your lights before\l"
	.string "I finish singing my song!$"

Route123_Text_FernandoRematchDefeat:
	.string "Hey, hold it!\n"
	.string "I haven't even hit the chorus!$"

Route123_Text_FernandoPostRematch:
	.string "I thought you'd be so enthralled\n"
	.string "by my tune, you'd lose.$"

Route123_Text_DavisIntro:
	.string "This is my awesome BUG POKéMON!\n"
	.string "My big brother got it for me.$"

Route123_Text_DavisDefeat:
	.string "Waaaah!\n"
	.string "You meanie!$"

Route123_Text_DavisPostBattle:
	.string "Don't tell my brother I lost.\n"
	.string "You have to keep it a secret!$"

Route123_Text_JazmynIntro:
	.string "My confidence will get a boost by\n"
	.string "beating someone obviously strong!$"

Route123_Text_JazmynDefeat:
	.string "There goes my confidence…$"

Route123_Text_JazmynPostBattle:
	.string "They say that you can't judge a person\n"
	.string "by their appearance.\p"
	.string "But often, their looks don't lie…$"

Route123_Text_FrederickIntro:
	.string "Hello, child!\n"
	.string "Can you spare some time?$"

Route123_Text_FrederickDefeat:
	.string "Ah, a mighty capable child!\n"
	.string "Let me contribute to your allowance.$"

Route123_Text_FrederickPostBattle:
	.string "Contribute to your allowance?\n"
	.string "Wasn't the prize money enough?$"

Route123_Text_AlbertoIntro:
	.string "I have to tell you, BIRD POKéMON\n"
	.string "are my obsession!\p"
	.string "Birds are cool!\n"
	.string "They're the best!$"

Route123_Text_AlbertoDefeat:
	.string "Even in defeat, BIRD POKéMON are cool!$"

Route123_Text_AlbertoPostBattle:
	.string "I gather BIRD POKéMON feathers that\n"
	.string "scatter during battles.\p"
	.string "I'm going to make a hat with\n"
	.string "BIRD POKéMON feathers.$"

Route123_Text_EdIntro:
	.string "When there are no TRAINERS around,\n"
	.string "I let my POKéMON battle each other.\l"
	.string "I watch them.$"

Route123_Text_EdDefeat:
	.string "I kind of like your POKéMON.$"

Route123_Text_EdPostBattle:
	.string "Hehe, I'm swiping your battling ideas!\n"
	.string "I think they'll make me better.$"

Route123_Text_JonasIntro:
	.string "I lay in ambush, and a TRAINER has\n"
	.string "landed in my trap!$"

Route123_Text_JonasDefeat:
	.string "If you don't lose, how am I supposed\n"
	.string "to have fun playing ninja?$"

Route123_Text_JonasPostBattle:
	.string "I'm going to ambush a weaker-looking\n"
	.string "TRAINER next time.$"

Route123_Text_KayleyIntro:
	.string "I just bought this parasol.\n"
	.string "My cuteness should be up by a third!$"

Route123_Text_KayleyDefeat:
	.string "You're better than me by about\n"
	.string "five times!$"

Route123_Text_KayleyPostBattle:
	.string "Using accessories effectively is\n"
	.string "the secret behind fashion appeal.$"

Route124_Text_SpencerIntro:
	.string "Hey, are you lost at sea?\p"
	.string "If you can beat my POKéMON,\n"
	.string "I can serve as your pilot.$"

Route124_Text_SpencerDefeat:
	.string "I lost my bearings in battle!$"

Route124_Text_SpencerPostBattle:
	.string "Many people lose their bearings at sea.\p"
	.string "If you're that sort, you should refer\n"
	.string "to the POKéNAV's MAP.$"

Route124_Text_RolandIntro:
	.string "Hm! You're riding a POKéMON instead\n"
	.string "of swimming yourself…\p"
	.string "I am envious!$"

Route124_Text_RolandDefeat:
	.string "Oh!\n"
	.string "I can't…$"

Route124_Text_RolandPostBattle:
	.string "I'm getting chilled…\n"
	.string "I've been in the water too long…\p"
	.string "I wish I could ride a POKéMON like you…$"

Route124_Text_JennyIntro:
	.string "If you just float in the sea like\n"
	.string "this, POKéMON come around to play.$"

Route124_Text_JennyDefeat:
	.string "Oh, darn.\n"
	.string "I've gone and lost.$"

Route124_Text_JennyPostBattle:
	.string "While swimming, I noticed that some\n"
	.string "POKéMON attack, and some just watch.\p"
	.string "I guess POKéMON have personalities\n"
	.string "of their own.$"

Route124_Text_JennyRegister:
	.string "It's only on a whim, but maybe I'll get\n"
	.string "you to register me in your POKéNAV.$"

Route124_Text_JennyRematchIntro:
	.string "If you just float in the sea like this,\n"
	.string "TRAINERS challenge you!$"

Route124_Text_JennyRematchDefeat:
	.string "That's strange…\n"
	.string "I lost again…$"

Route124_Text_JennyPostRematch:
	.string "This has nothing to do with anything,\n"
	.string "but maybe I'll visit the TRICK HOUSE.$"

Route124_Text_GraceIntro:
	.string "I'm growing bored of swimming…\n"
	.string "How about a battle?$"

Route124_Text_GraceDefeat:
	.string "I had no idea that you were\n"
	.string "this strong!$"

Route124_Text_GracePostBattle:
	.string "All the effort you put in must have\n"
	.string "made you this strong.$"

Route124_Text_ChadIntro:
	.string "Fufufufu… I dive deep underwater\n"
	.string "to go deep under cover.\l"
	.string "Plumbing the depths is where I excel!$"

Route124_Text_ChadDefeat:
	.string "Glub, glub, glub…\n"
	.string "I'm sinking…$"

Route124_Text_ChadPostBattle:
	.string "I have it on good authority that\n"
	.string "there's a DIVE spot around here.\p"
	.string "It gives me the urge to go deep\n"
	.string "again…$"

Route124_Text_LilaIntro:
	.string "LILA: Sigh…\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Let's battle so I won't have to dwell\n"
	.string "on that!$"

Route124_Text_LilaDefeat:
	.string "LILA: ROY! It's your fault we lost!\n"
	.string "You're in for it later!$"

Route124_Text_LilaPostBattle:
	.string "LILA: Sigh…\p"
	.string "If only it wasn't my little brother\n"
	.string "next to me, but a nice boyfriend…$"

Route124_Text_LilaNotEnoughMons:
	.string "LILA: You're planning to battle us?\n"
	.string "Not unless you have two POKéMON.$"

Route124_Text_RoyIntro:
	.string "ROY: My big sister is tough at POKéMON!\p"
	.string "Don't cry when you lose!$"

Route124_Text_RoyDefeat:
	.string "ROY: Uh-oh…\n"
	.string "My big sister will chew me out…$"

Route124_Text_RoyPostBattle:
	.string "ROY: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "That's why she doesn't have a\n"
	.string "boyfriend.$"

Route124_Text_LilaRoyRegister:
	.string "ROY: Will you battle with us again?\n"
	.string "But take it easy next time, okay?$"

Route124_Text_RoyNotEnoughMons:
	.string "ROY: Did you want to battle us?\n"
	.string "Bring two POKéMON, then.$"

Route124_Text_LilaRematchIntro:
	.string "LILA: Sigh…\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Oh, hi, it's been a while. Let's battle\n"
	.string "so I won't have to dwell on things!$"

Route124_Text_LilaRematchDefeat:
	.string "LILA: ROY!\n"
	.string "It's your fault we lost again!\p"
	.string "We're having a training session later!$"

Route124_Text_LilaPostRematch:
	.string "LILA: Sigh…\p"
	.string "If I had a nice boyfriend, we'd beat\n"
	.string "anyone with lovely combinations…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "LILA: You're planning to battle us?\n"
	.string "Not unless you have two POKéMON.$"

Route124_Text_RoyRematchIntro:
	.string "ROY: If we lose, I'll catch heck.\n"
	.string "I'm going to go totally all out!$"

Route124_Text_RoyRematchDefeat:
	.string "ROY: Uh-oh…\n"
	.string "My big sister will chew me out again.$"

Route124_Text_RoyPostRematch:
	.string "ROY: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "She's going to make me train really\n"
	.string "hard with POKéMON later…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "ROY: Did you want to battle us?\n"
	.string "Bring two POKéMON, then.$"

Route124_Text_DeclanIntro:
	.string "Here I am swimming by my lonesome\n"
	.string "on this wide, beautiful sea.\p"
	.string "There's no other word for it.\n"
	.string "This is pathetic!$"

Route124_Text_DeclanDefeat:
	.string "I'm feeling blue.\n"
	.string "Blue as the sky…$"

Route124_Text_DeclanPostBattle:
	.string "I should chat up lady SWIMMERS\n"
	.string "and invite them on a long swim.$"

Route124_Text_IsabellaIntro:
	.string "I'm not going to lose to some\n"
	.string "surfer TRAINER.$"

Route124_Text_IsabellaDefeat:
	.string "I've only got sweat in my eyes!\n"
	.string "I am not crying!$"

Route124_Text_IsabellaPostBattle:
	.string "You can find pretty colored shards\n"
	.string "of things around here.$"

Route125_Text_NolenIntro:
	.string "I heard you approaching, so I hung\n"
	.string "around for you!$"

Route125_Text_NolenDefeat:
	.string "I surrender!$"

Route125_Text_NolenPostBattle:
	.string "Sound travels faster in water than\n"
	.string "it does through air.$"

Route125_Text_StanIntro:
	.string "Hey, there!\n"
	.string "Check out my sweet POKéMON!$"

Route125_Text_StanDefeat:
	.string "I floundered…$"

Route125_Text_StanPostBattle:
	.string "I was blown away by HORSEA's charm,\n"
	.string "so I started swimming, too.$"

Route125_Text_TanyaIntro:
	.string "I'm tired of swimming.\n"
	.string "Are you up for a battle with me?$"

Route125_Text_TanyaDefeat:
	.string "You're too much!$"

Route125_Text_TanyaPostBattle:
	.string "Whew…\n"
	.string "Which way is it to MOSSDEEP CITY?$"

Route125_Text_SharonIntro:
	.string "How would you like to take on the\n"
	.string "WATER-type POKéMON I raised?$"

Route125_Text_SharonDefeat:
	.string "{JPN}まけた…$"

Route125_Text_SharonPostBattle:
	.string "Your power… You're the real deal.\n"
	.string "I'm amazed!$"

Route125_Text_ErnestIntro:
	.string "Ahoy! I'm a buff, tough SAILOR!\n"
	.string "I've braved the world's seas!$"

Route125_Text_ErnestDefeat:
	.string "Gwrroooar!\n"
	.string "I couldn't win!$"

Route125_Text_ErnestPostBattle:
	.string "The tide ebbs and flows inside the\n"
	.string "SHOAL CAVE.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Did you know?$"

Route125_Text_ErnestRegister:
	.string "Register me in your POKéNAV,\n"
	.string "and I'll tell you something good.$"

Route125_Text_ErnestRematchIntro:
	.string "It's high time I get my payback\n"
	.string "from you! Come on, we're battling!$"

Route125_Text_ErnestRematchDefeat:
	.string "I couldn't win!\n"
	.string "I flat out couldn't win!$"

Route125_Text_ErnestRematchPostBattle:
	.string "The SHOAL CAVE…\p"
	.string "There are places you can and can't\n"
	.string "get to depending on the rise and fall\l"
	.string "of the tide.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Don't forget!$"

Route125_Text_KimIntro:
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE. Someone told me.\l"
	.string "Are you going to see him, too?$"

Route125_Text_KimDefeat:
	.string "KIM: I thought we would win.$"

Route125_Text_KimPostBattle:
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE, doesn't he?\p"
	.string "Let's go see him, IRIS!$"

Route125_Text_KimNotEnoughMons:
	.string "KIM: No, no, no! You need two POKéMON,\n"
	.string "or it's just no good!$"

Route125_Text_IrisIntro:
	.string "IRIS: KIM, can you tell me what we're\n"
	.string "looking for out here?$"

Route125_Text_IrisDefeat:
	.string "IRIS: Oh, we came sort of close.$"

Route125_Text_IrisPostBattle:
	.string "IRIS: KIM, are we really going into\n"
	.string "the SHOAL CAVE?\l"
	.string "We'll get all wet.$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS: Oh, we could never, ever do\n"
	.string "anything like a 2-on-1 battle.$"

Route125_Text_PresleyIntro:
	.string "Why would a BIRDKEEPER like me\n"
	.string "come out to the sea?$"

Route125_Text_PresleyDefeat:
	.string "Okay.\n"
	.string "I'll tell you why I'm here.$"

Route125_Text_PresleyPostBattle:
	.string "I put a message in a bottle and put\n"
	.string "it out to sea.\p"
	.string "I'm sure that a girl SWIMMER will\n"
	.string "find it!$"

Route125_Text_AuronIntro:
	.string "Hey! Was it you throwing garbage\n"
	.string "into the sea?$"

Route125_Text_AuronDefeat:
	.string "Oh, you weren't throwing trash into\n"
	.string "the sea.$"

Route125_Text_AuronPostBattle:
	.string "I found an unsightly bottle bobbing\n"
	.string "in the waves earlier.\p"
	.string "It angers me that someone would\n"
	.string "pollute the sea!$"

Route126_Text_BarryIntro:
	.string "Swimming is a full-body workout!\n"
	.string "You will get fit!$"

Route126_Text_BarryDefeat:
	.string "I admit it!\n"
	.string "You win!$"

Route126_Text_BarryPostBattle:
	.string "Thanks to my daily swimming routine…\n"
	.string "Look! Feast your eyes on this physique!$"

Route126_Text_DeanIntro:
	.string "This towering white mountain of rock\n"
	.string "is SOOTOPOLIS CITY.$"

Route126_Text_DeanDefeat:
	.string "I was done in?$"

Route126_Text_DeanPostBattle:
	.string "I can't find the entrance to\n"
	.string "SOOTOPOLIS. Where could it be?$"

Route126_Text_NikkiIntro:
	.string "Ufufufufu!\n"
	.string "I'm a mermaid!$"

Route126_Text_NikkiDefeat:
	.string "My fantasy burst as if it were a bubble!\n"
	.string "Blub, blub, blub…$"

Route126_Text_NikkiPostBattle:
	.string "You thrashed me… I want to\n"
	.string "disappear in a wave of despair…$"

Route126_Text_BrendaIntro:
	.string "Hello, kiddo!\n"
	.string "Want a battle with me?$"

Route126_Text_BrendaDefeat:
	.string "Oh, noooooh!$"

Route126_Text_BrendaPostBattle:
	.string "I love frolicking with POKéMON in\n"
	.string "the sea like this!$"

Route126_Text_PabloIntro:
	.string "Check out this sculpted body!\n"
	.string "I'm more cut than a BLACK BELT!$"

Route126_Text_PabloDefeat:
	.string "Whoops! Too strong!\n"
	.string "Not bad! Not bad at all!$"

Route126_Text_PabloPostBattle:
	.string "Losing to you stimulated my senses!\n"
	.string "I'll train myself and POKéMON harder!$"

Route126_Text_PabloRegister:
	.string "Yep, you're not bad at all!\n"
	.string "I'd like to get to know you more!$"

Route126_Text_PabloRematchIntro:
	.string "Check out this beautiful body!\n"
	.string "I'm more shapely than a SWIMMER!$"

Route126_Text_PabloRematchDefeat:
	.string "Whoops! Really too strong!\n"
	.string "Not bad! Not bad at all!$"

Route126_Text_PabloPostRematch:
	.string "I'm going to train even harder!\n"
	.string "You're a great motivator!\l"
	.string "You have to come back again!$"

Route126_Text_LeonardoIntro:
	.string "I couldn't even swim last year,\n"
	.string "but now I'm a decent SWIMMER.\p"
	.string "I think I'm capable of anything now.$"

Route126_Text_LeonardoDefeat:
	.string "Sheesh, getting greedy didn't do\n"
	.string "a thing for me.$"

Route126_Text_LeonardoPostBattle:
	.string "If you practice at something,\n"
	.string "you will get better at it.\p"
	.string "You're young--don't be afraid to\n"
	.string "try all sorts of things!$"

Route126_Text_IsobelIntro:
	.string "If seawater gets up your nose,\n"
	.string "doesn't it feel terrible?$"

Route126_Text_IsobelDefeat:
	.string "Ack! Why, you…\n"
	.string "Glub!$"

Route126_Text_IsobelPostBattle:
	.string "Ooh, I choked on some water!\n"
	.string "It's bitter! It's salty!!$"

Route126_Text_SiennaIntro:
	.string "I'm throwing my whole heart\n"
	.string "into this!$"

Route126_Text_SiennaDefeat:
	.string "You had more heart!$"

Route126_Text_SiennaPostBattle:
	.string "I need to cool down now…\n"
	.string "I think I'll go for a dive.$"

Route127_Text_CamdenIntro:
	.string "I can see it in your face.\n"
	.string "You want to challenge me.$"

Route127_Text_CamdenDefeat:
	.string "Awawawawawa…$"

Route127_Text_CamdenPostBattle:
	.string "A well-played match leaves me feeling\n"
	.string "refreshed and serene.$"

Route127_Text_DonnyIntro:
	.string "Do you have a rival whom you just\n"
	.string "hate to lose against?$"

Route127_Text_DonnyDefeat:
	.string "Arrrgh!\n"
	.string "I hate losing!$"

Route127_Text_DonnyPostBattle:
	.string "If you have a rival, don't you get the\n"
	.string "feeling that you have to keep getting\l"
	.string "better?$"

Route127_Text_JonahIntro:
	.string "Through fishing, I have attained a\n"
	.string "state of becalmed serenity…\p"
	.string "Please, allow me to demonstrate…$"

Route127_Text_JonahDefeat:
	.string "Though I have lost, my heart remains\n"
	.string "calm…$"

Route127_Text_JonahPostBattle:
	.string "It matters not that I catch nothing.\n"
	.string "The line remains in the water…$"

Route127_Text_HenryIntro:
	.string "Whoops! Don't tell me I snagged\n"
	.string "a SURFING POKéMON?$"

Route127_Text_HenryDefeat:
	.string "I can't keep up!$"

Route127_Text_HenryPostBattle:
	.string "It'd be a handful if I hooked\n"
	.string "your tough POKéMON!$"

Route127_Text_RogerIntro:
	.string "Well, hey! This is a match between\n"
	.string "a POKéMON fan and a fishing buff!$"

Route127_Text_RogerDefeat:
	.string "No! My line's all tangled!\n"
	.string "The party's over!$"

Route127_Text_RogerPostBattle:
	.string "My fishing line's doing a dance!\n"
	.string "The tangle tango! Hahaha, snarl!$"

Route127_Text_AidanIntro:
	.string "BIRD POKéMON have excellent vision.\n"
	.string "They spot prey from great heights.$"

Route127_Text_AidanDefeat:
	.string "Whew… I give up.$"

Route127_Text_AidanPostBattle:
	.string "There're lots of diving spots in\n"
	.string "the sea around here.\p"
	.string "You can spot them easily from the sky\n"
	.string "because of their darker color.$"

Route127_Text_KojiIntro:
	.string "Run in your bare feet.\n"
	.string "That will toughen up your soles!$"

Route127_Text_KojiDefeat:
	.string "Yowch!\n"
	.string "I got a pebble under a toenail!$"

Route127_Text_KojiPostBattle:
	.string "Going barefoot feels great.\n"
	.string "But your RUNNING SHOES are cool, too.$"

Route127_Text_KojiRegister:
	.string "This is what I do to people who beat me!\n"
	.string "I hope we can do this again.$"

Route127_Text_KojiRematchIntro:
	.string "I still run in my bare feet daily.\n"
	.string "My soles are tough!$"

Route127_Text_KojiRematchDefeat:
	.string "Yowch!\n"
	.string "Pebbles dug into my arches!$"

Route127_Text_KojiPostRematch:
	.string "Want to go barefoot for a while?\n"
	.string "So I can try your RUNNING SHOES?$"

Route127_Text_AthenaIntro:
	.string "We should have a slow and methodical\n"
	.string "match.$"

Route127_Text_AthenaDefeat:
	.string "You didn't give me the chance to\n"
	.string "do any strategizing.$"

Route127_Text_AthenaPostBattle:
	.string "When I'm surrounded by the blue sea\n"
	.string "and sky, it feels as if time slows down.$"

Route128_Text_IsaiahIntro:
	.string "EVER GRANDE CITY is still a long ways\n"
	.string "away…$"

Route128_Text_IsaiahDefeat:
	.string "My first victory seems to be far\n"
	.string "away, too…$"

Route128_Text_IsaiahPostBattle:
	.string "My whole life has been about losing,\n"
	.string "but I will never give up!$"

Route128_Text_IsaiahRegister:
	.string "I know I'm not good now, but I think\n"
	.string "I can win eventually.\p"
	.string "Please register me in your POKéNAV.$"

Route128_Text_IsaiahRematchIntro:
	.string "I'm still feeling good. I'll keep on\n"
	.string "swimming to EVER GRANDE CITY.$"

Route128_Text_IsaiahRematchDefeat:
	.string "I've yet to taste my first victory…$"

Route128_Text_IsaiahPostRematch:
	.string "I'll eventually reach EVER GRANDE CITY\n"
	.string "where I can eventually win…$"

Route128_Text_KatelynIntro:
	.string "You have to swim, cycle, and then run\n"
	.string "a marathon in a triathlon.\p"
	.string "It's a grueling race that consists\n"
	.string "of three events.$"

Route128_Text_KatelynDefeat:
	.string "A POKéMON battle is grueling, too…$"

Route128_Text_KatelynPostBattle:
	.string "I have to ride a BIKE next, but…\n"
	.string "I'm about to throw in the towel…$"

Route128_Text_KatelynRegister:
	.string "Well, I may as well make the best\n"
	.string "of this. I'd like a rematch sometime.$"

Route128_Text_KatelynRematchIntro:
	.string "A triathlon is long. But I guess the\n"
	.string "road to become the POKéMON CHAMPION\l"
	.string "is also a long and grueling one.$"

Route128_Text_KatelynRematchDefeat:
	.string "A POKéMON battle really is harsh\n"
	.string "and unforgiving…$"

Route128_Text_KatelynPostRematch:
	.string "You should give serious thought to\n"
	.string "challenges on VICTORY ROAD.$"

Route128_Text_AlexaIntro:
	.string "We've been working so hard to mount\n"
	.string "a POKéMON LEAGUE challenge…\p"
	.string "We can't afford to lose now!$"

Route128_Text_AlexaDefeat:
	.string "Oh!\n"
	.string "How could this happen?!$"

Route128_Text_AlexaPostBattle:
	.string "After all I've done to get here,\n"
	.string "I won't give up after one setback.$"

Route128_Text_RubenIntro:
	.string "There is no stronger TRAINER than I!$"

Route128_Text_RubenDefeat:
	.string "This can't be!$"

Route128_Text_RubenPostBattle:
	.string "There probably is no stronger TRAINER\n"
	.string "than you!$"

Route128_Text_WayneIntro:
	.string "I want to visit EVER GRANDE, so I\n"
	.string "caught myself a POKéMON that knows\l"
	.string "the move WATERFALL to crest the falls.$"

Route128_Text_WayneDefeat:
	.string "I'm crestfallen!$"

Route128_Text_WaynePostBattle:
	.string "Awww, phooey!\p"
	.string "My POKéMON knows WATERFALL, but\n"
	.string "I don't have the SOOTOPOLIS GYM BADGE!$"

Route128_Text_HarrisonIntro:
	.string "You're looking awfully tough.\n"
	.string "I wonder if I can win?$"

Route128_Text_HarrisonDefeat:
	.string "Ouch!\n"
	.string "I guess it was impossible to win.$"

Route128_Text_HarrisonPostBattle:
	.string "There are tough TRAINERS galore\n"
	.string "around EVER GRANDE.\p"
	.string "Do you think I may be out\n"
	.string "of my league?$"

Route128_Text_CarleeIntro:
	.string "The sunlight seems to be more harsh\n"
	.string "in this area.$"

Route128_Text_CarleeDefeat:
	.string "I couldn't see very well because of\n"
	.string "the sun's glare.$"

Route128_Text_CarleePostBattle:
	.string "I should go back soon.\n"
	.string "I need to reapply my sunscreen.$"

Route129_Text_ChaseIntro:
	.string "This is my first triathlon.\n"
	.string "I'm all tense and nervous!$"

Route129_Text_ChaseDefeat:
	.string "Wroooaaar!\n"
	.string "I failed to win!$"

Route129_Text_ChasePostBattle:
	.string "If I'm all tensed up, I won't be able to\n"
	.string "give it my all.$"

Route129_Text_AllisonIntro:
	.string "I'm in the middle of a triathlon,\n"
	.string "but, sure, why don't we battle?$"

Route129_Text_AllisonDefeat:
	.string "I was sure I'd win!$"

Route129_Text_AllisonPostBattle:
	.string "Do you know what's the greatest thing\n"
	.string "about triathlons?\p"
	.string "Testing the limits of your own\n"
	.string "strength and endurance against\l"
	.string "Mother Nature!$"

Route129_Text_ReedIntro:
	.string "Say hey, hey!\n"
	.string "Let's get on with it!$"

Route129_Text_ReedDefeat:
	.string "Beat, I'm beaten.\n"
	.string "That's it, done!$"

Route129_Text_ReedPostBattle:
	.string "There's nothing for a loser.\n"
	.string "Time for me to beat it home.$"

Route129_Text_TishaIntro:
	.string "What's the hurry?\n"
	.string "Let's take it slow and easy.$"

Route129_Text_TishaDefeat:
	.string "Oh, my.\n"
	.string "I wanted to relax a little more…$"

Route129_Text_TishaPostBattle:
	.string "Don't you hate making mistakes when\n"
	.string "you're in a rush?\p"
	.string "That's why I try to take things\n"
	.string "slowly.$"

Route129_Text_ClarenceIntro:
	.string "Surfing isn't as easy as it seems,\n"
	.string "isn't that right?$"

Route129_Text_ClarenceDefeat:
	.string "Winning sure isn't easy.$"

Route129_Text_ClarencePostBattle:
	.string "You have your sights on the POKéMON\n"
	.string "LEAGUE? Keep at it!$"

Route130_Text_RodneyIntro:
	.string "What a surprise! I didn't expect to\n"
	.string "see a TRAINER out in the sea.\p"
	.string "I think we should battle!$"

Route130_Text_RodneyDefeat:
	.string "This kid's awfully tough…$"

Route130_Text_RodneyPostBattle:
	.string "Your eyes have that look of someone\n"
	.string "who's experienced harsh challenges\l"
	.string "and won. It suits you well!$"

Route130_Text_KatieIntro:
	.string "In the deep blue sea,\n"
	.string "my shattered blue heart finds\l"
	.string "comfort among waves.$"

Route130_Text_KatieDefeat:
	.string "Like the vast blue sea,\n"
	.string "the world of POKéMON spans\l"
	.string "depths beyond belief.$"

Route130_Text_KatiePostBattle:
	.string "The world's children dream\n"
	.string "of one day becoming\l"
	.string "the POKéMON CHAMPION.$"

Route130_Text_SantiagoIntro:
	.string "Floating on the open sea like this…\n"
	.string "It's peaceful.$"

Route130_Text_SantiagoDefeat:
	.string "I needed to be a little less peaceful!$"

Route130_Text_SantiagoPostBattle:
	.string "Swimming and battling like this…\n"
	.string "I'm one happy guy…$"

Route131_Text_RichardIntro:
	.string "The sea is teeming with POKéMON.\n"
	.string "It's not easy swimming, I tell you.$"

Route131_Text_RichardDefeat:
	.string "POKéMON raised by TRAINERS are\n"
	.string "seriously tough…$"

Route131_Text_RichardPostBattle:
	.string "Gasp… Gasp…\n"
	.string "I'm wiped out…\p"
	.string "The going's easy. It's the leaving\n"
	.string "that's the hard part.\p"
	.string "Will I have any energy left to make\n"
	.string "the return trip?$"

Route131_Text_HermanIntro:
	.string "The sea… The sea… The sea…\n"
	.string "The sea as far as these eyes can see!\l"
	.string "I'm sick and tired of the sea!$"

Route131_Text_HermanDefeat:
	.string "Bleah!$"

Route131_Text_HermanPostBattle:
	.string "Bored I am by the sea, but swim I must.\p"
	.string "I'm a born swimmer!\n"
	.string "That's what I am.$"

Route131_Text_SusieIntro:
	.string "Hi, sweetie, wait!\n"
	.string "We should battle, you and I!$"

Route131_Text_SusieDefeat:
	.string "You're tough in spite of the way\n"
	.string "you look!$"

Route131_Text_SusiePostBattle:
	.string "Did you see a guy over there who whines\n"
	.string "that he's bored of the sea?\p"
	.string "That's all talk.\n"
	.string "He's hopelessly in love with the sea!$"

Route131_Text_KaraIntro:
	.string "Why do men love bathing suits so much?\p"
	.string "They all ogle me!$"

Route131_Text_KaraDefeat:
	.string "I'm out of my depth!$"

Route131_Text_KaraPostBattle:
	.string "Maybe it's not my bathing suit that\n"
	.string "makes men look. It must be my beauty!$"

Route131_Text_ReliIntro:
	.string "RELI: We'll work together as siblings\n"
	.string "to take you on!$"

Route131_Text_ReliDefeat:
	.string "RELI: We couldn't win even though we\n"
	.string "worked together…$"

Route131_Text_ReliPostBattle:
	.string "RELI: The people of PACIFIDLOG are\n"
	.string "together with the sea and POKéMON from\l"
	.string "the time they are born.$"

Route131_Text_ReliNotEnoughMons:
	.string "RELI: You don't have two POKéMON?\n"
	.string "We can't enjoy a battle, then.$"

Route131_Text_IanIntro:
	.string "IAN: I'm doing my best together with\n"
	.string "my sis!$"

Route131_Text_IanDefeat:
	.string "IAN: I did my best with my sis,\n"
	.string "but we still couldn't win…$"

Route131_Text_IanPostBattle:
	.string "IAN: You know how PACIFIDLOG is\n"
	.string "a floating town?\p"
	.string "So, wherever there is the sea,\n"
	.string "that's a part of PACIFIDLOG!$"

Route131_Text_IanNotEnoughMons:
	.string "IAN: If you have two POKéMON,\n"
	.string "we'll take you on!$"

Route131_Text_TaliaIntro:
	.string "If you can beat me, I'll give you some\n"
	.string "great information!$"

Route131_Text_TaliaDefeat:
	.string "Oh?\n"
	.string "Did I lose?$"

Route131_Text_TaliaPostBattle:
	.string "There is an odd place nearby.\n"
	.string "There's a huge tower there.\l"
	.string "Why don't you go take a look?$"

Route131_Text_KevinIntro:
	.string "The people of PACIFIDLOG are\n"
	.string "a peaceful bunch.\p"
	.string "They never get angry.\n"
	.string "That goes for me, too.$"

Route131_Text_KevinDefeat:
	.string "Oops!$"

Route131_Text_KevinPostBattle:
	.string "Tch! …Oh, wait.\n"
	.string "I'm not angry. Honestly!\p"
	.string "But, boy, you're strong!\n"
	.string "Hahaha!$"

Route132_Text_GilbertIntro:
	.string "I used to catch colds all the time as\n"
	.string "a kid, but I became totally fit after\l"
	.string "I started swimming.$"

Route132_Text_GilbertDefeat:
	.string "I crave more power…$"

Route132_Text_GilbertPostBattle:
	.string "TRAINERS travel the fields and\n"
	.string "mountains, so they must be fit, too.$"

Route132_Text_DanaIntro:
	.string "I try not to swim where the currents\n"
	.string "are too strong.$"

Route132_Text_DanaDefeat:
	.string "Oh, please, no!$"

Route132_Text_DanaPostBattle:
	.string "If I get swept away, I'll lose all my\n"
	.string "sense of place…$"

Route132_Text_RonaldIntro:
	.string "Win or lose, you'll never know until\n"
	.string "you try!$"

Route132_Text_RonaldDefeat:
	.string "Waah!\n"
	.string "I sank in defeat!$"

Route132_Text_RonaldPostBattle:
	.string "I never battle when I know I'll win.\n"
	.string "I like to battle at the razor's edge of\l"
	.string "victory and defeat!$"

Route132_Text_KiyoIntro:
	.string "I contemplate POKéMON 24 hours a day.\n"
	.string "How could you possibly beat me?$"

Route132_Text_KiyoDefeat:
	.string "I lose.\n"
	.string "I will concede defeat.$"

Route132_Text_KiyoPostBattle:
	.string "Urggh…\n"
	.string "You're a POKéMON fanatic, aren't you?\p"
	.string "You must contemplate POKéMON 24 hours\n"
	.string "a day, don't you?$"

Route132_Text_MakaylaIntro:
	.string "I'm always with my husband,\n"
	.string "but I can win even without him.$"

Route132_Text_MakaylaDefeat:
	.string "Oh, I guess I wasn't good enough.$"

Route132_Text_MakaylaPostBattle:
	.string "That young man over there looks just\n"
	.string "like my husband when he was young.\p"
	.string "He's making me blush!$"

Route132_Text_JonathanIntro:
	.string "Someone's been watching me intently.\n"
	.string "Was it you?$"

Route132_Text_JonathanDefeat:
	.string "Wow!\n"
	.string "That's pretty strong, all right!$"

Route132_Text_JonathanPostBattle:
	.string "I can't shake this feeling that\n"
	.string "someone's watching me.\p"
	.string "I can't concentrate!$"

Route132_Text_PaxtonIntro:
	.string "Now where could my wife have gone?\n"
	.string "I'm always with her.\l"
	.string "I wonder if I can win on my own.$"

Route132_Text_PaxtonDefeat:
	.string "Ah, I see that I couldn't manage\n"
	.string "to win on my own after all.$"

Route132_Text_PaxtonPostBattle:
	.string "My wife must be looking for me.\n"
	.string "I'd best go find her right away.$"

Route132_Text_DarcyIntro:
	.string "I liked training here by myself.\n"
	.string "It's awful that all these people came!$"

Route132_Text_DarcyDefeat:
	.string "Okay! I won't complain about other\n"
	.string "people being here.$"

Route132_Text_DarcyPostBattle:
	.string "I suppose I can partner up with that\n"
	.string "old man and challenge that other team.$"

Route133_Text_FranklinIntro:
	.string "Did the currents carry you here, too?\n"
	.string "This must have been fated.\l"
	.string "Let's battle!$"

Route133_Text_FranklinDefeat:
	.string "Strong!\n"
	.string "Too much so!$"

Route133_Text_FranklinPostBattle:
	.string "It's just my luck that a tough TRAINER\n"
	.string "like you would drift here…\l"
	.string "I must be cursed…$"

Route133_Text_DebraIntro:
	.string "I've led a life of woe and misery…\n"
	.string "I've been cast away, and this is where\l"
	.string "I've drifted…$"

Route133_Text_DebraDefeat:
	.string "Another loss…$"

Route133_Text_DebraPostBattle:
	.string "A life adrift…\n"
	.string "I don't want it anymore!$"

Route133_Text_LindaIntro:
	.string "Welcome!\n"
	.string "I've been expecting you!$"

Route133_Text_LindaDefeat:
	.string "No! Please!$"

Route133_Text_LindaPostBattle:
	.string "A strong child TRAINER…\n"
	.string "That's so annoying!$"

Route133_Text_WarrenIntro:
	.string "I want to win like everyone else, but I\n"
	.string "won't raise POKéMON like everyone else.$"

Route133_Text_WarrenDefeat:
	.string "Darn it!\n"
	.string "My way is still too slack!$"

Route133_Text_WarrenPostBattle:
	.string "It's way more fun to do things the way\n"
	.string "I want than to be like everybody else.\l"
	.string "I mean, that's obvious!$"

Route133_Text_BeckIntro:
	.string "I came all the way out here with my\n"
	.string "BIRD POKéMON.$"

Route133_Text_BeckDefeat:
	.string "You…\n"
	.string "You're stunningly cool!$"

Route133_Text_BeckPostBattle:
	.string "I'd like to go back to FORTREE,\n"
	.string "but I've grown to like this place, too.$"

Route133_Text_MollieIntro:
	.string "I must have battled thousands\n"
	.string "of times. I've lost count.$"

Route133_Text_MollieDefeat:
	.string "I may have lost thousands of times,\n"
	.string "but a loss still stings.$"

Route133_Text_MolliePostBattle:
	.string "Keep at this, youngster. So you can\n"
	.string "become like my husband and me.$"

Route133_Text_ConorIntro:
	.string "Young people are too happy to go with\n"
	.string "the flow. They're without direction.$"

Route133_Text_ConorDefeat:
	.string "You have a firm sense of purpose.$"

Route133_Text_ConorPostBattle:
	.string "Don't let others lead you astray.\n"
	.string "Don't lose direction as you grow older.$"

Route134_Text_JackIntro:
	.string "Even those POKéMON that can swim are\n"
	.string "carried along by the rapid currents.$"

Route134_Text_JackDefeat:
	.string "Aiyeeeeh!$"

Route134_Text_JackPostBattle:
	.string "I think POKéMON enjoy the fast-running\n"
	.string "currents around these parts.$"

Route134_Text_LaurelIntro:
	.string "My LUVDISC are looking for a fun\n"
	.string "match. Will you join us?$"

Route134_Text_LaurelDefeat:
	.string "Oopsie!$"

Route134_Text_LaurelPostBattle:
	.string "There's a collector who's after\n"
	.string "the SCALES of LUVDISC.$"

Route134_Text_AlexIntro:
	.string "Okeydokey! That's enough rest, gang!\n"
	.string "It's time for a match!$"

Route134_Text_AlexDefeat:
	.string "Tuckered out again…$"

Route134_Text_AlexPostBattle:
	.string "My BIRD POKéMON get tired quickly after\n"
	.string "a long flight…$"

Route134_Text_HitoshiIntro:
	.string "You're a POKéMON TRAINER.\n"
	.string "No need for words. We battle now.$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "It was I who challenged you, and yet\n"
	.string "I lost. I am deeply shamed…$"

Route134_Text_AaronIntro:
	.string "The savage tide in this area serves to\n"
	.string "make us stronger than ever.$"

Route134_Text_AaronDefeat:
	.string "I willingly concede defeat.$"

Route134_Text_AaronPostBattle:
	.string "We will return for more training at\n"
	.string "METEOR FALLS.\p"
	.string "If you'd like, you should go, too.\n"
	.string "It will definitely toughen you up!$"

Route134_Text_KelvinIntro:
	.string "O-our boat!\n"
	.string "The tide carried it away!$"

Route134_Text_KelvinDefeat:
	.string "Awawawawah!\n"
	.string "Please, stop! Please!$"

Route134_Text_KelvinPostBattle:
	.string "If we can't SURF, how are we supposed\n"
	.string "to get home?\p"
	.string "Actually, I know a fainted POKéMON\n"
	.string "can still SURF, but it feels wrong.$"

Route134_Text_MarleyIntro:
	.string "Can your POKéMON dodge our\n"
	.string "lightning-quick attacks?$"

Route134_Text_MarleyDefeat:
	.string "I never knew such a technique existed!\n"
	.string "You've defeated us thoroughly.$"

Route134_Text_MarleyPostBattle:
	.string "I haven't lost my passion for speed.\n"
	.string "I will try harder.$"

Route134_Text_ReynaIntro:
	.string "My POKéMON can't be taken down\n"
	.string "easily!$"

Route134_Text_ReynaDefeat:
	.string "You're kidding!\n"
	.string "Explain how I lost!$"

Route134_Text_ReynaPostBattle:
	.string "Haha!\n"
	.string "You won, all right!\p"
	.string "I'll work my way back up by taking on\n"
	.string "TRAINERS I happen to meet!$"

Route134_Text_HudsonIntro:
	.string "Listen, have you seen another SAILOR\n"
	.string "around here?$"

Route134_Text_HudsonDefeat:
	.string "Now, that's something!$"

Route134_Text_HudsonPostBattle:
	.string "Our boat drifted out to sea.\p"
	.string "My buddy's a timid fellow, so I'm\n"
	.string "worried about him.$"

VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "The battery isn't charged enough.\p"
	.string "No. of steps required to fully\n"
	.string "charge the battery: {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "There are no Trainers within range\n"
	.string "who can battle…\p"
	.string "The VS Seeker was turned off.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady::
	.string "The other Trainers don't appear\n"
	.string "to be ready for battle.\p"
	.string "Let's wait till later.{PAUSE_UNTIL_PRESS}$"
