Route102_Text_CalvinIntro:
	.string "{JPN}ポケモンを つれて いるなら\nりっぱな ポケモントレーナー!\lわたしの しょうぶを ことわれないよ!$"

Route102_Text_CalvinDefeated:
	.string "{JPN}ああ まけた…\nもっと きたえて おくべきだった…$"

Route102_Text_CalvinPostBattle:
	.string "{JPN}ちょっと つよいなら\nさきに いって おいてよ!$"

Route102_Text_CalvinRegister:
	.string "{JPN}まえに あってから ずっと\nがんばって きたんだ。\pまた しょうぶ したいから ポケナビに\nとうろく して くれないかな?$"

Route102_Text_CalvinRegisterShort:
	.string "{JPN}また しょうぶ したいから ポケナビに\nとうろく して くれないかな?$"

Route102_Text_CalvinRematchIntro:
	.string "{JPN}きみに まけてから ひっしで\nポケモンを きたえて きた。\lしょうぶを ことわらせないよ!$"

Route102_Text_CalvinRematchDefeated:
	.string "{JPN}ああ まけた…\nきたえかたが まちがって いるのかな?$"

Route102_Text_CalvinRematchPostBattle:
	.string "{JPN}きみが つよく なるなら\nわたしも つよく なる。$"

Route102_Text_AllenIntro:
	.string "{JPN}トレーナーに なったばかり?\nおたがい しんまいだね!$"

Route102_Text_AllenDefeated:
	.string "{JPN}かてると おもって よんだのに…$"

Route102_Text_AllenPostBattle:
	.string "{JPN}まだ 1かいも かって いない…\nそろそろ かちたいなあ…$"

Route102_Text_RickIntro:
	.string "{JPN}ははっ めが あったね!\nむしポケモンで あいてに なるよ!$"

Route102_Text_RickDefeated:
	.string "{JPN}うっ のされた!$"

Route102_Text_RickPostBattle:
	.string "{JPN}トレーナーと めが あったら\nしょうぶ! それが ルール!$"

Route102_Text_TianaIntro:
	.string "{JPN}かちつづけて さいこうの トレーナーを\nめざすんだ。\pわたしの しゅっせに つきあって!$"

Route102_Text_TianaDefeated:
	.string "{JPN}きみの しゅっせを てつだって しまった…$"

Route102_Text_TianaPostBattle:
	.string "{JPN}かちあがるには もっと ポケモンを\nつかまえないと だめみたい。$"

Route103_Text_DaisyIntro:
	.string "{JPN}こころ やすらぐ かおりに\nひきよせられたの?$"

Route103_Text_DaisyDefeated:
	.string "{JPN}かおりに まどわされ なかったのね…$"

Route103_Text_DaisyPostBattle:
	.string "{JPN}アロマセラピーは かおりで こころを\nいやす ほうほうなの。$"

Route103_Text_AmyIntro:
	.string "{JPN}アミ: わたしは アミ。\nこちらは いもうとの リブ。\lふたりで たたかうの!$"

Route103_Text_AmyDefeated:
	.string "{JPN}アミ: あーあ まけちゃった。$"

Route103_Text_AmyPostBattle:
	.string "{JPN}アミ: トレーナー ふたりを あいてに\nするときは いろいろ かんがえないと\lいけないのよ。$"

Route103_Text_AmyNotEnoughPokemon:
	.string "{JPN}アミ: あら ポケモンが 1ぴきしか\nいないのね。\lそれでは しょうぶに ならないわ。$"

Route103_Text_LivIntro:
	.string "{JPN}リブ: わたしたち ひとつの チームで\nたたかうの。$"

Route103_Text_LivDefeated:
	.string "{JPN}リブ: ああ まけちゃった おねえちゃん…$"

Route103_Text_LivPostBattle:
	.string "{JPN}リブ: おねえちゃんとは ぴったり\nあうのに…\pそれでも まけちゃった…$"

Route103_Text_AmyLivRegister:
	.string "{JPN}リブ: ほんとは もっと つよいのよ…\nほんとだもん! こんどは みせて あげる!$"

Route103_Text_LivNotEnoughPokemon:
	.string "{JPN}リブ: わたしたちと しょうぶ するなら\nポケモンが 2ひき いるのよ!\lそうじゃないと ずるいわ!$"

Route103_Text_AmyRematchIntro:
	.string "{JPN}アミ: わたしは アミ。\nこちらは いもうとの リブ。\lふたりで たたかうの!$"

Route103_Text_AmyRematchDefeated:
	.string "{JPN}アミ: ああ もう!\nまた かてなかった…$"

Route103_Text_AmyRematchPostBattle:
	.string "{JPN}アミ: トレーナー ふたりを あいてに\nするときは いろいろ かんがえないと\lいけないのよ。$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "{JPN}アミ: あら ポケモンが 1ぴきしか\nいないのね。\lそれでは しょうぶに ならないわ。$"

Route103_Text_LivRematchIntro:
	.string "{JPN}リブ: わたしたち ひとつの チームで\nたたかうの。$"

Route103_Text_LivRematchDefeated:
	.string "{JPN}リブ: ああ また まけちゃった…\nおねえちゃん…$"

Route103_Text_LivRematchPostBattle:
	.string "{JPN}リブ: おねえちゃんとは ぴったり\nあうのに…\pどうして また まけたの?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "{JPN}リブ: わたしたちと しょうぶ するなら\nポケモンが 2ひき いるのよ!\lそうじゃないと ずるいわ!$"

Route103_Text_AndrewIntro:
	.string "{JPN}ぐあ! つりいとが からまった!\nいらいらして きたぞ!\lよし しょうぶだ!$"

Route103_Text_AndrewDefeated:
	.string "{JPN}ぐあ! まけた!\nますます いらいら するぞ!$"

Route103_Text_AndrewPostBattle:
	.string "{JPN}ぐぬぬ まだ はらが たつ…\nぐぬぬぬ…$"

Route103_Text_MiguelIntro:
	.string "{JPN}わたしの ポケモン とっても かわいいの!\nえんりょ しないで みて!$"

Route103_Text_MiguelDefeated:
	.string "{JPN}ああ そんな!\nかわいい わたしの ポケモン!$"

Route103_Text_MiguelPostBattle:
	.string "{JPN}わたしの ポケモンは ひんしに なっても\nかわいいの!$"

Route103_Text_MiguelRegister:
	.string "{JPN}また わたしの かわいい ポケモンを\nみに きて もらうんだから!$"

Route103_Text_MiguelRematchIntro:
	.string "{JPN}あら! わたしの かわいい ポケモンが\nもっと かわいく なったの!$"

Route103_Text_MiguelRematchDefeated:
	.string "{JPN}ああ!\nかわいい わたしの ポケモン!$"

Route103_Text_MiguelRematchPostBattle:
	.string "{JPN}いっしょに いる ときが ながいほど\nポケモンは かわいく なるの。$"

Route103_Text_PeteIntro:
	.string "{JPN}これくらいの きょりなら…\nおよいだら いいのに!$"

Route103_Text_PeteDefeated:
	.string "{JPN}やるじゃない!$"

Route103_Text_PetePostBattle:
	.string "{JPN}ああ きみの きもちが わかったわ。\pそんなに たよれる ポケモンが いたら\nわたしも なみのり したく なるもの!$"

Route103_Text_IsabelleIntro:
	.string "{JPN}まえを みて!\nぶつかっちゃう!$"

Route103_Text_IsabelleDefeated:
	.string "{JPN}うーん…$"

Route103_Text_IsabellePostBattle:
	.string "{JPN}およぎが へたで れんしゅう してたの…\nぶつかりそうに なって ごめんね。$"

Route103_Text_RhettIntro:
	.string "{JPN}うわっ!\nこんな せまい ところに よく きたな?$"

Route103_Text_RhettDefeated:
	.string "{JPN}うわっ!\nこの こ やるな!$"

Route103_Text_RhettPostBattle:
	.string "{JPN}こういう せまい ところが すきなのか?$"

Route103_Text_MarcosIntro:
	.string "{JPN}おれの ギターの ねに ひかれたか?$"

Route103_Text_MarcosDefeated:
	.string "{JPN}ひとりの ステージが だいなしだ…$"

Route103_Text_MarcosPostBattle:
	.string "{JPN}ひとの すくない ところで ひいて いたのに\nファンが たくさん あつまって きた。\lうれしいね。\pふふん プロに なろうかな。$"

Route104_Text_GinaIntro:
	.string "{JPN}ジナ: さあ ポケモンで しょうぶよ!$"

Route104_Text_GinaDefeat:
	.string "{JPN}ジナ: まけるのは くやしい!$"

Route104_Text_GinaPostBattle:
	.string "{JPN}ジナ: あなた つよいのね!\nもっと きたえないと!$"

Route104_Text_GinaNotEnoughMons:
	.string "{JPN}ジナ: あら? ポケモンが 1ぴきだけ?\nそれじゃ しょうぶ しないわ。\pポケモンが 1ぴきだと さびしいもの。\nかわいそうよ。$"

Route104_Text_MiaIntro:
	.string "{JPN}ミア: わたしたち ふたごだから\nいっしょに しょうぶ するの。$"

Route104_Text_MiaDefeat:
	.string "{JPN}ミア: ふたりで たたかったのに\nどっちも まけちゃった…$"

Route104_Text_MiaPostBattle:
	.string "{JPN}ミア: もっと ポケモンを きたえて\nあなたみたいに つよく なるわ。$"

Route104_Text_MiaNotEnoughMons:
	.string "{JPN}ミア: わたしたちと しょうぶ したいの?\pポケモンが 2ひき いないと だめよ。\lわたしたちのほうが つよいもの!$"

Route104_Text_IvanIntro:
	.string "{JPN}かくす ことは ない。\nおれは みずポケモンの めいじんだ!\pん?\nおれを しらないのか?$"

Route104_Text_IvanDefeat:
	.string "{JPN}そこそこ やれると おもって いたが\nそうでも なかったか… うう…$"

Route104_Text_IvanPostBattle:
	.string "{JPN}つりに むちゅうに なりすぎた。\nポケモンを そだてるのを わすれて いた…$"

Route104_Text_BillyIntro:
	.string "{JPN}すなはまに あしあとを のこすのが\nたのしいの!$"

Route104_Text_BillyDefeat:
	.string "{JPN}わあ! くつに すなが はいった!\nじゃりじゃり する!$"

Route104_Text_BillyPostBattle:
	.string "{JPN}どこにでも あしあとを のこしたいけど\nすぐに きえちゃうのよね…\lざんねん。$"

Route104_Text_HaleyIntro:
	.string "{JPN}しようかな…\nやめようかな?\pよし しょうぶ するわ!$"

Route104_Text_HaleyDefeat:
	.string "{JPN}しょうぶ しなければ よかった…$"

Route104_Text_HaleyPostBattle:
	.string "{JPN}まよった とき ほかの ひとに\nきめさせると どんな けっかに なっても\lこうかい する ものよ。\lおぼえて おいてね。$"

Route104_Text_HaleyRegister1:
	.string "{JPN}あなた つよいけど ポケナビに\nとうろく しようかしら…\lやめようかしら…\pよし とうろく するわ!$"

Route104_Text_HaleyRegister2:
	.string "{JPN}あなた つよいけど ポケナビに\nとうろく しようかしら…\lやめようかしら…\pよし とうろく するわ!$"

Route104_Text_HaleyRematchIntro:
	.string "{JPN}さあ しょうぶ しましょう!$"

Route104_Text_HaleyRematchDefeat:
	.string "{JPN}ああ…\nかてると おもったのに…$"

Route104_Text_HaleyPostRematch:
	.string "{JPN}じぶんで しょうぶを えらんだから\nまけも うけいれるわ。\pでも やっぱり くやしい!$"

Route104_Text_WinstonIntro:
	.string "{JPN}ええ しょうぶを うけて あげましょう。\nおかねは たくさん あるのよ。$"

Route104_Text_WinstonDefeat:
	.string "{JPN}どうして かてなかったの?$"

Route104_Text_WinstonPostBattle:
	.string "{JPN}おかねで かえない ものも あるのね。\nポケモンが そうだわ…$"

Route104_Text_WinstonRegister1:
	.string "{JPN}あら?\nポケナビを もって いるのね。\pよろこんで とうろく するわ。\nおかねなら たっぷり あるもの。$"

Route104_Text_WinstonRegister2:
	.string "{JPN}あら?\nポケナビを もって いるのね。\pよろこんで とうろく するわ。\nおかねなら たっぷり あるもの。$"

Route104_Text_WinstonRematchIntro:
	.string "{JPN}あなたに まけてから ポケモンに ついて\nいろいろ まなんだのよ。$"

Route104_Text_WinstonRematchDefeat:
	.string "{JPN}また まけたの?\nどうして かてないのかしら?$"

Route104_Text_WinstonPostRematch:
	.string "{JPN}おかねは ありあまる ほど あるのに\nポケモンでは かてない…\pポケモンの せかいは おくが ふかいわ…$"

Route104_Text_CindyIntro:
	.string "{JPN}わたしたち であう うんめい だったのね。\nしょうぶを おねがい できるかしら?$"

Route104_Text_CindyDefeat:
	.string "{JPN}あらまあ!$"

Route104_Text_CindyPostBattle:
	.string "{JPN}「こんにちは」は「さようなら」の はじまり。\nまた あえると いいわね。$"

Route104_Text_CindyRegister1:
	.string "{JPN}こんにちは また あったわね。\pひかれあって いるみたい。 おたがいの\nポケナビに とうろく しましょう。$"

Route104_Text_CindyRegister2:
	.string "{JPN}ひかれあって いる きねんに\pおたがいの ポケナビに\nとうろく しましょう。$"

Route104_Text_CindyRematchIntro:
	.string "{JPN}こんにちは また あったわね。\nしょうぶを おねがい できるかしら?$"

Route104_Text_CindyRematchDefeat:
	.string "{JPN}あらまあ…\nせいいっぱい やったのだけれど…$"

Route104_Text_CindyPostRematch:
	.string "{JPN}「こんにちは」は「さようなら」の はじまり。\nまた あえると いいわね。$"

Route104_Text_DarianIntro:
	.string "{JPN}つよそうな ポケモンを つりあげたぞ!\pなにか ふしぎな かんじが する!\nきっと つよいはずだ そうにちがいない!$"

Route104_Text_DarianDefeat:
	.string "{JPN}なんだと…$"

Route104_Text_DarianPostBattle:
	.string "{JPN}おい コイキング なまえまけ して いるぞ?$"

Route105_Text_FosterIntro:
	.string "{JPN}この あたりに ふしぎな いわが\nあるらしいんだ。\lなにか しらないか?$"

Route105_Text_FosterDefeated:
	.string "{JPN}いわの ことばかり かんがえて いて\nポケモンが よわいままだった…$"

Route105_Text_FosterPostBattle:
	.string "{JPN}いい いわは なんじかん ながめて いても\nあきないんだ。$"

Route105_Text_LuisIntro:
	.string "{JPN}ふう! こどもが おぼれて いるのかと\nしんぱい したよ。\pだいじょうぶ そうだね しょうぶでも\nどうかな?$"

Route105_Text_LuisDefeated:
	.string "{JPN}ごぼ… ごぼ…$"

Route105_Text_LuisPostBattle:
	.string "{JPN}おぼれた ときは かたほうの うでを\nはまべに むけて ふるんだよ。$"

Route105_Text_DominikIntro:
	.string "{JPN}まっさおな うみを およぐ…\nさいこうの きぶんだ!$"

Route105_Text_DominikDefeated:
	.string "{JPN}まけた…\nきぶんが しずむよ…$"

Route105_Text_DominikPostBattle:
	.string "{JPN}うみは なぜ あおいのか?\pカイナの はくぶつかんで ならったのに\nわすれて しまった。$"

Route105_Text_BeverlyIntro:
	.string "{JPN}みずの なかだと からだが かるいの。\nやせた みたい!$"

Route105_Text_BeverlyDefeated:
	.string "{JPN}うかんで いる…$"

Route105_Text_PostBattle:
	.string "{JPN}みずの なかでは たいじゅうが\n10ぶんの1に なるのよ。\pということは わたしは…\nおっと たいじゅうは ないしょ!$"

Route105_Text_ImaniIntro:
	.string "{JPN}あおい あおい そら…\nひろい うみ…\lなんて おだやかなの…$"

Route105_Text_ImaniDefeated:
	.string "{JPN}のんびり して いたら まけたわ!$"

Route105_Text_ImaniPostBattle:
	.string "{JPN}いっしょに いると おちつくって\nいわれたいの。 うふふ。$"

Route105_Text_AndresIntro:
	.string "{JPN}うみは わたしたちに ひみつを\nかくして いると おもうの。$"

Route105_Text_AndresDefeated:
	.string "{JPN}ええ…\nしょうぶは にがてなの…$"

Route105_Text_AndresPostBattle:
	.string "{JPN}せかいの うみには まだ たくさんの\nひみつが あるはず。\pぜんぶ みつけて みせるわ!$"

Route105_Text_AndresRegister:
	.string "{JPN}あら? こんなに よわいのに\nポケナビに とうろく して くれるの?$"

Route105_Text_AndresRematchIntro:
	.string "{JPN}よわいって いったでしょう…\nほんとうに いいの?$"

Route105_Text_AndresRematchDefeated:
	.string "{JPN}ええ…\nかてるとは おもって いなかったわ。$"

Route105_Text_AndresRematchPostBattle:
	.string "{JPN}しょうぶは よわくても たんけんへの\nじょうねつは まけないわ。\pせかいじゅうの うみを たびするの!$"

Route105_Text_JosueIntro:
	.string "{JPN}およいで つかれた。\nなれて いないんだ。\pきぶんてんかんに しょうぶ しよう!$"

Route105_Text_JosueDefeated:
	.string "{JPN}うみで しょうぶ したから まけたんだ。$"

Route105_Text_JosuePostBattle:
	.string "{JPN}うん ぼくには うみより そらの ほうが\nあって いる みたいだ。$"

Route106_Text_ElliotIntro:
	.string "{JPN}つりは うみと かわ どちらが すき?$"

Route106_Text_ElliotDefeated:
	.string "{JPN}ふかうみの つりの ように\nみごとに まけたよ!$"

Route106_Text_ElliotPostBattle:
	.string "{JPN}うみでも かわでも つりは さいこうだ。\nきみも そう おもうだろう?\lちがうかい?$"

Route106_Text_ElliotRegister:
	.string "{JPN}つりも いいが しょうぶも いい。\nよければ また あわないか?$"

Route106_Text_ElliotRematchIntro:
	.string "{JPN}つりで ポケモンを たくさん つかまえた。\nみごとな しょうぶを みせて やろう!$"

Route106_Text_ElliotRematchDefeated:
	.string "{JPN}また みごとに まけた!$"

Route106_Text_ElliotRematchPostBattle:
	.string "{JPN}かっても まけても ポケモンは さいこうだ!\nきみも そう おもうだろう?$"

Route106_Text_NedIntro:
	.string "{JPN}トイレに いきたく なったら\nみんな どう するんだ?\pトイレの あいだに おおものが かかったら\nこまる。 だから いけないんだ…$"

Route106_Text_NedDefeated:
	.string "{JPN}トイレを がまん して いたから まけた…$"

Route106_Text_NedPostBattle:
	.string "{JPN}まずい! おおものが かかる きが する!$"

Route106_Text_DouglasIntro:
	.string "{JPN}はははっ! はしるのは にがてだが\nみずの なかなら つかまらないぞ!$"

Route106_Text_DouglasDefeated:
	.string "{JPN}まいった!$"

Route106_Text_DouglasPostBattle:
	.string "{JPN}およぎの きょうそうなら まけないのに…$"

Route106_Text_KylaIntro:
	.string "{JPN}うみは おれの にわだ。 こどもだからと\nてかげんは しないぞ!$"

Route106_Text_KylaDefeated:
	.string "{JPN}もしかして てかげん したのか?$"

Route106_Text_KylaPostBattle:
	.string "{JPN}なみに ゆられて ただよう…\nすきなの! あなたも やってみたら?$"

Route107_Text_DarrinIntro:
	.string "{JPN}ふわあ…\pなみに ゆられて いるうちに\nねむって しまった みたい。$"

Route107_Text_DarrinDefeated:
	.string "{JPN}あはは まけちゃった…\nひとねむり しようかしら…$"

Route107_Text_DarrinPostBattle:
	.string "{JPN}なみに ゆられて うかぶのは\nふかふかの きもちいい ベッドで\lねむって いるみたい。$"

Route107_Text_TonyIntro:
	.string "{JPN}うみは わたしの にわの ような もの。\nしょうぶ しましょう!$"

Route107_Text_TonyDefeated:
	.string "{JPN}ホームで まけるなんて…\nショックだわ!$"

Route107_Text_TonyPostBattle:
	.string "{JPN}ゆめを むねに うみを およぐ…\pうたよ!\nさて もう ひとおよぎ してくるわ。$"

Route107_Text_TonyRegister:
	.string "{JPN}ほねの ずいまで おどろいたわ!\nわすれられない ように…$"

Route107_Text_TonyRematchIntro:
	.string "{JPN}ひろい うみを およいで\nポケモンが つよく なったの!$"

Route107_Text_TonyRematchDefeated:
	.string "{JPN}おどろいたわ!\pポケモンは つよく なったのに\nトレーナーの わたしは よわいまま!$"

Route107_Text_TonyRematchPostBattle:
	.string "{JPN}しょうぶで まなんだ ことが トレーナーを\nつよく するの。\lなみが おしえて くれたわ。$"

Route107_Text_DeniseIntro:
	.string "{JPN}ムロタウンって ちいさな まちを\nしって いる?$"

Route107_Text_DeniseDefeated:
	.string "{JPN}やだ もう!$"

Route107_Text_DenisePostBattle:
	.string "{JPN}ムロタウンの ホールで へんな ことばが\nはやって いるのよ。$"

Route107_Text_BethIntro:
	.string "{JPN}しょうぶ したいの?\nいいわよ おつきあい するわ!$"

Route107_Text_BethDefeated:
	.string "{JPN}あなたには およばなかったわ。$"

Route107_Text_BethPostBattle:
	.string "{JPN}あなたは これからも つよく なりそうね。\nわたしも がんばるわ!$"

Route107_Text_LisaIntro:
	.string "{JPN}リサ: きょうだいで しょうぶを\nいどむわ!$"

Route107_Text_LisaDefeated:
	.string "{JPN}リサ: すごい。\nつよさの けたが ちがうわ。$"

Route107_Text_LisaPostBattle:
	.string "{JPN}リサ: いっしょに うみへ いく ともだちは\nいるの?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "{JPN}リサ: しょうぶ するなら ポケモンを\nもっと つれて きて。$"

Route107_Text_RayIntro:
	.string "{JPN}レイ: ねえさんと いつも ポケモンで\nしょうぶ してるんだ。\pいつも まけるけど ふたりなら\nきみに かてる!$"

Route107_Text_RayDefeated:
	.string "{JPN}レイ: うわあ ぼくらより ずっと うえだ!$"

Route107_Text_RayPostBattle:
	.string "{JPN}レイ: この ポケモンは ねえさんに\nもらったんだ。 そだてて いまでは\lたいせつな あいぼうだよ!$"

Route107_Text_RayNotEnoughPokemon:
	.string "{JPN}レイ: しょうぶ するなら ポケモンを\nもっと つれて きてよ!$"

Route107_Text_CamronIntro:
	.string "{JPN}トライアスロンの とちゅうだけど\nぜんぜん つかれて いないぞ!$"

Route107_Text_CamronDefeated:
	.string "{JPN}つかれた…$"

Route107_Text_CamronPostBattle:
	.string "{JPN}このあと まだ すいえいと ランニングが\nのこって いる。\pだいじょうぶ かな?$"

Route108_Text_JeromeIntro:
	.string "{JPN}せかいの ななつの うみを およぐのが\nゆめなの!$"

Route108_Text_JeromeDefeated:
	.string "{JPN}これじゃ ななつの うみは およげないわ…$"

Route108_Text_JeromePostBattle:
	.string "{JPN}うみの ポケモンと あそぶのも\nすいえいの たのしみ!$"

Route108_Text_MatthewIntro:
	.string "{JPN}おーい きみも すてられぶねに\nいくのかい?$"

Route108_Text_MatthewDefeated:
	.string "{JPN}しずむ!\nごぼ… ごぼ…$"

Route108_Text_MatthewPostBattle:
	.string "{JPN}あの すてられぶねの なかに はいる\nひとも いるらしいよ。$"

Route108_Text_TaraIntro:
	.string "{JPN}うそつきの かれしが みずぎが にあうって\nいったのよ…$"

Route108_Text_TaraDefeated:
	.string "{JPN}ああ もう!$"

Route108_Text_TaraPostBattle:
	.string "{JPN}うそでも にあうって いわれるのは\nうれしいの…\lおんなごころは ふくざつなのよ…$"

Route108_Text_MissyIntro:
	.string "{JPN}うみが だいすき!\nおよぐと なやみを わすれられるの!$"

Route108_Text_MissyDefeated:
	.string "{JPN}しょうぶに まけると ストレスが たまる!$"

Route108_Text_MissyPostBattle:
	.string "{JPN}ストレスは およいで はっさん!\nけんこうに いいのよ!$"

Route108_Text_CoryIntro:
	.string "{JPN}みずタイプの ポケモンが すき。\nほかの ポケモンも すきよ!$"

Route108_Text_CoryDefeated:
	.string "{JPN}わあん! まけた!\nわあん! わあん!$"

Route108_Text_CoryPostBattle:
	.string "{JPN}さけぶと すっきり する!\nげんきが でるの!$"

Route108_Text_CoryRegister:
	.string "{JPN}つよい トレーナーも だいすき!\nポケナビに とうろく して!$"

Route108_Text_CoryRematchIntro:
	.string "{JPN}かっても まけても うみでの しょうぶは\nだいすき!$"

Route108_Text_CoryRematchDefeated:
	.string "{JPN}わあん! また まけた!\nわあん! わあん!$"

Route108_Text_CoryRematchPostBattle:
	.string "{JPN}こまった ときは うみに むかって\nさけんで みて!$"

Route108_Text_CarolinaIntro:
	.string "{JPN}わたしの ポケモンが じまんなの。\nすばやい しょうぶを みせて あげる!$"

Route108_Text_CarolinaDefeated:
	.string "{JPN}ぜんぜん かわいく なかったわ。$"

Route108_Text_CarolinaPostBattle:
	.string "{JPN}こうして うみに いるんだから\nピンクの ひらひらした みずぎも いいかも…$"

Route109_Text_DavidIntro:
	.string "{JPN}ふん! この きたえた ふっきんを みろ!\nこれが われた はらと いう ものだ!$"

Route109_Text_DavidDefeated:
	.string "{JPN}あいたっ!\nしくじった!$"

Route109_Text_DavidPostBattle:
	.string "{JPN}ふん!\pきたえた ふっきんと ポケモンの しょうぶは\nかんけいが なかったか!$"

Route109_Text_AliceIntro:
	.string "{JPN}ひやけどめは ちゃんと ぬって いる?$"

Route109_Text_AliceDefeated:
	.string "{JPN}いたた いたた!$"

Route109_Text_AlicePostBattle:
	.string "{JPN}ほおが いちばん やけやすいのよ!$"

Route109_Text_HueyIntro:
	.string "{JPN}せかいじゅうの みなとに よったが\nカイナが いちばんだ。$"

Route109_Text_HueyDefeated:
	.string "{JPN}きみが いちばんだ!$"

Route109_Text_HueyPostBattle:
	.string "{JPN}さいこうの みなとに さいこうの\nトレーナーが いた…$"

Route109_Text_EdmondIntro:
	.string "{JPN}うっぷ…\nしょうぶ? おれと?$"

Route109_Text_EdmondDefeated:
	.string "{JPN}うっ おおおおお…\nうっぷ…$"

Route109_Text_EdmondPostBattle:
	.string "{JPN}ふだんは もっと つよいんだ!\nふなよいが ひどくて…\pふなのりなのに…$"

Route109_Text_RickyIntro:
	.string "{JPN}のどが かわいた… かいはまハウスで\nソーダすいでも のみたいな…$"

Route109_Text_RickyDefeated:
	.string "{JPN}うーん…$"

Route109_Text_RickyPostBattle:
	.string "{JPN}はらが へって きた… うきわが おおきな\nドーナツに みえる…$"

Route109_Text_RickyRegister:
	.string "{JPN}のどが かわいて いない ときに\nまた しょうぶ して くれるかい?$"

Route109_Text_RickyRematchIntro:
	.string "{JPN}はらぺこだが しょうぶ するくらいの\nげんきは あるぞ!$"

Route109_Text_RickyRematchDefeated:
	.string "{JPN}まけた…\nはらが へって いたからだ…$"

Route109_Text_RickyRematchPostBattle:
	.string "{JPN}はまべで たべると なんでも\nすこし おいしく かんじるの。$"

Route109_Text_LolaIntro:
	.string "{JPN}ビーチパラソルって おおきな はなに\nみえない?$"

Route109_Text_LolaDefeated:
	.string "{JPN}ママー!$"

Route109_Text_LolaPostBattle:
	.string "{JPN}そらから はまべを みたら\nおおきな はなばたけに みえるはず!$"

Route109_Text_LolaRegister:
	.string "{JPN}わたし?\nまいにち ここに いるわ!$"

Route109_Text_LolaRematchIntro:
	.string "{JPN}もう まけないわ!\nうきわが あるんだから!$"

Route109_Text_LolaRematchDefeated:
	.string "{JPN}ママー!$"

Route109_Text_LolaRematchPostBattle:
	.string "{JPN}うきわが あると わたしも ポケモンも\nかわいさが ぐんと あがるの!$"

Route109_Text_AustinaIntro:
	.string "{JPN}うきわが ないと およげないけど\nポケモンでは まけないわ!$"

Route109_Text_AustinaDefeated:
	.string "{JPN}うきわが あるから まけたのかしら?$"

Route109_Text_AustinaPostBattle:
	.string "{JPN}うきわは おしゃれの ひとつ。\nこれが ないと でられないの。$"

Route109_Text_GwenIntro:
	.string "{JPN}ねえ おおきい トレーナー。\nしょうぶ して くれる?$"

Route109_Text_GwenDefeated:
	.string "{JPN}わあ つよいんだね。$"

Route109_Text_GwenPostBattle:
	.string "{JPN}どうやって そんなに つよく なったの?$"

Route109_Text_CarterIntro:
	.string "{JPN}わははは! おれさまが おおものを\nつりあげて やるぜ!$"

Route109_Text_CarterDefeated:
	.string "{JPN}おれさま いっぴき にがした…$"

Route109_Text_CarterPostBattle:
	.string "{JPN}おれさまが みるに きみは おおものだ。\nいや これから おおものに なる!$"

Route109_Text_PaulIntro:
	.string "{JPN}ポール: ああ しらけるな。\pふたりの たいせつな じかんを\nじゃま しないで ほしいな。$"

Route109_Text_PaulDefeated:
	.string "{JPN}ポール: まあ こうさん だね。$"

Route109_Text_PaulPostBattle:
	.string "{JPN}ポール: ここに いる ことは\nだれにも いわないで くれよ。\lふたりだけの せかいなんだ!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "{JPN}ポール: ぼくらは ふかく あいしあって いる。\nだから ポケモンも いっしょに\lたたかわせるのさ。$"

Route109_Text_MelIntro:
	.string "{JPN}メル: わたしたち ラブラブなの。\nこの あつさは ホウエンじゅうに とどくわ!$"

Route109_Text_MelDefeated:
	.string "{JPN}メル: まけちゃった わたしの せいね!\nポールに きらわれちゃう!$"

Route109_Text_MelPostBattle:
	.string "{JPN}メル: ねえ ポール おこってる?\nおこらないで。$"

Route109_Text_MelNotEnoughPokemon:
	.string "{JPN}メル: わたしたち ほんとうに\nあいしあって いるの。 だから ポケモンも\lいっしょに たたかわせるのよ。$"

Route109_Text_ChandlerIntro:
	.string "{JPN}じゃーん! みて?\nぼくの うきわ まんまるだよ!$"

Route109_Text_ChandlerDefeated:
	.string "{JPN}ああ ああ!\nざんねん!$"

Route109_Text_ChandlerPostBattle:
	.string "{JPN}まんまるの うきわを みせて あげたのに…$"

Route109_Text_HaileyIntro:
	.string "{JPN}およげないから およぐ まねを して いるの。$"

Route109_Text_HaileyDefeated:
	.string "{JPN}やっぱり!\nかてるとは おもって いなかったわ。$"

Route109_Text_HaileyPostBattle:
	.string "{JPN}およげるように なったら ポケモンも\nつよく なる きが するの。$"

Route109_Text_ElijahIntro:
	.string "{JPN}おれさまの ような マッチョには\nこういう ポケモンが ぴったりだ!$"

Route109_Text_ElijahDefeated:
	.string "{JPN}まけても かっこいい だろう?$"

Route109_Text_ElijahPostBattle:
	.string "{JPN}おれさまの ような マッチョには\nみなとが にあうんだ!\pカイナへ いくと するか。$"

Route110_Text_JacobIntro:
	.string "{JPN}うわっ あぶない!\n じてんしゃレースに なれて いないな。$"

Route110_Text_JacobDefeated:
	.string "{JPN}うわっ!\nブレーキが きかない!$"

Route110_Text_JacobPostBattle:
	.string "{JPN}パンクや ブレーキの ふぐあいは\nおおけがの もとだ!\lじてんしゃは よく てんけん しよう!$"

Route110_Text_AnthonyIntro:
	.string "{JPN}よお きみ!\nおれの スピードに ついてこられるか?$"

Route110_Text_AnthonyDefeated:
	.string "{JPN}はでに ころんだ!$"

Route110_Text_AnthonyPostBattle:
	.string "{JPN}はやさだけでは ポケモンで かてないか。\nかんがえなおさないとな…$"

Route110_Text_BenjaminIntro:
	.string "{JPN}じてんしゃが はやくても あわてるなよ!$"

Route110_Text_BenjaminDefeated:
	.string "{JPN}ポケモンの しょうぶでも\nあわてては いけないな…$"

Route110_Text_BenjaminPostBattle:
	.string "{JPN}あわてる ことも あせる ことも ない。\nゆっくり いこう。 じかんは たっぷりある。$"

Route110_Text_BenjaminRegister:
	.string "{JPN}あせらず こつこつ いくよ。\nその きが あったら こえを かけてくれ。$"

Route110_Text_BenjaminRematchIntro:
	.string "{JPN}すこし いそぎすぎでは ないか?\nおちついて しょうぶ しよう。$"

Route110_Text_BenjaminRematchDefeated:
	.string "{JPN}あわてなかったのに まけたな…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "{JPN}あわてる ことも あせる ことも ない。\nゆっくり いこう。 じかんは たっぷりある。$"

Route110_Text_AbigailIntro:
	.string "{JPN}トライアスロンは とても きびしい。\pすいえい じてんしゃ ランニングの\n3つを こなさないと いけないんだ。$"

Route110_Text_AbigailDefeated:
	.string "{JPN}ポケモンの しょうぶも きびしいな!$"

Route110_Text_AbigailPostBattle:
	.string "{JPN}つかれたから やすむよ。\nちゃんと やすむのも たいせつだ。$"

Route110_Text_AbigailRegister:
	.string "{JPN}きみの ことが きに いった!\nじてんしゃロードで また しょうぶ しよう。$"

Route110_Text_AbigailRematchIntro:
	.string "{JPN}じてんしゃに のりながらの しょうぶも\nいい ものだろう?$"

Route110_Text_AbigailRematchDefeated:
	.string "{JPN}すごい…\nどうして そんなに つよいんだ?$"

Route110_Text_AbigailRematchPostBattle:
	.string "{JPN}きろくを ねらって いたのかい?\pじゃま したなら ごめんよ!$"

Route110_Text_JasmineIntro:
	.string "{JPN}やすまずに こぎつづけて いる。\nふとももが いわの ようだ!$"

Route110_Text_JasmineDefeated:
	.string "{JPN}あしが つらないか しんぱいだ…$"

Route110_Text_JasminePostBattle:
	.string "{JPN}おや ジムバッジを もって いるのか?\nどうりで つよいわけだ!$"

Route110_Text_EdwardIntro:
	.string "{JPN}あなたの かんがえは よんで いる!\nまける はずが ない!$"

Route110_Text_EdwardDefeated:
	.string "{JPN}じぶんの まけは よめなかった!$"

Route110_Text_EdwardPostBattle:
	.string "{JPN}あなたの みらいが みえる…\pうむ…\nまばゆい ひかりが みえる…$"

Route110_Text_JaclynIntro:
	.string "{JPN}あははは!\nふしぎな ちからで まどわせて あげる!$"

Route110_Text_JaclynDefeated:
	.string "{JPN}ふしぎと まけて しまったわ!$"

Route110_Text_JaclynPostBattle:
	.string "{JPN}かてたのは ふしぎな ちからの おかげよ!\lいつも かてると おもわない ことね!$"

Route110_Text_EdwinIntro:
	.string "{JPN}あなたの ポケモンを みせて くれる?\nひとめだけで いいの!$"

Route110_Text_EdwinDefeated:
	.string "{JPN}コレクションを かんせい させたかったのに…$"

Route110_Text_EdwinPostBattle:
	.string "{JPN}しらない ポケモンを みると\nあつめたい きもちに ひが つくの!$"

Route110_Text_EdwinRegister:
	.string "{JPN}れんらくさきを あつめるのも すきなの…$"

Route110_Text_EdwinRematchIntro:
	.string "{JPN}やあ あたらしい ポケモンは つかまえた?\pあなたの ポケモンを みせて くれる?\nひとめだけで いいの!$"

Route110_Text_EdwinRematchDefeated:
	.string "{JPN}あなたの ポケモン…\nうらやましいわ。$"

Route110_Text_EdwinRematchPostBattle:
	.string "{JPN}めずらしい ポケモンは ぜんぶ\nじぶんの ものに したいわ!$"

Route110_Text_DaleIntro:
	.string "{JPN}おい!\nうしろから そっと ちかづくなよ!$"

Route110_Text_DaleDefeated:
	.string "{JPN}まけた!\nくそっ!$"

Route110_Text_DalePostBattle:
	.string "{JPN}つりは しゅうちゅうりょくが すべてだ。\nうきに めを こらすんだ。$"

Route110_Text_IsabelIntro:
	.string "{JPN}あははは! かわいい ポケモンを\nみせびらかすためなら どこへでも いくわ。$"

Route110_Text_IsabelDefeated:
	.string "{JPN}あらまあ これは いけないわ。$"

Route110_Text_IsabelPostBattle:
	.string "{JPN}しょうぶより ファンクラブで ポケモンを\nみせびらかす ほうが いいかしら。$"

Route110_Text_IsabelRegister:
	.string "{JPN}ポケモンを みせびらかすには\nぜんぜん たりなかったわ。\pできるだけ たくさん みて もらうわよ!$"

Route110_Text_IsabelRematchIntro:
	.string "{JPN}あははは! いくらでも わたしの ポケモンを\nみせて あげるわ!$"

Route110_Text_IsabelRematchDefeated:
	.string "{JPN}あらまあ これは いけないわ。$"

Route110_Text_IsabelRematchPostBattle:
	.string "{JPN}ポケモンを みせびらかすのは\nやめられそうに ないわ。\pでも しょうぶも すきなの!$"

Route110_Text_TimmyIntro:
	.string "{JPN}この あたりの くさむらで かっこいい\nポケモンを みつけたぞ!$"

Route110_Text_TimmyDefeated:
	.string "{JPN}かっこよさだけでは かてないか…$"

Route110_Text_TimmyPostBattle:
	.string "{JPN}つかまえたばかりの ポケモンで\nたたかうのは むずかしいな。$"

Route110_Text_AlyssaIntro:
	.string "{JPN}じてんしゃロードから おちて しまった…\pはずかしさを しょうぶで まぎらわせるぞ!$"

Route110_Text_AlyssaDefeated:
	.string "{JPN}おっと!\nまけて しまった!$"

Route110_Text_AlyssaPostBattle:
	.string "{JPN}おちて まけて…\nはずかしくて たまらない!$"

Route110_Text_JosephIntro:
	.string "{JPN}よし ぜんかいで いくぜ! ノリが わるいと\nおいて いかれるぞ!$"

Route110_Text_JosephDefeated:
	.string "{JPN}すっかり ノって いたな…$"

Route110_Text_JosephPostBattle:
	.string "{JPN}この くらいで へこたれないぜ!\nまけて おとこを あげたのさ!$"

Route110_Text_KalebIntro:
	.string "{JPN}かわいい ポケモンどうしが たすけあう…\nこんなに かわいい ものは ないわ!$"

Route110_Text_KalebDefeated:
	.string "{JPN}なさけも あわれみも ないのね?$"

Route110_Text_KalebPostBattle:
	.string "{JPN}はいはい よく がんばったわ かわいい こたち。$"

Route111_Text_DrewIntro:
	.string "{JPN}あら! その ゴーグル にあうわね。\nでも わたしの ほうが にあうと おもうの。\pどちらが にあうか しょうぶで きめましょう!$"

Route111_Text_DrewDefeat:
	.string "{JPN}ゴーグルの せいで よこが みえなかったわ。$"

Route111_Text_DrewPostBattle:
	.string "{JPN}ゴーグルが あれば すなあらしも\nとおれるのよ。\lうれしいわ!$"

Route111_Text_HeidiIntro:
	.string "{JPN}さばくで ピクニックを して いるの。\pトレーナーも かならず いるから\nここでも しょうぶが たのしめるわ!$"

Route111_Text_HeidiDefeat:
	.string "{JPN}ああ! いじわる!$"

Route111_Text_HeidiPostBattle:
	.string "{JPN}すなあらしの なかで たたかう ときは\nポケモンの HPに きを つけてね。\pみて いないと ひんしに なって しまうわ!$"

Route111_Text_BeauIntro:
	.string "{JPN}この ゴーグルを つけると ヒーローに\nなった きぶんだ。\lいまの おれには だれも かてない!$"

Route111_Text_BeauDefeat:
	.string "{JPN}きあいだけでは かてないか…$"

Route111_Text_BeauPostBattle:
	.string "{JPN}いつか ほんものの ヒーローに なる。\nもっと がんばって じぶんも ポケモンも\lつよく するぞ。$"

Route111_Text_BeckyIntro:
	.string "{JPN}さばくで かせきが みつかると きいた。\nどこに あるのだろう?$"

Route111_Text_BeckyDefeat:
	.string "{JPN}およばなかった…$"

Route111_Text_BeckyPostBattle:
	.string "{JPN}さばくで かせきが みつかるなら\nむかしは うみ だったに ちがいない。$"

Route111_Text_DustyIntro:
	.string "{JPN}30ねんかん いせきを さがして きた!\nこの わたしに\lしょうぶを いどむと いうのか?$"

Route111_Text_DustyDefeat:
	.string "{JPN}いせきは さがして きたが\nつよい ポケモンは さがして いなかった。$"

Route111_Text_DustyPostBattle:
	.string "{JPN}30ねんかん いせきを さがして きた!\pいや まてよ 40ねん だったか?\nどっち だったかな?$"

Route111_Text_DustyRegister:
	.string "{JPN}つよい ポケモンは さがして いない。\pだが なぜか ポケナビは すきなんだ。$"

Route111_Text_DustyRematchIntro:
	.string "{JPN}30ねんかん いせきを さがして きた!\pいや まてよ 40ねん だったか?\nともかく しょうぶを いどむのか?$"

Route111_Text_DustyRematchDefeat:
	.string "{JPN}いせきも みつからず つよい ポケモンも\nみつからず…$"

Route111_Text_DustyPostRematch:
	.string "{JPN}30ねんかん いせきを さがして きた!\pいや まてよ 40ねん だったか?\pうーむ 50ねんかも しれん…\nどれだけ さがして いるのだろう?$"

Route111_Text_TravisIntro:
	.string "{JPN}げんきいっぱい!\nポケモンも げんきいっぱい!$"

Route111_Text_TravisDefeat:
	.string "{JPN}ポケモンの げんきが なくなった…$"

Route111_Text_TravisPostBattle:
	.string "{JPN}げんきな トレーナーを みると\nつい めが いって しまうんだ。$"

Route111_Text_IreneIntro:
	.string "{JPN}どこへ いくのか しらないが\nしょうぶ しないか?$"

Route111_Text_IreneDefeat:
	.string "{JPN}いやに つよいな!$"

Route111_Text_IrenePostBattle:
	.string "{JPN}えんとつやまへ いこうと おもって いるが\nこの あたりの けしきも\lなかなか わるくない。$"

Route111_Text_DaisukeIntro:
	.string "{JPN}じぶんを きたえるため であう ものすべてに\nしょうぶを いどむ!$"

Route111_Text_DaisukeDefeat:
	.string "{JPN}まいった! こうさんだ!$"

Route111_Text_DaisukePostBattle:
	.string "{JPN}きみの ような つよい トレーナーに\nかてる ように なるまで\lきたえつづける しかない。$"

Route111_Text_WiltonIntro:
	.string "{JPN}どれだけ ポケモンを きたえたか\nみせて もらおう。$"

Route111_Text_WiltonDefeat:
	.string "{JPN}なるほど かなり きたえて あるな。$"

Route111_Text_WiltonPostBattle:
	.string "{JPN}ポケモンも トレーナーも しょうぶから\nおおくを まなぶ。\pだいじなのは まけても あきらめない ことだ。$"

Route111_Text_WiltonRegister:
	.string "{JPN}きみの きたえかたには まなぶ ことが おおい。\pよければ また しょうぶ して ほしい。$"

Route111_Text_WiltonRematchIntro:
	.string "{JPN}つぎの だんかいへ すすむために\nここで きたえて いる。\lきみも いっしょに どうだ!$"

Route111_Text_WiltonRematchDefeat:
	.string "{JPN}ほう なかなか やるな!$"

Route111_Text_WiltonPostRematch:
	.string "{JPN}それだけ つよいなら ポケモンリーグを\nめざすと いい。$"

Route111_Text_BrookeIntro:
	.string "{JPN}おお きみの ポケモンは いい やくしゃの\nようだ。\lぜひ しゅつえんを おねがいしたい。$"

Route111_Text_BrookeDefeat:
	.string "{JPN}つよそうなだけでは なく\nほんとうに つよかった!$"

Route111_Text_BrookePostBattle:
	.string "{JPN}ねっしんに そだてて きた つもりだが\nいやはや まだまだ\lやる ことが おおいな。$"

Route111_Text_BrookeRegister:
	.string "{JPN}きみの ような つよい ひとと\nもっと ともだちに なりたいものだ!$"

Route111_Text_BrookeRematchIntro:
	.string "{JPN}おぼえさせる わざで ポケモンは\nつよくも よわくも なる。\lそれを わすれては いけない。\pきみの ポケモンは どんな わざを\nおぼえて いるのかな?$"

Route111_Text_BrookeRematchDefeat:
	.string "{JPN}いい わざを おぼえさせて いるな!$"

Route111_Text_BrookePostRematch:
	.string "{JPN}いい わざを おぼえるまで\nポケモンの しんかを とめて\lおくべき だったかな…$"

Route111_Text_CeliaIntro:
	.string "{JPN}こんな ところで ピクニックを\nするんじゃ なかった!$"

Route111_Text_CeliaDefeat:
	.string "{JPN}ああ!\nやっぱり くるんじゃ なかった!$"

Route111_Text_CeliaPostBattle:
	.string "{JPN}これだけ すなあらしが ひどいと\nゴーグルが あっても ピクニックの\lしたくが できないわ…$"

Route111_Text_BryanIntro:
	.string "{JPN}どれほど つよいのか?\nその ひみつを あばいて みせよう!$"

Route111_Text_BryanDefeat:
	.string "{JPN}おお その つよさ!\nまさに なぞに つつまれて いる!$"

Route111_Text_BryanPostBattle:
	.string "{JPN}この さばくは うごく すなの なかに\nなぞを かくして いるのだ!$"

Route111_Text_BrandenIntro:
	.string "{JPN}まけて くれたら サンドイッチを\nわけて あげるよ。$"

Route111_Text_BrandenDefeat:
	.string "{JPN}ちぇっ! サンドイッチで じゅうぶんだと\nおもったのに…$"

Route111_Text_BrandenPostBattle:
	.string "{JPN}うちの サンドは サンドイッチが\nだいすきなんだ。$"

Route111_Text_TyronIntro:
	.string "{JPN}これが おきにいりの ポケモンだ!$"

Route111_Text_TyronDefeat:
	.string "{JPN}まって!\nおれの ポケモンを よく みたか?$"

Route111_Text_TyronPostBattle:
	.string "{JPN}しょうぶの ときは ポケモンを\nみせびらかせるのが うれしいんだ。\pみんな そう おもって いるはずだ!$"

Route111_Text_CelinaIntro:
	.string "{JPN}わたしの まいにちに すこし\nどきどきを ください。$"

Route111_Text_CelinaDefeat:
	.string "{JPN}ああ…\nどきどきしすぎたわ。$"

Route111_Text_CelinaPostBattle:
	.string "{JPN}むねの どうきが まだ おさまらない。\nすばらしい トレーナーね。$"

Route111_Text_HaydenIntro:
	.string "{JPN}これだけ はらが へって いると\nなさけを かける よゆうは ない!$"

Route111_Text_HaydenDefeat:
	.string "{JPN}うーん…$"

Route111_Text_HaydenPostBattle:
	.string "{JPN}はらが なる!\nきのみでも やこうかな…$"

Route111_Text_BiancaIntro:
	.string "{JPN}キンセツから きたのか?\nそれなら げんきいっぱい だろう!$"

Route111_Text_BiancaDefeat:
	.string "{JPN}おお!\nこれは こたえるな!$"

Route111_Text_BiancaPostBattle:
	.string "{JPN}この みちは…\nまだまだ さきが ながいぞ。$"

Route112_Text_BriceIntro:
	.string "{JPN}はははは!\nしょうぶ しないか?\lきみと おれで!\lはははは!$"

Route112_Text_BriceDefeat:
	.string "{JPN}まけた!\nはははは!$"

Route112_Text_BricePostBattle:
	.string "{JPN}はははは! はなに なにか はいった!\nははは はっくしょん!$"

Route112_Text_TrentIntro:
	.string "{JPN}やまを のぼりおりして あしは\nがちがちだ。\pそう かんたんには へこたれないぞ!$"

Route112_Text_TrentDefeat:
	.string "{JPN}いてっ! あしが つった!$"

Route112_Text_TrentPostBattle:
	.string "{JPN}じゅっキロも ある にもつを せおって\nやまみちを ほんきで\lあるいて みると いい。\lきみも やって みないか。\pそうすれば からだは しっかり\nしあがるんだ。$"

Route112_Text_TrentRegister:
	.string "{JPN}いてて あしが つった。\nリュックから ほうたいを\lとって くれるか?\pいや それは ポケナビだ!\nまあ いい とうろく して やろう。$"

Route112_Text_TrentRematchIntro:
	.string "{JPN}やまあるきで からだを きたえて いる。\nちからなら じしんが ある!$"

Route112_Text_TrentRematchDefeat:
	.string "{JPN}ちからで まけたのか?$"

Route112_Text_TrentRematchPostBattle:
	.string "{JPN}えんとつやまの うえに とんでもなく\nつよい トレーナーが いるらしい。\pのぼって いって しょうぶを いどむぞ!$"

Route112_Text_LarryIntro:
	.string "{JPN}ぼくは つよいんだ。\nまけても なかないぞ。$"

Route112_Text_LarryDefeat:
	.string "{JPN}うわあああん!$"

Route112_Text_LarryPostBattle:
	.string "{JPN}ママが こいしくて ないて いるんじゃ ないぞ!\nぐすん…$"

Route112_Text_CarolIntro:
	.string "{JPN}ピクニックに きたら やっぱり\nうたわなくちゃ!\lいっしょに うたいましょう!$"

Route112_Text_CarolDefeat:
	.string "{JPN}まあ とても つよいのね!$"

Route112_Text_CarolPostBattle:
	.string "{JPN}うたも ポケモンも じょうずでも へたでも\nかまわないの。\pいちばん たのしんだ ひとの かちよ!$"

Route112_Text_BryantIntro:
	.string "{JPN}えんとつやまの みちで あつい ポケモンを\nつかまえたぞ! みて くれ!$"

Route112_Text_BryantDefeat:
	.string "{JPN}はでに ふきとばされたな!$"

Route112_Text_BryantPostBattle:
	.string "{JPN}きみの たたかいかたが きに いった。\nどこか かっこいいんだ。$"

Route112_Text_ShaylaIntro:
	.string "{JPN}あら かわいい トレーナーね!\nロマンチックな しょうぶを おねがい!\lわたしも そこそこ やるのよ!$"

Route112_Text_ShaylaDefeat:
	.string "{JPN}まあ なんて つよいの!\nおどろいて しまったわ!$"

Route112_Text_ShaylaPostBattle:
	.string "{JPN}いま いそがしい?\nよければ すぐにでも また しょうぶを\lしたいのだけど…\lいそがしいなら いいのよ。$"

Route113_Text_JaylenIntro:
	.string "{JPN}この あたりが すずしい わけが\nわかるかしら?$"

Route113_Text_JaylenDefeat:
	.string "{JPN}うわあ!\nくさい!$"

Route113_Text_JaylenPostBattle:
	.string "{JPN}かざんばいが たいようを さえぎるから\nあまり あつく ならないの。\pあつさが にがてな わたしには ありがたいわ!$"

Route113_Text_DillonIntro:
	.string "{JPN}かざんの ふんかは だいちが いきて いる\nしょうこなの。$"

Route113_Text_DillonDefeat:
	.string "{JPN}とんでもなく つよいのね!$"

Route113_Text_DillonPostBattle:
	.string "{JPN}いたた! みえない!\nまつげに はいが はいったわ!\pはいと まつげ… なんてね?\pいまのは よくなかったわね ごめんなさい…$"

Route113_Text_MadelineIntro:
	.string "{JPN}この ひがさで かわいい ドンメルを\nよごれた かざんばいから\lまもって いるの。$"

Route113_Text_MadelineDefeat:
	.string "{JPN}はあ はあ…\nつかれたわ…$"

Route113_Text_MadelinePostBattle:
	.string "{JPN}あなた とても じょうずね。\nかんしん したわ!$"

Route113_Text_MadelineRegister:
	.string "{JPN}さあ ひがさの したへ どうぞ。\nポケナビに とうろく させて。$"

Route113_Text_MadelineRematchIntro:
	.string "{JPN}あら こんにちは ひさしぶりね?\nしょうぶに さそっても いいかしら?$"

Route113_Text_MadelineRematchDefeat:
	.string "{JPN}まあ すてき!$"

Route113_Text_MadelinePostRematch:
	.string "{JPN}あいかわらず じょうずね。\nかんしん するわ!$"

Route113_Text_LaoIntro:
	.string "{JPN}はいの なかから とびだす! やあっ!\nしょうぶを いどむ!$"

Route113_Text_LaoDefeat:
	.string "{JPN}いさぎよく まけを みとめよう!$"

Route113_Text_LaoPostBattle:
	.string "{JPN}かくれる わざを もっと みがかねば。\nさらばだ。$"

Route113_Text_LaoRegister:
	.string "{JPN}やあっ! にんじゃ ひでんの\nポケナビ とうろくを みよ!$"

Route113_Text_LaoRematchIntro:
	.string "{JPN}はいの なかから とびだす! やあっ!\nしょうぶを いどむ!$"

Route113_Text_LaoRematchDefeat:
	.string "{JPN}いさぎよく まけを みとめよう!$"

Route113_Text_LaoPostRematch:
	.string "My flawless concealment was let down\n"
	.string "by my immature battle skills…\p"
	.string "I bid thee farewell.$"

Route113_Text_LungIntro:
	.string "Thanks for finding me!\n"
	.string "But we still have to battle!$"

Route113_Text_LungDefeat:
	.string "I'll use my ninjutsu on you…\n"
	.string "“VOLCANIC ASH SWIRL CLOAK”!\p"
	.string "…What?\n"
	.string "It's already over?$"

Route113_Text_LungPostBattle:
	.string "You know what's crummy about hiding?\n"
	.string "It's lonely if no one comes along.$"

Route113_Text_ToriIntro:
	.string "TORI: Both of us, we collect ashes.\n"
	.string "We battle POKéMON, too.$"

Route113_Text_ToriDefeat:
	.string "TORI: We lost… It's boring, so I'm going\n"
	.string "to get some more ashes.$"

Route113_Text_ToriPostBattle:
	.string "TORI: How much ash do we have?\n"
	.string "Enough for a WHITE FLUTE, I hope.$"

Route113_Text_ToriNotEnoughMons:
	.string "TORI: We want to battle 2-on-2.\n"
	.string "If we didn't, we would lose!$"

Route113_Text_TiaIntro:
	.string "TIA: Both of us, we collect ashes.\n"
	.string "We battle POKéMON, too.$"

Route113_Text_TiaDefeat:
	.string "TIA: We couldn't win… It's boring,\n"
	.string "so I'm getting some more ashes.$"

Route113_Text_TiaPostBattle:
	.string "TIA: We have a lot of ashes!\n"
	.string "I think enough for a WHITE FLUTE!$"

Route113_Text_TiaNotEnoughMons:
	.string "TIA: We want to battle 2-on-2.\n"
	.string "If we don't, we won't win!$"

Route113_Text_CobyIntro:
	.string "Pfft, with these wings I can\n"
	.string "flick you away!$"

Route113_Text_CobyDefeat:
	.string "A… What?$"

Route113_Text_CobyPostBattle:
	.string "I don't know what to say when I get\n"
	.string "beaten so easily…$"

Route113_Text_SophieIntro:
	.string "The warmth here is making me drowsy.\n"
	.string "Battle with me so I can stay awake.$"

Route113_Text_SophieDefeat:
	.string "This is a dream.\n"
	.string "I'm sure of it…$"

Route113_Text_SophiePostBattle:
	.string "Losing burns me up…\n"
	.string "I'm just going to sleep right here!\l"
	.string "Zzz!$"

Route113_Text_LawrenceIntro:
	.string "Were you maybe in the middle\n"
	.string "of gathering volcanic ashes?$"

Route113_Text_LawrenceDefeat:
	.string "Ehehe.\n"
	.string "We got beaten cleanly.$"

Route113_Text_LawrencePostBattle:
	.string "I ought to hide under the ashes, too.$"

Route113_Text_WyattIntro:
	.string "Y-you want to battle with me?\n"
	.string "Even though I just caught my POKéMON?$"

Route113_Text_WyattDefeat:
	.string "Y-you're all happy to win?\n"
	.string "Even though it's only me?$"

Route113_Text_WyattPostBattle:
	.string "Oh, so now you want to say a word to\n"
	.string "the loser?\p"
	.string "Aren't you just the coolest?\n"
	.string "Humph!$"

Route114_Text_LennyIntro:
	.string "Yodelayhihoo!\p"
	.string "… …\p"
	.string "You're supposed to shout\n"
	.string "“yodelayhihoo” since it doesn't\l"
	.string "echo here!$"

Route114_Text_LennyDefeat:
	.string "Yodelayhihoo!$"

Route114_Text_LennyPostBattle:
	.string "When I was a wee tyke, I believed there\n"
	.string "was someone copying me and shouting\l"
	.string "back, “Yodelayhihoo.”$"

Route114_Text_LucasIntro:
	.string "If you're not prepared, you shouldn't\n"
	.string "be up in the mountains!$"

Route114_Text_LucasDefeat:
	.string "The mountains are unforgiving…$"

Route114_Text_LucasPostBattle:
	.string "In the winter, mountains turn deadly\n"
	.string "with blizzards and avalanches.$"

Route114_Text_ShaneIntro:
	.string "Camping's fun! You can fish, roast\n"
	.string "marshmallows, and tell spooky stories!\p"
	.string "But the best of all are the POKéMON\n"
	.string "battles!$"

Route114_Text_ShaneDefeat:
	.string "Way too strong!$"

Route114_Text_ShanePostBattle:
	.string "I think it's great that I can go\n"
	.string "camping with my POKéMON.$"

Route114_Text_NancyIntro:
	.string "I need to exercise after a meal.\n"
	.string "Let's have a match!$"

Route114_Text_NancyDefeat:
	.string "Oh, no!$"

Route114_Text_NancyPostBattle:
	.string "I just had a tasty meal.\n"
	.string "I'm getting drowsy…$"

Route114_Text_SteveIntro:
	.string "Ufufufufufu…\n"
	.string "Want to battle against my POKéMON?$"

Route114_Text_SteveDefeat:
	.string "M-My POKéMON…$"

Route114_Text_StevePostBattle:
	.string "A big body that's all lumpy and hard,\n"
	.string "enormous horns, and vicious fangs…\p"
	.string "Ufufufufu…\n"
	.string "I wish I had a POKéMON like that…$"

Route114_Text_SteveRegister:
	.string "Don't forget what you've done to me!\n"
	.string "I'll make it so you can't forget!$"

Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu…\n"
	.string "Come on, battle my POKéMON…$"

Route114_Text_SteveRematchDefeat:
	.string "I feel so lucky getting to see your\n"
	.string "POKéMON…$"

Route114_Text_StevePostRematch:
	.string "Ufufufufufu…\p"
	.string "When I see POKéMON battling, I get all\n"
	.string "shivery and shaky…$"

Route114_Text_BernieIntro:
	.string "If you're lighting a campfire,\n"
	.string "make sure you have water handy.$"

Route114_Text_BernieDefeat:
	.string "Thanks for dousing my fire!$"

Route114_Text_BerniePostBattle:
	.string "You really do have to be careful with\n"
	.string "any sort of fire in a forest.\p"
	.string "Don't ever underestimate the power\n"
	.string "of fire.$"

Route114_Text_BernieRegister:
	.string "You set my spirit on fire.\n"
	.string "Let's register each other!$"

Route114_Text_BernieRematchIntro:
	.string "Have you learned to keep water handy\n"
	.string "for campfires?$"

Route114_Text_BernieRematchDefeat:
	.string "I got hosed down before I could\n"
	.string "flare up, I guess.$"

Route114_Text_BerniePostRematch:
	.string "You really do have to be careful with\n"
	.string "any sort of fire in a forest.\p"
	.string "Don't ever underestimate the power\n"
	.string "of fire.$"

Route114_Text_ClaudeIntro:
	.string "If we were fishing, you wouldn't stand\n"
	.string "a chance against me.\l"
	.string "So, bring on your POKéMON!$"

Route114_Text_ClaudeDefeat:
	.string "If we were fishing, I would've won…$"

Route114_Text_ClaudePostBattle:
	.string "I think I'll try my luck at landing\n"
	.string "a big one at METEOR FALLS.\p"
	.string "There has to be something in there.\n"
	.string "I just know it.$"

Route114_Text_NolanIntro:
	.string "I like to fish. But I also like to\n"
	.string "battle!\p"
	.string "If anyone challenges me, I'm there,\n"
	.string "even if I'm fishing.$"

Route114_Text_NolanDefeat:
	.string "I like to battle, but that doesn't\n"
	.string "mean I'm good at it…$"

Route114_Text_NolanPostBattle:
	.string "This time I'll do it!\p"
	.string "I always think that, so I can't walk\n"
	.string "away from fishing or POKéMON.$"

Route114_Text_TyraIntro:
	.string "TYRA: Well, sure.\n"
	.string "I'm in the mood for it.\l"
	.string "I'll teach you a little about POKéMON.$"

Route114_Text_TyraDefeat:
	.string "TYRA: What an amazing battle style!$"

Route114_Text_TyraPostBattle:
	.string "TYRA: I was teaching my junior IVY\n"
	.string "about POKéMON.$"

Route114_Text_TyraNotEnoughMons:
	.string "TYRA: Giggle…\n"
	.string "If you want to battle with us, just one\l"
	.string "POKéMON isn't enough!$"

Route114_Text_IvyIntro:
	.string "IVY: Who taught you about POKéMON?$"

Route114_Text_IvyDefeat:
	.string "IVY: What an amazing battle style!$"

Route114_Text_IvyPostBattle:
	.string "IVY: I started training POKéMON\n"
	.string "because TYRA, my student mentor,\l"
	.string "taught me!$"

Route114_Text_IvyNotEnoughMons:
	.string "IVY: Do you only have one POKéMON?\n"
	.string "I think it must feel lonesome.$"

Route114_Text_KaiIntro:
	.string "I landed a big one!\n"
	.string "A huge one, I tell you!$"

Route114_Text_KaiDefeat:
	.string "What was that about?\n"
	.string "Did mine lose in size?$"

Route114_Text_KaiPostBattle:
	.string "Okay!\n"
	.string "I'll just fish me a bigger one!$"

Route114_Text_CharlotteIntro:
	.string "Me!\n"
	.string "I'm not just a pretty face!$"

Route114_Text_CharlotteDefeat:
	.string "That wasn't cute in the least!$"

Route114_Text_CharlottePostBattle:
	.string "I don't want a POKéMON that's\n"
	.string "just cute.\p"
	.string "I adore cute ones that have a quirk\n"
	.string "or two!$"

Route114_Text_AngelinaIntro:
	.string "Have you made your POKéMON evolve\n"
	.string "very much?$"

Route114_Text_AngelinaDefeat:
	.string "Oh, I see.\n"
	.string "That's good to know.$"

Route114_Text_AngelinaPostBattle:
	.string "Some POKéMON change so much when\n"
	.string "they evolve, it's startling!$"

Route115_Text_TimothyIntro:
	.string "Hm…\n"
	.string "You seem rather capable…\l"
	.string "Let me keep you company!$"

Route115_Text_TimothyDefeat:
	.string "You're much stronger than\n"
	.string "I'd imagined!$"

Route115_Text_TimothyPostBattle:
	.string "There is no such thing as a born genius.\n"
	.string "It all depends on effort!\l"
	.string "That is what I believe…$"

Route115_Text_TimothyRegister:
	.string "Hmm… A loss this thorough has been\n"
	.string "a distant memory.\p"
	.string "If you would allow it, I wish for\n"
	.string "another opportunity to do battle.$"

Route115_Text_TimothyRematchIntro:
	.string "Hm… As always, your agility speaks\n"
	.string "for itself.\l"
	.string "Come, keep me company!$"

Route115_Text_TimothyRematchDefeat:
	.string "As strong as ever!$"

Route115_Text_TimothyPostRematch:
	.string "All it takes is effort!\p"
	.string "I lost because I haven't put in enough\n"
	.string "effort!$"

Route115_Text_KoichiIntro:
	.string "You!\p"
	.string "My MACHOP!\p"
	.string "Demand a battle!$"

Route115_Text_KoichiDefeat:
	.string "{JPN}いたた いたた!$"

Route115_Text_KoichiPostBattle:
	.string "My MACHOP crew!\p"
	.string "So long as they seek power, I will\n"
	.string "grow strong with them!$"

Route115_Text_NobIntro:
	.string "My strongest skill is busting bricks\n"
	.string "with my forehead!$"

Route115_Text_NobDefeat:
	.string "Ugwaaaah!\n"
	.string "My head is busted!$"

Route115_Text_NobPostBattle:
	.string "I've been teaching my POKéMON karate.\p"
	.string "It looks like they'll get a lot better\n"
	.string "than me. I'm excited about that.$"

Route115_Text_NobRegister:
	.string "You impress me! Give me a rematch\n"
	.string "after I redo my training!$"

Route115_Text_NobRematchIntro:
	.string "After you beat me, we trained hard to\n"
	.string "improve our skills.\l"
	.string "Come on, give us a rematch!$"

Route115_Text_NobRematchDefeat:
	.string "Ugwaaah!\n"
	.string "We lost again!$"

Route115_Text_NobPostRematch:
	.string "My POKéMON will grow stronger!\n"
	.string "I'll redouble my training!$"

Route115_Text_CyndyIntro:
	.string "This beach is my secret training spot!\n"
	.string "Don't come butting in!$"

Route115_Text_CyndyDefeat:
	.string "I haven't trained enough!$"

Route115_Text_CyndyPostBattle:
	.string "The sand acts as a cushion to reduce\n"
	.string "impact and prevent injury.\l"
	.string "This is the perfect place to train.$"

Route115_Text_CyndyRegister:
	.string "Okay, fine, you're free to come here.\n"
	.string "In return, I'd like to battle you again.$"

Route115_Text_CyndyRematchIntro:
	.string "Okay, let's get this battle on!$"

Route115_Text_CyndyRematchDefeat:
	.string "I can battle but my POKéMON…$"

Route115_Text_CyndyPostRematch:
	.string "Even when I lose, I still get some\n"
	.string "enjoyment out of it.\l"
	.string "It must be that I love POKéMON.$"

Route115_Text_HectorIntro:
	.string "I have a rare POKéMON!\n"
	.string "Would you like me to show you?$"

Route115_Text_HectorDefeat:
	.string "You…\n"
	.string "You want my POKéMON, don't you?$"

Route115_Text_HectorPostBattle:
	.string "I have this rare POKéMON.\n"
	.string "It's enough to keep me satisfied.$"

Route115_Text_KyraIntro:
	.string "I'll battle while I'm running!\n"
	.string "Try to keep up with me!$"

Route115_Text_KyraDefeat:
	.string "Gasp, gasp…$"

Route115_Text_KyraPostBattle:
	.string "I made the mistake of trying to battle\n"
	.string "while running!\p"
	.string "I should take a run to calm down…$"

Route115_Text_JaidenIntro:
	.string "Take that!\n"
	.string "Ultra POKéMON ninja attack!$"

Route115_Text_JaidenDefeat:
	.string "Waaah!\n"
	.string "Our strategy failed!$"

Route115_Text_JaidenPostBattle:
	.string "But my POKéMON were ultra,\n"
	.string "weren't they?$"

Route115_Text_HeleneIntro:
	.string "My POKéMON have black belt-level\n"
	.string "strength!$"

Route115_Text_HeleneDefeat:
	.string "This is too humiliating!$"

Route115_Text_HelenePostBattle:
	.string "I rarely meet anyone who's better\n"
	.string "than me…\p"
	.string "I get it now!\n"
	.string "You're a GYM LEADER, aren't you?$"

Route115_Text_AlixIntro:
	.string "Our eyes met!\n"
	.string "There's no getting away now!$"

Route115_Text_AlixDefeat:
	.string "Gah!\n"
	.string "Not bad!$"

Route115_Text_AlixPostBattle:
	.string "Oh, well.\n"
	.string "I think I will TELEPORT home.$"

Route115_Text_MarleneIntro:
	.string "You've disturbed my meditation…\n"
	.string "You'll be punished for it.$"

Route115_Text_MarleneDefeat:
	.string "You've broken my concentration!$"

Route115_Text_MarlenePostBattle:
	.string "I was meditating with my POKéMON.\n"
	.string "But this place isn't very peaceful…$"

Route116_Text_ClarkIntro:
	.string "If the tunnel doesn't go through, then\n"
	.string "I'll just go over the top.$"

Route116_Text_ClarkDefeat:
	.string "Gasp… Gasp…\n"
	.string "Losing made me tired…$"

Route116_Text_ClarkPostBattle:
	.string "It's no big deal if there's no tunnel.\n"
	.string "To a HIKER, mountains are roads!$"

Route116_Text_JoeyIntro:
	.string "My POKéMON rule!\n"
	.string "Check them out!$"

Route116_Text_JoeyDefeat:
	.string "Ouch! A scrape!\n"
	.string "I have to put on a bandage!$"

Route116_Text_JoeyPostBattle:
	.string "Bandages are signs of toughness!\n"
	.string "I've got another one!$"

Route116_Text_JoseIntro:
	.string "My BUG POKéMON are tough!\n"
	.string "Let's battle!$"

Route116_Text_JoseDefeat:
	.string "I lost!\n"
	.string "I thought I had you!$"

Route116_Text_JosePostBattle:
	.string "BUG POKéMON evolve quickly.\n"
	.string "So they get strong quickly, too.$"

Route116_Text_JaniceIntro:
	.string "Let me teach you how strong my\n"
	.string "adorable POKéMON is!$"

Route116_Text_JaniceDefeat:
	.string "You're a notch above me…$"

Route116_Text_JanicePostBattle:
	.string "POKéMON that possess cuteness and\n"
	.string "power, that's ideal, I think.$"

Route116_Text_JerryIntro:
	.string "We learn all sorts of things at the\n"
	.string "TRAINER'S SCHOOL.\p"
	.string "I want to test things out for real!$"

Route116_Text_JerryDefeat:
	.string "I slacked off in school…\n"
	.string "That's why I lost.$"

Route116_Text_JerryPostBattle:
	.string "I'll have to redo some courses at\n"
	.string "the TRAINER'S SCHOOL.\l"
	.string "If I don't, ROXANNE will be steamed.$"

Route116_Text_JerryRegister1:
	.string "I learned at the TRAINER'S SCHOOL\n"
	.string "that a POKéNAV can register TRAINERS.\p"
	.string "I don't really get what that means,\n"
	.string "so can I just try it?$"

Route116_Text_JerryRegister2:
	.string "I learned at the TRAINER'S SCHOOL\n"
	.string "that a POKéNAV can register TRAINERS.\p"
	.string "I don't really get what that means,\n"
	.string "so can I just try it?$"

Route116_Text_JerryRematchIntro:
	.string "I've been studying seriously at the\n"
	.string "TRAINER'S SCHOOL.\l"
	.string "I won't lose like I did last time.$"

Route116_Text_JerryRematchDefeat:
	.string "Hunh?\n"
	.string "I studied diligently.$"

Route116_Text_JerryPostRematch:
	.string "I'll have to redo some courses at\n"
	.string "the TRAINER'S SCHOOL.\l"
	.string "If I don't, ROXANNE will be steamed.$"

Route116_Text_KarenIntro:
	.string "I study at school, and I study on\n"
	.string "the way home, too!$"

Route116_Text_KarenDefeat:
	.string "I'm in shock--I lost?$"

Route116_Text_KarenPostBattle:
	.string "Awww, I'll never become an elegant\n"
	.string "TRAINER like ROXANNE this way!$"

Route116_Text_KarenRegister1:
	.string "Oh, wow! Isn't that a POKéNAV?\n"
	.string "I have one, too! Please register me!$"

Route116_Text_KarenRegister2:
	.string "Oh, wow! Isn't that a POKéNAV?\n"
	.string "I have one, too! Please register me!$"

Route116_Text_KarenRematchIntro:
	.string "I studied a whole lot since I saw you.\n"
	.string "You must see my achievements!$"

Route116_Text_KarenRematchDefeat:
	.string "I'm in shock.\n"
	.string "I lost again?$"

Route116_Text_KarenPostRematch:
	.string "You've beaten ROXANNE?\n"
	.string "I can't beat you, then. Not yet.$"

Route116_Text_SarahIntro:
	.string "Just so you know, I've never once been\n"
	.string "bested by anyone at anything.$"

Route116_Text_SarahDefeat:
	.string "Oh, my goodness.\n"
	.string "This is a new experience for me.$"

Route116_Text_SarahPostBattle:
	.string "My life of luxury affords me all that\n"
	.string "I could possibly desire.\p"
	.string "However, when it comes to POKéMON,\n"
	.string "my wealth has no meaning.$"

Route116_Text_DawsonIntro:
	.string "When you lay your eyes on my POKéMON's\n"
	.string "gorgeous fur, their beauty will render\l"
	.string "you helpless!$"

Route116_Text_DawsonDefeat:
	.string "Oh, baby, say it isn't so!$"

Route116_Text_DawsonPostBattle:
	.string "Oh, no, no, no!\n"
	.string "You've mussed up my POKéMON's fur!\l"
	.string "You've ruined my hairdo, too!\l"
	.string "I'll have to call my stylist now!$"

Route116_Text_DevanIntro:
	.string "We'll rock you hard!$"

Route116_Text_DevanDefeat:
	.string "Aiyiyi!\n"
	.string "No contest at all!$"

Route116_Text_DevanPostBattle:
	.string "I should try different POKéMON\n"
	.string "types, that's what I ought to do.$"

Route116_Text_JohnsonIntro:
	.string "It's a dead end up here.\n"
	.string "I'm bored, so can we battle?$"

Route116_Text_JohnsonDefeat:
	.string "That was fun even though I lost.$"

Route116_Text_JohnsonPostBattle:
	.string "Want to stay here and keep\n"
	.string "me company?$"

Route117_Text_IsaacIntro:
	.string "Listen, could I get you to battle\n"
	.string "the POKéMON I'm raising?$"

Route117_Text_IsaacDefeat:
	.string "You've raised yours superbly…$"

Route117_Text_IsaacPostBattle:
	.string "POKéMON isn't all about power.\p"
	.string "Polishing a unique aspect of one's\n"
	.string "character is another way of enjoying\l"
	.string "POKéMON.$"

Route117_Text_IsaacRegister:
	.string "I'm going to redouble my training.\n"
	.string "Would you come look in on us?$"

Route117_Text_IsaacRematchIntro:
	.string "The POKéMON I've been raising are\n"
	.string "looking good, just like before.$"

Route117_Text_IsaacRematchDefeat:
	.string "You know how to raise them properly.\n"
	.string "You might have DAY CARE skills…$"

Route117_Text_IsaacPostRematch:
	.string "Your POKéMON are growing good!\n"
	.string "You should enter them in CONTESTS.$"

Route117_Text_LydiaIntro:
	.string "Please, allow me to evaluate if you\n"
	.string "have raised your POKéMON properly.$"

Route117_Text_LydiaDefeat:
	.string "Yes, they are growing properly.$"

Route117_Text_LydiaPostBattle:
	.string "Try raising POKéMON with more\n"
	.string "attention to their character traits.$"

Route117_Text_LydiaRegister:
	.string "I'm glad I met a superb TRAINER in you.\n"
	.string "I hope to see you again.$"

Route117_Text_LydiaRematchIntro:
	.string "Allow me to reevaluate if you have\n"
	.string "raised your POKéMON properly.$"

Route117_Text_LydiaRematchDefeat:
	.string "They are growing admirably.$"

Route117_Text_LydiaPostRematch:
	.string "POKéMON seem to like different kinds\n"
	.string "of {POKEBLOCK}S, depending on their nature.$"

Route117_Text_DylanIntro:
	.string "I'm in the middle of a triathlon, but,\n"
	.string "whatever, let's have a battle!$"

Route117_Text_DylanDefeat:
	.string "I ran out of energy!$"

Route117_Text_DylanPostBattle:
	.string "I may have blown it…\p"
	.string "I might have dropped to last during\n"
	.string "that battle…$"

Route117_Text_DylanRegister:
	.string "POKéMON have to be strong, too?\n"
	.string "I'd like you to train me!$"

Route117_Text_DylanRematchIntro:
	.string "I'm smack in the middle of a triathlon,\n"
	.string "but I'm comfortably ahead.\l"
	.string "Let's make this a quick battle!$"

Route117_Text_DylanRematchDefeat:
	.string "I ran out of energy again!$"

Route117_Text_DylanPostRematch:
	.string "I was tops in swimming and cycling,\n"
	.string "but I'm not quite that confident with\l"
	.string "POKéMON yet.$"

Route117_Text_MariaIntro:
	.string "I do my triathlon training with POKéMON,\n"
	.string "so I'm pretty confident about my speed.$"

Route117_Text_MariaDefeat:
	.string "I need to get more practices in,\n"
	.string "I guess.$"

Route117_Text_MariaPostBattle:
	.string "Training is meaningful only if you\n"
	.string "keep it up regularly.\p"
	.string "Okay! I'll resume my training!\n"
	.string "Tomorrow!$"

Route117_Text_MariaRegister:
	.string "You appear to be training properly…\n"
	.string "If you'd like, I'll battle you later!$"

Route117_Text_MariaRematchIntro:
	.string "Are you keeping up with your training?\n"
	.string "I sure am!\l"
	.string "Let me show you the evidence!$"

Route117_Text_MariaRematchDefeat:
	.string "I need to get more practices in,\n"
	.string "I guess.$"

Route117_Text_MariaPostRematch:
	.string "I'll resume training tomorrow.\n"
	.string "Let's battle again sometime!$"

Route117_Text_DerekIntro:
	.string "Once a BUG CATCHER!\n"
	.string "And now a BUG MANIAC!\p"
	.string "But my love for POKéMON remains\n"
	.string "unchanged!$"

Route117_Text_DerekDefeat:
	.string "My ineptitude also remains\n"
	.string "unchanged…$"

Route117_Text_DerekPostBattle:
	.string "All I did was follow my heart, and now\n"
	.string "they call me a BUG MANIAC…\p"
	.string "Still, I am an expert on BUG POKéMON,\n"
	.string "so it's only natural that they call me\l"
	.string "a BUG MANIAC.$"

Route117_Text_AnnaIntro:
	.string "ANNA: I'm with my pretty junior student\n"
	.string "partner. I have to do good!$"

Route117_Text_AnnaDefeat:
	.string "ANNA: I'm with my pretty junior student\n"
	.string "partner! Let me win!$"

Route117_Text_AnnaPostBattle:
	.string "ANNA: Your POKéMON have some good\n"
	.string "combinations.\p"
	.string "I'd say you're second only to us!$"

Route117_Text_AnnaAndMegRegister:
	.string "ANNA: We can't take this lying down!\n"
	.string "You will come back, won't you?$"

Route117_Text_AnnaNotEnoughMons:
	.string "ANNA: If you want to battle us,\n"
	.string "bring two POKéMON with you.$"

Route117_Text_MegIntro:
	.string "MEG: I'm going to tag up with my super\n"
	.string "senior student partner and beat you!$"

Route117_Text_MegDefeat:
	.string "MEG: Oh, no!\n"
	.string "I'm sorry, ANNA! I let you down…$"

Route117_Text_MegPostBattle:
	.string "MEG: I dragged ANNA down…\n"
	.string "If I didn't, she would have won!$"

Route117_Text_MegNotEnoughMons:
	.string "MEG: Do you only have one POKéMON?\n"
	.string "We can't battle with you, then.\p"
	.string "We want to have a 2-on-2 battle.$"

Route117_Text_AnnaRematchIntro:
	.string "ANNA: I can't keep losing in front of\n"
	.string "my junior partner, right?$"

Route117_Text_AnnaRematchDefeat:
	.string "ANNA: I couldn't get into the groove.$"

Route117_Text_AnnaPostRematch:
	.string "ANNA: Your POKéMON have some good\n"
	.string "combinations.\p"
	.string "I'd say you're second only to us!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "ANNA: If you want to battle us,\n"
	.string "bring two POKéMON with you.$"

Route117_Text_MegRematchIntro:
	.string "MEG: I'm going to tag up with my\n"
	.string "senior partner and win this time!$"

Route117_Text_MegRematchDefeat:
	.string "MEG: Too strong!$"

Route117_Text_MegPostRematch:
	.string "MEG: I battled together with my\n"
	.string "senior partner, but we lost…\p"
	.string "That's so discouraging…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "MEG: Do you only have one POKéMON?\n"
	.string "We can't battle with you, then.\p"
	.string "We want to have a 2-on-2 battle.$"

Route117_Text_MelinaIntro:
	.string "Isn't it nice? To battle while looking\n"
	.string "at pretty flowers?$"

Route117_Text_MelinaDefeat:
	.string "Oh, that's quite impressive!$"

Route117_Text_MelinaPostBattle:
	.string "It feels wonderful to go for a jog\n"
	.string "while looking at flowers.$"

Route117_Text_BrandiIntro:
	.string "Let me demonstrate the power\n"
	.string "hidden within a PSYCHIC POKéMON!$"

Route117_Text_BrandiDefeat:
	.string "Astonishing!$"

Route117_Text_BrandiPostBattle:
	.string "PSYCHIC POKéMON are complex.\n"
	.string "You should try catching some.$"

Route117_Text_AishaIntro:
	.string "Concentrate on getting the win.\n"
	.string "That's how I battle!$"

Route117_Text_AishaDefeat:
	.string "I don't waste any time being angry\n"
	.string "over a loss--I would rather train.$"

Route117_Text_AishaPostBattle:
	.string "I think that if you worry about losing,\n"
	.string "you're more likely to lose.$"

Route118_Text_RoseIntro:
	.string "The aroma of flowers has a magical\n"
	.string "power. It cleanses us body and soul.$"

Route118_Text_RoseDefeat:
	.string "Oh, dear me.\n"
	.string "I seem to have lost.$"

Route118_Text_RosePostBattle:
	.string "Flowers, POKéMON…\n"
	.string "I love whatever smells nice.\p"
	.string "Stinky things…\n"
	.string "I'll pass.$"

Route118_Text_RoseRegister:
	.string "Sniff… That odor--it's a POKéNAV!\n"
	.string "We must register each other!$"

Route118_Text_RoseRematchIntro:
	.string "Were you drawn here by the sweet\n"
	.string "aroma?$"

Route118_Text_RoseRematchDefeat:
	.string "The power of aroma…\n"
	.string "It didn't seem to do much.$"

Route118_Text_RosePostRematch:
	.string "If you use a sweet aroma properly,\n"
	.string "POKéMON will be attracted by it.$"

Route118_Text_PerryIntro:
	.string "BIRD POKéMON that FLY elegantly in\n"
	.string "the sky… They're the best!$"

Route118_Text_PerryDefeat:
	.string "Urgh…\n"
	.string "I crashed…$"

Route118_Text_PerryPostBattle:
	.string "You've got great POKéMON.\n"
	.string "I'll have to train mine better.$"

Route118_Text_ChesterIntro:
	.string "Take flight!\n"
	.string "My BIRD POKéMON!$"

Route118_Text_ChesterDefeat:
	.string "They did take flight…$"

Route118_Text_ChesterPostBattle:
	.string "If they'd get stronger, they'd be able\n"
	.string "to fly more freely…$"

Route118_Text_BarnyIntro:
	.string "I'm a FISHERMAN, but also a TRAINER.\n"
	.string "I'm raising the POKéMON I caught.$"

Route118_Text_BarnyDefeat:
	.string "I thought I was doing okay in my\n"
	.string "training…$"

Route118_Text_BarnyPostBattle:
	.string "I couldn't win by training POKéMON\n"
	.string "while I fished…\p"
	.string "Was I doing things in half measures?$"

Route118_Text_WadeIntro:
	.string "For FISHERMEN, equipment is the key.\p"
	.string "But for TRAINERS, the key ingredients\n"
	.string "are POKéMON and heart, of course!$"

Route118_Text_WadeDefeat:
	.string "I was beaten in heart?$"

Route118_Text_WadePostBattle:
	.string "Come to think of it, fishing is a battle\n"
	.string "between a FISHERMAN and a POKéMON.$"

Route118_Text_DaltonIntro:
	.string "Let my melody rock your soul!$"

Route118_Text_DaltonDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostBattle:
	.string "An electric guitar doesn't always\n"
	.string "have to be noisy…\p"
	.string "It can be strummed to squeeze out\n"
	.string "this heart-stirring melody…$"

Route118_Text_DaltonRegister:
	.string "When I compose better melodies,\n"
	.string "you have to come listen, okay?$"

Route118_Text_DaltonRematchIntro:
	.string "A melody from my POKéMON and me…\n"
	.string "Let us deliver it to your soul.$"

Route118_Text_DaltonRematchDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostRematch:
	.string "When I play, my emotions should reach\n"
	.string "you through my electric guitar…$"

Route118_Text_DeandreIntro:
	.string "Go, go, go!\n"
	.string "POKéMON 1, 2, and 3!$"

Route118_Text_DeandreDefeat:
	.string "Come in, POKéMON! Are you okay?\n"
	.string "POKéMON 1, 2, and 3?!$"

Route118_Text_DeandrePostBattle:
	.string "Isn't it cool that I have a POKéMON\n"
	.string "battle team?\p"
	.string "You can copy me--I don't mind!$"

Route119_Text_BrentIntro:
	.string "We're the MIMIC CIRCLE!\n"
	.string "We MIMIC what you do!$"

Route119_Text_BrentDefeat:
	.string "Whoopsie!\n"
	.string "I lost!$"

Route119_Text_BrentPostBattle:
	.string "What's so good about mimicry?\p"
	.string "Fufufu…\n"
	.string "You'll never understand…$"

Route119_Text_DonaldIntro:
	.string "So, we finally meet!\n"
	.string "My BUG POKéMON will keep you company!$"

Route119_Text_DonaldDefeat:
	.string "I wish we'd never met…$"

Route119_Text_DonaldPostBattle:
	.string "I want to MIMIC you some more.\n"
	.string "Can you hurry up and move?$"

Route119_Text_TaylorIntro:
	.string "If you step forward, we step forward.\p"
	.string "If you turn right, we turn, too…$"

Route119_Text_TaylorDefeat:
	.string "But if you win, I lose…$"

Route119_Text_TaylorPostBattle:
	.string "I can't MIMIC you winning the match.\n"
	.string "That's just impossible…\l"
	.string "It's burning me up…$"

Route119_Text_DougIntro:
	.string "Yep, you've finally caught me!\n"
	.string "Or were you trying to avoid me?$"

Route119_Text_DougDefeat:
	.string "Whoop, that was a great match!$"

Route119_Text_DougPostBattle:
	.string "We're the MIMIC CIRCLE!\n"
	.string "I hope you enjoyed our performance.$"

Route119_Text_GregIntro:
	.string "You don't know who I am, do you?\p"
	.string "But, I also don't know you.\n"
	.string "So, we'll battle!$"

Route119_Text_GregDefeat:
	.string "You're pretty strong!$"

Route119_Text_GregPostBattle:
	.string "Until you go away somewhere, we'll\n"
	.string "keep on mimicking your every move.$"

Route119_Text_KentIntro:
	.string "The MIMIC CIRCLE was formed by people\n"
	.string "who like to MIMIC.\p"
	.string "A battle starts the instant we meet!$"

Route119_Text_KentDefeat:
	.string "{JPN}まいった!$"

Route119_Text_KentPostBattle:
	.string "Won't you join our MIMIC CIRCLE?$"

Route119_Text_JacksonIntro:
	.string "Who has the knowledge and\n"
	.string "the technique for survival?\p"
	.string "POKéMON RANGERS, that's who!$"

Route119_Text_JacksonDefeat:
	.string "I didn't have enough POKéMON\n"
	.string "know-how…$"

Route119_Text_JacksonPostBattle:
	.string "To break away from civilization and\n"
	.string "awaken the wild spirit within!\p"
	.string "That's our vision.$"

Route119_Text_JacksonRegister:
	.string "I hope you'll give me a rematch without\n"
	.string "mocking my lack of knowledge.$"

Route119_Text_JacksonRematchIntro:
	.string "I'm going to regain my wild spirit by\n"
	.string "being together with POKéMON.$"

Route119_Text_JacksonRematchDefeat:
	.string "You've remained strong!$"

Route119_Text_JacksonPostRematch:
	.string "Believe in your POKéMON.\n"
	.string "Believe in yourself.\p"
	.string "The road will reveal itself to you.$"

Route119_Text_CatherineIntro:
	.string "Oh? Look at you.\p"
	.string "For someone on an adventure,\n"
	.string "you're traveling awfully light.$"

Route119_Text_CatherineDefeat:
	.string "Accidents happen when you're not\n"
	.string "prepared!$"

Route119_Text_CatherinePostBattle:
	.string "You're traveling light but you have\n"
	.string "everything you need.\p"
	.string "You're on top of things mentally and\n"
	.string "physically, too.$"

Route119_Text_CatherineRegister:
	.string "Do you have a POKéNAV?\n"
	.string "It's a must-have tool for any TRAINER.\p"
	.string "Oh, you do have one!\n"
	.string "Let's register each other, then!$"

Route119_Text_CatherineRematchIntro:
	.string "How's your journey with POKéMON\n"
	.string "going?$"

Route119_Text_CatherineRematchDefeat:
	.string "I'm still missing something…$"

Route119_Text_CatherinePostRematch:
	.string "In the same way that you, as a TRAINER,\n"
	.string "rely on your POKéMON, your POKéMON\l"
	.string "rely on you.$"

Route119_Text_HughIntro:
	.string "The vast sky holds untold promise!\p"
	.string "Nothing can compare to the sheer\n"
	.string "exhilaration of flight!$"

Route119_Text_HughDefeat:
	.string "Down and out!$"

Route119_Text_HughPostBattle:
	.string "My BIRD POKéMON made my dreams of\n"
	.string "flying come true!$"

Route119_Text_PhilIntro:
	.string "I'll show you the true potential of me\n"
	.string "and my BIRD POKéMON!$"

Route119_Text_PhilDefeat:
	.string "We lacked potential…$"

Route119_Text_PhilPostBattle:
	.string "Ever since I was a little kid, I always\n"
	.string "admired BIRD POKéMON…$"

Route119_Text_YasuIntro:
	.string "To lurk in shadows, and live in\n"
	.string "darkness… That is my destiny.\p"
	.string "I emerge to challenge you!$"

Route119_Text_YasuDefeat:
	.string "I admit defeat!$"

Route119_Text_YasuPostBattle:
	.string "Those defeated in battle withdraw\n"
	.string "quietly back into the shadows.\l"
	.string "That, too, is destiny…$"

Route119_Text_TakashiIntro:
	.string "If you're not on your guard,\n"
	.string "you're in for some pain!$"

Route119_Text_TakashiDefeat:
	.string "You're surprisingly good!$"

Route119_Text_TakashiPostBattle:
	.string "My surprise attack ended in\n"
	.string "failure…$"

Route119_Text_HideoIntro:
	.string "To hide a tree, use a forest!$"

Route119_Text_HideoDefeat:
	.string "I bow to your superiority.$"

Route119_Text_HideoPostBattle:
	.string "To hide a tree, use a forest!\n"
	.string "To hide a POKéMON, use a POKéMON!\p"
	.string "There is no deep, hidden meaning\n"
	.string "to that.$"

Route119_Text_ChrisIntro:
	.string "You spoke to me…\n"
	.string "So you want to challenge me!\p"
	.string "Sure! I'll try out the POKéMON I caught\n"
	.string "while SURFING!$"

Route119_Text_ChrisDefeat:
	.string "I don't have a clue about what it\n"
	.string "takes to win.$"

Route119_Text_ChrisPostBattle:
	.string "Go for a SURF on my POKéMON…\p"
	.string "Then fish off its back…\p"
	.string "It's an indescribably luxuriant moment!$"

Route119_Text_FabianIntro:
	.string "Hit me with a power chord!\n"
	.string "Victory is mine!\l"
	.string "It's our time to shine, whoa, yeah!$"

Route119_Text_FabianDefeat:
	.string "You showed me who's the boss!\n"
	.string "We'll have to take the loss, oh, no!$"

Route119_Text_FabianPostBattle:
	.string "Hit me with another power chord!\n"
	.string "Leave me alone!\l"
	.string "Your win you have to atone!$"

Route119_Text_DaytonIntro:
	.string "Hohoho!\n"
	.string "I like kid TRAINERS!\l"
	.string "Let's have a good one!$"

Route119_Text_DaytonDefeat:
	.string "You're pretty amazing!\n"
	.string "Hohoho!$"

Route119_Text_DaytonPostBattle:
	.string "Hohoho!\n"
	.string "I'll try emulating the pep of kid\l"
	.string "TRAINERS like you!$"

Route119_Text_RachelIntro:
	.string "Wherever and whenever I may be,\n"
	.string "I always have my parasol in hand.$"

Route119_Text_RachelDefeat:
	.string "Oh, but…\n"
	.string "That's not fair.$"

Route119_Text_RachelPostBattle:
	.string "You're asking if my parasol is heavy?\n"
	.string "Your BAG is filled with more junk than\l"
	.string "I ever carry around.$"

Route120_Text_ColinIntro:
	.string "Do you have any moves that can strike\n"
	.string "a flying POKéMON?$"

Route120_Text_ColinDefeat:
	.string "You soared above me!$"

Route120_Text_ColinPostBattle:
	.string "The move FLY is convenient,\n"
	.string "don't you think?\p"
	.string "While the POKéMON is flying,\n"
	.string "almost no moves can strike it.$"

Route120_Text_RobertIntro:
	.string "My POKéMON is strong!\n"
	.string "How about yours?$"

Route120_Text_RobertDefeat:
	.string "Your POKéMON were stronger…$"

Route120_Text_RobertPostBattle:
	.string "A POKéMON that grows steadily is one\n"
	.string "you can count on.$"

Route120_Text_RobertRegister:
	.string "You can be counted on to get better.\n"
	.string "I'd like to register you in my POKéNAV!$"

Route120_Text_RobertRematchIntro:
	.string "A POKéMON that grows steadily is one\n"
	.string "you can count on.$"

Route120_Text_RobertRematchDefeat:
	.string "Your POKéMON are seriously strong.$"

Route120_Text_RobertPostRematch:
	.string "My POKéMON are growing stronger.\n"
	.string "I have to grow stronger, too.$"

Route120_Text_LorenzoIntro:
	.string "I'll check your POKéMON and see if\n"
	.string "they're fit for the outdoors.$"

Route120_Text_LorenzoDefeat:
	.string "With POKéMON that strong, you're in\n"
	.string "no danger of needing rescue!$"

Route120_Text_LorenzoPostBattle:
	.string "To travel wherever your heart desires\n"
	.string "with POKéMON…\l"
	.string "That's the joy of being a TRAINER.$"

Route120_Text_JennaIntro:
	.string "How's your physical fitness?\n"
	.string "If you're not fit, you could have a\l"
	.string "rough time in critical situations.$"

Route120_Text_JennaDefeat:
	.string "I'm totally fit, but…$"

Route120_Text_JennaPostBattle:
	.string "Fitness training is in my routine.\n"
	.string "I always run with my POKéMON.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Want to battle?$"

Route120_Text_JeffreyDefeat:
	.string "Lost it…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "I'll try harder…$"

Route120_Text_JeffreyRegister:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Do you have a POKéNAV…?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Want to battle again?$"

Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … …\n"
	.string "I lost again…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "I'll try harder…\l"
	.string "For my precious BUG POKéMON…$"

Route120_Text_JenniferIntro:
	.string "POKéMON have many special abilities.\n"
	.string "If you want to become a first-class\l"
	.string "TRAINER, learn about them.$"

Route120_Text_JenniferDefeat:
	.string "You're obviously thinking.$"

Route120_Text_JenniferPostBattle:
	.string "The special abilities of POKéMON\n"
	.string "will make battle styles change.$"

Route120_Text_ChipIntro:
	.string "Who might you be?\p"
	.string "Are you perhaps searching for ancient\n"
	.string "ruins that are rumored to possibly\l"
	.string "exist according to legend?$"

Route120_Text_ChipDefeat:
	.string "What a disgraceful setback…$"

Route120_Text_ChipPostBattle:
	.string "That giant rock… I would like to\n"
	.string "believe it may indeed contain ancient\l"
	.string "ruins. But I see no entrance.$"

Route120_Text_ClarissaIntro:
	.string "Why am I carrying this parasol?\p"
	.string "I'll tell you if you can win against me.$"

Route120_Text_ClarissaDefeat:
	.string "A parasol can't ward off POKéMON\n"
	.string "attacks…$"

Route120_Text_ClarissaPostBattle:
	.string "I don't think strong sunlight is good\n"
	.string "for my POKéMON.\l"
	.string "So I shield them with my parasol.$"

Route120_Text_AngelicaIntro:
	.string "Me, POKéMON, and my parasol…\p"
	.string "If any one of them is missing,\n"
	.string "the picture of beauty will be ruined.$"

Route120_Text_AngelicaDefeat:
	.string "You've completely ruined my beauty…$"

Route120_Text_AngelicaPostBattle:
	.string "A parasol wouldn't suit you at all.\p"
	.string "Why, something like this would only\n"
	.string "get in your way.$"

Route120_Text_KeigoIntro:
	.string "I will adopt the movements of POKéMON\n"
	.string "and create new ninja techniques.$"

Route120_Text_KeigoDefeat:
	.string "The creation of new ninja techniques\n"
	.string "is but a distant dream…$"

Route120_Text_KeigoPostBattle:
	.string "Perhaps I ought to apprentice under\n"
	.string "a ninja sensei.$"

Route120_Text_RileyIntro:
	.string "We ninja conceal ourselves under our\n"
	.string "camouflage cloaks.\l"
	.string "I bet you didn't know where I was!$"

Route120_Text_RileyDefeat:
	.string "I lost!\n"
	.string "I should camouflage my shame!$"

Route120_Text_RileyPostBattle:
	.string "Our camouflage cloaks are all\n"
	.string "handmade.$"

Route120_Text_CallieIntro:
	.string "If you don't pay attention,\n"
	.string "you could get hurt!$"

Route120_Text_CallieDefeat:
	.string "Ouch!\n"
	.string "I was the one to get hurt.$"

Route120_Text_CalliePostBattle:
	.string "I wonder… Should I evolve my POKéMON?\n"
	.string "They're cute the way they are, though.$"

Route120_Text_LeonelIntro:
	.string "Your party POKéMON…\n"
	.string "Do you have different types?$"

Route120_Text_LeonelDefeat:
	.string "I've seen your policy in action!$"

Route120_Text_LeonelPostBattle:
	.string "I think it's awesome you're so strong\n"
	.string "battling with your favorite POKéMON.$"

Route121_Text_VanessaIntro:
	.string "Will you play with my delightfully\n"
	.string "pretty POKéMON?$"

Route121_Text_VanessaDefeat:
	.string "This isn't what I meant!$"

Route121_Text_VanessaPostBattle:
	.string "I'm going to a CONTEST in LILYCOVE.\p"
	.string "My POKéMON should have no problem\n"
	.string "sweeping the MASTER CLASS.$"

Route121_Text_WalterIntro:
	.string "With my POKéMON, I have traveled\n"
	.string "to the world's four corners.\p"
	.string "You might say I have some confidence\n"
	.string "in my abilities.$"

Route121_Text_WalterDefeat:
	.string "Ah, well played.$"

Route121_Text_WalterPostBattle:
	.string "I would like to circle the globe once\n"
	.string "again with my POKéMON.$"

Route121_Text_WalterRegister:
	.string "Your POKéMON prowess is remarkable.\n"
	.string "Allow me to register you as a memento.$"

Route121_Text_WalterRematchIntro:
	.string "With my POKéMON, I have traveled\n"
	.string "to the world's four corners.\p"
	.string "You might say I have some confidence\n"
	.string "in my abilities.$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, well played.$"

Route121_Text_WalterPostRematch:
	.string "Your POKéMON and you…\p"
	.string "Your prowess together will be\n"
	.string "considered strong, even overseas.$"

Route121_Text_TammyIntro:
	.string "There are powers beyond our\n"
	.string "understanding in the world…$"

Route121_Text_TammyDefeat:
	.string "I have lost…$"

Route121_Text_TammyPostBattle:
	.string "MT. PYRE…\n"
	.string "There is a mysterious power\l"
	.string "at work there…$"

Route121_Text_KateIntro:
	.string "KATE: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_KateDefeat:
	.string "KATE: I blew it in front of my junior\n"
	.string "student partner…$"

Route121_Text_KatePostBattle:
	.string "KATE: When someone's relying on me,\n"
	.string "I get this urge to look cool in front\l"
	.string "of them…$"

Route121_Text_KateNotEnoughMons:
	.string "KATE: If you've only got one POKéMON,\n"
	.string "we can't battle with you.\p"
	.string "That would be bullying.$"

Route121_Text_JoyIntro:
	.string "JOY: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_JoyDefeat:
	.string "JOY: Please forgive me, KATE!$"

Route121_Text_JoyPostBattle:
	.string "JOY: Ehehe, I'll have to train with KATE,\n"
	.string "my senior student partner, again.$"

Route121_Text_JoyNotEnoughMons:
	.string "JOY: You need at least two POKéMON\n"
	.string "if you're going to challenge us!$"

Route121_Text_JessicaIntro:
	.string "Stop! Have a good look at my precious\n"
	.string "POKéMON!$"

Route121_Text_JessicaDefeat:
	.string "Oh, how dare you!\n"
	.string "Don't take it so seriously!$"

Route121_Text_JessicaPostBattle:
	.string "Maybe I'll go catch more POKéMON at\n"
	.string "the SAFARI.$"

Route121_Text_JessicaRegister:
	.string "I took it easy on you this time!\n"
	.string "It won't be that way the next time!$"

Route121_Text_JessicaRematchIntro:
	.string "My precious POKéMON grew!\n"
	.string "Have a good look!$"

Route121_Text_JessicaRematchDefeat:
	.string "Oh, how dare you!\n"
	.string "You still won't take it easy!$"

Route121_Text_JessicaPostRematch:
	.string "Maybe I'll go catch more POKéMON at\n"
	.string "the SAFARI.$"

Route121_Text_CristinIntro:
	.string "I have this routine.\n"
	.string "Defeat five TRAINERS a day.\l"
	.string "Guess what? You're number five!$"

Route121_Text_CristinDefeat:
	.string "No!\n"
	.string "You're horrid!$"

Route121_Text_CristinPostBattle:
	.string "I didn't expect to lose this easily…\n"
	.string "I'll win next time!$"

Route121_Text_CristinRegister:
	.string "That was total humiliation!\n"
	.string "I won't forget you…\l"
	.string "Hand over your POKéNAV!$"

Route121_Text_CristinRematchIntro:
	.string "I have this new routine.\n"
	.string "Defeat ten TRAINERS a day.\l"
	.string "Guess what? You're number ten!$"

Route121_Text_CristinRematchDefeat:
	.string "Wait! That's nasty!\n"
	.string "I demand a rematch!$"

Route121_Text_CristinPostRematch:
	.string "An opponent I just can't beat…\n"
	.string "Snivel…\l"
	.string "I can't believe this is happening…$"

Route121_Text_CaleIntro:
	.string "Can't you see that I have all this\n"
	.string "stuff with me?\p"
	.string "Despite that, you still insist that\n"
	.string "we battle?$"

Route121_Text_CaleDefeat:
	.string "Of course I lost!\n"
	.string "I'm holding stuff in both hands!$"

Route121_Text_CalePostBattle:
	.string "I bought too much stuff at\n"
	.string "the LILYCOVE DEPT. STORE.\p"
	.string "It's up the road from here.\n"
	.string "I wish I had a BAG like yours.$"

Route121_Text_MylesIntro:
	.string "There's nothing I love more than\n"
	.string "checking out other people's POKéMON!$"

Route121_Text_MylesDefeat:
	.string "Super awesome!$"

Route121_Text_MylesPostBattle:
	.string "They're great, your POKéMON!\n"
	.string "How do you raise them?$"

Route121_Text_PatIntro:
	.string "I want everybody to see the POKéMON\n"
	.string "I've raised!$"

Route121_Text_PatDefeat:
	.string "Wow!\n"
	.string "Spectacular!$"

Route121_Text_PatPostBattle:
	.string "I raise every POKéMON with the same\n"
	.string "love and care--I don't pick favorites.$"

Route121_Text_MarcelIntro:
	.string "My POKéMON have never tasted defeat!\n"
	.string "On their next win, I'm entering them\l"
	.string "in CONTESTS.$"

Route121_Text_MarcelDefeat:
	.string "Oh, now what happened here?$"

Route121_Text_MarcelPostBattle:
	.string "I may have to train my gang some more\n"
	.string "before entering any CONTEST.$"

Route123_Text_WendyIntro:
	.string "Want to determine how strong you are?\n"
	.string "I'll be the test!$"

Route123_Text_WendyDefeat:
	.string "You passed with flying colors!$"

Route123_Text_WendyPostBattle:
	.string "To best even me…\n"
	.string "Your strength is marvelous!$"

Route123_Text_BraxtonIntro:
	.string "You seem to have a big collection\n"
	.string "of GYM BADGES.\p"
	.string "Let me see if you're actually worthy of\n"
	.string "those BADGES!$"

Route123_Text_BraxtonDefeat:
	.string "Oh, you're worthy, all right!$"

Route123_Text_BraxtonPostBattle:
	.string "You did your BADGES proud in that\n"
	.string "match!$"

Route123_Text_VioletIntro:
	.string "They say that good times are filled\n"
	.string "with good aromas.$"

Route123_Text_VioletDefeat:
	.string "Oh…\n"
	.string "I smell the bitter scent of misery…$"

Route123_Text_VioletPostBattle:
	.string "The BERRY MASTER's garden is filled\n"
	.string "with uplifting fragrances.$"

Route123_Text_CameronIntro:
	.string "Being a psychic is about willpower.\p"
	.string "I've willed myself not to lose to\n"
	.string "anyone. That makes me strong!$"

Route123_Text_CameronDefeat:
	.string "I feel sad…$"

Route123_Text_CameronPostBattle:
	.string "Being a psychic is about willpower.\n"
	.string "I thought I wouldn't lose to you…$"

Route123_Text_CameronRegister:
	.string "I sense it!\n"
	.string "You and I shall battle again!\l"
	.string "I can't tell if I'll win, though…\p"
	.string "Let's see your POKéNAV.$"

Route123_Text_CameronRematchIntro:
	.string "I've convinced myself that I won't\n"
	.string "lose anymore. That makes me strong!$"

Route123_Text_CameronRematchDefeat:
	.string "I feel sad…$"

Route123_Text_CameronPostRematch:
	.string "I should train at MT. PYRE…\n"
	.string "I'll never beat you this way…$"

Route123_Text_JackiIntro:
	.string "Don't be too happy if your POKéMON\n"
	.string "develop psychic powers.\p"
	.string "You need to refine those powers to\n"
	.string "make them really useful.$"

Route123_Text_JackiDefeat:
	.string "Overwhelmed!$"

Route123_Text_JackiPostBattle:
	.string "We all have psychic powers.\n"
	.string "We've just forgotten how to use them.$"

Route123_Text_JackiRegister:
	.string "I would like to face you again.\n"
	.string "Is that okay with you?$"

Route123_Text_JackiRematchIntro:
	.string "Have you awoken the psychic powers\n"
	.string "within you?$"

Route123_Text_JackiRematchDefeat:
	.string "Astounding!$"

Route123_Text_JackiPostRematch:
	.string "Your power with POKéMON…\n"
	.string "That could be a psychic power, too.$"

Route123_Text_MiuIntro:
	.string "MIU: Hello, TRAINER. I hope your\n"
	.string "POKéMON won't cry when they lose.$"

Route123_Text_MiuDefeat:
	.string "MIU: Uh-oh, we lost.$"

Route123_Text_MiuPostBattle:
	.string "MIU: TRAINER, your POKéMON are\n"
	.string "strong because you are friends.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI: Okay!\n"
	.string "We're beating the TRAINER's POKéMON!$"

Route123_Text_YukiDefeat:
	.string "YUKI: Uh-oh, we lost.$"

Route123_Text_YukiPostBattle:
	.string "YUKI: Why are you so strong?\n"
	.string "We've never lost before.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_KindraIntro:
	.string "MT. PYRE…\n"
	.string "Where the spirits of POKéMON sleep…\l"
	.string "Will your POKéMON sleep?$"

Route123_Text_KindraDefeat:
	.string "Overflowing with vitality…$"

Route123_Text_KindraPostBattle:
	.string "MT. PYRE…\n"
	.string "Where the spirits of POKéMON sleep…\p"
	.string "It must overflow with a power that\n"
	.string "soothes spirits…$"

Route123_Text_FernandoIntro:
	.string "I'll turn your lights out while\n"
	.string "I rip through this tune!$"

Route123_Text_FernandoDefeat:
	.string "Hey, hold it!\n"
	.string "I was still playing the intro!$"

Route123_Text_FernandoPostBattle:
	.string "You're rock steady.\n"
	.string "I'd like to write a tune about you.$"

Route123_Text_FernandoRegister:
	.string "The next time, lend your ears to\n"
	.string "the full tune, will you?$"

Route123_Text_FernandoRematchIntro:
	.string "Today's the day I'm going to do it!\n"
	.string "I'll turn out your lights before\l"
	.string "I finish singing my song!$"

Route123_Text_FernandoRematchDefeat:
	.string "Hey, hold it!\n"
	.string "I haven't even hit the chorus!$"

Route123_Text_FernandoPostRematch:
	.string "I thought you'd be so enthralled\n"
	.string "by my tune, you'd lose.$"

Route123_Text_DavisIntro:
	.string "This is my awesome BUG POKéMON!\n"
	.string "My big brother got it for me.$"

Route123_Text_DavisDefeat:
	.string "Waaaah!\n"
	.string "You meanie!$"

Route123_Text_DavisPostBattle:
	.string "Don't tell my brother I lost.\n"
	.string "You have to keep it a secret!$"

Route123_Text_JazmynIntro:
	.string "My confidence will get a boost by\n"
	.string "beating someone obviously strong!$"

Route123_Text_JazmynDefeat:
	.string "There goes my confidence…$"

Route123_Text_JazmynPostBattle:
	.string "They say that you can't judge a person\n"
	.string "by their appearance.\p"
	.string "But often, their looks don't lie…$"

Route123_Text_FrederickIntro:
	.string "Hello, child!\n"
	.string "Can you spare some time?$"

Route123_Text_FrederickDefeat:
	.string "Ah, a mighty capable child!\n"
	.string "Let me contribute to your allowance.$"

Route123_Text_FrederickPostBattle:
	.string "Contribute to your allowance?\n"
	.string "Wasn't the prize money enough?$"

Route123_Text_AlbertoIntro:
	.string "I have to tell you, BIRD POKéMON\n"
	.string "are my obsession!\p"
	.string "Birds are cool!\n"
	.string "They're the best!$"

Route123_Text_AlbertoDefeat:
	.string "Even in defeat, BIRD POKéMON are cool!$"

Route123_Text_AlbertoPostBattle:
	.string "I gather BIRD POKéMON feathers that\n"
	.string "scatter during battles.\p"
	.string "I'm going to make a hat with\n"
	.string "BIRD POKéMON feathers.$"

Route123_Text_EdIntro:
	.string "When there are no TRAINERS around,\n"
	.string "I let my POKéMON battle each other.\l"
	.string "I watch them.$"

Route123_Text_EdDefeat:
	.string "I kind of like your POKéMON.$"

Route123_Text_EdPostBattle:
	.string "Hehe, I'm swiping your battling ideas!\n"
	.string "I think they'll make me better.$"

Route123_Text_JonasIntro:
	.string "I lay in ambush, and a TRAINER has\n"
	.string "landed in my trap!$"

Route123_Text_JonasDefeat:
	.string "If you don't lose, how am I supposed\n"
	.string "to have fun playing ninja?$"

Route123_Text_JonasPostBattle:
	.string "I'm going to ambush a weaker-looking\n"
	.string "TRAINER next time.$"

Route123_Text_KayleyIntro:
	.string "I just bought this parasol.\n"
	.string "My cuteness should be up by a third!$"

Route123_Text_KayleyDefeat:
	.string "You're better than me by about\n"
	.string "five times!$"

Route123_Text_KayleyPostBattle:
	.string "Using accessories effectively is\n"
	.string "the secret behind fashion appeal.$"

Route124_Text_SpencerIntro:
	.string "Hey, are you lost at sea?\p"
	.string "If you can beat my POKéMON,\n"
	.string "I can serve as your pilot.$"

Route124_Text_SpencerDefeat:
	.string "I lost my bearings in battle!$"

Route124_Text_SpencerPostBattle:
	.string "Many people lose their bearings at sea.\p"
	.string "If you're that sort, you should refer\n"
	.string "to the POKéNAV's MAP.$"

Route124_Text_RolandIntro:
	.string "Hm! You're riding a POKéMON instead\n"
	.string "of swimming yourself…\p"
	.string "I am envious!$"

Route124_Text_RolandDefeat:
	.string "Oh!\n"
	.string "I can't…$"

Route124_Text_RolandPostBattle:
	.string "I'm getting chilled…\n"
	.string "I've been in the water too long…\p"
	.string "I wish I could ride a POKéMON like you…$"

Route124_Text_JennyIntro:
	.string "If you just float in the sea like\n"
	.string "this, POKéMON come around to play.$"

Route124_Text_JennyDefeat:
	.string "Oh, darn.\n"
	.string "I've gone and lost.$"

Route124_Text_JennyPostBattle:
	.string "While swimming, I noticed that some\n"
	.string "POKéMON attack, and some just watch.\p"
	.string "I guess POKéMON have personalities\n"
	.string "of their own.$"

Route124_Text_JennyRegister:
	.string "It's only on a whim, but maybe I'll get\n"
	.string "you to register me in your POKéNAV.$"

Route124_Text_JennyRematchIntro:
	.string "If you just float in the sea like this,\n"
	.string "TRAINERS challenge you!$"

Route124_Text_JennyRematchDefeat:
	.string "That's strange…\n"
	.string "I lost again…$"

Route124_Text_JennyPostRematch:
	.string "This has nothing to do with anything,\n"
	.string "but maybe I'll visit the TRICK HOUSE.$"

Route124_Text_GraceIntro:
	.string "I'm growing bored of swimming…\n"
	.string "How about a battle?$"

Route124_Text_GraceDefeat:
	.string "I had no idea that you were\n"
	.string "this strong!$"

Route124_Text_GracePostBattle:
	.string "All the effort you put in must have\n"
	.string "made you this strong.$"

Route124_Text_ChadIntro:
	.string "Fufufufu… I dive deep underwater\n"
	.string "to go deep under cover.\l"
	.string "Plumbing the depths is where I excel!$"

Route124_Text_ChadDefeat:
	.string "Glub, glub, glub…\n"
	.string "I'm sinking…$"

Route124_Text_ChadPostBattle:
	.string "I have it on good authority that\n"
	.string "there's a DIVE spot around here.\p"
	.string "It gives me the urge to go deep\n"
	.string "again…$"

Route124_Text_LilaIntro:
	.string "LILA: Sigh…\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Let's battle so I won't have to dwell\n"
	.string "on that!$"

Route124_Text_LilaDefeat:
	.string "LILA: ROY! It's your fault we lost!\n"
	.string "You're in for it later!$"

Route124_Text_LilaPostBattle:
	.string "LILA: Sigh…\p"
	.string "If only it wasn't my little brother\n"
	.string "next to me, but a nice boyfriend…$"

Route124_Text_LilaNotEnoughMons:
	.string "LILA: You're planning to battle us?\n"
	.string "Not unless you have two POKéMON.$"

Route124_Text_RoyIntro:
	.string "ROY: My big sister is tough at POKéMON!\p"
	.string "Don't cry when you lose!$"

Route124_Text_RoyDefeat:
	.string "ROY: Uh-oh…\n"
	.string "My big sister will chew me out…$"

Route124_Text_RoyPostBattle:
	.string "ROY: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "That's why she doesn't have a\n"
	.string "boyfriend.$"

Route124_Text_LilaRoyRegister:
	.string "ROY: Will you battle with us again?\n"
	.string "But take it easy next time, okay?$"

Route124_Text_RoyNotEnoughMons:
	.string "ROY: Did you want to battle us?\n"
	.string "Bring two POKéMON, then.$"

Route124_Text_LilaRematchIntro:
	.string "LILA: Sigh…\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Oh, hi, it's been a while. Let's battle\n"
	.string "so I won't have to dwell on things!$"

Route124_Text_LilaRematchDefeat:
	.string "LILA: ROY!\n"
	.string "It's your fault we lost again!\p"
	.string "We're having a training session later!$"

Route124_Text_LilaPostRematch:
	.string "LILA: Sigh…\p"
	.string "If I had a nice boyfriend, we'd beat\n"
	.string "anyone with lovely combinations…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "LILA: You're planning to battle us?\n"
	.string "Not unless you have two POKéMON.$"

Route124_Text_RoyRematchIntro:
	.string "ROY: If we lose, I'll catch heck.\n"
	.string "I'm going to go totally all out!$"

Route124_Text_RoyRematchDefeat:
	.string "ROY: Uh-oh…\n"
	.string "My big sister will chew me out again.$"

Route124_Text_RoyPostRematch:
	.string "ROY: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "She's going to make me train really\n"
	.string "hard with POKéMON later…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "ROY: Did you want to battle us?\n"
	.string "Bring two POKéMON, then.$"

Route124_Text_DeclanIntro:
	.string "Here I am swimming by my lonesome\n"
	.string "on this wide, beautiful sea.\p"
	.string "There's no other word for it.\n"
	.string "This is pathetic!$"

Route124_Text_DeclanDefeat:
	.string "I'm feeling blue.\n"
	.string "Blue as the sky…$"

Route124_Text_DeclanPostBattle:
	.string "I should chat up lady SWIMMERS\n"
	.string "and invite them on a long swim.$"

Route124_Text_IsabellaIntro:
	.string "I'm not going to lose to some\n"
	.string "surfer TRAINER.$"

Route124_Text_IsabellaDefeat:
	.string "I've only got sweat in my eyes!\n"
	.string "I am not crying!$"

Route124_Text_IsabellaPostBattle:
	.string "You can find pretty colored shards\n"
	.string "of things around here.$"

Route125_Text_NolenIntro:
	.string "I heard you approaching, so I hung\n"
	.string "around for you!$"

Route125_Text_NolenDefeat:
	.string "I surrender!$"

Route125_Text_NolenPostBattle:
	.string "Sound travels faster in water than\n"
	.string "it does through air.$"

Route125_Text_StanIntro:
	.string "Hey, there!\n"
	.string "Check out my sweet POKéMON!$"

Route125_Text_StanDefeat:
	.string "I floundered…$"

Route125_Text_StanPostBattle:
	.string "I was blown away by HORSEA's charm,\n"
	.string "so I started swimming, too.$"

Route125_Text_TanyaIntro:
	.string "I'm tired of swimming.\n"
	.string "Are you up for a battle with me?$"

Route125_Text_TanyaDefeat:
	.string "You're too much!$"

Route125_Text_TanyaPostBattle:
	.string "Whew…\n"
	.string "Which way is it to MOSSDEEP CITY?$"

Route125_Text_SharonIntro:
	.string "How would you like to take on the\n"
	.string "WATER-type POKéMON I raised?$"

Route125_Text_SharonDefeat:
	.string "Lost it…$"

Route125_Text_SharonPostBattle:
	.string "Your power… You're the real deal.\n"
	.string "I'm amazed!$"

Route125_Text_ErnestIntro:
	.string "Ahoy! I'm a buff, tough SAILOR!\n"
	.string "I've braved the world's seas!$"

Route125_Text_ErnestDefeat:
	.string "Gwrroooar!\n"
	.string "I couldn't win!$"

Route125_Text_ErnestPostBattle:
	.string "The tide ebbs and flows inside the\n"
	.string "SHOAL CAVE.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Did you know?$"

Route125_Text_ErnestRegister:
	.string "Register me in your POKéNAV,\n"
	.string "and I'll tell you something good.$"

Route125_Text_ErnestRematchIntro:
	.string "It's high time I get my payback\n"
	.string "from you! Come on, we're battling!$"

Route125_Text_ErnestRematchDefeat:
	.string "I couldn't win!\n"
	.string "I flat out couldn't win!$"

Route125_Text_ErnestRematchPostBattle:
	.string "The SHOAL CAVE…\p"
	.string "There are places you can and can't\n"
	.string "get to depending on the rise and fall\l"
	.string "of the tide.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Don't forget!$"

Route125_Text_KimIntro:
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE. Someone told me.\l"
	.string "Are you going to see him, too?$"

Route125_Text_KimDefeat:
	.string "KIM: I thought we would win.$"

Route125_Text_KimPostBattle:
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE, doesn't he?\p"
	.string "Let's go see him, IRIS!$"

Route125_Text_KimNotEnoughMons:
	.string "KIM: No, no, no! You need two POKéMON,\n"
	.string "or it's just no good!$"

Route125_Text_IrisIntro:
	.string "IRIS: KIM, can you tell me what we're\n"
	.string "looking for out here?$"

Route125_Text_IrisDefeat:
	.string "IRIS: Oh, we came sort of close.$"

Route125_Text_IrisPostBattle:
	.string "IRIS: KIM, are we really going into\n"
	.string "the SHOAL CAVE?\l"
	.string "We'll get all wet.$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS: Oh, we could never, ever do\n"
	.string "anything like a 2-on-1 battle.$"

Route125_Text_PresleyIntro:
	.string "Why would a BIRDKEEPER like me\n"
	.string "come out to the sea?$"

Route125_Text_PresleyDefeat:
	.string "Okay.\n"
	.string "I'll tell you why I'm here.$"

Route125_Text_PresleyPostBattle:
	.string "I put a message in a bottle and put\n"
	.string "it out to sea.\p"
	.string "I'm sure that a girl SWIMMER will\n"
	.string "find it!$"

Route125_Text_AuronIntro:
	.string "Hey! Was it you throwing garbage\n"
	.string "into the sea?$"

Route125_Text_AuronDefeat:
	.string "Oh, you weren't throwing trash into\n"
	.string "the sea.$"

Route125_Text_AuronPostBattle:
	.string "I found an unsightly bottle bobbing\n"
	.string "in the waves earlier.\p"
	.string "It angers me that someone would\n"
	.string "pollute the sea!$"

Route126_Text_BarryIntro:
	.string "Swimming is a full-body workout!\n"
	.string "You will get fit!$"

Route126_Text_BarryDefeat:
	.string "I admit it!\n"
	.string "You win!$"

Route126_Text_BarryPostBattle:
	.string "Thanks to my daily swimming routine…\n"
	.string "Look! Feast your eyes on this physique!$"

Route126_Text_DeanIntro:
	.string "This towering white mountain of rock\n"
	.string "is SOOTOPOLIS CITY.$"

Route126_Text_DeanDefeat:
	.string "I was done in?$"

Route126_Text_DeanPostBattle:
	.string "I can't find the entrance to\n"
	.string "SOOTOPOLIS. Where could it be?$"

Route126_Text_NikkiIntro:
	.string "Ufufufufu!\n"
	.string "I'm a mermaid!$"

Route126_Text_NikkiDefeat:
	.string "My fantasy burst as if it were a bubble!\n"
	.string "Blub, blub, blub…$"

Route126_Text_NikkiPostBattle:
	.string "You thrashed me… I want to\n"
	.string "disappear in a wave of despair…$"

Route126_Text_BrendaIntro:
	.string "Hello, kiddo!\n"
	.string "Want a battle with me?$"

Route126_Text_BrendaDefeat:
	.string "Oh, noooooh!$"

Route126_Text_BrendaPostBattle:
	.string "I love frolicking with POKéMON in\n"
	.string "the sea like this!$"

Route126_Text_PabloIntro:
	.string "Check out this sculpted body!\n"
	.string "I'm more cut than a BLACK BELT!$"

Route126_Text_PabloDefeat:
	.string "Whoops! Too strong!\n"
	.string "Not bad! Not bad at all!$"

Route126_Text_PabloPostBattle:
	.string "Losing to you stimulated my senses!\n"
	.string "I'll train myself and POKéMON harder!$"

Route126_Text_PabloRegister:
	.string "Yep, you're not bad at all!\n"
	.string "I'd like to get to know you more!$"

Route126_Text_PabloRematchIntro:
	.string "Check out this beautiful body!\n"
	.string "I'm more shapely than a SWIMMER!$"

Route126_Text_PabloRematchDefeat:
	.string "Whoops! Really too strong!\n"
	.string "Not bad! Not bad at all!$"

Route126_Text_PabloPostRematch:
	.string "I'm going to train even harder!\n"
	.string "You're a great motivator!\l"
	.string "You have to come back again!$"

Route126_Text_LeonardoIntro:
	.string "I couldn't even swim last year,\n"
	.string "but now I'm a decent SWIMMER.\p"
	.string "I think I'm capable of anything now.$"

Route126_Text_LeonardoDefeat:
	.string "Sheesh, getting greedy didn't do\n"
	.string "a thing for me.$"

Route126_Text_LeonardoPostBattle:
	.string "If you practice at something,\n"
	.string "you will get better at it.\p"
	.string "You're young--don't be afraid to\n"
	.string "try all sorts of things!$"

Route126_Text_IsobelIntro:
	.string "If seawater gets up your nose,\n"
	.string "doesn't it feel terrible?$"

Route126_Text_IsobelDefeat:
	.string "Ack! Why, you…\n"
	.string "Glub!$"

Route126_Text_IsobelPostBattle:
	.string "Ooh, I choked on some water!\n"
	.string "It's bitter! It's salty!!$"

Route126_Text_SiennaIntro:
	.string "I'm throwing my whole heart\n"
	.string "into this!$"

Route126_Text_SiennaDefeat:
	.string "You had more heart!$"

Route126_Text_SiennaPostBattle:
	.string "I need to cool down now…\n"
	.string "I think I'll go for a dive.$"

Route127_Text_CamdenIntro:
	.string "I can see it in your face.\n"
	.string "You want to challenge me.$"

Route127_Text_CamdenDefeat:
	.string "Awawawawawa…$"

Route127_Text_CamdenPostBattle:
	.string "A well-played match leaves me feeling\n"
	.string "refreshed and serene.$"

Route127_Text_DonnyIntro:
	.string "Do you have a rival whom you just\n"
	.string "hate to lose against?$"

Route127_Text_DonnyDefeat:
	.string "Arrrgh!\n"
	.string "I hate losing!$"

Route127_Text_DonnyPostBattle:
	.string "If you have a rival, don't you get the\n"
	.string "feeling that you have to keep getting\l"
	.string "better?$"

Route127_Text_JonahIntro:
	.string "Through fishing, I have attained a\n"
	.string "state of becalmed serenity…\p"
	.string "Please, allow me to demonstrate…$"

Route127_Text_JonahDefeat:
	.string "Though I have lost, my heart remains\n"
	.string "calm…$"

Route127_Text_JonahPostBattle:
	.string "It matters not that I catch nothing.\n"
	.string "The line remains in the water…$"

Route127_Text_HenryIntro:
	.string "Whoops! Don't tell me I snagged\n"
	.string "a SURFING POKéMON?$"

Route127_Text_HenryDefeat:
	.string "I can't keep up!$"

Route127_Text_HenryPostBattle:
	.string "It'd be a handful if I hooked\n"
	.string "your tough POKéMON!$"

Route127_Text_RogerIntro:
	.string "Well, hey! This is a match between\n"
	.string "a POKéMON fan and a fishing buff!$"

Route127_Text_RogerDefeat:
	.string "No! My line's all tangled!\n"
	.string "The party's over!$"

Route127_Text_RogerPostBattle:
	.string "My fishing line's doing a dance!\n"
	.string "The tangle tango! Hahaha, snarl!$"

Route127_Text_AidanIntro:
	.string "BIRD POKéMON have excellent vision.\n"
	.string "They spot prey from great heights.$"

Route127_Text_AidanDefeat:
	.string "Whew… I give up.$"

Route127_Text_AidanPostBattle:
	.string "There're lots of diving spots in\n"
	.string "the sea around here.\p"
	.string "You can spot them easily from the sky\n"
	.string "because of their darker color.$"

Route127_Text_KojiIntro:
	.string "Run in your bare feet.\n"
	.string "That will toughen up your soles!$"

Route127_Text_KojiDefeat:
	.string "Yowch!\n"
	.string "I got a pebble under a toenail!$"

Route127_Text_KojiPostBattle:
	.string "Going barefoot feels great.\n"
	.string "But your RUNNING SHOES are cool, too.$"

Route127_Text_KojiRegister:
	.string "This is what I do to people who beat me!\n"
	.string "I hope we can do this again.$"

Route127_Text_KojiRematchIntro:
	.string "I still run in my bare feet daily.\n"
	.string "My soles are tough!$"

Route127_Text_KojiRematchDefeat:
	.string "Yowch!\n"
	.string "Pebbles dug into my arches!$"

Route127_Text_KojiPostRematch:
	.string "Want to go barefoot for a while?\n"
	.string "So I can try your RUNNING SHOES?$"

Route127_Text_AthenaIntro:
	.string "We should have a slow and methodical\n"
	.string "match.$"

Route127_Text_AthenaDefeat:
	.string "You didn't give me the chance to\n"
	.string "do any strategizing.$"

Route127_Text_AthenaPostBattle:
	.string "When I'm surrounded by the blue sea\n"
	.string "and sky, it feels as if time slows down.$"

Route128_Text_IsaiahIntro:
	.string "EVER GRANDE CITY is still a long ways\n"
	.string "away…$"

Route128_Text_IsaiahDefeat:
	.string "My first victory seems to be far\n"
	.string "away, too…$"

Route128_Text_IsaiahPostBattle:
	.string "My whole life has been about losing,\n"
	.string "but I will never give up!$"

Route128_Text_IsaiahRegister:
	.string "I know I'm not good now, but I think\n"
	.string "I can win eventually.\p"
	.string "Please register me in your POKéNAV.$"

Route128_Text_IsaiahRematchIntro:
	.string "I'm still feeling good. I'll keep on\n"
	.string "swimming to EVER GRANDE CITY.$"

Route128_Text_IsaiahRematchDefeat:
	.string "I've yet to taste my first victory…$"

Route128_Text_IsaiahPostRematch:
	.string "I'll eventually reach EVER GRANDE CITY\n"
	.string "where I can eventually win…$"

Route128_Text_KatelynIntro:
	.string "You have to swim, cycle, and then run\n"
	.string "a marathon in a triathlon.\p"
	.string "It's a grueling race that consists\n"
	.string "of three events.$"

Route128_Text_KatelynDefeat:
	.string "A POKéMON battle is grueling, too…$"

Route128_Text_KatelynPostBattle:
	.string "I have to ride a BIKE next, but…\n"
	.string "I'm about to throw in the towel…$"

Route128_Text_KatelynRegister:
	.string "Well, I may as well make the best\n"
	.string "of this. I'd like a rematch sometime.$"

Route128_Text_KatelynRematchIntro:
	.string "A triathlon is long. But I guess the\n"
	.string "road to become the POKéMON CHAMPION\l"
	.string "is also a long and grueling one.$"

Route128_Text_KatelynRematchDefeat:
	.string "A POKéMON battle really is harsh\n"
	.string "and unforgiving…$"

Route128_Text_KatelynPostRematch:
	.string "You should give serious thought to\n"
	.string "challenges on VICTORY ROAD.$"

Route128_Text_AlexaIntro:
	.string "We've been working so hard to mount\n"
	.string "a POKéMON LEAGUE challenge…\p"
	.string "We can't afford to lose now!$"

Route128_Text_AlexaDefeat:
	.string "Oh!\n"
	.string "How could this happen?!$"

Route128_Text_AlexaPostBattle:
	.string "After all I've done to get here,\n"
	.string "I won't give up after one setback.$"

Route128_Text_RubenIntro:
	.string "There is no stronger TRAINER than I!$"

Route128_Text_RubenDefeat:
	.string "This can't be!$"

Route128_Text_RubenPostBattle:
	.string "There probably is no stronger TRAINER\n"
	.string "than you!$"

Route128_Text_WayneIntro:
	.string "I want to visit EVER GRANDE, so I\n"
	.string "caught myself a POKéMON that knows\l"
	.string "the move WATERFALL to crest the falls.$"

Route128_Text_WayneDefeat:
	.string "I'm crestfallen!$"

Route128_Text_WaynePostBattle:
	.string "Awww, phooey!\p"
	.string "My POKéMON knows WATERFALL, but\n"
	.string "I don't have the SOOTOPOLIS GYM BADGE!$"

Route128_Text_HarrisonIntro:
	.string "You're looking awfully tough.\n"
	.string "I wonder if I can win?$"

Route128_Text_HarrisonDefeat:
	.string "Ouch!\n"
	.string "I guess it was impossible to win.$"

Route128_Text_HarrisonPostBattle:
	.string "There are tough TRAINERS galore\n"
	.string "around EVER GRANDE.\p"
	.string "Do you think I may be out\n"
	.string "of my league?$"

Route128_Text_CarleeIntro:
	.string "The sunlight seems to be more harsh\n"
	.string "in this area.$"

Route128_Text_CarleeDefeat:
	.string "I couldn't see very well because of\n"
	.string "the sun's glare.$"

Route128_Text_CarleePostBattle:
	.string "I should go back soon.\n"
	.string "I need to reapply my sunscreen.$"

Route129_Text_ChaseIntro:
	.string "This is my first triathlon.\n"
	.string "I'm all tense and nervous!$"

Route129_Text_ChaseDefeat:
	.string "Wroooaaar!\n"
	.string "I failed to win!$"

Route129_Text_ChasePostBattle:
	.string "If I'm all tensed up, I won't be able to\n"
	.string "give it my all.$"

Route129_Text_AllisonIntro:
	.string "I'm in the middle of a triathlon,\n"
	.string "but, sure, why don't we battle?$"

Route129_Text_AllisonDefeat:
	.string "I was sure I'd win!$"

Route129_Text_AllisonPostBattle:
	.string "Do you know what's the greatest thing\n"
	.string "about triathlons?\p"
	.string "Testing the limits of your own\n"
	.string "strength and endurance against\l"
	.string "Mother Nature!$"

Route129_Text_ReedIntro:
	.string "Say hey, hey!\n"
	.string "Let's get on with it!$"

Route129_Text_ReedDefeat:
	.string "Beat, I'm beaten.\n"
	.string "That's it, done!$"

Route129_Text_ReedPostBattle:
	.string "There's nothing for a loser.\n"
	.string "Time for me to beat it home.$"

Route129_Text_TishaIntro:
	.string "What's the hurry?\n"
	.string "Let's take it slow and easy.$"

Route129_Text_TishaDefeat:
	.string "Oh, my.\n"
	.string "I wanted to relax a little more…$"

Route129_Text_TishaPostBattle:
	.string "Don't you hate making mistakes when\n"
	.string "you're in a rush?\p"
	.string "That's why I try to take things\n"
	.string "slowly.$"

Route129_Text_ClarenceIntro:
	.string "Surfing isn't as easy as it seems,\n"
	.string "isn't that right?$"

Route129_Text_ClarenceDefeat:
	.string "Winning sure isn't easy.$"

Route129_Text_ClarencePostBattle:
	.string "You have your sights on the POKéMON\n"
	.string "LEAGUE? Keep at it!$"

Route130_Text_RodneyIntro:
	.string "What a surprise! I didn't expect to\n"
	.string "see a TRAINER out in the sea.\p"
	.string "I think we should battle!$"

Route130_Text_RodneyDefeat:
	.string "This kid's awfully tough…$"

Route130_Text_RodneyPostBattle:
	.string "Your eyes have that look of someone\n"
	.string "who's experienced harsh challenges\l"
	.string "and won. It suits you well!$"

Route130_Text_KatieIntro:
	.string "In the deep blue sea,\n"
	.string "my shattered blue heart finds\l"
	.string "comfort among waves.$"

Route130_Text_KatieDefeat:
	.string "Like the vast blue sea,\n"
	.string "the world of POKéMON spans\l"
	.string "depths beyond belief.$"

Route130_Text_KatiePostBattle:
	.string "The world's children dream\n"
	.string "of one day becoming\l"
	.string "the POKéMON CHAMPION.$"

Route130_Text_SantiagoIntro:
	.string "Floating on the open sea like this…\n"
	.string "It's peaceful.$"

Route130_Text_SantiagoDefeat:
	.string "I needed to be a little less peaceful!$"

Route130_Text_SantiagoPostBattle:
	.string "Swimming and battling like this…\n"
	.string "I'm one happy guy…$"

Route131_Text_RichardIntro:
	.string "The sea is teeming with POKéMON.\n"
	.string "It's not easy swimming, I tell you.$"

Route131_Text_RichardDefeat:
	.string "POKéMON raised by TRAINERS are\n"
	.string "seriously tough…$"

Route131_Text_RichardPostBattle:
	.string "Gasp… Gasp…\n"
	.string "I'm wiped out…\p"
	.string "The going's easy. It's the leaving\n"
	.string "that's the hard part.\p"
	.string "Will I have any energy left to make\n"
	.string "the return trip?$"

Route131_Text_HermanIntro:
	.string "The sea… The sea… The sea…\n"
	.string "The sea as far as these eyes can see!\l"
	.string "I'm sick and tired of the sea!$"

Route131_Text_HermanDefeat:
	.string "Bleah!$"

Route131_Text_HermanPostBattle:
	.string "Bored I am by the sea, but swim I must.\p"
	.string "I'm a born swimmer!\n"
	.string "That's what I am.$"

Route131_Text_SusieIntro:
	.string "Hi, sweetie, wait!\n"
	.string "We should battle, you and I!$"

Route131_Text_SusieDefeat:
	.string "You're tough in spite of the way\n"
	.string "you look!$"

Route131_Text_SusiePostBattle:
	.string "Did you see a guy over there who whines\n"
	.string "that he's bored of the sea?\p"
	.string "That's all talk.\n"
	.string "He's hopelessly in love with the sea!$"

Route131_Text_KaraIntro:
	.string "Why do men love bathing suits so much?\p"
	.string "They all ogle me!$"

Route131_Text_KaraDefeat:
	.string "I'm out of my depth!$"

Route131_Text_KaraPostBattle:
	.string "Maybe it's not my bathing suit that\n"
	.string "makes men look. It must be my beauty!$"

Route131_Text_ReliIntro:
	.string "RELI: We'll work together as siblings\n"
	.string "to take you on!$"

Route131_Text_ReliDefeat:
	.string "RELI: We couldn't win even though we\n"
	.string "worked together…$"

Route131_Text_ReliPostBattle:
	.string "RELI: The people of PACIFIDLOG are\n"
	.string "together with the sea and POKéMON from\l"
	.string "the time they are born.$"

Route131_Text_ReliNotEnoughMons:
	.string "RELI: You don't have two POKéMON?\n"
	.string "We can't enjoy a battle, then.$"

Route131_Text_IanIntro:
	.string "IAN: I'm doing my best together with\n"
	.string "my sis!$"

Route131_Text_IanDefeat:
	.string "IAN: I did my best with my sis,\n"
	.string "but we still couldn't win…$"

Route131_Text_IanPostBattle:
	.string "IAN: You know how PACIFIDLOG is\n"
	.string "a floating town?\p"
	.string "So, wherever there is the sea,\n"
	.string "that's a part of PACIFIDLOG!$"

Route131_Text_IanNotEnoughMons:
	.string "IAN: If you have two POKéMON,\n"
	.string "we'll take you on!$"

Route131_Text_TaliaIntro:
	.string "If you can beat me, I'll give you some\n"
	.string "great information!$"

Route131_Text_TaliaDefeat:
	.string "Oh?\n"
	.string "Did I lose?$"

Route131_Text_TaliaPostBattle:
	.string "There is an odd place nearby.\n"
	.string "There's a huge tower there.\l"
	.string "Why don't you go take a look?$"

Route131_Text_KevinIntro:
	.string "The people of PACIFIDLOG are\n"
	.string "a peaceful bunch.\p"
	.string "They never get angry.\n"
	.string "That goes for me, too.$"

Route131_Text_KevinDefeat:
	.string "Oops!$"

Route131_Text_KevinPostBattle:
	.string "Tch! …Oh, wait.\n"
	.string "I'm not angry. Honestly!\p"
	.string "But, boy, you're strong!\n"
	.string "Hahaha!$"

Route132_Text_GilbertIntro:
	.string "I used to catch colds all the time as\n"
	.string "a kid, but I became totally fit after\l"
	.string "I started swimming.$"

Route132_Text_GilbertDefeat:
	.string "I crave more power…$"

Route132_Text_GilbertPostBattle:
	.string "TRAINERS travel the fields and\n"
	.string "mountains, so they must be fit, too.$"

Route132_Text_DanaIntro:
	.string "I try not to swim where the currents\n"
	.string "are too strong.$"

Route132_Text_DanaDefeat:
	.string "Oh, please, no!$"

Route132_Text_DanaPostBattle:
	.string "If I get swept away, I'll lose all my\n"
	.string "sense of place…$"

Route132_Text_RonaldIntro:
	.string "Win or lose, you'll never know until\n"
	.string "you try!$"

Route132_Text_RonaldDefeat:
	.string "Waah!\n"
	.string "I sank in defeat!$"

Route132_Text_RonaldPostBattle:
	.string "I never battle when I know I'll win.\n"
	.string "I like to battle at the razor's edge of\l"
	.string "victory and defeat!$"

Route132_Text_KiyoIntro:
	.string "I contemplate POKéMON 24 hours a day.\n"
	.string "How could you possibly beat me?$"

Route132_Text_KiyoDefeat:
	.string "I lose.\n"
	.string "I will concede defeat.$"

Route132_Text_KiyoPostBattle:
	.string "Urggh…\n"
	.string "You're a POKéMON fanatic, aren't you?\p"
	.string "You must contemplate POKéMON 24 hours\n"
	.string "a day, don't you?$"

Route132_Text_MakaylaIntro:
	.string "I'm always with my husband,\n"
	.string "but I can win even without him.$"

Route132_Text_MakaylaDefeat:
	.string "Oh, I guess I wasn't good enough.$"

Route132_Text_MakaylaPostBattle:
	.string "That young man over there looks just\n"
	.string "like my husband when he was young.\p"
	.string "He's making me blush!$"

Route132_Text_JonathanIntro:
	.string "Someone's been watching me intently.\n"
	.string "Was it you?$"

Route132_Text_JonathanDefeat:
	.string "Wow!\n"
	.string "That's pretty strong, all right!$"

Route132_Text_JonathanPostBattle:
	.string "I can't shake this feeling that\n"
	.string "someone's watching me.\p"
	.string "I can't concentrate!$"

Route132_Text_PaxtonIntro:
	.string "Now where could my wife have gone?\n"
	.string "I'm always with her.\l"
	.string "I wonder if I can win on my own.$"

Route132_Text_PaxtonDefeat:
	.string "Ah, I see that I couldn't manage\n"
	.string "to win on my own after all.$"

Route132_Text_PaxtonPostBattle:
	.string "My wife must be looking for me.\n"
	.string "I'd best go find her right away.$"

Route132_Text_DarcyIntro:
	.string "I liked training here by myself.\n"
	.string "It's awful that all these people came!$"

Route132_Text_DarcyDefeat:
	.string "Okay! I won't complain about other\n"
	.string "people being here.$"

Route132_Text_DarcyPostBattle:
	.string "I suppose I can partner up with that\n"
	.string "old man and challenge that other team.$"

Route133_Text_FranklinIntro:
	.string "Did the currents carry you here, too?\n"
	.string "This must have been fated.\l"
	.string "Let's battle!$"

Route133_Text_FranklinDefeat:
	.string "Strong!\n"
	.string "Too much so!$"

Route133_Text_FranklinPostBattle:
	.string "It's just my luck that a tough TRAINER\n"
	.string "like you would drift here…\l"
	.string "I must be cursed…$"

Route133_Text_DebraIntro:
	.string "I've led a life of woe and misery…\n"
	.string "I've been cast away, and this is where\l"
	.string "I've drifted…$"

Route133_Text_DebraDefeat:
	.string "Another loss…$"

Route133_Text_DebraPostBattle:
	.string "A life adrift…\n"
	.string "I don't want it anymore!$"

Route133_Text_LindaIntro:
	.string "Welcome!\n"
	.string "I've been expecting you!$"

Route133_Text_LindaDefeat:
	.string "No! Please!$"

Route133_Text_LindaPostBattle:
	.string "A strong child TRAINER…\n"
	.string "That's so annoying!$"

Route133_Text_WarrenIntro:
	.string "I want to win like everyone else, but I\n"
	.string "won't raise POKéMON like everyone else.$"

Route133_Text_WarrenDefeat:
	.string "Darn it!\n"
	.string "My way is still too slack!$"

Route133_Text_WarrenPostBattle:
	.string "It's way more fun to do things the way\n"
	.string "I want than to be like everybody else.\l"
	.string "I mean, that's obvious!$"

Route133_Text_BeckIntro:
	.string "I came all the way out here with my\n"
	.string "BIRD POKéMON.$"

Route133_Text_BeckDefeat:
	.string "You…\n"
	.string "You're stunningly cool!$"

Route133_Text_BeckPostBattle:
	.string "I'd like to go back to FORTREE,\n"
	.string "but I've grown to like this place, too.$"

Route133_Text_MollieIntro:
	.string "I must have battled thousands\n"
	.string "of times. I've lost count.$"

Route133_Text_MollieDefeat:
	.string "I may have lost thousands of times,\n"
	.string "but a loss still stings.$"

Route133_Text_MolliePostBattle:
	.string "Keep at this, youngster. So you can\n"
	.string "become like my husband and me.$"

Route133_Text_ConorIntro:
	.string "Young people are too happy to go with\n"
	.string "the flow. They're without direction.$"

Route133_Text_ConorDefeat:
	.string "You have a firm sense of purpose.$"

Route133_Text_ConorPostBattle:
	.string "Don't let others lead you astray.\n"
	.string "Don't lose direction as you grow older.$"

Route134_Text_JackIntro:
	.string "Even those POKéMON that can swim are\n"
	.string "carried along by the rapid currents.$"

Route134_Text_JackDefeat:
	.string "Aiyeeeeh!$"

Route134_Text_JackPostBattle:
	.string "I think POKéMON enjoy the fast-running\n"
	.string "currents around these parts.$"

Route134_Text_LaurelIntro:
	.string "My LUVDISC are looking for a fun\n"
	.string "match. Will you join us?$"

Route134_Text_LaurelDefeat:
	.string "Oopsie!$"

Route134_Text_LaurelPostBattle:
	.string "There's a collector who's after\n"
	.string "the SCALES of LUVDISC.$"

Route134_Text_AlexIntro:
	.string "Okeydokey! That's enough rest, gang!\n"
	.string "It's time for a match!$"

Route134_Text_AlexDefeat:
	.string "Tuckered out again…$"

Route134_Text_AlexPostBattle:
	.string "My BIRD POKéMON get tired quickly after\n"
	.string "a long flight…$"

Route134_Text_HitoshiIntro:
	.string "You're a POKéMON TRAINER.\n"
	.string "No need for words. We battle now.$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "It was I who challenged you, and yet\n"
	.string "I lost. I am deeply shamed…$"

Route134_Text_AaronIntro:
	.string "The savage tide in this area serves to\n"
	.string "make us stronger than ever.$"

Route134_Text_AaronDefeat:
	.string "I willingly concede defeat.$"

Route134_Text_AaronPostBattle:
	.string "We will return for more training at\n"
	.string "METEOR FALLS.\p"
	.string "If you'd like, you should go, too.\n"
	.string "It will definitely toughen you up!$"

Route134_Text_KelvinIntro:
	.string "O-our boat!\n"
	.string "The tide carried it away!$"

Route134_Text_KelvinDefeat:
	.string "Awawawawah!\n"
	.string "Please, stop! Please!$"

Route134_Text_KelvinPostBattle:
	.string "If we can't SURF, how are we supposed\n"
	.string "to get home?\p"
	.string "Actually, I know a fainted POKéMON\n"
	.string "can still SURF, but it feels wrong.$"

Route134_Text_MarleyIntro:
	.string "Can your POKéMON dodge our\n"
	.string "lightning-quick attacks?$"

Route134_Text_MarleyDefeat:
	.string "I never knew such a technique existed!\n"
	.string "You've defeated us thoroughly.$"

Route134_Text_MarleyPostBattle:
	.string "I haven't lost my passion for speed.\n"
	.string "I will try harder.$"

Route134_Text_ReynaIntro:
	.string "My POKéMON can't be taken down\n"
	.string "easily!$"

Route134_Text_ReynaDefeat:
	.string "You're kidding!\n"
	.string "Explain how I lost!$"

Route134_Text_ReynaPostBattle:
	.string "Haha!\n"
	.string "You won, all right!\p"
	.string "I'll work my way back up by taking on\n"
	.string "TRAINERS I happen to meet!$"

Route134_Text_HudsonIntro:
	.string "Listen, have you seen another SAILOR\n"
	.string "around here?$"

Route134_Text_HudsonDefeat:
	.string "Now, that's something!$"

Route134_Text_HudsonPostBattle:
	.string "Our boat drifted out to sea.\p"
	.string "My buddy's a timid fellow, so I'm\n"
	.string "worried about him.$"

VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "The battery isn't charged enough.\p"
	.string "No. of steps required to fully\n"
	.string "charge the battery: {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "There are no Trainers within range\n"
	.string "who can battle…\p"
	.string "The VS Seeker was turned off.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady::
	.string "The other Trainers don't appear\n"
	.string "to be ready for battle.\p"
	.string "Let's wait till later.{PAUSE_UNTIL_PRESS}$"
