gTrickHouse_Mechadoll_Oddish::
	.string "{JPN}ナゾノクサ$"

gTrickHouse_Mechadoll_Poochyena::
	.string "{JPN}ポチエナ$"

gTrickHouse_Mechadoll_Taillow::
	.string "{JPN}スバメ$"

gTrickHouse_Mechadoll_Azurill::
	.string "{JPN}ルリリ$"

gTrickHouse_Mechadoll_Lotad::
	.string "{JPN}ハスボー$"

gTrickHouse_Mechadoll_Wingull::
	.string "{JPN}キャモメ$"

gTrickHouse_Mechadoll_Dustox::
	.string "{JPN}ドクケイル$"

gTrickHouse_Mechadoll_Zubat::
	.string "{JPN}ズバット$"

gTrickHouse_Mechadoll_Nincada::
	.string "{JPN}ツチニン$"

gTrickHouse_Mechadoll_Ralts::
	.string "{JPN}ラルトス$"

gTrickHouse_Mechadoll_Zigzagoon::
	.string "{JPN}ジグザグマ$"

gTrickHouse_Mechadoll_Slakoth::
	.string "{JPN}ナマケロ$"

gTrickHouse_Mechadoll_Poochyena2::
	.string "{JPN}ポチエナ$"

gTrickHouse_Mechadoll_Shroomish::
	.string "{JPN}キノココ$"

gTrickHouse_Mechadoll_Zigzagoon2::
	.string "{JPN}ジグザグマ$"

gTrickHouse_Mechadoll_Poochyena3::
	.string "{JPN}ポチエナ$"

gTrickHouse_Mechadoll_Zubat2::
	.string "{JPN}ズバット$"

gTrickHouse_Mechadoll_Carvanha::
	.string "{JPN}キバニア$"

gTrickHouse_Mechadoll_BurnHeal::
	.string "{JPN}やけどなおし$"

gTrickHouse_Mechadoll_HarborMail::
	.string "{JPN}ハーバーメール$"

gTrickHouse_Mechadoll_SamePrice::
	.string "{JPN}おなじ ねだん$"

gTrickHouse_Mechadoll_60Yen::
	.string "¥60$"

gTrickHouse_Mechadoll_55Yen::
	.string "¥55$"

gTrickHouse_Mechadoll_Nothing::
	.string "{JPN}なにも ない$"

gTrickHouse_Mechadoll_CostMore::
	.string "{JPN}たかく なる$"

gTrickHouse_Mechadoll_CostLess::
	.string "{JPN}やすく なる$"

gTrickHouse_Mechadoll_SamePrice2::
	.string "{JPN}おなじ ねだん$"

gTrickHouse_Mechadoll_Male::
	.string "{JPN}おとこ$"

gTrickHouse_Mechadoll_Female::
	.string "{JPN}おんな$"

gTrickHouse_Mechadoll_Neither::
	.string "{JPN}どちらでも ない$"

gTrickHouse_Mechadoll_ElderlyMen::
	.string "{JPN}おじいさん$"

gTrickHouse_Mechadoll_ElderlyLadies::
	.string "{JPN}おばあさん$"

gTrickHouse_Mechadoll_SameNumber::
	.string "{JPN}おなじ かず$"

gTrickHouse_Mechadoll_None::
	.string "{JPN}いない$"

gTrickHouse_Mechadoll_One::
	.string "1$"

gTrickHouse_Mechadoll_Two::
	.string "2$"

gTrickHouse_Mechadoll_Two2::
	.string "2$"

gTrickHouse_Mechadoll_Three::
	.string "3$"

gTrickHouse_Mechadoll_Four::
	.string "4$"

gTrickHouse_Mechadoll_Six::
	.string "6$"

gTrickHouse_Mechadoll_Nine::
	.string "9$"

gTrickHouse_Mechadoll_Seven::
	.string "7$"

gTrickHouse_Mechadoll_Eight::
	.string "8$"

gTrickHouse_Mechadoll_Six2::
	.string "6$"

gTrickHouse_Mechadoll_Seven2::
	.string "7$"

gTrickHouse_Mechadoll_Eight2::
	.string "8$"
