LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "{JPN}あら こんにちは! ポケモンコンテストに\nでて いましたよね?\lポケモンを みれば わかりますよ。\pわたしは きしゃです。ポケモンコンテストの\nきじを かいて いるんです。\pよろしければ いくつか しつもんに\nこたえて いただけませんか?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "{JPN}ほんとうですか?\nありがとう ございます。\pいま でた コンテストを ひとことで\nいうと どんな かんじでしたか?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "{JPN}なるほど。\nとても ためになる ごいけんです。\pコンテストの ふんいきが よく\nつたわって きますね。\pさいごに もう ひとつ しつもんです。\p「{STR_VAR_2}」と きいて\nどんな イメージが うかびますか?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "{JPN}なるほど!\p「{STR_VAR_2}」を そんなふうに\nかんじて いるのですね。\pありがとう ございます!\nいい ヒントを いただきました。\pこれで ポケモンコンテストの いい きじが\nかけそうです。\pもしかしたら この はなしは テレビにも\nなるかも しれません。\lたのしみに して いて くださいね!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "{JPN}おや ざんねん…\pいい はなしが あったら\nぜひ きかせて くださいね。$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "{JPN}つぎの ポケモンコンテストを\nたのしみに して います。$"

gTVBravoTrainerText00::
	.string "{JPN}イエーイ!\nブラボートレーナーの じかんだ!\pきょうは {STR_VAR_1}さんの ポケモンを\nしょうかい するぞ。\pこの ポケモン {STR_VAR_2}ぶもんで\n{STR_VAR_3}ランクの じつりょくだ。$"

gTVBravoTrainerText01::
	.string "{JPN}ごしょうかい {STR_VAR_1}の\n{STR_VAR_2}!\p{STR_VAR_2}と いう ニックネーム…\pニックネームからして「{STR_VAR_3}」の\nかおりが ただよって いるぞ!$"

gTVBravoTrainerText02::
	.string "{JPN}さて トレーナーの {STR_VAR_1}さんが\nこの ポケモンを コンテストに だした とき\lあいぼうへの あつい ことばを\lいくつか きく ことが できた。$"

gTVBravoTrainerText03::
	.string "{JPN}コンテストの あとに きいて みると\n{STR_VAR_1}さんは まんめんの えがおで\l「{STR_VAR_2}!」と こたえて くれた。\pそれも そのはず {STR_VAR_1}さんの ポケモンは\nコンテストで {STR_VAR_3}いだったのだ。\pいまの {STR_VAR_1}さんに ぴったりの\nひとことだと いえるだろう!$"

gTVBravoTrainerText04::
	.string "{JPN}コンテストの あとに きいて みると\n{STR_VAR_1}さんは すこし くやしそうに\l「{STR_VAR_2}」と こたえて くれた。\pそれも そのはず {STR_VAR_1}さんの ポケモンは\nコンテストで {STR_VAR_3}いだったのだ。\p{STR_VAR_1}さんの ざんねんな きもちが\nよく つたわって くるぞ!$"

gTVBravoTrainerText05::
	.string "{JPN}{STR_VAR_1}さんが {STR_VAR_2}を どう\nかんじて いるか きになるだろう?\pもちろん きになる!\nだから きいて みたぞ!\pこたえは この ひとことに つまって いた。\n「{STR_VAR_3}!」\pこれが {STR_VAR_1}さんに とっての\n{STR_VAR_2}なのだ!$"

gTVBravoTrainerText06::
	.string "{JPN}{STR_VAR_1}が さいごに つかった わざ\n{STR_VAR_2}は まさに\l「{STR_VAR_3}」そのものだ!$"

gTVBravoTrainerText07::
	.string "{JPN}ブラボー {STR_VAR_1}さん!\nブラボー {STR_VAR_2}!\p{STR_VAR_1}さんの さらなる かつやくに\nきたい したい ところだ!\pきょうは ここまで!\nそれでは また あおう!$"

gTVBravoTrainerText08::
	.string "{JPN}トレーナーの {STR_VAR_1}を ごしょうかい!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "{JPN}こんにちは! いま バトルを して いた\nトレーナーさんですよね?\pあちこちで トレーナーの みなさんに\nインタビューを して いるんです。\pバトルの かんそうを ひとこと\nいただけませんか?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "{JPN}ほんとうですか?\nありがとう ございます!\lでは ええと…\pきょうの バトルタワーは\nいかがでしたか?\pまんぞくの いく バトルでしたか?\nそれとも ふまんが のこりますか?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "{JPN}そうですか…\nおじゃま しました。\pこんど バトルタワーに きた ときは\nぜひ インタビュー させて ください。$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "{JPN}やはり そうですか!\pまちがい ようの ない まんぞくの\nひょうじょうを して いますね…\pすばらしい バトルだったのが\nよく わかります。$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "{JPN}そうですか…\pおもいどおりの バトルに するのは\nたしかに むずかしい ものですね。$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "{JPN}あっ もう ひとつ しつもん いいですか?\pこんかいの バトルの かんそうを\nひとことで あらわすと\lどんな ことばに なりますか?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "{JPN}わあ とても かっこいい!\pすてきな ひとことです!\nつぎも がんばって くださいね。\pまた おあい しましょう!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "{JPN}そうですか…\pでも むくちなのも かっこいい\nものですよね?\pまた おはなしを きかせて\nいただける ひを たのしみに して います!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "{JPN}つぎの バトルを\nたのしみに して います!$"

BravoTrainerBattleTower_Text_Intro::
	.string "{JPN}イエーイ!\nブラボートレーナーの じかんだ!\pきょうは バトルタワーに ちょうせん した\n{STR_VAR_1}さんを しょうかい するぞ!\p{STR_VAR_1}さんが つれて いったのは\nとんでもない {STR_VAR_2}だ。$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "{JPN}ふたりは {STR_VAR_1}で {STR_VAR_2}れんしょうと\nいう しんきろくを うちたてた!\lブラボー トレーナー!$"

BravoTrainerBattleTower_Text_Lost::
	.string "{JPN}ふたりは {STR_VAR_2}せんめで ついに\n{STR_VAR_1}に やぶれて しまった。\lおしかったな トレーナー!\pだが こんなに はやく {STR_VAR_1}と\nあたるとは うんが なかったな。\p{STR_VAR_1}との たたかいの かんそうを\nトレーナーに きいて みたぞ。$"

BravoTrainerBattleTower_Text_Won::
	.string "{JPN}ふたりは {STR_VAR_1}の {STR_VAR_2}を\nかんぜんに やぶって かちぬいた。\lブラボー トレーナー!\pあの {STR_VAR_1}まで たおすとは…\nしんじられない! おどろきだ!\pえいこうの しゅんかんの かんそうを\nトレーナーに きいて みたぞ。$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "{JPN}れんしょうを かさねた ふたりだが さいごの\nかべ {STR_VAR_1}の {STR_VAR_2}に\lついに やぶれて しまった。\pおしかったな トレーナー!\pだが みごとと いう ほか ない。\n{STR_VAR_1}と {STR_VAR_2}ほど ゆうめいな\lくみあわせは そう ないからな。\pこの ゆうめいな ふたりとの たたかいの\nかんそうを トレーナーに きいて みたぞ。$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "{JPN}トレーナーの こたえは こうだった。\n「まんぞく!」\pじつに さわやかな こたえでは ないか?\nブラボー トレーナー!\pまんぞくの いくまで たたかえるとは\nじつに すばらしい ことだ!\pどれほど まんぞく なのかは この ひとことで\nよく わかった。$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "{JPN}トレーナーの こたえは こうだった。\n「まんぞくして いない…」\pその ひとことを いう ときの トレーナーは\nあきらかに おちこんで いた。\pだが まんぞくの いく たたかいと いうのは\nそう かんたんでは ないよな?\pどれほど ふまん なのかは この ひとことで\nよく わかった。$"

BravoTrainerBattleTower_Text_None1::
	.string "{JPN}いない$"

BravoTrainerBattleTower_Text_None2::
	.string "{JPN}いない$"

BravoTrainerBattleTower_Text_None3::
	.string "{JPN}いない$"

BravoTrainerBattleTower_Text_None4::
	.string "{JPN}いない$"

BravoTrainerBattleTower_Text_Response::
	.string "{JPN}「{STR_VAR_1}」$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "{JPN}「{STR_VAR_1}」\nじつに いい ことばでは ないか?\p{STR_VAR_2}さんの よろこびが\nよく つたわって くる。\pさいごの {STR_VAR_3}との たたかい…\nあれは まさに「{STR_VAR_1}」と\lいう ほか ない!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "{JPN}「{STR_VAR_1}」\nじつに ぴったりでは ないか?\pさいごの {STR_VAR_3}との たたかい…\nあれは「{STR_VAR_1}」と いう ほかに\lいいようが ない!\p{STR_VAR_2}さんの くやしさが\nよく つたわって くるぞ!$"

BravoTrainerBattleTower_Text_Outro::
	.string "{JPN}ブラボー {STR_VAR_1}さん!\nブラボー {STR_VAR_2}!\p{STR_VAR_1}さんの さらなる かつやくに\nきたい したい ところだ!\pきょうは ここまで!\nそれでは また あおう!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "{JPN}わあ!\pあなたが {STR_VAR_1}を たいせつに\nして いるのが よく わかります。\pなまえは {STR_VAR_2}と いうのですね。\pおねがいが あるのですが?\pわたしは テレビの きしゃで ポケモンの\nアンケートを して いるんです。\pかんたんな しつもんに いくつか\nこたえて いただけませんか?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "{JPN}よかった! ありがとう ございます!\pでは いきますね。\nかるい きもちで こたえて ください。$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "{JPN}{STR_VAR_1}に はじめて あった とき\nどう かんじましたか?\pその ときの きもちを ひとことで\nいうと どうなりますか?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "{JPN}{STR_VAR_1}は たいせつに されて いますね。\pすきな ものに たとえるなら\nなにに なりますか?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "{JPN}この しつもんも かわいい {STR_VAR_1}に\nついてです。\p{STR_VAR_1}の どんな ところに\nひかれましたか?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "{JPN}なるほど よく わかります。\pつぎの しつもんは すこし\nむずかしいかも しれません。\pいきますね…\pあなたに とって ポケモンとは?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "{JPN}なるほど!\pふむふむ…\pわかりました!\nごきょうりょく ありがとう ございます。\pたのしくて ためになる\nおはなしでした。\pこの インタビューは テレビに でるかも\nしれません。ぜひ みて くださいね!\pでは これで。\nバイバイ!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "{JPN}そうですか…\pポケモンの ことを はなしたく なったら\nいつでも ここに いますよ!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "{JPN}インタビューで ポケモンの ことを しれる\nこの しごとが すきなんです。$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "{JPN}こんにちは {STR_VAR_1}と とても なかが\nよさそうですね。\pごぞんじですか?\nわたしは テレビの きしゃなんです。\pあちこちを まわって ポケモンの ことを\nインタビューして いるんです。\pよろしければ {STR_VAR_1}の ことを\nすこし きかせて もらえませんか?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "{JPN}わあ ありがとう ございます!\pでは {STR_VAR_1}の ことを なんでも\nきかせて ください。$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "{JPN}わあ…\nとても おもしろい おはなしです。\p{STR_VAR_1}と ほんとうに なかが\nいいんですね?\pこの おはなしなら すてきな ばんぐみに\nなりそうな きが します。\pきっと たのしい ばんぐみに して\nみせますね。\lたのしみに して いて ください。\pでは これで。\nバイバイ!$"

gTVFanClubOpinionsText00::
	.string "{JPN}わたしたちは ポケモンファンクラブ!\pほうそう ちゅうです!\pこの ばんぐみでは みなさんの いけんを\nわたしが かわりに さけびます!\lすばらしい ばんぐみでしょう?\pきょうは ポケモンファンクラブに おくった\nレポーターからの リポートを\lおとどけ します。\pさて きょうの ポケモンファンは\nいったい どなたでしょう?\p… … … … … … … …\p{STR_VAR_1}さん!\pでは {STR_VAR_1}さんが {STR_VAR_2}の\n{STR_VAR_3}を どう おもって いるか きいて みましょう。\pそして その あいの ことばを\nテレビで おおごえで さけびます!\pフー ハー!\pさあ さけびましょう!$"

gTVFanClubOpinionsText01::
	.string "{JPN}{STR_VAR_1}さんに ききました。「{STR_VAR_2}を\nはじめて みた とき どう\lおもいましたか?」\p「{STR_VAR_3}!」\pイエーイ! すばらしい さけびです!\pとおい あの ひを おもいださせて\nくれるでは ありませんか?$"

gTVFanClubOpinionsText02::
	.string "{JPN}{STR_VAR_1}さんに ききました。「{STR_VAR_2}を\nなにかに たとえるなら\lそれは…」\p… … … … … … … …\p「{STR_VAR_3}!」\pおおっと これは とても どくそうてき!\pトレーナーの {STR_VAR_2}への\nおもいの つよさが\lつたわって きますね。$"

gTVFanClubOpinionsText03::
	.string "{JPN}そして…\n{STR_VAR_1}さんは その {STR_VAR_2}の\lどこに ひかれたのでしょう?\p… … … … … … … …\p「{STR_VAR_3}!」\pおお! なんと みごとな せんげん!\pトレーナーの {STR_VAR_2}への あいが\nはっきりと つたわって きます!$"

gTVFanClubOpinionsText04::
	.string "{JPN}おや? まだ つづきが あります。\nみて みましょう!\pええと そうですね…\p{STR_VAR_1}さんに ききました。「あなたに\nとって ポケモンとは?」\p… … … … … …\p「{STR_VAR_3}!」\pブラボー!\pきょう いちばんの さけびです!\p「{STR_VAR_3}!」\pなんども おおごえで さけびたく\nなりますね!\pすばらしい さけびが でた ところで\nつぎまで おわかれの じかんです!\pさあ さいごに もう いちど さけびましょう!\nみなさん ごいっしょに…\p「{STR_VAR_3}!」$"

gTVFanClubText00::
	.string "{JPN}わたしたちは ポケモンファンクラブ!\pほうそう ちゅうです!\pきょうは ポケモンアンケートコーナーから\nはじめましょう。\pポケモンと トレーナーが おりなす はなしの\nなかから きょうは どんな おどろきの ドラマが\lわたしたちを まって いるのでしょう?\pええと…\pこれに しましょう!\pこの おてがみから いきます!\p{STR_VAR_1}さんから とどいた かわいい\n{STR_VAR_2}についての おてがみです。\p{STR_VAR_2}への あいが どれほど あつく\nつづられて いるのでしょうか!\lふむふむ…$"

gTVFanClubText01::
	.string "{JPN}おおっ!\nなんと すばらしい おてがみ!$"

gTVFanClubText02::
	.string "{JPN}きに いったので もういちど どうぞ!$"

gTVFanClubText03::
	.string "{JPN}いい おてがみは なんども\nよみたく なりますね!$"

gTVFanClubText04::
	.string "{JPN}「{STR_VAR_3}」の ところが\nこころに ひびきますね!\pきもちの こもった すばらしい\nおてがみです!$"

gTVFanClubText05::
	.string "{JPN}とくに「{STR_VAR_3}」の ところ!\p「{STR_VAR_3}」の つかいかたが すきです!$"

gTVFanClubText06::
	.string "{JPN}ところで だいじな ことでは ありませんが\n「{STR_VAR_3}」は いい ことばですね。\pさいきん わたしも「{STR_VAR_3}」を\nよく つかって いるんですよ。$"

gTVFanClubText07::
	.string "{JPN}この おてがみに てんすうを つけるなら\n{STR_VAR_3}てんです。\pつぎは もっと すごい おてがみを\nきたいして いますよ {STR_VAR_1}さん!\pおっと もう こんな じかん!\nつぎまで おわかれの じかんです!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "{JPN}おや?\nポケモンが すきなのですか?\pわたしは テレビきょくの しごとで きました。\pさいきん あった ポケモンと トレーナーの\nはなしを あつめて いるんです。\pよろしければ あなたの ことを\nきかせて もらえませんか?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "{JPN}さいきん あった ポケモンと トレーナーの\nはなしを あつめて いるんです。\pよろしければ あなたの ことを\nきかせて もらえませんか?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "{JPN}ほんとうですか?\nありがとう ございます!\pでは さいきん あった ポケモンに かんする\nおもしろい ことを なんでも\lきかせて ください。$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "{JPN}そうですか…\pおもしろい はなしが あったら\nぜひ おしえて くださいね。$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "{JPN}なんと こころ おどる おはなし!\pかならず テレビで しょうかい\nさせて いただきます。\pいつか ほうそう される はずですので\nたのしみに して いて ください。$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "{JPN}ふむむ…\nテレビばんぐみに いい はなしが きけました。\pいそいで まとめないと!$"

gTVRecentHappeningsText00::
	.string "{JPN}こんにちは さいきんの できごとの じかんです。\pポケモントレーナーに とって まいにちが\nものがたりの ような ものです。\pそんな ポケモンの ものがたりを みなさんに\nしょうかい したいと おもいます。\pきょうは トレーナーの {STR_VAR_1}さんの\nおはなしを おとどけ します。\p{STR_VAR_1}さんに さいきん なにが あったのか\nみて みましょう。\pええと…$"

gTVRecentHappeningsText01::
	.string "{JPN}ためになる おはなしでしたね?\p{STR_VAR_1}さんに さいきん なにが あったのか\nよく わかる おはなしです。\lまるで その ばに いたかの ようです!$"

gTVRecentHappeningsText02::
	.string "{JPN}「{STR_VAR_3}」その ひとことが\nはなしに ふかみを あたえて います。$"

gTVRecentHappeningsText03::
	.string "{JPN}「{STR_VAR_3}」\nこの ひとことで ばめんが うかびます。\lはなしの ぶたいが めに みえる ようです。$"

gTVRecentHappeningsText04::
	.string "{JPN}「{STR_VAR_3}」の ところが\nとても ひょうげんゆたかです。$"

gTVRecentHappeningsText05::
	.string "{JPN}{STR_VAR_1}さんは ポケモンとの すばらしい\nものがたりを きかせて くれました。\p{STR_VAR_1}さんの ものがたりは みなさんの\nこころにも きざまれた ことでしょう。\pきょうは ここまで。\nつぎも ぜひ ごらん ください。$"

gTVMassOutbreakText00::
	.string "{JPN}こんにちは!\nポケモンニュースの じかんです。\pたいへん めずらしい できごとの\nしらせが とどきました。\p{STR_VAR_1}の あたりで {STR_VAR_2}が\nたいりょうに あらわれて いると\lほうこく されて います。\pごぞんじの とおり {STR_VAR_2}は\nなかなか みつからない めずらしい\lポケモンとして しられて います。\pやせいの {STR_VAR_2}が たいりょうに\nあらわれる ふしぎな ようすを みられる\lめったに ない きかいの ようです。\pいじょう ポケモンニュースでした。$"

gTV3CheersForPokeblocksText00::
	.string "{JPN}しかい: ごきげん いかがですか。\n{POKEBLOCK}ばんざいの じかんです!\pきょうは {STR_VAR_1}さんたちが つくった\n{POKEBLOCK}を しらべます。\pさっそく グルメな ポケモン ゴクリンに\nたべさせて みましょう。\p… … … … … …\n… … … … … …$"

gTV3CheersForPokeblocksText01::
	.string "{JPN}ゴクリン: グビ! グビィ!\pしかい: けっかは とても {STR_VAR_1}!\nゴクリンは「{STR_VAR_2}!」と いって います!\pありがとう ございました {STR_VAR_3}さん!$"

gTV3CheersForPokeblocksText02::
	.string "{JPN}{STR_VAR_1}さんの ブレンドは\nもうすこし がんばれた ようです。\pうまく まわせて いれば {POKEBLOCK}は\nもっと おいしく なったでしょう。$"

gTV3CheersForPokeblocksText03::
	.string "{JPN}ゴクリン: グビ! グビィ!\pしかい: うーん… {STR_VAR_1}すぎます。\nゴクリンは「{STR_VAR_2}!」と いって います!\p{STR_VAR_3}さんの しっぱいが\nでき に ひびいた ようです…$"

gTV3CheersForPokeblocksText04::
	.string "{JPN}{STR_VAR_1}さんの がんばりが\nむだに なって しまい ざんねんです。\pつぎは {STR_VAR_2}さんの かつやくに\nきたい しましょう!$"

gTV3CheersForPokeblocksText05::
	.string "{JPN}つぎも ぜひ ごらん ください!\nあいことばは {POKEBLOCK}ばんざい!$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "{JPN}やあ こんにちは!\pわたしは {STR_VAR_1}さんの ファンなの。\n{STR_VAR_1}さんの こと どう おもう?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "{JPN}なるほど なるほど。あの トレーナーを\nそんなふうに おもって いるのね。$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "{JPN}{STR_VAR_1}さんの ことは\nすっかり わすれて しまった?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "{JPN}わたしは {STR_VAR_1}さんの ファンなの。\n{STR_VAR_1}さんの こと どう おもう?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "{JPN}{STR_VAR_1}さんの つよさは\n100てんまんてんで なんてん?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "{JPN}{STR_VAR_1}さんの ことは\nすっかり わすれて しまった?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "{JPN}なるほど!\nいちど {STR_VAR_1}さんに あって みてよ。\lきっと あなたも ファンに なるわ!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "{JPN}なるほど なるほど。\pありがとう!\nとても さんこうに なったわ。\pほかの {STR_VAR_1}さんの ファンにも\nおしえて はなしあって みるわね。$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "{JPN}もうすぐ {STR_VAR_1}さんの とくばんが\nほうそう されるのよ。\pぜひ みて ね!$"

gTVTrainerFanClubSpecialText00::
	.string "{JPN}トレーナーファンクラブ\n{STR_VAR_1}さん とくべつへん!\pホウエンじゅうの {STR_VAR_1}さんファンに\nおくる とくべつばんぐみです!\pきょうの しつもんは「みんなは {STR_VAR_1}さんを\nどう おもって いるのか?」\pトレーナーの だいひょうとして\n{STR_VAR_2}さんに きいて みました。\p「ひとことで いうと {STR_VAR_1}さんは\nどんな ひと?」\pこたえは「{STR_VAR_3}」!\pさすが {STR_VAR_2}さん!\nなんと するどい ごいけん!\p「{STR_VAR_3} {STR_VAR_1}さん」\nひびきも すばらしい!\p{STR_VAR_2}さんは {STR_VAR_1}さんの つよさも\n0から 100で つけて くれました。$"

gTVTrainerFanClubSpecialText01::
	.string "{JPN}てんすうは {STR_VAR_3}てん!\nたいへんな こうとくてんです!\p{STR_VAR_2}さんは {STR_VAR_1}さんを\nよほど たかく かって いるようです。$"

gTVTrainerFanClubSpecialText02::
	.string "{JPN}てんすうは {STR_VAR_3}てん!\nなかなか いい てんすうです。\p{STR_VAR_2}さんは {STR_VAR_1}さんを\nライバルと おもって いるようです。$"

gTVTrainerFanClubSpecialText03::
	.string "{JPN}てんすうは {STR_VAR_3}てん!\nすこし ひくめの てんすうです。\p{STR_VAR_2}さんは {STR_VAR_1}さんを\nこぶんくらいに おもって いるようです。$"

gTVTrainerFanClubSpecialText04::
	.string "{JPN}てんすうは {STR_VAR_3}てん!\nひどい てんすうです。\p{STR_VAR_2}さんは {STR_VAR_1}さんを\nしたっぱと おもって いるようです。$"

gTVTrainerFanClubSpecialText05::
	.string "{JPN}みなさん いかがでしたか!\p{STR_VAR_1}さんの あたらしい いちめんを\nしる ことが できましたね。\pさいごは {STR_VAR_2}さんの ことばで\nしめくくりましょう。\p{STR_VAR_3} {STR_VAR_1}さん!$"

gTVNameRaterText00::
	.string "{JPN}さて つづいては…\nなまえ はんてい ショーです。\pつけられた ニックネームから\nポケモンの うんせいを うらないます。\pわたしが おおくり するのは アドバイス\nそれも やくに たつ アドバイスです。\pきょう うらなうのは {STR_VAR_1}さんの\nポケモン {STR_VAR_2}の ニックネーム\l{STR_VAR_3}です。\pふむふむ…\pふむ…\nこの ニックネームは…$"

gTVNameRaterText01::
	.string "{JPN}さまざまな さいのうを かんじさせる\nニックネームです。\pこの トレーナーには ゆうきを もって\nいろいろな ことに ちょうせん して ほしい。$"

gTVNameRaterText02::
	.string "{JPN}トレーナーの なまえ {STR_VAR_1}と\nみごとに つりあう ニックネームです。\pぴったりの いきで すばらしい コンビに\nなれる ことを しめして います。$"

gTVNameRaterText03::
	.string "{JPN}こせいてきな ポケモンに ふさわしい\nニックネームです!\pうまく そだてれば この ポケモンの こせいは\nあふれるほど かがやくでしょう!$"

gTVNameRaterText04::
	.string "{JPN}ポケモンの やさしさと おもいやりを\nそだてる ニックネームです。\pうまく そだてれば この ポケモンは\nほんとうの あたたかさを みせるでしょう!$"

gTVNameRaterText05::
	.string "{JPN}これからの かつやくを かんじさせる\nたいへん りっぱな ニックネームです。\pこの ポケモンの みらいが\nたのしみで なりません。$"

gTVNameRaterText06::
	.string "{JPN}ポケモンを じょうぶで げんきに\nして くれる よい ニックネームです!\pこの ポケモンは ながく けんこうで\nたくましく いられるでしょう。$"

gTVNameRaterText07::
	.string "{JPN}ポケモンを とても かっぱつに\nして くれる よい ニックネームです!\pこの ポケモンは バトルで つよさを\nはっき する ことでしょう。$"

gTVNameRaterText08::
	.string "{JPN}ポケモンを とても みりょくてきに する\nすてきな ニックネームです!\pこの ポケモンは ポケモンコンテストで\nひとを みりょう する ことでしょう。$"

gTVNameRaterText09::
	.string "{JPN}ニックネーム {STR_VAR_1}は\n「{STR_VAR_3}」の もじが ねに なって います。\pさいしょの もじ「{STR_VAR_2}」が それを ささえ\nニックネームとしての どっしりした\lそんざいかんを うみだして います。$"

gTVNameRaterText10::
	.string "{JPN}ニックネーム {STR_VAR_1}は\nじつに ここちよい かたちを して います。\p「{STR_VAR_2}」と「{STR_VAR_3}」の もじが\nはいって いる これが すばらしい!$"

gTVNameRaterText11::
	.string "{JPN}ニックネーム {STR_VAR_1}には\nうつくしい ながれが あります。\pさいしょの もじ「{STR_VAR_2}」から「{STR_VAR_3}」への\nながれが とくに すばらしい。$"

gTVNameRaterText12::
	.string "{JPN}ほかの すばらしい ニックネームの れいも\nみて みましょうか?$"

gTVNameRaterText13::
	.string "{JPN}たとえば トレーナーの なまえ {STR_VAR_1}の\nいちぶを とって {STR_VAR_2}{STR_VAR_3}と いう\lすてきな ニックネームに する てもあります。$"

gTVNameRaterText14::
	.string "{JPN}{STR_VAR_2}{STR_VAR_3}と いう ニックネームも\nなかなか よいでしょう。$"

gTVNameRaterText15::
	.string "{JPN}ポケモンの しゅぞくめい {STR_VAR_2}を\nもとに して {STR_VAR_1}{STR_VAR_3}と いう\lニックネームに する てもあります。$"

gTVNameRaterText16::
	.string "{JPN}{STR_VAR_1}{STR_VAR_3}も よく にあう\nニックネームでしょう。$"

gTVNameRaterText17::
	.string "{JPN}けっして さけるべきなのは べつの ポケモンの\nしゅぞくめいを つかう ことです。\pたとえば {STR_VAR_2}の なまえを とって\n{STR_VAR_1}{STR_VAR_3}と つける ような ことは\lいけません。$"

gTVNameRaterText18::
	.string "{JPN}{STR_VAR_1}は じつに よい ニックネームだと\nもうしあげましょう。\pこれからも トレーナーには {STR_VAR_1}を\nあいじょうを もって そだてて ほしい。\pきょうの ばんぐみは ここまで。\nまた おあい しましょう。$"

gTVPokemonAnglerText00::
	.string "{JPN}{STR_VAR_2}つり\pアナウンサー: こんにちは! きょうは\n{STR_VAR_2}の つりかたを おききします。\pめいじんさん {STR_VAR_2}を つるには\nどうすれば いいのでしょう?\pめいじん: ん? {STR_VAR_2}を つるだと?\nそうだな あわてず じっと まつ ことだ。\lそれに つきる。\pあそこの {STR_VAR_1}が みえるか?\nあの トレーナーが いい みほんだ。\pあの トレーナーは もう {STR_VAR_3}びきも\nにがして いる。\pそれでも {STR_VAR_1}は まちつづけて いる。\nそれが {STR_VAR_2}を つる おきてだ。\pアナウンサー: なるほど…\pおおっ! {STR_VAR_1}さんが ついに\n{STR_VAR_2}を つりあげました!\pうれしさの あまり なきそうな\nかおを して います!\pあんな よろこぶ かおを みると\nわたしも つりが したく なりますね!\pみなさんも これを きっかけに\n{STR_VAR_2}つりを して みては?\pそれでは つぎの ほうそうまで\nみなさん よい つりを!$"

gTVPokemonAnglerText01::
	.string "{JPN}{STR_VAR_2}つり\pアナウンサー: こんにちは! きょうは\n{STR_VAR_2}の つりかたを おききします。\pめいじんさん {STR_VAR_2}を つるには\nどうすれば いいのでしょう?\pめいじん: ん? {STR_VAR_2}を つるだと?\nそうだな つりざおを いきおいよく\lつかう ことだ!\pあそこの {STR_VAR_1}が みえるか?\nさおの あつかいかたを みて みろ。\pあの トレーナーは もう {STR_VAR_3}びき\nれんぞくで つりあげて いる。\pアナウンサー: すごい!\nまるで あらしの ようです…\pあれほどの うでまえを みると\nわたしも つりが したく なりますね。\pみなさんも これを きっかけに\n{STR_VAR_2}つりを して みては?\pそれでは つぎの ほうそうまで\nみなさん よい つりを!$"

gTVPokemonTodayFailedText00::
	.string "{JPN}こんにちは!\pポケモンきょうの じかんです!\pおねえさん: こんにちは! みなさん きょうも\nげんきに して いますか?\pきょうは {STR_VAR_1}さんの ポケモン\n{STR_VAR_2}を みて いきましょう!\pおにいさん: そうだね!\nそうしよう!$"

gTVPokemonTodayFailedText01::
	.string "{JPN}あっ!\n{STR_VAR_1}さんと いえば…\pおねえさん ぼく あの トレーナーを\nこの めで みたんだ!\pおねえさん: あら なにを みたの?\pおにいさん: じつは {STR_VAR_2}まで\nでかける ことが あってね。\pそこで ぐうぜん {STR_VAR_1}さんに あったんだ。\n{STR_VAR_3}と いう ポケモンを\lつかまえようと して いたんだけど…$"

gTVPokemonTodayFailedText02::
	.string "{JPN}ポケモンに にげられて しまったんだ!\pむだに した モンスターボールは\nなんと {STR_VAR_2}こ!\pにげられた ときの {STR_VAR_1}さんの\nくやしそうな かおと いったら\lみせて あげたいくらいだよ!$"

gTVPokemonTodayFailedText03::
	.string "{JPN}でも {STR_VAR_1}さんは しくじって\nポケモンを たおして しまったんだ!\pむだに した モンスターボールは\nなんと {STR_VAR_2}こ!\pたおれた ときの {STR_VAR_1}さんの\nあぜんと した かおと いったら\lみせて あげたいくらいだよ!$"

gTVPokemonTodayFailedText04::
	.string "{JPN}おねえさん: ちょっと!\nそれは よく ないわ!\pひとの ふこうを わらうものでは\nありませんよ!\pかわいそうな {STR_VAR_1}さん。\nおきのどくに!\pおにいさん: たしかに そうだね!\nわらって ごめんなさい。$"

gTVPokemonTodayFailedText05::
	.string "{JPN}おねえさん: ぶふふ…\pおにいさん: ちょっと!\nいま わらったよね!\pおねえさん: えっ?!\pわらって なんて いないわ!\nほんとうよ!\pかわいそうな {STR_VAR_1}さん。\nおきのどくに!\pおにいさん: …$"

gTVPokemonTodayFailedText06::
	.string "{JPN}おねえさん: おふざけは ここまで!\nきょうの ポケモンを みて いきましょう…\pあら?\nもう じかんが ないの?\pああ!\nきょうは ポケモンを しょうかい できなかったわ!\pおにいさん: それでは また つぎかい!\pおねえさん: ちょっと わたしを おいて\nおわらせないで!$"

gTVPokemonTodaySuccessfulText00::
	.string "{JPN}こんにちは!\pポケモンきょうの じかんです!\pおねえさん: こんにちは! みなさん きょうも\nげんきに して いますか?\pきょうは {STR_VAR_1}さんの ポケモン\n{STR_VAR_2}を みて いきましょう!\pおにいさん: そうだね!\nそうしよう!$"

gTVPokemonTodaySuccessfulText01::
	.string "{JPN}おねえさん: {STR_VAR_1}さんは {STR_VAR_2}に\n{STR_VAR_3}と いう ニックネームを つけました!\p{STR_VAR_3}は たっぷり あいじょうを\nそそがれて いるようですね!$"

gTVPokemonTodaySuccessfulText02::
	.string "{JPN}おにいさん: つかまえるまでに なげた\nモンスターボールは なんと {STR_VAR_3}こ!\pさいごは {STR_VAR_2} ひとつで\nつかまえられたんだ!$"

gTVPokemonTodaySuccessfulText03::
	.string "{JPN}おねえさん: そんなに かんたんに つかまるなんて\n{STR_VAR_1}さんと {STR_VAR_2}は うんめいで\lむすばれて いたのね!$"

gTVPokemonTodaySuccessfulText04::
	.string "{JPN}おねえさん: わあ! すてき!\pでも くろうして つかまえた ポケモンほど\nトレーナーに あいされると いうから\lそれも いいのよね!$"

gTVPokemonTodaySuccessfulText05::
	.string "{JPN}おねえさん: {STR_VAR_1}さんの {STR_VAR_2}は\nきちょうな マスターボールで つかまえた\lわすれられない ポケモンなのね!\pおにいさん: わあ! それは すごい!\pおねえさん: {STR_VAR_1}さんは よほど その\n{STR_VAR_2}が ほしかったのね!$"

gTVPokemonTodaySuccessfulText06::
	.string "{JPN}おにいさん: しかも その {STR_VAR_2}に\n{STR_VAR_3}と いう ニックネームを つけるなんて…\p{STR_VAR_1}さんの トレーナーとしての\nセンスが よく わかるね。\pおねえさん: わたしも そう おもうわ!$"

gTVPokemonTodaySuccessfulText07::
	.string "{JPN}わたしなら その ニックネームは\nこんな {STR_VAR_3}に つけるかしら!\pおにいさん: おおっ! それは あたらしい\nはじまりに なるかも しれないね!$"

gTVPokemonTodaySuccessfulText08::
	.string "{JPN}{STR_VAR_1}の {STR_VAR_2}?\nぴったりだと おもわない?\pもじも ひびきも なにもかも\n{STR_VAR_1}と いう ポケモンに\lちょうど いいわ!\pおにいさん: うん たしかに そうだね!$"

gTVPokemonTodaySuccessfulText09::
	.string "{JPN}わたしの しる かぎり {STR_VAR_1}に\n{STR_VAR_2}と いう ニックネームを つけた\lトレーナーは いないわ!\pおにいさん: それだけ この トレーナーは\nニックネームの センスが いいって\lことだね!$"

gTVPokemonTodaySuccessfulText10::
	.string "{JPN}こんど ポケモンを つかまえたら\n{STR_VAR_2}と なづけようかしら。\pおにいさん: えっ? ぼくも!\nぼくも {STR_VAR_2}に するよ!$"

gTVPokemonTodaySuccessfulText11::
	.string "{JPN}おねえさん: たいへん!\nもう こんな じかん!\pみなさん きょうは ここまで。\nまた つぎかい あいましょう!\pおにいさん: つぎは きみの ポケモンが\nしゅやくかも しれないよ!$"

SmartShopper_Text_Intro::
	.string "{JPN}こんにちは!\pきょうの おかいものじょうずの じかんです。\pレポーター: みなさん おげんきですか?\pきょうは {STR_VAR_2}の おみせに\nおじゃま して います。\pさいきん なにが うれて いるのか\nしらべて みましょう。$"

SmartShopper_Text_ClerkNormal::
	.string "{JPN}てんいんさんに はなしを\nきいて みましょう。\pこんにちは しょうばいは いかがですか?\pてんいん: ええ とても じゅんちょうです。\pさいきんは {STR_VAR_2}が とくに\nよく うれて いますね。\pついこのあいだも {STR_VAR_1}と いう トレーナーが\n{STR_VAR_3}こ かって いきました。$"

SmartShopper_Text_RandomComment1::
	.string "{JPN}レポーター: その トレーナーが {STR_VAR_2}を\n{STR_VAR_3}こも? それは たいりょうですね!\pきっと {STR_VAR_1}さんは とおくへの\nながい たびに そなえて かいこんで\lいたのでしょう。\pたびには {STR_VAR_2}が\nかかせませんからね!$"

SmartShopper_Text_RandomComment2::
	.string "{JPN}レポーター: {STR_VAR_2}と いえば\nわたしも さいきん {STR_VAR_3}こ\lかった ばかりなんです。\pなにしろ {STR_VAR_2}は すばらしい どうぐですから!$"

SmartShopper_Text_RandomComment3::
	.string "{JPN}レポーター: {STR_VAR_2}を?!\nしかも {STR_VAR_3}こも?!\pそんなに かう ひとが いるとは\nおもいません でした。\pわたしなんて いちどに 1つか 2つが\nせいいっぱいです…$"

SmartShopper_Text_RandomComment4::
	.string "{JPN}レポーター: わたしも いちど {STR_VAR_2}と\nいう どうぐを どっさり かった ことが あります。\pでも かいすぎて しまって\nこうかい したんです…\pそれからは どうしても ひつような ものしか\nかわない ように して います…\pおっと!\pわたしの はなしは どうでも いいですね!$"

SmartShopper_Text_SecondItem::
	.string "{JPN}てんいん: {STR_VAR_1}さんは {STR_VAR_2}と いう\nどうぐも {STR_VAR_3}こ まとめがい されました。\pレポーター: それは かしこい。\n{STR_VAR_2}も とても いい どうぐですからね。$"

SmartShopper_Text_ThirdItem::
	.string "{JPN}てんいん: それから {STR_VAR_2}と いう\nどうぐも {STR_VAR_3}こ かって いかれました。$"

SmartShopper_Text_DuringSale::
	.string "{JPN}てんいん: しかも おおうりだしの ときでした。\nかしこい おかいものです。$"

SmartShopper_Text_OutroNormal::
	.string "{JPN}レポーター: ふむ… {STR_VAR_1}さんは かなりの\nおかいものじょうずの ようですね!\p{STR_VAR_1}さんの おかいものは ぜんぶで…\p{STR_VAR_2}¥?!\nなんと すごい きんがく!\pおっと じかんが きて しまいました!\nつぎの ほうそうで おあい しましょう!$"

SmartShopper_Text_IsVIP::
	.string "{JPN}てんいん: {STR_VAR_1}さんは まちがい なく\nとくべつな おきゃくさまです。$"

SmartShopper_Text_ClerkMax::
	.string "{JPN}てんいんさんに はなしを\nきいて みましょう。\pこんにちは しょうばいは いかがですか?\pてんいん: それが しんじられないほど\nいそがしくて たいへんなんです。\pさいきん {STR_VAR_1}と いう トレーナーが\n{STR_VAR_2}と いう どうぐを まとめがい されて。\pおみせの {STR_VAR_2}が ほとんど\nなくなって しまうほどでした。\p{STR_VAR_2}を そんなに たくさん ひつような\nおきゃくさまが いるなんて おもっても\lみません でした! はじめての ことです!\pレポーター: それは 100こや 200こ\nくらい ですか?\pてんいん: いえ もっと たくさんです!\pレポーター: なんと!\n{STR_VAR_1}さんは とくべつな おきゃくさまですね!\pてんいん: {STR_VAR_1}さんは まちがい なく\nとくべつな おきゃくさまです。$"

SmartShopper_Text_OutroMax::
	.string "{JPN}レポーター: ふむ…\nそれは おどろきです。\pしかし なぜ そんなに たくさん\nかう ひつようが あったのでしょう?\p… …\pなぞは ふかまるばかりですが きょうは\nここまでの じかんの ようです。\lつぎの ほうそうで おあい しましょう!\pそれにしても {STR_VAR_1}さんは なぞの ひとです…$"

gTVWorldOfMastersText00::
	.string "{JPN}たつじんの せかい\pみなさん こんにちは。\p{STR_VAR_1}と いう トレーナーを\nごぞんじでしょうか。\p{STR_VAR_1}さんは ポケモンを つかまえる\nたつじんとして ゆうめいです。\p{STR_VAR_1}さんの ポケモンさがしは\nじぶんの あしで さがす ことに つきます。\pある ひ その トレーナーは\n{STR_VAR_2}ほも あるいたそうです。\pその ひ つかまえた ポケモンの かずは\nなんと {STR_VAR_3}びきに たっしました!$"

gTVWorldOfMastersText01::
	.string "{JPN}この みごとな きろくは トレーナーと\n{STR_VAR_1}との あいだの しんらいが\lあってこそでしょう。$"

gTVWorldOfMastersText02::
	.string "{JPN}たつじんが その ひ さいごに つかまえた\n{STR_VAR_3}は {STR_VAR_2}の ちかくでした。\pその ポケモンは きろくほじしゃとして\nとくべつな そんざいの ようです。\pうでに じしんの ある トレーナーは ぜひ\nこの きろくに ちょうせん して ください。\pきょうは ここまで。\nつぎも ぜひ ごらん ください。$"

gTVTodaysRivalTrainerText00::
	.string "{JPN}きょうの ライバルトレーナー!\pポケモントレーナーの みなさん こんにちは!\nきょうも おげんきですか?\pきょうも いつもの ように\nライバルを ひとり みて いきましょう!$"

gTVTodaysRivalTrainerText07::
	.string "{JPN}きょうの ライバルは {STR_VAR_1}さん。\nいまは {STR_VAR_3}の あたりに いるようです。\p{STR_VAR_1}さんは これまでに ポケモンを\n{STR_VAR_2}ひき ずかんに とうろく して います。$"

gTVTodaysRivalTrainerText08::
	.string "{JPN}きょうの ライバルは {STR_VAR_1}さん。\nいまは ひみつきちに いるようです。\p{STR_VAR_1}さんは これまでに ポケモンを\n{STR_VAR_2}ひき ずかんに とうろく して います。$"

gTVTodaysRivalTrainerText09::
	.string "{JPN}きょうの ライバルは {STR_VAR_1}さんです。\p{STR_VAR_1}さんは これまでに ポケモンを\n{STR_VAR_2}ひき ずかんに とうろく して います。$"

gTVTodaysRivalTrainerText10::
	.string "{JPN}きょうの ライバルは {STR_VAR_1}さん。\nいまは れんらくせんに のって いるようです。\p{STR_VAR_1}さんは これまでに ポケモンを\n{STR_VAR_2}ひき ずかんに とうろく して います。$"

	.string "{JPN}$"

gTVTodaysRivalTrainerText01::
	.string "{JPN}バッジは いくつ もって いるのでしょう?\nこたえは {STR_VAR_1}こ!$"

gTVTodaysRivalTrainerText02::
	.string "{JPN}でも ライバルは バッジを まだ\nひとつも もって いません!$"

gTVTodaysRivalTrainerText03::
	.string "{JPN}ライバルは バトルフロンティアの シンボルを\nまだ ひとつも もって いません。$"

gTVTodaysRivalTrainerText04::
	.string "{JPN}ライバルの バトルフロンティアの シンボルを\nみて みましょう。\pきんの シンボル {STR_VAR_1}こ!\nぎんの シンボル {STR_VAR_2}こ!$"

gTVTodaysRivalTrainerText05::
	.string "{JPN}ライバルは バトルフロンティアで\nバトルポイントを {STR_VAR_1} あつめて います。$"

gTVTodaysRivalTrainerText06::
	.string "{JPN}さて あなたは {STR_VAR_1}さんと くらべて\nどうだったでしょうか?\pぼうけんは まだまだ つづきます!\pトレーナーの みなさん!\pライバルの さきを いく ように\nどんどん すすんで いきましょう!$"

TrendWatcher_Text_Intro::
	.string "{JPN}ムロタウン りゅうこう ネットワーク!\pしかい: どうも!\nムロタウンの いま イケてる はなしを\lおとどけ しますぜ。\pきょうの ゲストは ムロタウンの ことなら\nなんでも しって いると いう\lごろうじんです。\pろうじん: よろしくの。\pしかい: さっそく ほんだいに いきましょう。\pムロタウンの みなさんが いま もりあがって\nいるのは なんですかい?\pろうじん: {STR_VAR_1} {STR_VAR_2}じゃ。\pしかい: {STR_VAR_1} {STR_VAR_2}\nって いうんですかい?\pろうじん: いや。\p{STR_VAR_1} {STR_VAR_2}は\nまったく はやらなかったのう。\pその はなしを ききたいかね?\pしかい: いや けっこうです。ぼくらが しりたいのは\nいま はやって いる ものでして…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTaughtMePhrase::
	.string "{JPN}ろうじん: {STR_VAR_1} {STR_VAR_2}は\nミシロタウンの {STR_VAR_3}が\lりゅうこうだと おしえて くれたんじゃが…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "{JPN}ろうじん: {STR_VAR_1} {STR_VAR_2}は\nミシロタウンの {STR_VAR_3}が\lりゅうこうだと おしえて くれたんじゃが…$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "{JPN}まるで だめじゃった。\p{STR_VAR_1} {STR_VAR_2}まつり!\p{STR_VAR_1} {STR_VAR_2}たいかい!\pせいいっぱい みんなに おしえたんじゃが\nだめじゃった…\p{STR_VAR_1}の ところが よく\nなかったのかも しれん…\pしかい: あの すみません いま はやって いる\nものを おききしたいのですが…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTellMeBigger::
	.string "{JPN}ろうじん: {STR_VAR_3}!\nあの {STR_VAR_1} {STR_VAR_2}より\lすごい ものを おしえて くれんか!$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "{JPN}ろうじん: {STR_VAR_3}!\nあの {STR_VAR_1} {STR_VAR_2}より\lすごい ものを おしえて くれんか!$"

TrendWatcher_Text_Outro::
	.string "{JPN}しかい: …ええと… と いう わけで\nイケてる みなさん おわかりですかい!\p{STR_VAR_1} {STR_VAR_2}は…ええと…\nムロタウンでは はやらなかった!\pじかんです それでは また!\pろうじん: {STR_VAR_1} {STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "{JPN}ホウエン おたからちょうさたい!\pみなさん こんにちは!\nさいきん ひみつの どうぐは みつけましたか?\pいつもの ように あちこちからの もくげき\nじょうほうを しらべて いきましょう!\pまずは おてがみから。\n「{STR_VAR_1}を はっけん!」と あります。$"

gTVHoennTreasureInvestigatorsText01::
	.string "{JPN}これは しらべて みなければ!\nよんで みましょう。\p…ちょうさたいの みなさん\nおげんきですか。\pさいきん {STR_VAR_3}の あたりで\n{STR_VAR_2}さんを みかけました。\pその トレーナーは {STR_VAR_1}と いう どうぐを\nみつけて いました。うらやましい かぎりです。\p…いやあ やりましたね {STR_VAR_2}さん!\pみなさんも これを きっかけに\nダウジングマシンで さがして みましょう!\pみなさんからの わくわくする しらせを\nまって います!$"

gTVHoennTreasureInvestigatorsText02::
	.string "{JPN}これは しらべて みなければ!\nよんで みましょう。\p…ちょうさたいの みなさん\nおげんきですか。\pさいきん れんらくせんで {STR_VAR_2}さんを みかけました。\pその トレーナーは {STR_VAR_1}と いう どうぐを\nみつけて いました。うらやましい かぎりです。\p…いやあ やりましたね {STR_VAR_2}さん!\pみなさんも これを きっかけに\nダウジングマシンで さがして みましょう!\pみなさんからの わくわくする しらせを\nまって います!$"

gTVFindThatGamerText00::
	.string "{JPN}あの ゲーマーを さがせ!\pゲーマーの みなさん!\n{STR_VAR_2}の ちょうしは いかがですか?\pいつもの ように ゲームコーナーを おとずれた\nめずらしい トレーナーに スポットを\lあてて いきましょう!\pきょうの ナンバーワン ゲーマーは…\n{STR_VAR_1}さん!$"

gTVFindThatGamerText01::
	.string "{JPN}{STR_VAR_1}さんは {STR_VAR_2}で あそんで\nめずらしくも {STR_VAR_3}コインを かせぎました。\p「{STR_VAR_1}さんが きた ときは コインを\nじゅうぶん よういして おかないと」\pゲームコーナーの てんいんさんは そう\nつぶやいて いるそうです!\pみなさんも ゲームコーナーで {STR_VAR_2}を\nあそぶ ときは {STR_VAR_1}さんの ように\lコインに きを つけましょう。\pこうふんを かんじる ゲームコーナーから\nおおくり しました!\pきょうは ここまで!$"

gTVFindThatGamerText02::
	.string "{JPN}{STR_VAR_1}さんは {STR_VAR_2}で あそんで\n{STR_VAR_3}コインを うしないました。\p「{STR_VAR_1}さんが くると コインの\nうりあげが のびる みたいです」\pゲームコーナーの てんいんさんは そう\nいって いるそうです!$"

gTVFindThatGamerText03::
	.string "{JPN}みなさんも ゲームコーナーで {STR_VAR_2}を\nあそぶ ときは {STR_VAR_1}さんの ように\lコインに きを つけましょう。\pこうふんを かんじる ゲームコーナーから\nおおくり しました!\pきょうは ここまで!$"

gTVBreakingNewsText00::
	.string "{JPN}ニュース そくほう テレビ!$"

gTVBreakingNewsText01::
	.string "{JPN}{STR_VAR_1}さんが めずらしい\n{STR_VAR_2}を ゲット!\p{STR_VAR_3}の ちかくから\nちゅうけい して います!\pさきほど ここで {STR_VAR_1}さんが めずらしい\n{STR_VAR_2}を つかまえました!$"

gTVBreakingNewsText02::
	.string "{JPN}{STR_VAR_1}さんは めずらしい {STR_VAR_2}に\nであった とき ポケモンの {STR_VAR_3}を\lくりだしました。$"

gTVBreakingNewsText03::
	.string "{JPN}この たたかいで トレーナーが なげた\nモンスターボールは {STR_VAR_1}こ。\pさいごに つかった {STR_VAR_2}で\nめずらしい ポケモンは つかまりました。$"

gTVBreakingNewsText04::
	.string "{JPN}その しゅんかん {STR_VAR_2}には\n{STR_VAR_1}さんの かちどきの さけびが\lひびきわたりました。\p{STR_VAR_1}さんが すこし うらやましい。\nわたしも さけんで みたい ものです。\p…しあわせな げんばからの\nちゅうけいでした!$"

gTVBreakingNewsText05::
	.string "{JPN}{STR_VAR_1}さんが めずらしい\n{STR_VAR_2}を にがす!\p{STR_VAR_3}の ちかくから\nちゅうけい して います!\pここで {STR_VAR_1}さんは めずらしい\n{STR_VAR_2}を にがして しまいました!$"

gTVBreakingNewsText06::
	.string "{JPN}{STR_VAR_1}さんは めずらしい {STR_VAR_2}に\nであった とき ポケモンの {STR_VAR_3}を\lくりだしました。$"

gTVBreakingNewsText07::
	.string "{JPN}トレーナーは {STR_VAR_2}に\n{STR_VAR_1}と いう わざを つかわせました。\pそのつもりは なかったのに めずらしい\nポケモンを たおして しまったのです…$"

gTVBreakingNewsText12::
	.string "{JPN}ところが {STR_VAR_1}さんは めずらしい\n{STR_VAR_2}を まえに あわてて しまいました。\pこんらん した トレーナーは {STR_VAR_3}に\nこうげきを めいじたのです。\pそのつもりは なかったのに めずらしい\nポケモンを たおして しまいました。$"

gTVBreakingNewsText08::
	.string "{JPN}その しゅんかん {STR_VAR_2}には\n{STR_VAR_1}さんの くやしさの さけびが\lひびきわたりました…$"

gTVBreakingNewsText09::
	.string "{JPN}ところが {STR_VAR_1}さんは モンスターボールを\nきらして しまった ようです。\pトレーナーは めずらしい {STR_VAR_2}との\nたたかいを あきらめる ほか ありません でした。\pその しゅんかん {STR_VAR_3}には\n{STR_VAR_1}さんの くやしさの さけびが\lひびきわたりました…$"

gTVBreakingNewsText10::
	.string "{JPN}ところが {STR_VAR_2}は とつぜん\nにげて しまいました。\pその しゅんかん {STR_VAR_3}には\n{STR_VAR_1}さんの くやしさの さけびが\lひびきわたりました…$"

gTVBreakingNewsText11::
	.string "{JPN}{STR_VAR_1}さんの きもちが よく わかります。\nわたしも さけびたく なりますね。\p…かなしい げんばからの\nちゅうけいでした!$"

gTVSecretBaseVisitText00::
	.string "{JPN}みなさん こんにちは!\nきょうも ひみつきち ほうもんの\lじかんが やって きました。\pきょうは {STR_VAR_1}さんの\nひみつきちを たずねます。\p{STR_VAR_1}さんは ひみつきちを どんなふうに\nかざって いるのでしょうか?\pさっそく みて みましょう!\n… … … … … …$"

gTVSecretBaseVisitText01::
	.string "{JPN}おお!\nなんと すばらしい!\pこの {STR_VAR_2}…\nここに あるとは おもいも\lよりません でした!$"

gTVSecretBaseVisitText02::
	.string "{JPN}おお!\nなんと みごとな!\pかぐも インテリアも\nひとつも ありません!\pこの だいたんさは なみの ひとには\nまねの できない ことです!\pシンプルですが やせいみが\nあふれて います!\pおみそれ しました {STR_VAR_1}さん。\nあなたしか いません!$"

gTVSecretBaseVisitText03::
	.string "{JPN}おお! わかりました!\nはっきりと わかりましたよ!\pこの {STR_VAR_2}が ここに ある…\nじつに こうかてきな メッセージです!$"

gTVSecretBaseVisitText04::
	.string "{JPN}おお! わかりました!\nはっきりと わかりましたよ!\pこの ばしょは あえて なにも おかずに\nあけて あるのですね!\pじつに こうかてきな メッセージです!$"

gTVSecretBaseVisitText05::
	.string "{JPN}ふぅー!\p{STR_VAR_2}と {STR_VAR_3}の\nくみあわせ!\pまさに ゆめの ような コンビと\nいう ほか ありません!$"

gTVSecretBaseVisitText06::
	.string "{JPN}ふぅー!\pこの {STR_VAR_2}を\nここに おくとは…\pひみつきち ぜんたいを つつむ ような\nそんざいかんが あります!$"

gTVSecretBaseVisitText07::
	.string "{JPN}ふぅー!\pここには なにも おかれて いません。\pこの なにも ない くうかんが ひみつきち\nぜんたいに えいきょうを あたえて います。$"

gTVSecretBaseVisitText08::
	.string "{JPN}おお!\n{STR_VAR_1}さんが やって きました!\lしょうぶを いどんで みましょう!\p… … … … … …\n… … … … … …$"

gTVSecretBaseVisitText09::
	.string "{JPN}はあ…\n{STR_VAR_1}さんには かないません。\pあの トレーナーの ポケモンは まさに\nチャンピオンの なに ふさわしい ものでした。\p{STR_VAR_1}さんの トレーナーとしての つよさを\nじゅうぶんに しめして いました。\p{STR_VAR_2}が {STR_VAR_3}と いう わざを\nおぼえて いたとは…\p{STR_VAR_1}さんが どんな トレーナーか\nよく わかりますね。\pたいへん べんきょうに なりました!$"

gTVSecretBaseVisitText10::
	.string "{JPN}ひええ!\n{STR_VAR_1}さんには かないません。\pあの トレーナーの ポケモンは\nとんでもなく つよかった!\p{STR_VAR_1}さんの トレーナーとしての ねばりづよさを\nじゅうぶんに しめして いました。\p{STR_VAR_2}が {STR_VAR_3}と いう わざを\nおぼえて いたとは…\p{STR_VAR_1}さんが どんな トレーナーか\nよく わかりますね。\pたいへん べんきょうに なりました!$"

gTVSecretBaseVisitText11::
	.string "{JPN}ふぅー!\n{STR_VAR_1}さんには かないません。\pあの トレーナーの ポケモンは バランスよく\nそだてられて いるのが よく わかりました。\p{STR_VAR_1}さんの トレーナーとしての こまやかさを\nじゅうぶんに しめして いました。\p{STR_VAR_2}が {STR_VAR_3}と いう わざを\nおぼえて いたとは…\p{STR_VAR_1}さんが どんな トレーナーか\nよく わかりますね。\pたいへん べんきょうに なりました!$"

gTVSecretBaseVisitText12::
	.string "{JPN}おやおや!\n{STR_VAR_1}さんには かないません。\pあの トレーナーの ポケモンは これからの\nせいちょうが たのしみな ものばかりでした。\p{STR_VAR_1}さんの きぼうと ゆめが\nそこに あらわれて いました。\p{STR_VAR_2}が {STR_VAR_3}と いう わざを\nおぼえて いたとは…\p{STR_VAR_1}さんが どんな トレーナーか\nよく わかりますね。\pたいへん べんきょうに なりました!$"

gTVSecretBaseVisitText13::
	.string "{JPN}いやはや なんとも すばらしい\nひみつきちでした!\pみなさんも きかいが あれば ぜひ\n{STR_VAR_1}さんの ひみつきちを たずねて ください。\pそれでは つぎまで さようなら!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "{JPN}わくわく します!\nドラマチックです!\pポケモンくじ とうせんしゃ\nそくほうです!\pこんにちは! ミナモデパート 1かいの\nポケモンくじコーナーから\lちゅうけいで おおくり して\lいます!\pきょうも いつもの ように しあわせな\nトレーナーが あらわれました!\pその トレーナーの なまえは…\n{STR_VAR_1}さん!\p{STR_VAR_1}さんは {STR_VAR_2}とうしょうに あたり\n{STR_VAR_3}を てに いれました!\p{STR_VAR_1}さん!\nおめでとう ございます!\pみなさんも みて いるだけで なく\nぜひ ちょうせん して ください!\pミナモデパート いちどう みなさまの\nごらいてんを おまち して おります!\pホウエンいちの しなぞろえを ほこる\nミナモデパートから\lちゅうけいで おおくり\lしました。$"

gTVThePokemonBattleSeminarText00::
	.string "{JPN}ポケモンバトルセミナー!\pバトルを しらべて ほかの ひとから\nなにを まなべるかを かんがえます。\pきょうの れいは {STR_VAR_1}さんの\nバトルです。\p{STR_VAR_1}さんの {STR_VAR_2}は\n{STR_VAR_3}と たたかって いました…$"

gTVThePokemonBattleSeminarText01::
	.string "{JPN}そして {STR_VAR_2}に {STR_VAR_3}と いう\nわざを つかったのです…\pうーん… {STR_VAR_1}さん!\nそれは いけません!$"

gTVThePokemonBattleSeminarText02::
	.string "{JPN}その わざの ほかに トレーナーの\n{STR_VAR_1}が おぼえて いたのは$"

gTVThePokemonBattleSeminarText03::
	.string "{JPN}{STR_VAR_1}と {STR_VAR_2}\nそして {STR_VAR_3}でした。$"

gTVThePokemonBattleSeminarText04::
	.string "{JPN}{STR_VAR_1}と\n{STR_VAR_2}でした。$"

gTVThePokemonBattleSeminarText05::
	.string "{JPN}{STR_VAR_2}でした。$"

gTVThePokemonBattleSeminarText06::
	.string "{JPN}では この ばめんで トレーナーは\nなにを つかうべきだったのでしょう?\p… … … … … …\n{STR_VAR_1}です!\p{STR_VAR_1}の ほうが {STR_VAR_2}よりも\nあきらかに よかったはずです。\pみなさんも この れいから まなんで\nかしこく たたかいましょう!\pそれでは つぎまで さようなら!$"

gTVTrainerFanClubText00::
	.string "{JPN}みんな そろって!\nトレーナーファンクラブ!\pしかい: みなさん ちょうしは どうですか?\nきょうは だいにんきの トレーナー {STR_VAR_1}さんの\lファンの みなさんに あつまって もらいました!\pファン: うおおおおお!\pファン: {STR_VAR_1}さん!\pしかい: みなさん!\n{STR_VAR_1}さんの ことは すきですか?!\pファン: {STR_VAR_1}さん だいすき!\pしかい: {STR_VAR_1}さんの どこが\nすきなんですか?!$"

gTVTrainerFanClubText01::
	.string "{JPN}ファン: モンスターボールを なげる\nかっこいい すがた!$"

gTVTrainerFanClubText02::
	.string "{JPN}ファン: かわいらしい はしりかた!$"

gTVTrainerFanClubText03::
	.string "{JPN}ファン: くるしい ときほど つよく なる\nところ!$"

gTVTrainerFanClubText04::
	.string "{JPN}ファン: ポケモンに ついての\nものしりな ところ!$"

gTVTrainerFanClubText05::
	.string "{JPN}ファン: すべての ポケモンに やさしい\nところ!$"

gTVTrainerFanClubText06::
	.string "{JPN}ファン: みごとな じてんしゃの\nのりこなしかた!$"

gTVTrainerFanClubText07::
	.string "{JPN}ファン: どうぐを かう ときの\nみごとな かいっぷり!$"

gTVTrainerFanClubText08::
	.string "{JPN}ファン: ポケモンに ニックネームを つける\nすてきな センス!$"

gTVTrainerFanClubText09::
	.string "{JPN}ファン: ひみつきちを かざる\nしゃれた センス!$"

gTVTrainerFanClubText10::
	.string "{JPN}ファン: わざマシンを だいたんに つかう\nところ!$"

gTVTrainerFanClubText11::
	.string "{JPN}しかい: ごらんの とおり {STR_VAR_1}さんは\nいま おおにんき! あつすぎます!\p{STR_VAR_1}さんの ファンには\nとくべつな あいことばが あるんです!\pしかい: わたしが {STR_VAR_1}と いったら\nみなさんは…\pファン: {STR_VAR_2}!\pファン: {STR_VAR_3}!\pファン: {STR_VAR_2}!\pファン: {STR_VAR_3}!\pしかい: そうです だれかが\n「{STR_VAR_1}」と いったら…\p「{STR_VAR_2} {STR_VAR_3}!」と\nかえすんです!\pじつに どくとくな ひびきです!\n{STR_VAR_1}さんの ファンが ふえる りゆうが\lよく わかりますね!\pテレビの まえの みなさんも いっしょに!\nせーの!\pしかい: わたしが {STR_VAR_1}と いったら\nみなさんは…\pファン: {STR_VAR_2}!\pファン: {STR_VAR_3}!\pファン: {STR_VAR_2}!\pファン: {STR_VAR_3}!\pしかい: {STR_VAR_1}さんの ねっきょうてきな ファンの\nみなさん ありがとう ございました!\lきょうは ここまで! また あいましょう!\pしかい: わたしが {STR_VAR_1}と いったら\nみなさんは…\pファン: {STR_VAR_2}!\pファン: {STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "{JPN}かわいい こを さがせ!\nリボンの ポケモン!\pかわいい みなさん こんにちは!\pきっと おわかりでしょうが リボンを つけた\nポケモンは それはもう すてきなんです!\pきょうは まちを さんぽ して いる ときに\nみかけた すてきな ポケモンを\lしょうかい します。\pきょうの かわいい ポケモンは\n{STR_VAR_1}さんの {STR_VAR_2}です。$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "{JPN}{STR_VAR_2}が つけて いる リボンの\nかずは {STR_VAR_3}こ。\p{STR_VAR_1}さんが どれほど この ポケモンを\nかわいがって いるかが よく わかります。$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{JPN}{STR_VAR_2}は なんと {STR_VAR_3}この\nリボンを つけて います!\p{STR_VAR_1}さんの この ポケモンへの\nおもいいれの ふかさが つたわります!$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{JPN}{STR_VAR_2}は しんじられない ことに\n{STR_VAR_3}この リボンを つけて います!\p{STR_VAR_1}さんの コレクターとしての\nてっていぶりが よく わかります!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "{JPN}{STR_VAR_2}が つけて いる たくさんの\nリボンを くわしく みて いきましょう。$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "{JPN}チャンピオンリボンが とくに\nすてきです。\p{STR_VAR_2}は でんどういりした ときに\nもらいました。\p{STR_VAR_2}の ゆうかんさを\nみごとに ひきだして います。\p{STR_VAR_2}と チャンピオンリボン!\nこの くみあわせは こうかばつぐん!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "{JPN}かっこよさリボンが とくに\nすてきです。\p{STR_VAR_2}は かっこよさコンテストに かって\nもらいました。\p{STR_VAR_2}の かっこよさを\nみごとに ひきだして います。\p{STR_VAR_2}と かっこよさリボン!\nこの くみあわせは こうかばつぐん!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "{JPN}うつくしさリボンが とくに\nすてきです。\p{STR_VAR_2}は うつくしさコンテストに かって\nもらいました。\p{STR_VAR_2}の うつくしさを\nみごとに ひきだして います。\p{STR_VAR_2}と うつくしさリボン!\nこの くみあわせは こうかばつぐん!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "{JPN}かわいさリボンが とくに\nすてきです。\p{STR_VAR_2}は かわいさコンテストに かって\nもらいました。\p{STR_VAR_2}の かわいさを\nみごとに ひきだして います。\p{STR_VAR_2}と かわいさリボン!\nこの くみあわせは こうかばつぐん!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "{JPN}かしこさリボンが とくに\nすてきです。\p{STR_VAR_2}は かしこさコンテストに かって\nもらいました。\p{STR_VAR_2}の かしこさを\nみごとに ひきだして います。\p{STR_VAR_2}と かしこさリボン!\nこの くみあわせは こうかばつぐん!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "{JPN}たくましさリボンが とくに\nすてきです。\p{STR_VAR_2}は たくましさコンテストに かって\nもらいました。\p{STR_VAR_2}の たくましさを\nみごとに ひきだして います。\p{STR_VAR_2}と たくましさリボン!\nこの くみあわせは こうかばつぐん!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "{JPN}しょうりリボンが とくに\nすてきです。\p{STR_VAR_2}は バトルタワーでの かつやくで\nもらいました。\p{STR_VAR_2}の つよさを\nみごとに ひきだして います。\p{STR_VAR_2}と しょうりリボン!\nこの くみあわせは こうかばつぐん!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "{JPN}せいはリボンが とくに\nすてきです。\p{STR_VAR_2}は バトルタワーでの かつやくで\nもらいました。\p{STR_VAR_2}の とてつもない つよさを\nみごとに ひきだして います。\p{STR_VAR_2}と せいはリボン!\nこの くみあわせは こうかばつぐん!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "{JPN}アーティストリボンが とくに\nすてきです。\p{STR_VAR_2}は えの モデルに なって\nもらいました。\p{STR_VAR_2}の アイドルのような みりょくを\nみごとに ひきだして います。\p{STR_VAR_2}と アーティストリボン!\nこの くみあわせは こうかばつぐん!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "{JPN}がんばりやリボンが とくに\nすてきです。\p{STR_VAR_2}は とくに よく はたらいて\nもらいました。\p{STR_VAR_2}の こんじょうを\nみごとに ひきだして います。\p{STR_VAR_2}と がんばりやリボン!\nこの くみあわせは こうかばつぐん!$"

TVSpotTheCuties_Text_Outro::
	.string "{JPN}…はあ…\pリボンと ポケモン…\nなんて すばらしい くみあわせ!\pきぜつ する まえに\nみなさん さようなら!$"

gTVPokemonNewsBattleFrontierText00::
	.string "{JPN}こんにちは!\nポケモンニュースの じかんです。\pバトルフロンティアから こころ おどる\nニュースが とどきました。$"

gTVPokemonNewsBattleFrontierText01::
	.string "{JPN}トレーナーの {STR_VAR_1}さんが バトルタワーの\nシングルバトルルームへの ちょうせんで\l{STR_VAR_2}れんしょうと いう しんきろくを\lうちたてました。\p{STR_VAR_1}さんに はくしゅを!$"

gTVPokemonNewsBattleFrontierText02::
	.string "{JPN}トレーナーの {STR_VAR_1}さんが バトルタワーの\nダブルバトルルームへの ちょうせんで\l{STR_VAR_2}れんしょうと いう しんきろくを\lうちたてました。\p{STR_VAR_1}さんに はくしゅを!$"

gTVPokemonNewsBattleFrontierText03::
	.string "{JPN}トレーナーの {STR_VAR_1}さんが バトルタワーの\nマルチバトルルームへの ちょうせんで\l{STR_VAR_2}れんしょうと いう しんきろくを\lうちたてました。\p{STR_VAR_1}さんに はくしゅを!$"

gTVPokemonNewsBattleFrontierText04::
	.string "{JPN}トレーナーの {STR_VAR_1}さんが バトルタワーの\nつうしんマルチバトルルームへの ちょうせんで\l{STR_VAR_2}れんしょうと いう しんきろくを\lうちたてました。\p{STR_VAR_1}さんに はくしゅを!$"

gTVPokemonNewsBattleFrontierText05::
	.string "{JPN}トレーナーの {STR_VAR_1}さんが バトルドームの\nシングルバトルたいかいで\l{STR_VAR_2}かい れんぞく ゆうしょうと いう\lしんきろくを うちたてました。\p{STR_VAR_1}さんに はくしゅを!$"

gTVPokemonNewsBattleFrontierText06::
	.string "{JPN}トレーナーの {STR_VAR_1}さんが\nバトルドームの ダブルバトルたいかいで\l{STR_VAR_2}かい れんぞく ゆうしょうと いう しんきろくを\lうちたてました。\p{STR_VAR_1}さんに はくしゅを!$"

gTVPokemonNewsBattleFrontierText07::
	.string "{JPN}トレーナーの {STR_VAR_1}さんが\nバトルファクトリーの こうかんシングルへの\lちょうせんで {STR_VAR_2}れんしょうの しんきろくを\lうちたてました。\p{STR_VAR_1}さんに はくしゅを!$"

gTVPokemonNewsBattleFrontierText08::
	.string "{JPN}トレーナーの {STR_VAR_1}さんが\nバトルファクトリーの こうかんダブルへの\lちょうせんで {STR_VAR_2}れんしょうの しんきろくを\lうちたてました。\p{STR_VAR_1}さんに はくしゅを!$"

gTVPokemonNewsBattleFrontierText09::
	.string "{JPN}トレーナーの {STR_VAR_1}さんが\nバトルパイクへの ちょうせんで\l{STR_VAR_2}へやを クリアする しんきろくを\lうちたてました。\p{STR_VAR_1}さんに はくしゅを!$"

gTVPokemonNewsBattleFrontierText10::
	.string "{JPN}トレーナーの {STR_VAR_1}さんが\nバトルアリーナの ノックアウトたいかいで\l{STR_VAR_2}れんしょうの しんきろくを\lうちたてました。\p{STR_VAR_1}さんに はくしゅを!$"

gTVPokemonNewsBattleFrontierText11::
	.string "{JPN}トレーナーの {STR_VAR_1}さんが\nバトルパレスの シングルバトルホールへの\lちょうせんで {STR_VAR_2}れんしょうの しんきろくを\lうちたてました。\p{STR_VAR_1}さんに はくしゅを!$"

gTVPokemonNewsBattleFrontierText12::
	.string "{JPN}トレーナーの {STR_VAR_1}さんが\nバトルパレスの ダブルバトルホールへの\lちょうせんで {STR_VAR_2}れんしょうの しんきろくを\lうちたてました。\p{STR_VAR_1}さんに はくしゅを!$"

gTVPokemonNewsBattleFrontierText13::
	.string "{JPN}トレーナーの {STR_VAR_1}さんが\nバトルピラミッドへの ちょうせんで\l{STR_VAR_2}かいを クリアする しんきろくを\lうちたてました。\p{STR_VAR_1}さんに はくしゅを!$"

gTVPokemonNewsBattleFrontierText14::
	.string "{JPN}そして 3びきの ポケモン {STR_VAR_1}\n{STR_VAR_2} {STR_VAR_3}にも!\pきろくを ぬりかえた かつやく\nおめでとう ございます!$"

gTVPokemonNewsBattleFrontierText15::
	.string "{JPN}そして 2ひきの ポケモン {STR_VAR_1}と\n{STR_VAR_2}にも!\pきろくを ぬりかえた かつやく\nおめでとう ございます!$"

gTVPokemonNewsBattleFrontierText16::
	.string "{JPN}そして 4ひきの ポケモン {STR_VAR_1}!\p{STR_VAR_2}!\p{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "{JPN}そして {STR_VAR_1}!\pきろくを ぬりかえた かつやく\nおめでとう ございます!$"

gTVPokemonNewsBattleFrontierText18::
	.string "{JPN}{STR_VAR_1}さんと ちゅうじつな ポケモンたちの\nさらなる しんきろくに\lきたい しましょう!\pいじょう ポケモンニュースでした!$"

gTVWhatsNo1InHoennTodayText00::
	.string "{JPN}きょうの ホウエン ナンバーワンは?\nはい その じかんが やって きました!\pみなさん こんにちは! なにごとにも\nぜんりょくで とりくんで いますか?\pきょう いちばん がんばった トレーナーを\nみて いきましょう!\pきょうの ナンバーワンは なんと\n{STR_VAR_1}さんです!$"

gTVWhatsNo1InHoennTodayText01::
	.string "{JPN}{STR_VAR_1}さんは 1にちで ゲームコーナーの\nスロットを {STR_VAR_2}かい まわしました。\pあそびながら {STR_VAR_1}さんは\n「わたしの ときは リールが うごきも\lしない…」と つぶやいて いたとか。\lおもしろい ですね?$"

gTVWhatsNo1InHoennTodayText02::
	.string "{JPN}{STR_VAR_1}さんは 1にちで ゲームコーナーの\nルーレットを {STR_VAR_2}かい\lあそびました。\pあそびながら {STR_VAR_1}さんは\n「たまに まかせる!」と さけんで いました。\pトレーナーの めは するどく かおには\nしゅうちゅうりょくが あふれて いました。$"

gTVWhatsNo1InHoennTodayText03::
	.string "{JPN}{STR_VAR_1}さんは 1にちで やせいの ポケモンと\n{STR_VAR_2}かいも たたかいました!\p{STR_VAR_1}さんの ポケモンは くらべものに\nならないほど つよく なった ようです。\pいつでも どこでも どんな ときでも\nたたかいたそうに して います!$"

gTVWhatsNo1InHoennTodayText04::
	.string "{JPN}{STR_VAR_1}さんは たった 1にちで きのみブレンダーを\n{STR_VAR_2}かいも まわしました!\pさいごの ほうは さすがの {STR_VAR_1}さんも\nめが まわって いた ようです。\pまるで パッチールの ように\nふらふらして いたとか!$"

gTVWhatsNo1InHoennTodayText05::
	.string "{JPN}{STR_VAR_1}さんは たった 1にちで きのみを\n{STR_VAR_2}こも うえました!\pおかげで {STR_VAR_1}さんの ふくは\nどろだらけに なって しまいました。\pトレーナーが うえた ばしょには かぞえきれない\nほどの はなが さきほこって います。\pその はなは ひとの こころを\nなごませると いわれて います。$"

gTVWhatsNo1InHoennTodayText06::
	.string "{JPN}{STR_VAR_1}さんは たった 1にちで きのみを\n{STR_VAR_2}こも つみました!\p{STR_VAR_1}さんの バッグは きのみで いっぱいに\nなって しまい そのあと あるくのにも\lくろうしたとか!$"

gTVWhatsNo1InHoennTodayText07::
	.string "{JPN}{STR_VAR_1}さんは たった 1にちで\nバトルポイントを {STR_VAR_2} かせぎました!\pそのあと {STR_VAR_1}さんは バトルポイントを\nかっこいい どうぐと こうかんするか\lしゃれた インテリアと こうかんするか\lなやんで いたそうです。\pなやみながらも にこにこして いたと\nつたえられて います。$"

gTVWhatsNo1InHoennTodayText08::
	.string "{JPN}いやはや たいした ものです!\p{STR_VAR_1}さん!\nあなたが きょうの ナンバーワンです!\pみなさんも {STR_VAR_1}さんを みならって!\nまいにち ナンバーワンに なれますよ!$"

TVSecretBaseSecrets_Text_Intro::
	.string "{JPN}ひみつきちの ひみつ!\pトレーナーたちは ひみつきちの なかで\nなにを して いるのでしょう?\pきょうは {STR_VAR_1}さんの ひみつきちを\nしらべます。\pおや? {STR_VAR_2}さんが あそびに\nきたようです。\pのぞいて みましょう!\p{STR_VAR_2}さんは なにを するのでしょう?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "{JPN}{STR_VAR_2}さんは つぎに なにを するのでしょう?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "{JPN}さて {STR_VAR_2}さんは なにを するのでしょう?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "{JPN}けっきょく {STR_VAR_2}さんは {STR_VAR_1}さんの\nひみつきちを {STR_VAR_3}ほ あるいてから\lでて いきました。$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "{JPN}うーん…\p{STR_VAR_1}さんの ひみつきちは {STR_VAR_2}さんの\nきょうみを ひかなかった ようです…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{JPN}{STR_VAR_2}さんは {STR_VAR_1}さんの ひみつきちを\nじゅうぶんに たのしんだ ようです。$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{JPN}{STR_VAR_2}さんは {STR_VAR_1}さんの\nひみつきちの だいファンに\lなった ようです。$"

TVSecretBaseSecrets_Text_Outro::
	.string "{JPN}みなさんも {STR_VAR_1}さんの ひみつきちを\nのぞいて みては いかがでしょう。\pつぎも べつの ひみつきちを たずねます!\nごらん いただき ありがとう ございました!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "{JPN}おきゃくさんが とまりました!\pまったく うごきません!\p{STR_VAR_1}さんの ひみつきちは そんなに\nつまらなかったのでしょうか?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "{JPN}おきゃくさんが とまりました!\pまったく うごきません!\pつかれたのでしょうか?\nくたびれて しまったのでしょうか?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "{JPN}おきゃくさんが いすに すわりました!\nすわって います!\pあの うれしそうな かおを ごらん ください!\pあんな かおを するとは よほど\nすわりごこちの いい いすなのでしょう!$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "{JPN}おきゃくさんが ふうせんに とっしん!\pわれました!\nわあ われて しまいました!\pきゅうな おとに おきゃくさんも\nおどろいて いる ようです!$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "{JPN}おきゃくさんが テントに はいりました!\pはしりまわって います!\pおやおや はしゃいで いますね!\pテントの ひろさに おどろいて\nいる ようです!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "{JPN}おきゃくさんが うえきばちを\nしらべて います!\pおどろくほど おとなな センスを\nして いますね!$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "{JPN}おきゃくさんが きんの たてを\nしらべて います!\pおきゃくさんの めが かがやいて\nいるようです!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "{JPN}おきゃくさんが ぎんの たてを\nしらべて います!\pめを まるく して いますね!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "{JPN}おきゃくさんが ガラスの おきものを\nしらべて います!\pああっ!\pさわって います!\pゆびあとが たくさん ついて\nしまいそうです…$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "{JPN}おきゃくさんが テレビを みて います!\pテレビの だいファンの ようですね!$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "{JPN}おきゃくさんが どろだんごを ふみました!\pうれしそうに して います!$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "{JPN}…おや?\pおきゃくさんが じぶんの バッグに\nてを いれて さがして います!\p{STR_VAR_2}を ひとつ\nとりだしました!\p{STR_VAR_2}を かかげて えがおに なる\nおきゃくさんを ごらん ください!\pまるで テレビの コマーシャルの ようです!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "{JPN}おきゃくさんが クッションを つかんで…$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "{JPN}…たたきはじめました!\pストレスが たまって いるのでしょうか?$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "{JPN}…ぎゅっと だきしめました!\pなにか うれしい ことが\nあったのでしょうか?$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "{JPN}おきゃくさんが {STR_VAR_1}さんと\nはなして います!\pどうやら しょうぶを する\nようです!\pそして…\pおきゃくさんです!\nおきゃくさんが てきちで かちました!\pおきゃくさんが かちどきの ダンスを\nおどって います!$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "{JPN}おきゃくさんが {STR_VAR_1}さんと\nはなして います!\pどうやら しょうぶを する\nようです!\pそして…\p{STR_VAR_1}さんです!\nおきゃくさんの まけです!\pおきゃくさんは がっかりして います!$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "{JPN}おきゃくさんが {STR_VAR_1}さんと\nはなして います!\pどうやら しょうぶを する\nようです!\pそして…\pいえ おきゃくさんが ことわりました!\pしょうぶは なしに なった ようです!\p{STR_VAR_1}さんに みりょくを かんじなかった\nのでしょうか?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "{JPN}おきゃくさんが ポスターを じっと\nみつめて います!\pポスターが おきに めしたので\nしょうか?\p…ですが… その みつめかたには\nどこか きになる ものが あります。$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "{JPN}おきゃくさんが おとの マットを ふみました!\p…うーん…\nおかしな メロディーが できましたね!$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "{JPN}おきゃくさんが {STR_VAR_1}さんと\nはなして います!\pどうやら しょうぶを する\nようです!\pそして…\pひきわけです!\nしょうぶは つきません でした!\pふたりとも とても ざんねんそうに\nして います!$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "{JPN}おきゃくさんが まわるマットを\nふみました!\pめが まわって いる ようです!\pふらふらして います!\nあぶない!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "{JPN}おきゃくさんが すなの おきものに\nてを のばして います!\pあっ!\pくずれました!\nばらばらに なって しまいました!\pおきゃくさんは バツが わるそうに\nして います!$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "{JPN}おきゃくさんが つくえの うえを\nゆびで こすって います!\pどうやら ほこりが きに いらない\nようです!\pおどろくほど きれいずきな\nようですね!$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "{JPN}おきゃくさんが レンガを みつめて います!\pレンガの うえの ものを かんがえて\nいるのかも しれません。$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "{JPN}おきゃくさんが かたい いたの うえを\nあるいて います。\pずっと したを むいて います。\pおどろくほど おくびょうで しんちょうな\nようです!$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "{JPN}おきゃくさんが さくを じっと\nみつめて います!\pあたらしい しかけを おもいついたの\nでしょうか?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "{JPN}おきゃくさんが きらきらマットを\nふみました!\pいろいろな ポーズを\nきめて います!\pアイドルに なった きぶんに なって\nいる ようです!$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "{JPN}おきゃくさんが タイヤを じっと\nみつめて います!\pどんな くるまに つかうのか\nかんがえて いるのでしょうか?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "{JPN}おきゃくさんが だいに のぼりました!\pたかい ところから {STR_VAR_1}さんの きちを\nみわたして います!\pそして…\pさけびました!\nおきゃくさんが ほえて います!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "{JPN}おきゃくさんが こわれる とびらに\nあたまから とっしん しました!\pおおわらい して います!$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "{JPN}おきゃくさんが にんぎょうに はなしかけて います!\p…すこし こわいですね…$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "{JPN}おきゃくさんが すべりだいの はしごを\nのぼって います!\pそして…\pすべりおりました!\pとても たのしそうに して\nいますね!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "{JPN}おきゃくさんが すべりだいの はしごを\nのぼって います!\pそして…\pはしごを おりて\nしまいました!\pきゅうに こわく なったのでしょうか?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "{JPN}おきゃくさんが ジャンプマットを\nふみました!\p1かい とびました!\p2かい とびました!\pそして みごとに ちゃくち!\pおきゃくさんが はくしゅ して います!\nなんという ひとりしばい!$"

gTVSafariFanClubText00::
	.string "{JPN}サファリファンクラブ!\pレポーター: みなさん!\nサファリボールを なげて いますか?\pすごい ポケモンで いっぱいの サファリゾーンに\nわたしは きて いますよ!\pさっそく この やさしそうな サファリガイドさんに\nはなしを きいて みましょう!\pさあ おきゃくさんの トレーナーたちの\nようすは どうですか?$"

gTVSafariFanClubText01::
	.string "{JPN}ガイド: みなさん がんばって いる\nようですよ。\pとくに {STR_VAR_1}さんは たいしたものです。\pさきほども {STR_VAR_1}さんは ポケモンを\n{STR_VAR_2}ひき つかまえました。$"

gTVSafariFanClubText02::
	.string "{JPN}あの トレーナーは {POKEBLOCK}づかいが うまい。\nあの ときは {STR_VAR_2}を つかって いましたね。$"

gTVSafariFanClubText03::
	.string "{JPN}あの トレーナーは {POKEBLOCK}を ひとつも\nつかいません でした! ひとつもです!\pまさに たつじんですね。$"

gTVSafariFanClubText04::
	.string "{JPN}レポーター: そうなんですか?\p{STR_VAR_1}さんは たいした サファリの\nたつじんの ようですね!\pガイド: また きて その うでまえを\nみせて ほしい ものです。$"

gTVSafariFanClubText05::
	.string "{JPN}ガイド: みなさん あまり うまく\nいって いない ようです。\pとくに {STR_VAR_1}さんは ひどかった。\pさきほども ポケモンを {STR_VAR_2}ひきしか\nつかまえられません でした。$"

gTVSafariFanClubText06::
	.string "{JPN}ガイド: みなさん あまり うまく\nいって いない ようです。\pとくに {STR_VAR_1}さんは ひどかった。\pさきほども ポケモンを 1ぴきも\nつかまえられません でした!$"

gTVSafariFanClubText07::
	.string "{JPN}あの トレーナーは {POKEBLOCK}を つかいます。\nあの ときは {STR_VAR_2}でしたね。\pでも もうすこし じょうずに なって\nほしい ものです。$"

gTVSafariFanClubText08::
	.string "{JPN}あの ときは まったく つかって いなかった\n{POKEBLOCK}を つかえば もっと うまく\lいくと おもうのですが。$"

gTVSafariFanClubText09::
	.string "{JPN}レポーター: そうなんですか?\p{STR_VAR_1}さんは まだまだ サファリの\nけいけんが ひつような ようですね。\pガイド: なんども きて こつを つかんで\nほしい ものです。$"

gTVSafariFanClubText10::
	.string "{JPN}レポーター: まったくです!\nちょうせん する ことが たいせつですね!\pみなさんも サファリに きて\nちょうせん して みて ください!\pそれでは また つぎかい!$"

ContestLiveUpdates_Text_Intro::
	.string "{JPN}「ポケモンコンテスト じっきょうちゅうけい!」\pしかい: ごらん いただき ありがとう ございます!\pおわった ばかりの {STR_VAR_1}の かいじょうから\nおおくり して います。\pかいじょうは まだ かえろうと しない\nおきゃくさんで いっぱいです。\pかんきゃく: {STR_VAR_2}!\pかんきゃく: {STR_VAR_3}!\pしかい: いま おききの とおり コンテストで\nゆうしょう したのは {STR_VAR_3}さんの\lポケモン {STR_VAR_2}です。\pかんきゃく: {STR_VAR_2}!\nさいこう!\pかんきゃく: {STR_VAR_3}さん!\nやったね!\pしかい: ファンの みなさんに この コンテストの\nかんそうを きいて みましょう。$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "{JPN}かんきゃく: {STR_VAR_2}は いちじしんさも\nにじしんさも トップでした!\pあの {STR_VAR_2}は これからも かちつづけるわ!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "{JPN}かんきゃく: {STR_VAR_2}は いちじしんさでは\nふるいません でしたが にじしんさで\lいっきに まくりました!\pあの {STR_VAR_2}の きせきの ぎゃくてん!\nすごかった!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "{JPN}かんきゃく: {STR_VAR_2}は いちじしんさも\nにじしんさも さいごまで ちからを\lたもって いました。\p{STR_VAR_3}さんと {STR_VAR_2}は\nただものでは ありませんね!$"

ContestLiveUpdates_Text_BetterRound1::
	.string "{JPN}かんきゃく: {STR_VAR_1}と いう てんでは\nあの {STR_VAR_2}は ぴかいちでした。\pでも つぎは もっと いい アピールを\nして ほしい ですね。$"

ContestLiveUpdates_Text_GotNervous::
	.string "{JPN}かんきゃく: {STR_VAR_2}が きんちょう した とき\nおもわず こえを だして\lおうえん して しまいました。\pあの {STR_VAR_2}に いいたい。\n「おめでとう!」$"

ContestLiveUpdates_Text_StartledFoes::
	.string "{JPN}かんきゃく: あの {STR_VAR_2}の アピールには\nわたしも おどろきました!\p{STR_VAR_2} すばらしかった!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "{JPN}かんきゃく: あの {STR_VAR_2}の れんぞくアピールは\nみごとでした!\pこころの そこから しびれました!$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "{JPN}かんきゃく: ゆうしょう した {STR_VAR_2}の\nアピールに むねが たかなりました!$"

ContestLiveUpdates_Text_WasCool::
	.string "{JPN}{STR_VAR_2}!\nかっこよかった!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{JPN}{STR_VAR_2}!\nうつくしかった!$"

ContestLiveUpdates_Text_WasCute::
	.string "{JPN}{STR_VAR_2}!\nかわいかった!$"

ContestLiveUpdates_Text_WasSmart::
	.string "{JPN}{STR_VAR_2}!\nかしこかった!$"

ContestLiveUpdates_Text_WasTough::
	.string "{JPN}{STR_VAR_2}!\nたくましかった!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "{JPN}かんきゃく: ゆうしょう した {STR_VAR_2}の\nアピールに いまでも むねが たかなります!$"

ContestLiveUpdates_Text_VeryCool::
	.string "{JPN}{STR_VAR_2}!\nかっこよさで きみの うえは いない!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{JPN}{STR_VAR_2}!\nいちばん うつくしい!$"

ContestLiveUpdates_Text_VeryCute::
	.string "{JPN}{STR_VAR_2}!\nだれよりも かわいい!$"

ContestLiveUpdates_Text_VerySmart::
	.string "{JPN}{STR_VAR_2}!\nかしこさなら いちばん!$"

ContestLiveUpdates_Text_VeryTough::
	.string "{JPN}{STR_VAR_2}!\nたくましさなら だれにも まけない!$"

ContestLiveUpdates_Text_TookBreak::
	.string "{JPN}かんきゃく: {STR_VAR_2}が アピールを\nやすんで いる ときでさえ めを\lはなせません でした。\pあの {STR_VAR_2}に みりょう されました。$"

ContestLiveUpdates_Text_GotStartled::
	.string "{JPN}かんきゃく: {STR_VAR_2}が ほかの ポケモンの\nアピールに おどろいた とき\lなきそうに なりました。\p{STR_VAR_2} よく たえた!\nよく やった!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "{JPN}かんきゃく: ああ…\nあの {STR_VAR_2}の {STR_VAR_3}!\l{STR_VAR_2}の {STR_VAR_3}!\l{STR_VAR_2}の {STR_VAR_3}!\lどうして あんなに すばらしいの?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "{JPN}しかい: と いう わけです。ここは\n{STR_VAR_1}の ファンで いっぱいですね!\pそれと もう ひとつ {STR_VAR_2}さんの\n{STR_VAR_3}と いう ポケモンも\lめを ひきました。\p{STR_VAR_2}さんの {STR_VAR_3}…$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "{JPN}きんちょうの あまり にじしんさで アピールを\nひとつも できません でした。\pつぎは この {STR_VAR_1}に せめて ひとつは\nアピールを して ほしい ものです。$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "{JPN}いちじしんさも にじしんさも\nさいかいでした。\p{STR_VAR_1}さんには この {STR_VAR_2}を\nそだてなおして ぶっちぎりの さいかいと いう\lはじを すすいで ほしい ものです。$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "{JPN}かんきゃくの もりあがりを いかした\nアピールを する ことが\lできません でした。\p{STR_VAR_1}さんには つぎこそ かんきゃくの ようすを\nよみとり もりあがりを さいこうちょうに\lして ほしい ものです。$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "{JPN}いちじしんさでは 1いだったのに\nにじしんさの アピールが\lかみあいません でした。\pくつじょくてきな ぎゃくてんまけを\nきっして しまいました。\p{STR_VAR_1}さんは いまごろ もっと こうかてきな\nアピールを けんきゅう して いる ことでしょう。$"

ContestLiveUpdates_Text_NeverExciting::
	.string "{JPN}にじしんさの アピールでは かんきゃくが\nまったく もりあがりません でした。\pほかの ポケモンを きに するのを やめて\nかんきゃくに むけた アピールを\lおぼえて ほしい ものです。$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "{JPN}{STR_VAR_1}さんの {STR_VAR_2}に\nわずかな さで やぶれました。\pしょうりまで あと ひといきで とどかないのは\nむねの いたむ ことでしょう。\p{STR_VAR_3}さんが この けっかに ないて いても\nおどろきません。$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "{JPN}おなじ アピールを くりかえして\nしんさいんを がっかり させました。\pどの コンテストでも ゆるされない ミスであり\nその だいしょうを はらいました。\p{STR_VAR_1}さんは この ふがいない けっかを\nはんせい すべきでしょう。$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{JPN}{STR_VAR_1}さんは けんめいに\nがんばりましたが…\pすべては みずのあわ さいかいに おわりました。\p{STR_VAR_1}さんには この まけから まなび\nつぎに いかして ほしい ものです。$"

ContestLiveUpdates_Text_Outro::
	.string "{JPN}さいごは いつもの ように ゆうしょうしゃへの\nおおくる ことばで しめましょう。\pこんかいは {STR_VAR_1}さんと\n{STR_VAR_2}です!\pしかい: みなさん いいですか?\nせーの!\pかんきゃく: {STR_VAR_1}さん! {STR_VAR_2}!\nおめでとう!\lコンテストの ゆうしょうしゃです!$"

gTVPokemonBattleUpdateText00::
	.string "{JPN}「ポケモンバトル そくほう!」\pとどいたばかりの ポケモンバトルの けっかを\nおとどけ します!$"

gTVPokemonBattleUpdateText01::
	.string "{JPN}トレーナーの {STR_VAR_1}さんと\n{STR_VAR_2}さんが {STR_VAR_3}バトルで\lたいせん しました。\pこの しょうぶは {STR_VAR_1}さんの\nしょうりに おわりました!$"

gTVPokemonBattleUpdateText02::
	.string "{JPN}この たたかいでは {STR_VAR_1}さんの\n{STR_VAR_2}が {STR_VAR_3}で\lおおあばれ しました!$"

gTVPokemonBattleUpdateText03::
	.string "{JPN}{STR_VAR_1}さんの {STR_VAR_2}が ふるわなかったのが\nいたかったですね。$"

gTVPokemonBattleUpdateText04::
	.string "{JPN}しょうり おめでとう ございます\n{STR_VAR_1}さん!\pやぶれた {STR_VAR_2}さんには\nつぎこそ いい けっかを!\pいじょう「ポケモンバトル そくほう!」\nでした!$"

gTVPokemonBattleUpdateText05::
	.string "{JPN}トレーナーの {STR_VAR_1}さんチームと {STR_VAR_2}さん\nチームが マルチバトルで たいせん しました。\pこの しょうぶは {STR_VAR_1}さんチームの\nしょうりに おわりました。$"

gTVPokemonBattleUpdateText06::
	.string "{JPN}この たたかいでは {STR_VAR_1}さんチームの\n{STR_VAR_2}が {STR_VAR_3}で\lおおあばれ しました。$"

gTVPokemonBattleUpdateText07::
	.string "{JPN}{STR_VAR_2}さんチームの {STR_VAR_3}が\nふるわなかったのが いたかったですね。\pチームの しょうり おめでとう ございます\n{STR_VAR_1}さん!\pやぶれた {STR_VAR_2}さんチームには\nつぎこそ いい けっかを!\pいじょう「ポケモンバトル そくほう!」\nでした!$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "{JPN}ヒトミ: あっ! こんな ところで つよそうな\nトレーナーを みつけました!\pさあ カメラを まわして!\nインタビュー しましょう。$"

GabbyAndTy_Text_GabbyIntro:
	.string "{JPN}ヒトミ: あっ! {PLAYER}さん! こんにちは!\nこのまえの こと おぼえて いますか?\pどれだけ つよく なったか みせて\nくれますか? さあ インタビューです!$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "{JPN}ヒトミ: わたしの めに くるいは なかった!\nおどろくべき トレーナーを みつけました!$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "{JPN}ヒトミ: すごい! すごい!\nあなたは いったい だれ?!\pみつけた ときから ただものでは ないと\nわかって いました!\pああ せつめい させて ください。わたしたちは\nあちこちを まわって いろいろな トレーナーに\lインタビューを して いるんです。\pすこし おじかんを いただいて\nインタビュー させて もらえませんか?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "{JPN}ヒトミ: 「{STR_VAR_1}!」\pおぼえて いますか? まえの バトルの\nしめの ひとことですよ。\pそういう ことは ぜったいに わすれないんです!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "{JPN}まえの バトルでは かまえる まもなく\nたたきのめされました…\pそれは ともかく どうですか?\nまた インタビュー させて もらえますか?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "{JPN}まえの バトルでは わたしたちに\nモンスターボールを なげません でしたか?\pおどろきました! だから みんなに\nはなして まわったんですよ!\pそれは ともかく どうですか?\nまた インタビュー させて もらえますか?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "{JPN}まえの バトルでは どうぐの つかいかたで\nみごとに やられました。\pそれは ともかく どうですか?\nまた インタビュー させて もらえますか?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "{JPN}まえの バトルでは わたしたちも\nなんとか かっこうが つきました。\pそれは ともかく どうですか?\nまた インタビュー させて もらえますか?$"

GabbyAndTy_Text_InterviewAgain:
	.string "{JPN}それは ともかく どうですか?\nまた インタビュー させて もらえますか?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "{JPN}いいんですか?\nありがとう ございます!\pでは いまの バトルの きもちを\nはなして ください。ただし みじかく\lびしっと おねがいします!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "{JPN}ヒトミ: うんうん!\nそれこそ かんぺきな しめの ひとこと!\pこれは すばらしい ばんぐみに\nなりそうな きが します。\pテレビで ほうそう されるかも しれないので\nぜひ さがして みて くださいね!\pそれでは!\nまた おあい しましょう!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "{JPN}ヒトミ: そんな…\pわかりました でも あきらめませんよ!\nまた さがしに きますからね!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "{JPN}ヒトミ: また さがしに\nきますからね!$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "{JPN}ヒトミ: どこかに ポケモンを たくさん もった\nつよい トレーナーは いないかしら?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "{JPN}ヒトミ: わあ たいした ものです!\pまえの バトルから ずいぶん\nつよく なりましたね。\pあなたを イケてる トレーナーだと みぬいた\nわたしたちの めに くるいは なかった!\pそれは ともかく どうですか?\nこんども インタビュー させて\lもらえますか?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "{JPN}ヒトミ: すごい バトルでした!\nちゃんと さつえい できて いますか?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "{JPN}カメラマン: おっと みろよ! こんな ところに\nつよそうな トレーナーが いるぜ!\lカメラは まわして るぞ!$"

GabbyAndTy_Text_TyIntro:
	.string "{JPN}カメラマン: おっと みろよ!\nおぼえて るぜ!\pこの バトルは ぜんぶ この カメラに\nおさめて やるからな!$"

GabbyAndTy_Text_TyPostBattle:
	.string "{JPN}カメラマン: たいした ものだ!\nさいこうの えいぞうが とれたぜ!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "{JPN}カメラマン: ポケモンは その 1ぴきだけ\nなのかい?\pもっと いれば いい えいぞうに\nなるんだがな…$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "{JPN}カメラマン: イケてる トレーナーを みつけたぜ。\nこいつは おおスクープだぜ!$"

GabbyAndTy_Text_TyDefeat:
	.string "{JPN}カメラマン: ああ ばっちりだ。\nバトルは ぜんぶ カメラに おさめたぜ。$"

gTVInSearchOfTrainersText00::
	.string "{JPN}トレーナーを もとめて…\pヒトミ: こんにちは! きょうは {STR_VAR_1}の\nちかくに きて います。\pこれから のびて くる あたらしい さいのうを\nさがして いるんです。\pきょう レンズを むけたのは\nトレーナーの {PLAYER}さんです。\pこの トレーナーには なにか きに なる\nものが ありました。$"

gTVInSearchOfTrainersText01::
	.string "{JPN}{PLAYER}さんとは まえにも たたかいましたが\nあの ころより あきらかに うでを あげたと\lいいきれます。\pこの トレーナーを みつけた とき ただものでは\nないと わかって いました!$"

gTVInSearchOfTrainersText02::
	.string "{JPN}トレーナーの つよさを しる いちばんの\nほうほうと いえば…\pいちばん はやいのは バトルです。\nそこで ちょうさを はじめました!\p… …\pそんな わけで {PLAYER}さんと\nたたかう ことに なりました。\pあっとうてきな つよさの まえに わたしたちは\nのされて まるめられて すてられました!\p{PLAYER}さんは ようしゃなく つよい…\pここからは とりあげた トレーナーと たたかった\nかんそうを おとどけ します。$"

gTVInSearchOfTrainersText03::
	.string "{JPN}{STR_VAR_1}と {STR_VAR_3}の\nくみあわせは かみわざでした!\pはげしい たたかいの なかで {STR_VAR_1}と\n{STR_VAR_3}が おたがいを ささえあう\lその すがた…\pそれは みごとな ながめでした!\p{STR_VAR_2}は わたしたちとの バトルで\nさいごに つかわれた わざです。\p{STR_VAR_2}と いう わざこそ {STR_VAR_1}と\n{STR_VAR_3}の きずなの あかしなのです!$"

gTVInSearchOfTrainersText04::
	.string "{JPN}…この であいの けっか わたしは\nじしんを なくして しまいました。\pこうげきを ひとつも だす まもなく\nやぶれて しまったのです。\lああ… ぐすっ…\pそれでも {PLAYER}さんの バトルは\nみる かちが あります。\pじしんの ある トレーナーは ぜひ {PLAYER}さんに\nちょうせん して みて ください。$"

gTVInSearchOfTrainersText05::
	.string "{JPN}ひとつだけ いわせて ください。\nトレーナーとの バトルちゅうに モンスターボールを\lなげては いけません!\p{PLAYER}さんは たしかに つよいのですが\nきほんの ルールを わかって いません。\pテレビの まえの みなさんに おねがいです。\p{PLAYER}さんを みかけたら\nちゅういして あげて ください!$"

gTVInSearchOfTrainersText06::
	.string "{JPN}{PLAYER}さんは あいての うごきを\nよむのが とても うまい。\pどうぐを つかう タイミングが みごとに\nきまって いました!$"

gTVInSearchOfTrainersText07::
	.string "{JPN}しょうじきに いえば わたしも なかなか\nやるほうだと おもって いました。\pまけは しましたが せった バトルに\nなりましたよ。\pわたし あいてに くろうする ようでは\n{PLAYER}さんも まだまだですね!$"

gTVInSearchOfTrainersText08::
	.string "{JPN}バトルの あと {PLAYER}さんに ひとことで\nかんそうを もらいました。\pトレーナーの こたえは「{STR_VAR_1}」。\p{PLAYER}さんの ポケモン {STR_VAR_2}と\n{STR_VAR_3}…\lそして「{STR_VAR_1}」…\pうーん! ふかい! この ことばには\nふかい いみが あります!\pとうぜんですね いい トレーナーは\nいい ことを いう ものです。\pきょうは ここまで!\nつぎの ほうそうで また あいましょう!$"

ContestLadyShow_Text_Intro::
	.string "{JPN}「ポケモンコンテスト じっきょうちゅうけい!」\pしかい: ばんぐみの とちゅうですが\nごらん いただき ありがとう ございます!\pおわった ばかりの {STR_VAR_1}の\nかいじょうから ちゅうけいで\lおおくり して います!\pかんきゃく: ?!!!!\pしかい: おっと! コンテストの さんかしゃが\nこちらへ くるようです!\pテレビの まえの みなさんの ために\nとっさの インタビューを して みます!\pかんきゃく: ?!!!!\n?!!!!$"

ContestLadyShow_Text_Won::
	.string "{JPN}しかい: しつれい します!\nなまほうそうに ごきょうりょく かんしゃします!\pゆうしょう おめでとう ございます!\pきょうの みごとな しょうりの\nきめては なんですか?\pびじょ: {STR_VAR_2}と ふたりで\nきょうは ぜんりょくを だしました!\pでも コンテストまでの あいだに たくさんの\nたすけを もらわなければ ここまで\lこられません でした!\pしかい: この よろこびを つたえたい\nとくべつな かたは いますか?\lぜひ なまほうそうで どうぞ!\pびじょ: きいて いますか!\p{STR_VAR_3}! みて いる?\nやったよ!\lありがとう!$"

ContestLadyShow_Text_Lost::
	.string "{JPN}しかい: しつれい します!\nなまほうそうに ごきょうりょく かんしゃします!\pこの けっかは ざんねんでしたね。\nなにか ひとこと ありますか?\pびじょ: つらいです…\n{STR_VAR_2}と ぜんりょくで やったのに…\pささえて くれた みんなを がっかり させて\nしまった きが します。\pしかい: いいにくいのですが ポケモンの\nいろつやが すこし ものたりませんね。\pびじょ: {STR_VAR_3} ごめんね…\nつぎは きっと うまく やるから…\l…ぐすっ… うわあああん!\pかんきゃく: みたか?\nかわいそうに!\pしかい: あの… まずい…\pええと… きょうは ここまでです!\nごらん いただき ありがとう ございました!$"

ContestLadyShow_Text_LostBadly::
	.string "{JPN}しかい: しつれい します!\nなまほうそうに ごきょうりょく かんしゃします!\pコンテストは いかがでしたか?\pびじょ: なにも うまく いきません でした…\nどういう わけか {STR_VAR_2}は\lにんきが とれなくて。\pしかい: いいにくいのですが ポケモンの\nいろつやが すこし ものたりませんね。\pびじょ: … … … … … …\n…ぐすっ… うわあああん!\pかんきゃく: みたか?\nかわいそうに!\pしかい: あの… まずい…\pええと… きょうは ここまでです!\nごらん いただき ありがとう ございました!$"
