Roulette_EventScript_Table1::
	end

Roulette_EventScript_Table2::
	end

Roulette_EventScript_Play::
	special PlayRoulette
	waitstate
	end

Roulette_Text_PlayMinimumWagerIsX::
	.string "{JPN}この だいの さいてい かけきんは\n{STR_VAR_1}です。あそびますか?$"

Roulette_Text_NotEnoughCoins::
	.string "{JPN}コインが たりません。$"

Roulette_Text_SpecialRateTable::
	.string "{JPN}いまなら とくべつレートです!$"

Roulette_Text_ControlsInstruction::
	.string "{JPN}じゅうじキーで かける ばしょを きめて\nAボタンを おして ください。$"

Roulette_Text_ItsAHit::
	.string "{JPN}あたり!$"

Roulette_Text_Jackpot::
	.string "{JPN}おおあたり!$"

Roulette_Text_NothingDoing::
	.string "{JPN}はずれ!$"

Roulette_Text_YouveWonXCoins::
	.string "{JPN}{STR_VAR_1}コイン ゲット!$"

Roulette_Text_NoCoinsLeft::
	.string "{JPN}コインが なくなった…$"

Roulette_Text_KeepPlaying::
	.string "{JPN}まだ あそびますか?$"

Roulette_Text_BoardWillBeCleared::
	.string "{JPN}ルーレットの ばんめんを リセットします。$"

@ Unused
Roulette_Text_YouDontHaveACoinCase::
	.string "{JPN}コインケースを もって いません。$"

Roulette_Text_CoinCaseIsFull::
	.string "{JPN}コインケースが いっぱいです!\nコインは けいひんと こうかん できます。$"
